### ISSUE TITLE
assertComplete in TestSubscriber should be proactive about reporting the error

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-core#100]
I think `assertComplete` should delegate to `assertNoError` first. Since onComplete and onError are mutually exclusive, that would give the same information (not complete) and more (the actual error). 

Otherwise currently for the very common success scenario you have to be remember to write `.assertNoError().assertComplete()` in that specific order or else you'll just get "Not completed". 

After a change like that I could just write `.assertComplete()`.

**Comment by smaldini** [comment]
WDYT @akarnokd  ?

**Comment by akarnokd** [comment]
This is why I'm using `AssertResult` in .NET and [proposing it](https://github.com/akarnokd/RxJava/blob/1193826bc97d56c4a6a3f88b8a2ec95a186b47ec/src/main/java/io/reactivex/subscribers/TestSubscriber.java#L849) plus two other methods for RxJava 2.x as well. It is clearly telling you expect a normally terminating sequence with the given values.

**Comment by smaldini** [comment]
WDYT @rstoyanchev @sdeleuze ?
