### ISSUE TITLE
RetryWhen operator?

### ISSUE THREAD

**Issue by robertroeser** [reactor/reactor-core#1006]
Hi,

I find myself doing something like this fairly often:
.retryWhen(throwables -> throwables.flatMap(t -> Mono.delay(Duration.ofSeconds(1))))

I was wondering if there was an operator, or a plan for an operator that was 
.retryAfter(Duration.ofSeconds(1)) 
that would retry after a delay.

It would be really great if it could have a low and high mark and a step so you could do a back-off. Something like 
retryAfter(low, high, step, stepUnits)
.retryAfter(Duration.ofSeconds(2), Duration.ofSeconds(10), 500, TimeUnit.MILLISECONDS)

Thanks,
Robert

**Comment by smaldini** [comment]
Hey @robertroeser , looks like something we are evaluating in reactor-extra under
https://github.com/reactor/reactor-addons/blob/v3.1.2.RELEASE/reactor-extra/src/test/java/reactor/retry/RetryTests.java. 

Would you suggest that we promote those ?

**Comment by robertroeser** [comment]
Took a look - I think that would be super useful. I have seem people implement things like this various times in different ways. Something standard in Reactor would great.

**Comment by simonbasle** [comment]
@robertroeser it is hard to judge where to make the cut between `reactor-extra` and `reactor-core`. But considering that this already exists in `reactor-extra` (ie. 1 dependency away), would you still strongly advocate these classes should be moved to `reactor-core`?

**Comment by robertroeser** [comment]
Yeah I do - esp if when you start using reactor near a network boundary, or a database. You're going to retry a lot, and people will just do I've been doing an write something yourself - most likely because it's not obvious there is another library.

**Comment by smaldini** [comment]
We'll add the most common retry with backoff in reactor core 3.2

**Comment by simonbasle** [comment]
see #1122
