### ISSUE TITLE
Retry using DirectProcessor

### ISSUE THREAD

**Issue by tstavinoha** [reactor/reactor-core#1009]
Hi,

I'm trying to use a DirectProcessor in order to manually emit items into a flux. My use case is that events are received via a method call and I want to 'enqueue' and process them using Flux. However I've noticed that retry operator does not seem to retry anything. Is that the expected behavior for DirectProcessor?

A standard flux, created via Flux static methods, retries all calls resulting in an exception without any problems.

Here's a couple of tests proving these claims (2nd one fails):

    import org.junit.Before;
    import org.junit.Test;
    import org.junit.runner.RunWith;
    import org.mockito.Mock;
    import org.mockito.Mockito;
    import org.mockito.runners.MockitoJUnitRunner;
    import reactor.core.publisher.*;

    import java.util.function.Consumer;

    import static org.mockito.Mockito.times;

    @RunWith(MockitoJUnitRunner.class)
    public class FluxRetryTest {

        @Mock
        private Consumer<Integer> mockConsumer;

        @Before
        public void before() {
            Mockito.doThrow(new RuntimeException()).when(mockConsumer).accept(Mockito.anyInt());
        }

        @Test
        public void shouldRetryFlux() {

            Flux.just(1)
                .doOnNext(mockConsumer)
                .retry(2)
                .doOnError(System.out::println)
                .onErrorResume(e -> Flux.empty())
                .subscribe();

            Mockito.verify(mockConsumer, times(3)).accept(Mockito.anyInt());
        }

        @Test
        public void shouldRetryProcessor() throws Exception {

            DirectProcessor<Integer> processor = DirectProcessor.create();

            processor.doOnNext(mockConsumer)
                     .retry(2)
                     .doOnError(System.out::println)
                     .onErrorResume(e -> Flux.empty())
                     .subscribe();

            FluxSink<Integer> sink = processor.sink();
            sink.next(1);
            sink.complete();

    //        Thread.sleep(1000);

            Mockito.verify(mockConsumer, times(3)).accept(Mockito.anyInt());

        }
    }

What are my options in this case? Should I use some other implementation of Flux or configure the DirectProcessor in another way?

Thanks

**Comment by akarnokd** [comment]
A terminated `DirectProcessor` only emits the terminal even (`onComplete` in this case) to late subscribers, thus using `repeat` or `retry` often doesn't do much (unless you have `doOnError` or `doOnComplete` side-effect between the two).

In your specific case, you trigger the first retry via `sink.next(1)` after which the processor is resubscribed. However, you don't issue another `sink.next(x)` call thus the `doOnNext` never executes again. the `sink.complete()` then stops the whole sequence and no further interactions happen. 

Did you expect that the first `sink.next(1)` will get somehow re-executed or cached? If so, either use a cold `Flux` with some generator that can be re-run or use `ReplayProcessor` to replay events you manually put into it via the `next` and `complete` calls.

**Comment by tstavinoha** [comment]
I understand now, thank you for explaining. Closing this.
