### ISSUE TITLE
How to map flux with mono and combiner?

### ISSUE THREAD

**Issue by kamilgregorczyk** [reactor/reactor-core#1014]
It's a question

I have a very simple flux which looks like this 

``` 
Flux<Post> posts  = postRepository.findAll(); 
```
now, I'd like to map my flux with a function that takes as an input post, and outputs mono of type Long and then, a combiner which takes as an input post, and result of my mono type of Long and outputs post.

Something like this:

```
postRepository
.findAll()
.mapWithMono((post)->commentsRepository.count(post), (post, commentsCount) -> {
    post.setCount(commentsCount); 
    return post;
})
```

With streams I'd like to do  something like:

```
postRepository
.findAll()
.stream()
.map(post -> post.setCommentsCount(commentsRepository.count(post))
.collect....
```

I know that I can do .zipWith on flux but it takes a publisher not a function that will produce a publisher

Now, It's somehow possible with Mono by doing:

```
 @GetMapping("posts/{id}")
    Mono<ResponseEntity<Post>> getPost(@PathVariable String id) {
        return postRepository
                .findById(id)
                .zipWith(commentRepository.countCommentsByPostId(id), (post, commentsCount) -> {
                    post.setCommentsCount(commentsCount);
                    return post;
                })
                .map(ResponseEntity::ok)
                .defaultIfEmpty(ResponseEntity.notFound().build());
    }

```

But not with flux. Is there maybe a walkaround ?

**Comment by OlegDokuka** [comment]
Hey @kamilgregorczyk! With `Flux` you may do it in the next way: 

```
postRepository
.findAll()
.flatMap((post) -> commentsRepository.count(post).map(cnt -> {
    post.setCommentsCount(commentsCount);
    return post;
}));
```

***Note*** I highly recommend you to avoid mutation of elements in stream since `commentsRepository` may return an element from the different thread than you have executed it

Also, I recommend you to ask such a question in [gitter room](https://gitter.im/reactor/reactor) since you will get an answer much faster :)

**Comment by kamilgregorczyk** [comment]
Thank you so much for your idea! Please close it.
