### ISSUE TITLE
Thread isolated Flux with Processor onNext

### ISSUE THREAD

**Issue by lc-nyovchev** [reactor/reactor-core#1024]
I have some remote consumer interface which is defined like that:

```
public interface Consumer {
      void onMessage(Object message);
}
```

where multiple threads are calling the same consumer (which is normally not a problem as consumers don't have side effects nor concurrent resources inside to sync on)

I'd like to come up with a Flux with the 100 most recent messages that came on each thread.
Basically, if I have thread 1 hitting onMessage 100 times and thread 2 hitting onMessage 100 times, I want to have two different Flux, the first Flux containing the messages on thread 1, the second Flux having the messages on thread 2.

The reason for that is my messages coming on each of those threads are pre-grouped and is no need to group them again. 

My 'pseudo' code is like this:

 ```
int nrThreads = 2;
ExecutorService[] executors = new ExecutorService[2];
for (int i = 0; i < nrThreads; i ++){
	executors[i] = Executors.newSingleThreadExecutor(new ThreadFactoryBuilder().setNameFormat("thread-" + i).build());
}

???Processor<Integer> emitterProcessor = ???Processor.create();
emitterProcessor
.buffer(100)
.subscribe((integers) -> {                 //maybe here I have to subscribe on something else?
       log.info("{}", integers);              //these should be either only odd numbers or only even numbers
});

for (int i = 0; i < nrThreads*2*100; i++){
	final int j = i;
	final ExecutorService executorService = executors[j%nrThreads];
	executorService.submit(() -> {
               emitterProcessor.onNext(j); //what kind of processor/sink do I need here so I get 2 separate fluxes: one odd numbers, one even numbers only?
	});
}
```

What kind of processor do I need so I get two fluxes, one flux with only odd numbers, one flux with only even numbers (without grouping)?

The real use case is listening to click stream of events and it is important finding duplicates that hit  more than a certain threshold for preventing message flood and detecting abnormal usage. As the data comes on different threads pre-grouped (if I have been getting events of group A on thread 1, I am guaranteed to never get events of group A on thread 2) there is no need to combine the Fluxes.

in this case I am dealing with the JMS standard and the JMSXGroupID property where each Consumer is effectively called by a thread in a common worker pool.

**Comment by simonbasle** [comment]
You can't. A `Processor` only represents a single `Flux`. Why not use two processors? (or `Flux.create()`, which is a good alternative to adapt listener-based asynchronous APIs)

**Comment by lc-nyovchev** [comment]
I am having trouble understanding how I can use the Flux.create?. I have a class like this:

```
public class Consumer {
        private final EmitterProcessor<Integer> emitter = EmitterProcessor.create();

         public void onConsume(Integer message){
                  Flux.create(s -> {
                       //what am I supposed to do here, who subscribes to that?, how can I use the sink at all?
                  });
         } 
}
```

There is a similar question on StackOverflow:
https://stackoverflow.com/questions/48229488/reactor-choosing-a-sink-processor/48331284#48331284

Where the only suggestion so far is to use a ThreadLocal processor, something like

```
public class Consumer {
     private final ThreadLocal<EmitterProcessor<Integer>> emitterProcessorHolder = 
          ThreadLocal.withInitial(() -> {
               return EmitterProcessor.create();
          });
     public void onCosume(Integer message){
             emitterProcessorHolder.get().onMessage(message);
     }
}
```
But I am not sure if going back to ThreadLocals is the way to go.

**Comment by simonbasle** [comment]
But in JMS / ActiveMQ it seems you can get to 1 `MessageConsumer` instance per group id, can't you?
If that's the case, it's simply a matter of registering a `Flux.create` as a `Listener` on each consumer, and subscribing to both `Flux`. Something like this:

```
Consumer groupOdd = ...;
Consumer groupEven = ...;

Flux<Integer> fluxOdd = Flux.create(sink -> groupOdd.setMessageListener(
    oddMsg -> sink.next(oddMsg))
);
Flux<Integer> fluxEven = Flux.create(sink -> groupEven.setMessageListener(
    evenMsg -> sink.next(evenMsg))
);

//take the first 100 odd messages and mix them with the first 50 even messages
Flux.merge(fluxOdd.take(100), fluxEven.take(50))
    .subscribe(System.out::println, Throwable::printStackTrace);
```

**Comment by lc-nyovchev** [comment]
Yes, I realize it's a good solution, however, I probably can't use it, in the sense that I have only one ConsumerBean instance for all the actual Consumers per a message group on a single destination (as the API I am dealing with is not the most flexible). So far we have been getting away with it cause the big ConsumerBean that dispatches to the smaller Consumers on multiple threads has, itself, no sire-effects.

So we'd probably stick with the ThreadLocal Emitter.
