### ISSUE TITLE
Flux.distinct() does use Object.hashCode() without Object.equals() which is counter-intuitive and not documented

### ISSUE THREAD

**Issue by andmoos** [reactor/reactor-core#1025]
### Expected behavior
Especially as a "default" without further arguments Flux.distinct() should use Object.hashCode() and then check Object.equals() as e.g. Java Collections normally are expected to do.

If using Object.equals() is not intended for any reason (e.g. performance) - it should at least be mentioned in the documentation that this method is solely depending on Object.hashCode(). But at least in my opinion is quite unusual (even java.util.stream.Stream.distinct() seems to honor Object.hashCode() and Object.equals()).

### Actual behavior
Without further arguments Flux.distinct() uses a Object.hashCode() key extractor then ignoring the actual Object. 

Without developer awareness unintended collisions can happen anytime, causing elements to be filtered which wouldn't when e.g. using a normal HashSet.

### Steps to reproduce
Use Flux.distinct() on a Flux with two objects returning the same integer from Object.hashCode() but not being equal according to Object.equals().

### Reactor Core version
At least 3.1.2

### JVM version (e.g. `java -version`)
Not relevant.

### OS version (e.g. `uname -a`)
Not relevant.

**Comment by simonbasle** [comment]
You are indeed correct, this shouldn't default to extracting `hashcode()`. Note that the simplest workaround for now is to call `.distinct(Functions.identity())`, but I'll change that default for 3.1.3.

**Comment by andmoos** [comment]
Thanks!
