### ISSUE TITLE
Investigate two FluxGroupByTest failing in Bamboo only

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#1028]
The tests have temporarily been ignored;
 - `twoGroupsFullAsyncFullHide()`
 - `twoGroupsFullAsync()`

Did a `git bisect` with pushes to a temporary branch in order to trigger Bamboo builds. Although it seems dubious it would influence the `FluxGroupByTest`, this is the commit that stood out:

```
4b2fd19c13beef03e4a72795b9d267d2cb9fd993 is the first bad commit
commit 4b2fd19c13beef03e4a72795b9d267d2cb9fd993
Author: Stephane Maldini <stephane.maldini@gmail.com>
Date:   Tue Jan 2 15:01:19 2018 -0800

    Fix #990 eventual premature termination issue with WorkQueueProcessor

    * reactivate (on release) TestNG task, less verbose TCK tests, per-test resources
    * Fix premature termination inconsistency on WorkQueueProcessor

:100644 100644 09674fe4fadd4f8fc0880a3d5c897f55a868bd91 228cbab12b7299a1a662665b653146ee0cfd6434 M    build.gradle
:040000 040000 78c1f41facab1da385869306cd64315c52a9f015 17db78ac444e7677f8500895b9b1422e30421b01 M    reactor-core
```

**Comment by simonbasle** [comment]
One potential candidate is the bad cleanup of schedulers and other sources of threads. During one of the failing runs, did a thread dump on test failure in Bamboo and got 90+ threads, which sounds large. A big contributor seems to be the `WorkQueueProcessor` (through its tests). Doing some cleanup might fix the situation?
[threaddumpBamboo.txt](https://github.com/reactor/reactor-core/files/1640159/threaddumpBamboo.txt)

**Comment by akarnokd** [comment]
For cases when there could be cross-test thread leaks, I keep some extra code [in comments](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/schedulers/RxThreadFactory.java#L53) so that it can append the stacktrace were workers are created that likely show which tests they were in.

**Comment by simonbasle** [comment]
@akarnokd thanks for the tip, this might prove useful in investigating this issue 👍
