### ISSUE TITLE
Data item hangs in WorkQueueProcessor buffered with time and size

### ISSUE THREAD

**Issue by TanyaGaleyev** [reactor/reactor-core#103]
Consider ```WorkQueueProcessor``` buffered with some duration and max buffer size. If data items consuming and new data element submission happen in the same time then this new data element will not be consumed. Most likely hanging element will be consumed after additional elements (at least once) are submitted.
See [gist](https://gist.github.com/TanyaGaleyev/10152bc999c8276fd4754a7b35a7d230) reproducing the problem. My setup is OS X 10.11.4, Intel Core i7 4 cores,16 GB RAM.

**Comment by smaldini** [comment]
Could you add .log() operator before buffer and the last subscriber and use log4j bridge to java logging or slf4j. BTW the Subscriber class here is equivalent to .subscribe( d - doOnNext ), it will take care of backpressure for you and default request to Long.MAX in this timer-or-size batch scenario.

**Comment by TanyaGaleyev** [comment]
Hi Stephane. Thanks for pointing out tricks =).

**Comment by smaldini** [comment]
Do we still have an issue here ?

**Comment by TanyaGaleyev** [comment]
Yes, issue is still there with 3.0.0.BUILD-SNAPSHOT.

**Comment by smaldini** [comment]
Hey do not hesitate to test the latest snapshot if you can. My run using your sample looks correct now (https://github.com/reactor/reactor-core/commit/4240e9941335d090b6bd53ad992680bbc426f83f#diff-4f70221f9f490604ee11276fc8856164R131). But there is room for improvement as discussed with @akarnokd

**Comment by TanyaGaleyev** [comment]
Hi @smaldini, issue is not reproducible anymore!
