### ISSUE TITLE
consider bufferSplit/windowSplit naming 

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1038]
Currently we have `bufferUntil(predicate, boolean)` and `windowUntil(predicate, boolean)` but an explicit naming instead of a boolean for behavior change might be better.

**Comment by simonbasle** [comment]
I don't find it too confusing, you're still buffering _until_ a condition changes, just fine tuning if the trigger element should be part of the buffer or not.

Should we wait for anybody's opinion and/or request people to voice their opinion on that (eg. from the Spring team)?

I'd prefer not to change an API signature unless there is a strong need for it (eg. two variants with ambiguous signatures for some languages, etc...), or the name is obviously inconsistent (which I don't think is the case here).

**Comment by smaldini** [comment]
Decision made, we keep the current ones.
