### ISSUE TITLE
Consider adding an order-preserving scatter-gather feature

### ISSUE THREAD

**Issue by ab-taktik** [reactor/reactor-core#1041]
Hello, 

I'd like to process items in a Flux differently based on some discriminator. I could use Flux.groupBy and then merge back the resulting transformed Fluxes, but I want to preserve the ordering of the initial Flux. To my knowledge there is no standard way of doing this? 

I didn't find any, so I came up with the following "scatterGather" implementation :

```java
public class ReactiveUtils {
   public static <I, D, O> Flux<O> scatterGather(Publisher<I> input, Function<I, D> discriminator, Function<D, Function<Flux<I>, Flux<O>>> actions, int window) {
      return Flux.concat(
            Flux.from(input)
                  .window(window)
                  .map(inputWindow -> {
                     Flux<GroupedFlux<D, IndexedItem<I>>> groupedInput = indexedFlux(inputWindow).groupBy(indexedItem -> discriminator.apply(indexedItem.getItem()));
                     return groupedInput.flatMap(groupFlux -> {
                        Flux<IndexedItem<I>> cachedGroupedFlux = groupFlux.cache();
                        Flux<Long> indexFlux = cachedGroupedFlux.map(IndexedItem::getIndex);
                        Flux<I> inputFlux = cachedGroupedFlux.map(IndexedItem::getItem).cache();
                        Flux<O> outputFlux = Flux.from(actions.apply(groupFlux.key()).apply(inputFlux));
                        return indexFlux.zipWith(outputFlux, (index, outputItem) -> new IndexedItem<>(outputItem, index));
                     })
                           .collectSortedList(Comparator.comparing(IndexedItem::getIndex))
                           .flatMapMany(Flux::fromIterable)
                           .map(IndexedItem::getItem);
                  }));
   }

   public static <I> Flux<IndexedItem<I>> indexedFlux(Flux<I> flux) {
      LongAdder longAdder = new LongAdder();
      return flux.map(item -> {
         long index = longAdder.longValue();
         longAdder.increment();
         return new IndexedItem<>(item, index);
      });
   }

   public static class IndexedItem<T> {
      private final T item;
      private final long index;

      IndexedItem(T item, long index) {
         this.item = item;
         this.index = index;
      }

      public T getItem() {
         return item;
      }

      public long getIndex() {
         return index;
      }
   }
}
```

Is this the correct way to implement this feature? Thanks for your help!

Antoine

**Comment by simonbasle** [comment]
this seems overly complicated. would `flatMapSequential` work for that use case?
something closer to this:
```
flatMapSequential(v -> actions.apply(discriminator.apply(v)))
```

note that in 3.1.3, just released, there's a `indexed()` operator that can replace your `indexedFlux` and `IndexedItem`. I am also working on an `orderedMerge` for 3.1.4 (see #1040), but not sure it would help you as it doesn't reorder whole sequences but rather peeks at two or more sources and picks the smallest value between the two peeks.

**Comment by ab-taktik** [comment]
Hello, 
flatMapSequential doesn't work for me, because my "actions" are operators that transform an input Flux into an output Flux.
For example, some items in the input flux could be saved in a DB by calling a `Flux<I> save(Flux<I> toSave)` action , while the others would be deleted by calling a `Flux<I> delete(Flux<I> toDelete)` action, but I would need to get back a Flux<I> with preserved order.

However your orderedMerge could be useful, I need to check it.

Thanks,

Antoine

**Comment by ab-taktik** [comment]
To clarify, suppose I have a class Car
```java
	public class Car {
		private String make;
		private String color;

		public String getMake() {
			return make;
		}

		public void setMake(String make) {
			this.make = make;
		}

		public String getColor() {
			return color;
		}

		public void setColor(String color) {
			this.color = color;
		}
	}
```

Suppose I have a `Flux<Car>`, with some cars with make=BMW and some cars with make=Mercedes

suppose I have two methods, to paint cars in blue or red:
```java
public Flux<Car> paintRed(Flux<Car> cars)
public Flux<Car> paintBlue(Flux<Car> cars)
```

I want to paint all BMW cars in blue and all Mercedes in red, and I want to get back a `Flux<Car>` with the same ordering as the original Flux.

So my discriminator would be 
```
Car::getMake
```

and my actions would be

```
make ->  bmwsOrMercedes ->  {
			if (make.equals("BMW")) {
                                 return paintBlue(bmwsOrMercedes);
                        } else {
                                 return paintRed(bmwsOrMercedes);
                        }
		};
```

**Comment by simonbasle** [comment]
as long as the action preserve the same `I` type, `flatMapSequential` still seems like the good solution:

```
allCars.flatMapSequential(car -> {
    if (car.getMake().equals("BMW")) {
        return paintBlue(car);
    } else {
        return paintRed(car);
    }
});
```

**Comment by ab-taktik** [comment]
Notice that `paintBlue` and `paintRed` take a Flux in parameter, not an individual `Car`

**Comment by simonbasle** [comment]
`mergeOrdered` cannot work with `groupBy` nor have a `flatMap`-equivalent: it needs all the sources upfront (as a vararg). Unless you know the possible groups in advance? (in which case you could represent each group exhaustively as a `Flux<Car>` that uses eg. a `filter` on the `carSource`?)

If you can't adapt the `actions`, how about using `Mono.just` to make the `actions` work with `flatMapSequential`? Like this:

```
allCars.flatMapSequential(car -> {
    if (car.getMake().equals("BMW")) {
        return paintBlue(Mono.just(car));
    } else {
        return paintRed(Mono.just(car));
    }
});
```

Still better than resorting to `collectSortedList`, `groupBy` and `cache` IMHO.

**Comment by ab-taktik** [comment]
In my case, the paintBlue() and paintRed() method internally buffer() the input flux to batch-process the cars, which is much more efficient than calling the paint methods one car at a time with `paint{Red,Blue}(Mono.just(car))`

So I really can't do as you suggest.

**Comment by simonbasle** [comment]
mmh I see. I might have found a way to make it work with the upcoming `mergeOrdered`:

```java
	private Function<String, String> discriminator = car -> car.substring(0, car.indexOf('_'));

	private Function<String, Function<Flux<Tuple2<Long, String>>, Flux<Tuple2<Long, String>>>> actions = make -> {
		switch (make) {
				case "BMW":
					return bmws -> bmws.map(indexedCar -> Tuples.of(indexedCar.getT1(), indexedCar.getT2() + "_blue"));
				case "LADA":
					return ladas -> ladas.map(indexedCar -> Tuples.of(indexedCar.getT1(), indexedCar.getT2() + "_grey"));
				default:
					return otherMakes -> otherMakes.map(indexedCar -> Tuples.of(indexedCar.getT1(), indexedCar.getT2() + "_red"));
			}
	};

	@Test
	public void test() {
		@SuppressWarnings("unchecked")
		final Mono<Flux<Tuple2<Long, String>>[]> arrayMono =
				Flux.just("BMW_1", "BMW_2", "AUDI_1", "BMW_3", "AUDI_2", "AUDI_3", "LADA_1", "BMW_4")
				    .index()
				    .groupBy(indexedCar -> discriminator.apply(indexedCar.getT2()))
				    .map(carGroup -> actions.apply(carGroup.key()).apply(carGroup))
				    .collectList()
				    .map(l -> l.toArray(new Flux[l.size()]));

		Flux<String> reordered =
				arrayMono.flatMapMany(array -> Flux.mergeOrdered(Comparator.comparing(
						Tuple2::getT1), array))
				.map(Tuple2::getT2);

		StepVerifier.create(reordered)
		            .expectNext("BMW_1_blue", "BMW_2_blue", "AUDI_1_red", "BMW_3_blue", "AUDI_2_red", "AUDI_3_red", "LADA_1_grey", "BMW_4_blue")
		            .verifyComplete();
	}
```

**Comment by ab-taktik** [comment]
Yes, the index leaks into the actions, that's why I have to do the ugly tricks with map(), cache(), zipWith(), to extract the index, then put it back after the action is called, before sorting.

This does't seem an exotic demand, and I find myself having to use this at several places in my code, so I was surprised that I had to do ugly code to implement it and I hoped that a better solution would exist.

**Comment by ab-taktik** [comment]
I see. I guess I'll keep my utility method for now then. Thanks for your time
