### ISSUE TITLE
3.1.x marble diagram issues

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#1043]
This issue tracks marble diagram related problems. Which can be:

 - out of date marble diagrams (the operator has changed but not the diagram)
 - wrong link used
 - operator has been renamed / aliased in 3.1.0 but the diagram hasn't been updated
 - new operator is missing a diagram
 - diagram PNG was edited but the OmniGraffle hasn't

Sub-issues can be attached to this tracking issue.

# Marble Diagram Issues

 - [ ] `then`: old operator named used on `Mono.thenEmpty(Publisher<Void>)` and `Mono.thenMany(Publisher<V>)` (#1008)
 - [ ] `windowUntil`: `windowUntil.png` should basically be the same as `windowUntilCutBefore.png` minus the operator block.
 - [ ] Missing diagrams for `concatWithValues`, `thenReturn` and `mergeOrdered`/`mergeOrderedWith`
 - [ ] `Mono.when*` and `Mono.zip*` (#1167)
 - [ ] `Flux.onErrorResume` shows `onErrorResumeWith` in its marble

**Comment by OlegDokuka** [comment]
WIP
