### ISSUE TITLE
Weird threading behaviour in reactor-core

### ISSUE THREAD

**Issue by ymolists** [reactor/reactor-core#105]
Hi All.

I am using reactor-core 2.5.0.M4. I am starting to think that this (maybe) a bug. Unless i am doing something wrong. Here is the [code](https://gist.github.com/ymolists/0781ec403563ac29d068b1219a221506) to reproduce the issue.

when i call test000 i get this output (sometimes):
```
12:38:00.105 [main] INFO Main - test000 call
12:38:00.115 [thread:0] INFO Main - groupBy ghash:1864483865 1
12:38:00.118 [thread:0] INFO Main - groupBy ghash:-1048864609 -1
12:38:00.119 [thread:0] INFO Main - groupBy ghash:1864483865 1
```

when i call test001 i get this output (consistently):
```
12:37:13.265 [main] INFO Main - test001 call
12:37:13.277 [main] INFO Main - groupBy ghash:-1048864609 -1
12:37:13.282 [thread:0] INFO Main - groupBy ghash:1864483865 1
12:37:13.283 [thread:1] INFO Main - groupBy ghash:1864483865 1
```

The question is why is the thread that runs the groupBy log non deterministic only in the first case ? Am i stumbling on undefined behavior ? the only difference between the two is the placement of the first onNext !

The thing i am trying to make sure that item sent by the main thread is executed on one thread and all the items sent by the (spawn threads ) get executed on one single thread in queue. How can i do that ?

**Comment by akarnokd** [comment]
Many operators have a so-called non-blocking queue-drain inside them. Its property is that when thread race for emission, one of them may get in and drain for all the others' values. Sometimes they switch, sometimes they don't. In your second example, you signal from the main thread before the other threads even run so the log contains the deterministic source.

**Comment by smaldini** [comment]
Answered here and on Gitter.
