### ISSUE TITLE
Add Scannable support for Schedulers/Workers

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1050]
And link the scannable inside the operators using those.

**Comment by simonbasle** [comment]
A few questions:

1. Should we try to introduce a link between `Worker` and their `PARENT` `Scheduler` where there is none (eg by storing a `WeakReference<Scheduler>` in these Worker implementations that miss a ref to their original scheduler)?
Often the `Worker` will have a reference to an `Executor` at best.
2. Introspection of the `Executor` themselves is limited. One has to recognize a particular implementation with `instanceof`, cast and call the available getters. Is that something we want to do?
