### ISSUE TITLE
Rename MonoProcessor to NextProcessor

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1053]
Currently MonoProcessor is the only Mono based processor. A recurrent case also present in Rx as in AsyncProcessor is to emit the last item as a Mono, regardless on how many times we emit to the processor (unlike current MonoProcessor that will cancel on first item).

**Comment by simonbasle** [comment]
@smaldini do we really need/want to rename the existing one? We could just add `LastProcessor` as a first step?

**Comment by smaldini** [comment]
A different route that might need alignment in FluxProcessor would be to hide all Processor impl behind static factories in Flux and MonoProcessor - I started discussing that with @rstoyanchev and also @akarnokd as he experimented with new processors.

**Comment by simonbasle** [comment]
So in preparation for adding a new flavor of processors, and with the work on #1169, the idea would be to rename the too generic `MonoProcessor` to `NextProcessor`, possibly reintroducing `MonoProcessor` as an interface (although in #1296 we are tending towards `IdentityProcessor<T>`, which NextProcessor could simply implement).

Opening a separate issue for adding the `LastProcessor` later.
