### ISSUE TITLE
Proposition : Mono.blockSingle

### ISSUE THREAD

**Issue by ab-taktik** [reactor/reactor-core#1059]
Hello, 

`Mono.block()` returns a `@Nullable` object, and `Mono.blockOptional()` is nice when you want to explicitly handle empty monos.

When your code returns a Mono that should never be empty, wouldn't is be nice to have a 
`Mono.blockSingle()` that returns a `@NonNull` object and throws a NoSuchElementException if the mono completes without value?

That way the client code doesn't have to handle empty monos explicitly, and there are no NPE warnings that you could have if you used block() without checking for null.

Thanks, 

Antoine

**Comment by simonbasle** [comment]
It was discussed in #906 and dropped in favor of `blockOptional()`, which you can use to perform the same by way of calling `blockOptional().orElseThrow(IllegalArgumentException::new)`

**Comment by ab-taktik** [comment]
Yes, I saw this issue, but it forces client code to put `orElseThrow(IllegalArgumentException::new)` everywhere, which is a bit cumbersome and put the burden of checking the state at the client side.

**Comment by simonbasle** [comment]
You could also write `myMono.single().block()` which is 3 keystrokes more than `blockSingle()`, so I don't think we really need that.

**Comment by ab-taktik** [comment]
Yeas but again `block()` returns a Nullable object so you will have NPE warnings

**Comment by simonbasle** [comment]
@smaldini what do you think? should we revisit and add yet another `block*` variant to `Mono`?

**Comment by smaldini** [comment]
@ab-taktik ```Yes, I saw this issue, but it forces client code to put orElseThrow(IllegalArgumentException::new) everywhere```

The optional should be enough, we don't really intent to provide a better blocking experience for production code, and for testing code there is StepVerifier. What is the use case for blocking "everywhere" ?

**Comment by smaldini** [comment]
That migration in itself would be an interesting topic for a post :) i don't want to be extremist about the blocking API but we are restricting ourselves on the overall API surface as much as it makes sense and try to focus on the 80% scenarios. You can build a quick helper and do : 

```
T blockingGet(Mono<T> mono){
   return mono.blockOptional().orElseThrow(NoSuchElementException::new);
}
//...
T t = myMono.as(this::blockingGet); 
```

And going beyond you could even add this as a static extension with kotlin on every mono.

**Comment by rstoyanchev** [comment]
Or adapt the `Mono` to a `DeferredResult` which can be automated in an argument resolver. In any case I don't think such a temporary measure makes a good use case for library support.

**Comment by rotilho** [comment]
Quick note: Optional.get already throw `NoSuchElementException`. So `blocOptional().get()` already give you what you want without the cumbersome `.orElseThrow(NoSuchElementException::new)`

https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#get--

**Comment by simonbasle** [comment]
@rotilho that's right, I only used `orElseThrow` in my original example because in that previous issue the user wanted something else than that default `NoSuchElementException`. Thanks for pointing that out 👍

**Comment by ab-taktik** [comment]
@rotilho That's probably the best solution without adding blockSingle(), thanks for pointing that out. 
@smaldini Yes I was planning to add such an utility method, and I understand that you don't want to add more blocking methods to the APIs. 

Thanks all for your help.
