### ISSUE TITLE
RxJava1CompletableConverter has no public methods

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-core#106]
Maybe I'm missing something obvious but `RxJava1CompletableConverter` appears unusable with all package private methods. What the [tests show](https://github.com/reactor/reactor-core/blob/0d459836c9b3621846bedc48a3b839e465167726/src/test/java/reactor/core/converter/RxJavaCompletableTests.java) for example cannot be done from any other package.

**Comment by akarnokd** [comment]
Isn't there a global converter host where you put in the classs and get a converter API back?

**Comment by rstoyanchev** [comment]
Yes I think you mean [this here](https://github.com/spring-projects/spring-reactive/blob/master/src/main/java/org/springframework/core/convert/support/ReactiveStreamsToRxJava1Converter.java) but we can't make use of the `RxJava1CompletableConverter`. The Observable and Single converters do have public methods so this looks like an oversight.

**Comment by akarnokd** [comment]
Made public via https://github.com/reactor/reactor-core/commit/13fc576e0455f5759a7b957b0e84f629256470fb .

**Comment by sdeleuze** [comment]
I made `RxJava1CompletableConverter #from()` public as well in order to be consistent across all `RxJava1*Converter` classes via https://github.com/reactor/reactor-core/commit/531ad0f1c9264e2f7037d088c64cf305c317ab2b.
