### ISSUE TITLE
Higer arities for zipWith and zip?

### ISSUE THREAD

**Issue by yilinwei** [reactor/reactor-core#1063]
Would there be any objections to adding `.zip` for higher arities than exist currently up to 9?

**Comment by simonbasle** [comment]
I don't think this is an especially good idea. The 1-8-arity variants are convenience that produce a `Tuple` variant, which is intentionally limited to an arity of 8. Past that, this is probably an indicator that you need a specialized aggregator type. This feels a little bit arbitrary, and it it (we had to make a cut at some point). Use the `zip(Iterable<Publisher<?>>, Function<Object[], R>` variant and create a meaningful object out of the array.

**Comment by yilinwei** [comment]
Sure, what about the `zipWith` function, would it be OK to mirror this up to the current tuple arity?

**Comment by smaldini** [comment]
We do pairwise operators only for the xxxWith but you can do this : 
```flux.as(f -> Flux.zip(f, f2, f3, f4, f5)).subscribe()```

**Comment by yilinwei** [comment]
@smaldini I'm not sure I understand.

I've got quite a few examples of two or three `Mono`'s which I want to combine like `m1.zipWith(m2, m3, f3)` where `f3` is a `Function3`. I don't quite see how `as` would make a difference?

**Comment by smaldini** [comment]
@yilinwei it meant to say that with as you can chain a static method like zip which already has the aliases including the one @simonbasle mentioned `zip(Iterable<Publisher<?>>, Function<Object[], R>`.

e.g. ```m1.as(m -> Mono.zip(Arrays.asList(m, m2, m3), objects -> {/*...*/})```
or   ```m1.as(m -> Mono.zip(m, m2, m3).map(t -> t.getT1() + t.getT2() + t.getT3())) ```
