### ISSUE TITLE
potential double call of onAssembly

### ISSUE THREAD

**Issue by tfeiner** [reactor/reactor-core#1064]
### Expected behavior
onAssembly is called only once

### Actual behavior
Within the method

`public final <V> Mono<V> transform(Function<? super Mono<T>, ? extends Publisher<V>> transformer)`

onAssembly() is potentially called twice, because this call

`return onAssembly(from(transformer.apply(this)));`

calls subsequently

`public static <T> Mono<T> from(Publisher<? extends T> source)`

where onAssembly(new MonoFromPublisher<>(source))

is called again, if the source is neither a Mono, nor a Flux.

Is this the intended behaviour?

### Steps to reproduce
-

### Reactor Core version
3.1.2.RELEASE

### JVM version (e.g. `java -version`)
"1.8.0_151"

**Comment by simonbasle** [comment]
This is expected, as the first `onAssembly` would allow to traceback to the call to `transform`. The `onAssembly` in `from` is also necessary for when the `from` method is called directly.
