### ISSUE TITLE
RxJava to Reactor conversion not working properly

### ISSUE THREAD

**Issue by Delorien84** [reactor/reactor-core#1069]
I have found strange behavior when going from RxJava world to Reactor world. When I set `Observable.doOnCompleted()` callback, it is not called in same case (see test case bellow).

I do not known if its a bug in reactor, rxjava or rxjava-reactive-streams. But there is possible workaround on Reactor side (see bellow).

See original bug [2708 in Spring Cloud Netflix project](https://github.com/spring-cloud/spring-cloud-netflix/issues/2708).

### Expected behavior

RxJava `Observable.doOnCompleted()` method is called in all case. Not depends if creating `Mono` or `Flux` from converted `Publisher`.

### Actual behavior

When converting RxJava Observable using [RxReactiveStreams](https://github.com/ReactiveX/RxJavaReactiveStreams) to `Publisher` and then use `Mono.from(Publisher)` to create `Mono`. After the Mono complete the original `Observable.onCompleted()` method is never called.  When I use workaround to create `Mono` via `Flux.from(Publisher).singleOrEmpty()` the `Observable.onCompleted()`  is called.

### Steps to reproduce

See following test case. _testMono_ method fail.

See also working example https://github.com/Delorien84/hystrix-observable-flux-bug/blob/master/src/test/java/cz/hystrix/bug/ObservableTest.java

```
    @Test
    public void testFlux() throws InterruptedException {
        doTest(false);
    }

    @Test
    public void testMono() throws InterruptedException {
        doTest(true);
    }

    public void doTest(boolean useMono) throws InterruptedException {
        AtomicBoolean bool = new AtomicBoolean(false);

        Observable<Integer> observable = Observable.just(1)
                .doOnCompleted(() -> bool.set(true))
                .map(i -> i * 10);

        Publisher<Integer> publisher = RxReactiveStreams.toPublisher(observable);

        Mono<Integer> mono = useMono ? Mono.from(publisher) : Flux.from(publisher).singleOrEmpty();
        int res = mono
                .map(i -> i * 10)
                .block();

        assertThat(res, is(100));
        assertTrue("OnCompleted handler has not been called", bool.get());
    }
```

I found,  that the suspect may be the `Mono.from(Publisher) `method (`MonoFromPublisher`, `reactor.core.publisher.MonoNext.NextSubscriber`). In method `reactor.core.publisher.MonoNext.NextSubscriber.onNext(T)`  there is invocation of `onComplete()` callback, that in chain cause un-subscription of `Observable` callbacks.  When real `Publisher` `Subscriber.onComplete()`,  the call is then not propagated to `Observable`.

### Reactor Core version

* reactor-core 3.1.3
* rxjava 1.3.4
* rxjava-reactive-streams 1.2.1

### JVM version (e.g. `java -version`)
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

**Comment by akarnokd** [comment]
There is no problem in any of the libraries. `Mono.fromPublisher` simply cancels the source after the first item has been received and `Observable.just()` honors such cancellation if it arrives before it would call `onComplete`. You can verify this behavior by adding `doOnUnsubscribe` somewhere after `just`:

```java
        Observable<Integer> observable = Observable.just(1)
                .doOnCompleted(() -> bool.set(true))
                .doOnUnsubscribe(() -> System.out.println("Unsubscribed!"))
                .map(i -> i * 10);
```

In contrast `singleOrEmpty()` does wait for a second item from the source so it can tell you about it in an error, but since the source completes, it produces the guaranteed single value from it.

**Comment by simonbasle** [comment]
In addition to @akarnokd explanation's, note that one can use `doFinally` on `Observable` as a method that is called in all three termination cases (onComplete, onError, cancel).

**Comment by akarnokd** [comment]
`doFinally` is not available in RxJava 1.x.

**Comment by simonbasle** [comment]
oh my bad, thanks @akarnokd

**Comment by Delorien84** [comment]
@akarnokd I accept this in situation, when Observable emit N items. But in my case, Observable emits one item, Mono subscribes one item. I would expect, that everything is ok, then `onCompleted` handler should be called. And no cancellation is done. From user, that known the Observable emit only one item, it is natural to use `Mono.from(Publisher)`. I can still use `Flux.from(Publisher).singleOrEmpty()` (at least), but for many people it is confusing.

**Comment by akarnokd** [comment]
People who know there is going to be one item use `Single`.

**Comment by Delorien84** [comment]
Ok, this makes sense. Thank you for clarification.
