### ISSUE TITLE
Flux.takeUntil() issue with lambdas

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor-core#107]
There is a conflict between both variants of `Flux.takeUntil()`, see [this code sample](https://github.com/spring-projects/spring-reactive/blob/master/src/test/java/org/springframework/web/reactive/result/method/annotation/SseIntegrationTests.java#L111) where this is not possible to use simply `.takeUntil(s -> s.endsWith("foo 1\"}"))`.

It would be nice to disambiguate these 2 variants.

**Comment by akarnokd** [comment]
Rename one of them: `takeUntilPredicate` or `takeUntilOtherPublisher`
