### ISSUE TITLE
Align completion signal behavior of Mono.zip to Flux.zip

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1071]
Currently Mono.zip wait for all source completion before completing. It was initially a way to support Publisher<Void> behavior but we since then reworked when/and to do exactly this. It seems borderline to a bug but it is a behavior change. Cc @nebhale

**Comment by nebhale** [comment]
What exactly is the change going to be?  I'd guess that completion can't happen before all the elements of `zip()` are complete as well.  Or are you instead saying that all you need is the `onNext()` signal and you reserve the right to cancel before `onComplete()`s come through?

**Comment by akarnokd** [comment]
The problem is when those completions are distributed in time. For example, one source is immediately has value/empty whereas another turns out to be empty much later.

**Comment by nebhale** [comment]
@akarnokd So you're talking about short-circuiting for empty `Mono`s?  But a `zip()` that emit's a `Tuple` will still have the same lifecycle?

**Comment by simonbasle** [comment]
@nebhale yes, short-circuiting on the first empty `Mono`. My addition to that is that `zipDelayError` should still wait for all completions (onComplete or onError). That way it won't forget about the set-aside error(s) upon encountering the first empty signal.

**Comment by nebhale** [comment]
Sounds fine to me, as every use of `zip()` that we have expects values to be returned.  We have extensive use of `switchIfEmpty()` for defaults in cases where that is necessary.  If your testing turns up any errors (because we've relied on the previous behavior), we'll consider it a bug and update our code to behave properly.
