### ISSUE TITLE
BaseSubscriber#request(n) produces request(unbound) by default

### ISSUE THREAD

**Issue by apischan** [reactor/reactor-core#1076]
### Expected behavior
Implementations of `BaseSubscriber` have to request exactly the value that passed as parameter to `BaseSubscriber#request`
### Actual behavior
Passed value to `BaseSubscriber#request` value ignores and there is `request(unbound)` instead
### Steps to reproduce
Having the test:
```
@Test
public void testBaseSubscriber() {
    Flux<Integer> integerFlux = Flux.just(1, 2, 3).log();
    CustomRequester subscriber = integerFlux
            .subscribeWith(new CustomRequester());
    subscriber.request(1L);

    System.out.println(subscriber.counter);
    System.out.println(subscriber.completed);
}
```
And the following implementation of `BaseSubscriber`
```
class CustomRequester extends BaseSubscriber<Integer> {
    int counter;
    boolean completed;
    //@Override
    //protected void hookOnSubscribe(Subscription subscription) {}
    @Override
    protected void hookOnNext(Integer value) { counter++;}
    @Override
    protected void hookOnComplete() { completed = true; }
}
```
I have the following reactor logs:
```
reactor.Flux.Array.1                     : | onSubscribe([Synchronous Fuseable] FluxArray.ArraySubscription)
reactor.Flux.Array.1                     : | request(unbounded)
reactor.Flux.Array.1                     : | onNext(1)
reactor.Flux.Array.1                     : | onNext(2)
reactor.Flux.Array.1                     : | onNext(3)
reactor.Flux.Array.1                     : | onComplete()
3
true
```
My logic is following: suppose I have "potentially infinite" `Flux` and once I ready to consume some amount of elements - I want periodically to call `subscriber.request(<some_num>)` to consume the next portion of data (suppose for custom backpressure).
I know the workaround (that is commented in my `CustomRequester`) but why it is just a workaround?
P.S. I've read the javadoc and it is quite unclear why the default parameter of `subscriber.request` is `Long.MAX_VALUE`.
### Reactor Core version
3.1.2-RELEASE
### JVM version (e.g. `java -version`)
no matter

**Comment by simonbasle** [comment]
The goal of `BaseSubscriber` is to provide an abstract subscriber implementation that takes the boilerplate of keeping track of the request and subscription out for yo and to provide sane defaults. The minimal requirement we wanted is for the user to define what to do with the data signals (`hookOnNext`).

From this perspective, what is a sane default for the initial request, upon subscription? Requesting a random amount, or not requesting at all, is not an option in our opinion: it can lead to hang by lack of request, and it should be a very conscious decision by the programmer (as she/he will know best what amount to request). Requesting an unbounded amount to start the flow and let it run to completion is a better default behavior. No hanging surprise there.

So what you describe as a workaround is actually a feature, and the correct way to use the class.

**Comment by apischan** [comment]
Let me describe some concerns about that:
1. If to look at my test the code doesn't contain something suspicious but it works another way than it looks like. There I'm requesting one element but I'm getting all.
2. Maybe I am wrong but it looks that method `subscribeWith` is needed for **custom** cases (which my case is). You saying that _minimal requirement is to implement `hookOnNext`_. But exactly this case looks even better with regular `subscribe(Consumer<T>)` method (in this case compiler forces us to implement `accept` which is analogue of `hookOnNext` but in case of `BaseSubscriber` compiler doesn't force us to implement anything).
So back to custom cases. If I want to react on next event some custom way - then I have very custom logic and I want to do the requests custom way as well. I cannot invent any case when `BaseSubsriber` can do something that cannot give us regular `subscribe` methods (in case if we have default behavior of `hookOnSubscribe`).

**Comment by simonbasle** [comment]
Don't use `BaseSubscriber` for tests, use `StepVerifier.create(youFluxGoesThere, 0)`.

**Comment by apischan** [comment]
Nothing to say... ¯\_(ツ)_/¯

**Comment by simonbasle** [comment]
wrt to your "`subscribe(lambdas...)` can do anything `BaseSubscriber` does" comment: how would you solve the following scenario with the lambda based version: initial request of 0, request 1-by-1 on each `onNext`?

`BaseSusbcriber` was made to solve just that, because with the lambda version you need to capture an external reference to the `Subscription`:

```java
AtomicReference<Subscription> subRef = new AtomicReference<>();

myFlux.subscribe(v -> {
    doSomethingWith(v);
    subRef.get().request(1);
}, Throwable::printStackTrace(), () -> {}, sub -> subRef.set(sub)); //notice last lambda doesn't call request
```

Compare to baseSubscriber:
```java
myFlux.subscribe(new BaseSubscriber<String>() {
    public void hookOnSubscribe() { } //avoid initial request
    public void hookOnNext(String next) {
        doSomethingWith(next);
        request(1);
    }
    //error and complete default behaviors
}
```

Of course, this makes 0 sense if you don't want to manipulate the request yourself. And a bit less sense if this manual request is a one-shot occurrence in your whole application (because subclassing BaseSubscriber, as intended, lets you reuse the manual request behavior).

If you look at your code and haven't looked at the documentation and understood the correct way of using the class, then maybe it's normal that you don't see anything suspiscious in your test?


> Nothing to say... ¯_(ツ)_/¯

Really? Actually took the time out of an ongoing release to reply to you and that's how you decide to act? Great...

**Comment by simonbasle** [comment]
We could have made `hookOnSubscribe` abstract (which would have forced us to make `hookOnNext` abstract as well), but decided that providing a default that is equivalent to calling `.subscribe()` was more coherent.

We expected people to at least be able to read the javadoc:

```
/**
 * A simple base class for a {@link Subscriber} implementation that lets the user
 * perform a {@link #request(long)} and {@link #cancel()} on it directly. As the targeted
 * use case is to manually handle requests, the {@link #hookOnSubscribe(Subscription)} and
 * {@link #hookOnNext(Object)} hooks are expected to be implemented, but they nonetheless
 * default to an unbounded request at subscription time.
 * <p>
```

`¯\_(ツ)_/¯`

**Comment by apischan** [comment]
About the first comment: as I said if we don't have implemented `hookOnSubscribe` `BaseSubscriber` don't give us more flexibility comparing to `subscribe(lambdas...)`. And as javadoc says in the second comment "_lets the user perform a {@link #request(long)} and {@link #cancel()} on it directly_ " but by default it doesn't. It behaving by it's own.
About the second comment: here is the same story as in #1033. As @Kindrat said "_you can't just cover with documentation some unexpected or wrong behavior_ (c)"

I understand your position and respect it.
Thank you for your support and contribution to Reactor. Have a good release :)

**Comment by simonbasle** [comment]
And what dictates that this is "wrong behavior"? This class does what it advertises on the package.

The `request(1)` is actually called, *after* the initial `request(Long.MAX_VALUE)`. So by the time this happens, source has been drained and emitted `onComplete()`, at which point requests MUST be ignored:
 - Rule [2.4 of the `Subscriber` specification](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.2/README.md#2-subscriber-code)
 - Rule [3.6 of the `Subscription` specification](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.2/README.md#3-subscription-code)

The `Flux.just(...)` is synchronously drained, so the `log` never sees the `request(1)` because it happens on an already cancelled subscription.

To convince yourself that the `request` is called, make the source publish on another thread:

```java
	@Test
	public void testBaseSubscriberAsync() {
		Flux<Integer> integerFlux = Flux.just(1, 2, 3)
		                                .publishOn(Schedulers.elastic())
		                                .log();
		CustomRequester subscriber = integerFlux
				.subscribeWith(new CustomRequester());
		subscriber.request(1L);

		//of course this is now asynchronous and thus data can be delayed, yielding 0/false
		System.out.println(subscriber.counter);
		System.out.println(subscriber.completed);
	}
```
```
13:28:05.734 [main] INFO  reactor.Flux.PublishOn.1 - | onSubscribe([Fuseable] FluxPublishOn.PublishOnSubscriber)
13:28:05.739 [main] INFO  reactor.Flux.PublishOn.1 - | request(unbounded)
13:28:05.742 [main] INFO  reactor.Flux.PublishOn.1 - | request(1)
0
false
13:28:05.742 [elastic-2] INFO  reactor.Flux.PublishOn.1 - | onNext(1)
13:28:05.742 [elastic-2] INFO  reactor.Flux.PublishOn.1 - | onNext(2)
13:28:05.742 [elastic-2] INFO  reactor.Flux.PublishOn.1 - | onNext(3)
13:28:05.742 [elastic-2] INFO  reactor.Flux.PublishOn.1 - | onComplete()
```
And if you don't make it fully asynchronous but look at the counters before the `request(1)`:
```
	@Test
	public void testBaseSubscriberSyncCounterBeforeRequest() {
		Flux<Integer> integerFlux = Flux.just(1, 2, 3)
		                                .log();
		CustomRequester subscriber = integerFlux
				.subscribeWith(new CustomRequester());

		//by that point, initial request and draing done synchronously, counters already at 3/true
		System.out.println(subscriber.counter);
		System.out.println(subscriber.completed);

		subscriber.request(1L);
	}
```
```
13:28:24.879 [main] INFO  reactor.Flux.Array.1 - | onSubscribe([Synchronous Fuseable] FluxArray.ArraySubscription)
13:28:24.886 [main] INFO  reactor.Flux.Array.1 - | request(unbounded)
13:28:24.887 [main] INFO  reactor.Flux.Array.1 - | onNext(1)
13:28:24.887 [main] INFO  reactor.Flux.Array.1 - | onNext(2)
13:28:24.887 [main] INFO  reactor.Flux.Array.1 - | onNext(3)
13:28:24.888 [main] INFO  reactor.Flux.Array.1 - | onComplete()
3
true
```

**Comment by apischan** [comment]
I understand all this and I meant that this behavior rather "unexpected" rather then "wrong". The code looks that I requesting 1 element but actually I have `requestUnbound()` instead. That only one thing that I wanted to say in this issue.
Also sorry but I didn't understand what my logic violate with respect to the links on "Reactive streams specification".
I understand that nothing will be changed but I had to raise this issue.
