### ISSUE TITLE
[Feature request] Support for naming of StepVerifier scenario

### ISSUE THREAD

**Issue by mostroverkhov** [reactor/reactor-core#1077]
Raising issue as proposed by @simonbasle in chat

Consider scenario 
```java
StepVerifier.create(Flux.never())
                  .expectError()
                  .verify(Duration.ofSeconds(10));
```

### Expected behavior
It would be nice to have descriptive message for failed scenario as a whole.
Proposed change is handy when multiple scenarios are verified 
in single test method, because It is not clear which one has failed.
E.g.

> java.lang.AssertionError: **[Scenario Request-check]** VerifySubscriber timed   
out on reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain@1a38c59b

### Actual behavior

>java.lang.AssertionError: VerifySubscriber timed out on
reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain@1a38c59b

### Reactor Core version
3.1.3.RELEASE

### JVM version (e.g. `java -version`)

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**Comment by mostroverkhov** [comment]
Possible solution depends on how often name is required in practice, can be overload `StepVerifier.create(Publisher, name)`, or enhancement of `StepVerifierOptions` with `name(String)` method.

**Comment by mostroverkhov** [comment]
Looking more closely on code I found out API exists already : `StepVerifier.create(...).as("scenario error message")`, just needs to fixed. Can It be better solution @simonbasle ?

**Comment by simonbasle** [comment]
`as` only applies to the expectation *step* before it. The last step (expect complete; etc) or the verify timeout can't be described this way, so there is still a missing piece. Plus if you have several assertions (eg. two expectNext) and use as on only one, you'll see the description only if this is the one that fails.

**Comment by mostroverkhov** [comment]
@simonbasle `StepVerifier.create(...).as("scenario error message")` was an attempt to neatly capture scenario name (by hijacking description from default OnSubscribe assertion),  will use `StepVerifierOptions` instead.

So, scenario name should prefixed in
* terminal expects (`expectError` ...)
* terminal verifies (`verifyError`...)
* `verify (timeout)`

> Plus if you have several assertions (eg. two expectNext) and use as on only one, you'll see the description only if this is the one that fails.
Do you mean  set `Step` description to Scenario name, if there is no own description? Or always concatenate scenario name with own description?

**Comment by simonbasle** [comment]
probably always concatenate the scenario name if possible

**Comment by mostroverkhov** [comment]
@simonbasle Thanks for implementing this! :+1:
