### ISSUE TITLE
Flux<Integer> Flux.combineLatest(source1, source2, combinator)

### ISSUE THREAD

**Issue by felipeazv** [reactor/reactor-core#1079]
where:
source1: 2,4
source2: 1,3,5
BiFunction: (a, b) -> a + b

### Expected behavior
3, 7, 9, which represents (2+1, 4+3, 4+5)
"Build a Flux whose data are generated by the combination of the most recently published value from each of two Publisher sources."

### Actual behavior
5, 7, 9, which represents (4+1, 4+3, 4+5)
Seems to capture the latest element of the first Publisher (source1) and combining(BiFuntction) with each element of source2.

### Steps to reproduce
```java
    private static Integer min = 1;
    private static Integer max = 5;
    private static Flux<Integer> evenNumbers = Flux.range(min, max).filter(x -> x % 2 == 0);
    private static Flux<Integer> oddNumbers = Flux.range(min, max).filter(x -> x % 2 > 0);
  
   @Test
    public void testCombineLatest() {
        Flux<Integer> fluxOfIntegers = Flux.combineLatest(
                evenNumbers, 
                oddNumbers, 
                (a, b) -> a + b);

        StepVerifier.create(fluxOfIntegers)
        .expectNext(5)
        .expectNext(7)
        .expectNext(9)
        .expectComplete()
        .verify();

    }
```
### Reactor Core version
3.1.3.RELEASE

### JVM version (e.g. `java -version`)
jdk 9.0.4

**Comment by akarnokd** [comment]
As the name of the operator should imply, it combines the **latest** value of each source. If the sources are synchronous or really fast, this could mean that one or more sources will run to their completion and the operator will remember only the very last values of each. You have to interleave the source values by some means, such as having asynchronous sources with ample amount of time between items and avoid close overlapping of items of multiple sources.

**Comment by simonbasle** [comment]
It is true that `combineLatest` behaviour can be a little surprising, and the javadoc should probably make it clearer. 

The operator is made for sequences that have delays in their emissions.
As @akarnokd explained, having a source that produces really fast (like `range` or `just`) will see the first source rush through the operator, only producing combinations with the last element in that source.

The order also matters: source A is subscribed to first, then source B. But by the time the operator subscribes to source B, source A has already completed.

**Comment by madgnome** [comment]
I will update the marble diagram to make this behaviour clearer. Something like:

![image](https://user-images.githubusercontent.com/279528/40807495-cdf11e70-6567-11e8-90ab-62b7cad43b3c.png)
