### ISSUE TITLE
ExecutorScheduler is terminated after receiving RejectedExecutionException

### ISSUE THREAD

**Issue by cybuch** [reactor/reactor-core#1080]
### Expected behavior
With default rejected execution policy I expect the Scheduler to reject tasks to the caller and continue consuming tasks, after time passes and queue is not full again it should accept new tasks.

### Actual behavior
Exception terminates the [ExecutorScheduler ](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/scheduler/ExecutorScheduler.java#L66), then parts of the system that shares the Scheduler are unavailable. Also please note [the comment](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/scheduler/ExecutorScheduler.java#L60) - I can't understand what does it mean, I guess there's something missing in that statement.  

### Steps to reproduce
1. Run your app with Mono/Flux that have subscribeOn(yourExecutorScheduler).
2. Generate heavy traffic, so you'll have more tasks than you can handle - fill the bounded queue.
3. Once RejectedExecution happens the Scheduler is terminated and it's useless. 

### Reactor Core version
3.1.3 
### JVM version (e.g. `java -version`)
Oracle 1.8.144

**Comment by simonbasle** [comment]
@cybuch can you share the detail of how you create and what you use as `youExecutorScheduler` please?
That indeed sound like a bad behaviour on `ExecutorScheduler`'s part, as the `RejectedExecutionException` can mean two things: the executor is shut down, or it is temporarily out of resources. That piece of code did only consider the first case :(

**Comment by cybuch** [comment]
Sure, here we go:
```
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setThreadNamePrefix("MyExecutorThread");
        executor.setCorePoolSize(50);
        executor.setMaxPoolSize(200);
        executor.setQueueCapacity(200);
        executor.initialize();
        return Schedulers.fromExecutor(executor)
```
`ThreadPoolTaskExecutor` is Spring's class. As I've said earlier it happens under heavy load, but once that happens Scheduler is useless. 
You're right - first it happens when scheduler is out of resources, but then it never restores and later exceptions are `RejectedExectionException: Scheduler is unavailable`

**Comment by simonbasle** [comment]
Yup. I have a proposed change at #1082.

On a side note, this Spring class actually disguises an `ExecutorService` as a plainer `Executor`. You might want to consider [`ThreadPoolExecutorFactoryBean`](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/scheduling/concurrent/ThreadPoolExecutorFactoryBean.html) and you could then wrap it using `Schedulers.fromExecutorService` (which doesn't have the terminating issue).

`ExecutorService`s are far better citizens in Reactor compared to `Executor`s.
