### ISSUE TITLE
NPE in FluxReplay SizeBoundReplayBuffer.add

### ISSUE THREAD

**Issue by twoseat** [reactor/reactor-core#1081]
The java client has an [open issue](https://github.com/cloudfoundry/cf-java-client/issues/855) that I think is an issue in reactor. The user sees an NPE during authentication:
```
java.lang.NullPointerException
at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.add(FluxReplay.java:749)
at reactor.core.publisher.ReplayProcessor.onNext(ReplayProcessor.java:434)
at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.lambda$null$2(AbstractUaaTokenProvider.java:203)
at java.util.Optional.ifPresent(Optional.java:159)
at org.cloudfoundry.reactor.tokenprovider.AbstractUaaTokenProvider.lambda$extractRefreshToken$3(AbstractUaaTokenProvider.java:191)
at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:177)
at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
```

Based on the code it looks like reactor may be tripping over generics - we're passing in a string when it looks like a `Node` is expected. Ben has the context if you need to follow up.

I'm currently chasing the user for the exact reactor version, but based on the line number I believe it's 3.1.x (though I believe the same issue will appear in 3.0).

**Comment by akarnokd** [comment]
That [line](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/FluxReplay.java#L749) should not fail as `head` is supposed to be non-`null` at all times. The only way it could become `null` if there is a concurrent call to `ReplayProcessor.onNext()`. One thread decides to move the head forward the same time another does, but the second thread will retrieve a `null` subsequent link at that point, clearing out the `head` field.

**Comment by akarnokd** [comment]
[This part](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/tokenprovider/AbstractUaaTokenProvider.java#L217) looks suspicious to me as it provides a shared processor without serialized `onNext` access.

**Comment by smaldini** [comment]
This connects to this https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/tokenprovider/AbstractUaaTokenProvider.java#L203

**Comment by nebhale** [comment]
@akarnokd If `head` is [initialized to null](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/FluxReplay.java#L727), does the first call to `head = head.get()` result in `head` becoming `null`?

**Comment by nebhale** [comment]
In addition the generic for `head = head.get()` is broken.  Unless head happens to coincidently be `Node<T>` as well (never enforced), the assignment of `head.get()` might result in a `ClassCastException`.

**Comment by smaldini** [comment]
Note: This is yet another use case for #1053 - which should be coming into 3.2

**Comment by akarnokd** [comment]
No. Since size > 0, trimming happens after the second add() call. Head is always one node behind the one that is replayed to subscribers, it can never become null.

```
// initially
// size = 0
head -> Node[null, null]

// add "value"
// size = 0
head -> Node[null, Node[value, null]]
// size != limit, increment size:
//     size = 1

// add "another"
// size = 1
head -> Node[null, Node[value, Node[another, null]]

// since size == limit, trimming happens:
head -> Node[value, Node[another, null]]
// size = 1
```

**Comment by akarnokd** [comment]
Also there no typing problem as `get()` returns a `Node`, not the value of type `T`:

[FluxReplay.java#L910](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/FluxReplay.java#L910)
```java
		static final class Node<T> extends AtomicReference<Node<T>> {

			/** */
			private static final long serialVersionUID = 3713592843205853725L;

			final T value;

			Node(@Nullable T value) {
				this.value = value;
			}
		}
```

**Comment by nebhale** [comment]
Understood.  Looks like you can close this out.

**Comment by simonbasle** [comment]
So easiest fix is probably to use the `sink()` in cf-client rather than the `Processor` directly?

**Comment by smaldini** [comment]
Yes until we have a LastProcessor that would be able to deal with MultiProducer 👍

**Comment by nebhale** [comment]
@simonbasle Way ahead of you :)  https://github.com/cloudfoundry/cf-java-client/commit/2b273e2a9fe347b972842221e1d966c90ef036d2

**Comment by simonbasle** [comment]
@nebhale is like
![](https://media.giphy.com/media/UUudet2qhpAmk/giphy.gif)
