### ISSUE TITLE
Add Flux.split

### ISSUE THREAD

**Issue by mayras** [reactor/reactor-core#1089]
I use next code to convert my Flux<List<Task>> to Flux<Task>:
flux.flatMap(Flux::fromIterable)

Maybe better to have something simpler than this code like you had in Reactor 2:

Stream.split()

or didn't  I find something in new reactor?

**Comment by akarnokd** [comment]
Why not use `flux.flatMapIterable(v -> v)`?

**Comment by mayras** [comment]
yes, better, but looks like that "v -> v" is so redundant ...

**Comment by akarnokd** [comment]
Java's type system doesn't allow having certain methods only if the type arguments conform to specific type patterns. You'd need extension methods for that, i.e., `Flux<T> flatten(this Flux<Iterable<T>> source)` available in C# and Kotlin for example. In plain Java, the remaining option is to use result selectors that often end up as identity mappings. This way, the type safety is retained at a minor inconvenience.

**Comment by smaldini** [comment]
Could be a kotlin extension tho :)

**Comment by IgorPerikov** [comment]
Hi, everyone, I'd like to grab this one
