### ISSUE TITLE
NPE in PeekFuseableConditionalSubscriber#poll

### ISSUE THREAD

**Issue by sskrla** [reactor/reactor-core#109]
When using `Flux.concatMap` I am hitting a code path that throws a NPE at [FluxPeekFuseable.java#L472](https://github.com/reactor/reactor-core/blob/0d459836c9b3621846bedc48a3b839e465167726/src/main/java/reactor/core/publisher/FluxPeekFuseable.java:472).

Earlier in that same file there is a `poll` method that includes null pointer checks.

**Comment by akarnokd** [comment]
Thanks. Fixed via https://github.com/reactor/reactor-core/commit/5792cf970568bf7d8494b024758095cfa503b5f6
