### ISSUE TITLE
Not all doFinally called when cancelling intermediate subscription

### ISSUE THREAD

**Issue by baptistemesta** [reactor/reactor-core#1090]
I was using this code:
```
                    .doOnSubscribe(subscription -> executions.put(tenant, subscription))
                    .doFinally(signal -> {
                        executions.remove(tenant);
                    })
```
When calling `executions.get(tenant).cancel()`, the doFinally is not called

I wrote a small test: (in groovy spock, my bad 😄 )
```
    def "should execute 3 finally"() {
        given:
        def holder = new Holder()
        def flux = Flux.just(1, 2, 3, 4, 5, 6).delayElements(Duration.ofSeconds(1))
                .doFinally({ signal -> holder.count.incrementAndGet() })
                .doFinally({ signal -> holder.count.incrementAndGet() })
                .doOnSubscribe({ sub -> holder.sub = sub })
                .doFinally({ signal -> holder.count.incrementAndGet() })
        when:
        flux.subscribe({ it -> println "ok: $it" }, { it -> println "ko: $it" })
        Thread.sleep(2000)
        holder.sub.cancel()

        then:
        holder.count.get() == 3

    }

    class Holder {
        AtomicLong count = new AtomicLong()
        Subscription sub
    }
```

In that case only the 2 firsts doFinally are called, I was expecting that all doFinally to be called.
Is this a bug? or just the expected behavior? or is this not the way to cancel a flux?

I think doFinally would need some javadoc update regarding the subscription cancel if its the accepted behavior.

**Comment by akarnokd** [comment]
Cancellation travels only upstream, therefore, when you access the `Subscription` at that point, the `doFinally` will not be notified as no signal travels to its direction. Put the `doOnSubscribe` last to get all 3 cancelled. Note however, that `doOnSubscribe` isn't really intended for this purpose but to side-effect the subscriptions exactly for its behavior stated above. Consider saving the `Disposable` the end `subscribe()` returns and disposing that.

**Comment by baptistemesta** [comment]
Ok thanks a lot for this clarification. Do  you want me to do a PR on the doOnSubscribe javadoc to clarify that this method is not intended for this purpose?

**Comment by baptistemesta** [comment]
BTW, `.subscribe()` returns a `Disposable`, is there a reason why it does not returns the `Subscription` directly?

**Comment by simonbasle** [comment]
Regarding your last question, we didn't want to leak the `Subscription`, and particularly the `request` method. Doing a `request` should always be a conscious choice, and we felt that exposing the subscription directly would make it easier to make mistakes like concurrent calls to `request`.

You can make a PR to the `doOnSubscribe` javadoc clearer that this is not intended for capturing the `Subscription` and calling `cancel`/`request` on it (don't forget about `Mono.doOnSubscribe` and `ParallelFlux.doOnSubscribe` too)

**Comment by akarnokd** [comment]
> this is not intended for capturing the Subscription and calling cancel/request on it

More like not recommended because such action can leave the downstream of `doOnSubscribe` hanging/ indefinitely and potentially leaking resources as there is no way to signal a terminal event to have them finish and release any resources they may have.
