### ISSUE TITLE
Add scanEval operator

### ISSUE THREAD

**Issue by yilinwei** [reactor/reactor-core#1097]
Hi,

It would be good to be able to have a function with a signature of `Mono<B> scanEval(B initial, BiFunction<B, A, Mono<B>> f)`.

**Comment by simonbasle** [comment]
I assume on `Flux`? What would be a typical use case (maybe represented as one or a few unit tests)?

**Comment by simonbasle** [comment]
I had a "scan" example based on `expand` in that linked issue, but I need to think it through further to see if it can fit the bill. Don't hesitate to play with `expand` yourself, as I'll be busy with a few other issues in the next few days.

**Comment by akarnokd** [comment]
You could achieve this with composition of existing operators:

```java
public static <A, B> Flux<B> scanAsync(Flux<A> source, 
        Callable<B> initialValue, BiFunction<B, A, Mono<B>> f) {
    return Flux.defer(() -> {
        AtomicReference<B> accumulator = new AtomicReference<>(initialValue.call());
        return Flux.just(accumulator.get())
            .concatWith(
                 source.concatMap(a ->
                     f.apply(accumulator.get(), a)
                      .doOnNext(b -> accumulator.set(b))
                 )
            );
    });
}
```

**Comment by yilinwei** [comment]
@akarnokd Indeed that's what we're doing at the moment but use of the `AtomicReference` feels wrong.

**Comment by akarnokd** [comment]
@kharole How is `nextHolderMono` implemented?

**Comment by kharole** [comment]
@akarnokd While preparing a reproduce for you i found a bug in my code ) Please disregard my comment. Sorry for disturbance. 
nextHolderMono is an external jax-ws external call wrapped in a Mono but it seems irrelevant.
