### ISSUE TITLE
Check if concatMapDelayError is aligned with flatMapDelayError

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1101]
After the demo at DevNexus we noticed a possible difference between multiple delayError behaviors. ConcatMapDelayError default to BOUNDARY when all other delayError seem to default on END. Should we revisit that and if so in time for tomorrow release @simonbasle ?

**Comment by simonbasle** [comment]
maybe for 3.2.0. this would be a behavioural change, so I'm against doing it in 3.1.x, certainly not for this week's release!

**Comment by smaldini** [comment]
Let's get that in for 3.2 then
