### ISSUE TITLE
Mark Scheduler threads to warn uses of block() inside one

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1102]
We frequently observe users invoking Mono/Flux.block calls inside WebFlux Netty thread, or inside Schedulers.parallel()/Schedulers.single().

One solution would be to mark Threads via a ThreadFactory that extend Thread via a marking subclass, so later introspection via `Thread.currentThread() instanceof NonBlockingThread` could evaluate to true and even log or throw if Mono/Flux.block is called.

Encapsulation ideas are open, but 2 constraints to be useful would be:
- to keep an external API to check for the current thread e.g. `Schedulers.isInNonBlockingThread()`
- to offer a mean for external libraries such as reactor-netty to use the same marker when creating threads: could be that NonBlockingThread is public, or Schedulers can create ThreadFactory.

**Comment by akarnokd** [comment]
This is how it's done in RxJava:

- [io/reactivex/plugins/RxJavaPlugins.java#L116](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/plugins/RxJavaPlugins.java#L116)
- [io/reactivex/plugins/RxJavaPlugins.java#L125](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/plugins/RxJavaPlugins.java#L125)
- [io/reactivex/plugins/RxJavaPlugins.java#L1162](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/plugins/RxJavaPlugins.java#L1162)
- [io/reactivex/internal/util/BlockingHelper.java](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/util/BlockingHelper.java)
- [io/reactivex/internal/schedulers/NonBlockingThread.java](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/schedulers/NonBlockingThread.java)
- [io/reactivex/internal/schedulers/RxThreadFactory.java#L74](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/schedulers/RxThreadFactory.java#L74)
- [io/reactivex/internal/schedulers/ComputationScheduler.java#L61](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/schedulers/ComputationScheduler.java#L61)

**Comment by simonbasle** [comment]
fixed by 92df4ab
