### ISSUE TITLE
Explore Kotlin coroutine as an operator extension

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1103]
Coroutine makes non blocking programming more progressive for some users. It would be great to explore a way to use an extension that offer direct support to implement a Reactor Operator as a coroutine, an alternative to `Flux.create`, `flatMap(data -> Flux.create(s -> /*...*/))` and `subscribe`.

More over an extension to `blockXxx()` as `suspend getXxx()` could be interesting for Flux/ Mono.block.

**Comment by akarnokd** [comment]
See http://akarnokd.blogspot.hu/2017/09/interoperation-between-rxjava-and.html

**Comment by sdeleuze** [comment]
Thanks for the link @akarnokd. https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/coroutines-guide-reactive.md#operators could also be interesting.

I am also wondering if we could bridge `CoroutineContext` and Reactor `Context`, see https://github.com/Kotlin/kotlinx.coroutines/issues/284.

**Comment by smaldini** [comment]
Should move discussion to reactor-addons (see #1658) if required but as of now we don't need it as a core extension
