### ISSUE TITLE
Reconsider the `LiftFunction`/`lift` operator contract

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#1105]
This contract has one problem in forcing the use of `Scannable`, both in the predicate and in the application of the `lifter` function (see `MonoLift`, `FluxLift`, ...).

Namely, it silently hides the original `Publisher` under a `Scannable.UNAVAILABLE_SCAN` if it isn't by itself `Scannable`, due to `Scannable.from(p)`.

There are still operators that have their base class non-`Scannable`, although these should probably be updated to be scannable.

Nonetheless, there are valid cases where the filter and/or the function could be applied without the `Publisher` being `Scannable`, so maybe a `BiPredicate<Scannable, Publisher>` and a `BiFunction<Scannable, Publisher<I>, Publisher<O>>` would make more sense.

**Comment by simonbasle** [comment]
For an example of a lift impacted by this, see https://github.com/spring-cloud/spring-cloud-sleuth/issues/646

**Comment by smaldini** [comment]
The problem is that Publisher can not be really used for anything there, it will be subscribed anyway in the end too.

**Comment by simonbasle** [comment]
The `xxxLift` operators and `LiftFunction` allowing a change of type from `<I>` to `<O>` doesn't make any sense to me as well.

**Comment by smaldini** [comment]
For lift it makes sense as a general util that might be used by flux.transform()/compose() - it doesn’t make sense for hooks which shouldn’t type the publisher here.

**Comment by simonbasle** [comment]
Still biting @marcingrzejszczak hard in Sleuth 😞
Lift is effectively unusable in 3.1.x, with all these operators not being actually `Scannable`. A workaround is to avoid any check on the `Scannable` input of `Operators.lift` and instead write one's own `Function<Publisher, Publisher>` that will perform the checks THEN delegate to a `Operators.lift` (which takes care of instantiating correct `Publisher` types, like `MonoLift` and `FluxLift`).

Note also that `LiftFunction` doesn't have a `ConnectableFlux` nor `GroupedFlux` implementation, which can cause `ClassCastException` when such publishers are used and decorated.

**Comment by simonbasle** [comment]
Since we cannot realistically reconsider the whole contract in 3.2.0 nor backport any such change to 3.1.x, let's come up with a battle plan to improve things, closing this issue and replacing it with multiple-level fixes (some of which *can* be backported):

 - `Operators.lift` should transparently support instances of `ConnectableFlux` and `GroupedFlux`, and return similar lift publishers
 - `Operators.lift` should have a single concern where it has two:
    - conditional transformation of `CoreSubscriber` rather than at `Publisher` level
    - `ClassCastException` avoidance: new `Publisher` must be of same interface than the original (eg. `ConnectableFlux`).
 - The later is one of the main difficulties in using `onEachOperator`/`onLastOperator` hooks directly, and could be covered automatically by the hook
 - `Publisher` wrapping should also probably transparently handle `Fuseable` Publishers 
    - (although since `Fuseable` is a marker, there shouldn't be any inner operator concrete code that performs a `instanceof Fuseable`)
    - One way of supporting fusion IF the user doesn't produce a `QueueSubscription` while the original subscriber is one would be to wrap the `CoreSubscriber` with a `QueueSubscription` that always answers `Fuseable.NONE` to `requestFusion` (see eg. [`FluxPublishMulticast.CancelMulticaster`](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/FluxPublishMulticast.java#L754))

**Comment by simonbasle** [comment]
After #1206, things now seem to be pretty stable. closing this
