### ISSUE TITLE
Rename RxJava1*Converter.from() methods?

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor-core#111]
These methods currently use the input parameter type to differentiate `Observable` -> `Publisher` from `Publisher` -> `Observable`. This is not an issue with RxJava1 but may be an issue with RxJava2 where `Observable` could be also a `Publisher` (@akarnokd please let me know if I am wrong).

While these converter are RxJava1 specific, it could be nice to use different method names in order to have the same kind of API for both `RxJava1*Converter` and `RxJava2*Converter`. Any thoughts?

**Comment by akarnokd** [comment]
In RxJava 2, `Observable` doesn't implement `Publisher` to prevent certain ambiguity situations plus the conversion requires the specification of the overflow behavior, hence the `toFlowable()` method.

Otherwise, see my PR #110 about the deeper interop with v2.

**Comment by sdeleuze** [comment]
Thanks for your feedback @akarnokd.

Even with knowing that, I think I would still be in favor of having distinct method names in our converters to avoid potential confusion with custom types, but that's up to you to decide @smaldini / @akarnokd. if we change that let's do it before RC1.

**Comment by smaldini** [comment]
We will evaluate this week if the PR #110 can make it for 3.0.0.RC1. #114 should also partially answer that issue.
