### ISSUE TITLE
Should flatMap and merge need to send cancelation signal if they were canceled?

### ISSUE THREAD

**Issue by stavalfi** [reactor/reactor-core#1113]
In my case, `createAsyncMono` returns a `Mono` which creates a socket (and listen to messages) that must be closed inside `onCancel` __only if__ `flatMap` (or `merge`) didn't pass it on. For now, the returned `Mono` will be completed and will never be canceled. I can't use `onDispose` because `onDispose` will be called even if the `flatMap` passed the socket on...

```java
public static Mono<Integer> createAsyncMono(int i) {
    return Mono.<Integer>create(sink -> {
        sink.onCancel(() ->
                System.out.println("cancel signal sent to Mono.create(" + i + ")"));
        System.out.println("start calculation inside Mono.create(" + i + ")");
        sink.success(i);
    }).subscribeOn(Schedulers.elastic());
}

public static void doWork() {
    Flux.just(1, 2)
            .flatMap(App::createAsyncMono)
            .limitRequest(1)
            .subscribe(System.out::println,
                    Throwable::printStackTrace,
                    () -> System.out.println("finish-work"));
}
```

### Expected behavior
```java
start calculation inside Mono.create(1)
start calculation inside Mono.create(2)
1
finish-work
cancel signal sent to Mono.create(2)
```
or
```java
start calculation inside Mono.create(1)
start calculation inside Mono.create(2)
2
finish-work
cancel signal sent to Mono.create(1)
```
### Actual behavior
```java
start calculation inside Mono.create(1)
1
finish-work
start calculation inside Mono.create(2)
```
### Reactor Core version
`Bismuth-SR7`
### JVM version (e.g. `java -version`)
`1.8`

**Comment by smaldini** [comment]
I think you meant to use take(1) but nevertheless I see what you mean, its a missing cancellation check at subscribe time probably, I'll investigate tomorrow.

**Comment by simonbasle** [comment]
Was the use of `limitRequest(1)` there to try and enforce only one socket creation?
The problem here I believe is the default `flatMap` concurrency, which you should reduce to 1.

Care to explain your socket creation scenario? For instance, how you came up with the idea of using `flatMap`, what is the source of the `flatMap`, any other relevant information...

**Comment by stavalfi** [comment]
@simonbasle Let's take a look at the following code:
```java
public static Flux<Socket> getMessagesFromUser() {
    return Flux.just(/* list of users.... */)
            .subscribeOn(Schedulers.elastic())
            .flatMap(user ->
                    Mono.<Socket>create(sink -> {
                        Socket socket = new Socket();
                        sink.onCancel(() -> { /* closing the socket... */});
                        // creating socket and then do: sink.next(Socket)....
                        sink.success(socket);
                    }))
            .map(socket ->
                    /* maybe do some transformation on the socket.... */ socket);
}

public static void doWork() {
    getMessagesFromUser()
            .take(1)
            .subscribe(message->System.out.println(message),Throwable::printStackTrace);
}
```
If the `flatMap` received `success` signal from the `Mono` faster then it will receive `cancel` signal from `map`, then no-one will close the sockets which were never used.

Why don't I make it synchronic? Because between the `flatMap` and the `map` I will listen to incoming messages from all the sockets. and to do that, I must use concurrency somewhere. I can expand this example a little bit more if I didn't explain it clearly.

**Comment by simonbasle** [comment]
And why you want to `take(1)` out of multiple users' `Socket`, as opposed to only doing it for 1 user right from the start? You want to "let the fastest established Socket win"?

I can see `first(Iterable)` being useful in this scenario: you'd `map` users to a `Socket`-creating `Flux` instead of `flatMapping`. You'd then collect these `Flux` into a list and pass it to `first`:

```java
return Flux.just(/* list of users.... */)
            .map(user ->
                    Mono.<Socket>create(sink -> {
                        Socket socket = new Socket();
                        sink.onCancel(() -> { /* closing the socket... */});
                        // creating socket and then do: sink.next(Socket)....
                        sink.success(socket);
                    }).subscribeOn(Schedulers.elastic()))
            .map(socket ->
                    /* maybe do some transformation on the socket.... */ socket)
            .collectList() //list of Flux<Socket>
            .flatMapMany(Flux::first) //let the first one win, others are cancelled
            ; //at this point we know it's a Mono<Socket>, but `first` returns a `Flux`. You could use `next()` if you want a Mono<Socket>
}
```

**Comment by stavalfi** [comment]
@simonbasle @smaldini 

Thanks @simonbasle. It's a nice solution :)


As soon as I will refactor my code to @simonbasle solution and see any possible problem, I will reopen this issue.
