### ISSUE TITLE
Mono.cache() loses Context

### ISSUE THREAD

**Issue by Vulcannis** [reactor/reactor-core#1114]
With the following code:
```
final String value = Mono.subscriberContext( )
	.cache( )
	.subscriberContext( Context.of( "a", "GOOD" ) )
	.map( x -> x.getOrDefault( "a", "BAD" ) )
	.block( );
System.out.println( value );
```
### Expected behavior
An output of `GOOD`.

### Actual behavior
An output of `BAD`.

### Reactor Core version
3.1.5.RELEASE

### JVM version (e.g. `java -version`)
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by smaldini** [comment]
it's due to the underlying implementation being a Processor (pub-sub). I think we should default to taking the first context found in any subscriber, wdyt @simonbasle ?

**Comment by Vulcannis** [comment]
Yeah, for most processors propagating the context doesn't make much sense. In this case though the processor is a bit of an implementation detail, and I think it makes sense to use the context that triggered the request. The caller just wants caching semantics after all.

**Comment by simonbasle** [comment]
I made it work with the `Mono#cache(Duration)` variant that is backed by an operator, with the following result:

- the `subscriberContext(Context.of(...))` is *always invoked* but when there is a cache hit it is basically ignored.
- the `Mono.subscriberContext()` will see the cached `Context` from the last cache miss.

**Comment by simonbasle** [comment]
@smaldini should we backport this?
