### ISSUE TITLE
100% CPU load on 32 bit Linux

### ISSUE THREAD

**Issue by TanyaGaleyev** [reactor/reactor-core#112]
**Environment**
VirtualBox guest: Debian 7.11 i686. Host: Mac OS X x64.
Oracle JDK 1.8.0_92.
Reactor 2.5.0.M4.
**Description**
On production we have observed that app installed on 32 bit Linux without load consumes 100% CPU. Consumption was measured using *top* utility.
I created a sample [program](https://gist.github.com/TanyaGaleyev/7eb3d8093344ca404dc31859402deb5c) which reproduces same 100% CPU consumption.
Some results from VisualVM are provided. Sampling tells us that CPU spends all time waiting using parking strategy (`Parking.waitFor`).
![screen shot 2016-07-05 at 17 31 17](https://cloud.githubusercontent.com/assets/1092664/16588180/11c4e314-42df-11e6-8d2a-ace80f1342fd.png)
![screen shot 2016-07-05 at 17 29 14](https://cloud.githubusercontent.com/assets/1092664/16588195/210d7a16-42df-11e6-982f-ebb8e78ecf9f.png)
On 64 bit Linux platform production code consumes around 10% of CPU. I did not run sample app on 64 bit yet.

**Comment by smaldini** [comment]
Hey @TanyaGaleyev can you try with latest snapshot 2.5.0.BUILD-SNAPSHOT ?

**Comment by TanyaGaleyev** [comment]
Hi @smaldini, yes with latest 2.5.0.BUILD-SNAPSHOT CPU consumption is fine (about 0%). Thanks for the fix!
I have observed that `Schedulers.newTimer` methods no more return `HashWheelTimer`. But all wait strategies are still present. And did not notice changes in `Parking` strategy. As we observed in test app `Parking` strategy eats 100% CPU on 32 bit Linux systems that makes it very similar to `BusySpin`. I think it is not expected behaviour =(.
And one more thing. In production we use Reactor 2.5.0.M4. Can you imagine some workaround to solve  100% CPU consumption on already running system without upgrade?

**Comment by TanyaGaleyev** [comment]
Hi @smaldini,
I created a same [issue](https://github.com/LMAX-Exchange/disruptor/issues/162) for disruptor. You can find a resolution there.

**Comment by smaldini** [comment]
@TanyaGaleyev we are aiming to release the first RC of 2.5 as 3.0.0.RC1 by the end of the week (ETA 15th of July) with this change. I read the discussion, very insightful, thanks a lot for this 👍 ATM we don't need and use anymore HashWheelTimer as it proved not that faster than the new `Schedulers.timer` in use contributed by @akarnokd . However there might be case than hash-wheel timer when the volume of timed tasks is huge.

**Comment by smaldini** [comment]
Can we consider it closed with the latest 3.0 stuff @TanyaGaleyev ?

**Comment by TanyaGaleyev** [comment]
Yes, starting from 2.5.0.BUILD-SNAPSHOT I cannot reproduce the issue (checked with 3.0.0.BUILD-SNAPSHOT).
