### ISSUE TITLE
GroupBy on Flux.defer() does not complete

### ISSUE THREAD

**Issue by paawak** [reactor/reactor-core#1120]
### Expected behavior
The control should come to the onComplete() block.

### Actual behavior
The control never comes to the onComplete() block. However, if we use Flux.create(), the same piece of code works fine.

### Steps to reproduce
Look at the attached file FluxDeferGroupByBug.java.
[FluxDeferGroupByBug.java.txt](https://github.com/reactor/reactor-core/files/1798134/FluxDeferGroupByBug.java.txt)

### Reactor Core version
3.1.5.RELEASE

### JVM version (e.g. `java -version`)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by akarnokd** [comment]
Please provide a code example that demonstrates your problem. Make sure you consume all the groups emitted by `groupBy`, which usually means setting the `maxConcurrency` level of `flatMap` large enough and otherwise not ignoring or dropping group `Flux`es.

**Comment by paawak** [comment]
Hi David,

I have written a simple JUnit Test that highlights this problem:

https://github.com/paawak/blog/blob/master/code/reactive-streams/reactor-core-3-demo/src/test/java/com/swayam/demo/reactive/reactor3/react/FluxDeferGroupByBug.java

If you notice, the Flux.create() test runs fine, but the same code with Flux.defer() fails.

The complete sources can be found here:

https://github.com/paawak/blog/tree/master/code/reactive-streams/reactor-core-3-demo

Thanks,
Palash.

**Comment by akarnokd** [comment]
[This is an invalid](https://github.com/paawak/blog/blob/master/code/reactive-streams/reactor-core-3-demo/src/test/java/com/swayam/demo/reactive/reactor3/react/FluxDeferGroupByBug.java#L70) `Publisher` implementation. You should use `Flux.fromArray` instead, at most`Flux.create` or `Flux.generate`.

**Comment by smaldini** [comment]
The test looks invalid can you reproduce with a Flux factory ?

**Comment by paawak** [comment]
Hi Stephane,

Can you please tell me why this test is invalid and what I am missing here?

Thanks,
Palash.

**Comment by simonbasle** [comment]
@paawak implementing a valid `Publisher` is not as simple as you might think, as you should abide by the Reactive Streams specification rules, taking concurrency, requests and a lot more into account... That's why we always recommend to use vanilla Reactor operators first, and if that's definitely not possible then use `Flux.create`.

Your `Publisher` that you wrap in `defer` is very naive in that sense. The `create` version will be protected from violating the Reactive Streams spec by the underlying create operator, but the lambda-based one won't.

Also, `Thread.sleep` inside Reactor code is a big code smell at best...

**Comment by paawak** [comment]
Thanks a lot Simon for the detailed explanation.

About the Thread.sleep, you don't serious believe that this is in
production, do you? It is just a small test-case that I wrote to
demonstrate what I believed was a bug.

Please feel free to close this issue if you are convinced the Publisher is
not valid.

Thanks,
Palash.

**Comment by simonbasle** [comment]
About the `Thread.sleep`: of course, but I thought you were likely trying to reproduce a production state where there is blocking code, which is to be avoided.
