### ISSUE TITLE
Add `accelerateTime` method to VirtualTimeScheduler

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#1128]
Relates to #783, cc @rwinch

The idea would be to have regular clock progress without having to manually call `advanceTimeXXX` methods, by triggering a regular background task that advances the virtual clock by `periodInRealTime * accelerationFactor` milliseconds. I propose a period of `10ms`, having the `accelerationFactor` expressed on the basis of `1ms`.

Calling the method twice would just change the factor, aka the amount of virtual time each task execution advances.

Calling the method with a factor of 0 would cancel the task and fall back to the mode where `avanceTimeXXX` manual invocations are needed.

Concept of what this could look like:

```java
StepVerifier.withVirtualTime(() -> Flux.interval(Duration.ofSeconds(3)).take(4))
    .accelerateTimeBy(300) //basis is 1ms, with ticks of 10ms thus each representing 3s
    .expectNextCount(4)
    .expectComplete()
    .verify(Duration.ofMillis(50)); //test should run 4 interval ticks in about 40ms
```

wdyt @smaldini ?

**Comment by simonbasle** [comment]
Let's consider a new factory method for `StepVerifier`:
```java
StepVerifier.withAcceleratedTime(300, () -> Flux.interval(Duration.ofSeconds(3)).take(4))
```

Another side is: should this be a new test `Scheduler` entirely, similar but not entirely like `VirtualTimeScheduler`? I think due to the subtleties around installing VTS and mutual exclusion of VTS tests, it would be preferable to keep that as an evolution of VTS...

**Comment by MatthewWeisCaps** [comment]
Perhaps I'm missing something, but if the goal is to have a clock progress without having to manually call advanceTimeXXX methods, is there a reason you can't drain the VTS instead? For an overly-simplified example (ignoring special cases such as unbounded infinitely generating time-based producers), something to the effect of:

```java
public static <T> Flux<T> delayedDrain(Flux<T> flux, VirtualTimeScheduler vts) {
    return Flux.empty()
            .doOnSubscribe(ignored -> vts.advanceTimeTo(Instant.ofEpochMilli(Long.MAX_VALUE)))
            .thenMany(flux);
}

@Test
public void drainVirtual() {
    // (all this setup would be handled by StepVerifier, without leaking the VTS)
    VirtualTimeScheduler vts = VirtualTimeScheduler.create();
    Supplier<Flux<Long>> supplier = () -> delayedDrain(Flux.interval(Duration.ofSeconds(3)).take(4), vts);
    StepVerifier.withVirtualTime(supplier, () -> vts, Long.MAX_VALUE)
            .expectNextCount(4)
            .expectComplete()
            .verify(Duration.ofMillis(50)); //test should run 4 interval ticks in about 40ms
}
```

This way the virtual clock always instantly advances to the next necessary time as the VTS drains (no acceleration factor required). One downside is that some StepVerifier assertions may be impacted (e.g. assertions about operator fusion), but I imagine there are work arounds.

**Comment by simonbasle** [comment]
the issue is that some operators will schedule tasks outside of the points
where the StepVerifier api allows to advance the time, so the task always
ends up scheduled in the future of the vts. background regular advancement
of the clock solves that.

**Comment by MatthewWeisCaps** [comment]
I see your point about the regular advancement clock, but I'm not sure I follow why draining the VTS wouldn't have the same effect. At the end of the day, aren't both just a means for users to sufficiently [drain the VTS queue](https://github.com/reactor/reactor-core/blob/98ecef19d98d1f77757344e5afe76bb42cc7eeb5/reactor-test/src/main/java/reactor/test/scheduler/VirtualTimeScheduler.java#L381)? If it's not too much to ask, it might help me to see an example which is solved by the former but not the latter.

**Comment by simonbasle** [comment]
This idea has never really gained any traction, closing this for now.
