### ISSUE TITLE
Flux.zip consumes Stream provided by source1 entirely.

### ISSUE THREAD

**Issue by christophstrobl** [reactor/reactor-core#113]
When using `Flux.zip` on a `Publisher` that is backed by a stream, the `zip` operation consumes the stream entirely. 

```java
Publisher<String> source = Flux.fromStream(Arrays.asList("foo", "bar").stream());

Flux<Tuple2<String, String>> target = Flux.zip(source, Flux.from(source).flatMap(val -> {

	// assume this would normally be call to a datastore eg. fetching values for a key provided.
	return Mono.fromSupplier(() -> val.toUpperCase());
}));

TestSubscriber<Tuple2<String, String>> subscriber = TestSubscriber.create();
target.subscribe(subscriber);
subscriber.await();
subscriber.assertValueCount(2);
```

Changing `source` to `Publisher<String> source = Flux.fromIterable(Arrays.asList("foo", "bar"));` everything behaves as expected.

**Comment by rstoyanchev** [comment]
I'm wondering if we need `fromStream` at all? You have to do extra work to obtain a `Stream`. Isn't easier to pass a Collection typically. Plus a `Stream` is usable only once.

**Comment by christophstrobl** [comment]
true, that was only a simple sample to show what happens. what we're trying to do is having an API like 

```java
/**
 * Get single element stored at {@literal key}.
 * 
 * @param key must not be {@literal null}.
 * @return
 */
default Mono<ByteBuffer> get(ByteBuffer key) {

	Assert.notNull(key, "Key must not be null!");
	return get(Mono.fromSupplier(() -> key)).next().map(Tuple2::getT2);
}

/**
 * Get elements one by one.
 * 
 * @param keys must not be {@literal null}.
 * @return {@link Flux} of {@link Tuple2} holding the {@literal key} to get along with the value retrieved.
 */
Flux<Tuple2<ByteBuffer, ByteBuffer>> get(Publisher<ByteBuffer> keys);
```

The thing is that we need to correlate the value returned to the key requested. That's what we use `zip` for.

```java
public Flux<Tuple2<ByteBuffer, ByteBuffer>> get(Publisher<ByteBuffer> keys) {

	return connection.execute(cmd -> {

		return Flux.zip(keys, Flux.from(keys).flatMap(key -> {
			return LettuceReactiveRedisConnection.<ByteBuffer> monoConverter()
					.convert(cmd.get(key.array()).map(ByteBuffer::wrap));
		}));
	});
}
```

Now if someone, for whatever reason, passes in a `Flux.fromStream(Arrays.asList("foo", "bar").stream())` then nothing would be retrieved. 

It might be that the overall pattern here is not idiomatic and we need to rethink our apporach and just stick to `Mono<ByteBuffer> get(ByteBuffer key)`.

**Comment by akarnokd** [comment]
The operator `zip` prefetches elements from its sources (256 by default) so it may exhaust a synchronous source before it goes to the next source. The array-based version of `zip()` allows you to configure this prefetch amount. A possible workaround is to use `source.publishOn(Schedulers.immediate(), n)` as the input to zip.

**Comment by smaldini** [comment]
An interesting issue indeed. This is a fundamental difference, as explained by @akarnokd . We could actually introduce an operator to throttle synchronous requests using `publishOn(Schedulers.immediate(), n)` like `throttleRequest(n)'. WDYT ?

**Comment by smaldini** [comment]
Ping

**Comment by christophstrobl** [comment]
sorry @smaldini got sidetracked a bit this week. I'll give the workaround a try next week. Maybe  for my purpose it might be sufficient if I just block and collect the suff in case I encounter a `FluxStream`.

**Comment by smaldini** [comment]
closing for now
