### ISSUE TITLE
CartesianProduct operator? 

### ISSUE THREAD

**Issue by IgorPerikov** [reactor/reactor-core#1132]
Recently I realised that I'm missing cartesian product operator. As I can see, the easiest way to implement this now is `flux.flatMap(t -> other.map(v -> Tuples.of(t, v)))`, but it doesn't look very neat. 

If you find it useful too, I'd like to provide implementations for this operator for both Mono and Flux

**Comment by simonbasle** [comment]
I'm not sure about it. To work well it depends on the `other` to be cold, and I feel we already have enough operators with such implicit "contracts" in the API that can be misinterpreted as "works in all cases" at first glance.

The `flatMap` based cartesian product is easy enough and can be made more "digest" by wrapping in a `compose` if you need more readability. It has the added benefit of forcing a conscious decision on the developper that implements it.

**Comment by IgorPerikov** [comment]
Haven't thought about cold and hot, can you please explain a bit more - what is gonna be wrong if second Publisher is hot? I'm just curious

**Comment by akarnokd** [comment]
It `other` is hot, you may lose or not see items when repeatedly consuming it, thus it won't be a Cartesian product. If it is cold, but not trivial (i.e., causing network access), you may end up creating a lot of traffic.

**Comment by simonbasle** [comment]
@IgorPerikov `flatMap` will re-subscribe to `other` for each incoming `flux` value. If it is hot, it might not re-emit values from the past and thus it wouldn't be a cartesian product anymore.

edit: what @akarnokd said

**Comment by IgorPerikov** [comment]
Got it! Thanks for your explanations :+1:
