### ISSUE TITLE
Better explain Tuple toList vs iterator

### ISSUE THREAD

**Issue by nnanda2016** [reactor/reactor-core#1135]
I checked the `Tuple2.java` and to me it has inconsistent APIs: The API `toList()` returns a mutable list whereas `iterator()` returns an immutable iterator.

Also, shouldn't the properties `T1`, `T2` etc in a tuple be `private`? I agree they're `final` and hence, cannot be modified outside; but I am curious to know the reason behind such a design. (not making them private).

**Comment by smaldini** [comment]
They are private, precisely package-private, which means only our code or tests should consume these fields directly. Its a general convention used in reactor-core to optimize field access and short circuit JVM synthetic accessors. As a low level library, every optimization counts for us, its certainly not a statement that would apply exactly as such for an end user application.

**Comment by simonbasle** [comment]
Answering on the `toList()` vs `iterator()` mutability standpoint (adapted from our discussion on [Gitter](https://gitter.im/reactor/reactor?at=5ab0c3f327c509a7748225e8)):

The goal is to give power to the user while maintaining `TupleN`'s own immutability.

With an `Iterator`, by definition, the `Iterable` **must** be mutable in order for the Iterator to be mutable. So `iterator()` cannot be mutable.

On the other hand, there's no such contract for `toList`. One could choose to make it immutable too, but for the sake of just maintaining the Tuple's immutability there is no need to do so: a copy list suffices.

This has the additonal benefit of letting the user decide what to do with the `List` (wrap it in `Collections.unmodifiableList`, add or remove to it, ...) without sacrificing the original invariant of "`Tuple2` is immutable". More power to the user, none of the drawbacks on the Tuple. So we didn't place the immutability restriction on the `List` returned by `toList`.

I think this should be made clearer in the javadoc of `toList()` and `iterator()`.

**Comment by simonbasle** [comment]
As @akarnokd pointed out in the PR review, the `Arrays.asList` doesn't support add or remove methods, so my heartfelt argumentation for the power of mutability is based on a false premise 😆 

Good news is, we **do** actually have consistency. I'll amend the PR to reflect the fact that the list doesn't support add and remove.
