### ISSUE TITLE
DirectProcessor and UnicastProcessor documentation outdated

### ISSUE THREAD

**Issue by codependent** [reactor/reactor-core#1149]
### Expected behavior
direct (DirectProcessor and UnicastProcessor): These processors can only push data through direct user action (calling their Sink's methods directly).
### Actual behavior
Both processors can subscribe to upstream Publishers
### Steps to reproduce
Described here: https://stackoverflow.com/questions/49536849/why-does-a-unicastprocessor-plus-connectableflux-send-previously-emitted-items-d
### Reactor Core version
3.1.5.RELEASE
### JVM version (e.g. `java -version`)
1.8

**Comment by OlegDokuka** [comment]
Will fix it this weekends.

**Comment by OlegDokuka** [comment]
@simonbasle do we need any other fixes there?

**Comment by simonbasle** [comment]
Don't think so, your PR has been merged. Unfortunately @smaldini blindly reused your initial commit message which was not super great and didn't start with "fix", preventing GitHub to detect which issue to close. I'll close manually.

**Comment by codependent** [comment]
@OlegDokuka @simonbasle having a look at the commits they only reference the javadoc, but what about the project documentation?

>direct (DirectProcessor and UnicastProcessor): **These processors can only push data through direct user action (calling their Sink's methods directly)**.

Maybe I missed the commit...

Regards!

**Comment by gdrouet** [comment]
@simonbasle @OlegDokuka I can subscribe to a `Publisher` with a `UnicastProcessor` which drains all its data. The documentation does not tell that as reported by this issue.
