### ISSUE TITLE
Avoid try catch on checked exceptions

### ISSUE THREAD

**Issue by weliff** [reactor/reactor-core#1151]
It would be interesting if the util Exceptions had a method that would receive a lambda that treats all subclasses of Exception for checked Exception and transforms into a RuntimeException.
`Flux.just("a", "b", "c").map(letter -> Exceptions.handle(() -> myMethodThrowCheckedException(letter))
         ....
`

**Comment by smaldini** [comment]
Good issue for reactor-extra but we won't get that in core for now.
