### ISSUE TITLE
Remove deprecated `Scannable#operatorName()`

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#1156]
See #1140 

- [ ] Rename all remaining `operatorName()` implementations to `stepName()`.
- [ ] Update japicmp exclusions accordingly

**Comment by simonbasle** [comment]
(Note that we could still decide to do that before 3.2.0)

**Comment by smaldini** [comment]
Yeah I think we can do that after the next milestone. It's not a heavily critical api as well.
