### ISSUE TITLE
Promote 2.5 milestones to 3.0

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#116]
A placeholder to mark the end of 2.5.0.MX process to start with 3.0.0.RC1 - ETA 15th

**Comment by smaldini** [comment]
Ok asking validation around with the new structure (javadoc : http://next.projectreactor.io/core/docs/api/) @akarnokd , @rstoyanchev, @sdeleuze, @nebhale and more, once your +1 flow away we're going to work from that base for the next coming month unless exceptional circumstance requiring changes. Of course additions are considered as usual including the current issues relative to global error handling  and context (#117).

**Comment by akarnokd** [comment]
:+1:

**Comment by sdeleuze** [comment]
I am mostly ok but I have some polishing to do before giving my +1. I will try to send a PR tonight.

**Comment by smaldini** [comment]
After much discussion online and offline http://next.projectreactor.io/core/docs/api/ has been slightly updated and Rc1 is on its way, thanks everyone !
