### ISSUE TITLE
StepVerifier.Step.then( ) and exceptions

### ISSUE THREAD

**Issue by Vulcannis** [reactor/reactor-core#1165]
Currently` StepVerifier.Step.then( )` accepts a `Runnable`, it would be nice if it could take a lambda that throws an exception. The actual implementation code seems to handle exceptions already, so it should just be a matter of type signature.

e.g. be able to write `verifier.then( () -> aFuture.get( 5, SECONDS ).doSomething( ) )` instead of wrapping it in some boilerplate to deal with the exception.

**Comment by OlegDokuka** [comment]
make sense. WDYT @smaldini @simonbasle?

**Comment by simonbasle** [comment]
what would the signature be? A new functional interface for `ThrowingRunnable`s?

**Comment by simonbasle** [comment]
There are other projects dedicated at providing this sort of features, like https://github.com/pivovarit/throwing-function
Closing this for now
