### ISSUE TITLE
Out of date marble diagrams for Mono.when* and Mono.zip *

### ISSUE THREAD

**Issue by wcong** [reactor/reactor-core#1167]
- The marble diagrams for *Mono.when** and *Mono.zip** seem all using diagram for *Mono.when*. 
- Diagrams for *Mono.when** seem not right:
   - since *Mono.when** return void, no items will pass through. 
   - The complete flag should be at last complete position, now it's at the first

This is in the latest snapshot of the docs.

**Comment by gmcelhoe** [comment]
This seems to still be incorrect -- the marble diagrams do not match the text for Mono.when at

http://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#when-java.lang.Iterable-

**Comment by simonbasle** [comment]
@gmcelhoe it seems this one was missed in the original PR. The url should be updated to replace `v3.1.3.RELEASE` with `v3.2.0.RELEASE`. If you could open a new issue compiling such problems if you find any other, and/or a PR?
