### ISSUE TITLE
Rework how we expose Processors in Reactor (simplified common contract, favor exposing Sink)

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#1169]
All concrete `FluxProcessor` implementations should be deprecated, introducing a new standard way of building these through builders exposed at the `FluxProcessor` level.

The builders entry point will bear a representative name for each specific type of processor. They will however return a downcasted instance of `FluxProcessor`.

Deprecated classes will be hidden away in a follow-up issue for 3.2.0, ~while this issue can be backported to 3.1.x.~

See #1051 for the ultimate goal with the `EventLoopProcessors`.

**Comment by simonbasle** [comment]
The `Processors` with the most "special" API are the `EventLoopProcessors`:

- `drain()`
- `awaitAndShutdown`
- `forceShutdown`
- `getAvailableCapacity`

There is also `MonoProcessor`:

 - `peek`
 - `cancel`
 - `isCancelled`

**Comment by simonbasle** [comment]
Deprecation won't be backported to 3.1.x, renaming this issue to make it about reworking the whole processor API.

**Comment by simonbasle** [comment]
Onec ommon goal is to avoid exposing the whole `Flux`/`Mono` APIs but instead offer "view" methods `asFlux()` and `asMono()`. But we are still hesitating between two possible outcomes for the simplification goal:

# Two sets of interfaces
This is explored in #1172

In this outcome, we force the user to choose between the two possible use case:
 - processor use: processor subscribes to a source and transmits to subscriber(s)
 - manual use: processor is pushed to through the sink and transmits to subscriber(s)

This is done by having two interface sets: one is just basically `Processor<T,T>` (no possibility of creating a `Sink`), the other is basically `FluxSink` (or `MonoSink`).

The concrete implementations remain unchanged, but they implement the processor-usecase interface.

The sink interface is obtained from the builders in `Processors` that specifically have a `buildSink()` method. Instances are just wrappers around the concrete `FluxProcessor`s that call their `sink()` method and forward to its methods.

## One set of interfaces
In this outcome, we'd manage to merge the `FluxSink`/`MonoSink` usage and `Processor` usage.

We'd expose a different `Processor` instance than the underlying concrete processor, because there would be a need to serialize `onNext` calls with the sink calls. **Right now concrete processors don't provide serialization guarantees against parallel use of both `onNext(T)` and `sink().next(T)`.**

Concrete sink would possibly be lazily created upon first call to one of the sink methods on the facade.

**Comment by OlegDokuka** [comment]
@simonbasle Could you please provide some example for the second option

**Comment by simonbasle** [comment]
@OlegDokuka it would probably look like this:

```java
interface SimpleFluxProcessor<T> extends Processor<T, T>, CoreSubscriber<T>, FluxSink<T> {

  Flux<T> asFlux();

  //from Processor
  onNext(T value);
  onComplete();
  onError(Throwable e);
  onSubscribe(Subscription s);
  subscribe(Subscriber s);

  //from FluxSink
  void next(T value);
  void complete();
  void error(Throwable e);
}

interface SimpleMonoProcessor<T> extends Processor<T, T>, CoreSubscriber<T>, MonoSink<T> {

  Mono<T> asMono();

  //from Processor
  onNext(T value);
  onComplete();
  onError(Throwable e);
  onSubscribe(Subscription s);
  subscribe(Subscriber s);

  //from MonoSink
  void success(T value);
  void success();
  void error(Throwable e);
}
```

The main thing is that the concrete class would be different from current eg. `EmitterProcessor`, wrapping it to serialize calls to `onNext` with calls to `next`/`success`.

**Comment by OlegDokuka** [comment]
Yeah, looks logical. The only thing we have to do in that case is providing aliasing for `onNext` call hence invocation of corresponding onNext onError onComplete would be equivalent to calling next error compete (I saw many examples where folks used onNext onError onComplete directly without sink)

In general that API preserve the overall notion of the processor without the direct introduction of a new one called Sink, hence it might be better

**Comment by OlegDokuka** [comment]
@simonbasle. I did try the new API and here is my feedback:

1) Having API's methods that return `FluxProcessorSink` and `FluxProcessorFacade` is over confusing. At least I was confused during migration to new API. In general, I suggest keeping only `FluxProcessorSink`. In turn, I would suggest hiding ***Builders methods under the separate API or at least `Processors.builders().replay()...` and keep simplified factories methods like `Processors.replay(5)` and that is it. I prefer less wordy API than writing `Processors.replay(5).buildSink()` or maybe `...Facade` (???) each time I need the same I had previously by calling `ReplayProcessor.create(50)`.
2) Feel the high need for `FluxProcessorSink#asSubscruber` (For my case); In my case, I have the endless loop which looks like following: 
```
ReplayProcessor<String> cursorSupplier = ReplayProcessor.cacheLast();
FluxSink<String> cursorSink = cursorSupplier.sink()
                                            .next("");

cursorSupplier.delayElements(Duration.ofSeconds(1), Schedulers.elastic())
              .concatMap(c -> pullAndNextCursor(c))
              .timeout(Duration.ofSeconds(3))
              .retryBackoff(Long.MAX_VALUE, Duration.ofMillis(200))
              .subscribe(cursorSupplier);
```
Thus in the case of new API I expected simplified API where I can write something like following:
```
FluxProcessorSink<String> cursorSupplier = Processors.cacheLast()
                                                     .next("");

cursorSupplier.asFlux()
              .delayElements(Duration.ofSeconds(1), Schedulers.elastic())
              .concatMap(c -> pullAndNextCursor(c))
              .timeout(Duration.ofSeconds(3))
              .retryBackoff(Long.MAX_VALUE, Duration.ofMillis(200))
              .subscribe(cursorSupplier.asSubscriber());
```
As it might be noticed, the expected simplification is reducing of the additional variable for sink and more natural flow of data 
3) `FluxProcessorSink.next()` should be overridden and return `FluxProcessorSink` instead of `FluxSink`

**Comment by simonbasle** [comment]
The latest step explored was the introduction of 3 interfaces in PR #1296 (closed and deleted since then). The interfaces have been archived in [this gist](https://gist.github.com/simonbasle/fcd40bf78b6f1ec55867e804df24447c).

Now we have:

 - `IdentityProcessor`: single simple interface for the processor-subscribes-to-source case, has all of this case's factory methods (flux and mono)
 - `StandaloneFluxSink`: `FluxSink` facade over the flux-like processors, has relevant factory methods
 - `StandaloneMonoSink`: wraps a `MonoSink` around a `MonoProcessor` (soon `FirstProcessor`), is a class but has a factory method for consistency.

**Comment by simonbasle** [comment]
See continuation of the discussion in #2179 and #2188 for how to expose sinks.

On top of that, this issue is superseded by:
 - #2203 for deprecation of the concrete classes, with `Processors` class centralizing neutral factory methods.
 - #2204 for removal of the concrete classes from the _publis_ API in 3.5
