### ISSUE TITLE
Provide Context merge callback and default multi values impl

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1176]
In order to support Context in fan out scenarios such as processors, one solution is to let the user define in the context how to react to merge.

For instance let's take a publish() operator with 3 subscribers defining a Context, API TBD but use case stands : 

```java
Flux<?> f = 
  Flux.create(sink -> {
   Context c = sink.currentContext();
   List<UserInfo> users = c.get("all");
   
   //dostuff
})
  .publish()
  .refCount(3))
  .subscriberContext(ctx ->
      ctx.onMergeWith(
             () -> Context.of("all", new ArrayList<UserInfo>()),
             (ctx1, ctx2) -> Context.of("all", ((List<UserInfo>)ctx1.get("all")).add(ctx2.get(UserInfo.class)));

f.subscriberContext(Context.of(UserInfo.class, userInfo1).subscribe();
f.subscriberContext(Context.of(UserInfo.class, userInfo2).subscribe();
f.subscriberContext(Context.of(UserInfo.class, userInfo3).subscribe();
```

**Comment by simonbasle** [comment]
@smaldini that gave me an idea: maybe the user could provide a lambda per key to merge?
chain in calls to `merge(Object key, BiFunction<Object, Object, Object> mergeFunction)` or `merge(Object key, BiFunction<Object, Object, Object> mergeFunction, Supplier<Object> ifNotPresent)`?

**Comment by simonbasle** [comment]
This couldn't be made a priority in 2 years, and no concrete usecase surface AFAIK, closing this.
