### ISSUE TITLE
Regression in MonoProcessor 

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-core#1184]
The latest MonoProcessor changes for #1114 cause a [test failure](https://build.spring.io/browse/SPR-PUB-6079) in the Spring Framework build. 

From what I can tell, [when we turn](https://github.com/spring-projects/spring-framework/blob/af0cb5374271ddeaab09541eb155cba4a8204d61/spring-messaging/src/main/java/org/springframework/messaging/tcp/reactor/ReactorNettyTcpConnection.java#L63) the `Mono<Void>` from a write into a `ListenableFuture` there are two subscribe calls, which then cause the same Netty ByteBuf to be written and decremented twice leading to `IllegalReferenceCountException`. The first (expected) subscribe happens [here](https://github.com/spring-projects/spring-framework/blob/af0cb5374271ddeaab09541eb155cba4a8204d61/spring-messaging/src/main/java/org/springframework/messaging/tcp/reactor/AbstractMonoToListenableFutureAdapter.java#L66) and the second (unexpected) subscribe [here](https://github.com/spring-projects/spring-framework/blob/af0cb5374271ddeaab09541eb155cba4a8204d61/spring-messaging/src/main/java/org/springframework/messaging/tcp/reactor/AbstractMonoToListenableFutureAdapter.java#L73).

**Comment by smaldini** [comment]
fixed in https://github.com/reactor/reactor-core/commit/87bf7a0e8322d05cc09545ba6dc44e54a6babde4
