### ISSUE TITLE
Optimize Mono producers to avoid onComplete when onNext

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1196]
Currently, all Mono generators send onComplete after a non null onNext.

Since we now have CoreSubscriber concept we can differentiate non reactor subscribers to create the onComplete signal only when subscribed from outside reactor.
Similarly we might need to do the same for Mono-to-Flux operators or port currently shared operators (between Flux and Mono) as exclusive Mono operators.

**Comment by simonbasle** [comment]
Deferring this to 3.4

**Comment by simonbasle** [comment]
I'm not keen on doing that anymore, given the level of complexity of the codebase as it is. If a benchmark can be produced that demonstrates a huge gain in doing this, we'll reconsider. Closing this in the meantime.
