### ISSUE TITLE
Detect CompletitionStage created from Mono

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#1200]
Hi!

In one of my projects, I'm using `CompletitionStage` and `Publisher` to make it reactive framework agnostic.

However, most of the code is in Reactor.

Currently, `Mono.fromCompletitionStage` does not detect if the `CompletitionStage` is implemented by another Mono (like Flux does with `Publisher`)

This adds a performance penalty we would like to avoid.

Is it something in works or maybe you want me to contribute it?
Thanks!

**Comment by akarnokd** [comment]
A `CompletionStage` indicates a running or completed source and is created by subscribing to a `Mono`.  If the `fromCompletionStage` detected the original `Mono`, it would create a likely cold chain again by not running the upstream mono at all, and thus if something relied upon side-effects of having a `CompletionStage` gets broken.

**Comment by bsideup** [comment]
@akarnokd 
oh wow, I checked the sources and now I see that!
I always thought that Reactor's `CompletitionStage` is cold (akin Akka Streams, but now I need to double check it in Akka Streams as well :D /cc @ktoso )

So, there is no way to return Mono-like interface without using Reactor's classes? :(
`Publisher` / Flow both lead to errors (or misunderstanding) because it's unclear how many emissions there will be (Also AFAIK the reason why Akka is using it, **I may be wrong here**)

**Comment by simonbasle** [comment]
Yes, as @akarnokd explained, once you use that bridge method, there's no real way to tie it back to the inherently lazy behavior of the `Mono` AND cover all the potential use cases, since a subscription will have happened by then. Sorry :(

**Comment by bsideup** [comment]
@simonbasle may I kindly ask you to keep it open, at least for the sake of discussion? :)
An obvious solution I see is adding `lazy` flag to `toFuture()`, but I want to hear from all the smart people here, maybe you know even better solution, especially some existing ones :)

**Comment by simonbasle** [comment]
@bsideup yes, you can continue the discussion (comments shouldn't be disabled). If by any chance an acceptable solution emerges, I'll reopen to track the fix.

**Comment by bsideup** [comment]
@simonbasle what if returned implementation will call `toFuture()` when any of the `CompletionStage`'s methods is called?
