### ISSUE TITLE
Clarify usage of doOnNext()

### ISSUE THREAD

**Issue by maconic** [reactor/reactor-core#1215]
This is not an issue but more of a question. 

The documentation is states that the doOnNext() operator is a side effect operator. Does this mean it is not supposed to modify the content of a stream (as in change the contained object).

I am aware that in a functional world we should not mutate the object at all, but in the real world we have to deal with stuff that mutates. Hence the question: what is the right approach to this? Creating another Mono and using flatMap or doOnNext ? 

THX; 

MaC

**Comment by simonbasle** [comment]
In an ideal world, you could avoid mutation by using a simple `map` that copy-constructs the new instance from the original one. But otherwise, it seems acceptable to mutate inside a `doOnNext` yes. Mutation won't be "seen" from the operators before the `doOnNext` but will be visible downstream.

**Comment by akarnokd** [comment]
> Mutation won't be "seen" from the operators before the doOnNext but will be visible downstream.

That's not true in general because it depends on the data type and whether or not it is shared within or outside the flow.

For example, this is safe:

```java
Flux.fromArray(new int[1], new int[1])
.doOnNext(ints = ints[0]++)
.publishOn(Schedulers.elastic())
.doOnNext(ints = ints[0]++)
.subscribe(ints -> System.out.println(Arrays.toString(ints)));
```

Each `int[1]` is mutable but they are standalone and thus mutation at various locations won't affect them.

However, this is unsafe:

```java
int[] data = new int[1];
Flux.fromArray(data, data, data)
.doOnNext(ints = ints[0]++)
.publishOn(Schedulers.elastic())
.doOnNext(ints = ints[0]++)
.subscribe(ints -> System.out.println(Arrays.toString(ints)));
```

Here, data is shared and the same instance is accessed from multiple threads and can end up with arbitrary value.

**Comment by simonbasle** [comment]
Indeed, thanks for clarifying that @akarnokd

**Comment by maconic** [comment]
I guess in Kotlin the proper way would be to use a data class and copy. 

Maybe it is rather just a feeling but doOnNext() feels wrong to me.
What about the non blocking nature of reactor?
What if there is a long running task (for instance a network call) inside a doOnNext block?

**Comment by simonbasle** [comment]
That you should **definitely** avoid. This is all supposing the mutation is pretty much instantaneous (no I/O). Otherwise you'll need to apply the usual patterns (`flatMap` for async processing, offset on a separate thread if unavoidable blocking imperative code...)
