### ISSUE TITLE
Missing next signals from Flux.replay

### ISSUE THREAD

**Issue by stavalfi** [reactor/reactor-core#1223]
In short: 

The following is done 20 times: I subscribe to a stream with history=1. when I actually subscribe, I signal the number I recieved (1-20) and I wait until I receive this number.

It took me 2 weeks to find the cause of my bugs. Please let me know if it is a desired behavior or a bug of reactor.

### Steps to reproduce
**the reproduce works every 1/15+- executions:**
```java
DirectProcessor<Integer> numbers1$ = DirectProcessor.create();
FluxSink<Integer> numbers1Sink = numbers1$.sink(FluxSink.OverflowStrategy.BUFFER);

Flux<Integer> replayNumbers1$ = numbers1$.publishOn(Schedulers.elastic())
		.replay(1)
		.autoConnect(0);

int amount = 20;
Flux.range(1, amount)
		.flatMap(number -> {
                        // there is a happens before relationship between the request
                        // from _replay stream_ and the emitting to replay stream.
			return replayNumbers1$.publishOn(Schedulers.elastic())
					.filter(received -> received.equals(number))
					.take(1)
					.doOnSubscribe(__ -> numbers1Sink.next(number));
		})
		.doOnNext(integer -> {
                        // for the buffer to signal if he recieve
                        // less then "amount" numbers.
			if (integer.equals(amount))
				numbers1Sink.complete();
		})
		.buffer(amount)
		.take(1)
		.doOnNext(list -> System.out.println(list))
		.map(List::size)
		.doOnNext(size -> {
			if (size.equals(amount))
				System.out.println("working");
			else
				System.out.println("not working");

		})
		.publish()
		.autoConnect(0);
```

### Expected behavior
Any permutation of the following:
```java
[1, 2, 3, 5, 4, 7, 6, 9, 10, 8, 11, 12, 14, 13, 15, 16, 20, 19, 18, 17]
working
```

### Actual behavior
```java
[1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 10, 12, 13, 16, 15, 17, 18, 19, 20]
not working
```
### Reactor Core version
`Bismuth-SR7`
### JVM version (e.g. `java -version`)
`1.8`

**Comment by simonbasle** [comment]
I think this is an issue with your whole flow. You are using `flatMap` and `Schedulers.elastic`, which introduces an asynchronous boundary that could cause the emissions of 2 numbers to race, resulting in them getting to the sink out of order. As you use a replay of 1, it seems to me that this sequence of operations can only deal with at most 2 elements being out of order, and a third out of order element would replace the first one in the history, resulting in said first element being seemingly dropped.

I don't understand the rationale for using `publish().autoconnect(0)` within the `flatMap` either.

Have you looked at `parallel().runOn()` if you want to divide work into groups? Or explored using `flatMapSequential` or `concatMap`?

**Comment by stavalfi** [comment]
> I don't understand the rationale for using publish().autoconnect(0) within the flatMap either.

It's a mistake - I forgot to remove it while reproducing the problem.

> ...that could cause the emissions of 2 numbers to race...

Are you saying that `DirectProcessor.sink` doesn't support more then one emmision concurrently?

> ....that could cause the emissions of 2 numbers to race, resulting in them getting to the sink out of order.

I don't care for the order. I subscribe __before__ I emit so there is no reason that will prevent each subscriber (inside the `flatMap` to miss the only signal he waits for).

-----
In general, for every new signal to the stream with history=1, he should of signal what he received to all it's subscribers before accepting a new signal from upstream. Am I right?

**Comment by simonbasle** [comment]
> In general, for every new signal to the stream with history=1, he should of signal what he received to all it's subscribers before accepting a new signal from upstream. Am I right?

Not quite, it replays the last signal it saw. So if its subscriber doesn't request faster than its source, it might replace the single element in its history with a new one. And since `flatMap` can have concurrent invocations, said invocations could race.

**Comment by stavalfi** [comment]
In the code I provided, there is a __happens before__ relationship between the request from _replay stream_ and the emitting to _replay stream_. First, the stream inside the `flatMap` is subscribing and *only then* he causes a new signal to the _replay stream_:

```java
The simpliest senario:

(1) subscriber1 subscribe
(2) emit signal: "1"
(3) replay stream receive signal "1" and send it to subscriber1.
(4) subscriber2 subscribe
(5) emit signal: "2"
(6) replay stream receive signal "2" and send it to subscriber1.
(7) replay stream receive signal "2" and send it to subscriber2.

A possible senario:

(1) subscriber1 subscribe
(2) subscriber2 subscribe
(3) emit signal: "2"
(4) emit signal: "1"
(5) replay stream receive signal "2" and send it to subscriber1 and subscriber2
(6)  replay stream receive signal "1" and send it to subscriber1 and subscriber2.
```
------

Unless `DirectProcessor.sink` doesn't support concurrent emmits or there is no __happens before__ relationship between the request from _replay stream_ and the emitting to _replay stream_, I may miss understood one of your replies because there is no way the replay stream can __lose__ signals.

**Comment by simonbasle** [comment]
But in your first scenario, `1)` and `4)` can race, because `flatMap` subscribes its inners in parallel.

**Comment by stavalfi** [comment]
@simonbasle you have an extremely sharp eye! 

How would you fix the code so it will work as expected? (in real life, the flatMap which allow parallel work is, in my app, an example of multiple different methods which can be called concurrently).

**Comment by simonbasle** [comment]
if you know in advance either the max amount _or_ the max parallelism you can get, maybe you could have a larger replay buffer. I would also recommend putting a TTL on the replay so that it doesn't keep items in the cache for longer than required.

**Comment by stavalfi** [comment]
Thanks @simonbasle for the replies so far.

I was just thinking about your scenario again and after a second thought, it is still a valid scenario (there should be no problem): if 2 subscribers subscribe at the same time then, as you said, they will emit signals at the same time. But because they are already subscribing and requested from upstream, then they won't lose any of the signals as opposed to your claim.

I made the above code little more simplified by replacing `replay()` with `publish()` . By the same assumptions that - unless `DirectProcessor.sink` doesn't support concurrent emits or there are no __happens before__ relationship between the request from _replay stream_ and the emitting to _replay stream_, __then the code should work as expected and all signals should go downstream (which doesn't happen).__
```java
int amount = 20;
Flux.range(1, amount)
		.flatMap(number -> {
			return replayNumbers1$.publishOn(Schedulers.elastic())
					.filter(received -> received.equals(number))
					.take(1)
					.doOnSubscribe(__ -> numbers1Sink.next(number));
		})
		.doOnNext(integer -> {
			if (integer.equals(amount))
				numbers1Sink.complete();
		})
		.buffer(amount)
		.take(1)
		.doOnNext(list -> System.out.println(list))
		.map(List::size)
		.doOnNext(size -> {
			if (size.equals(amount))
				System.out.println("working");
			else
				System.out.println("not working");

		})
		.publish()
		.autoConnect(0);
```
