### ISSUE TITLE
Github milestones, fixes impacting multiple releases and moving away from backport strategy

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#1225]
This issue is for discussion around changing our process when an issue is needed in both the current development version (`master` branch) and one or more maintenance releases (I'm actually assuming we'll only consider the `3.1.x` branch for now).

# Too Long; Didn't Read version
We're considering switching to an issue triage, github milestone usage and branching model similar to that of Spring Boot (see [branching wiki](https://github.com/spring-projects/spring-boot/wiki/Working-with-Git-branches) and [triage wiki](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Issue-Triage-Process)).

# So Far
Until now, we've worked exclusively with _backports_, which we've always decided on doing **after the original issue was fixed**. It usually goes like this:

 - a problem is discovered in the `master` branch, and an issue is created
 - the issue is affected to what we expect to be the next feature release (out of `master`)
 - the fix is developed against `master`
 - we think about it and decide the fix is important enough to warrant a maintenance release of the previous `GEN.MAJOR` (eg. if `master` is `3.2.x` then we decide we also want to release the fix in the `3.1.x` cycle)
 - we **backport** the fix from `master` to `3.1.x` by **cherry-pick**
 - we open or edit a "**tracker issue**" affected to the next `3.1.x` milestone that will list the backports
 - we _edit_ the cherry pick commit message to change the title prefix to `port`, and reference the original commit AND the tracker issue in the commit message body

This is somewhat convoluted from a process perspective and although it makes it _possible_ to see which fixes were backported from GitHub's UI, it is still _hard_. Also, from a git tooling perspective things are not so rosy (one can follow from the backport to the original fix by looking at the whole commit message, but the reverse is not possible).

# Proposal: switch to a `git merge` scheme
This is inspired by what the Spring Boot team does.

⚠️Note that this scheme would force us to be more proactive on deciding wether a bug needs a fix in a maintenance release or not.

Here is how it would go:

 - a bug is discovered in version `3.2.x`
 - we look at the bug and see if it is also present in `3.1.x`. If it is, we decide wether or not it is impacting enough that it should be fixed in a maintenance release
 - we affect the issue to the _backlog milestone_ for the maintenance branch to mark it as triaged and targeting that maintenance branch
 - the fix is worked on a branch created out of `3.1.x`, multiple reviews on the PR can lead to multiple commits but we still prefer `squash-and-merge` where possible to result in a **single commit on `3.1.x`** after the merge of the PR
 - **this is where additional manual steps are required**:
 - the `3.1.x` branch is merged forward into `master` (`git merge --no-ff 3.1.x`)
 - if there are any conflicts, meaning the fix impact a part of the code that has greatly diverged between 3.1 and 3.2, they are fixed immediately when the context of the fix is still fresh, and are made part of the merge commit.
 - if the fix was targeting 3.0 instead, the merge step would be done twice: once from 3.0 to 3.1 and once from 3.1 to master.

**Pros**
The upside is that when it is in a maintenance branch, this process would guarantee that it is also in all subsequent maintenance branches AND master. It would also result in a single commit for the fix in _all_ branches (plus GEN.MAJOR specific adjustments in the merge commit).

**Cons**
It adds noise in the commit history with merge commits, which should be made minimally descriptive:
 - when adjustments were made, reflect it in the commit message "Adapt #issueNumber fix to 3.2"?
 - when simple forward-merge, maybe use a simple title like "Merge #issueNumber fix into 3.2"?

# GitHub milestones and release contents / release notes
Rationalizing our usage of GitHub milestones would also be beneficial with this scheme. Here is something that could work for us (again following the Spring Boot model):
 - have backlog milestones receiving issues that we triaged and want in either the next feature release or a specific maintenance release, or at some point in the future.
 - have `.RELEASE` milestones (or `.M1`, etc...) that match an exact release and reflect what is _contained_ in this release and ready to ship with it.
 - when fixing in maintenance branches, make sure that the release notes of subsequent releases in higher versions also list the issues.

For instance, with a `master` that contains active development on 3.2.0, with a second milestone in the near future and a planned maintenance release of 3.1.8.RELEASE, we would have milestones for **triage**:
 - `[icebox]` (formerly `[backlog]`): issues that we want fixed at some point in the future but don't know when
 - `[backlog]`: issues that we want fixed in the next feature release (3.2.0)
 - `3.1.x`: issues that we definitely want fixed within 3.1.x, but not necessarily in 3.1.8
 - `3.2.x`: issues that we definitely want fixed within 3.2.x, but not necessarily in 3.2.0

And milestones for **shipping/tracking representative progress**:
 - `3.1.8.RELEASE`: issues that are fixed from `3.1.x` backlog are moved here. Open issues can also be affected here _if we absolutely need that issue fixed in that particular version_
 - `3.2.0.M2`: we're preparing a milestone 2 for 3.2.0 and issues that will ship with it are moved to this gh milestone, from `[backlog]`, when merged. Open issues can also be affected here _if we absolutely need that issue fixed in that particular version_

**Comment by simonbasle** [comment]
I've started with rationalizing the milestones in GH:
https://github.com/reactor/reactor-core/milestones?direction=desc&sort=title&state=open

**Comment by simonbasle** [comment]
We'll probably switch to this model once `3.1.8.RELEASE` and `3.2.0.M2` are released next week.

**Comment by snicoll** [comment]
Sweet :)

**Comment by simonbasle** [comment]
Done on `master`, phew 😅
I'll unshamefully copy-paste the wiki pages from Spring-Boot and adapt :p
