### ISSUE TITLE
Fix marble diagrams urls when releasing

### ISSUE THREAD

**Issue by madgnome** [reactor/reactor-core#1227]
Urls for marble diagrams updated as part of #1224 have changed to point to master ( https://github.com/reactor/reactor-core/pull/1224#pullrequestreview-124306932 ) .

We need to change them as part of the release process:

- [x] ~Change the urls before release to fix on the commit directly rather than a tag/branch~ N/A
- [ ] Change the urls after the release, once the tag is available, to fix on the tag and have "cleaner" urls 

Search for `https://raw.githubusercontent.com/reactor/reactor-core/master/` to find the urls that need changing.

**Comment by simonbasle** [comment]
As I'm preparing to release milestone 2, I'll directly fix to the M2 tag right after that and it can be the definitive tag for these urls
