### ISSUE TITLE
doOnEach breaks link to actual signal

### ISSUE THREAD

**Issue by Kindrat** [reactor/reactor-core#1228]
### Expected behavior
Method can be used to collect stream signals
### Actual behavior
All collected signals are actually pointing to same `DoOnEachSubscriber` hiding actual data of signal and providing copies of latest one only. Passing subscriber that is also a signal to a consumer is counterintuitive and is not reflected in documentation.

```
Expecting:
 <[10, 10, 10, 10, 10, 10, 10, 10, 10]>
to contain:
 <[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]>
but could not find:
 <[1, 2, 3, 4, 5, 6, 7, 8, 9]>
```
### Steps to reproduce
```java
    public void doOnEachFailure() {
        List<Integer> expected = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);

        List<Signal<Integer>> actualSignals = new ArrayList<>();
        Flux.fromIterable(expected)
                .doOnEach(actualSignals::add)
                .blockLast();

        assertThat(actualSignals).hasSize(expected.size() + 1);
        assertThat(actualSignals.get(10)).has(fieldEqualTo(SignalType.ON_COMPLETE, Signal::getType));
        List<Signal<Integer>> onNexts = actualSignals.subList(0, 9);
        for (Signal<Integer> onNext : onNexts) {
            assertThat(onNext).has(fieldEqualTo(SignalType.ON_NEXT, Signal::getType));
        }

        List<Integer> actualIntegers = onNexts.stream().map(Signal::get).collect(Collectors.toList());
        assertThat(actualIntegers).containsAll(expected);
    }
```

### Reactor Core version
3.1.6
### JVM version (e.g. `java -version`)
```
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

![Love this](http://i0.kym-cdn.com/photos/images/newsfeed/000/975/464/97d.gif)

**Comment by smaldini** [comment]
The intent is to use it to extract and should be reflected in doc (issue). The reason being to avoid wrapping/unwrapping and there are a few places we use these inlined containers. Alternatively you could use materialize.

**Comment by Kindrat** [comment]
@smaldini so you don't see a problem in wrapping all signals into a single mutable object here? The simple test I've provided describes how all such APIs are expected to work... It's the same as saying you can wrap actual DTO's with a proxy and passing them in doOnNext...

What about breaking `Signal` interface here? `get()` method will is unpredictable and may return any value, however it is still same signal instance. I can't tell if it's reasonable in any way, but can we at least have some minimal stable API? The last thing we wan't - is to verify every single public API of reactor by reading sources (still obfuscated by the way)...

**Comment by OlegDokuka** [comment]
I guess that is not a problem at all. Current API express particular functionality in order to react on any emitted signal within the stream. In turn, collection all events within the `forEach` operator (which is side effects) is not something unrecommended. As @smaldini mentioned, there is a `.materialize()` operator which is compliant to Reactive Spec and all signals emitted within the stream are immutable, see -> https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/FluxMaterialize.java#L107.

**Comment by Kindrat** [comment]
@OlegDokuka so I can post PR updating `Signal` docs referring the fact it's metods are providing unpredictable result?

**Comment by simonbasle** [comment]
@Kindrat you can post PR updating `Signal` doc referring the fact that `doOnEach` is, like all `doOn` operations, intended for a stateless in place processing of the value it receives (no guarantee about being able to "see" previous values, no deferred processing of the value without making a copy, immediate `get()` and deferred processing of the result of `get()` are fin though) + a `@see materialize()`

**Comment by Kindrat** [comment]
Guys, I still strongly disagree that there can be explanation for breaking one of core interfaces in favour of some internal needs. Better to remove this API at all. What would happen if JDK devs would do the same? There is no problem in using `materialize()` - the problem is in API inconsistency. The meaning of interface is to provide some contracts, useful for API users. And in current implementation you are forcing users to validate each public method to find such "side-effects".

**Comment by simonbasle** [comment]
The `Signal` API itself is not broken by `doOnEach`: `doOnEach` takes a `Consumer<Signal>`, which _MUST_ consume the provided `Signal` immediately and in a stateless way. If your consumer calls `isOnNext()` and it returns `true`, consumer can call `get()` and it will get the correct value.

Do not defer processing, by eg. storing it in a collection. Do not launch a `Thread` that sleeps for 1 second and then calls `signal.get()`. All these are bad consumers, and you will get wrong results.

**Comment by smaldini** [comment]
@Kindrat it's a trade-off which allows users to benefit from a allocation-less critical path. A functional API has a few rules regardless of the Signal contract:
- not blocking unless explicit thread jump operators are used
- not trying to extract a state outside unless explicit collector operators are used
- not having stateful functions as multiple subscribers could conflict
In particular doOnXxx operators are passive observers, it is also discouraged to extract Subscription form doOnSubscribe. However we could make the intent more clear in having a marker interface extending Signal which we would call SignalView or LiteSignal or something with a clear documented "clone" or "duplicate" to copy the signal altogether. But when you think about it as the set of rules established above, it kind of duplicate the overall doOn API intent.

**Comment by Kindrat** [comment]
The requirements for doOn are reasonable. I'm trying to say that the `evil` thing here is inconsistency. Signal is model here, but its methods are not deterministic. The result may vary depending when exactly you'll call those methods. This may lead to creepy bugs in user code b/c noone expects DTO to be a mutable wrapper over a stream of same DTO type pointing to latest one always. Some library may expose Signals and library users will be debugging and waiting for fixes - that's dangerous backdoor.

As for me. the best decision would be making completely different root interface (e.g. SignalView) that is not inferred from Signal and expose it in this method (could also provide API to clone current underlying Signal as you've described). It would be safe enough and obvious for API users. Making a service implement DTO marker interface is always a bad idea...

**Comment by simonbasle** [comment]
> Some library may expose Signals and library users will be debugging and waiting for fixes - that's dangerous backdoor.

Are you saying that such libraries would expose **the `Signal` provided to the `Consumer<Signal>` of `doOnEach`, or more generic `Signal` (eg. from `materialize()`, or instantiated through `Signal.next("foo")`)?

**Comment by simonbasle** [comment]
> > Some library may expose Signals and library users will be debugging and waiting for fixes - that's dangerous backdoor.
> >
> Are you saying that such libraries would expose the Signal provided to the Consumer<Signal> of doOnEach, or more generic Signal (eg. from materialize(), or instantiated through Signal.next("foo"))?

While the second case is fine (it would produce independent instances), the first one would mean said library has been built on false premises. It would be like a library that uses a `List<T> get()` method and mutates the `List`, assuming wrongly it is a copy and not the original list.

Note that for your test, the recommended usage pattern would be `.materialize().doOnNext(list::add).dematerialize()`, which produces distinct `Signal` instances that are suitable for deferred consumption. `doOnEach` produces a flyweight `Signal` that is only suitable for immediate consumption.

We will continue thinking about this issue. One trade-off could be to introduce a `doOnEach(Consumer, boolean)` variant with a `boolean allocationFree` parameter and have the `doOnEach(Consumer)` call it with `false` (changing the default behavior).

Users getting a performance hit could revert back to the allocation-free behavior, making it more explicit.

We won't however break the API to the point of `doOnEach` not using `Signal`.

**Comment by simonbasle** [comment]
> @simonbasle as you can see, you've confused yourself with your own API

How? 🤔

**Comment by Kindrat** [comment]
Asking how the library may expose your signals. For a consistent API it should not matter.

**Comment by simonbasle** [comment]
I'm asking how the library would **access** the `Signal`, big difference.

So you are arguing that similarly, for a library that uses `List`, it wouldn't matter how it got a `List`, wether via `new ArrayList()` or `Collections.unmodifiableList(new ArrayList())`?

You are arguing that for an API that produces `List`, since it has an `add` method the API should always produce mutable lists?

`Collections.unmodifiableList` produces a `List` that has an `add` method, but also a javadoc, which _is_ part of the contract, that stipulates that you won't be able to use `add`.

`Signal` is an interface that doesn't say anything about immutability. Eg. on `get()` method:
```
/**
 * Retrieves the item associated with this (onNext) signal.
 *
 * @return the item associated with this (onNext) signal, or null if not relevant
 */
```
Immutability is a concept that depends on the APIs exposing the `Signal`:

 - `materialize()` transforms a `Flux<T>` into a `Flux<Signal<T>>`, which are immutable.
 - `doOnEach` gives a `Signal` to a `Consumer`, but that `Signal` is not immutable so it should be consumed in place to get the relevant information.

Again, both (im)mutable aspects should be made clearer in the javadoc, and the `doOnEach` sacrificing of immutability to optimize allocations might be too surprising to be kept as a default, but the solution is not to introduce a completely different interface.

Also please stop saying `Signal` is a DTO. This is not a DTO any more than `List` is a DTO. It is not intended to be used to transfer data between a data access layer and a business layer. It is not intended to always be immutable.
