### ISSUE TITLE
Add transform() operator to Flux/Mono to support transforming stream without deferring

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#124]
Discussed in gitter:

**Daniel Feist @dfeist**
I see as() as an operator i'd primarily use when converting flux to something else, not for chaining, thats also typically how "as" is interpreted in API's. The fact that you can chain if you use a function that returns Flux is almost a convenient side-effect, but not the main purpose of that operator in my opinion.

Compose on the other hand is for chained composition, but it defers which isn't required/desired for simple Flux transformation.

**Stephane Maldini @smaldini**
no i see the point totally

**Comment by akarnokd** [comment]
That's why `as` exists; just use a lambda that returns a `Flux`/`Mono`.

**Comment by dfeist** [comment]
Ok.  Can you add a quick example of how you would use `as` with a `Function<Publisher, Publisher>` while supporting chaining?

`range(1,100).as(publisherFunction1).as(publisherFunction2)...`

Then we can tag this as question and close.

**Comment by dfeist** [comment]
This look about right?
```
Flux.range(1,100).as(flux -> Flux.from(flux.as(publisherFunction1)))
                             .as(flux -> Flux.from(flux.as(publisherFunction2)))
```
