### ISSUE TITLE
FluxSink's confusing onDispose and onCancel callbacks.

### ISSUE THREAD

**Issue by nnanda2016** [reactor/reactor-core#1240]
For a regular `Flux`, when `Disposable.dispose` is called, it invokes the `doOnCancel` operator; 
so there's a relationship between `dispose` and `cancel`. `FluxSink` however, provides two callback APIs `onDispose` and `onCancel` and adds confusion on their usage.

**Comment by OlegDokuka** [comment]
I would add here that this issue more related to the lack of the documentation rather than to implementation, so it would be nice if the result of that discussion will be some agreement on the additional section for behavior on disposing of the Flux. Currently, there is a small section which describes the difference between FluxSink#onCancel FluxSink#onDispose.

**Comment by nnanda2016** [comment]
I had a discussion with Simon Basle on this and he feels `onDispose` should rather be called `onTerminate` to make better sense.

**Comment by simonbasle** [comment]
Following discussion with @smaldini in @OlegDokuka's PR, this is maybe not the best course of action. The `terminate(d)` term is used throughout the codebase to mean `onError or onComplete`, and doesn't include `cancel`. `disposed` covers all three, hence the term.

The original confusion stems from confusing the `Sink` and the `Subscription`:
 - `someFlux.subscribe().dispose()` is actually disposing the `Subscription`, which is the same as cancelling it
 - for a `Sink`, `disposed` means no more data can be pushed to it. And a `Sink` is unusable as soon as it is completed (`onComplete`), failed (`onError`) or cancelled (`cancel`), hence that handler covers all three cases.

If will propose a PR to improve the documentation.

**Comment by phnxfire** [comment]
When my WebSocket disconnect the FluxSink gets in a Cancelled state and doesn't send messages anymore on onNext... what should I do to keep FluxSink in a 'active' state in such a way that the next WebSocket connection it will send objects again
