### ISSUE TITLE
Unused field in schedulers

### ISSUE THREAD

**Issue by smiklos** [reactor/reactor-core#1243]
### Expected behavior
The field should be either used or not be there at all.
### Actual behavior
It's there
### Steps to reproduce
look at usage of field 
https://github.com/reactor/reactor-core/blob/89a8e0eb84edbd482297011ed303d8158323bba4/reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java#L65
### Reactor Core version
3.1+

**Comment by simonbasle** [comment]
@smaldini do you remember any particular reason we'd avoid using that constant in the codebase?

@smiklos we won't be able to remove it, as it is public (so some users might rely on it in external code)

**Comment by smiklos** [comment]
Surely not right away, but better to start using it or getting rid of it :) 

I would love to see a config for default pool sizes, maybe something I can add?

We are running multiple apps on a server with many cores and each instance starts with numberOfCores thread for parallel scheduler. We could/can set each usage of scheduler to run with a user made scheduler but it would be better to be able to configure the default

**Comment by simonbasle** [comment]
I think it could make sense as a configurable option in the same vein as what is done [here](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/util/concurrent/Queues.java#L82)

**Comment by smaldini** [comment]
We could leverage that indeed, I wonder why i didn't use it for parallel.

**Comment by simonbasle** [comment]
@smaldini cool!

So we could:
 - replace all usage of `System.getRuntime().getAvailableProcessors()` with the constant
 - change the constant initialization to check a `System.getProperty` for user overload

@smiklos if you want to contribute that, let us know 👍

**Comment by smiklos** [comment]
@simonbasle I would love to! Will make a pr

**Comment by simonbasle** [comment]
Regarding the logic, I think we can remove the min of 4. It would only be used by people relying on the constant (I don't expect there's that many) and the boilerplate for them to get that minimum again would be small.

I'll make a note to mention that in the release notes update considerations, though.
