### ISSUE TITLE
Align `repeat(n)` and `repeat(n, predicate)`

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#1252]
### Expected behavior
`Flux.just(1).repeat(3)` and `Flux.just(1).repeat(3, () -> true)` both result in `1 1 1`.

### Actual behavior
The `repeat(int, Predicate)` form results in `1 1 1 1`

### Analysis
~This is due to the `countingBooleanPredicate` using `n++ > max` instead of `++n > max`, thus not considering the first emission as an "attempt", unlike `repeat(n)`.~

Note that retry on the other hand always uses the `n` parameter as a number of **retry attempts**, which implies that there is also an initial attempt, resulting in N+1 subscriptions (at most).

@smaldini I'm wondering if we should target 3.2 only for now, as people might have accepted and worked with the behavior misalignment in the 3.1.x line.

**Comment by sinwe** [comment]
Perhaps people doesn't realize the difference

**Comment by simonbasle** [comment]
After looking at it deeper, there's something I think we both missed: these variants with `BooleanSupplier` actually work **post-completion**. The `repeat*` javadocs need some love, sure, but it boils down to this: `repeat(BooleanSupplier)` and `repeat(int, BooleanSupplier)` will both always let the source run once before deciding to repeat or not. That is to say, they don't let you do an equivalent of `repeat(0)` (which is just basically replacing the source with `Flux.empty()`).

The order of parameters kind of suggests the opposite, but `repeat(int, BooleanSupplier)` is first and foremost a `repeat(BooleanSupplier)` in that regard...

**Comment by simonbasle** [comment]
I'm marking this as a documentation issue. I'll rename the parameter and rework the javadocs to clarify things. This can be done in the `3.1.x` branch and forwarded to 3.2.

**Comment by sinwe** [comment]
I believe an example (including the expected result) in the JavaDoc would be useful

**Comment by sinwe** [comment]
Another inconsistency:
If `Flux.repeat(3)` means **total subscription = 3** while `Flux.repeat(3, () -> true)` means total subscription = 4, 
why `Flux.retry(3)` means **total subscription = 4** and `Flux.retry(3, t -> true)` means total subscription = 4

**Comment by simonbasle** [comment]
Mmh you are right @sinwe, this makes the inconsistency worse...

We could align the simple case with the more complex ones, ie. `Flux.just(1, 2, 3).repeat(1)` would output `1 2 3 1 2 3` (instead of `1 2 3` right now).

That would align with both `retry(1)`, `retry(1, predicate)` and `repeat(1, boolSupplier)`.

What do you think @smaldini?

Of course this would now target `v3.2` because of the breaking behavior change.

**Comment by smaldini** [comment]
I agree @simonbasle  and that shouldn't go in 3.1
