### ISSUE TITLE
Make InnerOperator Hierarchy Public

### ISSUE THREAD

**Issue by nebhale** [reactor/reactor-core#1253]
Currently, the `InnerOperator` interface and its parents `InnerConsumer` and `InnerProducer` are package private.  Given that most people will begin creating (or updating to best practices) a custom operator by looking at existing operators, these interfaces being non-public becomes an obstacle.  You can ascend the hierarchy and implement the import interfaces they extend, but it's non-obvious and results in operators that cannot be as full featured as the built-in ones.

These interfaces should be made public and properly documented for usage.

**Comment by smaldini** [comment]
We should not expose that in the next reactor major version, the API is not yet public ready but we might consider a contract for a reactor 3.3 or reactor 4.
