### ISSUE TITLE
Document backpressure behaviour of operators

### ISSUE THREAD

**Issue by madgnome** [reactor/reactor-core#1261]
It would be nice if each operator Javadoc could clearly define the backpressure behaviour. 

RxJava does something like this, e.g.  http://reactivex.io/RxJava/javadoc/io/reactivex/Flowable.html#flatMap-io.reactivex.functions.Function-

**Comment by madgnome** [comment]
I will give it a go (or at least start 😄 )

**Comment by simonbasle** [comment]
This is low priority at the moment, so a bit of a stretch goal for 3.4.x, but one avenue to explore is to add a `Scannable.Attr`ibute, like what is currently being done around #2058 (but only on the `Publisher` level). Note the caveat covered in #2136

**Comment by chemicL** [comment]
Closing as there was no community interest to contribute and as a team we don't have the capacity to approach this.
