### ISSUE TITLE
Adding `Single` and `Completable` types

### ISSUE THREAD

**Issue by vy** [reactor/reactor-core#1268]
While `Mono` does a great job representing 0|1 items, sometimes (I would personally say *quite often*) you need to have a distinction between `Mono[0]` and `Mono[1]` in the types. While one might argue that `Mono#single()` does exactly fill this gap, it only helps you with a `NoSuchElementException` at runtime. It would be way more desirable to let the compiler assist us by introducing distinct types for `Mono[0]` and `Mono[1]` cases, which happens to be addressed by `Single` and `Completable` types in RxJava. Are there any plans to introduce these types into Reactor too? If not, how can I create an incentive for that?

**Comment by vy** [comment]
`Completable == Mono<Void>` and `Single` is hostile to back-pressure, says @simonbasle.

**Comment by simonbasle** [comment]
Another reason why we don't really want to add such types is the maintenance burden they introduce. The way Reactor (and RxJava) is architectured, each `Mono` operator is defined as a class that `extends Mono`. In order for the API to keep presenting you with an hypothetical `Single` type once you call more operators after `myMono.single()`, it would mean at least a partial duplication of operator classes just for the sake of `Single`.

(see https://github.com/ReactiveX/RxJava/tree/2.x/src/main/java/io/reactivex/internal/operators/single)

There could be a middle ground like having a simple marker "interface" that is only returned by `single()`, but it wouldn't help much if it disappears upon first use of an operator I think 🤔

**Comment by akarnokd** [comment]
I don't recommend it either. `Mono` captures both in a nice performant way and there is only extra maintenance when dealing with those types: diagrams to create and fix, operators to implement symmetrically, tests to adapt, etc.
