### ISSUE TITLE
Mistake on error handling documentation?

### ISSUE THREAD

**Issue by aalku** [reactor/reactor-core#1269]
On error handling section of the documentation I found the same mistake several times.

http://projectreactor.io/docs/core/release/reference/#error.handling
This is the shortest example:

```
Flux.just("key1", "key2")
    .flatMap(k -> callExternalService(k)) 
    .onErrorResume(e -> getFromCache(k));// <--- ERROR, no variable k
```

On the third line the variable k is not defined. It's a very important issue in my opinion as if the processing of an element fails you might want to know which one failed. By the examples it seems you can but you cannot unless you can get it from a custom Exception or somewhere else.

Same here:

```
Flux.just("timeout1", "unknown", "key2")
    .flatMap(k -> callExternalService(k))
    .onErrorResume(error -> { 
        if (error instanceof TimeoutException) 
            return getFromCache(k);// <--- ERROR, no variable k
        else if (error instanceof UnknownKeyException)  
            return registerNewEntry(k, "DEFAULT");// <--- ERROR, no variable k
        else
            return Flux.error(error); 
    });
```

And here:

```
LongAdder failureStat = new LongAdder();
Flux<String> flux =
Flux.just("unknown")
    .flatMap(k -> callExternalService(k)) 
    .doOnError(e -> {
        failureStat.increment();
        log("uh oh, falling back, service failed for key " + k); // <--- ERROR, no variable k
    })
    .onErrorResume(e -> getFromCache(k)); 
```

**Comment by simonbasle** [comment]
There is indeed an issue with these snippets: the `flatMap` should include the `*onError*` operators instead of closing after the `callExternalService(k)`...

See [these tests](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/test/java/reactor/guide/GuideTests.java#L447) that are meant to cover snippets from the reference guide.

Would you be willing to submit a PR on top of the `3.1.x` branch?

**Comment by aalku** [comment]
I never saw reactor code or documentation until this same morning. I don't think I should touch anything :D I just wanted to report what I thought it was a mistake. Thank you.
