### ISSUE TITLE
Mono map function with Kotlin

### ISSUE THREAD

**Issue by gimlet2** [reactor/reactor-core#1273]
### Expected behavior
Mapper function name shouldn't influence
### Actual behavior
If I map Mono, and then map it again it works as soon as mapper functions name is the same. Please check example below.
### Steps to reproduce
```
import reactor.core.publisher.Mono

class Example<A> {

    fun example1(input: Mono<API1<A>>): Mono<API1<A>> {
        return input.map(::map1).map(::map2) // error here - but if names are same it is ok
    }

    fun example2(input: Mono<API1<A>>): Mono<API1<A>> {
        return input.map(::map1).map(::map1)
    }

   fun example3(input: Mono<API1<A>>): Mono<API1<A>> {
        return input.map(::map1).map(this<A>::map2) // explisit type is also fine
    }
}

fun <A> map1(input: API1<A>): API2<A> {
    return API2(input.b)
}

fun <A> map1(input: API2<A>): API1<A> { // has the same signature as fun map2
    return API1(input.b)
}

fun <A> map2(input: API2<A>): API1<A> {
    return API1(input.b)
}

data class API1<B>(val b: B)
data class API2<B>(val b: B)
```

### Reactor Core version
3.1.8.RELEASE
### JVM version (e.g. `java -version`)
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
kotlinVersion = "1.2.50"
springBootVersion = "2.0.3.RELEASE"

**Comment by simonbasle** [comment]
I think this has nothing to do with Reactor and everything to do with Kotlin's type system and your hierarchy of classes. There's obviously a type ambiguity that the compiler can't resolve here with just the syntactic sugar of `::map1`:

```
error: type inference failed: Not enough information to infer parameter R in fun <R : Any!> map(mapper: ((Line_0.API1<A>!) -> R!)!): Mono<R!>!
```

**Comment by gimlet2** [comment]
But why it is fine when the function names are the same? why at all it depends on function name?

**Comment by simonbasle** [comment]
That's a question for the compiler experts in the Kotlin community ¯\_(ツ)_/¯ 
Maybe @sdeleuze has some insight though.

**Comment by sdeleuze** [comment]
Not sure, maybe raise the question in Kotlin Slack or bugtracker?

**Comment by gimlet2** [comment]
That what I did. Thank you for cooperation!
