### ISSUE TITLE
Flux.merge doesn't complete if inner Flux completes

### ISSUE THREAD

**Issue by Diagoras** [reactor/reactor-core#1279]
### Expected behavior

Completion of any Flux that is passed to `Flux.merge` results in the merged Flux also being completed. This is the same behavior seen with errors, where an error in any inner Flux is propagated to the merged Flux.

### Actual behavior

The merged Flux isn't completed and continues processing with one less source. Since this might not always be desired, a `delayCompletion` parameter similar to the existing `delayError` might be useful to allow configuration of how inner Flux completions are handled.

### Steps to reproduce

```java
final Flux<Long> flux1 = Flux.interval(Duration.ofSeconds(10));
final Flux<Long> flux1 = Flux.interval(Duration.ofSeconds(10));
final Disposable merged = Flux.merge(flux1, flux2).subscribe();
flux1.cancel();
merged.isCancelled(); // Will be false.
```

### Reactor Core version

3.1.8.RELEASE

### JVM version (e.g. `java -version`)

1.8

**Comment by smaldini** [comment]
I'm trying to reproduce this but I'm not sure I understand the issue, this works:

```java

@Test
	public void cancelledSource() throws Exception {
		final Flux<Long> flux1 = Flux.interval(Duration.ofSeconds(10)).log();
		final Flux<Long> flux2 = Flux.interval(Duration.ofSeconds(10)).log();
		final Disposable merged = Flux.merge(flux1, flux2).subscribe();
		merged.dispose();
		Assert.assertTrue(merged.isDisposed());
		Thread.sleep(100000);
	}```

```
13:09:51.771 [main] INFO  reactor.Flux.Interval.1 - onSubscribe(FluxInterval.IntervalRunnable)
13:09:51.778 [main] INFO  reactor.Flux.Interval.1 - request(32)
13:09:51.783 [main] INFO  reactor.Flux.Interval.2 - onSubscribe(FluxInterval.IntervalRunnable)
13:09:51.783 [main] INFO  reactor.Flux.Interval.2 - request(32)
13:09:51.785 [main] INFO  reactor.Flux.Interval.1 - cancel()
13:09:51.785 [main] INFO  reactor.Flux.Interval.2 - cancel()
true```

**Comment by akarnokd** [comment]
The `merge` operator merges items from all of its sources and completes when all sources complete by design.

I'm not sure why you wanted this particular behavior, but it can be achieved through sharing both sources so they can be used as parameters to `takeUntil`:

```java
Flux<Long> flux1 = Flux.interval(Duration.ofSeconds(1)).publish().autoConnect(2);
Flux<Long> flux2 = Flux.interval(Duration.ofSeconds(1)).publish().autoConnect(2);

Disposable merged = Flux.merge(flux1, flux2)
    .takeUntil(flux1.ignoreElements())
    .takeUntil(flux2.ignoreElements())
    .subscribe();
```

**Comment by Diagoras** [comment]
@smaldini I think your text code is incorrect - it's one of the inner fluxes that you need to cancel to demonstrate the issue.

@akarnokd Yeah, as I noted it's perfectly reasonable to want `merge` to behave the way it does. My situation involves multiple Fluxes with async sources getting merged together, where the completion or erroring of any of those sources means the entire merged Flux needs to cleanup resources and shutdown gracefully. Just continuing with the remaining async sources resulted in some seriously incorrect behavior, since datasources were dying without us logging the problem and restarting the process.

I only opened this issue since I noticed this behavior is configurable for errors (using the `delayError` parameter or the `mergeDelayError` method) so it seems to me that having an option for all terminal events might make sense. The `takeUntil` option is good to know, but it might get a little awkward when dealing with N arbitrary data sources that need to be merged together.

**Comment by smaldini** [comment]
Ha I think I see @Diagoras - you want to complete the merge as soon as one source completes, like zip.
In that case I would probably just use an error signal:

```java
Exception endError = new Exception();

Disposable merged = Flux.merge(
            flux1.concatWith(Mono.error(endError)), 
            flux2.concatWith(Mono.error(endError)))
    .onErrorResume(e -> e == endError ? Mono.empty() : Mono.error(e))
    .subscribe();```

**Comment by Diagoras** [comment]
@smaldini Yeah, I ended up switching to an error signal to ensure I got the behavior I wanted. I think that if nobody else needs a specific combinator for this case, you might as well close this issue for now. No use implementing it just for me.

Thanks.
