### ISSUE TITLE
Back-pressure not working proper on parallel flux

### ISSUE THREAD

**Issue by ksinghbora** [reactor/reactor-core#1280]
While I generate parallel flux from existing flux and subscribe with back pressure. It works partially.
Code is 

```
Flux<Integer> intFlux = Flux.just(1, 2, 3, 4, 5, 6, 7, 8);
 intFlux.doOnNext(data -> System.out.println("Next" + data))
            .parallel()
            .subscribe(new BaseSubscriber<Integer>() {
                @Override
                protected void hookOnSubscribe (Subscription subscription)
                {
                    request(1);
                }

                @Override
                protected void hookOnNext (Integer value)
                {
                    System.out.println("Next request ");
                    // request(1);
                }
            });
```
### Expected behavior
Only one "Next1" should print.
### Actual behavior
"Next1"..."Next8" are printing.
Note - If I remove parallel(), It will work as expected.
However code inside subscribe will execute only one time. Thats why I am saying this partial back pressure.
### Steps to reproduce
Run the code.
### Reactor Core version
3.1.7-RELEASE
### JVM version (e.g. `java -version`)
1.8

**Comment by madgnome** [comment]
`parallel()` honors backpressure **downstream**: in your `Subscriber` you're requested 1 and you are receiving one (`Next request` only printed once).

`parallel()` will by default request `Queues.SMALL_BUFFER_SIZE=256` **upstream** for efficiency purposes. You can change that by modifying the `prefetch` parameter when calling `parallel()`.

Another thing in play here is going from `ParallelFlux` to `Flux` when you want to subscribe.
When you call `subscribe()` on a `ParallelFlux` it's like calling `parrallel().sequential().subscribe(...)`
By default the `sequential` operator will prefetch up to `Queues.SMALL_BUFFER_SIZE=256` upstream as well.

**Comment by ksinghbora** [comment]
parallel(1,1) didn't work, however flatMapSequential(mapper,1,1) worked.

**Comment by madgnome** [comment]
`parallel(1,1)` doesn't work because you still have the implied `sequential()` call when doing `subscribe` it will work if you do `parallel(1,1).sequential(1).subscribe()`

**Comment by ksinghbora** [comment]
oh wow, It is working.  We need little more documentation . I will try to write some blog on this. Thanks @madgnome

**Comment by ksinghbora** [comment]
@madgnome Want to ask one more thing not related to this issue. 

Can we get insert sequence back from parallel()  without using sorting ?

**Comment by madgnome** [comment]
What do you mean?

**Comment by ksinghbora** [comment]
I mean if we apply parallel() to a flux and again make it sequential. Can we make sure we are getting element in same order as they insert in original flux without using sorting method?
like 
```
Flux.just(1, 2, 3, 4, 5, 6, 7, 8).parallel().runOn(Schedulers.parallel()).map(mapper).sequential().subscribe(System.out::println);
```
Can I ensure o/p - 1,2,3,4,5...

**Comment by madgnome** [comment]
I don't think it's possible without using some sorting, for example:

```
Flux.zip(Flux.just(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L),
				Flux.range(0, Integer.MAX_VALUE))
	       .parallel()
		    .sorted(Comparator.comparing(Tuple2::getT2))
		    .map(Tuple2::getT1)
		       .subscribe(new BaseSubscriber<Long>() {


			       @Override
			       protected void hookOnNext (Long value)
			       {
				       System.out.println("Next request " + value);
			       }
		       });
```

**Comment by simonbasle** [comment]
@ksinghbora for that last question, there's an `ordered` operator that works similar to `sequential` but uses a `Comparator` to choose which "rail" to pick. Combine that with `index()` upstream of the `parallel` call and you can get the order back, although you now have to deal with `Tuple2` in your parallel operations.
