### ISSUE TITLE
add log method with custom log message

### ISSUE THREAD

**Issue by helmbold** [reactor/reactor-core#1283]
Using the `log` method is often the best way to understand the flow of data, but the log messages sometimes contain too much noise. Therefore it would be useful to be able to customize the log output.

## Current Behavior

In the following (Kotlin) example the class `Message` contains meta data fields not relevant to understand the logic:

```kotlin
data class Message<T>(
        val value: T,
        val timestamp: Instant,
        val quality: Int,
        val source: String)

val source = Flux.just(
        Message(1, Instant.now(), 99, "A"),
        Message(2, Instant.now(), 98, "B"),
        Message(3, Instant.now(), 97, "A"))

source.filter { it.value > 1 }.log("category").subscribe()
```

The output would be

```
13:17:52.726 [main] DEBUG reactor.util.Loggers$LoggerFactory - Using Slf4j logging framework
13:17:52.770 [main] INFO  category - | onSubscribe([Fuseable] FluxFilterFuseable.FilterFuseableSubscriber)
13:17:52.773 [main] INFO  category - | request(unbounded)
13:17:52.774 [main] INFO  category - | onNext(Message(value=2, timestamp=2018-07-18T11:17:51.010Z, quality=98, source=B))
13:17:52.810 [main] INFO  category - | onNext(Message(value=3, timestamp=2018-07-18T11:17:51.010Z, quality=97, source=A))
13:17:52.811 [main] INFO  category - | onComplete()
```
## Behavior of new `log` method

But I'd like to be able to print only the `value` of the `Message` class. So I'd need a variant of the `log` method, something like this:

```kotlin
source.filter { it.value > 1 }.log("category") { it.value }.subscribe()
```

or in Java

```java
source.filter(message -> message.value > 1).log("category", message -> message.value).subscribe()
```

The output should be:

```
13:17:52.726 [main] DEBUG reactor.util.Loggers$LoggerFactory - Using Slf4j logging framework
13:17:52.770 [main] INFO  category - | onSubscribe([Fuseable] FluxFilterFuseable.FilterFuseableSubscriber)
13:17:52.773 [main] INFO  category - | request(unbounded)
13:17:52.774 [main] INFO  category - | onNext(2)
13:17:52.810 [main] INFO  category - | onNext(3)
13:17:52.811 [main] INFO  category - | onComplete()
```

The function parameter of the `log` method should have the type `T -> Object` and the `Object` should then be rendered as `String`.

**Comment by simonbasle** [comment]
That seems like a possible improvement. The obvious workaround is to use `doOnEach` (or more restrictive `doOn*` methods) to manually log part of the value, using a user-instantiated `reactor.util.Logger`.

**Comment by helmbold** [comment]
Thank for implementing my suggestion! I'm a very happy Reactor user :-)

**Comment by simonbasle** [comment]
I'm not sure about the amount of variants in the extra API though... For that variant we might want to remove some extraneous overrides, like the ones with no `Level` and/or the ones with `options`.

**Comment by simonbasle** [comment]
another workaround would be to rely on the logging framework underneath to achieve this functionality, if available. For example, logback has the `Message` trait. But that couples your code to that particular framework...

**Comment by simonbasle** [comment]
After experimenting a bit more with this and reviewing the PR, we don't feel that adding 5 or more variants of log just for the sake of mapping the values in the log is worth it. This feels more like a log-formatting issue that can be addressed either directly at the logging framework level (see `Message` suggestion above) or in an adhoc way using `doOnNext` / `doOnEach` and a manually obtained `Logger`.
