### ISSUE TITLE
Add method to log virtual time

### ISSUE THREAD

**Issue by helmbold** [reactor/reactor-core#1285]
Using virtual time in tests is a great way to reduce wait times, however it makes the timestamps logged by the logger somewhat useless. If I debug some tricky timing behavior I switch to real time to see whether the timing behavior is correct.

It would be helpful to have a method like `logVirtualTime()` that just prints the virtual time.

**Comment by helmbold** [comment]
Thanks for the tip to use `elapsed`.

Just in case someone else needs such a functionality, I post my Kotlin extension function here:

```kotlin
fun <T> Flux<T>.logTime(): Flux<T> {
    var totalMillis = 0L
    return this.elapsed()
            .map { timeAndValue ->
                totalMillis += timeAndValue.t1
                println("total ms: $totalMillis")
                timeAndValue.t2
            }
}
```

You can use like any other method of `Flux`: 
```kotlin
StepVerifier.withVirtualTime {
    Flux.just(1, 2, 3, 4)
        .delayElements(Durations.ofMillis(999))
        .logTime() // call it like any other method
        .map { ... }
        .filter{ ... }
}
    .expectSubscription()
    .thenAwait(Durations.ofMillis(999))
    ...
    .verifyComplete()
```

It might make sense to use a logger instead of `println`, but I didn't feel the need in my tests.

**Comment by helmbold** [comment]
@simonbasle My extension function was again very useful to fix a test. What do you think of including it in the [StepVerifierExtensions](https://github.com/reactor/reactor-core/blob/master/reactor-test/src/main/kotlin/reactor/test/StepVerifierExtensions.kt)?

If you would agree, I'd suggest to 

* add an optional parameter `category` to the `logTime` function, to be able to tell the output of different locations apart and 
* to replace `println` with a logger.

**Comment by simonbasle** [comment]
Yeah that makes sense as a Kotlin method extension provided it uses a `Logger`, I think (cc @smaldini)
@sdeleuze what do you think about the idea of adding a `Flux` extension to `StepVerifierExtensions.kt`? does that make sense, the idea being to imply that this is a test-only feature?
