### ISSUE TITLE
Review internal operator for naming and stack polishing

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1307]
Operators implementors could do with a review of its property name for readability purpose and evaluating the stack size operators might use for optimization purpose.
Explicit Inlining should be used to avoid having more than 2 levels of stack by operator when reacting to a signal.

**Comment by simonbasle** [comment]
This has been in the backlog for so long that I think it would make better sense to open an issue on specific operator(s) when their stack depth is noticed as too deep, closing this for now.
