### ISSUE TITLE
Introduce RxJava style typed lift(Operator<V,R> op) operator for chaining custom operators

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#131]
Occasionally there is a need to create and use custom operators.  There are two possible approaches for doing this:

**1.** Extend Flux/Mono implementing the new operator using a FluxSource implementation and exposing it as a new method e.g `MyFlux.mapOrFilter()`.
**2.** Use an existing Flux/Mono operator which allows for the use and chaining of custom alongside built-in operators.

It is clear that 1. is the most optimal approach due to the way it simply wraps the existing publisher and requires less allocations, and this is the approach used internally by Flux itself as well as by RSC and RxJava2 based on research by @akarnokd.  That said, having to extend Flux and add a method that uses FluxSource shouldn't, in my opinion, be to only way you can easily use a custom operator.

Here I will run through the current options for using a custom operator (implemented using OperatorAdaptor) without extending Flux and the issues the approaches have.  In the examples I will use a fictitious MapOrFilterOperator that extends OperatorAdaptor with a use case where I have a list of peoples names and need to output the list of everyones ages at their next birthday.  The age lookup is provided by an existing service which provides the age data and returns `null` if no data is available.  The resulting list of ages printed should include only the value for whom we have data. 

**1. Use FluxSource** 

```
Flux<String> names = Flux.just("dan", "stephane");
new FluxNullSafeMap<>(names, name -> lookupAge(name)).map(i -> i + 1).subscribe(System.out::println);
```

- Chaining with existing flux is not possible because FluxSource needs flux instance pass in constructor. Forward chaining is possible.

**2. Use Lift(Function<Subscriber, Subscriber> (removed in 2.5.0.M4)**

```
Flux<Integer> ages = Flux.just("dan", "stephane").lift(s -> new NullSafeMapOperator<>(s, name -> lookupAge(name)));
ages.map(i -> i + 1).subscribe(System.out::println);
```
- Chaining with existing flux is possible *but* forward chaining is not possible as there is no type information is propagated with this approach.

**3. Use Transform (introduced in 3.0.0)**

```
Flux<Integer> ages = Flux.just("dan", "stephane").transform(flux -> s -> new NullSafeMapOperator<String, Integer>(s, name -> lookupAge(name)));
ages.map(i -> i + 1).subscribe(System.out::println);
```
- Chaining with existing flux is possible *but* forward chaining is not possible as there is no type information is propagated with this approach.
- While this approach works, I don't personally consider it simple/intuitive.

**Summary**

While there a clearly multiple ways to do this, none of the approach are optimal because of issues with method chaining to generic type propagation.  This problem is already solved in RxJava with the  `lift(Operator<I, O>)` and as far as I understand provides this experience.

```
Flux.just("dan", "stephane").lift(new NullSafeMapOperator(name -> lookupAge(name))).map(i -> i + 1).subscribe(System.out::println);
```

Is there any reason why this shouldn't be introduced in reactor too?

See: https://github.com/ReactiveX/RxJava/wiki/Implementing-custom-operators-(draft)  (search for "_The lift operator_".

**Comment by dfeist** [comment]
I added a test case which shows these different options in a runnable/modifiable test case here: https://github.com/reactor/reactor-core/pull/134

This PR is not a proposed merged, but rather to use review options.  I pulled the old lift() implementation back in here, just in order to compare it's use to transform(), FluxSource and rxJava style lift.

**Comment by akarnokd** [comment]
Why not do the following:

```java
public static <T, R> Function<Flux<T>, Flux<R>> 
        lifter(Function<Subscriber<? super R>, Subscriber<? super T>> onLift) {
    return flux -> child -> flux.subscribe(onLift.apply(child));
}

Flux.range(1, 10).as(lifter(s -> new CustomOp(s, params...))).etc.etc.
```

**Comment by dfeist** [comment]
@akarnokd This isn't optimal approach IMO, but i added it for comparison in another commit.  I couldn't chain with this approach either though so it doesn't compile as is.  See https://github.com/reactor/reactor-core/pull/134/files#diff-96d45cdbc64d62e7b1ba6c7b98da5e16R75

**Comment by smaldini** [comment]
So as discussed on Gitter and offline, I consider introducing `handle(BiConsumer<SynchronousSink<R>, T>)` which would allow to also give a solution for #86.

The callback will allow drop on error, filtering, take and other few operators patterns. Asynchronous logic can be implemented through 'flatMap', 'concatMap and 'then' nevertheless.

**Comment by dfeist** [comment]
This approach should also give a concise solution for use case like #49 and #74 without requiring the use of a `concatMap()`.  Need to see if generic type propagation can be achieved or not, else it might be a pain to chain. 

**Filter On Error**
```
.handle((data, sink) -> {
  try { 
    sink.next(doSomething());
  } catch(Throwable e) {
    // Drop event 
  }
}).subscribe();
```

**Filter On Null**
```
.handle((data, sink) -> {
   T result = mapper.apply(data)
   if(result != null) sink.next(result);
}).subscribe();
```

**Wrap exception before subscriber.onError()**
```
.handle((data, sink) -> {
  try { 
    sink.next(doSomething(data));
  } catch(Throwable e) {
    sink.error(new WrappedException(data, e);
  }
}).subscribe();
```

**Comment by smaldini** [comment]
Available in latest commits
