### ISSUE TITLE
Why Flux.toIterable cannot happen in non-blocking thread

### ISSUE THREAD

**Issue by zzhao0** [reactor/reactor-core#1313]
https://github.com/reactor/reactor-core/blob/383453706fe441a74b82462ea65d6190ea0bfffd/reactor-core/src/main/java/reactor/core/publisher/Flux.java#L8410

Sorry, I did not find a better channel to ask this. So filing as an issue here.

## Problem description
Flux.toIterable() itself is lazy. BlockingIterable.iterator() is the place where a new subscription is created and even that doesn't seem to require true blocking behavior since iterator.next()/hasNext() is where it actually blocks on stream elements.

In contrast. Mono.toFuture() news up a Future with a new subscription. It can happen in non-blocking thread.

## Version
latest trunk

## Proposed fix
Move the check to place where blocking behavior is really needed

**Comment by smaldini** [comment]
Its actually a good point. I need to remember why we put it here, the prefetch is non blocking too, only next() might be the issue indeed.

**Comment by zzhao0** [comment]
Thanks a lot for the quick fix, @simonbasle
