### ISSUE TITLE
Replace String.replaceAll with Matcher.replaceAll in Scannable and InnerConsumer

### ISSUE THREAD

**Issue by pdudkiewicz** [reactor/reactor-core#1315]
Currently `reactor.core.Scannable.stepName` methods compiles Pattern for String replacement each time it's called because `String.replaceAll` is used. 
Consider extracting Patterns to constants and using `Matcher.replaceAll` instead.

**Comment by simonbasle** [comment]
That is a very good point. Would you care to open a PR? 😃

**Comment by pdudkiewicz** [comment]
ok, will do in the next few days

**Comment by pdudkiewicz** [comment]
I took a look at it.   
In order not to pollute Scannable interface with constant and to remove copy paste from InnerConsumer 
some static utility class would have to be introduced. I'm not a fan of such solution though. Do you have any better idea?

**Comment by simonbasle** [comment]
not really seeing an alternative. I think a constant in `Scannable` is acceptable.

**Comment by simonbasle** [comment]
@pdudkiewicz not really seeing an alternative. I think a constant in `Scannable` is acceptable.

**Comment by pdudkiewicz** [comment]
I've opened a pull request. Take a look: https://github.com/reactor/reactor-core/pull/1324
Two questions: 
* is javadoc needed for pattern?
* I don't know why replacement was done in two steps, please verify if it's fine to do this in one step
