### ISSUE TITLE
Support for side-effects *after* subscribing to a stream

### ISSUE THREAD

**Issue by stavalfi** [reactor/reactor-core#1316]
* I have a flux, `flux1`, which receives signals of TCP messages.
* I use Redux design pattern to notify another module in my app to start sending TCP messages to me by changing the "global status" of my app to: "started listening to incoming messages." 
* __The problem is:__  I can't find a way to notify about the new status without risking losing incoming signal(s) to `flux1` flux.

Demo:

```java
f1.doOnSubscribe(subscription -> create a new  global status: "started listening to incoming messages")
   ........do something with the incoming TCP messages.......
   ..........................................................
```

I sometimes encounter a scenario where the other module in my app receive the new global status and start sending messages, but `flux1` didn't subscribe yet. As a result, I lose (mostly) a single `next signal`.

A possible solution from reactor team side: create `doAfterSubscribe(lambda)` operator who runs the `lambda` in a different thread then the thread is using to listen to incoming signals.

Sulotions in the current API:
1. Record `flux1` using `replay` operator. 
* Advantages: It will work.
* Disadvantages: As far as I understand, it's not the best approach to solve this problem because I will not consume the records more than one time and this operator is not here to solve race-conditions. Also, the operator const lot's of resources and I don't know how much __exctaly__ to record (I can't guess). 

-----

#### From Reactor Core Gitter:

> Stav Alfi @stavalfi Aug 11 00:52
Hi guys! Questions - doOnSubscribe operator is called before or after the subscription? Is it possible for the stream to lose signals while the doOnSubscribe's lambda running?
Thanks!!!

Response:

>Simon Baslé @simonbasle Aug 13 12:08
@stavalfi confirmed, the lambda is invoked before the subscription signal is propagated up to the source operator
so conceptually (ie. avoid doing this!), Thread.sleep(100) in the lambda of doOnSubscribe would delay the subscription by 100ms, rather than miss 100ms worth of emissions

Confirmation:
```java
Flux<Long> longFlux = Flux.interval(Duration.ofSeconds(1))
        .publish()
        .autoConnect(0);

longFlux.doOnSubscribe(__ -> {
    try {
        Thread.sleep(5 * 1000);
    } catch (InterruptedException e) {
        e.printStackTrace();
    }
}).subscribe(System.out::println);
```
### Actual behavior
```java
5
6
7
8
...
```

**Comment by simonbasle** [comment]
@stavalfi careful, in that "Confirmation" snippet you are actively countering the `doOnSubscribe` delay by turning the `interval` source into a **hot** `Publisher`!

By using `autoConnect(0)`, you demand that the source is connected to **immediately**, no matter when the `doOnSubscribe(...).subscribe(...)` is actually done. Note that replacing with `autoConnect(1)` gives you the desired behavior, because now it will wait for the `doOnSubscribe` subscription before subscribing to the `interval` above.

Can you detail how you construct that `flux1`?

**Comment by stavalfi** [comment]
The example I provided didn't describe my scenario.

The source of my problem is that Java IO is blocking so I can't notify to someone that I started listening to socket after I started listening to that socket because the API is blocking. The new Java NIO API is not blocking so I can do what I'm trying to achieve.

Simple Example from the old Java API to handle sockets: (from https://systembash.com/a-simple-java-tcp-server-and-tcp-client/)

```java
        String clientSentence;
        String capitalizedSentence;
        ServerSocket welcomeSocket = new ServerSocket(6789);

        while (true) {
            Socket connectionSocket = welcomeSocket.accept();
            BufferedReader inFromClient =
                    new BufferedReader(new InputStreamReader(connectionSocket.getInputStream()));
            DataOutputStream outToClient = new DataOutputStream(connectionSocket.getOutputStream());
            
            
            clientSentence = inFromClient.readLine();
            // <<< ---- I can't notify other classes that I started listening because the above call is blocking.
            
            System.out.println("Received: " + clientSentence);
            capitalizedSentence = clientSentence.toUpperCase() + 'n';
            outToClient.writeBytes(capitalizedSentence);
```

Thanks for your time @simonbasle
