### ISSUE TITLE
Intuitive parameter names for `Flux.buffer(Duration timespan, Duration timeshift)`

### ISSUE THREAD

**Issue by thekalinga** [reactor/reactor-core#1331]
The name of method parameters for Flux that allows us to buffer element with capture period & new window period is `Flux.buffer(Duration timespan, Duration timeshift)`

The names `timespan` & `timeshift` are quite cryptic & hard to remmeber unless we refer to documentation. If we renamed these names to something like `capturePeriod` & `newBufferCreationPeriod` (or may be even better names), the method arguments become much more intuitive

**Comment by simonbasle** [comment]
cc @smaldini 
How about:

 - `bufferingTimespan`: keep the notion of the spanning of the buffer, indicates this is how long the operator buffers
 - `openBufferEvery`: the `timeshift` part is IMHO the most cryptic. This could better indicate this is the period at which the buffers are opened.

**Comment by simonbasle** [comment]
Additionally: 
 - `bufferTimeout` could use `maxTime` instead of `timespan`
 - `window` and `windowTimeout` could have similar changes (using `window` word instead of `buffer`)
 - the marbles should probably be changed (after the conversion to SVG source is done?)

**Comment by thekalinga** [comment]
@simonbasle How about renaming `buffer(int maxSize, int skip)` to `buffer(int maxSize, int openBufferEvery)`

`skip` is also not that intuitive & also people will have to remember one name
