### ISSUE TITLE
Inconsistent type of the empty / completable mono.

### ISSUE THREAD

**Issue by NeveHanter** [reactor/reactor-core#1336]
`Mono.empty()` static method uses generic cast, which allows deduction to any `Mono<T>` and that is inconsistent with `Mono.then()` instance method behavior which returns `Mono<Void>` or the result of invoking i.e. `Mono.empty().doOnTerminate()` which returns `Mono<T>` without the generic cast after deducting `Mono.empty()` to `Mono<Object>`.

### Expected behavior
```
Mono<Void> mono = Mono.empty()
    .doOnTerminate(() -> {});
```
would compile like the `Mono.empty()` alone or
```
Mono<Void> mono = Mono.just(1)
    .then()
    .doOnTerminate(() -> {});
```
would do.

### Actual behavior
Compilation fails with the following error:
`error: incompatible types: Mono<Object> cannot be converted to Mono<Void>`

### Steps to reproduce
Use the snippet from the expected behavior section.

### Reactor Core version
3.1.7.RELEASE

### JVM version (e.g. `java -version`)
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by simonbasle** [comment]
The compiler can only help you to a certain level. With only `Mono.empty()`, the compiler can deduce the type `T` from the left hand side. With chaining, the left-hand side becomes the `empty` part, which by itself doesn't hint at the generic type.

The `Mono<Void>` type for `doOnTerminate` is completely incorrect. What you need is to either split into several variables or be explicit about `<T>` on the empty:

```
Mono<String> a = Mono.empty();
Mono<String> b = a.doOnTerminate(() -> {});

//which is equivalent to:
Mono<String> c = Mono.<String>empty()
    .doOnTerminate(() -> {});
```
