### ISSUE TITLE
takeUntil() that behaves similarly to filterWhen() ?

### ISSUE THREAD

**Issue by mrusinak** [reactor/reactor-core#1352]
I have a scenario where I have a pool of items that can be used up, and a list of pending items that were stored if they came in when the pool was empty.

    class ResourcePool {
        Mono<Integer> getAvailableCount();
    }

    class PendingRequests {
        Flux<PendingRequest> getPendingRequests();
    }

When the pool gains more resources, I want to try and fulfill as many pending requests as possible. However, requests could still be coming in while this is happening, so I want to stop as soon as the pool is exhausted again.

    public Mono<Void> fulfillPendingRequestsJob() {
        pendingRequests.getPendingRequests()
                       .takeUntil(this::resourcesNotAvailable)
                       .map(this::fulfillRequest)
                       .then()
    }

    private boolean resourcesNotAvailable(final PendingRequest data) {
        final Integer count = resourcePool.getAvailableCount().block();
        final boolean result = count == null || count <= 0;

        if (result) {
            LOG.info("No more resources");
        }

        return result;
    }

Two important things to note are that my predicate has to block on the available count, and that this code will wind up being actually executed on `Schedulers.parallel()`. Previously this worked fine; with the current version of Reactor however this now throws an error, as it does not like `block()` being used when subscribed on a non-immediate thread.

I understand that using block() should be avoided, but currently I don't see a way to accomplish what I want without a new `takeUntil` method that can resolve a Boolean asynchronously. I can cheat by doing something silly like using a `CompletableFuture` and subscribing instead of blocking, but that feels bad :)

**Comment by simonbasle** [comment]
Isn't the `takeUntilOther` operator fitting the bill?

**Comment by mrusinak** [comment]
I could certainly write a blocking `availableCount` , but in general I was trying to keep all my network related operations as `Mono` 's (since the resource could be something like a cache or database).

To be clear, I definitely don't want to mess around with `Flux` - I want to use a predicate that might have been farmed off to another thread or is coming from a library that is exposing `Mono` check. In current versions of reactor I wind up needing to play games with `CompleteableFuture` & `subscribe()` since `block()` isn't allowed if the stream is using `parallel()` (an exception is thrown).
