### ISSUE TITLE
RejectedExcecutionException not being thrown from 3.2.0-M1 to 3.2.0-M2

### ISSUE THREAD

**Issue by mbuchwald** [reactor/reactor-core#1362]
While upgrading from 3.2.0-M1 to 3.2.0-M2 we got a performance degradation in some scenarios with high concurrency. This is caused because in those cases, we want to handle retries in case we get a `RejectedExcecutionException`: 
```
just(event)
           .transform(getTransformer())
           .retryWhen(onlyIf(ctx -> RejectedExecutionException.class.isAssignableFrom(unwrap(ctx.exception()).getClass()))
              .backoff(ctx -> new BackoffDelay(ofMillis(2), ZERO, ZERO))
              .withBackoffScheduler(getScheduler()));
// we basically check if RejectedExcecucionException is the cause of the exception thrown
```
After profiling, we found out that the retry logic is not being executed. This might be caused by a change in behaviour that was throwing a RejectedExecutionException, but now doesn't. 
We checked with 3.2.0-M3, 3.2.0.M4 and 3.2.0-RC1 and we are getting similar results.

**Comment by simonbasle** [comment]
Can you provide a more comprehensive self-executing reproduction case?
Or at least expand on when you expect the `RejectedExecutionException` would happen and how would the `getScheduler()` work to recover from that?

**Comment by simonbasle** [comment]
@mbuchwald ping for more info / self-contained reproduction code

**Comment by mbuchwald** [comment]
@simonbasle it was an error on our side. After upgrading from M1 we needed to change some parts of our pipeline.
