### ISSUE TITLE
EmitterProcessor not Emitting Items from Publisher it is subscribed to

### ISSUE THREAD

**Issue by Sage-Pierce** [reactor/reactor-core#1364]
### Expected behavior
EmitterProcessor emits items from publisher to which it is subscribed

### Actual behavior
EmitterProcessor doesn't emit anything except completion

### Steps to reproduce
    import java.util.concurrent.atomic.AtomicReference;
    
    import org.junit.Test;
    import org.reactivestreams.Subscriber;
    import org.reactivestreams.Subscription;
    
    import reactor.core.CoreSubscriber;
    import reactor.core.publisher.BaseSubscriber;
    import reactor.core.publisher.EmitterProcessor;
    import reactor.core.publisher.Flux;
    import reactor.core.publisher.FluxOperator;
    import reactor.core.publisher.Mono;
    
    import static org.junit.Assert.assertEquals;
    
    public class EmitterProcessorEmissionBug {
    
        @Test
        public void expose() {
            AtomicReference<String> result = new AtomicReference<>();
    
            Mono.just("DATA")
                .subscribeWith(EmitterProcessor.create())
                .transform(LowerCasingOperator::new)
                .subscribe(result::set);
    
            assertEquals("data", result.get());
        }
    
        private static final class LowerCasingOperator extends FluxOperator<String, String> {
    
            protected LowerCasingOperator(Flux<? extends String> source) {
                super(source);
            }
    
            @Override
            public void subscribe(CoreSubscriber<? super String> actual) {
                source.subscribe(new LowerCasingSubscriber(actual));
            }
        }
    
        private static final class LowerCasingSubscriber extends BaseSubscriber<String> {
    
            private final Subscriber<? super String> subscriber;
    
            private LowerCasingSubscriber(Subscriber<? super String> subscriber) {
                this.subscriber = subscriber;
            }
    
            @Override
            protected void hookOnSubscribe(Subscription subscription) {
                subscriber.onSubscribe(subscription);
            }
    
            @Override
            protected void hookOnNext(String value) {
                subscriber.onNext(value.toLowerCase());
            }
        }
    }

### Reactor Core version
3.1.9.RELEASE, 3.2.0.RELEASE

### JVM version (e.g. `java -version`)
1.8.0_102

Note: The above test works with Reactor Core version 3.1.8.RELEASE. It also works with 3.1.9.RELEASE if `EmitterProcessor.create()` is replaced with `UnicastProcessor.create()`

**Comment by smaldini** [comment]
There is a regression with scalar sources to be fixed in 3.2.1 - 3.1.10  you can workaround by adding ```hide()``` after your just() or any scalar source (fromArray etc)

**Comment by Sage-Pierce** [comment]
@smaldini solid, thanks!

**Comment by simonbasle** [comment]
Regression introduced by #1291. @artembilan has been validated that the fix doesn't reintroduce #1290 :+1:

**Comment by simonbasle** [comment]
This has been forward-merged into master
