### ISSUE TITLE
Null Pointer exception after hours running

### ISSUE THREAD

**Issue by rotilho** [reactor/reactor-core#1379]
### Expected behavior
No exception
### Actual behavior
Throwing exception
```
2018-10-08 14:38:41:809 [parallel-4] ERROR reactor.core.scheduler.Schedulers - Scheduler worker in group main failed with an uncaught exception
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
	at reactor.core.publisher.FluxReplay$SizeBoundReplayBuffer.add(FluxReplay.java:751)
	at reactor.core.publisher.ReplayProcessor.onNext(ReplayProcessor.java:440)
	at com.rotilho.jnano.node.EventBroker.publish(EventBroker.kt:24)
```
### Steps to reproduce
It happens after hours of execution, I can't see any specific pattern.

I'm using ReplayProcessor.create<Any>(2024) to manage events inside my application

### Reactor Core version
3.2.0.RELEASE
### JVM version (e.g. `java -version`)
version 1.8.0_171

**Comment by akarnokd** [comment]
Did you make sure you invoked `ReplayProcessor.onNext` non-concurrently? The specific location can only NPE if there is a concurrent invocation that breaks the internal state of the buffer.

**Comment by rotilho** [comment]
So this is the reason then. I'm using it as replacement to event bus where different sources can publish events on it as suggested [here](https://github.com/reactor/reactor-core/issues/375#issuecomment-273438773)

Does the Emitter have similar problem? Are there any Processor which can be concurrently called?

**Comment by smaldini** [comment]
Try to use FluxProcessor.sink() and keep a reference to the returned FluxSink.
Calls to FluxSink#next will be serialized.

**Comment by rotilho** [comment]
Works but a too slow. I need to figure out a better way. Thanks for the help @smaldini
