### ISSUE TITLE
Mono.metrics() throws NoClassDefFoundError if micrometer not on classpath

### ISSUE THREAD

**Issue by kennymacleod** [reactor/reactor-core#1383]
### Expected behavior

If I call `Mono.metrics()` (or `Flux.metrics()`), and micrometer is not on the classpath, then this should be a no-op. This is what the javadoc for those methods say should happen.

### Actual behavior

`java.lang.NoClassDefFoundError: io/micrometer/core/instrument/MeterRegistry` is thrown.

### Steps to reproduce

Run this test without micrometer on the classpath:

    @Test
    public void test() {
        Mono.just("foo").metrics();
    }

This would appear to be the fault of the `FluxMetrics` class, which has a `isMicrometerAvailable` method which is being correctly checked by `Mono.metrics()`, but the `FluxMetrics` class itself cannot be loaded if micrometer is not on the classpath, mostly likely because it uses micrometer types in its method signature.

The reactor-core test suite isn't catching this, because it always has micrometer on its classpath.

### Reactor Core version

3.2.0.RELEASE

### JVM version (e.g. `java -version`)

> openjdk version "1.8.0_181"
> OpenJDK Runtime Environment (Zulu 8.31.0.1-macosx) (build 1.8.0_181-b02)
> OpenJDK 64-Bit Server VM (Zulu 8.31.0.1-macosx) (build 25.181-b02, mixed mode)

**Comment by simonbasle** [comment]
![](https://media.giphy.com/media/nspvD8XYqUxP2/giphy-downsized.gif)
That's embarrassing! I favored having Micrometer on the test classpath and performing unit testing of metrics related functionalities, which made testing the case of no Micrometer more complicated. I thought I remember at least testing the early snapshots of the original PR in a separate project without Micrometer, but it seems this has rapidly devolved into a basic mistake of having Micrometer classes used at the same level the `isMicrometerAvailable()` check is offered.
