### ISSUE TITLE
share/refcount/refcountgrace can ignore repeat/retry re-subscriptions

### ISSUE THREAD

**Issue by petringo** [reactor/reactor-core#1385]
### Expected behavior

In `Flux.interval(d).map(fn).share().retry(n)` the upstream of `share()` should be resubscribed on retry, when an error is signaled within `map()`.

### Actual behavior

The `map()` and `interval()` Fluxes are never resubscribed on retry. It seems that the `share()` Flux still holds reference to the subscription
terminated by the error and never resubscribes upstream.

### Steps to reproduce

Run the following test:

```
@Test
public void testIntervalMapShareRetry() throws InterruptedException {
    final Flux<Long> flux = Flux.interval(Duration.ofMillis(250)).transform(report("interval"))
            .map(round -> {
                if (round == 3) {
                    throw new RuntimeException();
                }
                return round;
            }).transform(report("map"))
            .share().transform(report("share"))
            .retry(3).transform(report("retry"));

    final Disposable disposable = flux.subscribe(System.out::println);

    Thread.sleep(5_000);
    System.out.println("Timeout; disposing all");
    disposable.dispose();
}

private static <T> Function<Flux<T>, Publisher<T>> report(final String name) {
    return flux -> flux
            .doOnSubscribe(s -> System.out.println("onSubscribe " + name + " " + s))
            .doOnEach(s -> System.out.println(s.getType() + " " + name))
            .doOnCancel(() -> System.out.println("onCancel " + name));
}
```

The last round causing error outputs:

```
onNext interval
onCancel interval
onError map
onError share
onSubscribe share reactor.core.publisher.FluxRefCount$RefCountInner@72321294
Timeout; disposing all
onCancel retry
onCancel share
```

Another subscription after error resubscribes to upstream of `share()`, emitting events to both subscriptions until next error is signaled.

```
    //final Disposable disposable = flux.subscribe(System.out::println);
    final Disposable.Composite disposable = Disposables.composite();
    disposable.add(flux.subscribe(System.out::println));
    Thread.sleep(3_000);
    disposable.add(flux.subscribe(System.out::println));
```

This issue does _not_ appear if the root Flux is something executed in same thread, e.g.

```
Flux.fromStream(() -> LongStream.range(0, 10).boxed()).transform(report("stream"))
```

or if a scheduler to new thread is added after `share()`

```
            // ...
            .share().transform(report("share"))
            .subscribeOn(Schedulers.newSingle("newSingle scheduler")).transform(report("scheduler"))
            .retry(3).transform(report("retry"));
```

### Reactor Core version

3.2.1.RELEASE

### JVM version (e.g. `java -version`)

```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by simonbasle** [comment]
This is due to a bug in `FluxRefCount` (and `FluxRefCountGrace` as well) were the terminating signal is propagated downstream before the connection state has been reset. As a result, when retrying/repeating, the refcount operator receives a "re-subscribe" signal that it ignores because it thinks there is still an upstream active subscription.

**Comment by simonbasle** [comment]
note on forwarding to 3.2: needs a bit of adaptation in the test due to the `repeat(N)` change (decrease the repeat counter by 1).
