### ISSUE TITLE
Fix marble for Flux.next()

### ISSUE THREAD

**Issue by daniildxb** [reactor/reactor-core#1399]
### Described behaviour
Take one element from the stream and ignore rest.
![current_marble_next](https://user-images.githubusercontent.com/15066286/47295207-c1dedc00-d617-11e8-814c-7fc69ca99b7b.png)

### Actual behaviour
Take one element from the stream and cancel subscription.

![next](https://user-images.githubusercontent.com/15066286/47295169-b25f9300-d617-11e8-92c2-fb7ac8f55a26.png)

### Code reference
`Flux.next()` returns `MonoNext`, which cancels subscription `onNext`. However cancel is absent on a marble.

```
		@Override
		public void onNext(T t) {
			if (done) {
				Operators.onNextDropped(t, actual.currentContext());
				return;
			}

			s.cancel();
			actual.onNext(t);
			onComplete();
		}
```
### Reactor Core version
3.2.1

**Comment by simonbasle** [comment]
As said in the PR, the essence of this diagram is showing how a `Flux` (multiple elements) is turned into a `Mono` (single element) by only considering the first element from the source.

In my opinion, is should not be a goal of marble diagrams to be 100% exact and to show the whole detail of implementation, although - granted - we do show cancel and request signal on a bunch of marbles.

However, maybe a good middle ground would be to show a `cancel()` arrow going from the operator to the source, while still keeping the source as it is in the current diagram (ie. with multiple marbles).

pinging @smaldini for opinion.

Note that as we are migrating the whole set of marbles from OmniGraffle + PNG to SVG only, we cannot accept PRs on marbles until said migration is done. (#1390)

**Comment by daniildxb** [comment]
@simonbasle Ok, thanks for the feedback.

**Comment by thekalinga** [comment]
@simonbasle One way to show that its a Flux is to have the marbles after cancel to be shown in grey color which implies that they will no longer be pushed downstream, while maintaining showing its a flux
