### ISSUE TITLE
NPE when creating Mono<Void> from CompletableFuture<Void>

### ISSUE THREAD

**Issue by stylismo** [reactor/reactor-core#141]
When creating a Mono from a CompletableFuture<Void> an NPE is thrown since MonoCompletableFuture does not accept a null value.

```java
CompletableFuture<Void> myFuture = CompletableFuture.runAsync(() -> System.out.println("Doing some background work without result ..."));
Mono<Void> myMono = Mono.fromFuture(myFuture);
myMono.blockMillis(100);
```

**Comment by smaldini** [comment]
We specifically enforced no null result but for bridges to java 8 containers this one and Mono#justOrEmpty(Optional) we know that null is a valid value that should translate in simple completion.
