### ISSUE TITLE
Schedulers.fromExecutor(executor).createWorker() does not execute tasks in strict FIFO order, non concurrently

### ISSUE THREAD

**Issue by tukez** [reactor/reactor-core#1421]
### Expected behavior
Output:
```
0
1
2
3
4
5
6
7
8
9
```

### Actual behavior
Output:
```
0
2
1
3
4
5
7
6
8
9
```

### Steps to reproduce
```
Executor executor = Executors.newCachedThreadPool();
Worker worker = Schedulers.fromExecutor(executor).createWorker();
for (int i = 0; i < 10; i++) {
    int a = i;
    worker.schedule(() -> System.out.println(a));
}
Mono.delay(Duration.ofMillis(500)).block();
```

### Reactor Core version
3.2.2.RELEASE

### JVM version (e.g. `java -version`)
1.8.0_162

**Comment by simonbasle** [comment]
You are using a `ThreadPoolExecutorService` that allows parallelism. In its simplest form, `Schedulers.fromExecutor` (and its `Worker`) will purely delegate `schedule(Runnable)` to the `ExecutorService#execute` method. The implementation used will favor creating a new thread to run the task on, hence the result you get.

If you really want a pool but you want the `Worker` to queue up tasks rather that letting the `ExecutorService` decide, use `Schedulers.fromExecutor(executor, true).createWorker()`.

Trampolining here means tasks submitted in a burst are queued **by the `Worker` itself**, which acts as the sole task from the perspective of the `ExecutorService`, so no reordering (but also no parallelization).

**Comment by tukez** [comment]
I understand. The problem is that this behavior is unexpected, the javadoc for Scheduler.createWorker() states: "Creates a worker of this Scheduler that executed task in a strict FIFO order, guaranteed non-concurrently with each other".

This javadoc makes me believe the Scheduler interface sets this rule, so that each Scheduler implementation must follow it but it does not seem to be the case. This should be stated in the javadoc, maybe a mention about the Schedulers.fromExecutor as an example?
