### ISSUE TITLE
Change default onErrorDropped to log instead of bubbling error

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1431]
Should we change the default behavior from bubbling to logging for premature terminated flows observing errors ?

Should we add an extra callback in case like Flux/Mono#onErrorDiscard ?

**Comment by rstoyanchev** [comment]
An additional point, beyond the bubble vs log question is what kind of log level to use? Is it more information for debugging vs actual errors that need to be corrected and that can be corrected? If there isn't anything that can be done to correct in many cases, that would be an argument for DEBIG level as the default.

**Comment by simonbasle** [comment]
In M1 we'll go with `WARN`, as `onErrorDropped` is _usually_ denoting an issue with the source not conforming to Reactive Streams spec.
