### ISSUE TITLE
Provide ability to run the StepVerifier as a NonBlocking thread.

### ISSUE THREAD

**Issue by osi** [reactor/reactor-core#1433]
Reactor throws an exception if blocking operations are performed on threads that are marked with the `NonBlocking` marker interface. 

When using the `StepVerifier`, it will subscribe on the current thread. This leads to a potentially different environment then when deployed and the code might be called as part of a larger flow running on a `NonBlocking` thread.

To enable these errors to be caught earlier, provide the ability to have the current thread be considered `NonBlocking` for the duration of a `StepVerifier` execution.

**Comment by simonbasle** [comment]
This feature is implemented by detecting that `Thread.currentThread() instanceOf NonBlocking`, and having the `Schedulers` use Thread factories that produce such instances, so it is probably going to be difficult to have a perfect solution.

IMO the easiest way to achieve what you want to do is to rely on `subscribeOn`:
```java
Flux<Integer> test;
StepVerifier.create(test.subscribeOn(Schedulers.single())
    .expectNextCount(3)
    .verifyComplete();
```

Note that `VirtualTimeScheduler` and the use of `withVirtualTime` messes largely with both this solution _and_ anything related to blocking thread detection (all Schedulers being indifferently replaced by the VTS, which uses the current `Thread`).

**Comment by osi** [comment]
My naive thought was to extract the `Thread.currentThread() instanceOf NonBlocking` condition into a helper class that also had a boolean flag that's flipped during tests. I don't know how that'd interact with virtual time though, if a blocking-allowed thread were virtualized for time and shouldn't be part of the check.

**Comment by simonbasle** [comment]
That might be possible fo the general use case. The `VirtualTimeScheduler` is still problematic of course :(

**Comment by jforjava1981** [comment]
Is there any way to test infinite  flux stream created in controller method  using VirualTimeScheduler/ or any other means to test . e,g, i have following code in RestController 
`final String[] names = new String []{"Shailesh", "Josh", "Loredana", "Eugen", "Roger"};
        final Random randomGenerator = new Random();
        IntStream streamOfRandomIndexes = IntStream.iterate(0, nextInt -> randomGenerator.nextInt(names.length));
        Stream<String> fooNameStream = streamOfRandomIndexes.mapToObj(nextIndex -> names[nextIndex]);
        Flux<String> fooNames = Flux.fromStream(fooNameStream);

         Flux<Long> fooIds = Flux.interval(Duration.ofSeconds(1));

        return Flux.zip(fooNames,fooIds)
                .map(fooTuple -> new Foo(fooTuple.getT1(),fooTuple.getT2()));`

I am clueless how to verify that every element is in turn returned after 1 sec. Like if i change the delay in controller the particular test testing the time interval should fail. I searched a lot but in vain.
I have some idea that because getBody() is blocking, i cannot use virtualTimescheduler. But then how to get around this?

**Comment by simonbasle** [comment]
Usually, independently of whether or not to use the `VirtualTimeScheduler`, the way to check an `interval` is applied is to use `expectNoEvent(Duration.ofSeconds(1))`. When testing delay before first `onNext`, be sure to first use a `expectSubscription()`.

**Comment by simonbasle** [comment]
coming across this during issue cleanup. I don't think there is a real possibility of supporting that feature, and pieces of code that are supposed to execute on a specific (non-blocking) thread should have `publishOn`/`subscribeOn` in the pipeline, or have such decorations in tests.
