### ISSUE TITLE
Doc improvements for doOnDiscard

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-core#1436]
The project reference already [has a section](https://projectreactor.io/docs/core/release/reference/#_the_code_doondiscard_code_operator_local_hook) for the `doOnDiscard` hook. The explanation is very good, but in practice it remains tricky to reason about when the hook should be used or not. 

Specifically consider the following:

1. An exhaustive listing of all operators that support `doOnDiscard` is essential for reasoning about code and whether use of `doOnDiscard` is necessary in specific areas. The Javadoc for each operator is a good place to start. A centralized table in the docs might not be much more effort from there.  
2. A nuanced discussion might be necessary on a case by case basis. For example the `flatMap` does caching, but since caching kicks in after the transformation, if the transformation releases resources (e.g. data buffer) then `doOnDiscard` might not be needed. 
3. Optionally, as an aid for 2) it would be useful to have sample tests  that demonstrate when `doOnDiscard` is needed or not, and such tests could be linked to from the reference.

**Comment by simonbasle** [comment]
Note: a probably partial answer would be to integrate notes about such support directly in the javadoc body (#2136), since the existing custom javadoc tag information is not displayed in major IDEs ?

**Comment by chemicL** [comment]
@rstoyanchev this issue has been lingering for quite a while. Do you still feel this is needed?

**Comment by rstoyanchev** [comment]
Assuming the all operators that relate to this have a "Discard Support" comment stating one way or the other if they do or don't support it, then I think this can be closed.

**Comment by chemicL** [comment]
It seems that it was handled. Thanks for confirming. If anything is missing I believe we can have deal with them on a case-by-case basis.
