### ISSUE TITLE
Add null safe put method to Context interface

### ISSUE THREAD

**Issue by nikita-clearscale** [reactor/reactor-core#1442]
For now `reactor.util.context.Context#put` throws exception when receive null value. It would be better to nullsafe methods like:

    Context put(Object key, Optional<Object> value);

Intenally it should check whether `Optional.isPresent` and merge or not value into Context.

Now additional nullchecks leads to boilerplate code:

    ctx -> {
         if (some !=null) {
                  ctx.put("someKey", some);
         }
         return ctx;
    }

With new method:

    ctx -> ctx.put("someKey", Optional.ofNullable(some));

**Comment by simonbasle** [comment]
Wouldn't it be better to add an API method that more explicitly ignores `null` values? I'm anticipating that for such a generic class like `Context`, an `Optional` should be a valid value but here it would be constantly unwrapped.

**Comment by simonbasle** [comment]
There is another missing API for `size()`, will add it as part of the fix for this issue.
