### ISSUE TITLE
Automate release notes

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#1445]
to reduce the time it takes to release a new version, we might consider to automatically generate the release notes from the Github issues & commits

**Comment by simonbasle** [comment]
[release-drafter](https://github.com/toolmantim/release-drafter) seem like a good candidate, but I think one shortcoming is that it doesn't really deduplicates commits/PRs/issues. we'd probably need something that works out of the milestone, or at least can categorize entries according to labels **BOTH** from a pull request OR an issue linked in the commit title.

**Comment by simonbasle** [comment]
that or an external CLI tool which could work from a git diff between RELEASE_A..RELEASE_B (again, as long as it can find issues/pr in commit comments and get the labels from that for categorization)

**Comment by bsideup** [comment]
To consider: GitHub actions

**Comment by simonbasle** [comment]
Also, this shouldn't be an attempt at automating 100%, but rather producing a draft. Then we can reorganize the entries, group up some, etc... but the heavy lifting will be done.

**Comment by bsideup** [comment]
I agree. We do that in Testcontainers (draft with the release drafter, manual edits during the release), here is an example:
https://github.com/testcontainers/testcontainers-java/releases/tag/1.12.0

**Comment by simonbasle** [comment]
This could be moved to the bot, and take https://github.com/spring-cloud/spring-cloud-release-tools/blob/master/projects/reactor/src/main/java/releaser/reactor/GenerateReleaseNotesTask.java as an inspiration.

**Comment by hisener** [comment]
Somewhat related to this issue, release notes are missing for the latest version ([3.4.12](https://github.com/reactor/reactor-core/releases/tag/v3.4.12)).

**Comment by simonbasle** [comment]
release-drafter appears inadequate at multiple maintenance branches when a draft is desired, despite filter-by-commitish. reopening this.
