### ISSUE TITLE
Spring WebFlux - Retrying Mono from middle of a flow

### ISSUE THREAD

**Issue by Stefata** [reactor/reactor-core#1446]
### Expected behavior
If you have a flow such as below:
![flow](https://user-images.githubusercontent.com/14827647/48953908-543c0d80-ef3f-11e8-8cab-71c1cc01f9ea.JPG)
Let's imagine someObject is of type T and each one of those steps returns a new Mono<T>. I would like if an exception occurs in step4 for example, the flow is retried only from step4 (with the input from the successful step3).

Is this possible to implement in some way??

### Actual behavior
When an exception happens in step4, the flow is retried from step2.

### Steps to reproduce
Use the code above to reproduce

### Reactor Core version
3.2.2.RELEASE

### JVM version (e.g. java -version)
1.8

**Comment by bsideup** [comment]
Hi @Stefata,

you could either add individual retries to each step or (in case of Mono) `.cache()` the result after every step, so that when it retries, it will reuse the latest successful result instead of re-subscribing.

/cc @simonbasle correct me if I'm wrong :)

**Comment by simonbasle** [comment]
Yes, retrying inside the `flatMap` would be the way to go here.

Keep in mind these are not imperative steps, but a processing pipeline. If you look at it from a `Flux` perspective, then it becomes clearer that each step starts processing data as the previous step produces a new result, not as the previous step has finished running on the whole data set.
