### ISSUE TITLE
Materializing/dematerializing without complete loses last onNext

### ISSUE THREAD

**Issue by Netpilgrim** [reactor/reactor-core#1451]
### Expected behavior

Chaining Flux.materialize().dematerialize() should not alter output.

This seems to be related to issue #585 but if the behavior is indeed expected, it should at least be documented (JavaDoc for Flux.dematerialize()).

### Actual behavior

If the publisher never sends a complete signal, the last onNext signal is lost (stuck in dematerialize).

### Steps to reproduce

Example:

```java
Flux.just("one", "two", "three")
        .concatWith(Flux.never())
        .materialize()
        .dematerialize()
        .subscribe(x -> log.info("Got next: {}", x)) ;
```

The output shows only "one" and "two" arriving. All three arrive if either `concatWith(Flux.never())` or `materialize.()dematerialize.()` is omitted.

### Reactor Core version

3.2.3

### JVM version (e.g. `java -version`)

openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-b26)
OpenJDK 64-Bit Server VM (build 25.192-b26, mixed mode)

**Comment by simonbasle** [comment]
With small requests, like `request(2)`, the tradeoff is:
 - either you receive `1`,`2` and the Flux `complete`s without further request, mirroring `Flux.just(1, 2)` for instance (like in the current implementation)
 - or you only receive `1` and `2` and you need an additional `request(1)` to see the completion/error (like in RxJava2, where each request you make is directly mapped to a request for a **single** upstream `Signal` element)

@smaldini what do you think of this? Do you see a way to efficiently get best of both worlds?

**Comment by Netpilgrim** [comment]
> With small requests, like `request(2)`, the tradeoff is: […]

I do not see why backpressure is an issue here. In the case of Flux.subscribe(…) there is even unlimited demand; but even if there was only a demand of 3, that should be enough to deliver the three elements. As far as I understand it, between materialize() and dematerialize() a demand of 4 is needed because the onComplete signal is its own onNext there. But should it not suffice for dematerialize() to increase the demand by one and to buffer the last onNext signal received for the current downstream demand if it is not a materialized onComplete or onError?

Please note that I am only a (quite new) user of the library and have no knowledge about its implementation.

**Comment by rasentry** [comment]
```
Flux.interval(Duration.ofSeconds(1))
                .take(5)
                .materialize()
                .log("MATERIALIZE")
                .dematerialize()
                .log("DEMATERIALIZE")
                .subscribe();
```
will output
```
16:26:08.894 [main]            INFO  MATERIALIZE - onSubscribe(FluxMaterialize.MaterializeSubscriber)
16:26:08.895 [main]            INFO  DEMATERIALIZE - onSubscribe(FluxDematerialize.DematerializeSubscriber)
16:26:08.896 [main]            INFO  DEMATERIALIZE - request(unbounded)
16:26:08.897 [main]            INFO  MATERIALIZE - request(unbounded)
16:26:08.897 [main]            INFO  MATERIALIZE - request(1)
16:26:09.901 [parallel-1]      INFO  MATERIALIZE - onNext(onNext(0))
16:26:10.900 [parallel-1]      INFO  MATERIALIZE - onNext(onNext(1))
16:26:10.900 [parallel-1]      INFO  DEMATERIALIZE - onNext(0)
16:26:11.901 [parallel-1]      INFO  MATERIALIZE - onNext(onNext(2))
16:26:11.901 [parallel-1]      INFO  DEMATERIALIZE - onNext(1)
16:26:12.900 [parallel-1]      INFO  MATERIALIZE - onNext(onNext(3))
16:26:12.900 [parallel-1]      INFO  DEMATERIALIZE - onNext(2)
16:26:13.900 [parallel-1]      INFO  MATERIALIZE - onNext(onNext(4))
16:26:13.900 [parallel-1]      INFO  DEMATERIALIZE - onNext(3)
16:26:13.900 [parallel-1]      INFO  MATERIALIZE - onNext(onComplete())
16:26:13.901 [parallel-1]      INFO  MATERIALIZE - cancel()
16:26:13.901 [parallel-1]      INFO  DEMATERIALIZE - onNext(4)
16:26:13.902 [parallel-1]      INFO  DEMATERIALIZE - onComplete()
```

Last item delayed until onComplete (see timestamp). It is a trouble in my case.

**Comment by simonbasle** [comment]
reviving this issue, we'll rework the `dematerialize()` operator such that it requires 1 request per `Signal`, which includes the `onComplete` signal:

```
09:56:31.158 [main] INFO  MATERIALIZE - onSubscribe(FluxMaterialize.MaterializeSubscriber)
09:56:31.161 [main] INFO  DEMATERIALIZE - onSubscribe(FluxDematerialize.DematerializeSubscriber)
09:56:31.162 [main] INFO  DEMATERIALIZE - request(unbounded)
09:56:31.162 [main] INFO  MATERIALIZE - request(unbounded)
09:56:32.167 [parallel-1] INFO  MATERIALIZE - onNext(onNext(0))
09:56:32.169 [parallel-1] INFO  DEMATERIALIZE - onNext(0)
09:56:33.169 [parallel-1] INFO  MATERIALIZE - onNext(onNext(1))
09:56:33.169 [parallel-1] INFO  DEMATERIALIZE - onNext(1)
09:56:34.167 [parallel-1] INFO  MATERIALIZE - onNext(onNext(2))
09:56:34.167 [parallel-1] INFO  DEMATERIALIZE - onNext(2)
09:56:35.164 [parallel-1] INFO  MATERIALIZE - onNext(onNext(3))
09:56:35.164 [parallel-1] INFO  DEMATERIALIZE - onNext(3)
09:56:36.169 [parallel-1] INFO  MATERIALIZE - onNext(onNext(4))
09:56:36.169 [parallel-1] INFO  DEMATERIALIZE - onNext(4)
09:56:36.170 [parallel-1] INFO  MATERIALIZE - onNext(onComplete())
09:56:36.171 [parallel-1] INFO  MATERIALIZE - cancel()
09:56:36.172 [parallel-1] INFO  DEMATERIALIZE - onComplete()
```
