### ISSUE TITLE
Add hooks execution for Flux onNext methods

### ISSUE THREAD

**Issue by nikita-clearscale** [reactor/reactor-core#1454]
**The story**

I try to "inject" en intercepter for `onEachOperator` calls.
 1. But this works only for `Mono` classes.
 2. Event if I use `Mono`s flux webclient return a mono for me.

Here is code sample:

```
    @RestController
    public class MyController {
        @GetMapping("myPath")
        public Mono<MyDto> myDto() {
            log.info("1 " + new Object(){}.getClass().getEnclosingMethod().getName());
            Mono<FirtsDto> firtsDtoMono myFirstWebClient.get()
                   .uri("/first")
                   .retrieve()
                   .bodyToMono(FirtsDto.class);
           Mono<SecondDto> secondDtoMono mySecondWebClient.get()
                   .uri("/second")
                   .retrieve()
                   .bodyToMono(SecondDto.class);
            Mono<MyDto> myDtoMono = Mono.zip(firtsDtoMono, secondDtoMono).map(tuple -> /*some mapping ehre*/);
            myDtoMono.map(x -> {
                        log.info("2 " + new Object() {}.getClass().getEnclosingMethod().getName());
                        return x;
                    });
            log.info("3 " + new Object(){}.getClass().getEnclosingMethod().getName());
            return myDtoMono;
        }
    }

```

When I create a break point on line `log.info("2 " + new Object() {}.getClass().getEnclosingMethod().getName());`
I see something like this as stacktrace:

    lambda$myDto$0:117, MyController (com.myPackage)
    apply:-1, 1252817890 (com.myPackage.MyController$$Lambda$852)
    onNext:254, FluxMapFuseable$MapFuseableConditionalSubscriber (reactor.core.publisher)
    onNext:103, FluxContextStart$ContextStartSubscriber (reactor.core.publisher)
    onNext:262, FluxMapFuseable$MapFuseableConditionalSubscriber (reactor.core.publisher)
    onNext:103, FluxContextStart$ContextStartSubscriber (reactor.core.publisher)
    complete:1083, Operators$MonoSubscriber (reactor.core.publisher)
    signal:247, MonoZip$ZipCoordinator (reactor.core.publisher)
    onNext:329, MonoZip$ZipInner (reactor.core.publisher)
    onNext:103, FluxContextStart$ContextStartSubscriber (reactor.core.publisher)
    onNext:450, FluxOnAssembly$OnAssemblySubscriber (reactor.core.publisher)
    onNext:103, FluxContextStart$ContextStartSubscriber (reactor.core.publisher)
    onNext:73, FluxOnErrorResume$ResumeSubscriber (reactor.core.publisher)
    onNext:103, FluxContextStart$ContextStartSubscriber (reactor.core.publisher)
    complete:1083, Operators$MonoSubscriber (reactor.core.publisher)
    onNext:241, MonoFlatMap$FlatMapInner (reactor.core.publisher)
    onNext:103, FluxContextStart$ContextStartSubscriber (reactor.core.publisher)
    complete:1083, Operators$MonoSubscriber (reactor.core.publisher)
    onComplete:171, MonoSingle$SingleSubscriber (reactor.core.publisher)
    onComplete:130, FluxMap$MapSubscriber (reactor.core.publisher)
    checkTerminated:773, FluxFlatMap$FlatMapMain (reactor.core.publisher)
    drainLoop:543, FluxFlatMap$FlatMapMain (reactor.core.publisher)
    drain:523, FluxFlatMap$FlatMapMain (reactor.core.publisher)
    onComplete:409, FluxFlatMap$FlatMapMain (reactor.core.publisher)
    postCompleteDrain:131, DrainUtils (reactor.core.publisher)
    postComplete:186, DrainUtils (reactor.core.publisher)
    onComplete:213, FluxMapSignal$FluxMapSignalSubscriber (reactor.core.publisher)
    onComplete:130, FluxMap$MapSubscriber (reactor.core.publisher)
    onComplete:130, FluxMap$MapSubscriber (reactor.core.publisher)
    terminateReceiver:377, FluxReceive (reactor.ipc.netty.channel)
    drainReceiver:202, FluxReceive (reactor.ipc.netty.channel)
    onInboundComplete:342, FluxReceive (reactor.ipc.netty.channel)
    onInboundComplete:336, ChannelOperations (reactor.ipc.netty.channel)
    onHandlerTerminate:403, ChannelOperations (reactor.ipc.netty.channel)
    onInboundNext:605, HttpClientOperations (reactor.ipc.netty.http.client)
    channelRead:136, ChannelOperationsHandler (reactor.ipc.netty.channel)
    invokeChannelRead:362, AbstractChannelHandlerContext (io.netty.channel)
    invokeChannelRead:348, AbstractChannelHandlerContext (io.netty.channel)
    fireChannelRead:340, AbstractChannelHandlerContext (io.netty.channel)
    channelRead:102, MessageToMessageDecoder (io.netty.handler.codec)
    invokeChannelRead:362, AbstractChannelHandlerContext (io.netty.channel)
    invokeChannelRead:348, AbstractChannelHandlerContext (io.netty.channel)
    fireChannelRead:340, AbstractChannelHandlerContext (io.netty.channel)
    fireChannelRead:438, CombinedChannelDuplexHandler$DelegatingChannelHandlerContext (io.netty.channel)
    fireChannelRead:310, ByteToMessageDecoder (io.netty.handler.codec)
    channelRead:284, ByteToMessageDecoder (io.netty.handler.codec)
    channelRead:253, CombinedChannelDuplexHandler (io.netty.channel)
    invokeChannelRead:362, AbstractChannelHandlerContext (io.netty.channel)
    invokeChannelRead:348, AbstractChannelHandlerContext (io.netty.channel)
    fireChannelRead:340, AbstractChannelHandlerContext (io.netty.channel)
    channelRead:1434, DefaultChannelPipeline$HeadContext (io.netty.channel)
    invokeChannelRead:362, AbstractChannelHandlerContext (io.netty.channel)
    invokeChannelRead:348, AbstractChannelHandlerContext (io.netty.channel)
    fireChannelRead:965, DefaultChannelPipeline (io.netty.channel)
    read:163, AbstractNioByteChannel$NioByteUnsafe (io.netty.channel.nio)
    processSelectedKey:647, NioEventLoop (io.netty.channel.nio)
    processSelectedKeysOptimized:582, NioEventLoop (io.netty.channel.nio)
    processSelectedKeys:499, NioEventLoop (io.netty.channel.nio)
    run:461, NioEventLoop (io.netty.channel.nio)
    run:884, SingleThreadEventExecutor$5 (io.netty.util.concurrent)
    run:748, Thread (java.lang)

As you can see there is `onNext` calls only. Which in most cases looks like `reactor.core.publisher.FluxMapFuseable.MapFuseableConditionalSubscriber.onNext`:

```
    @Override
    public void onNext(T t) {
        if (sourceMode == ASYNC) {
            actual.onNext(null);
        }
        else {
            if (done) {
                Operators.onNextDropped(t, actual.currentContext());
                return;
            }

            R v;

            try {  // Look here !!!!
                v = Objects.requireNonNull(mapper.apply(t),
                        "The mapper returned a null value.");
            }
            catch (Throwable e) {
                onError(Operators.onOperatorError(s, e, t, actual.currentContext()));
                return;
            }

            actual.onNext(v);
        }
    }
```

look at line `v = Objects.requireNonNull(mapper.apply(t)` it do not contains any hooks call. So Hooks.onEachOperator does not works here. Hooks are invoked only on when errors happen or when next processing is over. Looks strange - why there is no possibility to make invocation when `done` variable is false?

Could you please add new Hools method for FLux intercepting call or add `Hooks.onEachOperator` on this?

**P.S.** I am trying to implement cross cutting concepts I am not big expert on Reactor so any comments with workarounds are welcome.

**Comment by simonbasle** [comment]
You seems to be making wrong assumptions on the use of `Hooks.onEachOperator`...
Current `Hooks` don't directly tie into generic `onNext`/`onError`/`onComplete` events, only for cases where there is a "protocol error".

`onEachOperator` is more about creating a wrapper around each operator method invocation when you build your chain, which basically allow you to wrap it in a custom `Publisher`, or `Subscriber` (via `Operators#lift`), but that's pretty advanced and hard to get right.

What kind of "cross-cutting concern" are you trying to implement?
