### ISSUE TITLE
[Suggestion] Add system property to enable metrics?

### ISSUE THREAD

**Issue by kkocel** [reactor/reactor-core#1455]
### Expected behavior
Setting property eg. `reactor.schedulers.metrics: enabled` could enable metrics

### Actual behavior
Schedulers.enableMetrics() needs to be called in order to enable metrics

### Reactor Core version

3.2.3

**Comment by simonbasle** [comment]
This is not something we're likely to do. Instead, the user application can easily enough bootstrap that sort of configuration itself. If you use Spring Boot, I think it would also make sense to raise an issue there for the Schedulers metrics to be configurable via Spring Boot configuration (keep in mind this is a very new feature, so they might already be working on that).

**Comment by kkocel** [comment]
I agree that it can be raised there. Thanks for clarification!
