### ISSUE TITLE
Inconsistent behaviour for error bubbling when using combineLatest and a publisher with publishOn

### ISSUE THREAD

**Issue by sm-matt** [reactor/reactor-core#1459]
### Expected behaviour
When using the `Flux.combineLatest()` operator where one of the publishers will surface an error **AND** use the `publishOn` operator, combined with a publisher that is empty, the error should bubble up to the subscriber

### Actual behaviour
The subscriber will receive `onNext` instead. If the 'publishOn' is removed, then the error is correctly bubbled up.

### Steps to reproduce
Please see this repo which has examples (I hope kotlin is ok) -> https://github.com/sm-matt/reactor-bug

The core issue is in the code below passing in null and an empty list to the top level function->

```
fun combineLatestWithScheduledCallableMonoAndFlux(monoValue: Int?, fluxList: List<Int>): Mono<Unit> {

    return Flux.combineLatest(returnScheduledCallableMonoWithValue(monoValue), fluxFromList(fluxList), BiFunction<Int, Int, Int> { t, u -> t + u })
        .collectList()
        .map { Unit }
 }

private fun returnScheduledCallableMonoWithValue(value: Int?): Mono<Int> {

    val scheduler = Schedulers.fromExecutor(Executors.newFixedThreadPool(10))

    return Mono.fromCallable<Int> {
        Thread.sleep(10) //represents a DB call
        value
    }
        .publishOn(scheduler)
        .switchIfEmpty(Mono.error<Int>(RuntimeException("We failed")))
}

private fun fluxFromList(fluxList: List<Int>): Flux<Int> {
    return fluxList.toFlux()
}
```

### Reactor Core version
3.2.3
### JVM version (e.g. `java -version`)
10.0.2

**Comment by tabiul** [comment]
I did some digging on your first function and I think  maybe I know what is happening

* The `fluxFromList(fluxList)` completes earlier then `returnScheduledCallableMonoWithValue(monoValue)` and as such complete the operation
* When it comes it  `returnScheduledCallableMonoWithValue(monoValue)` turn, it sees that the operation is completed as such does not propagate the error rather discard the error. 

The below code block in https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/FluxCombineLatest.java#L360
```
void innerError(Throwable e) {

			if (Exceptions.addThrowable(ERROR, this, e)) {
				done = true;
				drain();
			}
			else {
				discardQueue(queue);
				Operators.onErrorDropped(e, this.ctx);
			}
		}
```

Notice the **if** condition. If you navigate to the function itself you will see this
```
if (current == TERMINATED) {
				return false;
			}
```

You can hook into this error using the **Hooks** method as explained here https://projectreactor.io/docs/core/snapshot/reference/#hooks-dropping. In some sense this is considered as an illegal operation i.e calling subscribe on a terminated chain and I believe this is explained in this statement

> Typically, a Publisher calls onNext on the operator despite having already called onCompleted on it previously. In that case, the onNext value is dropped. The same is true for an extraneous onError signal.


If you modify your first function as below your test will pass even though both of them maybe possibly run on a seperate thread.

```
    fun combineLatestWithScheduledCallableMonoAndFlux(monoValue: Int?, fluxList: List<Int>): Mono<Unit> {

        return Flux.combineLatest(returnScheduledCallableMonoWithValue(monoValue), returnScheduledCallableMonoWithValue(monoValue), BiFunction<Int, Int, Int> { t, u -> t + u })
            .collectList()
            .map { Unit }

    }
```

**Comment by sm-matt** [comment]
It seems the behaviour is reproduce-able for a non-thread pooled producer if the empty list is the first publisher in the `combineLatest` operator parameter list. The subscription will terminate prior to the error being thrown. e.g.

`Flux.combineLatest(EmptyFlux, ErrorFlux, BiFunction)`

When `combineLatest` contains two producers, neither of which make use of publishOn, they will execute in order of declaration. If the producer that throws an error is declared first, the error will be caught by the subscriber, in the reverse case, the `combineLatest` operator will complete before the error and the error will be dropped.

`Flux.combineLatest(EmptyFlux, ErrorFlux, BiFunction) // returns onNext`
`Flux.combineLatest(ErrorFlux, EmptyFlux, BiFunction) // returns onError`

I'm not sure if this is the intended behaviour for `combineLatest` or if this is one of the intended use cases for a `Hook.onErrorDropped`. Happy for this issue to be closed with some clarification if this is the case.

**Comment by simonbasle** [comment]
That is indeed the behaviour intended for `combineLatest` @sm-matt
