### ISSUE TITLE
Wrong onErrorContinue description in documentation

### ISSUE THREAD

**Issue by pawelslowik** [reactor/reactor-core#1461]
### Expected behavior
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#onErrorContinue-java.util.function.BiConsumer-

Method does not take Predicate argument and documentation should not describe impact of that argument on method's behaviour.

### Actual behavior
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#onErrorContinue-java.util.function.BiConsumer-

Method does not take Predicate argument, but documentation states: 'Only errors matching the Predicate are recovered from.'

Looks like a copy-paste from:
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#onErrorContinue-java.util.function.Predicate-java.util.function.BiConsumer-

### Reactor Core version
Reactor Core 3.2.3.RELEASE

**Comment by simonbasle** [comment]
will fix in the same PR as #1458
