### ISSUE TITLE
Add transformation with zip

### ISSUE THREAD

**Issue by KrzychuJedi** [reactor/reactor-core#1462]
It would be a useful feature to allow combine two publishers which the second one produce data based on what the first one emits.

Currently, it could be achieved by the following code

```
        Flux.fromArray(new Integer[]{1,2,3,4,5,5})
                .map(i -> Tuples.of(i, someService.getBy(i)))
                .subscribe();
```
Expected solution
```
        Flux.fromArray(new Integer[]{1,2,3,4,5,5})
                .mapWithZip(someService::getBy)
                .subscribe();
```

It will be useful when We must fetch data from DB but don't want to lose the original source.

**Comment by simonbasle** [comment]
I don't think that is something we're going to add. We try to keep the number of operators limited, and only introduce new operators that have very specific semantics that can't be obtained by combining a few existing operators now. Plus having that for `map` would mean we'd probably be asked to add it for `flatMap`, `concatMap`, etc...
