### ISSUE TITLE
Missing marble diagrams post SVG change

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#1463]
⚠️ Diagram changes / new diagrams in 3.2.x won't be accepted in PNG form and will be blocked until #1390 is merged.

> (❓) denotes a diagram that might either be hard to graphically represent, or one that is maybe too similar to existing variants to introduce another diagram

### Flux diagrams
 - [x] `index` (see #1448)
 - `limitRate` (see #1449, ⛔️ ==> deferred, see if somebody contributes)
 - [x] `limitRequest` (❓) => done
 - [x] `onBackpressureBuffer(Duration, maxSize)`
 - [x] `sort`
 - [x] `switchOnFirst`

### Mono diagrams
 - [x] `sequenceEqual`
 - ~`cache(Duration, Duration, Duration)`(❓)~ => a bit complex

### Diagrams relevant to both `Flux` and `Mono`
 - [x] `doFinally`
 - [x] `doOnEach`
 - ~`handle` (❓)~ => will do if requested, a bit complex
 - ~`name` and `tag` (❓)~ => will do if requested

**Comment by OlegDokuka** [comment]
+ switchOnFirst
