### ISSUE TITLE
Remove sun.misc.* stubs

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#1469]
In #1466, we introduced `java8stubs` sourceset, because we started using Java 8's internal APIs, and Javac 9+ fails to compile Java 8-compatible code with such references.

Our current hacky approach is to provide compile-only stubs for them, but we probably can do better.

This is a placeholder Backburner issue for the future investigations.

**Comment by simonbasle** [comment]
Doesn't look like multi-release jars are prevalent enough that it would be a practical solution, and Gradle's variants don't help much here. The only improvement I thought of was to put it in buildSrc, but the build script is short enough that it is acceptable, especially now that it's been documented in #2573 ... Should we close this issue @bsideup ?

**Comment by simonbasle** [comment]
The approach seems good enough and we didn't come up with a more elegant solution, closing this.
