### ISSUE TITLE
reactor-core 3.2 OSGI bundle issue io.micrometer.* is not optional

### ISSUE THREAD

**Issue by agjini** [reactor/reactor-core#1470]
### Expected behavior
When using reactor-core bundle in OSGI environment, io.micrometer.core bundle would not be required as it is an optional dependency to reactor-core.

To fix this we have to add the following line into the 'bundleImportPackages' section of build.gradle file :
`'io.micrometer.*;resolution:=optional',`

### Actual behavior
Actually `io.micrometer.core.instrument,io.micrometer.core.instrument.binder.jvm,io.micrometer.core.instrument.composite,io.micrometer.core.instrument.search` are packages required at runtime. As micrometer bundle is not exporting those packages actually, it is impossible to run reactor-core >= 3.2 in OSGI env.

### Reactor Core version
reactor-core v3.2.0 and superior

### JVM version (e.g. `java -version`)
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**Comment by simonbasle** [comment]
Have you tried with 3.2.2/3.2.2? There were some mistakes around the integration of Micrometer in 3.2.0/3.2.1...

We don't want to enforce a dependency to Micrometer for folks who are not interested in metrics, hence the `optional` aspect. Classes are built against at compile time, but their loading is avoided with reflection-based guards. Reactor operators involving metrics then fallback to no-op when Micrometer is not in the classpath at runtime.

If you see a way to make all this compatible with OSGI while maintaining this "no hard dependency on Micrometer" feature for users outside of the OSGI sphere, please advise.

**Comment by agjini** [comment]
Yes, in fact my test was made with the latest reactor-core : 3.2.3.RELEASE
I've successfully tested the fix I've mentioned (in build.gradle file) :
'io.micrometer.*;resolution:=optional',

**Comment by simonbasle** [comment]
@agjini ah got it, from the section in the issue template I thought it was supposed to work but somehow didn't... Do you want to submit a PR, or should I take care of it?

**Comment by agjini** [comment]
Thanks a lot for making the change. It would have taken more time to make a PR.
