### ISSUE TITLE
make schedulers plugable

### ISSUE THREAD

**Issue by robertroeser** [reactor/reactor-core#1476]
I'd like the Schedulers pluggable - so that if someone uses Scheduler.parallel it goes to an implementation that I set. It doesn't seem like you can do that right now. It would be nice to change the behavior so that if you're using something with an event loop - like Netty - the default schedules the work on the netty eventloops instead of another threadpool.

**Comment by simonbasle** [comment]
Schedulers.Factory is the interface you are after, if I'm not mistaken

**Comment by robertroeser** [comment]
Yep that works thanks.

**Comment by simonbasle** [comment]
Note that sounds like a pretty drastic thing to do, so I wouldn't recommend that decision to be made by anybody other than the end user ;)
