### ISSUE TITLE
cache() inside transformer function has no effect

### ISSUE THREAD

**Issue by jruhe-adesso** [reactor/reactor-core#1485]
I cannot explain, why an cache() call inside a transformer function for compose does not cache the last emission for further subscriptions while cache() appended to compose does.
I consider this as a bug. Very unpleasant, because I do not want to append cache() to any use of the same transformer function instead of doing it once inside the function.
```java
        Flux<Integer> f = Flux.just(1).doOnSubscribe(System.out::println);
        System.out.println("--- no cache()");
        Flux<Integer> ff1 = f.compose(integerFlux -> integerFlux);
        ff1.blockFirst();
        ff1.blockFirst();
        System.out.println("--- cache() after compose");
        Flux<Integer> ff2 = f.compose(integerFlux -> integerFlux).cache();
        ff2.blockFirst();
        ff2.blockFirst();
        System.out.println("--- cache() inside compose");
        Flux<Integer> ff3 = f.compose(integerFlux -> integerFlux.cache());
        ff3.blockFirst();
        ff3.blockFirst();
```
Output:
--- no cache() **OK**
reactor.core.publisher.FluxJust$WeakScalarSubscription@5a1de7fb
reactor.core.publisher.FluxJust$WeakScalarSubscription@ee86bcb
--- cache() after compose **OK**
reactor.core.publisher.FluxJust$WeakScalarSubscription@6c0d9d86
--- cache() inside compose **NOT OK**
reactor.core.publisher.FluxJust$WeakScalarSubscription@1fde5d22
reactor.core.publisher.FluxJust$WeakScalarSubscription@5dcb4f5f
### Reactor Core version
3.1.12
### JVM version (e.g. `java -version`)
Java 8

**Comment by simonbasle** [comment]
`compose` re-applies the operator on each subscription, independently (it defers the application of the function until subscription time).

`transform` is what you are after: it applies the transformation `Function` during assembly time, instantiating only one decorated `Flux`.
