### ISSUE TITLE
Missing hasDiscardedMatching in StepVerifier

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1509]
Right now doOnDiscard test for element equality, we would need a version to introspect the data (possibly with optional type argument to cast Object).

**Comment by mumukiller** [comment]
What's the point of optional argument? As far as i understand Null element in flux array will throw an NPE
https://github.com/reactor/reactor-core/blob/f32944fdd10dfc4dc97fd21453b626d77b2856d9/reactor-core/src/main/java/reactor/core/publisher/FluxArray.java#L335
