### ISSUE TITLE
Improve Javadoc for switchOnFirst

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-core#1514]
There is no mention whether the Flux given to the transformer has the first item or not. This is an important detail.

There is no discussion of handling for error signals. What if I only want to handle the first item but not interfere with error signals? Or what if I want to switch on error signals too? 

From experimentation I see that returning either the original `Flux` or `Flux.empty` keeps the error signal while returning any other `Flux` suppresses the error signal. In which case returning `Flux.empty()` seems to behave like a return value that means "default handling without interference"? How does one then switch to an empty stream theoretically? 

It'd be good to clarify all this.

**Comment by OlegDokuka** [comment]
hey @rstoyanchev. let me quickly answer your questions

**Comment by rstoyanchev** [comment]
hey @OlegDokuka, no worries, thanks for elaborating. 

So returning the given `Flux` at the end ensures falling back on default behavior for everything else? That sounds good to me although it does makes the sample given in the Javadoc misleading at best. It shows falling back  on returning `Flux.empty()` at the end which would suppress errors, and that may or may not be the intent. It should be explained at least.

**Comment by OlegDokuka** [comment]
> So returning the given `Flux` at the end ensures falling back on default behavior for everything else?

Right, in case we want to fully connect the given upstream (represented as the second argument in `BiFunction`) with downstream, then we have to add required behavior to flux within BiFunction and return it back. In that case, all signals from upstream will be delivered to downstream.

In case we want to ignore all upstream signals, we can simply return absolutely unrelated `Publisher` so upstream will not get any `Subscription#request` anymore, and the first signal will be ignored by downstream.

> That sounds good to me although it does makes the sample given in the Javadoc misleading at best

Agree. I am going to send a PR with mentioned, more detailed docs. Thanks for reporting that!

**Comment by simonbasle** [comment]
@OlegDokuka @rstoyanchev I have already fixed the documentation as part of #1508

**Comment by simonbasle** [comment]
This clarification made me look at another aspect: if the returned `Flux` is unrelated, what happens to the subscription to the original `Flux`? Looks like it is not cancelled, I wonder if/how that could be improved @OlegDokuka

**Comment by OlegDokuka** [comment]
Not sure we can do that in any other way than implementing additional Decorator around outer Subscriber which in case of completion will send additional cancelation signal to the parent stream. I'm not sure we can detect whether the returned stream is the composition of original or absolutely unrelated one.

WDYT, @simonbasle ?

**Comment by simonbasle** [comment]
Looks like the operator needs a lot more work... While trying to write failing tests for this concern, I also found out that `TestPublisher` is lacking a few options and features (notably it currently doesn't respect backpressure at all). Opening two separate issues.

**Comment by simonbasle** [comment]
cf #1517. In the meantime, I'll indicate in the javadoc the caveat of switching to an unrelated `Publisher` (advising to do something more like `onErrorResume(Mono.empty())` for cases where one wants to suppress early errors, `then()` for suppressing data, etc...)
