### ISSUE TITLE
onErrorReturn should be lazy evaluated

### ISSUE THREAD

**Issue by mpalourdio** [reactor/reactor-core#1516]
### Expected behavior
`onErrorReturn` should be lazy evaluated whenever possible.
### Actual behavior
At the moment, when using `onErrorReturn`, the return value is always evaluated. It should be possible to specify `onErrorReturn` arguments without side-effects when all is OK. Even if `doOnErrors` allows us to perform void operations when things fail, it can lead to unexpected behaviors (ex. this `log.error` I have 'forgotten'' here in the `generateFallback` method.
### Steps to reproduce
```java
    public Mono<GeoLocationApiResponse> geoLocateIp(String ipAddress) {
        return webClient
                .get()
                .uri(SERVICE_URL + "/{apiKey}/{ipAddress}", API_KEY, ipAddress)
                .header(HttpHeaders.ACCEPT_LANGUAGE, Locale.CANADA.toLanguageTag())
                .retrieve()
                .bodyToMono(GeoLocationApiResponse.class)
                .doOnNext(response -> handleResponse(response, ipAddress))
                .doOnError(e -> log.error("Geolocation API call error", e))
                .onErrorReturn(generateFallback(ipAddress));
    }

    private GeoLocationApiResponse generateFallback(String ipAddress) {
        log.error("OOPS");
        GeoLocationApiResponse fallBack = new GeoLocationApiResponse();
        fallBack.setIpAddress(ipAddress);
        fallBack.setHasErrored(true);
        fallBack.setError("Unexpected error, please check server logs.");

        return fallBack;
    }
[...]
```

In this case, `generateFallback` will always be evaluated. 
Maybe something like this could be welcome.
```java
public <T> Mono<T> onErrorReturn(Supplier<T> fallback)
```
### Reactor Core version
3.2.5.RELEASE
### JVM version (e.g. `java -version`)
openjdk version "1.8.0_191"

**Comment by simonbasle** [comment]
I'm not sure we want to add methods to the `Flux` API that are just `Supplier` overloads, when the `Publisher` based alternatives are already lazy.

It is a small refactor, but for a more naturally lazy version use `onErrorResume` which takes a `Function`:

```java
    private Function<Throwable, Mono<GeoLocationApiResponse>> generateFallback(String ipAddress) {
        return t -> {
            log.error("OOPS");
            GeoLocationApiResponse fallBack = new GeoLocationApiResponse();
            fallBack.setIpAddress(ipAddress);
            fallBack.setHasErrored(true);
            fallBack.setError("Unexpected error, please check server logs : " + t); //now we can even include the error message

            return Mono.just(fallBack);
        }
    }
```

```java
    public Mono<GeoLocationApiResponse> geoLocateIp(String ipAddress) {
        return webClient
                .get()
                .uri(SERVICE_URL + "/{apiKey}/{ipAddress}", API_KEY, ipAddress)
                .header(HttpHeaders.ACCEPT_LANGUAGE, Locale.CANADA.toLanguageTag())
                .retrieve()
                .bodyToMono(GeoLocationApiResponse.class)
                .doOnNext(response -> handleResponse(response, ipAddress))
                .doOnError(e -> log.error("Geolocation API call error", e))
                .onErrorResume(generateFallback(ipAddress));
    }
```

**Comment by mpalourdio** [comment]
Hmm, you're right, that's much better. I am pretty new to reactor, and I hadn't tried `onErrorResume` because of the method name :) I thought that it would have performed some kind of 'retry' if things would fail.

Anyway, the fact that onErrorReturn is eager in a bit misleading at first sight.

Thanks for this awesome and fast feedback. Feel free to close this issue if needed.

**Comment by simonbasle** [comment]
Yeah this is sometimes confusing to newcomers, especially when they're also new to the functional programming aspects (they tend to think that everything becomes magically lazy and functional, even good old imperative method calls). `Mono.just(foo())` has the same behavior.

Note that here the method returns a `Function`, in order to capture the `ipAdress` parameter. As a result, it is prone to the same confusion: it will be invoked eagerly when assembling the pipeline, so eg. a `System.out.println("OOPS")` before the method's `return` statement would always get printed. But the body of the `lamdba` is lazily invoked.

**Comment by mpalourdio** [comment]
> Yeah this is sometimes confusing to newcomers, especially when they're also new to the functional programming aspects (they tend to think that everything becomes magically lazy and functional, even good old imperative method calls). `Mono.just(foo())` has the same behavior.
>

Fair point :) But I was most mislead by the `onErrorResume`  method name that by its signature. I was not expecting `onErrorReturn` to be lazy per se as it awaits a plain `T`, but raised this issue for signature overload for something more functional. `onErrorResume` is perfect.

> Note that here the method returns a `Function`, in order to capture the `ipAdress` parameter. As a result, it is prone to the same confusion: it will be invoked eagerly when assembling the pipeline, so eg. a `System.out.println("OOPS")` before the method's `return` statement would always get printed. But the body of the `lamdba` is lazily invoked.

Sure, I am well aware that things need to happen inside the function body, and not inside the method body .That's exactly what I needed :) I had well understood that the full pipeline was evaluated anyway.

Again, thanks for feedback.
