### ISSUE TITLE
onErrorContinue is called twice for each error

### ISSUE THREAD

**Issue by vinipuh5** [reactor/reactor-core#1530]
### Expected behavior
onErrorContinue is called once for each thrown error
### Actual behavior
onErrorContinue is called twice for each error
### Steps to reproduce
In my use case, I want to allow no more than two errors in a row for a stream. I have something similar to the code below.
```
    @Test
    fun threeErrorsInARow() {
        val ai = AtomicInteger(0)

        Flux
            .merge<String>(
                Exception("Error1").toMono<String>(),
                Exception("Error2").toMono<String>(),
                "1".toMono(),
                Exception("Error3").toMono<String>(),
                Exception("Error4").toMono<String>(),
                Exception("Error5").toMono<String>(),
                "2".toMono()
            )
            .onErrorContinue({ _: Throwable -> ai.getAndIncrement() < 2 }) { _, _ ->
                println("Warning: Retry: ${ai.get()}")
            }
            .doOnNext { ai.set(0) }
            .test()
            .expectNext("1")
            .verifyErrorMatches { it.message == "Error5" }
    }
```
This test fails because onErrorContinue is called twice for each error. Currently, my workaround is to rewrite the onErrorContinue to be like this
```
            .onErrorContinue({ _: Throwable -> ai.get() < 2 }) { _, _ ->
                println("Retry: ${ai.incrementAndGet()}")
            }
```
which really dirties up the code in my real application
### Reactor Core version
3.2.2.RELEASE
### JVM version (e.g. `java -version`)
java version "1.8.0_171" Java(TM) SE Runtime Environment (build 1.8.0_171-b11) Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

**Comment by simonbasle** [comment]
The `Predicate` is not supposed to have state, and must be a pure function of the `Throwable`. Put the state in the processing `Function`.
