### ISSUE TITLE
Mono context inside Mono methods like doOnSuccess(), doOnError(), retry(), etc is unavailable

### ISSUE THREAD

**Issue by igorewka** [reactor/reactor-core#1531]
Make those methods Mono context aware.
Atm, it's possible to use `doOnEach()` to workaround the issue for `doOnSuccess()` and `doOnError()`. The result of logging in `doOnSuccess()` is different from logging in `doOnEach(){if (signal.isOnComplete()){...}}`. Looks like the time of executing those callbacks is different. So even this workaround is not quite good.
Any available workaround for the `retry()` is unknown.
The point of getting the context is to be able to log some unique request id in those methods if necessary.

**Comment by simonbasle** [comment]
For retry, `retryWhen` has access to the `Context` through the input of the `whenFactory` `Function` (see the snippet in the javadoc, adapt to emit something else than the `Context` if you only want to read it).

For all `doOn` methods you quoted, `doOnEach` is the recommended approach. We're not eager to double the number of methods for the sake of exposing the `Context` for now, if we can avoid it.

Can you detail a bit more about that difference you saw between `doOnSuccess` and `doOnEach`?

**Comment by igorewka** [comment]
Thank you for a hint on `retryWhen`, works like a charm.

Code isn't concise using `doOnEach `and `retryWhen`. That's the main issue for me.

Regarding the difference between `doOnSuccess` and `doOnEach`:
```java
        Mono
                .fromSupplier(() -> {
                    log.info("parent");

                    return true;
                })
                .flatMap(p ->
                        Mono
                                .fromSupplier(() -> {
                                    log.info("child");

                                    return true;
                                })
                                .doOnEach(sig -> {
                                    if (sig.isOnComplete()) {
                                        log.info("child doOnEach");
                                    }
                                })
                                .doOnSuccess(c -> log.info("child doOnSuccess")))
                .doOnSuccess(c -> log.info("parent doOnSuccess"))
                .subscribe();
```
Expected: `child doOnEach` to be before `parent doOnSuccess`. 
Actual:  `child doOnEach` is the last.

**Comment by igorewka** [comment]
Any thoughts regarding the difference between `doOnSuccess` and `doOnEach`?

**Comment by simonbasle** [comment]
@igorewka yes I think I have found the source, opening #1547 to track it.
