### ISSUE TITLE
combineLatest operator does not produce values at the same pace

### ISSUE THREAD

**Issue by dhorman** [reactor/reactor-core#1542]
### Expected behavior
`combineLatest` produces latest values of input streams 

### Actual behavior
Fast stream takes priority over slow one.

a0-b3
00:31:55.042 [parallel-1] INFO  a - request(1)
a0-b4
00:31:57.043 [parallel-1] INFO  b - request(1)
00:31:57.043 [parallel-1] INFO  b - onNext(b24)
a0-b24
00:31:59.043 [parallel-1] INFO  b - request(1)
00:31:59.043 [parallel-1] INFO  b - onNext(b34)
a0-b34
00:32:01.044 [parallel-1] INFO  b - request(1)
00:32:01.044 [parallel-1] INFO  b - onNext(b44)
a0-b44
00:32:03.044 [parallel-1] INFO  b - request(1)
00:32:03.044 [parallel-1] INFO  b - onNext(b54)
a0-b54
00:32:05.045 [parallel-1] INFO  b - request(1)
00:32:05.045 [parallel-1] INFO  b - onNext(b64)
a0-b64
00:32:07.045 [parallel-1] INFO  b - request(1)
00:32:07.045 [parallel-1] INFO  b - onNext(b74)
a0-b74
00:32:09.045 [parallel-1] INFO  b - request(1)
00:32:09.045 [parallel-1] INFO  b - onNext(b84)
a0-b84
### Steps to reproduce
```scala
  Flux.combineLatest(Iterable(
    Flux.interval(1 second).map(a => s"a$a").onBackpressureLatest().log("a"),
    Flux.interval(200 millis).map(b => s"b$b").onBackpressureLatest().log("b"),
  ), prefetch = 1, (arr: Array[AnyRef]) => {
    Thread.sleep(2000) // slow computation
    s"${arr(0)}-${arr(1)}"
  })
  .subscribe(println(_))
```
### Reactor Core version
      "io.projectreactor" % "reactor-core" % "3.2.6.RELEASE",
      "io.projectreactor" %% "reactor-scala-extensions" % "0.3.5",
### JVM version (e.g. `java -version`)
"11.0.1" 2018-10-16 LTS

**Comment by simonbasle** [comment]
Not sure what you expected, and why you used `onBackpressureLatest()`, but it might come from that.
Locally, in java, I can get output like this consistently when removing the `onBackpressureLatest` from the first `Flux`:

```
a0-b3
a0-b4
a0-b5
a0-b6
a0-b7
a0-b8
a1-b8
a1-b9
a1-b10
a1-b11
```

For reference, the java code used is:
```java
	@Test
	public void test() {
		Flux.combineLatest(
				Arrays.asList(
						Flux.interval(Duration.ofSeconds(1))
						    .map(a -> "a" + a)
						,Flux.interval(Duration.ofMillis(200))
						    .map(b-> "b" + b )
						    .onBackpressureLatest()
				),
				1,
				arr -> arr[0] + "-" + arr[1]
		)
		    .doOnNext(System.err::println)
		    .take(10)
		    .blockLast(Duration.ofSeconds(5));
	}
```

**Comment by dhorman** [comment]
Thanks for reply @simonbasle 
Unfortunately, I still receive the same issue. Your code is not consistent with mine (you didn't include slow computation simulation). When you remove slow computation all works fine.
My initial idea is to prefetch only one value from input streams (`prefetch` parameter in `combineLatest` operator) and skip old values from streams if `combineLatest` can't accept these values right now but take latest from all inputs when `combineLatest` is ready

**Comment by simonbasle** [comment]
ah! I missed that `sleep` somehow.
So your actual transformation is blocking, synchronous and slow? That's completely opposed to what a reactive stream pipeline operation should include, no wonder it doesn't behave... The operators expect non-blocking operations, otherwise it can have an impact not only on the current operator but previous operators in the chain as well (since they often share the same thread).

What you could do in order not to block the thread is to offset the expensive computation on another thread. For now combine the elements in the simplest way possible (an array), publish that array on another `Scheduler` and then `map` the heavy computation:

```java
Flux.combineLatest(..., 1, Function.identity())
    .publishOn(Schedulers.elastic())
    .map(arr -> {
        Thread.sleep(2000);
        return arr[0] + "-" + arr[1];
    });
```

**Comment by dhorman** [comment]
Hi @simonbasle and thanks for reply again.

This code perfectly works for me

```scala
  Flux.combineLatest(Iterable(
    Flux.interval(1 second).map(a => s"a$a"),
    Flux.interval(200 millis).map(b => s"b$b"),
  ), prefetch = 1, identity)
  .onBackpressureLatest()
  .publishOn(Schedulers.elastic(), prefetch = 1)
  .map(arr => {
    Thread.sleep(2000)
    s"${arr(0)}-${arr(1)}"
  })
  .subscribe(println(_))
```
