### ISSUE TITLE
Grouping

### ISSUE THREAD

**Issue by DareUrDream** [reactor/reactor-core#1543]
Hi,

Is it possible to say that a group is complete based on a predicate function or some other function that gets evaluate for each row ?

Cheers !!
DareUrDream

**Comment by DareUrDream** [comment]
???

**Comment by simonbasle** [comment]
If you want overlapping groups but need to cut each group early, you can consume the group in a `flatMap` and apply some cancelling operator like `takeWhile(Predicate)` to the group. Note however that this will close each group **and reopen a new one with subsequent source values**.

This grouping produces 2 groups, dispatching each value to one then the other:
```java
Flux<Flux<Integer>> evenOdds = Flux.range(1, 10)
    .groupBy(i -> i % 2 == 0);
//1 3 5 7 9
//2 4 6 8 10
```

You can then cut each group short, eg. using `take(3)` in a `flatMap` and collecting each group into a list:
```java
Flux<List<Integer>> shorterGroups = evenOdds
    .flatMap(group -> group.take(3).collectList());
//[1, 3, 5], [2, 4, 6], [7, 9], [8, 10]
```
Notice how it sort of reopens the even and odd groups?

**But I think what you are after might be `windowWhile`/`windowUntil`**

Note that these operators produce non-overlapping windows, unlike `groupBy` which can keep multiple groups open (as long as they are consumed downstream).

**Comment by DareUrDream** [comment]
@simonbasle I will try this out. Thanks. Sharing my use-case for your inputs and suggestions  

What I am trying to achieve is to group a certain set of objects from a hot streaming source and then when the group has all the needed objects (want to determine that based on the condition evaluated with each data object) send the group downward for processing...In my case the number of objects in a group and number of groups can range from 1 to n.

Cheers !!
DareUrDream

**Comment by davidmoten** [comment]
If the reactor operator `groupBy` has a similar implementation to the one in `RxJava` then bear in mind when you use this terminating operator `takeWhile` within the `groupBy` that there is an opportunity for emissions from the source to be lost.  Any items that have been grouped and passed to the inner stream may be queued and then lost by an operator that terminates the inner stream (which then gets recreated by later emissions). For this reason I suggest you use an operator that buffers based on an expiry. I'm not familiar with the offerings in reactor but for RxJava you could use  [`collectWhile`](https://davidmoten.github.io/rxjava2-extras/apidocs/index.html) from [rxjava2-extras](https://github.com/davidmoten/rxjava2-extras).  I've also just been preparing a `buffer(maxSize, timeout)` operator (where the timeout is based on the last source emission). Feel free to weigh in on that [issue](https://github.com/davidmoten/rxjava2-extras/pull/17) with your requirements. By the way there is also a `groupBy` overload in RxJava 2.x with a Map factory parameter that allows you to limit the number of groups in the internal map by using a Map builder from Guava for example.

**Comment by DareUrDream** [comment]
Thanks @davidmoten for the info..

On other note would it be more useful if we have an API which along with grouping functions take a predicate function and then evaluate in order to determine when the group is closed.

**Comment by davidmoten** [comment]
@DareUrDream Note that `buffer(maxSize, timeout)` was built by composition with a new `insert` operator. I think we can compose with `insert` to solve your problem as well because it inserts something in to the stream on timeout and the timeout can vary by emission. You then use that special inserted record to delimit the list in a `collectWhile` call and choose not to add these special delimiting values to the emitted lists. Here's the implementation of `buffer(maxSize, timeout)`:

https://github.com/davidmoten/rxjava2-extras/blob/f17e136cde8b4f4dee4bab55a86b480148ed8086/src/main/java/com/github/davidmoten/rx2/flowable/Transformers.java#L622-L639

**Comment by davidmoten** [comment]
@DareUrDream I've added a `buffer(maxSize, timeout)` overload to the PR where the timeout is a function of the last emission.

**Comment by simonbasle** [comment]
@davidmoten would you say this is the rxjava2-extra equivalent of `bufferTimeout`?

> Collect incoming values into multiple List buffers that will be emitted by the returned Flux each time the buffer reaches a maximum size OR the maxTime Duration elapses.

**Comment by davidmoten** [comment]
@simonbasle yeah close. There is a subtle difference in the timeout. `FluxBufferTimeout` starts the timer when the first item in a buffer arrives. The rxjava2-extras version starts the timer on each arrival from the source and the timeout itself can be dependent on the item that arrived. I'm still unclear on @DareUrDream 's use case but at least he has some info in front of him.

**Comment by davidmoten** [comment]
@simonbasle some detail on the timer in the javadoc of `Flux.bufferTimeout` would be good

**Comment by DareUrDream** [comment]
@davidmoten Below is the snapshot of my code..

As per your suggestion to my question in RxJava form https://github.com/ReactiveX/RxJava/issues/6423 , I am planning to change my code to use either bufferWhile or collectWhile from the extras library so that I don't miss records. Would really appreciate some guidance/sample here, as I am not able to find any samples in the doc...

```
Flowable<List<Record>> flowable = observable
					.toFlowable(BackpressureStrategy.BUFFER)
					.subscribeOn(Schedulers.computation())
					.groupBy(callrecord -> callrecord.getSessionid())
					.flatMapSingle(group -> 
						group
							.timeout(2, TimeUnit.HOURS)
							.onErrorResumeNext(Flowable.never())
							.takeUntil(cr -> cr instanceof CCDR && ((CCDR) cr).isCallCompleted())
							.toList()
					);
```

**Comment by simonbasle** [comment]
@DareUrDream if you are going to discuss snippets that are RxJava2 specific, please refrain doing so in a Reactor issue, that is prone to confuse future users that are looking for similar stuff in the context of Reactor 😕

@davidmoten thanks for the clarification. It is true that the timeout is not covered in much details in the javadoc of `bufferTimeout`...

**Comment by DareUrDream** [comment]
Sure @simonbasle .. My bad :-)

**Comment by DareUrDream** [comment]
Closing this as moving the discussion to RxJava groups... Thanks @davidmoten , @simonbasle , @akarnokd
