### ISSUE TITLE
Explore how to optimize onAssembly Hook

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1545]
Avoid volatile check for every operator use. Maybe related to #1541

**Comment by bsideup** [comment]
We just merged #1677 to partially solve this

**Comment by simonbasle** [comment]
Seems like #1677 helped. Anything more to be done @smaldini ? Moving this to 3.3.1.RELEASE in the meantime, will close if you confirm we're in a good enough state.

**Comment by simonbasle** [comment]
Closing as no interaction since september.
