### ISSUE TITLE
Flux.genereate() complete early without understanding why.

### ISSUE THREAD

**Issue by ofekIsrael** [reactor/reactor-core#1550]
Introduction of the general flow: 
1. When a request is got from controller, an object of type "Command" is created, and that "Command" publishes the command as series of chunks. 
2. Many objects of type "Vlb" subscribe to the that "Commnad" and when new chunk is arriving ("onNext") the "Vlb" object handle the command and send the chunk as API request via Spring WebFlux WebClient to "Vlb" server. 
3. for handling the response , a "CommandResponseSubscriber" is registered to the request and  handle the incoming response untill it finishes, then it tells the "Vlb" object to finish its handle command, thus , it can handle the next chunk, so the vlb request from its "subscription"  subscription.request(1).

In concrete command, the command publisher is created via Flux.generate()
```java
1.    public void createSyncPublisher() {
2.        int lastChunk = getChunksAmount();
3.        Flux<CommandMessage> newFlux = Flux.<Command,Integer>generate(() -> sortedChunks.first(),
4.        (chunk, sink) -> {
5.            if (lastChunk < chunk)
6.                sink.complete();
7.            else
8.                sink.next(new CommandMessage(this, chunk.intValue()));
9.            return chunk+1;
10.        }).log();
11.        publisher = Optional.of(newFlux);
12.    }
```
assume sortedChunks have many chunks.
The problem - it works only from the second request.
### Expected behavior
It will go through line 8  as the size of sortedChunks  and then go through line 6

### Actual behavior
it goes through line 8 only once, then it doesn't  go through line 6.

but on the subscriber object (the VLB) it gets "onNext" once and then get "onComplete"

Notes:
1 I tried to put log() but I didn't find and reason why it get the onComplete so soon
2. There is no intermediate operation of the flux 

```java
    public void subscribeToSyncPublisher() {
        VlbSubscriber vlbSubscriber = vlb.getSubscriber();
        publisher.orElse(Flux.empty()).subscribeOn(Schedulers.single())
                .subscribe(vlbSubscriber);
    }

```
3. It works from the second request 

### Reactor Core version
reactor-core.3.2.3.RELEASE
### JVM version (e.g. `java -version`)
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)

**Comment by simonbasle** [comment]
What is the `VlbSubscriber` like exactly? Is there a `Subscription#cancel` call by any chance?
The fact that it works on the second request might indicate some shared mutable state that gets initialized too late and is wrongly seen by the second request, is that possible in your architecture?

**Comment by ofekIsrael** [comment]
> What is the VlbSubscriber like exactly? Is there a Subscription#cancel call by any chance?

As you can see I added in line 10 log(), but it didn't log and cancel siganl, and I try to find if there is...
I'll try to put the log in somewhere else and comment here.

> The fact that it works on the second request might indicate some shared mutable state that gets initialized too late and is wrongly seen by the second request, is that possible in your architecture?

I've already think about it, before I post and I'm pretty sure it doesn't, but yow know what, I'll take a look again and add new comment.

**Comment by ofekIsrael** [comment]
Without understanding what was fixed it, but it wasn't reproduced. 
sorry, and thanks.
