### ISSUE TITLE
Mono.defer executes supplier.get even if subscription is cancelled

### ISSUE THREAD

**Issue by leonard84** [reactor/reactor-core#1559]
The same issue described in #1503 applies for `Mono.defer`.

### Expected behavior
`supplier.get()` is not called if subscription is already cancelled.

### Actual behavior
`supplier.get()` is called even if subscription is cancelled.

### Steps to reproduce
```java

import java.util.concurrent.atomic.AtomicBoolean;

import org.junit.Assert;
import org.junit.Test;
import org.reactivestreams.Subscription;

import reactor.core.publisher.Mono;

public class ReactorTest {

    @Test
    public void defer() throws Exception {
        AtomicBoolean atomicBoolean = new AtomicBoolean(true);
        Mono.defer(() -> {
            atomicBoolean.set(false);
            return Mono.just("Yay");
        }).doOnSubscribe(Subscription::cancel)
                .subscribe();
        Assert.assertTrue("Supplier was executed", atomicBoolean.get());
    }
    @Test
    public void fromCallable()  throws Exception {
        AtomicBoolean atomicBoolean = new AtomicBoolean(true);
        Mono.fromCallable(() -> {
            atomicBoolean.set(false);
            return "Yay";
        }).doOnSubscribe(Subscription::cancel)
                .subscribe();
        Assert.assertTrue("Callable was executed", atomicBoolean.get());
    }
}
```
### Reactor Core version
reactor: 3.2.6.Final

### JVM version (e.g. `java -version`)
Java 8

**Comment by akarnokd** [comment]
The operator works as intended. The subscription can't be cancelled because it doesn't even exist until the `Supplier` is executed and the returned `Mono` subscribed to.

**Comment by simonbasle** [comment]
As a workaround that is a closer fit to your original problem (with a `CompletableFuture`), here is a solution:

```java
Mono.fromSupplier(webTarget.request().rx())
    .hide()
    .flatMap(Mono::fromFuture)
```

**Comment by leonard84** [comment]
@simonbasle could you explain a bit why solves the problem. The Javadoc for `hide()`is rather vague. 
> Hides the identity of this {@link Mono} instance.
>	 
>The main purpose of this operator is to prevent certain identity-based
>optimizations from happening, mostly for diagnostic purposes.

**Comment by simonbasle** [comment]
the purpose of `hide()` is to avoid fusion between `flatMap` and `fromSupplier` which could accelerate the invocation of the `Supplier`, too early for the cancellation to register.
