### ISSUE TITLE
Application does not finish immediately when using schedulers

### ISSUE THREAD

**Issue by akshaypatil-bex** [reactor/reactor-core#1636]
### Expected behavior
Application should immediately exit after running all code.
### Actual behavior
Application waits for 1-2 minutes after running all code and then exits successfully.

### Steps to reproduce

Run this code to see this behaviour

```
package com.example;

import lombok.extern.slf4j.Slf4j;
import reactor.core.publisher.Flux;
import reactor.core.scheduler.Schedulers;

import java.util.Arrays;
import java.util.List;
import java.util.stream.IntStream;

@Slf4j
public class ReactorDemo {
    public static void main(String[] args) throws InterruptedException {
        Flux<Integer> source = Flux.fromStream(IntStream.iterate(10, i -> i - 1).boxed());
        List<Integer> numbers = source
                .publishOn(Schedulers.newElastic("t"))
                .takeWhile(i -> i > 0)
                .collectList()
                .log()
                .block();
        logNumbers(numbers);
        log.info("Done with everything");
    }

    private static void logNumbers(List<Integer> numbers) {
        log.info("Numbers : " + Arrays.toString(numbers.toArray()));
    }
}
```

### Reactor Core version
3.2.8.RELEASE

### JVM version (e.g. `java -version`)

```
$ java -version
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
```

## Additional notes
When not using any schedulers, I noticed the application finishes immediately after running the code.

**Comment by simonbasle** [comment]
`Schedulers.newElastic()` by default doesn't use `daemon` threads. Use `Schedulers.newElastic("t", 60, true)` to have daemon threads and let the JVM exit immediately (instead of waiting for the threads to die down of age)
