### ISSUE TITLE
Javadoc diagrams fail to render in Eclipse with Reactor 3.2.4+

### ISSUE THREAD

**Issue by akiraly** [reactor/reactor-core#1638]
### Expected behavior

Diagrams showing up in Eclipse (2019-03 but also in earlier versions) in javadoc (for example when mouse overing a method).

![image](https://user-images.githubusercontent.com/557348/55115422-bf137600-50e4-11e9-8ad6-eee60fabf089.png)

### Actual behavior

The text shows up but instead of the diagram an X is shown.

![image](https://user-images.githubusercontent.com/557348/55115364-9ab79980-50e4-11e9-9907-7ff65a7190f9.png)

### Steps to reproduce

Mouse over a method in Eclipse

### Reactor Core version
Any reactor version starting with 3.2.4 (worked in 3.2.3). It happens with the current (3.2.8) release as well.

### JVM version (e.g. `java -version`)
Both with Java 8 and 11

**Comment by simonbasle** [comment]
It seems Eclipse is not capable of getting the embedded images from within the `-sources.jar`, despite the artifact having the `doc-files`. But it does from `-javadoc.jar`. Configure Maven in Eclipse preferences to "Download Artifact Javadoc".

**Comment by akiraly** [comment]
I think this issues is related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=464439

**Comment by simonbasle** [comment]
@akiraly I actually opened https://bugs.eclipse.org/bugs/show_bug.cgi?id=545882#c2

**Comment by simonbasle** [comment]
unfortunately it doesn't seem like they're willing to fix their widget getting the javadoc images in a `-sources.jar`, since the issue has been marked as duplicate of bugs.eclipse.org/bugs/show_bug.cgi?id=464439 which had been dead for 2 years 😢

so Download Artifact Javadoc is the only way to go for now
