### ISSUE TITLE
reactor-core does not declare a stable automatic module name

### ISSUE THREAD

**Issue by ashcoll** [reactor/reactor-core#1641]
### Expected behavior

Hope `reactor-core-3.2.8.RELEASE` support java9+ modular system!

### Actual behavior

it does not support java9+ modular system!

### Steps to reproduce

use reactor-core in my Jigsaw multi-module maven project, but it does not work.

Next, I inspected the reactor-core-3.2.8.RELEASE jar file, 
1. there is no `module-info.java` file.
1. and there is no `Automatic-Module-Name` attribute in META-INF/MANIFEST.MF file.

### Reactor Core version

3.2.8.RELEASE

### JVM version (e.g. `java -version`)

java 11.0.1

**Comment by simonbasle** [comment]
The fallback of solving from artifact filename should work with a result of `reactor.core`. However, I think that is a sane enough choice that we can "make it official" with an `Automatic-Module-Name` entry in the manifest. cc @bsideup @smaldini @violetagg for feedback and to do the same in other projects?

**Comment by bsideup** [comment]
@simonbasle since it does not require a JDK update and only a matter of adding a line to the manifest, I support the idea of adding an `Automatic-Module-Name` entry 👍

**Comment by simonbasle** [comment]
any counter-argument to using these: `reactor.core`, `reactor.test`, `reactor.extra`, `reactor.netty`, ... ?

**Comment by bsideup** [comment]
we need to double check that we have no conflicts with the packages.
AFAIK going jigsaw also enforces "exclusive package" rule, when two modules cannot contain the same package

**Comment by simonbasle** [comment]
right. so far I don't see a split package in `reactor-core` and addons (`reactor-extra` mainly), but the fact that `reactor-extra` uses `reactor` as root package might prove problematic...
Also, `reactor-core` has most of the code in `reactor.core` package, but it also has _some_ in `reactor.adapter` and `reactor.util`. These last two I'm a bit more concerned about.

**Comment by simonbasle** [comment]
Fixed as part of reactor/reactor#667 in #1692 / f8a2dac16903265a00b6e50ee1a69c0cb72b8f57
