### ISSUE TITLE
Mono creation from CompletionStage should unwrap CompletionException

### ISSUE THREAD

**Issue by mp911de** [reactor/reactor-core#1652]
Creating a `Mono` from `CompletableFuture` (`CompletionStage`) should unwrap `CompletionException` to not always require `onErrorMap(CompletionException.class, Throwable::getCause)`.

### Expected behavior

```java
CompletableFuture<String> future = new CompletableFuture<>();

Mono.fromCompletionStage(future.whenComplete((s, throwable) -> {
    throw new IllegalStateException("Boom!");
}))
        .as(StepVerifier::create)
        .then(() -> future.complete("Success"))
        .verifyError(IllegalStateException.class);
```
### Actual behavior

`CompletionException` is propagated if a future callback raises an exception.

### Reactor Core version

3.2

**Comment by smaldini** [comment]
Agree with this @simonbasle
