### ISSUE TITLE
Mono.zip instantly completes when Flux.then completes

### ISSUE THREAD

**Issue by cbossi** [reactor/reactor-core#1659]
### Expected behavior
Mono.zip waits for all Mono's to be completed.

### Actual behavior
Whene I use ``Flux.then()`` inside ``Mono.zip()``, the zip-method instantly completes as soon as the then-method completes, even though other Mono's (inside the zip-method) are not yet completed - those are cancelled.

### Steps to reproduce
The following sample code shows the problem:
```
Mono.zip(
        Flux.interval(Duration.ofSeconds(1)).take(3)
            .log("interval")
            .then()
            .log("then"),
        Mono.delay(Duration.ofSeconds(1))
            .log("fastMono"),
        Mono.delay(Duration.ofSeconds(10))
            .log("slowMono"),
        Mono.never()
            .log("never")
    ).log("zip")
        .block();
```

Here's the log output of above sample:
```
16:09:37.738 [main] INFO zip - onSubscribe([Fuseable] MonoZip.ZipCoordinator)
16:09:37.740 [main] INFO zip - request(unbounded)
16:09:37.748 [main] INFO interval - onSubscribe(FluxTake.TakeSubscriber)
16:09:37.748 [main] INFO then - onSubscribe(MonoIgnoreElements.IgnoreElementsSubscriber)
16:09:37.748 [main] INFO then - request(unbounded)
16:09:37.748 [main] INFO interval - request(unbounded)
16:09:37.751 [main] INFO fastMono - onSubscribe(MonoDelay.MonoDelayRunnable)
16:09:37.751 [main] INFO fastMono - request(unbounded)
16:09:37.753 [main] INFO slowMono - onSubscribe(MonoDelay.MonoDelayRunnable)
16:09:37.754 [main] INFO slowMono - request(unbounded)
16:09:37.758 [main] INFO never - onSubscribe([Fuseable] Operators.EmptySubscription)
16:09:37.758 [main] INFO never - request(unbounded)
16:09:38.753 [parallel-1] INFO interval - onNext(0)
16:09:38.754 [parallel-2] INFO fastMono - onNext(0)
16:09:38.756 [parallel-2] INFO fastMono - onComplete()
16:09:39.751 [parallel-1] INFO interval - onNext(1)
16:09:40.751 [parallel-1] INFO interval - onNext(2)
16:09:40.751 [parallel-1] INFO interval - onComplete()
16:09:40.751 [parallel-1] INFO then - onComplete()
16:09:40.752 [parallel-1] INFO fastMono - cancel()
16:09:40.752 [parallel-1] INFO slowMono - cancel()
16:09:40.752 [parallel-1] INFO never - cancel()
16:09:40.752 [parallel-1] INFO zip - onComplete()
```

As soon as the then-Method completes, all other Mono's are cancelled and the zip-method therfore completes.

### Reactor Core version
3.2.8.RELEASE

### JVM version (e.g. `java -version`)
11.0.2 (Oracle Corporation 11.0.2+9-LTS)

**Comment by simonbasle** [comment]
`zip` doesn't make sense with `then`, as the later suppresses all `onNext` signals whereas `zip` expects ALL sources to emit one `onNext` before it can emit one zipped value (ie it has the same cardinality as the smallest source).

**Comment by simonbasle** [comment]
you might be after `when()`, which completes (empty) _when_ all sources have completed

**Comment by cbossi** [comment]
@simonbasle thanks, ``when()`` is exactly what I need.

What I still don't understand: Why does the zip-method in the example above ever complete? One of it's inputs is ``Mono.never()`` which I assume will never produce an item. In the Javadoc of ``Mono.zip`` it is written:
```
Aggregate given monos into a new {@literal Mono} that will be fulfilled when all of the given {@literal Monos} have produced an item
```
Shouldn't ``Mono,zip`` then wait forever in the above example?

**Comment by simonbasle** [comment]
The javadoc goes onto saying that
```
 An error or <strong>empty</strong> completion of any source will cause other sources
 to be cancelled and the resulting Mono to immediately error or complete, respectively.
```
