### ISSUE TITLE
Have osgi compatible attribs for sources jar

### ISSUE THREAD

**Issue by frankbenoit** [reactor/reactor-core#1662]
### Expected behavior
Using reactor in Eclipse, it shall be able to navigate to the sources.

The content of the sources jar MANIFEST.FM should have this content:
````
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-SymbolicName: io.projectreactor.reactor-core.source
Bundle-Version: 3.2.8.RELEASE
Eclipse-SourceBundle: io.projectreactor.reactor-core;version="3.2.8.RELEASE";roots:="."
````

Ideally the binary jar and the source jar would have the naming

currently:
reactor-core-3.2.8.RELEASE.jar   
reactor-core-3.2.8.RELEASE-sources.jar   

ideally:
reactor.core_3.2.8.RELEASE.jar
reactor.core.source_3.2.8.RELEASE.jar

### Actual behavior
the attributes are missing and the naming is not matching the naming conv.

### Reactor Core version
3.2.8

**Comment by simonbasle** [comment]
we're not going to publish new artifacts with different naming conventions. furthermore, I couldn't find a way to add attributes to the sources jar manifest with BND-tools (the official BDN Gradle plugin) nor with the Gradle osgi plugin (which is now deprecated in favor of the former).

the best solution I could find is the `bnd-platform` Gradle plugin, which seems to be made with your particular case in mind: building an Eclipse plugin out of your "platform" dependencies, repackaging said dependencies with OSGI information and Eclipse PDE conventions (including `Eclipse SourceBundle` in the sources jar).

https://github.com/stempler/bnd-platform

**Comment by frankbenoit** [comment]
Hi Simon,

thanks for pointing me there.

If someone else stumbles about this, solution for me was:
````
buildscript {
	repositories {
		jcenter()
	}
	dependencies {
		classpath 'org.standardout:bnd-platform:+'
	}
}

apply plugin: 'org.standardout.bnd-platform'

repositories {
	mavenCentral()
}

platform {
    bundle 'io.projectreactor:reactor-core:3.+'
    bundle 'io.projectreactor.addons:reactor-extra:3.+'	
    bnd (group: 'io.projectreactor.addons', name: 'reactor-extra') {
        optionalImport 'kotlin.*'
    }
}
````

run `gradle bundles` and you find the bundles in `build/plugins`

cu
Frank
