### ISSUE TITLE
block causes the subscriberContext to be lost

### ISSUE THREAD

**Issue by bpwalford** [reactor/reactor-core#1667]
### Expected behavior
When calling .block() the subscriberContext should still be accessible

### Actual behavior
Calling .block() causes the subscriberContext to be lost

### Steps to reproduce

result is "failed"
``` java
String result = Mono.just("stuff")
    .map(str -> Mono.subscriberContext()
        .map(ctx2 -> {
            if (ctx2.isEmpty()) {
                return "failed";
            } else {
                return "success";
            }
        })
        .block())
    .subscriberContext(ctx -> ctx.put("foo", "bar"))
    .block();
```

### Reactor Core version
3.1.0.RELEASE

### JVM version (e.g. `java -version`)
java version 1.8.0_181

**Comment by simonbasle** [comment]
This is one of the reasons why calling `block()` or `subscribe()` inside a reactive chain is a code smell. Use `flatMap(i -> x)` instead of `map(i -> x.block())`.

**Comment by bpwalford** [comment]
@simonbasle I completely agree, flatmap is the way to go in the example I gave. However, the example I provided was meant to be a boiled down version of the issue I'm running into within a larger project.

Despite the best practice being flatmap in this case, is it still the expectation that the subscriberContext is lost after calling block?

If it helps, the use case where this problem is happening is a spring webflux app using a custom Jackson serializer that requires data from the subscriberContext. The Jackson serializer interface is not inherently reactive forcing the app to call block() in the serializer. And since the serializer is invoked through spring/Jackson there's no direct way to pass the subscriberContext data that is required.

**Comment by simonbasle** [comment]
Context simply cannot be reached outside of a continuous chain of Reactor operators, so there's no way around it. Can't the serializer be invoked from a Mono.fromCallable ?

**Comment by bsideup** [comment]
@bpwalford
> Despite the best practice being flatmap in this case

It is worth noting that this is not the best practice in this case, but `block` inside `map` is a misuse. You can also use `.handle` to access the context:
```java
Mono.just("stuff").handle((str, sink) -> {
    Context context = sink.currentContext();

    if (context.isEmpty()) {
	    sink.next("failed");
    } else {
	    sink.next("success");
    }
})
```

**Comment by bpwalford** [comment]
@bsideup Thanks for the pointer, I'm definitely still getting the hang of reactor and reactive programming.

@simonbasle Unfortunately I don't think Mono.fromCallable will work. It's the framework that's invoking the serializer. This behavior could be overridden, but even so, the serializer itself needs to be able to access the subscriberContext since the interface does not support passing in contextual data. I suspect I'm going to be stuck building a serializer from scratch or rethinking this altogether.
