### ISSUE TITLE
doOnSubscribe/flatMap execution order

### ISSUE THREAD

**Issue by pavelkryl** [reactor/reactor-core#1676]
### Expected behavior
I have the following code (kotlin):

```
fun main() {
    val stream = Mono.just(1)
        .flatMap {
            log("work")
            Mono.just(2)
        }
        .doOnSubscribe {
            log("subscribe")
        }.doOnSuccess {
            log("success")
        }
    stream.block()
}
```

I would expect that following is printed:

> subscribe
> work
> success

### Actual behavior
I am however getting:

> work
> subscribe
> success

### Steps to reproduce
Execute the above.

Note 1: there are modifications/workarounds which fix the above:
- replace `flatMap()` just with `map()` (and return directly '2')
- place another `doOnSubscribe()` right after `Mono.just()`
- place `delayElement()` right after `Mono.just()`

Note 2: if I write a similar code in RxJava, it works well:

```
fun main() {
    val stream = Single.just(1)
        .flatMap {
            log("work")
            Single.just(2)
        }
        .doOnSubscribe {
            log("subscribe")
        }.doOnSuccess {
            log("success")
        }
    stream.blockingGet()
}
```

This prints:

> subscribe
> work
> success

The buggy behavior disallows us to write a nice generic logging (start/stop) routine.

### Reactor Core version
`3.2.8`

### JVM version (e.g. `java -version`)
`java version "11.0.2" 2019-01-15 LTS`

**Comment by simonbasle** [comment]
This is due to the `Mono.just` source, which is conceptually simplified to a `Callable`.
`flatMap` sees that as an opportunity to optimize the call and resolve both the source value and the mapped `Publisher` immediately, in case said derived `Publisher` can also be simplified to a `Callable`. This avoids waiting for a `Subscription#request` when the value is readily available.

`doOnSubscribe` is tied to the `onSubscribe` event, not the act of calling `subscribe()`. The subtle thing is that `onSubscribe` is called by the upstream `Publisher` (the "source") to notify its `Subscriber` that it is ready to emit, at the subscriber's demand (by passing a `Subscription` through which the Subscriber can `request(n)`).

Sometimes operators perform some pre-computations before sending this notification, which is the case with the callable optimization discussed above.

Since what you seem to be after is a foolproof way of doing a side effect at the moment `subscribe` is called, there is a workaround:

```java
	@Test
	public void subscribeWorkSuccessOrder() {
		List<String> events = new CopyOnWriteArrayList<>();

		Mono<Integer> test = Mono.defer(() -> {
			events.add("subscribe");
			return Mono.just(1)
			           .flatMap(i -> {
				           events.add("work");
				           return Mono.just(2);
			           })
			           .doOnSuccess(i -> events.add("success"));
		});

		test.block();

		assertThat(events).containsExactly("subscribe", "work", "success");
	}
```

**Comment by pavelkryl** [comment]
Thank you for your response. I would like to point out that this problem does not happen because of the Mono.just(), same thing happens with Mono.defer() - and possibly with other calls. Although I understand that there might be a reason for optimization, if it breaks the logical flow of the event handling, then it is wrong to perform the optimization.

Thank you for pointing out that doOnSubscribe is signaled by the publisher, although I consider this unintuitive: could it happen that there is a subscribe request and the publisher responds with 'no I am not ready to subscribe and never will' - this could be signaled by exception - or 'I am not ready but wait a few seconds'? Is there any good reason for not binding the doOnSubscribe to the subscribe() method call? Obviously RxJava handles this differently and from my point of view is better/simpler.

### Context
I will try to introduce the whole context of the problem and why I think that doOnSubscribe is better to call on subscribe event and not before first emission.

We would like to log actions happening during reactive processing easily. Instead of doing:

```
   // log start - this is wrong, we should do this on subscribe (before restful invocation)
   log.info("action start")
   // do some work
   facade.restFulInvocationMono()
     .doOnSuccess {
        log.info("action end")
     }.doOnError( e ->
        log.info("action error", e)
     }

```
We would like to simply do:

```
   facade.restFulInvocationMono()
     .logRestfulAction("action", restfulUri)
```
Which could be implemented as follows:

```
fun <U> Mono<U>.logRestfulServerStartEndAction(
    actionName: String,
    receiveUri: String     // sample: [GET]/inbox/{pid}/messages
): Mono<U> {
    return this.
        doOnSubscribe {
            logActionStart(actionName, receiveUri)
        }.doOnSuccess {
            logActionComplete(actionName)
        }.doOnError {
            logActionError(actionName)
        }
}
```
This implementation works for some reactive chains, but whenever we introduce some preparation actions using Mono.defer() and we are doing some logging in the defer() supplier, these logs in supplier appear before actual logActionStart() which is really confusing.

### Workaround
So because of the 'optimized behavior', we must do this workaround:

```
fun <U> Mono<U>.logRestfulServerStartEndAction(
    actionName: String,
    receiveUri: String     // sample: [GET]/inbox/{pid}/messages
): Mono<U> {
    return this.
        subscriberContext {
            logActionStart(action, receiveUri)
            it
        }.doOnSuccess {
            logActionComplete(actionName)
        }.doOnError {
            logActionError(actionName)
        }
}
```
What is your opinion now when you have a broader context?

**Comment by simonbasle** [comment]
You have a point that this is confusing. These method hook into the signals of a `Subscriber` and Subscriber doesn't have a `subscribe()` method. The unfortunate thing is that `Subscriber#onSubscribe` and `Publisher#subscribe` method names are so close, so it makes `Flux#doOnSubscribe` a bit ambiguous.

The intent of `doOnSubscribe` was for cases when you want to look at the `Subscription` object, which sometimes comes deferred.

Unfortunately, this is also the closest method people find that **seems** to allow "logging the start of the sequence" / "logging the `subscribe()` call".

So maybe we need a new `do???(Runnable)` method that is more obviously dedicated to that, like `doFinally` is dedicated to covering all possible ends of a sequence.

Descriptive and differentiated naming is hard though...
A few ideas:
 - `doFirst`
 - `doFirstly` (better suggests the opposite of `doFinally`?)
 - `doPreliminarily`
 - `doAtStart`
 - `doOnPublisherSubscribe`
 - ...

**Comment by pavelkryl** [comment]
I vote for doFirst(). Or as an opposite to doAfterTerminate my suggestions are:

- doBeforeSubscription
- doBeforeSubscribe
- doBeforeSubscribeEvent
- ...

**Comment by simonbasle** [comment]
See #1716 for the introduction of a new side-effect operator
