### ISSUE TITLE
Flux.generate should wrap and throw exception in poll using propagate, not bubble

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1685]
Error is not thrown due to a missuse of Exceptions.bubble :
https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/FluxGenerate.java#L339

**Comment by simonbasle** [comment]
Does it even make sense to `bubble` here? When `SYNC` fusion is enabled, the polling of the operator would not result in `onError` but when no fusion is in place it would?

**Comment by simonbasle** [comment]
Moving forward with also changing `Exceptions.bubble(t)` to `Exceptions.propagate(t)`.
