### ISSUE TITLE
Javadoc of Reactor artifact members doesn't display (SVG) images in IntelliJ IDEA

### ISSUE THREAD

**Issue by vy** [reactor/reactor-core#1686]
**Reactor:** 3.2.8.RELEASE
**IntelliJ IDEA:** 2019.1.1 (Ultimate Edition) build 191.6707.61
**JRE:** 1.8.0_202
**OS:** Xubuntu 18.04.2 LTS

**Comment by szjani** [comment]
I have the same issue.

**Reactor:** 3.2.8
**IntelliJ IDEA:** 2019.1.1 (Ultimate Edition) build 191.6707.61
**JRE:** 11.0.2
**OS:** Windows 10 Enterprise

![intellij-nomarble](https://user-images.githubusercontent.com/545872/57136509-62733d00-6dad-11e9-8a31-41a8e64c1eaf.png)

**Comment by simonbasle** [comment]
Are you both using `Maven` (and which version)? Did you configure Maven to download source jars? What about javadoc jars?

**Comment by vy** [comment]
Yes, I am using Maven 3.6.0. In the Maven pane of IDEA, I tried downloading the sources and documentation for Reactor, that that did not help either.

**Comment by simonbasle** [comment]
It looks like there is an issue with `-javadoc.jar` artifacts display of embedded doc-files in IntelliJ. I was able to reproduce from a simple Maven project prepared on start.spring.io, with the Maven importer configured to NOT download source/javadoc jars:

 - by default nothing shows up in the quick doc panel
 - downloading the sources jar, the diagram shows up
 - downloading the javadoc jar, the diagram **disappears**
 - removing the javadoc jar from local maven repo, diagram comes back
 - starting without the sources but just the javadoc jar, diagram still doesn't appear

So it sounds like an IntelliJ issue with Maven + javadoc jar + `doc-files` 😞

Workaround would be to remove the javadoc jar from Maven local repo and downloading **only** the `-sources.jar`.

**Comment by simonbasle** [comment]
see IntelliJ issue: https://youtrack.jetbrains.com/issue/IDEA-212079

**Comment by vy** [comment]
Thanks so much for the lightening fast action @simonbasle! Gonna +1 the JetBrains ticket.

**Comment by neerajjain92** [comment]
Hey is this resolved yet ?
