### ISSUE TITLE
Document subscriberContext usage in reference guide, maybe with code snippets

### ISSUE THREAD

**Issue by zhouzhou19950825** [reactor/reactor-core#1694]
If necessary, I can provide some demos.And some Objects cleanup demos.

**Comment by simonbasle** [comment]
That would be interesting, I think, yes. You do mean snippets in the documentation @zhouzhou19950825, right? or more like tests?

**Comment by simonbasle** [comment]
the operator has been renamed in 3.4.0 for clarity, and `Context` handling is explained in details in the reference documentation: https://projectreactor.io/docs/core/release/reference/#context
