### ISSUE TITLE
Better default WaitStrategy when running on low CPU number hardware

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#17]
Currently WaitStrategy are quite CPU demanding and favor latency over cycles. However, using current machine CPU number we can avoid using these waiting strategies and try more relaxed ones (WaitStrategy.blocking() & liteBlocking()).

**Comment by ifesdjeen** [comment]
Do you mean timer or disruptor strategies? ;)  even though they implement the same interface they are unfortunately not compatible with each other iirc

**Comment by smaldini** [comment]
Consider it closed since emergence of alternative ExecutorService schedulers.
