### ISSUE TITLE
Have an API to await subscriber

### ISSUE THREAD

**Issue by frankbenoit** [reactor/reactor-core#1703]
### Expected behavior
I want to subscribe with a class implementing `Subscriber`. 
And I want to await this flux/mono to be finished.

There is the `reactor.publisher.BaseSubscriber` class.
Can it get a `BaseSubscriber.await()` and `BaseSubscriber.await(Duration)` ?

I think this might be useful as generic API.

### Actual behavior
the Flux.subscribe(Subscriber) returns void.
BaseSubscriber does not have an API to wait for finished state.

### Steps to reproduce
not needed

### Reactor Core version
3.2.9

### JVM version (e.g. `java -version`)
1.8

**Comment by simonbasle** [comment]
We don't want to further promote blocking on subscribers. Adding such a method on your implementation of `BaseSubscriber` isn't that much overhead fortunately:

```java
public abstract class CustomBaseSubscriber<T> extends BaseSubscriber<T> {
    
    private CountDownLatch latch = new CountDownLatch(1);

    protected void hookFinally(SignalType sig) {
        latch.countDown();
    }

    public void await() throws InterruptedException {
        latch.await();
    }

    public boolean await(long timeout, TimeUnit unit)
        throws InterruptedException {
        return latch.await(timeout, unit);
    }
}
```
