### ISSUE TITLE
bufferUntilChange operator proposal

### ISSUE THREAD

**Issue by jhaeyaert** [reactor/reactor-core#1706]
Hi,

I was wondering if the `Flux.bufferUntilChange` operator could be appropriate ?
Basically, this operator could collect incoming values into multiple List buffers that will be emitted by the resulting Flux each time the emitted value differ from the previous emitted value.

This operator could be declined as follow :

- `bufferUntilChange()`
- `bufferUntiChange(Function<? super T, ? extends V> keySelector)`
- `bufferUniltChange(Function<? super T, ? extends V> keySelector, BiPredicate<? super V, ? super V> keyComparator)`

Do you think this kind of operator could be a candidate for a future release ?

**Comment by simonbasle** [comment]
Can you give examples of expected inputs vs outputs of such an operator? If I understand the intent correctly, it would be to do something similar to `distinctUntilChanged`, but collecting the similar values? (which can be different instances if the `keyExtractor` is not congruent with objects' `equals` methods)

**Comment by jhaeyaert** [comment]
Yes this definitively similar to `distinctUntilChanged` operator but instead of dropping similar values it will buffer them and emit `List` each time the value differ from previous one.

Some examples :

Use of `Flux<T> bufferUntilChanged()` without argument will use the default `equals` method to compare the last element with the previous one.

```
+---A---A---A---B---B---C---D---D---A---|->

bufferUntilChanged()

+---[A,A,A]---[B,B]---[C]---[D,D]---[A]---|->
```

Use of `<V> Flux<T> bufferUntilChanged(Function<? super T, ? extends V> keySelector)` with key selector allows to define the key used for comparison.
Note : `(A,1)` is an object with `String field1=A` and `int field2=1`
```
+---(A,1)---(A,2)---(A,3)---(B,1)---(D,1)---(D,1)---(A,2)---|->

bufferUntilChanged(o -> o.getField1())

+---[(A,1),(A,2),(A,3)]---[(B,1)]---[(D,1),(D,1)]---[(A,2)]---|->
```

Use of `<V> Flux<T> bufferUntilChanged(Function<? super T, ? extends V> keySelector, BiPredicate<? super V, ? super V> keyComparator)` with key selector and key comparator allows to define the key used for comparison and the function used to compare keys.
Note : this time we will compare only `field2`.
```
+---(A,1)---(A,2)---(A,3)---(B,1)---(D,1)---(D,1)---(A,2)---|->

bufferUntilChanged(o -> o.getField2(), (o1, o2) -> o1 == o2)

+---[(A,1)]---[(A,2)]---[(A,3)]---[(B,1)]---[(D,1),(D,1)]---[(A,2)]---|->
```

Is this the level of detail you've been waiting for ?

**Comment by simonbasle** [comment]
That should be easy enough to do with `distinctUntilChanged` as a base :+1:

**Comment by simonbasle** [comment]
Ah snap, there's one thing that I totally overlooked in #1846 : stateful predicate at operator level is bad!
Each subscription to the resulting `Flux` will share the same `lasKey` state :(

Demonstration:

```java

	@Test
	public void untilChangedNoSharedState() {
		List<List<Integer>> buffers = new CopyOnWriteArrayList<>();
		List<Integer> list1 = Arrays.asList(1, 1, 1, 1);
		List<Integer> list2 = Arrays.asList(3, 3, 2, 2, 2, 2, 2, 2, 2, 2);
		AtomicBoolean first = new AtomicBoolean();

		Flux<List<Integer>> source = Flux.defer(() -> {
			if (first.compareAndSet(false, true)) {
				return Flux.fromIterable(list1).delayElements(Duration.ofMillis(200));
			}
			first.set(false);
			return Flux.fromIterable(list2).delayElements(Duration.ofMillis(50));
		})
				.bufferUntilChanged();

		Mono.when(
				source.map(buffers::add),
				source.map(buffers::add)
		).block();

		List<Integer> flattened = buffers.stream().flatMap(List::stream).collect(Collectors.toList());
		System.out.println(flattened);
		Assertions.assertThat(flattened).containsExactly(3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1);
	}
```
fails and prints:
```
[3, 3, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1]
```
