### ISSUE TITLE
OOME is occurred due to Throwable#addSuppressed at BlockingSingleSubscriber

### ISSUE THREAD

**Issue by be-hase** [reactor/reactor-core#1710]
### Steps to reproduce

Unfortunately, netty's Read(Write)TimeoutError is singleton.
This code can cause OOME.

https://github.com/reactor/reactor-core/blob/c86db5aa0cc648520c8f95349232b314cb6e953e/reactor-core/src/main/java/reactor/core/publisher/BlockingSingleSubscriber.java#L132-L133

In fact, in my environment, when a network trouble occurs, the heap accumulates and OOME has occurred.

I also created issue in netty-side.
https://github.com/netty/netty/issues/9151

### Reactor Core version

3.2.8.RELEASE

### JVM version (e.g. `java -version`)

```
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
```

**Comment by be-hase** [comment]
netty team has fixed.
https://github.com/netty/netty/pull/9152

It is OK to close this PR.
However, the same issues will occur if there are other non-singleton exceptions in the future.

**Comment by simonbasle** [comment]
Will close this for now, but we might indeed explore ways to either avoid suppressed exceptions OR allowing libraries and users to register singleton exceptions to be excluded from addSuppressed
