### ISSUE TITLE
Consecutive doOnSubscribe order

### ISSUE THREAD

**Issue by philsttr** [reactor/reactor-core#1713]
Since the `onSubscribe` signal flows "upstream" (from the end to the beginning of the stream), I would expect that when consecutive `doOnSubscribe` operators exist in the chain, the Consumers passed to `doOnSubscribe` would be executed in the _opposite_ order in which they were added to the chain.

Instead, it appears the Consumers are executed in the order in which they were added to the chain.

### Other observations
When other operators are added _between_ multiple `.doOnSubscribe` calls, the Consumers are executed in the expected order (bottom up) at subscription time.

Functions passed to consecutive `subscriberContext(Function)` calls, which is something else that happens at subscription time, are called in the expected way (e.g. bottom up), so it seems like it would be feasible for `doOnSubscribe` to also be called in this order.

Runnables passed to consecutive `doOnCancel` calls are executed in the expected way as well (e.g. bottom up), since the `cancel` signal also flows upstream.

And yes, consecutive `doOnSubscribe` calls could be combined and code ordered as needed  _when they exist in the same method_. But I first noticed this when a `doOnSubscribe` was the last operator added to a mono returned from a downstream method, and `doOnSubscribe` was the first operator added to the returned mono in an upstream method.  Due to separation of concerns, the consecutive `doOnSubscribe` calls could not be combined in this case.

### Expected behavior

Expect this simplified test case to pass

```java
    @Test
    void doOnSubscribe_consecutive() {
        List<String> list = new ArrayList<>();
        Mono.empty()
                .doOnSubscribe(s -> list.add("A"))
                .doOnSubscribe(s -> list.add("B"))
                .block();
        assertEquals(List.of("B", "A"), list);
    }
```

### Actual behavior

above test fails.

### Steps to reproduce

execute above test

### Reactor Core version

3.2.8.RELEASE

### JVM version (e.g. `java -version`)

11.0.2

**Comment by smaldini** [comment]
Hey @philsttr - this is actually an interesting issue and a confusing lifecycle problem.
Reactive Streams and Reactor uses 2 signals:
- subscribe (from right to left)
- onSubscribe (from left to right)

`doOnSubscribe` matches the second onSubscribe signal. We're open to suggestion to clear that confusion, we could add `doSubscribe` or `doOnStart` but I agree this is something we should address

**Comment by philsttr** [comment]
Ah, interesting.  Yeah, I was thinking onSubscribe went from right to left.  My mistake.

If that is the case, then this issue could probably be closed, and a new feature request opened for a do* method for the subscribe signal.  That is definitely a signal for which I'd like to have a callback.

I don't really have any naming suggestions.  I think any name is going to be somewhat confusing, given that there is already a doOnSubscribe

**Comment by simonbasle** [comment]
Duplicate of #1676 
I'll open a separate issue for a new `do*` method that ties to `Publisher#subscribe()`.

**Comment by simonbasle** [comment]
See #1716
