### ISSUE TITLE
Items are intermittently lost when flat mapping includes a Mono that uses the elastic scheduler

### ISSUE THREAD

**Issue by wilkinsona** [reactor/reactor-core#1719]
### Expected behavior

When flat mapping, all Monos are considered irrespective of the scheduler they use

### Actual behavior

The use of the elastic scheduler causes a Mono to be intermittently missed

### Steps to reproduce

Run the following code:

```java
for (int i = 0; i < 10000; i++) {
	Map<String, Mono<Integer>> input = new HashMap<String, Mono<Integer>>();
	input.put("one", Mono.just(1));
	input.put("two", Mono.create(
			(sink) -> Schedulers.elastic().schedule(() -> sink.success(2))));
	input.put("three", Mono.just(3));
	int sum = Flux.fromIterable(input.entrySet())
			.flatMap((entry) -> Mono.zip(Mono.just(entry.getKey()),
					entry.getValue()))
			.collectMap(Tuple2::getT1, Tuple2::getT2).map((items) -> {
				AtomicInteger result = new AtomicInteger();
				items.values().forEach(result::addAndGet);
				return result.get();
			}).block();
	assertThat(sum).as("Iteration %s", i).isEqualTo(6);
}
```

After approximately 100 iterations, the assertion will fail with the sum being 4 rather than 6. The problem does not occur if `log()` is called on the result of the call to `Mono.zip`.

I realise the logic above is a bit odd as it ignores the keys. It's a simplification of [something in Spring Boot](https://github.com/spring-projects/spring-boot/blob/a5537bd2e1179e52e009cc88882087d9a762d5e3/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/CompositeReactiveHealthIndicator.java#L83-L87) that uses the keys. The above is just intended to be as close to the Boot code as possible while also being as minimal as possible.

### Reactor Core version

3.3.0.M1

### JVM version (e.g. `java -version`)

1.8.0_181

**Comment by simonbasle** [comment]
(fix also deployed in 3.3.0.M2)
