### ISSUE TITLE
doOnSuccessOrError refers to doOnTerminateForMono marble

### ISSUE THREAD

**Issue by dkroehan** [reactor/reactor-core#1725]
The JavaDoc of `Mono<T> doOnSuccessOrError(BiConsumer<? super T, Throwable> onSuccessOrError)` in reactor.core.publisher.Mono.java is referencing the marble file 
`<img class="marble" src="doc-files/marbles/doOnTerminateForMono.svg" alt="">`

See: https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/Mono.java#L2218

That doesn't look right to me. The marble shows a Runnable param whereas doOnSuccessOrError uses a BiConsumer param.

Maybe a copy-paste error (Mono#doOnTerminate is the next method that follows).

FYI: https://github.com/reactor/reactor-core/tree/master/reactor-core/src/main/java/reactor/core/publisher/doc-files/marbles
does not contain a doOnSuccessOrError.svg yet.

### Reactor Core version

In current master

**Comment by simonbasle** [comment]
That's right, `doOnSuccessOrError` is specific to `Mono` and needs a dedicated diagram. I'll get it in in 3.2.10
