### ISSUE TITLE
Replace `Supplier<Queue>` with static `Function<Integer, Queue>` 

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#1744]
Currently, for non-cached suppliers (e.g. queue size `123`), we return a new instance of `Supplier` every time.
We could replace it with 4 static functions:
```
static Function<Integer, Queue> SPSC_QUEUE_FACTORY = ...;
static Function<Integer, Queue> SPSC_LINKED_QUEUE_FACTORY = ...;
static Function<Integer, Queue> ONE_QUEUE_FACTORY = ...;
static Function<Integer, Queue> ZERO_QUEUE_FACTORY = ...;
```

where the the argument is the queue's size (ignored in `ONE` and `ZERO`)

**Comment by simonbasle** [comment]
closing this unless we can demonstrate a huge benefit in changing the public API

**Comment by bsideup** [comment]
it won't change the public API but is beneficial for non-standard queue sizes. Please keep it open since I still want to work on it.
