### ISSUE TITLE
Mono fromCompletionStage dons't resume and wrap a CompletionFuture exception

### ISSUE THREAD

**Issue by B-hamza** [reactor/reactor-core#1753]
Trying to use a completionFuture for a timeout rather than the Mono timeout by the duration

```
CompletableFuture<String> promise = asyncCall();
CompletableFuture<String> timeout = timeout(3, TimeUnit.SECONDS);
CompletableFuture<Object> first = CompletableFuture.anyOf(timeout, promise);

Mono.fromCompletionStage(first)
          .onErrorReturn(TimeoutException.class, default())
          .subscribe(System.out::println)

```
the timeout function :

```
private static <T> CompletableFuture<T> timeout(long delay,TimeUnit timeUnit) {
    CompletableFuture<T> result = new CompletableFuture<>();
    scheduler.schedule(() -> {
        result.completeExceptionally(new TimeoutException());
        return;
    }, delay, timeUnit);
    return result;
}
```

### Expected behavior
Resume when timeout and return default.

### Actual behavior
raise timeoutException at Runtime and stop the call.

### Reactor Core version
reactor-core 3.2.9.RELEASE

### JVM version (e.g. `java -version`)
java version "1.8.0_202"

**Comment by bsideup** [comment]
From `CompletableFuture#anyOf`'s JavaDoc:
> if it completed exceptionally, the returned CompletableFuture also does so, with a CompletionException holding this exception as its cause.

While you're using `.onErrorReturn(TimeoutException.class`,  looks like you're expecting a wrong exception type.

I'm closing this issue as "invalid", feel free to reopen if you still have issue after fixing your code.

Also, out of curiosity - why don't you use `.timeout` operator?
