### ISSUE TITLE
Fast Ordered Parallel Processing

### ISSUE THREAD

**Issue by swimmesberger** [reactor/reactor-core#1754]
### Expected behavior
Fast way to parallelize ordered CPU intensive workload in a slow and fast producer scenario with "realtime" data.

### Actual behavior
I have tested a couple of ways to accomplish this task but each way has it's drawbacks:
```java
flow.parallel(this.parallelism)
.runOn(this.scheduler)
.map(mapping)
.ordered(Comparator.comparing(INumberedData::getInputNumber));
```
This works kind of well but when we have phases where less data is arriving the data is "queued". If I understand the ordered merge algorithm* correctly it waits to fill all slots of the "parallelism" level. So if we have a level of 12 we need to have 12 produced values before the smallest value can be determined. In our case the data is strictly numbered 1, 2, 3, 4, 5... so the algorithm can assume that when the previous value was 4 and the smallest value is 5 it don't have to wait before all 12 slots are filled before emitting the 5th value. I understand that the current algorithm works with an comparator and therefore can't make such assumptions but it would be nice to have the option to say "I can guarantee that the 5th value is the next smallest value after 4 - do not wait".

For our usecase even ParallelFlux performance is "just acceptable" because it uses "schedule" of a Worker from a Scheduler for each item in the source flux which has some performance implications. My favorite way to do this would be with something like a WorkQueueProcessor with a RingBuffer - single producer (ordered flux) - multiple consumer (e.g. 12 - one for each CPU core) - processing data on the CPU - merging back the data in an ordered flux. Doing this in a backpressure friendly way would be a big plus e.g. slowing down the producer before putting data in the RingBuffer when the consumer (the CPU workers) are too slow. I haven't found a acceptable way to do this with reactor unfortunately.

```java
flow.compose(f -> {
   final WorkQueueProcessor<T> disruptor = WorkQueueProcessor.<T> builder()
   .executor(this.execService).build();
   final Flux[] parallelStreams = new Flux[this.parallelism];
   for (int i = 0; i < this.parallelism; i++) {
       UnicastProcessor processor = UnicastProcessor.create();
       disruptor.subscribe(processor);
       parallelStreams[i] = processor.map(mapping);
   }
   return Flux.mergeOrdered(Comparator.comparing(INumberedData::getInputNumber), parallelStreams)
   .doOnSubscribe(s -> {
        f.subscribe(disruptor);
   });
});
```
This is the WorkQueueProcessor variant I came up with which is the most performant but it faces the same issue when using Flux.mergeOrdered in slow producing phases.

Other ways to achieve the task of parallelizing had large performance implications - ideas are welcome. @akarnokd 

\* https://github.com/reactor/reactor-core/blob/628258f644bdddd095e72d1fc81c5d6ac0e3fa12/reactor-core/src/main/java/reactor/core/publisher/FluxMergeOrdered.java#L271

### Reactor Core version
3.2.6

### JVM version (e.g. `java -version`)
1.8.0_202

**Comment by akarnokd** [comment]
> So if we have a level of 12 we need to have 12 produced values before the smallest value can be determined.

Yes, that's the logic of merging in an ordered fashion. There is no way around it; you need the full row, otherwise it would be just non-deterministic merging of rails.

> but it would be nice to have the option

This requires a completely different collector strategy, one that understands the data it transmits. Unfortunately, I don't think you could emulate this via external means because you can't access the rail index in the parallel map so that you would queue up rails individually after returning to sequential mode.
