### ISSUE TITLE
Specific utility/API for optimized calls of mixed (computation vs. I/O) processing

### ISSUE THREAD

**Issue by mp911de** [reactor/reactor-core#1759]
Pluggable components in Spring Framework/Spring Data that invoke a chain of components for reactive APIs  typically require a `Publisher` and combination via `concatMap`/`flatMap`:

```java
interface MyCallback<T> {
    Mono<T> callback(T object);
}

MyCallback a = …;
MyCallback b = …;
MyCallback c = …;

a.concatMap(b::callback).concatMap(c::callback);
```

In most cases, these implementations use `Mono.just(object)` and in 20% of the cases, the returned publisher requires truly non-blocking/async processing.

This arrangement leads to a lot of object creations (`Mono.just(…)`, `Mono.fromSupplier(…)`) to satisfy API requirements.

Typical characteristics of these APIs are:

* Known number of callbacks/chain segments
* Multiplicity retention (`Mono<T>` must always emit an object, dropping the element is not permitted, `Mono<Void>` stays completion-only)

It would be great to have a utility that wraps that aspect, and that can be passed on to participating callbacks (somewhat similar to the `handle` operator) but in the sense that the utility would not require `Publisher` creation if not necessary and would accept `Publisher`s  where appropriate.

The using code could look like (pseudo-code):

```
HandlerResult<T> onBeforeSave(Handler<T> inbound, T entity, Document document, String collection){
  return inbound.continue(entity);
}

HandlerResult<T> onBeforeSave(Handler<T> inbound, T entity, Document document, String collection){
  Mono<T> remoteEncryptionService = …;
  return inbound.continue(remoteEncryptionService);
}
```

We have these use-cases in Spring Data [`EntityCallbacks`](https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/mapping/callback/ReactiveEntityCallbacks.java#L53) (see also [`ReactiveBeforeSaveCallback`](https://github.com/spring-projects/spring-data-mongodb/blob/master/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/core/mapping/event/ReactiveBeforeSaveCallback.java#L44) where multiple objects are picked up from the context and being called sequentially. Another example, in Spring Framework [Reactive transaction management](https://github.com/spring-projects/spring-framework/blob/master/spring-tx/src/main/java/org/springframework/transaction/reactive/TransactionSynchronizationUtils.java#L117) ([`AbstractReactiveTransactionManager`](https://github.com/spring-projects/spring-framework/blob/master/spring-tx/src/main/java/org/springframework/transaction/reactive/AbstractReactiveTransactionManager.java#L676)) to process registered transaction synchronizations or in internal methods to cater for the lazy `Publisher` nature. 

Ideally, the outcome of this ticket is to start a discussion and identify whether this case is worth pursuing and how support could look like.

What the proposal effectively does is moving the decision `map` vs. `flatMap` into the implementation being called.

**Comment by simonbasle** [comment]
I think that is something that needs to live along  `Callback`'s implementation.

The `Handler` would have 2 implementations:
 - imperative one that composes `Function` and only switch to reactive one when adding `Mono`, switching the combined functions to a `concatMap(o -> Mono.fromCallable(combinedFunction.apply(o))`
 - reactive one that composes `Mono` with `concatMap` switching to imperative one when adding a `Function`, switching back to combination by composition

In any case I don't think that is something we can easily provide a generic version in Reactor itself...
