### ISSUE TITLE
Flux loses elements sometimes

### ISSUE THREAD

**Issue by kamax70** [reactor/reactor-core#1771]
### Expected behavior
If Flux publishes n elements, I expect to consume n elements after flatMap and publishOn operations.

### Actual behavior
Sometimes I lose elements. I don't understand what it depends on.

### Steps to reproduce
Simple test:

```
        List info;
        Scheduler scheduler = Schedulers.elastic();
        long count = 0;
        do {
            info = Flux.range(0, 37)
                    .flatMap(t -> Mono.just("")
                            .publishOn(scheduler)
                            .flatMap(Mono::just)
                    )
                    .collectList()
                    .block();
        } while (info.size() == 37 && ++count < 1000);
        assertEquals(info.size(), 37);
```
At some iteration info.size() can return less than 37.

But for example this code always works fine:

```
        List info;
        Scheduler scheduler = Schedulers.elastic();
        long count = 0;
        do {
            info = Flux.range(0, 37)
                    .flatMap(t -> Mono.just("")
                            .publishOn(scheduler)
                            .flatMap(Mono::just)
                            .doOnSuccess(v -> {})
                    )
                    .collectList()
                    .block();
        } while (info.size() == 37 && ++count < 1000);
        assertEquals(info.size(), 37);
```

### Reactor Core version
3.2.9.RELEASE

### JVM version (e.g. `java -version`)
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

**Comment by bsideup** [comment]
Hi @kamax70,

I tried running your code but it does not fail for me. Is it always reproducible on your machine?

**Comment by kamax70** [comment]
> Hi @kamax70,
> 
> I tried running your code but it does not fail for me. Is it always reproducible on your machine?

Yes, this test stable fails in 3.2.9.RELEASE (or reactor-netty 0.8.8.RELEASE)

**Comment by kamax70** [comment]
[
![flux](https://user-images.githubusercontent.com/13140210/60095045-5628b200-9756-11e9-8944-000e42329032.png)
](url)

**Comment by bsideup** [comment]
@kamax70 ok, I accidentally used "3.2.10" instead of "3.2.9". I confirm that it fails on "3.2.9", but works on "3.2.10".

Could you please try upgrading Reactor's version?

**Comment by kamax70** [comment]
> @kamax70 ok, I accidentally used "3.2.10" instead of "3.2.9". I confirm that it fails on "3.2.9", but works on "3.2.10".
> 
> Could you please try upgrading Reactor's version?

Yes. I confirm that it works on 3.2.10 (and reactor-netty 0.8.9).

**Comment by bsideup** [comment]
@kamax70 ok, thanks for confirming! 👍 
I'm closing this issue, feel free to report more findings as new ones, or reopen this one if it is not fixed completely for you :)
