### ISSUE TITLE
Move Kotlin to a separate module and include it into the final jar

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#1772]
After we decided to not drop Kotlin in 3.3 (see #1658), we agreed that Kotlin should be at least a separate module included into the final JAR, since Kotlin causes some maintenance problems that affect non-Kotlin development, like:

1. Kotlin Gradle plugin depends on the JAR produced by Java, and forces JAR compilation every time you want to run the tests (when you delegate to Gradle in IDEA, default mode in 2019)
2. After major refactorings, Kotlin fails to resolve some types (like `AssemblyOp`). Full rebuild helps, but consumers a lot of time
3. Build file with Kotlin becomes much bigger and makes it harder to navigate

**Comment by simonbasle** [comment]
Irrelevant now as Kotlin extensions are being phased outside of the repository.
