### ISSUE TITLE
Explore deprecating onEachOperator

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1773]
OnEachOperator is a difficult to use hook and very specific to logging/tracing. We should give if required a dedicated API and/or move toward bytecode (external) AOP via reactor-tools.

**Comment by martin-tarjanyi** [comment]
On our project we currently use doOnEach operator to easily access the Reactor Context. As the alternative `flatMap(x -> Mono.subscriberContext().doOnNext(ctx -> ...).thenReturn(x))` is quite cumbersome to use if we just want to log something for example.

Did you consider adding other utility methods to access the context something like 
`doWithContext(ctx -> ...)` or `doOnContext(ctx -> ...)` or `doOnNextWithContext((item, ctx) -> ...)`?

Sorry if this is not the right place to ask this question. Let me know if I should open a separate issue for this.

**Comment by bsideup** [comment]
@martin-tarjanyi `doOnEach` has nothing to do with `onEachOperator` (from Hooks)

**Comment by bsideup** [comment]
Since there is at least 1 project that has to use `onEachOperator` (Sleuth), I don't think we can include it in M3 without providing an alternative
