### ISSUE TITLE
Is it possible to achieve conflation based on predicate?

### ISSUE THREAD

**Issue by moonrumble** [reactor/reactor-core#1774]
I want to conflate values based on key while flux is notifying subscribers. Is it possible using existing operator?

[Conflation](https://dzone.com/articles/when-disruptor-not-good-fitl)

**Comment by simonbasle** [comment]
Note the link is a 404, so I'm not sure what you exactly mean by _conflation_.

It seems to me that you have a "hot" source that emits its values independently of its subscriber(s) having made a `request` for it. The usual strategy for dealing with such a source would be to buffer values incoming too fast (or at least part of it) using `onBackpressureBuffer()` or `onBackpressureBuffer(int)`.

But if you are only interested in the last occurrence of each value that matches your filter, you could probably do `onBackpressureLatest()` instead.

This is all of course supposing you're actually driving each subscriber's `request`.

A good alternative where there is less need to keep the `request` under control is the `sample()` family of operators.

**Comment by moonrumble** [comment]
@simonbasle Thanks for reply. Link is up but for some reason it is not showing up.

Here is explanation. 

Lets take the scenario where a single publisher is generating stock prices for a single stock at a rate of 1000 prices per second.  There are three subsribers in the process.  If one of the subscribers blocks for 1 second, then 1000 events will backup in the RIngBuffer.  Subscribers that are not keeping up with the publisher will cause the Java VM to work harder on minor garbage collections as newly created events live longer in the ringbuffer.  In a more terminal scenario, say you size your ringbuffer at 1,000,000 events, if one subscriber blocks for more than 1000 seconds, then the publisher will have to block as well, as the ringbuffer becomes full, affecting the two fast subscribers that were keeping up.  The impact on garbage collection will be even heavier, causing latency jitter.

**Comment by simonbasle** [comment]
Yes, I think `sample` or `onBackpressureLatest()` could help here. Also the fact that subscribers in the reactive world do not block, especially during filtering or mapping operations. It is all architectured around this idea, so of course things would turn bad if you put in a `Thread.sleep` in your subscriber.
