### ISSUE TITLE
Deprecate Mono#doOnRequest

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1791]
`Mono#doOnRequest` does not bring any value given how many mono operators just prefetch using `Long.MAX_VALUE`

**Comment by simonbasle** [comment]
Is there a common misuse that I'm missing? Can we **really** decide that nobody ever has a valid usecase for this operator? What are we trying to achieve exactly?

`PublisherProbe` relies on `Mono#doOnRequest` to track the request and provide assertions like `wasRequested`, so we'd already be breaking one of our own test functionalities...

👎

**Comment by simonbasle** [comment]
Closing this as we're one business day away from the milestone. Unless a far better case can be made for it (eg. it regularly does the wrong thing), I don't think we'll reopen this discussion.
