### ISSUE TITLE
Context.of() not checking for duplicate keys

### ISSUE THREAD

**Issue by srnagar** [reactor/reactor-core#1793]
### Expected behavior
Creating an instance of `Context`  using `Context.of()` method should check for duplicate keys.

### Actual behavior
`Context.of()` currently allows duplicate keys and when an update to the key is made, only the 1st entry matching the key is updated. When the context is read, the last argument matching the key in `Context.of()` is returned as the value for the key.

For e.g. 
```
Context context = Context.of(key, "value1", key, "value2"); 
context.put(key, "value3");
```
This will result in `key` returning `value2` instead of `value3` which was the last updated value.

### Steps to reproduce
```
import java.util.List;
import java.util.Map.Entry;
import java.util.stream.Collectors;
import reactor.core.publisher.Mono;
import reactor.util.context.Context;

public class TestReactorContext {
    public static void main(String[] args) {
        TestReactorContext test = new TestReactorContext();
        String key = "name";

        // Same key with multiple values. Last updated value is "Baz"
        Context context = Context.of(key, "John", key, "Doe");
        context = context.put(key, "Foo");
        context = context.put(key, "Bar");
        context = context.put(key, "Baz");

        String result = test
            .greet("Hello, ")
            .subscriberContext(context)
            .block();

        // Expected: "Hello, my name is Baz."
        // Actual: "Hello, my name is Doe."
        System.out.println(result);
    }

    Mono<String> greet(String prefix) {
        // convert subscriberContext coming into this method into a string
        return Mono.subscriberContext()
            .map(this::getMessage)
            .flatMap(message -> prettyPrint(prefix, message));
    }

    private Mono<String> prettyPrint(String prefix, String context) {
        String msg = prefix + context;
        return Mono.just(msg);
    }

    private String getMessage(Context context) {
        List<Entry<Object, Object>> entries = context.stream().collect(Collectors.toList());
        System.out.println("Reactor context size = " + entries.size()); // size is 1
        StringBuilder contextBuilder = new StringBuilder();
        entries.stream().forEach(
            entry -> contextBuilder.append("my ").append(entry.getKey()).append(" is ").append(entry.getValue()).append("."));
        return contextBuilder.toString();
    }
}

```
### Reactor Core version
3.2.3.RELEASE

### JVM version (e.g. `java -version`)
JDK 8

**Comment by simonbasle** [comment]
there is indeed an issue there. the `Context` implementations of size < 6 will keep both entries, but only the `stream()` method will expose the duplicate(s), while `get(duplicateKey)` will happily return the first matching value.

At the expense of making the `Context.of(...)` methods less efficient, we can check for duplicate keys there.

Question is, what to do in case of a duplicate? Should we:
 - throw an `IllegalArgumentException` (the easiest)?
 - attempt to fall back on creating a smaller `Context` with the _first_ of the duplicate values?
 - attempt to fall back on creating a smaller `Context` with the _second_ of the duplicate values?

**Comment by simonbasle** [comment]
Solution (1) above is implemented is https://github.com/reactor/reactor-core/pull/1794/commits/d319edfe43ee968c86ce7c3e41142401804a2e23

**Comment by simonbasle** [comment]
Alternate solution 4.: Offer `of(Map)` that chooses the right implementation. `of` assumes deduplicated keys, and since you're most probably providing these statically, it should be possible to ensure no two keys are the same in the explicit version....

**Comment by srnagar** [comment]
Thank you for the quick fix! Could you please let me know when this release will be available on maven central?

**Comment by simonbasle** [comment]
3.2.11 should be released next week, if everything goes as planned 🤞
