### ISSUE TITLE
Multi-function mappers

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#1805]
It is a common pattern to have multiple mappers one after another:
```java
users.map(User::getSocial).map(SocialProfile::getFriends).map(List::size);
```

Java method references make it especially attractive, and people tend to use multiple maps instead of a lambda:
```java
users.map(it -> it.getSocial().getFriends().size())
```

One way of dealing with it is described in #1556 but requires some changes to the operators.

But, for this simple case, we may consider adding short-cutting `map` overloads:
```java
users.map(User::getSocial, SocialProfile::getFriends, List::size)
```

that will internally use `andThen`:
```java
	public final <V1, V2, V3> Flux<V3> map(
			Function<? super T, ? extends V1> mapper1,
			Function<? super V1, ? extends V2> mapper2,
			Function<? super V2, ? extends V3> mapper3
	) {
		return map(mapper1.andThen(mapper2).andThen(mapper3));
	}
```
(with variants for 2, 3, 4, 5 parameters)

This will eliminate the operator while not affecting the expectations (e.g. the debugging mode)

**Comment by bsideup** [comment]
Note however that it does not eliminate the need for macro fusion:
```java
Mono<User> getUser() {
    return fetchUser().map(UserResponse::getObject);
}

getUser().map(User::getName);
```

**Comment by simonbasle** [comment]
thinking again about it, simple-case macro fusion of multiple subsequent invocations of same operator would be a better solution
