### ISSUE TITLE
Revisit metrics' names

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#1807]
Due to the use of unit names, some metrics have weird names like `reactor_requested_requested_amount`.

We should review the current unit names and ensure that they have proper names after flattened by Prometheus and other exporters

**Comment by ericbottard** [comment]
I wonder if we shouldn't drop these (mis?)uses of baseUnits entirely (instead of trying to find a better one).
For anything that counts instances of "stuff", there is no particular unit (in the physical sense).

This is true for 
```java
		Counter.builder(METER_SUBSCRIBED)
		       .tags(commonTags)
		       .baseUnit("subscribers")
		       .description("Counts how many Reactor sequences have been subscribed to")
```
as well IMO.

The parameter is `@Nullable`, so I assume this is ok.

**Comment by simonbasle** [comment]
Agreed, let's remove the two `baseUnit` uses that we have in Reactor since they don't bring any precision.
