### ISSUE TITLE
Behavior of requestN in FluxTake

### ISSUE THREAD

**Issue by zzhao0** [reactor/reactor-core#1818]
In FluxTake, requestN may request for more stream elements than n, where n is the parameter used to call flux.take(n).

https://github.com/reactor/reactor-core/blob/628258f644bdddd095e72d1fc81c5d6ac0e3fa12/reactor-core/src/main/java/reactor/core/publisher/FluxTake.java#L151

FluxTake is defined to return n elements at maximum, so it appears to me wasteful to request beyond n items. I was also wondering if request(n) should rather be made directly when subscribing (similar to how FluxSkip does), and with further request(n) ignored.

**Comment by smaldini** [comment]
This has been raised previously: the reason behind this choice is that `Long.MAX` triggers fast paths in data sources (unbounded/push mode). Cancel will then take care of preventing further producing.
Have a look at `limitRequest` for something more aligned with your expectations.

**Comment by zzhao0** [comment]
Thanks @smaldini for the details. Is there a place I can find more information regarding unbounded/push mode?
