### ISSUE TITLE
reactor.core.publisher.Traces to catch specific exception and errors

### ISSUE THREAD

**Issue by suztomo** [reactor/reactor-core#1830]
`reactor.core.publisher.Traces` class has code to catch `Throwable`. However, It's good practice to specify more explicit errors and exceptions.

```
try {
        Class<?> clazz = Class.forName(className);
        @SuppressWarnings("unchecked")
        Supplier<Supplier<String>> function = (Supplier) clazz.getDeclaredConstructor()
                                                              .newInstance();
        return Stream.of(function);
}
catch (Throwable e) {
        return Stream.empty();
}
```

## Motivation

it's good practice to specify exceptions and errors that may occur in try clause rather than `Throwable`. https://stackoverflow.com/a/6083271/975074

## Desired solution

Catching more specific exceptions and errors is desirable:

```
try {
        Class<?> clazz = Class.forName(className);
        @SuppressWarnings("unchecked")
        Supplier<Supplier<String>> function = (Supplier) clazz.getDeclaredConstructor()
                                                              .newInstance();
        return Stream.of(function);
}
catch (ClassNotFoundException|NoSuchMethodException|LinkageError e) {
        return Stream.empty();
}
```

## Considered alternatives

None

## Additional context

Our static analysis tool "Linkage Checker" detected reactor.core.publisher.Traces not properly catching LinkageError.

https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/816

**Comment by simonbasle** [comment]
So the goal is that the catch clause explicitly bears the `LinkageError`, so the attempt at detecting the Java 9 environment isn't picked up by your Linkage Checker?

Since this is very specifically calling 3 well-known constructors that don't have particular thrown exceptions, it should not be an issue.

Just in case, would a catch-all after the specific catch throw off your checker?

**Comment by suztomo** [comment]
> So the goal is that the catch clause explicitly bears the LinkageError
Yes, it's more easier to reason by human as well as tools (including Linkage Checker).

> would a catch-all after the specific catch throw off your checker?
No, it would not throw off the checker as long as `LinkageError` is explicitly caught.
