### ISSUE TITLE
Add groupBy with map factory

### ISSUE THREAD

**Issue by TuomasKiviaho** [reactor/reactor-core#1834]
HashMap is used currently internally to as groupMap. Would it be possible to have similar possibility as Collectors.groupBy has where one can supply the map implementation to be used. I'd personally just like just to preserve the order by using ConcurrentLinkedHashMap and I see that switching to it by default might not be the ideal solution.

**Comment by simonbasle** [comment]
@TuomasKiviaho do you have a confirmed issue with the internal map being a `HashMap`? The map is never actually passed down to the user, and the groups are emitted as soon as an element that causes a new group to open is received, so ordering of the `HashMap` doesn't affect the `Flux<GroupedFlux>` order...

**Comment by simonbasle** [comment]
please re-open if you have additional arguments to provide
