### ISSUE TITLE
Is it possible to revisit a stage in pipe in a loop ? 

### ISSUE THREAD

**Issue by DareUrDream** [reactor/reactor-core#1839]
In the below definition what we would like to do is to go back to `.bufferUntil(record -> isGroupComplete(record))` until a certain condition is met ? And also is it possible to get the list of existing records as well while going back in the loop to check all the records to determine that a specific condition is met ??

And outside of this question, how do we in general handle looping kind of situations in data flow definitions ?

```
ds.getPublisher()
        .onBackpressureBuffer(15000)
        .onBackpressureDrop(record -> LOGGER.error("Backpressure applied-1. Dropped records: {}", record))
        .groupBy(record -> record.getGroupId())
        .flatMap(group -> group
                .timeout(Duration.ofSeconds(60))
                .bufferUntil(record -> isGroupComplete(record))
                .bufferTimeout(100, Duration.ofSeconds(5))
                .GO BACK TO --> bufferUntil with existing list of records in the grouped flux
                .map(listOflistOfRecords -> listOflistOfRecords.stream().flatMap(List::stream).collect(Collectors.toList()))
                .onErrorContinue((th, records) -> {
                    LOGGER.error("Timedout records: {}", records);
                                            // TAKE ACTION ON THE RECORDS
                }))
        .filter(records -> {
            return (publishController.shouldIPublish()) ? true 
                    : records.get(0).getCreatedTimestamp() <= (publishController.stopRequestTimestamp() - 5);
        })
        .doOnDiscard(List.class, records -> {
            if(! records.isEmpty()) {
                LOGGER.error("Discarded: {}", records);
                discardedRecords.put(records, new Object());
            } else {
                LOGGER.error("Empty record received. This should never happen.");
            }
        })
        .map(record -> Collections.unmodifiableList(Enricher.enrich(record)))
        .map(dbRecords -> RecordTransformer.transform(dbRecords))
        .retryBackoff(MAX_RETRY, Duration.ofSeconds(FIRST_BACKOFF_IN_SECONDS), Duration.ofSeconds(MAX_BACKOFF_IN_SECONDS))
        .publishOn(Schedulers.single());
```

**Comment by simonbasle** [comment]
You'd need to define "looping kind of situations"... There is no loop in Reactive Streams, only the inbound stream of data.

 Operators don't share state, so you cannot "go back to bufferUntil with existing list of records". Note however that cancelling a `GroupedFlux` will cause `groupBy` to open a second group if the same grouping key pops up again, maybe that helps?

**Comment by DareUrDream** [comment]
Interesting I will evaluate that. 

Is there a possibility of having a context that gets created when a group is formed and then destroyed when the group is consumed. Or is there a way I can manually put in in map kind of data-structure at the beginning of data flow and then consume it various stages. These might help me built a work-around.

In-fact in Reactor how do we handle situations when we want to build data flow definitions where the downstream depend on a markers that have been set at the start of the data flow based on some conditions. Do we have an example if this is possible ?

**Comment by gindex** [comment]
We had to some degree a similar case having multiple transformation, but in particular scenarios we needed the initial state again. We leveraged `Tuples` in our workaround: 
```		
Flux.just(1,2,3)
    .map(request -> Tuples.of(request, request.toString()))
    .map(tuple -> tuple.mapT2(value -> value + " unit"))
    .doOnNext(tuple -> {throw new RuntimeException("");})
    .onErrorContinue((th, obj) -> {
			Integer request = ((Tuple2<Integer, String>) obj).getT1();
			System.out.println("Initial request " + request);
     })
    .subscribe(result -> System.out.println(result.getT2()));
```
@DareUrDream maybe that helps. 

@simonbasle what do you think about having something like `BiFlux<U,T>` with `bimap(first -> transform, second -> transform)` and `map1`, `map2`? It would make some cases easier.

**Comment by simonbasle** [comment]
@DareUrDream the `Context` (with the `subscriberContext(Function)` operator) can be injected with a mutable data structure like a `List`. `Context` is an advanced feature, with a few caveats (ie. it is only visible to operators that appear above it in the code, not below it, so it must be set up "as late as possible" for the whole chain to be able to access it).

Note also that operators like `flatMap`, which involve an inner sequence, will generally give said inner sequences their own `Context`, initially a copy of the main one. So you can find the same values in it, but if you chain in `.subscriberContext(Function)` inside the `flatMap`'s lambda, that context write will only be visible in the scope of the lambda-created inner sequence.

Have a look at the [documentation]() if you haven't already.

About `groupBy` and cancellation, it would only cancel the current `GroupedFlux` and the subsequent matching values would trigger the opening of a new `GroupedFlux`, they wouldn't be dropped.

@gindex `BiFlux` we don't plan to add any new reactive type at this point, this would add a lot of surface both from a maintainability standpoint and a usability standpoint. Not sure I understood what you intended with `bimap` and `map1`/`map2` though...

**Comment by gindex** [comment]
Thats true. In general, it would add syntactic sugar simplifying to work around tuples in flux/mono. `Flux<Tulpe<S,U>>` would became `BiFlux<S,U>`. In the example above `map(tuple -> tuple.mapT2(value -> value + " unit"))` would become `map2(value -> value + " unit"))`. But I see you point.
