### ISSUE TITLE
Buffer/Window Until Changed

### ISSUE THREAD

**Issue by UgiR** [reactor/reactor-core#1840]
WindowUntilChanged/BufferUntilChanged

## Motivation
To window a flux where the boundary trigger depends on the element that arrived last.

DistinctUntilChanged already exists where it filters elements, but it would be useful to split a flux based on this same concept.

## Desired solution

Original Flux:

A - A - B - B - B - C - B - B - D - D - E - E - E - E

Using WindowUntilChanged operator where the key is the letter in the element:

(A, A) - (B, B, B) - (C) - (B, B) - (D, D) - (E, E, E, E)

## Considered alternatives
Using WindowWhile with a Predicate that keeps track of the last-seen element can work but a native solution would be great.

This would also help in cases where GroupBy is not appropriate due to high number of groups.

**Comment by UgiR** [comment]
I just saw this has been suggested previously: #1706

**Comment by simonbasle** [comment]
Duplicate of #1706
