### ISSUE TITLE
Flux bufferTimeout Add Predicate

### ISSUE THREAD

**Issue by belugabehr** [reactor/reactor-core#1843]
Currently, the only predicate that is accepted for Flux.bufferTimeout is a maximum size.

>Collect incoming values into multiple List buffers that will be emitted by the returned Flux each time the buffer reaches a maximum size OR the maxTime Duration elapses.

Please add the ability to add a predicate, just like in Flux.bufferUntil.

>Collect incoming values into multiple List buffers that will be emitted by the returned Flux each time the buffer reaches a maximum size OR the maxTime Duration elapses OR the given predicate returns true.

## Motivation

I have a system the produces messages of various priorities.  If the priority of the messages are low, then buffering is acceptable.  However, if a message comes in with a high priority, I seek to flush all of the low priority messages then immediately send the high priority.

## Desired solution

flux.bufferTimeout(100, Duration.ofMillis(500L), msg -> msg.isHighPriority())

**Comment by simonbasle** [comment]
`help wanted` if somebody wants to try their hands at this, but keep in mind timed out buffers add quite a lot of complexity to the implementation, and to the management of backpressure: the timeout ticks release the buffers no matter what the request currently is, potentially leading to an `OverflowException` (see `Operators#failWithOverflow` and Exceptions#isOverflow`).

**Comment by gindex** [comment]
I would like to try if you don't mind

**Comment by simonbasle** [comment]
sure @gindex please do !

**Comment by simonbasle** [comment]
there is indeed a lot of `buffer*` variants, not sure this will be easy to cover, and whether or not we actually want to cover these cases. buffer/window codebase has already grown quite large and hard to maintain, and the API is also a bit overwhelming already :(

**Comment by simonbasle** [comment]
closing this. the work was started but proved too large in scope, and we don't want to grow the number of `buffer` variants right now.
