### ISSUE TITLE
Capture generic type of Publisher in `Flux.zip(Iterable, Function)`

### ISSUE THREAD

**Issue by berry120** [reactor/reactor-core#1851]
At present, one variation of the `zip()` method on `Flux` has the following signature:

    static <O> Flux<O> zip(Iterable<? extends Publisher<?>> sources, Function<? super Object[],? extends O> combinator)

The generic type of `Publisher` is not captured, so can't be used.

## Motivation
Assuming some `Iterable` of `Publisher`, eg:

    List<Mono<String>> list = new ArrayList<>();
    l.add(Mono.just("foo"));
    l.add(Mono.just("bar"));

...we can't currently do something akin to:

    Flux.zip(list, o -> Arrays.stream(o).collect(Collectors.joining(" ")))

...as the type of the `Publisher` isn't captured. Instead, we have to do something like:

    Flux.zip(l, o -> Arrays.stream(o).map(s -> (String)s).collect(Collectors.joining(" ")))

...which is messy and (more importantly) not type safe.

## Desired solution
Change the signature of the relevant `zip()` method to:

    static <I, O> Flux<O> zip(Iterable<? extends Publisher<? extends I>> sources, Function<? super I[], ? extends O> combinator)

## Considered alternatives
 - Casting (as above)
 - Defining a separate method on `Flux` and deprecating the old one if compatibility is a concern
 - In some cases where the combinator is incremental, calling `zip(Publisher, Publisher, BiFunction)` in a loop may provide a type-safe solution
 - Less backwards compatible - but the first generic argument to the combinator could be `? super Iterable<I>` instead of `? super Object[]` to remove arrays from the equation entirely.

## Additional context
There's a second such `zip()` method which takes an explicit `prefetch` parameter that would obviously need to be changed too.

I notice that `FluxZip` also uses a `Function<? super Object[], ? extends R>` as the type for its zipper internally, and changing this to `Function<? super I[], ? extends R>` isn't trivially possible as it would rely on generic array creation, which is a bit of a hack in Java. Would changing the zipper type to `Function<? super Iterable<I>, ? extends R>` and using lists in place of arrays be feasible, or too much of a change?

**Comment by akarnokd** [comment]
`T[]` doesn't work in Java as you can't create generic arrays. So what remains is `Object[]` as the most contravariant type. Also it would cause `ClassCastException` due to auto-casting in the generic function. For example, if `T = Integer`, `((T[])objArr)` would do nothing inside the zip but with `Function<Integer[], R>`, you'd get a `(Integer[])objArr` generated by the compiler and fail with CCE.

**Comment by berry120** [comment]
You can't *create* generic arrays, but you can reference them. I understand that the current internal implementation creates arrays internally based on the generic type, but that doesn't absolutely *have* to be the case?

In any case, is there a good reason why an array has to be used here? An `Iterable` or similar would sidestep the array issue entirely.

**Comment by akarnokd** [comment]
You could try and play tricks with generics via reflection, but that works only for one level as there is no `List<Option<Integer>>.class`.

Providing `Object[]` array uses the least allocation and provides simple independence/quasi immutability of rows when calling the function (i.e., not sharing the same backing structure like certain `Map` implementations do with `Map.Entry` for example). Anything more requires another layer (like an `Accessor<T>` with `get(int)` and `size()`) and state (`Iterator<T>` current position) or even two layers (`Iterable`/`Iterator`). With the current API, you can add such convenience wrappers yourself if needed wereas you couldn't undo the wrapping if the library did it for you all the time.

**Comment by simonbasle** [comment]
as @akarnokd pointed out:

> With the current API, you can add such convenience wrappers yourself if needed wereas you couldn't undo the wrapping if the library did it for you all the time.

closing this issue for now
