### ISSUE TITLE
Add a doOnEmpty side effect to both Flux and Mono

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#1855]
## Motivation
A side effect that doesn't change the main sequence but allows to detect the empty case, like `switchIfEmpty`, could be useful.

Moreover, this would fix the limitation of #1854 (if implemented).

`need-design`: naming could also be `doIfEmpty` but that is a departure from _most_ do* operators (especially the ones around onNext|onError|onComplete signals).

Relates to #1854

**Comment by bsideup** [comment]
We should be **very** careful with this one, because (as seen in the community chats/SO) people tend to use the side effects for IO (e.g. `doOnNext`), and `doOnEmpty` may become a really popular misuse.

**Comment by simonbasle** [comment]
we'll keep `doOnSuccess` in #1855 and thus will close this one for now
