### ISSUE TITLE
Provide way to detect/debug stateful callbacks

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#1857]
We should consider offering a debug option (via reactor-tools) to detect use of stateful callbacks e.g.:
```java
class MyFunction implements Function<Integer, Integer> {
   int property1 = 10;  //state

   Integer apply(Integer p2) {
      return property1 + p2;
   }
}

//...

return flux.map(newMyFunction());
```

Whenever we use a concrete class (vs a lambda), static analysis should reveal if properties are used and we could warn to use `Flux.defer/Mono.defer`

**Comment by bsideup** [comment]
This requires pretty complex analysis, and not just static, but dynamic.

We could do a simple "pureness" check (by calling the same function multiple times and checking that the result is the same) but that does not always detect it plus breaks if the function is pure but always return some new value (think `return new MyObject()` where `MyObject` does not implement `equals` / `hashCode`)
