### ISSUE TITLE
FluxReplay source is never canceled with Hooks.onEachOperator()

### ISSUE THREAD

**Issue by robotmrv** [reactor/reactor-core#1860]
FluxReplay `source` is not canceled if all subscribers are disconnected and `Hooks.onEachOperator()` is applied 

## Expected Behavior
`source` should be cancelled after first signal 

## Actual Behavior
`source` never shows cancellation and continues emit data signals

## Steps to Reproduce
```java
Hooks.onEachOperator(Operators.lift((scannable, coreSubscriber) -> coreSubscriber));
Flux.interval(Duration.ZERO, Duration.ofMillis(300))
        .log("source")
        .replay(Duration.ofMillis(500))
        .refCount()
        .log("connected")
        .take(1)
        .subscribe();
Thread.sleep(1000);
```

## Possible Solution
It seems that there is a typo in reactor.core.publisher.ConnectableLiftFuseable#connect
```java 
@Override
public void connect(Consumer<? super Disposable> cancelSupport) {
	this.source.connect();//<--- does not pass cancelSupport
}
```
if I change it to `this.source.connect(cancelSupport);` 
or remove `Hooks.onEachOperator` 
all work as expected 

## Your Environment
* Reactor version(s) used: 3.2.10.RELEASE
* JVM version (`javar -version`): 
openjdk version "1.8.0_191-1-ojdkbuild"
OpenJDK Runtime Environment (build 1.8.0_191-1-ojdkbuild-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
* OS and version: Windows 10

**Comment by simonbasle** [comment]
Thanks for reporting this, indeed this should pass the `cancelSupport` !

**Comment by robotmrv** [comment]
@simonbasle  I've found that fix was made only for `ConnectableLift` but `ConnectableLiftFuseable#connect` still does not pass `cancelSupport`

**Comment by simonbasle** [comment]
Reopening and assigning to new milestone 3.2.15.RELEASE.

`ConnectableLift` was fixed in [`3.2.12.RELEASE`](https://github.com/reactor/reactor-core/milestone/64)

**Comment by simonbasle** [comment]
@robotmrv do you want to tackle it?

**Comment by robotmrv** [comment]
sure, if it is not urgent (can wait till weekend) I can
