### ISSUE TITLE
Better document that, unless specified, interval initial delay is same as period

### ISSUE THREAD

**Issue by timsazon** [reactor/reactor-core#1866]
I think it should be 0 if rely on docs for the method:

`Flux<Long> interval(Duration period)`
Create a Flux that emits long values starting with 0 and incrementing at specified time intervals on the global timer.

`Flux<Long> interval(Duration delay, Duration period)`
Create a Flux that emits long values starting with 0 and incrementing at specified time intervals, **after an initial delay**, on the global timer.

## Motivation
Make interval behavior more consistent.

## Desired solution
Change `period.toMillis()` to 0 in `Flux<Long> interval(Duration period, Scheduler timer)` method:
```
public static Flux<Long> interval(Duration period, Scheduler timer) {
	return onAssembly(new FluxInterval(0, period.toMillis(), TimeUnit.MILLISECONDS, timer));
}
```

## Considered alternatives
Add notes about default initial delay in docs

**Comment by simonbasle** [comment]
I'd prefer improving the javadoc than changing the behavior. The marble diagram is already pretty explicit about the initial delay defaulting to the "period".

**Comment by simonbasle** [comment]
@timsazon would you like to tackle this in a PR? (it would need to be branched against `3.2.x`)

**Comment by timsazon** [comment]
> I'd prefer improving the javadoc than changing the behavior. The marble diagram is already pretty explicit about the initial delay defaulting to the "period".

My bad, didn't see the image.
