### ISSUE TITLE
Classloader leak with Throwable in static fields

### ISSUE THREAD

**Issue by fsgonz** [reactor/reactor-core#1872]
In dynamic classloader environments, the use of Throwable in static fields may cause a classloader leak in the backtrace field. This field is set in runtime at native code with an array that are instances of Class. This may cause a Classloader which should be disposed to be retained.

In other [projects](https://github.com/eclipse/jetty.project/issues/868), an error without a writable stacktrace was used for this cases. 

I've opened a PR for this:
https://github.com/reactor/reactor-core/pull/1871

Let me know.

Thanks!

**Comment by simonbasle** [comment]
reference of a similar issue in the JDK: https://bugs.openjdk.java.net/browse/JDK-8146961

**Comment by simonbasle** [comment]
Thanks for reporting this! IntelliJ Structural Search reveals a total of 4 static fields that have a type that extends `Throwable`:
 - [x] `Throwable Exceptions.TERMINATED` (covered in your PR)
 - [ ] `RejectedExecutionException Exceptions.REJECTED_EXECUTION`
 - [ ] `RejectedExecutionException Exceptions.NOT_TIME_CAPABLE_REJECTED_EXECUTION`
 - [x] `AlertException.INSTANCE` (already avoiding stacktrace filling)
