### ISSUE TITLE
Stackoverflow question: last element not emitted

### ISSUE THREAD

**Issue by DareUrDream** [reactor/reactor-core#1873]
Below is my data flow definition. Can some point out the what I am missing here ? I am observing that the last JsonElement is not returned from `flatMapIterable`. Say if the jsonArray have 5 elements, I am only receiving 4 elements to my groupBy operator

```
		Flux<List<JsonObject>> dataFlow = Flux.empty()
			.mergeWith(dataFlow1)
			.publishOn(Schedulers.newSingle("data-in", true))
			.filter(this::recordsPresent)
			.map(dataToPublishOrError -> dataToPublishOrError.getUnchecked())
			.publishOn(Schedulers.newElastic("group-processing", 20, true))
			.groupBy(dataToPublish -> dataToPublish.getId().orElse(""), 512)
			.flatMap(outerGroup -> outerGroup
					.timeout(MAX_DUARTION_IN_HOURS)
					.flatMapIterable(dataToPublish -> dataToPublish.getRecords().getOrDefault(ActivityType.AAR, new JsonArray(0)))
					.cast(JsonObject.class)
					.groupBy(data -> data.get("primaryId").getAsString(), 512)
					.flatMap(innerGroup -> innerGroup
							.bufferUntil(records -> isInnerGroupComplete(records, Optional.of(outerGroup.key())))
							.map(this::transformedJsons)
							.takeUntil(x -> true), 512, 512)
					.takeUntil(x -> true), 512, 512)
			.publishOn(Schedulers.newElastic("aar-out", 20, true));
```

**Comment by simonbasle** [comment]
_questions_ are best asked on stackoverflow, with the [project-reactor] tag. Unless you strongly suspect there is a bug, have started debugging and saw something fishy or encounter behavior that differs that contradicts the documentation, github issues are not the preferred place to ask questions.

**Comment by simonbasle** [comment]
(have you verified the `JsonArray` has 5 entries that all have the required `primaryId`? have you tried simplifying the `flatMap(innerGroup` and/or `log()`ging of what's in there? `flatMapIterable` is pretty simple, if the array has 5 elements it should emit 5 elements)

**Comment by DareUrDream** [comment]
@simonbasle I am not sure what the RCA is but once I removed the `flatMap` from `outerGroup` it started working.
