### ISSUE TITLE
onLastAssembly() could be invoked more than once per subscribe()/block()

### ISSUE THREAD

**Issue by robotmrv** [reactor/reactor-core#1883]
I've noticed that `onLastAssembly()` could be invoked more than once per subscription which contradicts with its name. 
If `Hooks.onLastOperator` is used to initialize context (propagation form ThreadLocal) it could lead to re-initialization/replacement of the original context with wrong one.

I'm not sure if it is correct behavior. 
If it is correct one what is the reason/use case for such behavior? 

## Expected Behavior
`onLastAssembly()`  should be invoked once per subscription

## Actual Behavior
in addition to initial subscription `onLastAssembly()` is invoked from  
reactor.core.publisher.FluxRetry.RetrySubscriber#resubscribe  
reactor.core.publisher.FluxOnErrorResume.ResumeSubscriber#onError  
reactor.core.publisher.MonoTimeout#subscribe
...

## Steps to Reproduce
```java
@Test
public void onLastAssemblyShouldBeInvokedOncePerSubscription() {
    ArrayList<Exception> traces = new ArrayList<>();
    Hooks.onLastOperator("my-hook", (publisher) -> {
        traces.add(new RuntimeException("fromHook"));
        return publisher;
    });
    Mono.error(new RuntimeException("boom"))
            .retry(1)
            .onErrorResume(throwable -> Mono.empty())
            .block();
    traces.forEach(e -> e.printStackTrace());
    Assertions.assertThat(traces).size().isEqualTo(1);
}
```

## Possible Solution
if Publisher is Mono or Flux use 
`public abstract void subscribe(CoreSubscriber<? super T> actual);`

## Your Environment
* Reactor version(s) used:
reactor-core-3.2.12.RELEASE

**Comment by bsideup** [comment]
Hi @robotmrv,

Thanks for reporting!

I created https://github.com/reactor/reactor-core/pull/1884 to fix it. It targets "3.3.x" (aka "master") because we introduced `CorePublisher` in 3.3.x to be able to distinguish Reactor's types from RS.

**Comment by robotmrv** [comment]
Hi @bsideup ,
Thanks for fast reply  
so it will not be fixed in 3.2.x?

**Comment by bsideup** [comment]
@smaldini @simonbasle any suggestion how we can fix it in 3.2.x?

**Comment by simonbasle** [comment]
nothing comes to mind for 3.2, if this all depends on restricting the sources on any of `Mono` or `Flux`, then `CorePublisher` is needed.

**Comment by robotmrv** [comment]
@bsideup 
I am not sure that fix from #1884 is complete.  
`Mono#retry()`  was just an example of the problem.    
There are a lot of `org.reactivestreams.Publisher#subscribe` usage  inside of operators.  
So, I think they would still invoke `onLastAssembly()`, or am I wrong?

**Comment by simonbasle** [comment]
@robotmrv no, `onLastAssembly` doesn't have anything to do with "on last subscription" and shouldn't prevent more subscriptions being performed by operators that depend on it, like retry/repeat/etc... It's to do with the last operator being added in the chain of Publishers, at assembly time.

**Comment by robotmrv** [comment]
from `reactor.core.publisher.Hooks#onLastOperator()`  
> Add or replace a named Publisher operator interceptor for the last operator created in every flow (Flux or Mono).

and from reference guide  
> onLastOperator is similar, except that it is only invoked on the last operator in the chain before the subscribe call.

So I understood it in the wrong way. Like flow/chain is the resulting publisher.  
Maybe it is worth to add definition of the `flow/chain` or just an example to the reference/javadoc?

**Comment by simonbasle** [comment]
I believe the `chain` and `operator` terms are used consistently to talk about `Publishers` throughout the documentation. one could say `a chain of operators results in a Publisher that represents the composition of said operators`.
