### ISSUE TITLE
Throwing exceptions from subscribe back to caller does not work

### ISSUE THREAD

**Issue by shamir-gs** [reactor/reactor-core#1887]
I have an application that's listening to a kafka topic. The application is reactive java, and uses spring kafka. We inject a middleware code for kafka that allows us to set up retries whenever an exception is thrown from the subscriber of a topic. This works for non-reactive applications. However in reactive apps, we use ".subscribe" to listen and react to messages in the topic. Using flux "subscribe" we are not able to return an exception to kafka handlers.

## Expected Behavior
Whenever the subscriber is not able to process the message, the application should throw a custom exception upstream

## Actual Behavior
Error within application stating ErrorCallbackNotImplemented

## Steps to Reproduce
Throwing an exception in mono and then subscribing doesn't allow the exception to bubble up. I need a way to bubble up the exception

```java
Example
clien1.getDetails() //returns Mono
.map(details ->
client2.submitDetails(details) //throws an exception to buble up
).subscribe(aVoid -> {
}, error -> {throw new RuntimeException(error);})) . //I wish the exception to bubble up
.doOnError(error -> log.error("Error thrown from first subscriber", error))
.doOnSuccess(data -> log.info("Successfully sent the details", data)) //instead a success is registered here
.subscribe(aVoid -> {
}, error -> {throw new RuntimeException(error);})) . //it doesn't reach here with an exception
```

**Comment by simonbasle** [comment]
your fundamental error was to do a nested subscribe. this breaks the reactive chain and typically causes onError signal propagation issue. the other wrong assumption is that throwing is effective in an asynchronous reactive world. Sure, most operators that act synchronously like map will turn a thrown exception into an onError signal that can also be correctly propagated asynchronously. but throwing in subscribe isn't behaving as well. it sounds like your handler is only capable of dealing with imperative blocking code, which is in itself a problem. a tempting workaround would be to replace the last subscribe with a block(), but you'd be sacrificing all which makes reactive programming beneficial 😔
ideally, the handler would be capable of dealing with error notifications, eg via a callback, or by receiving a future

**Comment by simonbasle** [comment]
for the first (nested) subscribe, replace its parent map with flatMap, and chain thenReturn(details) to submitDetails
