### ISSUE TITLE
Conditional Transformation on Mono

### ISSUE THREAD

**Issue by niksw7** [reactor/reactor-core#1895]
## Summary
I had a use case where I wanted to do a conditional transformation on the input data.
eg: I have welcomeShopper function which will welcome a shopper and return any type of shoppers like WindowShopper or RegularCustomer. Now the use case is if the customer is WindowShopper, I have to transform her to RegulaCustomer and continue the rest of the flow as it is. Here is how imperative code looks like.
```
   fun welcomeShopper(): Mono<Shopper> {
       return listOf(WindowShopper(), RegularCustomer()).random().toMono()
   }
   interface Shopper {
       fun checkOut() {}
       fun getItems(): List<String> {
           return listOf("free-coupons")
       }
   }

   class WindowShopper : Shopper

   class RegularCustomer : Shopper
```

```
fun main() {
    welcomeShopper()
            .map {
                if (it is WindowShopper)
                    Mono.just(RegularCustomer()) //convert to regular customer
                else
                    it //do nothing
            }.
map{
//do other things
}.subscribe()
```
## Motivation
Imperatively writing if and else is something that should be avoided in reactive programming and in the quest of enforcing this idea, I created a small extension function in Kotlin to help me get to the desired style of reactive programming
## Desired solution
The below code is an extension function on the top of Mono
```
fun <T> Mono<T>.conditionalTransformation(
        predicate: Predicate<T>,
        transformer: (T) -> Mono<T>
): Mono<T> {
    return flatMap {
        if (predicate.test(it))
            transformer.invoke(it)
        else
            Mono.just(it)
    }
}
```
```
interface Shopper {
    fun checkOut() {}
    fun getItems(): List<String> {
        return listOf("free-coupons")
    }
}

class WindowShopper : Shopper
class RegularCustomer : Shopper

fun welcomeShopper(): Mono<Shopper> {
    return listOf(WindowShopper(), RegularCustomer()).random().toMono()
}

fun main() {
    welcomeShopper()
            .conditionalTransformation(
                    Predicate {
                        it is WindowShopper
                    },
                    toRegularCustomerTransformation
            )
            .filter {
                it.getItems().size > 1
            }
            .map {
                it.checkOut()
            }
            .subscribe()
}

val toRegularCustomerTransformation: (Shopper) -> Mono<Shopper> = {
    Mono.just(RegularCustomer())
}
```

I also see this request very much similar to what I am facing, but not sure if it solves my issue
https://github.com/reactor/reactor-core/issues/1186

**Comment by simonbasle** [comment]
There is nothing inherently wrong with using `if/else` in `flatMap` blocks. Your extension method approach is also sound, just not something we're thinking about integrating in the core.
