### ISSUE TITLE
Mono/Flux `retry` and `retryBackoff` should support a filter for errors that are retried.

### ISSUE THREAD

**Issue by sollecitom** [reactor/reactor-core#1905]
An example use case is preventing the retries in case a `WebClient` request mapping unexpected statuses to an error is retried.

```
var response = request.retrieve().onStatus(status -> !status.equals(HttpStatus.OK), response -> error(new HttpStatusCodeException(response.statusCode()) {})).bodyToMono(String.class);

var retried = response.retry(3);
...
```

Now, if the status is say 403, there's no point retrying, so adding a filter would allow to write something that looks like:

```
...
var retried = response.retryErrorsMatching(3, error -> error instanceOf HttpStatusCodeException.class && ((HttpStatusCodeException) error).getRawStatusCode() != 403 );
...
```

The equivalent should apply to `retryBackoff`.

The implementation would be trivial, requiring to add an additional check in `FluxRetryWhen`.

```
   if (iteration >= numRetries || !retriedErrors.test(t2.getT2())) {
      return Mono.<Long>error(new IllegalStateException("Retries exhausted: " + iteration + "/" + numRetries, t2.getT2()));
   }
```
(perhaps with different error message in the `IllegalStateException`.

I'd even be ready to write my own `FluxRetryWhen`-like `FluxOperator`, but everything is final and package-private.

**Comment by simonbasle** [comment]
@sollecitom thanks for submitting this idea and sorry for not getting back to you sooner. There is a `retry(long, Predicate)` variant that will forward non-matching errors directly. The same is missing for `retryBackoff`, but I feel this has quite a large number of overloads already, so I'm on the fence adding another variant.

Note that there is `Retry` builder in [`reactor-extra`](https://github.com/reactor/reactor-addons/blob/master/reactor-extra/src/main/java/reactor/retry/Retry.java#L96) which is more customizable. Would that be enough?

**Comment by sollecitom** [comment]
Hi Simon, thanks for getting back to me. Yeah, the retry builder probably
works, I wasn't aware of it.

**Comment by simonbasle** [comment]
ok, cool. it implies another dependency though...

closing this for now, but if somebody else feels this is important enough that the additional overload(s) tradeoff is worth it, please comment and we'll evaluate again.
