### ISSUE TITLE
Allow Mono.block to take a null duration

### ISSUE THREAD

**Issue by philwebb** [reactor/reactor-core#1909]
It would be useful if `Mono.block(duration)` could accept `null` and in such cases work in the same way as `Mono.block()`.

**Comment by simonbasle** [comment]
hey @philwebb what is the end goal? I'm guessing that you want to call the same method within a logical path that selects a `Duration`? In that case, would there be a real improvement with `null` over an arbitrarily large `Duration`?

**Comment by philwebb** [comment]
We quite often end up calling the method with a timeout that the user has configured and `null` is generally used to indicate infinite. Currently this means that for a configurable timeout we need to always do an if statement:

```java
if(timeout != null) {
    mono.block(timeout);
} else {
    mono.block();
}
```

An infinite timeout seems distinct from an arbitrarily large timeout, and `null` feels like quite a natural way to represent it (at least for configuration).

The same pattern could also be applied to the `cache()` method BTW.

**Comment by rsbeoriginal** [comment]
does it needs to fixed? If yes may I try to fox it

**Comment by simonbasle** [comment]
I'd vote against changing `cache` or any operator, on the fence for `block` (which isn't an operator proper, more a bridge to the imperative world). On one end I don't want to limit the number of new `@Nullable` input parameters in the API, but on the other hand blocking is already smelly, so why not make it smellier 😜

The danger would be to add operators that accept `null` and make it seem like the rest of the API is `null`-friendly (it is not!).

@smaldini any opinion?

@rsbeoriginal sure you can either wait for a clearer decision or prepare a PR right away (keeping in mind it might end up declined). The impacted method would be the variants of `Flux#blockFirst`, `Flux#blockLast`, `Mono#block` and `Mono#blockOptional` that take a `Duration`, which could delegate to duration-less counterparts when the parameter is `null`.

**Comment by juanpmarin** [comment]
@philwebb have you tried something like this ?
`mono.block(Objects.requireNonNullElse(timeout, Duration.ofSeconds(Long.MAX_VALUE)));`

**Comment by philwebb** [comment]
@juanpmarin That's a really nice solution, unfortunately we're constrained to Java 8 :(

**Comment by philwebb** [comment]
I think I'll close this one since `null` parameters aren't common in Reactor. It's not really a big deal for us to use the existing `if/else` logic.

I had seen the pattern of allowing `null` for input but never returning `null` used in a few libraries so I just raised the issue in case it was also a pattern you wanted to follow.
