### ISSUE TITLE
StackOverflow with filter or skipWhile

### ISSUE THREAD

**Issue by msoub** [reactor/reactor-core#191]
FilterSubscriber.onNext recursively calls onNext when the predicate is not verified, which could end up with a StackOverflow error at some point. The same applies to skipWhile.

**Comment by smaldini** [comment]
Hey thanks for your report !
Can you attach the exception trace and the flow to reproduce it ?

**Comment by msoub** [comment]
Thanks for the quick reply!

Here you go:

```java
@Test
public void testFilterStackOverflow() {
    Flux<Double> flux = Flux.from((Publisher<Double>) s -> s.onSubscribe(new Subscription() {
        boolean cancel = false;
        OfDouble stream = new Random().doubles().iterator();

        @Override
        public void request(long n) {
            while (!cancel && n-- > 0) {
                if (stream.hasNext()) {
                    s.onNext(stream.next());
                } else {
                    s.onComplete();
                }
            }
        }

        @Override
        public void cancel() {
            cancel = true;
        }
    }))
        .filter(v -> v < 0);

    TestSubscriber.subscribe(flux).await();
}

> java.lang.StackOverflowError
	at java.util.Random$RandomDoublesSpliterator.tryAdvance(Random.java:1140)
	at java.util.Spliterators$4Adapter.hasNext(Spliterators.java:816)
	at com.edgelab.forecast.impact.ImpactFactoryTest$1.request(ImpactFactoryTest.java:91)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:121)
	at com.edgelab.forecast.impact.ImpactFactoryTest$1.request(ImpactFactoryTest.java:92)
	at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:121)
	at com.edgelab.forecast.impact.ImpactFactoryTest$1.request(ImpactFactoryTest.java:92)
        ...

**Comment by akarnokd** [comment]
Almost all operators call `actual.onNext()` to pass along the value when the circumstances are right, they don't call themselves. If the chain is very long (~100 subsequent operators) then yes, you may end up with SO but this is true for any deeply nested method calls.


You implemented `Subscription` incorrectly; it should be reentrant-safe; also there is a `Flux.fromIterable` that does what you need.

```java
Flux.fromIterable(() -> new Random().doubles().iterator())
filter(v -> v < 0);

**Comment by msoub** [comment]
The test case is a big shortcut to reproduce the StackOverflowError.
I think I will inspire my Publisher from FluxIterable to avoid this scenario to happen.

**Comment by smaldini** [comment]
Closing for now as clarified as a design question.
