### ISSUE TITLE
Clarify Flux#join documentation / diagram: role of onNext in windowing functions

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#1915]
## Motivation
The documentation and marble diagram of `Flux#join` is a bit unclear as to what happens when the left and right publishers used for "windowing" emit a value: is the windowing taking only `onComplete` into account, or does `onNext` count? What about a publisher that emits `onNext` then completes with a delay?

The `onNext` ARE actually considered as closing of the "window" for the particular value that spawned the Publisher. The window is immediately closed, so the original value will stop being fed to the combination `Function`.

## Desired solution
The documentation phrasing should be improved, as well as the diagram, which should show an `onNext` on at least one of the left/right publishers, ending that particular window.

**Comment by gindex** [comment]
I would like to submit a PR for that 😊

**Comment by simonbasle** [comment]
sure, go ahead 😊
