### ISSUE TITLE
Add upper limit time to Mono#cache(Function, Function, Function) 

### ISSUE THREAD

**Issue by robotmrv** [reactor/reactor-core#1916]
Current implementation of `reactor.core.publisher.Mono#cache(java.util.function.Function<? super T,java.time.Duration>, java.util.function.Function<java.lang.Throwable,java.time.Duration>, java.util.function.Supplier<java.time.Duration>)` provides lower bound `Duration.ZERO` as special case for caching - it avoids unnecessary cache invalidation task scheduling but it does not provide upper bound `Duration` which would be treated as `infinity`  

## Motivation
It would be helpful for cases when user wants cache only data signal.
like here https://github.com/reactor/reactor-rabbitmq/blob/master/src/main/java/reactor/rabbitmq/Utils.java#L60 
```java
    public static <T> Mono<T> cache(Mono<T> mono) {
        return mono.cache(
                // cache success
                element -> Duration.ofMillis(Long.MAX_VALUE),
                // do not cache failures (allows retry to work)
                throwable -> Duration.ZERO,
                // do not cache empty
                () -> Duration.ZERO);
    }
```
with usage here https://github.com/reactor/reactor-rabbitmq/blob/master/src/main/java/reactor/rabbitmq/Sender.java#L320
```java
    public RpcClient rpcClient(String exchange, String routingKey) {
        return new RpcClient(connectionMono.map(CHANNEL_CREATION_FUNCTION).transform(this::cache), exchange, routingKey);
    }
```

In this example caching leads to memory leak as invalidation task will wait `Duration.ofMillis(Long.MAX_VALUE)` i.e. - effectively indefinitely. 

## Desired solution
add special `Duration` value like `Duration.ofMillis(Long.MAX_VALUE)` or `null` to not schedule invalidation task and maybe even release reference to the parent like it was made in `reactor.core.publisher.Mono#cache()`

## Considered alternatives
use `Mono.cache()` + invalidated Holder like 
```java
public <T> Mono<T> cacheOnlyData(Mono<T> mono) {
    AtomicInteger counter = new AtomicInteger();
    ConcurrentHashMap<Integer, Mono<T>> cache = new ConcurrentHashMap<>();
    return Mono.defer(() -> cache.computeIfAbsent(counter.get(),
            key -> mono
                    .cache()
                    .doOnSuccessOrError((data, throwable) -> {
                        if (data == null || throwable != null) {
                            if (counter.compareAndSet(key, key + 1)) {
                                cache.remove(key);
                            }
                        }
                    })
    ));
}
```

**Comment by robotmrv** [comment]
Hi Reactor team, 
any thoughts? 
btw. There was similar request about timeout/cache in 
https://github.com/reactor/reactor-core/issues/1909#issuecomment-536730704
> An infinite timeout seems distinct from an arbitrarily large timeout, and null feels like quite a natural way to represent it (at least for configuration).
>
>The same pattern could also be applied to the cache() method BTW.

or is it just better to fix on `reactor-rabbitmq` and other users side?

**Comment by simonbasle** [comment]
I agree the interpretation of `Duration.ofMillis(Long.MAX_VALUE)` would be an enhancement, but it doesn't feel too bad since conceptually if you cache, you are already being conservative with the resource. i.e. you are not likely to cache a ton of different sources, but rather cache once and reuse the cached `Mono`. Since only one cleanup task is created (in the case of `Long.MAX_VALUE` being mapped to `onNext`, and since we're dealing with a `Mono` there), this limits damages.

**Comment by robotmrv** [comment]
Hi @simonbasle  
will this feature be backported to 3.2.x? it does not look like a big change in behavior

**Comment by simonbasle** [comment]
As I was merging on master, I thought "oops I had that issue  targeting 3.2 initially...", went back here to double check and it was 3.3 after all... I think I can backport it to 3.2 if you feel this is heavily needed.

**Comment by robotmrv** [comment]
It is small, non-breaking feature, but it fixes possible issues with leaks and a lot of people still use 3.2.x (me also).  
So it would be nice to have it there.
