### ISSUE TITLE
Mono.doOnSubscribe(...) doesn't respect Mono.subscribeOn(...)

### ISSUE THREAD

**Issue by christian-schlichtherle** [reactor/reactor-core#1919]
I'm not sure if this is actually a bug as the documentation doesn't detail the expected behavior, but it fails my personal expectation at least, so here we go...

Using `reactor-core` from the Dysprosium release, I have some piece of code similar to this:

```
// In some class:
static final Logger logger = ...;

Mono<Result> scanFile(Path file) {
    return Mono
            .fromCallable(() -> {
                logger.debug("(A) Scanning file: {}", file);
                try (var is = Files.newInputStream(file)) {
                    return readData(is);
                }
            })
            .subscribeOn(Schedulers.boundedElastic())
            .publishOn(Schedulers.parallel())
            .map(this::processData);
}

void run(Path file) {
    scanFile(file)
            .doOnSubscribe(s -> logger.debug("(B) Scanning file: {}, file));
}
```

The logging statements have been inserted to illustrate my point, which is that I want to use `Mono.doOnSubscribe(...)` to monitor the `scanFile` method - this use case is described in the Javadocs.

However, the logging output shows that the two statements are executed on different thread pools:

+ Logging statement (A) is executed on `Schedulers.boundedElastic()`, as expected.
+ Logging statement (B) is executed on `Schedulers.parallel()`, which is a surprise.

Apparently, logging statement (B) picks up the scheduler set by the `.publishOn(Schedulers.parallel())` statement, which it shouldn't.
When I insert another `.publishOn(Schedulers.boundedElastic())` call just before the `.doOnSubscribe(...)` call, nothing changes, so I cannot fix the issue.

I'm running this on macOS 10.14.6 using OpenJDK 13.

**Comment by simonbasle** [comment]
How are you invoking the `run()` method?
I just tested with a simplified version and the B message is logged from the `main` thread, which is what to be expected:

```java
Mono<String> mono = Mono
		.fromCallable(() -> {
			System.out.println("(A) on " + Thread.currentThread().getName());
			return "foo";
		})
		.subscribeOn(Schedulers.boundedElastic())
		.publishOn(Schedulers.parallel())
		.map(v -> v + "processed")
		.doOnSubscribe(s -> System.out.println("(B) on " + Thread.currentThread().getName()));
StepVerifier.create(mono)
            .expectNext("fooprocessed")
            .verifyComplete();
```

The `doOnSubscribe` is tied to the `Flux#subscribe` signal (NB: not `Subscriber#onSubscribe`, but that's not a relevant subtlety). Subscription signal flows from bottom to top, so the operator acts _before_ the subscription thread is switched by `subscribeOn`:

```
MAIN:      subscribe() -> doOnSubscribe -> subscribeOn
ELASTIC:                                      |-> fromCallable -> publishOn
PARALLEL:                                                            |-> map -> completion
```

**Comment by akarnokd** [comment]
This is by design. `onSubscribe` is invoked on the subscribing thread so that if the operator goes async and would need to timeout/stop, there is a handle to cancel it from the start. Otherwise a call to `onSubscribe` on another thread would be arbitrarily delayed and no way to cancel it because the `Subscription` is not available until `onSubscribe` is actually run. `doOnSubscribe` is attached to `onSubscribe` thus the same properties apply.

If you want to move `doOnSubscribe` to a different thread, you have get it subscribed on a background thread:

```java
Mono.just(1).publishOn(Schedulers.computation())
.flatMap(v -> 
    source.doOnSubscribe(s -> { })
    .op()
    .op()
    ...
)
```

**Comment by christian-schlichtherle** [comment]
> * Logging statement (A) is executed on `Schedulers.boundedElastic()`, as expected.
> * Logging statement (B) is executed on `Schedulers.parallel()`, which is a surprise.

Apparently I'm calling `run()` from a thread in the `parallel()` pool. Thanks for clarification! This ticket can be closed.
