### ISSUE TITLE
Allow zipWith to take a BiFunction that returns Mono

### ISSUE THREAD

**Issue by NickFitton** [reactor/reactor-core#1920]
## Motivation
I find myself in spring zipping two monos to then do a reactive call very often.
For example gathering security context and the request body to do some function.

## Desired solution
Any of the following:
* A version of the public zip() method that takes a BiFuction that produces a Mono.
* A version of the zipWith() method that takes a BiFunction that produces a Mono.
For example, the first method would have the following signature:
```java
public static <T1, T2, O> Mono<O> zip(
    Mono<? extends T1> p1,
    Mono<? extends T2> p2,
    BiFunction<? super T1, ? super T2, Mono<? extends O>> combinator);
```

## Considered alternatives
I have written a workaround alternative for the cases I would like this functionality, but feel it would be cleaner if implemented into core.
```java
  public static <T1, T2, O> Mono<O> zip(Mono<? extends T1> p1, Mono<? extends T2> p2,
      BiFunction<T1, T2, Mono<? extends O>> combinator) {
    return Mono.zip(p1, p2).flatMap(tuple2 -> combinator.apply(tuple2.getT1(), tuple2.getT2()));
  }
```
With the usage then being:
```java
zip(SecurityContext.getAuthenticatedClaims(), request.bodyToMono(SomeDto.class), (claims, body) -> reactiveService::doSomething);
```
This feels nice now but doesn't work for the zipWith scenario.
The following code feels like it should be valid but zipWith will return a Mono<Mono<>>:
```java
Mono<SomeDto> request.bodyToMono(SomeDto.class)
    .doOnNext(this::someValidation)
    .zipWith(SecurityContext.getAuthenticatedClaims(), (body, claims) -> reactiveService::doSomething)
```
and if you want to use it in this fashion you then need to flatMap the result
```java
    .flatMap(res -> res)
```
<hr>

Another alternative would just be to suck it up and use the tuples produced by zips which I'm not a fan of.

As far as I can see the implementation limitation lies in the `MonoZip` class which holds the zipper:
```java
	final Function<? super Object[], ? extends R> zipper;
```

**Comment by simonbasle** [comment]
`zip` is not in the business of dealing with a `Mono` and subscribing to it, I'm afraid we won't introduce such a signature. The `tuple2` + `flatMap` is the recommended way of doing this.

You could maybe make it a bit more palatable to you by having an utility function like this as syntactic sugar:

```java
public static <T1,T2, R> Function<Tuple2<T1, T2>, R> bifunctionOnTuple(BiFunction<T1,T2,R> combinator) {
	return t2 -> combinator.apply(t2.getT1(), t2.getT2());
}
```
usage would look like:

```java
SecurityContext.getAuthenticatedClaims()
    .zipWith(request.bodyToMono(SomeDto.class))
    .flatMap(bifunctionOnTuple(reactiveService::doSomething));
```

**Comment by jamb1975** [comment]
// This returns a JSON or XML with the users
			Mono<Quote> m_lastquote =quotesclient.getLatestQuote(ticket);
			Mono<TradingCompany> m_tradingcompany =tradingcompanyclient.getTradingCompany(ticket);
			//Mono.zip(monoA, monoB, biFunction) or monoA.zipWith(monoB, biFunction).
			 Mono<TradingCompanySummary> m_tradingquote= Mono.zip(m_tradingcompany, m_lastquote,(t, q)->new TradingCompanySummary(t, q));
