### ISSUE TITLE
Flux.cache hangs indefinately in multi-batch flow scenarios (many request calls).

### ISSUE THREAD

**Issue by a701440** [reactor/reactor-core#1921]
@Test
    public void testCacheWithMultipleBatches() {
        List<Integer> x = Flux.range(0, 1000).cache(5).toStream(10).collect(Collectors.toList());
    }

This code hangs in version 3.3.0.RELEASE. Was not causing this problem in 3.2.2.RELEASE.
Looks like hanging is caused by cache, when cache is removed it succeeds. When toStream parameter is bumped to a large number so only one request is made it does not hang.

**Comment by a701440** [comment]
Not 100% sure, but this seems to be a side effect caused by the c5a66ba79bd10ac13923e5fd0d845d3d91f83ae9 commit. FluxReplay does not seem to have any capability to make multiple "request" calls to it's own source. Only one call is made in "onSubscribe". If downstream is making multiple request calls to FluxReplay it does not propagate them properly upstream. @simonbasle

**Comment by simonbasle** [comment]
we'll look into it, but it seems indeed to be a side effect of that change. the thing is, a complete revert is probably not appropriate, so I'll explore middle grounds (see #1948)

**Comment by a701440** [comment]
It's weird, but I do not see any code that would handle multiple "request" calls in the FluxReplay. it looks like the class needs to be redesigned to handle that.
