### ISSUE TITLE
add Flux.lastOrEmpty()

### ISSUE THREAD

**Issue by cybuch** [reactor/reactor-core#1927]
## Motivation

Currently `Flux` has method `last()` which returns `NoSuchElementException` if there wasn't anything to return. IMHO it would be nice to have a method `lastOrEmpty` so I wouldn't have to catch 'NoSuchElementException`. 

## Desired solution

I can call operator `lastOrEmpty()`  on `Flux` which will return empty `Mono` if there's no element to return

**Comment by simonbasle** [comment]
You can actually use `takeLast(n)` (`takeLast(1)` in your case) to achieve the same without the exception, as hinted in the javadoc.
