### ISSUE TITLE
Using custom tags for metrics with Prometheus forces the same tags on all publishers in the system

### ISSUE THREAD

**Issue by alexandrelasouza** [reactor/reactor-core#1928]
## Expected Behavior
Publishers should allow different tags for different flows.

## Actual Behavior
All publishers in the system must have the exact same set of tags, otherwise Prometheus registry throws an exception (same exception as issue #1425) during execution of different flows.
`java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter containing tag keys [exception, flow, owner, service, status, type]. The meter you are attempting to register has keys [flow, owner, service, status, type].`

## Steps to Reproduce

```java
    @Test
    void testPrometheusThrowsException() {        
        Mono.just("data")
            .name("noTag")
            .metrics()
            .block();

        assertThrows(IllegalArgumentException.class, () -> {
            Flux.just("data", "moreData")
                .name("withTag")                
                .tag("tagKey", "tagValue")
                .metrics()
                .blockLast();
        });

        assertThrows(IllegalArgumentException.class, () -> {
            Mono.just("data")
                .name("withAnotherTag")
                .tag("otherTagKey", "otherTagValue")
                .metrics()
                .block();
        });
    }

    @Test
    void testPrometheusThrowsExceptionStartingWithTag() {
        Mono.just("data")
            .name("withTag")
            .tag("tagKey", "tagValue")
            .metrics()
            .block();

        assertThrows(IllegalArgumentException.class, () -> {
            Flux.just("data", "moreData")
                .name("noTag")                
                .metrics()
                .blockLast();
        });

        assertThrows(IllegalArgumentException.class, () -> {
            Mono.just("data")
                .name("withAnotherTag")
                .tag("otherTagKey", "otherTagValue")
                .metrics()
                .block();
        });
    }
```

## Possible Solutions
1-) Modify the **metrics** operator to take a prefix as input and replace the **reactor** prefix with it.

2-) Use the publisher name as prefix for the meters, or put it in the middle (e.g.: **myPublisherName.flow.duration** or **reactor.myPublisherName.flow.duration**, instead of **reactor.flow.duration**). This would also eliminate the **flow** tag, since the publisher name would be in the metric name.

## Your Environment
* Reactor version(s) used: 3.3.0.RELEASE
* Other relevant libraries versions (eg. `netty`, ...): micrometer-registry-prometheus:1.3.0 (from Spring Boot 2.2.0 BOM)
* JVM version (`java -version`): openjdk version "11.0.5" 2019-10-15

**Comment by alexandrelasouza** [comment]
I also set up a simple application to show it.
https://github.com/alexandrelasouza/reactor-metrics-bug-demo

Just run the app and do a GET request to /notag and /withtag
The second request would show the issue.

**Comment by shakuzen** [comment]
Unless the aggregation of metrics from all flows is generally meaningful, using a different metric name for different flows (or groups of flows with the same tags?) sounds reasonable to me. In Micrometer, we are also exploring if the limitation imposed in the current Prometheus implementation is still necessary, but I'll need more time to fully investigate that.

**Comment by simonbasle** [comment]
@bsideup @shakuzen I wonder if the proposition of adding the flux `.name()` to the meters names makes sense, in light of recent issues around meter explosion (see reactor-netty)?

we can certainly pursue fixing the missing `exception` tag, at least. wdyt @bsideup ?

**Comment by shakuzen** [comment]
> in light of recent issues around meter explosion (see reactor-netty)

Sorry if I've missed a notification. What's happened?

> I wonder if the proposition of adding the flux `.name()` to the meters names makes sense

Again, this depends on expectations. Should metrics for different publishers be separate, or is there value in aggregating across all of them? Looking at, for example, the `reactor.subscribed` Counter, would a user ever want to sum this for all publishers to get a count subscribed for all publishers? Or would it only be used on a per-publisher basis?

**Comment by simonbasle** [comment]
@shakuzen as I understand it, there was an issue with `reactor-netty` metrics where creating meters for each route in an application would lead to an OOM. This can be dealt with to some extent by setting up a hard limit on the number of meters the registry can create, as a workaround.

doesn't adding a `Flux`'s "name" to the meter name help manifesting the same kind of issue?

that said, metrics are already enabled on a per-`Flux` (or even per Flux "stage") basis, and indeed it doesn't make much sense to have most of the metrics being aggregated across the whole set of instrumented Flux (except maybe for visualizing stats like "request per second" vs "data publication per second" or something)...

**Comment by marvedly** [comment]
I have also experienced this problem and find it cumbersome that all metrics reported to `"reactor.subscribed"` must have the same set of tags. Also, it is not very clear that:
`Flux.just(1, 2).name("some.name").metrics()` == `Flux.just(1, 2).tag("flow", "some.name").metrics()` from what I can read in the documentation.

By using `.name("some.name")` I expect that the metrics will be reported on a meter named `some.name`, not a metric called `"reactor.subscribed"` tagged with `"flow" = "some.name"`

Or have I misunderstood something?

**Comment by simonbasle** [comment]
for reference, the exact opposite was asked for reactor-netty metrics: https://github.com/reactor/reactor-netty/issues/986

**Comment by simonbasle** [comment]
@alexandrelasouza the name and `flow` tag themselves don't seem to be the problem, since the message you quote rather mentions `exception` as the missing tag. #1425 should have fixed that, but maybe we have missed something?

@shakuzen it seems that having a "flow" tag rather than making the publisher name part of the metric name can be desirable, allowing to both get aggregated metrics (like "what's the average subscription-to-completion duration over all `Flux` and `Mono` in the app?") as well as digging into a named `Flux`.

**Comment by alexandrelasouza** [comment]
@simonbasle the `exception` tag is just an example. Check the tests I put in the `Steps to reproduce` section.

In the first case, it begins by executing a `Mono` without any tags (which will create the metric in the `MeterRegistry`) and then it tries to execute `Mono`s with some added tags and it throws the exception from the MeterRegistry.

The second case, the metric is initialized with the tags from the first `Mono` and than it tries to execute a `Mono` without any tags and with a tag different from the first one.

The issue happens if you try to add any tag to an existing metric (which is the case for the current `Flux`/`Mono` metrics), not only for the `exception` tag.

**Comment by simonbasle** [comment]
got it, it is not about micrometer tags that are added by the `metrics()` operator, but rather about tags that the _user_ manually adds through the `tag()` operator.

in order to accommodate both the use case where one doesn't add tags and wants to look at an aggregated view of all publishers in the app AND the use case where one wants custom tags and is ok to have these under a different metric name, we could maybe add a configuration option that opts into the later (picking up the prefix via the `name()` operator)?

so the limitation would be that A) you don't get an aggregated view anymore and B) you need to ensure a consistent set of custom `tag()`s whenever you use the same `name()`.

**Comment by simonbasle** [comment]
so battle plan:

 - remove the `flow` tag altogether
 - using the `name` operator will replace the `reactor` prefix in meter names with whatever name was given to the sequence
 - using tags but not `name` will be documented as potentially dangerous, as it creates a sparse set of tags for sequences in the application that don't have a unique name
 - aggregated view is still somewhat possible in this mode by refraining from giving a `name` to the sequence, but consistently using a `tag("flow", "theName")` across all usages of `.metrics()` (which might be challenging if a framework or library also uses `metrics()` without a `name()`)
