### ISSUE TITLE
add Flux.lastOrEmpty() 

### ISSUE THREAD

**Issue by cybuch** [reactor/reactor-core#1930]
Continuation of https://github.com/reactor/reactor-core/issues/1927, because it was closed prematurely. 
That's true what Simon said - I can use `takeLast(1)`, but `takeLast` returns Flux and since I expect one or no value (a `Mono`) I have to use another operator to transform `Flux` to a `Mono`. I could use `takeLast(1).last()`, however this will throw `NoSuchElementException`.  So let's give it another try - `takeLast(1).next()` works as expected - no error returned, we got `Mono`. Wouldn't it be better to have API that would encapsulate that behavior?

**Comment by simonbasle** [comment]
we try not to had more operators when the desired behavior can easily be obtained by combination of two other operators like that, unless we see a super clear incentive to do so.
