### ISSUE TITLE
Flux.create does not propagate immediately after first request

### ISSUE THREAD

**Issue by ivailo-pashov** [reactor/reactor-core#1940]
## Expected Behavior
Events emitted inside the `onRequest` callback parameter invocation of `FluxSink` will be propagated downstream immediately in all cases.

## Actual Behavior
Currently, events emitted only inside the first `onRequest` callback parameter invocation of `FluxSink` will be propagated downstream immediately.
On the next invocations of the `onRequest` callback parameter, the events will not be propagated immediately. Instead, they will be propagated after the requested amount is reached (see related tests).
However, this is will introduce delays or even prevent events from propagating downstream dependent on the publishing rate for infinite streams.

## Steps to Reproduce

```java

import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.LinkedTransferQueue;
import java.util.concurrent.TimeUnit;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import reactor.core.publisher.Flux;
import reactor.core.scheduler.Schedulers;

public class LimitRateTest {

    @Test
    public void testSingleRequestHigherLimit() throws InterruptedException {
        testLimitRate(5, 10);
    }

    @Test
    public void testSingleRequestExactLimit() throws InterruptedException {
        testLimitRate(5, 5);
    }

    @Test
    public void testMultipleRequestsLimitSizeNoMultiplier() throws InterruptedException {
        testLimitRate(5, 3);
    }

    @Test
    public void testMultipleRequestsLimitSizeMultiplier() throws InterruptedException {
        testLimitRate(6, 3);
    }

    @Test
    public void testMultipleRequestsLimitSizeOne() throws InterruptedException {
        testLimitRate(5, 1);
    }

    private static void testLimitRate(int eventsCount, int limit) throws InterruptedException {
        LinkedTransferQueue<Integer> queue = new LinkedTransferQueue<>();

        List<Integer> result = new CopyOnWriteArrayList<>();
        CountDownLatch latch = new CountDownLatch(eventsCount);

        Flux.<Integer>create(sink -> sink.onRequest(requested -> {
            int current = 0;
            while (current < requested) {
                try {
                    Integer value = queue.take();
                    System.out.println("Sending " + value);
                    sink.next(value);
                    current++;
                } catch (InterruptedException e) {
                    throw new IllegalStateException(e);
                }
            }
        }))
            .subscribeOn(Schedulers.elastic())
            .limitRate(limit, 0)
            .doOnNext(next -> System.out.println("Received " + next))
            .subscribe(next -> {
                result.add(next);
                latch.countDown();
            });

        for (int i = 0; i < eventsCount; i++) {
            queue.add(i);
        }

        Assertions.assertTrue(latch.await(5000, TimeUnit.MILLISECONDS), result + "");
    }
}
```

## Your Environment

* Reactor version(s) used: 3.2.8.RELEASE, 3.3.0.RELEASE
* JVM version: OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
* OS and version: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by bsideup** [comment]
Can reproduce, investigating...

**Comment by bsideup** [comment]
FYI if you use `Flux.push` (that does not serialize the sink), the problem goes away

**Comment by bsideup** [comment]
Okay, so...

Since you use `queue.take()`, it will block until the item arrives. Since you use `limitRate`, you will re-batch the requests into chunks of N.
First request drains your queue and gets the first 3 items, all good. But the second one will pull the remained 2 elements and then stuck waiting for one more (since the request is 3), which means that you will block the thread forever.
Try changing `queue.take()` to `queue.poll(1, TimeUnit.SECONDS)` to see the difference.

**Comment by ivailo-pashov** [comment]
`Flux.push` is not a workaround option as it does not respect the rate limit and performs a request with `Long.MAX_VALUE` which is similar to using `Flux.create` with `limitRate ` operator removed.

I guess I did not manage to explain correctly the expected behavior. If you check the logs at `LimitRateTest#testMultipleRequestsLimitSizeMultiplier` you will observe:
```
Sending 0
Received 0
Sending 1
Received 1
Sending 2
Received 2
Sending 3
Sending 4
Sending 5
Received 3
Received 4
Received 5
```
You will observe that events are batched for the second request but not batched for the first request (on the first request events are propagated even before the request callback exists).
It is OK to block the thread indefinitely upon arrival of new data but what has already been received needs to be immediately propagated downstream (in our example, by the same thread before it blocks indefinitely).
My understanding is that `limitRate` operator exists for backpressure of fast publishers and should not prevent slow publishers from emitting their latest data while batching should be performed by `window` and `buffer` operators. 

The expected behavior would be to disable this batching for all requests:
```
Sending 0
Received 0
Sending 1
Received 1
Sending 2
Received 2
Sending 3
Received 3
Sending 4
Received 4
Sending 5
Received 5
```

Changing `queue.take()` to `queue.poll(1, TimeUnit.SECONDS)` is not an option for us because: 
- The provided example is a simplified scenario simulating integration with a blocking API that does not have a timeout option.
- The stream is infinite, so existing the request callback early before the requested amount has been received will prevent new events from being processed
(In the provided example if we call `queue.add` after `latch.await(5000, TimeUnit.MILLISECONDS)`).

**Comment by bsideup** [comment]
@ivailo-pashov 
`Flux.push` does not perform a request, it is a `Publisher`. The workaround works because it won't serialize the `Sink`. "Serialization" here means that there will be an internal queue and everything you produce from `onRequest` will be drained *after* the `onRequest` call.

> The provided example is a simplified scenario simulating integration with a blocking API that does not have a timeout option.

Have you considered using:
```
Mono.fromCallable(() -> callBlockingAPI()).repeat()
```
?

**Comment by ivailo-pashov** [comment]
@bsideup 
Many thanks, I was able to achieve the same using:

```java
Flux.defer(() -> {
    //setup connection
    return Mono.fromCallable(() -> connection.callBlockingAPI())
        .repeat()
        .doFinally(signalType -> connection.stop());
})
```
and it works!

In this case, shall we close this issue? 
The events propagation for `Flux.create` within `onRequest` callback still looks inconsistent to me between the first and subsequent requests.

**Comment by bsideup** [comment]
Yay, happy that you were able to fix it 👍

Since it works as designed (due to the serialization), I guess there is nothing to act upon and we should close the issue. The "inconsistency" is not guaranteed and, as long as you're not blocking in your `onRequest`, it behaves absolutely predictable, and, even if you block, you will see the events after you release `onRequest`.
If that's undesired, `Flux.push` can be used, because it does not serialize the `onNext` calls

**Comment by ivailo-pashov** [comment]
Ok thanks, I am closing the issue then.
