### ISSUE TITLE
Flux onError's exhibit inconsistent behavior

### ISSUE THREAD

**Issue by RankWeis** [reactor/reactor-core#1945]
This issue was working correctly in `3.2.11` and began to fail in `3.2.12`

While upgrading our services, we ran into an issue where our onErrorResume which had previously been working, no longer did.

In examining the behavior, it seems that when a flux has only a single element, the onErrorResume is wrapped in a `ReactiveException` with the `.getCause()` being the original exception. When the publisher is a Mono or when a Flux has multiple elements, this behavior goes away.

A junit test to demonstrate the inconsistent behavior (using NoSuchMethodException for no reason in particular except demonstration):

```java
  @Test
  public void temptest() {
    boolean monoTest = (boolean) Mono.just("")
      .flatMap(x -> Mono.error(new NoSuchMethodException()))
      .onErrorResume(x -> x instanceof NoSuchMethodException ? Mono.just(true) : Mono.just(false))
      .block();
    boolean fluxMultiTest = (boolean) Flux.just("", "")
      .flatMap(x -> Mono.error(new NoSuchMethodException()))
      .onErrorResume(x -> x instanceof NoSuchMethodException ? Mono.just(true) : Mono.just(false))
      .next()
      .block();
    boolean fluxTest = (boolean) Flux.just("")
      .flatMap(x -> Mono.error(new NoSuchMethodException()))
      .onErrorResume(x -> x instanceof NoSuchMethodException ? Mono.just(true) : Mono.just(false))
      .next()
      .block();

    assertTrue("Mono test failed", monoTest);
    assertTrue("Flux Multi test failed", fluxMultiTest);
    assertTrue("Flux test failed", fluxTest);  // The only assertion that fails
  }
```

While we are lucky that we caught this issue in test, this now forces us to understand at every step whether the Flux is emitting a single element or more, and in areas of unpredictable behavior, we are forced to check both the actual exception and the ReactiveException, which does not seem to be the documented behavior.

**Comment by ssko1** [comment]
The change we think caused this issue: https://github.com/reactor/reactor-core/pull/1831

**Comment by simonbasle** [comment]
yes that is indeed the source, I'll fix it.

Please note that it is likely the use of checked exceptions is problematic, and `RuntimeException` should work fine. Maybe you can switch to the later as a workaround?

Another possible workaround for now is to systematically _unwrap_ the exception before onErrorResume, like for example:

```java
whatever
    .onErrorResume(x -> Exceptions.unwrap(x) instanceof CheckedException ? Mono.just(true) : Mono.just(false));
//doesn't work with the onErrorResume(Class, Function) variant though
```

This alternative notation, although it is itself an alias for `onErrorResume`, would also be easier to weed out once the situation is fixed:
```java
whatever
    .onErrorMap(Exceptions::unwrap) //factoring out the unwrapping
    .onErrorResume(x -> x instanceof CheckedException ? Mono.just(true) : Mono.just(false));
//  .onErrorResume(SomeRuntimeException.class, x -> recoverFrom(x));

```
