### ISSUE TITLE
reactor-test direct assertions for Context

### ISSUE THREAD

**Issue by philsttr** [reactor/reactor-core#1955]
Provide direct assertions for `Context` in reactor-test

## Motivation

Currently, it is only possible to perform assertions on a Context [within a `StepVerifier`](https://projectreactor.io/docs/core/release/reference/#_testing_the_context).

It is not possible to perform direct assertions on the Context itself outside of a `StepVerifier`. 
This will be useful for testing code that deals with the Context, but does not necessarily have a stream to test.  i.e. tooling code that populates the context etc.  For example, functions or results passed to `subscriberContext(...)` methods.

It will also be useful for performing assertions in downstream code which contain context values that may not necessarily be seen at the `StepVerifier` level of the main stream under test.

These assertions would also be useful within the `Consumer` passed to `.expectAccessibleContext().assertThat(context -> *here*)`

As a workaround, assertions can be performed on the results of method calls on the context.

For example (using assertj):

```
assertThat(context.hasKey("foo")).isTrue()
assertThat(context.get("foo")).isEqualTo(foo);
```

Unfortunately, the error messages that result from failed assertions do not accurately mention the problem with the context, but rather the problem with the _result_ being asserted on.

Additionally, some of the methods on context throw instead of returning values.  For example, `context.get("foo")` will throw if the entry is not found.  Therefore, I would need to use `context.getOrDefault("foo", null)` in the assertion, which makes the assertion code more verbose.

## Desired solution

I would like to be able to assert on the Context itself, and have the assertion failure messages accurately mention the problem with the Context.

I would like assertions similar to those available to those provided by assertj for `Map`.

For example:

```
assertThat(context).hasSize(x)
assertThat(context).containsKey(x)
assertThat(context).containsExactly(...)
assertThat(context).doesNotContain(...)
```

## Considered alternatives

Currently using assertions on results of method calls on the context.  This is not optimal, because
* assertion failure errors do not accurately point to the main problem with the context
* some context methods throw, causing tests to result in error instead of assertion failures

Could also consider adding a context.toMap() method, so that normal `Map` assertions provided by assertj could be used.

## Additional context

Perhaps use https://joel-costigliola.github.io/assertj/assertj-assertions-generator.html ?  Not sure if that covers all cases though.  I haven't investigated fully.

**Comment by simonbasle** [comment]
I think `ContextAssertion` extension to AssertJ (as described in http://joel-costigliola.github.io/assertj/assertj-core-custom-assertions.html) would work very well, but that would force a compile dependency to `reactor-test`, which we don't want. That said, as a side artifact that could work. It could live either:
 - in the `reactor-addons` repo
 - in a new incubating repo in `reactor-incubator` org
 - as a community project

**Comment by simonbasle** [comment]
@philsttr I have started incubating this idea in https://github.com/reactor-incubator/assertj-reactor, please let me know there of what you think. Eg. in this [draft PR](https://github.com/reactor-incubator/assertj-reactor/pull/1)
