### ISSUE TITLE
Add `Context#reduce`

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#1964]
Often we internally use `stream()` because we need to iterate over the key-value pairs in the `Context`, in order eg. to implement `putAll`. The issue is that `stream` creates immutable `Map.Entry` objects due to its signature, so it generates a bit too much garbage.

Offering a `reduce` operation would solve that problem, and offer a flexible way for users to accumulate or somehow merge values from multiple `Context` into arbitrary objects:

```java
HOLDER reduce(HOLDER initial, ReductionFunction<HOLDER> reductionFunction);
```

This change would include a "tri function":

```java
interface ReductionFunction<T> {
    T apply(T, Object key, Object value);
}
```
Typically `Context` would be used as the `<T>` but it could be anything else.

**Comment by bsideup** [comment]
It looks to me that `reduce` will only be used internally for the operations where *we* merge the `Context`s.

Perhaps we can make it an internal interface and do the `instanceof` check in `putAll`?

**Comment by bsideup** [comment]
Alternatively, we could extend `Context{1, 2, ..., N}` from internal `AbstractContext` with `reduce` or similar operation

**Comment by bsideup** [comment]
To rephrase:
I do not see users reducing `Context` into any object other than `Context`

**Comment by simonbasle** [comment]
AbstractContext doesn't work, because `putAll` takes an arbitrary `Context` and that is the one we need to iterate over (since putAll is not reflexive)

**Comment by simonbasle** [comment]
as for the `Context` never reducing into anything else than `Context`, I'm sure having the flexibility will prove useful at some point, and it's no extra effort nor maintenance.

**Comment by bsideup** [comment]
@simonbasle

> AbstractContext doesn't work, because putAll takes an arbitrary Context 

We can always do `if (context instanceof AbstractContext) fastPath(); else slowPath();`

In most of the cases it will be evaluated to `true`, isn't it?

**Comment by simonbasle** [comment]
Closing this for now as we don't really want to expose new API and new functional interface. The `AbstractContext` indirection could work in reducing garbage generation, but implies that `ContextN` stops extending `LinkedHashMap` and delegates instead.
Opened #1970 to track this idea.
