### ISSUE TITLE
[Minor enhancement] Unnecessary null check and cast in Flowable.collectSortedList(Comparator)

### ISSUE THREAD

**Issue by slisaasquatch** [reactor/reactor-core#1966]
The code I'm talking about is [this](https://github.com/reactor/reactor-core/blob/d15098b/reactor-core/src/main/java/reactor/core/publisher/Flux.java#L3527).

`List.sort(Comparator)` can already take a `null` `Comparator`. In fact, `Collections,sort(List)` on Java 8 simply defaults to `list.sort(null)`. So the whole method can be replaced with:

```java
	@SuppressWarnings({ "unchecked", "rawtypes" })
	public final Mono<List<T>> collectSortedList(@Nullable Comparator<? super T> comparator) {
		return collectList().doOnNext(list -> {
			// Note: this assumes the list emitted by buffer() is mutable
			list.sort(comparator);
		});
	}
```

**Comment by simonbasle** [comment]
Ah, good simplification indeed. Do you want to submit a PR @slisaasquatch? (you'll need to sign the CLA)

**Comment by slisaasquatch** [comment]
Here's the pull request: https://github.com/reactor/reactor-core/pull/1967
