### ISSUE TITLE
[Enhancement] Retry backoff reset

### ISSUE THREAD

**Issue by swimmesberger** [reactor/reactor-core#1978]
Currently using retryBackoff on a hot source is kind of strange because the internal backoff counter is not reset. I would like to have the ability to say "If a error happens retry with a backoff until a onNext item is emitted. Next time an error happens - backoff should start with the first backoff value again"

## Motivation
For hot sources it kind of makes sense to connect to something get some values but when an error happens to completely resubscribe with a backoff. E.g. connection to a service which goes down - retrying with backoff and jitter - and when the connection is successful again and later the service goes down again I want a immediate retry not the time it was previously at.

## Desired solution
Somehow changing the retryBackoff operate do signal a reset of the internal throwable publisher.

## Considered alternatives
I haven't found any suiting alternative for retryBackoff which works for this usecase. Maybe I have misunderstood something and it's possible with some combination of existing operators.
I know that it would be possible when I differentiate the flux which is providing the data and the mono which establishes the connection but it feels kind of strange to do that when retryBackoff is working fine in this usecase but simply do not support resetting the backoff at some point.

Example:
```java
  public static void main(String[] args) throws InterruptedException {
    Flux.<Long, AtomicLong> generate(() -> new AtomicLong(0), (counter, s) -> {
      try {
        long currentCount = counter.incrementAndGet();
        if (currentCount % 10 == 0) {
          System.out.println("Error!");
          s.error(new RuntimeException("Error!"));
        } else {
          s.next(currentCount);
        }
        Thread.sleep(100);
      } catch (InterruptedException e) {
        s.complete();
      }
      return counter;
    }).retryBackoff(Long.MAX_VALUE, Duration.ofSeconds(1), Duration.ofMinutes(1)).subscribe(val -> {
      System.out.println(val);
    });
    synchronized (Thread.currentThread()) {
      Thread.currentThread().wait();
    }
  }
```

When you run this example - you see that it will take longer and longer to see some values again. In my usecase I want the wait time between resubscribing to always be the same. As long as errors are happening the time should be higher each time, on a success it should be reset.

**Comment by simonbasle** [comment]
Something puzzles me though: a hot source is still terminated by a `onError` signal, so I don't understand how that aspect comes into account. A pure hot source couldn't be retried at all, by definition. Something like a `ConnectableFlux` (or the result of applying the `share()` operator) would attempt to reconnect upstream if that is possible.

**Comment by swimmesberger** [comment]
You can run the sample I have provided at the end how to better get a understanding of what I mean. The example prints:
- 1-10 then ERROR, then it waits 1 second
- 1-10 then ERROR, then it waits more than 1 second
....
- after a couple of seconds it always waits 1 minute

What I want is that it always waits 1 minute and only in the case that multiple errors occur in a row it should wait longer.

The hot source is terminated that is right but after the retry a new connection is made to the source and data in between when the connection was lost is lost too - but we still want to retry as fast as possible so we don't miss out more data.
