### ISSUE TITLE
Publisher#then() should allow type mapping, like #thenMany() does

### ISSUE THREAD

**Issue by ericbottard** [reactor/reactor-core#198]
The `then` family of methods is inconsistent:

```
Publisher<X>#then(Publisher<X>) p)
vs
Publisher<X>#thenMany(Publisher<Y> p)
```

it should be possible to change types in the Mono (`then()`) case as well.

**Comment by smaldini** [comment]
Should also add Mono.then(Publisher<Void>) for symmetry if its not conflicting with Mono.then(Function) lambda signature

**Comment by simonbasle** [comment]
taking a deeper look at just the signature differences:
## Flux API
### then
`public final Mono<Void> then()`
>  :white_check_mark: aligned with mono version

`public final <V> Mono<V> then(Mono<V> other)`
> :white_check_mark: added, easy to align with mono version

`public final Mono<Void> then(Publisher<Void> other)`
> :white_check_mark: could be added to mono

`public final Mono<Void> then(Supplier<? extends Publisher<Void>> afterSupplier)`
> :warning: misalignment with mono version (which takes Supplier<Mono<V>>), can't be fixed

### thenMany
`public final <V> Flux<V> thenMany(Publisher<V> other)`
> :white_check_mark: aligned with mono version
> :warning: javadoc says that this one is interrupted by errors, contrary to mono one

`public final <V> Flux<V> thenMany(Supplier<? extends Publisher<V>> afterSupplier)`
> :warning: misaligned with mono version, this one makes more sense though
  
## Mono API
### then
`public final Mono<Void> then()`
> :white_check_mark: ok

`public final <V> Mono<V> then(Mono<V> other)`
> :white_check_mark: ok

`public final <V> Mono<V> then(final Supplier<? extends Mono<V>> sourceSupplier)`
> :warning: different from flux version but this one makes more sense in mono

`public final <R> Mono<R> then(Function<? super T, ? extends Mono<? extends R>> transformer)`
> :white_check_mark: specific to mono (cannot transform more than one value so difficult to adapt in Flux)

### thenMany
`public final <V> Flux<V> thenMany(Publisher<V> other)`
> :white_check_mark: aligned with flux
> :warning: except javadoc says it will append even in case of error?

`public final <V> Flux<V> thenMany(final Supplier<? extends Mono<V>> sourceSupplier)`
> :warning: different from flux, supplies a Mono<V> not Publisher<V> although it would make more sense...
>
> note the signature could be changed to accept Publisher<V>, to which Mono<V> would still comply
>
> note that the implementation could simply use Flux.thenMany? (although once again javadoc says this one appends in case of error)

**Comment by simonbasle** [comment]
- [ ] add `Flux#then(Mono<V>)`
- [ ] modify `Mono#thenMany(Supplier)` to take supplier of `Publisher`
- [ ] update javadoc in Mono to reflect that errors short-circuit
- [ ] update ignorethens1 schemas to reflect that as well
