### ISSUE TITLE
Incorrect marble diagram for withLatestFrom

### ISSUE THREAD

**Issue by sgsfak** [reactor/reactor-core#1981]
I believe the "marble" diagram in the documentation of the `withLatestFrom` [here](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#withLatestFrom-org.reactivestreams.Publisher-java.util.function.BiFunction-) is not correct (`C2` and `D3` should not have been emitted). In fact, it does not agree with the one found in [rxmarbles](https://rxmarbles.com/#withLatestFrom), [rxjs](https://rxjs.dev/api/operators/withLatestFrom), or [rxjava](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Observable.html#withLatestFrom-java.lang.Iterable-io.reactivex.functions.Function-)

## Motivation

Based on the documentation of other reactive libraries `withLatestFrom` is similar to `combineLatest` but it only emits items when the single source Flux emits an item (not when any of the Fluxes that are passed to the operator do, as `combineLatest` does).

## Desired solution

Change the documentation and the diagram according to the offered functionality.

**Comment by simonbasle** [comment]
Indeed you're right. Are you willing to submit a PR? `withLatestFrom` diagram should be straightforward to edit in eg. Inkscape (see https://github.com/reactor/reactor-core/blob/master/docs/svg/README.md for instructions on contributing SVGs). this would have to target `3.2.x` branch.

**Comment by sgsfak** [comment]
> Indeed you're right. Are you willing to submit a PR? `withLatestFrom` diagram should be straightforward to edit in eg. Inkscape (see https://github.com/reactor/reactor-core/blob/master/docs/svg/README.md for instructions on contributing SVGs). this would have to target `3.2.x` branch.

OK, I will submit a PR
