### ISSUE TITLE
Publisher Mono or Flux onErrorContinue raised "No transaction in context" 

### ISSUE THREAD

**Issue by lizecn** [reactor/reactor-core#1987]
Starting from spring-boot 2.2.0.RELEASE, the publisher like Mono or Flux, onErrorContinue raised 
"No transaction in context" , but i never used or declared any transaction manager.
same code compared with spring-boot 2.1.10.RELEASE, onErrorContinue not raised.

##pseudo code 
@Slf4j
@RestController
public class RabbitmqRest {
  @Autowired OrderRepo orderRepo;
  @GetMapping("/order/get")
  public Mono<CmaOrder> getMono() {
    return orderRepo
        .findById("xxxxxxxx")
        .flatMap(
            order -> {
              log.info(JSON.toJSONString(order));
              return Mono.just(order);
            })
        .onErrorContinue(
            (e, obj) -> {
              log.error("rest on error continue : " + e.getMessage());
            });
  }
}

## Expected Behavior
 log.error("rest on error continue : " + e.getMessage());  not raised 
## Actual Behavior
log.error("rest on error continue : " + e.getMessage());  raised 

## Possible Solution
downgrade to spring boot  2.1.10.RELEASE

## Your Environment
openJdk 11 

* Reactor version(s) used:
* Other relevant libraries versions (netty):
* JVM version (openjdk11):
* OS and version (win10`):

**Comment by DavidDionise** [comment]
I'm getting the same behavior

**Comment by simonbasle** [comment]
There is no concept of transaction in Reactor. The handler in `onErrorContinue` being invoked seem to indicate that a step upstream of it raises that exception (probably the Spring Data repository). Please investigate with the Spring Boot / Spring Data teams.

PS: I would challenge whether or not `onErrorContinue` is really the only alternative here, btw (it should always be a last resort IMHO, as opposed to eg. splitting a flux with a flatMap and wrapping each inner with an `onErrorContinue`)
