### ISSUE TITLE
Scheduler.immediate() behavior is different from my expectation.

### ISSUE THREAD

**Issue by hojongs** [reactor/reactor-core#1994]
I tested Scheduler.immediate() with publishOn.
And the result is different from my expectation.

It is Scheduler.immedate() documentation.

> Executes tasks on the caller's thread immediately.

Or from Reference documentation.

> The current thread (Schedulers.immediate()).

## Expected Behavior

```
I 1 elastic-2
II 1 main
I 2 elastic-2
II 2 main
I 3 elastic-2
II 3 main
...
```
When I called Flux.subscribe() on "main" thread, It's my expected behavior.
The ordering can be changed.

## Actual Behavior

```
I 1 elastic-2
II 1 elastic-2 // This point, different from my expectation. should be main I think
I 2 elastic-2
II 2 elastic-2 // and also all points including "II"
I 3 elastic-2
II 3 elastic-2
I 4 elastic-2
II 4 elastic-2
I 5 elastic-2
II 5 elastic-2
I 6 elastic-2
II 6 elastic-2
I 7 elastic-2
II 7 elastic-2
I 8 elastic-2
II 8 elastic-2
I 9 elastic-2
II 9 elastic-2
I 10 elastic-2
II 10 elastic-2
```

## Steps to Reproduce

```java
@Test
public void repoCase() {
    Flux.range(1,10)
        .publishOn(Schedulers.elastic())
        .doOnNext { println("I $it ${Thread.currentThread().name}") }
        .publishOn(Schedulers.immediate())
        .doOnNext { println("II $it ${Thread.currentThread().name}") }
        .subscribe()
}
```

## Confim that it happens by immediate() and not happens by single()
I compared the result above with this case to confirm that it happens by immediate().
I used Scheduler.single(), alternative to immediate().

```java
@Test
public void repoCase() {
    Flux.range(1,10)
        .publishOn(Schedulers.elastic())
        .doOnNext { println("I $it ${Thread.currentThread().name}") }
        .publishOn(Schedulers.single()) // changed here! used single()
        .doOnNext { println("II $it ${Thread.currentThread().name}") }
        .subscribe()
}
```

```
I 1 elastic-2
I 2 elastic-2
I 3 elastic-2
I 4 elastic-2
I 5 elastic-2
II 1 single-1 // It is working good. pushed data by single scheduler
I 6 elastic-2
I 7 elastic-2
II 2 single-1
I 8 elastic-2
II 3 single-1
II 4 single-1
I 9 elastic-2
II 5 single-1
I 10 elastic-2
II 6 single-1
II 7 single-1
II 8 single-1
II 9 single-1
II 10 single-1
```

## Your Environment

JDK 8

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`):
* OS and version (eg `uname -a`):

**Comment by simonbasle** [comment]
You misunderstood what the caller is in this case. The first `publishOn` switches all signals to the `elastic` scheduler, so for the second `publishOn` the "caller" is the elastic scheduler. There is no way to go back to `main` once you've left it, since `main` is not an `Executor` and thus operators like `publishOn` have no mean of submitting tasks to it.

**Comment by simonbasle** [comment]
I just published a blog post that could clarify things for you, @hojongs: https://spring.io/blog/2019/12/13/flight-of-the-flux-3-hopping-threads-and-schedulers

**Comment by hojongs** [comment]
Thank you for your reply and blog post. It was very useful for me.

> Schedulers.immediate() can be used as a null object for when an API requires a Scheduler but you don’t want to change threads

It's very obvious about when to use immediate()
on the contrary to this, I think Reference document and Javadoc give ambiguous information about that.
* About when to use immediate() (as a null object)
* About what does that mean correctly `caller's thread` and `current thread` (the thread that `processing` operator chain, not the thread that `created` operator chain)

So, How about add these information into reference doc?
@simonbasle 
Thank you for your comment, again.

**Comment by simonbasle** [comment]
I have opened a PR to add some small amount of clarification to the docs
