### ISSUE TITLE
Mono should handle subscriber (Consumer) exceptions with provided exception handler

### ISSUE THREAD

**Issue by create1st** [reactor/reactor-core#1995]
Exceptions thrown by subscriber (**Consumer**) are propagated to error handler defined in **Flux.subscribe**, yet they are re-thrown with **onErrorDropped** once we use **Mono**. This causes inconsistent behavior when using **Flux** and **Mono** respectively.
Moreover, if we extend **BaseSubscriber** and pass it to Mono.subscribe then exceptions are handled as expected.

## Expected Behavior
Error handler in Mono.subscribe should handle exceptions thrown by subscriber.
## Actual Behavior
Test cases attached. All tests should pass as semantically they are identical.

## Steps to Reproduce
```java
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

public class SubscriberTest {
    private static Logger LOG = LoggerFactory.getLogger(SubscriberTest.class);

    @Test
    public void monoHandlingSubscriberError() {
        Mono
                .just("test")
                .subscribe(x -> {
                    throw new IllegalStateException();
                }, e -> LOG.error("Handler", e));
    }

    @Test
    public void fluxHandlingSubscriberError() {
        Flux
                .just("test")
                .subscribe(x -> {
                    throw new IllegalStateException();
                }, e -> LOG.error("Handler", e));
    }

    @Test
    public void monoHandlingSubscriberErrorWhenBaseSubscriber() {
        Mono
            .just("test")
            .subscribe(new BaseSubscriber<String>() {
                @Override
                protected void hookOnNext(String value) {
                    throw new IllegalStateException();
                }

                @Override
                protected void hookOnError(Throwable e) {
                    LOG.error("Handler", e);
                }
            });
}
} 
```

## Your Environment
* Reactor version(s) used: 3.3.1.RELEASE
* JVM version (`javar -version`): 1.8.0_202-release-1483-b58 amd64
* OS and version (eg `uname -a`): Windows Version 6.1 (Build 7601: SP1)

**Comment by simonbasle** [comment]
On a `Mono`, the `onNext` implies an `onComplete`, ie a successful completion. This drop stems from the fact that at this point the `Mono` is considered complete, so no `onError` is valid. The case of the lambda subscriber is a bit more fuzzy though. @smaldini any opinion?

**Comment by donmarjanus** [comment]
`onNext` does not imply anything, even in `Mono`.
Reference says: `A Mono<T> is a specialized Publisher<T> that emits at most one item and then (optionally) terminates with an onComplete signal or an onError signal.`

But this is irrelevant anyway, since there's no `onError` signal coming from upstream.
Instead, the `Subscriber` fails, when processing `onNext` signal by throwing an Exception. In reactive streams this is not allowed (Subscriber's rule no.13), but this is where reactor comes into play so we can implement `Consumer<T>` and signal failures by throwing Exceptions.

Why should we try-catching Exceptions inside `Consumer<T>` passed to `Mono.subscribe` and having errorHandler to deal with upstream errors at the same time?

**Comment by create1st** [comment]
As a temporary WA we recommend to wrap Consumer and error Consumer with an adapter to proper Subscriber implementation. The drawback is that you don't have an access to returned Disposable if you need one.

```java
import java.util.function.Consumer;

import org.reactivestreams.Subscriber;

import reactor.core.publisher.BaseSubscriber;
import reactor.util.annotation.Nullable;

public class SecureSubscriber<T> extends BaseSubscriber<T> {
    private final Consumer<? super T> consumer;
    private final Consumer<? super Throwable> errorConsumer;

    public SecureSubscriber(Consumer<? super T> consumer, Consumer<? super Throwable> errorConsumer) {
        this.consumer = consumer;
        this.errorConsumer = errorConsumer;
    }

    @Override
    protected void hookOnNext(T value) {
        consumer.accept(value);
    }

    @Override
    protected void hookOnError(Throwable throwable) {
        errorConsumer.accept(throwable);
    }

    public static <T> Subscriber<T> of(@Nullable Consumer<? super T> consumer, Consumer<? super Throwable> errorConsumer) {
        return new SecureSubscriber<T>(consumer, errorConsumer);
    }
} 
```
and supporting test case

```java
@Test
public void monoNotHandlingSubscriberError() {
    Mono
            .just("test")
            .subscribe(SecureSubscriber.of(x -> {
                throw new IllegalStateException();
            }, e -> logger.error("Handler", e)));
} 
```

**Comment by simonbasle** [comment]
Note the `BaseSubscriber` is `Disposable`, so what you can do is use `subscribeWith`:

```java
Disposable d = Mono.just("test")
    .subscribeWith(SecureSubscriber.of(x -> {
                throw new IllegalStateException();
            }, e -> logger.error("Handler", e)));

d.dispose();
```

**Comment by simonbasle** [comment]
I think 3.4.0 is a good milestone to fix that inconsistency, wdyt?
cc @reactor/discuss
