### ISSUE TITLE
Provide possibility to limit rate by quantity per time

### ISSUE THREAD

**Issue by ivyazmitinov** [reactor/reactor-core#2000]
## Motivation
When integrating with external APIs, there is often limits like "one request per minute". With the reactor it would be extremely useful to limit the calls to such API by limiting `Flux<ApiRequest>` with according operator.
There might be other use-cases, when it would be useful to limit quantity of processed object in period of time

## Desired solution
Code might look like this:

```java
   Flux.generate(() -> 0, (s, sink) -> {
            sink.next(s);
            return s++;
        }).limitRate(5, Duration.ofMinutes(1))
            .subscribe(o -> {
                System.out.println("Got 5 ints per minute");
            });
```

## Considered alternatives
We came up with custom implementation of such operator and using it via `transformDeferred`:

```java
        Flux.generate(() -> 0, (s, sink) -> {
            sink.next(s);
            return s++;
        }).transformDeferred(flux -> FluxUtil.limitRate(flux, 5, Duration.ofMinutes(1)))
            .subscribe(o -> System.out.println("Got 5 ints per minute"));
```

**Comment by bsideup** [comment]
Have you considered using Resilience4j?
https://resilience4j.readme.io/docs/examples-1#section-decorate-mono-or-flux-with-a-ratelimiter

**Comment by ivyazmitinov** [comment]
@bsideup 
I have not, thanks for the insight. 
Anyway, it would be nice to have such functionality out of box, as it is with the RetrySpec, which was incorporated from `extra` in one of recent releases.
