### ISSUE TITLE
FlatMap switches the response thread

### ISSUE THREAD

**Issue by shlomishem** [reactor/reactor-core#2003]
## Actual Behavior
I tried simple reactive code:
```
Flux.fromStream(Stream.iterate(0, i -> i + 1))
                    .flatMap(i -> Mono.just(i)
                                    .doOnNext(j -> printThread(j, "before delay"))
                                    .delayElement(Duration.ofSeconds(2))
                                    .doOnNext(j -> printThread(j, "after delay"))
                            , 5)
                    .doOnNext(j -> printThread(j, "after flat"))
                    .subscribe();
```
The output is:
...
1 after delay parallel-2
0 after delay parallel-1
1 after flat parallel-2
2 after delay parallel-3
3 after delay parallel-4
5 before delay parallel-2
0 after flat parallel-4
4 after delay parallel-1
**2 after flat parallel-4
3 after flat parallel-4
4 after flat parallel-4
6 before delay parallel-4
7 before delay parallel-4
8 before delay parallel-4
9 before delay parallel-4**
...

We can see that all elements moved to thread "parallel-4" after the flatMap operation.

## Expected Behavior
I don't know if it's by-design, but I would expect the elements to continue on the same thread they arrived.
Especially when this thread pulls the new elements into the flatMap:

> 6 before delay parallel-4
> 7 before delay parallel-4
> 8 before delay parallel-4
> 9 before delay parallel-4

* Reactor version(s) used: 3.3.0.RELEASE

**Comment by simonbasle** [comment]
This is by design: you instruct `flatMap` to have a `concurrency` of 5, so it will start subscribing up to 5 `Mono` derived from the stream. Once one of these `Mono` completes, `flatMap` will _replenish_ by requesting a new source element from the stream then derive the `Mono` and subscribe to it. **This operation is done on the `Thread` on which the previous `Mono` completed**, hence the `parallel-4`.

**Comment by shlomishem** [comment]
@simonbasle I really appreciate your reply.

> Once one of these Mono completes, flatMap will replenish.. This operation is done on the Thread on which the previous Mono completed

In my example, **0** finished with `parallel-1` before **3** but it continued with `parallel-4`.
Also, performance wise, isn't it better that each finished thread, will continue with the new element right away. 
In the example above, 9 needs to wait for the subscription of 6,7,8, because all happens on the same thread.
I'm asking because I encountered performance issues when setting high concurrency.
