### ISSUE TITLE
OverflowStrategy seems to have no effect

### ISSUE THREAD

**Issue by straumat** [reactor/reactor-core#2013]
## Expected Behavior
I created a Flux that procudes continuously a new interger value. I have a subscriber running in its own thread but who is slower (.publishOn(single())). By choosing a specific strategy (DROP or LATEST), I expect the subscriber to not receive all integers.

## Actual Behavior
No matter what strategy I use (LATEST or DROP), I always get the same result :

``` 
*** Received 1 with thread single-1
>>> Generated 1 with thread main
>>> Generated 2 with thread main
>>> Generated 3 with thread main
>>> Generated 4 with thread main
>>> Generated 5 with thread main
>>> Generated 6 with thread main
>>> Generated 7 with thread main
>>> Generated 8 with thread main
>>> Generated 9 with thread main
*** Received 2 with thread single-1
*** Received 3 with thread single-1
*** Received 4 with thread single-1
*** Received 5 with thread single-1
*** Received 6 with thread single-1
*** Received 7 with thread single-1
*** Received 8 with thread single-1
*** Received 9 with thread single-1

``` 
## Steps to Reproduce
```java
	@Test
	@DisplayName("test")
	public void workingFlux() throws InterruptedException {
		CountDownLatch latch = new CountDownLatch(1);

		Flux<Integer> IntGenerator = Flux.create(e -> {
			AtomicInteger iteration = new AtomicInteger(1);
			while (iteration.intValue() < 10) {
				int value = iteration.getAndIncrement();
				e.next(value);
				if (value < 10) {
					System.out.println(">>> Generated " + value + " with thread " + Thread.currentThread().getName());
				}
			}
		}, FluxSink.OverflowStrategy.DROP);

		IntGenerator.publishOn(single())
				.subscribe(new Subscriber<Integer>() {
					private Subscription s;

					@Override
					public void onSubscribe(final Subscription subscription) {
						s = subscription;
						s.request(1);
					}

					@Override
					public void onNext(final Integer integer) {
						System.out.println("*** Received " + integer + " with thread " + Thread.currentThread().getName());
						try {
							Thread.sleep(10000);
						} catch (InterruptedException e) {
							e.printStackTrace();
						}
						s.request(1);
					}

					@Override
					public void onError(final Throwable throwable) {

					}

					@Override
					public void onComplete() {

					}
				});

		latch.await(120L, TimeUnit.SECONDS);
	}
```
## Your Environment

* Reactor version(s) used: Bismuth-RELEASE
* Other relevant libraries versions (eg. `netty`, ...): Spring boot 2.2.2.RELEASE
* JVM version (`javar -version`): 1.11
* OS and version (eg `uname -a`): Ubuntu 19.10

**Comment by akarnokd** [comment]
`publishOn` has an internal buffer with 32 capacity by default so you are not generating enough items. Generate way more or limit the buffer via [another overload](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#publishOn-reactor.core.scheduler.Scheduler-int-).

**Comment by straumat** [comment]
@akarnokd  thanks a lot for this very quick reply.

I added `publishOn(single(), 1)` and seems the thread stopped receiving elements :(

Second point, from what you explained, I think maybe i'm not doing things the right way but I don't see in the documentation or in the books I bought how i should do that.

My sink will contiuously push the last bitcoin price retrieved from exchange and I want my subscriber, when he request a new value, to get the last bitcoin price pushed ? Am I doing it wrong ? Thank you.

**Comment by akarnokd** [comment]
Your example generates 10 items in a tight loop and then does nothing else while your consumer waits 10 seconds between requests.

Also your use case usually doesn't like any buffering so try using `delaySequence` with zero duration to avoid even the minimum buffer in `publishOn`.
