### ISSUE TITLE
Share Mono and Flux methods in a common interface

### ISSUE THREAD

**Issue by Sam-Kruglov** [reactor/reactor-core#2016]
I have a UI that performs an async operation on the backend when you click a button. This async operation, of course, uses the glorious reactor project. I want to disable the button for the time of that operation, so I call `doOnTerminate { updateUi { isEnabled = true } }` on it.
I want to do it for all my buttons, so I created a function for reactive button but some buttons use `Mono`, some use `Flux`, so this function accepts a `CorePublisher` but it barely has any methods, so I suggest to extend it to all the methods of the same signature from both `Mono` and `Flux`.

## Motivation
I have to do this to achieve the async enabling:
```kotlin
if (this is Mono) {
    doOnTerminate { updateUi { isEnabled = true } }
            .subscribeOn(Schedulers.parallel())
            .subscribe()
} else {
    (this as Flux).doOnTerminate { updateUi { isEnabled = true } }
            .subscribeOn(Schedulers.parallel())
            .subscribe()
}
```

## Desired solution
Use the CorePublisher interface from https://github.com/reactor/reactor-core/pull/1527

## Considered alternatives
I could not extract this piece of code into a function and just copy-paste it everywhere but I personally don't like it.

**Comment by dfeist** [comment]
Relates to/duplicates https://github.com/reactor/reactor-core/issues/85.

See @akarnokd comments here.

**Comment by Sam-Kruglov** [comment]
Hmm, maybe we can skip methods that modify return type? Should be fine to share the `doOn*` methods

**Comment by Sam-Kruglov** [comment]
Just found out a way! :) 

```
interface Common<T> {
    fun filter(predicate: (T) -> Boolean): Common<T>
}

@Suppress("UNCHECKED_CAST")
class CommonUtil<T, C : Common<T>>(var common: C) {
    fun filter(p: (T) -> Boolean): CommonUtil<T, C> {
        common = common.filter(p) as C
        return this
    }
}

class First<T>(val thing: T) : Common<T> {
    override fun filter(predicate: (T) -> Boolean): First<T> {
        println(predicate(thing))
        return this
    }
}
```
As you can see below, type inference works fine
![Screenshot 2020-01-16 at 19 17 51](https://user-images.githubusercontent.com/23556336/72547226-e8c8a400-3894-11ea-8f02-d55cc8012891.png)

I would be OK using such a util

**Comment by simonbasle** [comment]
This is kotlin though 🙈 We have a Java 8 codebase and must cater to Java 8 first. I'm not convinced it is possible to create a similar util in Java and supporting it in Kotlin would yield all the impracticalities and drawbacks that @akarnokd highlighted in #85. 

Why not create two extension methods though, rather than an util function that takes a `Publisher`?

**Comment by simonbasle** [comment]
Duplicate of #85

**Comment by Sam-Kruglov** [comment]
@simonbasle what's that 🙈🙈🙈 about?
I didn't use anything Kotlin-specific, generics are super simple here. The same in java, works equally.

Common
```java
import java.util.function.Predicate;

public interface Common<T> {

    Common<T> filter(Predicate<T> predicate);
}
```

First
```java
import java.util.function.Predicate;

public class First<T> implements Common<T> {

    private final T thing;

    public First(T thing) {
        this.thing = thing;
    }

    @Override
    public First<T> filter(Predicate<T> predicate) {
        System.out.println("filter in first: " + predicate.test(thing));
        return this;
    }

    public T getThing() {
        return thing;
    }

    @Override
    public String toString() {
        return "First{" +
                "thing=" + thing +
                '}';
    }
}
```

Second
```java
import java.util.function.Predicate;

public class Second<T> implements Common<T> {

    private final T thing;

    public Second(T thing) {
        this.thing = thing;
    }

    @Override
    public Second<T> filter(Predicate<T> predicate) {
        System.out.println("filter in second: " + predicate.test(thing));
        return this;
    }

    public T getThing() {
        return thing;
    }

    @Override
    public String toString() {
        return "Second{" +
                "thing=" + thing +
                '}';
    }
}
```

```java
import java.util.function.Predicate;

@SuppressWarnings("unchecked")
public class CommonUtil<T, C extends Common<T>> {

    private C common;

    public CommonUtil(C common) {
        this.common = common;
    }

    public CommonUtil<T, C> filter(Predicate<T> predicate) {
        System.out.println("filter in common");
        common = (C) common.filter(predicate);
        return this;
    }

    public C getCommon() {
        return common;
    }

    @Override
    public String toString() {
        return "CommonUtil{" +
                "common=" + common +
                '}';
    }
}
```

usage:
<img width="1537" alt="Screenshot 2020-01-17 at 13 28 33" src="https://user-images.githubusercontent.com/23556336/72609341-46a8ca80-392d-11ea-8362-abda2294b243.png">

**Comment by Sam-Kruglov** [comment]
Also, don't see the extension methods viable since you'd have to do `instanceof` in there anyway

**Comment by simonbasle** [comment]
There's a high maintenance cost to pay for such a small convenience. The high number of methods that we would have to duplicate in `CommonUtils` associated to the boilerplate you _still_ have to write as a user, plus the incurred cost in dispatching.

For the kotlin extensions, what I was suggesting is something along the line of:

```kotlin

fun <T> Mono<T>.enableAsync(): Mono<T> = this.doOnTerminate { updateUi { isEnabled = true } }
        .publishOn(Schedulers.parallel())

fun <T> Flux<T>.enableAsync(): Flux<T> = this.doOnTerminate { updateUi { isEnabled = true } }
        .publishOn(Schedulers.parallel())

//usage:
    fun updateUi() {
        Mono.just("foo")
                .enableAsync()
                // we keep access to Mono-specific API:
                .flatMapMany { i -> Mono.just(i) }
                .subscribe()

        Flux.just("bar")
                .enableAsync()
                // we keep access to Flux-specific API:
                .count()
                .subscribe()
    }
```

**Comment by Sam-Kruglov** [comment]
I guess you do still have to wrap it into util. But what if we remove the util and just leave the methods in the `Common` that will return `Common`? You wouldn't be able to go back to the subclass without casting but that may be actually fine, for example, for my case:

```kotlin
fun doStuff(publisher: CorePublisher<*>){
    publisher.doOnTerminate { updateUi { isEnabled = true } }
                    .subscribeOn(Schedulers.parallel())
                    .subscribe()
}
```
No need to check if it's `Mono` or `Flux` and no need to know which one is it anyway!

**Comment by Sam-Kruglov** [comment]
Also, your extension example is fine actually but I still don't like that you have to copy-paste the code 2 times for each extension. 
In my case, my DSL accepts CorePublisher and calls the needed code on it, that's why it checks if mono or flux. 
In your case, you have to call the extension function before you pass it to the DSL.

**Comment by Sam-Kruglov** [comment]
@simonbasle could you, please, take a look at this approach?

**Comment by simonbasle** [comment]
@Sam-Kruglov for all the reasons stated above this is not on the top of my list, no
