### ISSUE TITLE
Publish without Subscribers silently drops items

### ISSUE THREAD

**Issue by swimmesberger** [reactor/reactor-core#2018]
It seems that if you publish a source (which effectively will be a hot source after publish) and connect that source so it subscribes to upstream - without subscribing to the FluxPublish items are dropped without notice.

In my example I have a source which I want to be subscribed to but which needs to be released manually (netty bytebuf). I have multiple consumers which can be from 0...N if I have one or more consumers everything works fine the consumers get the bytebuf, the bytebuf is released in each consumer and the refCount drops to zero. When I have NO consumers of the published source the items are still requested but no "onDiscard" callback is called where I could potentially clean things up.

I also expected that there is some documentation how publish behaves without any subscribers but unfortunately I couldn't find anything. 

## Expected Behavior
I expected that:
1.  Publish behaves in such a way that when there are no subscribers the item is dropped and the onDiscard callback is called
2. When there are no subscribers there is no demand so nothing is requested (but what should be done when something is requested but in the meantime subscribers are cancelled?)

## Actual Behavior
Publish seems to request 1 item at a time and silently drops that item when it's received

## Steps to Reproduce
```java
    ConnectableFlux<Integer> connectFlux = Flux.range(0, Integer.MAX_VALUE).doOnDiscard(Integer.class, i -> {
      System.out.println("Item discarded!");
    }).doOnNext(item -> {
      System.out.println("Requested item " + item);
    }).publish();
    connectFlux.connect();
```

## Possible Solution
Call the onDiscard hook when there are no subscribers in FluxPublish or provide a way to identify the case that there a no subscribers and items are lost.

## Your Environment
* Reactor version(s) used: reactor-core-3.3.1.RELEASE
* Other relevant libraries versions (eg. `netty`, ...): Netty
* JVM version (`javar -version`): 1.8.0_202-ea
* OS and version (eg `uname -a`): Windows 10 x64

**Comment by swimmesberger** [comment]
By further investigating the design of the publish operator it seems that it differentiates between:
- Initial State (no Subscription ever, item dropped, new item requested)
- Canceled State (there was at some point a subscription which was cancelled, item queued, no item requested)

So depending on if the publish is "fresh" (e.g. there was no subscription ever) or if the publish was subscribed to before but cancelled the behavior is very much different. In a perfect world the user should decide which behavior he wants.
There might be usecases for the later and for the former. Personally I like the Canceled behavior most because why should there be demand when in fact there is none. Using refCount is counter intuitiv because I maybe want a persistent pipeline subscription (when e.g. subscribing/unsubscribing is expensive in terms of reconnecting) but I want that the pipeline "halts" when there is no demand (no subscriptions to publish). This would allow us to e.g. subscribe to a hot source apply backpressure (e.g. drop) and ensure at this point that everything is dropped because there is no demand downstream (no subscribers to the publish). But currently when there never was a subscription to publish it seems that there is demand downstream even though there isn't and we have no way to handle the drops at this point.
Using the discard hook in FluxPublish will also not work because discard hooks are applied upstream but when there are no subscriptions to publish we have no downstream and therefore no hooks to call.
Using the onNextDropped hook seems to be also counter intuitiv because the event is not unexpected at this point (we requested it).
One "easy" fix would be to allow the possibility to pass a consumer to the FluxPublish which will be called in the initial case with the item that will be dropped but that feels kind of "hacky".
Would love to hear some thoughts about the reasoning behind all that and what might be the best solution for this. (@simonbasle)

**Comment by simonbasle** [comment]
Hi @swimmesberger,

This is intended behavior, with the distinction between cancellation case and early `connect()` (the goal of a `ConnectableFlux` is after all to let you subscribe all you need to subscribe before the `connect()` to upstream). This is all to support the variants of `publish` like `autoconnect(0)`, `refCount(x)`, etc...

See #1528 #1639 #1712 and #1715 for history
