### ISSUE TITLE
ReactorDebugAgent messes up with collectList return value

### ISSUE THREAD

**Issue by gmaiztegi** [reactor/reactor-core#2023]
Using `ReactorDebugAgent` changes the behaviour of the return value of `Flux.collectList()`. If I am not using the agent `Flux.empty().collectList()` will return `Mono.just(List.of())`, while if I am using the agent, it will return `Mono.empty()`.

## Expected Behavior
I would expect `Flux.empty().collectList()` to return `Mono.just(List.of())` without mattering if I am using the debug agent or not.

## Actual Behavior
If I am using the debug agent, the return value of that call will be `Mono.empty()`.

## Steps to Reproduce

Without the agent:

```java
  @Test
  void noAgent() {
    var empty = new EmptyFlux();
    var result = empty.value()
        .collectList();

    StepVerifier.create(result)
        .assertNext(res -> assertEquals(0, res.size()))
        .verifyComplete();
  }

  public static class EmptyFlux {
    public Flux<String> value() {
      return Flux.empty();
    }
  }
```

With the agent:

```java
  @Test
  void agent() {
    ReactorDebugAgent.init();
    var empty = new EmptyFlux();
    var result = empty.value()
        .collectList();

    StepVerifier.create(result)
        .verifyComplete();
  }

  public static class EmptyFlux {
    public Flux<String> value() {
      return Flux.empty();
    }
  }
```

Run the tests separately.

## Possible Solution
My knowledge of the library is not good enough to think about the cause and possible solutions :(

## Your Environment
I am using reactor-core, reactor-tools and reactor-test version 3.3.2 and I am executing the tests in JUnit 5.

* Reactor version(s) used: 3.3.2
* Other relevant libraries versions (eg. `netty`, ...): JUnit 5.5.2
* JVM version (`javar -version`): OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
* OS and version (eg `uname -a`): Darwin MBP073.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64 i386

**Comment by bsideup** [comment]
Thanks @gmaiztegi,

I was able to reproduce the bug, although it is not reactor-tools, but core:
```java
class EmptyFluxCallable extends Flux<String> implements Callable<String> {
	@Override
	public String call() {
		return null;
	}

	@Override
	public void subscribe(CoreSubscriber<? super String> actual) {
		Flux.<String>empty().subscribe(actual);
	}
}
List<String> result = new EmptyFluxCallable().collectList().block();

assertThat(result).isEmpty();
```

reactor-tools wraps every operator with `FluxOnAssembly`, and, in your case, it was `FluxCallableOnAssembly` that triggered the same issue with `Callable` handling.

I will provide a fix in a moment 👍

**Comment by gmaiztegi** [comment]
Thank you @bsideup. That was super quick 😄

**Comment by bsideup** [comment]
@gmaiztegi thanks for reporting! 👍
