### ISSUE TITLE
Support reading internally queued values in ReplayProcessor

### ISSUE THREAD

**Issue by TheSpiritXIII** [reactor/reactor-core#2032]
Request: Add a method to ReplayProcessor that returns a Boolean indicating the cache is empty or not.

## Motivation

My use-case: I am working on a feature that sends events to the user. Each event has an ID associated with it. When the user disconnects and reconnects, they pass the last event ID they recorded to my service. I was using flux.cache().filter() to handle this. When my last event ID is in the cache, I replay only from there and the user can catch up.

The problem is when the last event ID is no longer in the cache. This means that the user disconnected for a long period of time and they need to completely refresh their screen, so I was thinking of sending them a refresh event. At first I realized that I could do flux.take(1) and compare the event ID with the last event ID (since the event IDs are sequential, this is a single greater than check), and send the refresh event. This works... as long as the cache always has at least one entry, because otherwise the source is not hot anymore so the flux operations do not go through to send my refresh event.

## Desired solution

Prior Art: RxJava has several methods in their ReplayProcessor, including getValues() and hasValue()

http://reactivex.io/RxJava/javadoc/io/reactivex/processors/ReplayProcessor.html

For my use-case, I only need hasValue().

## Considered alternatives

N/A

## Additional context

N/A

**Comment by simonbasle** [comment]
With a planned rework of the `FluxProcessor` API and how processors are exposed, it is less clear whether or not it could happen anytime soon. However, we'll try to keep that usecase in mind when reworking the processor APIs.
