### ISSUE TITLE
When using Flux.replay(), sometimes messages are getting lost under high load

### ISSUE THREAD

**Issue by arunim29** [reactor/reactor-core#2035]
When using Flux.replay(), sometimes messages are getting lost under high load

## Expected Behavior

 The messages should not be dropped after replay() operator.

## Actual Behavior

Under huge loads, sometimes, the messages get dropped after replay() operator.

## Steps to Reproduce

I am using spring web-flux framework.

I am using UnicastProcessor as below to pass messages from http calls to sink as below.

```
      UnicastProcessor<String> processor = UnicastProcessor.create();
      FluxSink<String> sink = processor.sink(OverflowStrategy.BUFFER);
      Flux<String> postParserFlux = processor.compose(httpMessageParser);
      preparePostParserChain(postParserFlux).subscribe();
```

On each http call, I do sink.next(httpMsg.body()).

```
private Flux<String> preparePostParserChain(Flux<String> incomingFlux){

  ConnectableFlux<String> preprocessedFlux =
        incomingFlux
            .filter(preprocessor) - (1)
            .replay();

 Flux<String> flux1 = preprocessedFlux.compose(//some composer); -(2)

 Flux<String> flux2 = preprocessedFlux.compose(//some composer); -(3)

 preprocessedDataFlux.connect();

 return Flux.merge(flux1,flux2);
}
```

I have observed that under huge loads, some of the http messages reach step (1) but they do not reach steps (2) or (3). They are getting lost after replay().

This issue is reproduced intermittently. 

## Your Environment

* Reactor version(s) used: - 3.2.10.RELEASE
* Spring WebFLux - 5.1.8.RELEASE
* JVM version - 1.8.0_144

**Comment by simonbasle** [comment]
- Can you spot any pattern in the message that are lost? (eg. all towards the beginning, or from the same composer, or with certain common characteristics)
 - What are the composer doing? Have you observed similar loss with simplified or no composers?

**Comment by arunim29** [comment]
1. I am not able to spot any pattern in the messages that are lost.
2. The composer persists in the db. I have not tried with a simplified composer.
3. As I am using replay(), even if the connect() is afterwards, it should not matter right? Also, the messages are going till replay() operator. So, the sink is passing the messages downstream.

**Comment by arunim29** [comment]
The issue was not with .replay(). The flux was getting finished due to a runtime exception which was not handled. Thanks.
