### ISSUE TITLE
Add SwapSubscription utility similar to DeferredSubscription

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2036]
Close to a `DeferredSubscription` (the two classes should even share a common base), the `SwapSubscription` would maintain only one active wrapped subscription, but allows replacement of said subscription (and opt-in cancellation of the old one when replacing).

**Comment by simonbasle** [comment]
Came up during work on `retryWhenReset`, see #1978 and #1979

**Comment by akarnokd** [comment]
That sounds like a [subscription arbiter](https://github.com/reactor/reactor-core/blob/e6798f682f6713f79d527568c16b7f8b7aeefa1b/reactor-core/src/main/java/reactor/core/publisher/Operators.java#L1880).

**Comment by simonbasle** [comment]
@akarnokd pretty close to `MultiSubscriptionSubscriber`, except it is not a `Subscriber`. In that sense it is closer to `DeferredSubscription` (which can be swapped only once).

**Comment by simonbasle** [comment]
`MultiSubscriptionSubscriber` should indeed generally be preferred, with `produced(n)` tracking
