### ISSUE TITLE
Schedulers.enableMetrics() generates bad prometheus metric names.

### ISSUE THREAD

**Issue by delta50** [reactor/reactor-core#2047]
## Summary
When I added`Schedulers.enableMetrics()` to a spring boot project I found that the additional metrics created for prometheus had labels hat prometheus considers invalid. For example, `reactor.scheduler.id` is an invalid label:
```
# HELP actuator_executor_max  
# TYPE actuator_executor_max gauge
actuator_executor_max{name="parallel(2,\"parallel\")-0",reactor.scheduler.id="parallel(2,\"parallel\")",} 0.155661231
actuator_executor_max{name="elastic(\"elastic\")-0",reactor.scheduler.id="elastic(\"elastic\")",} 0.380598276
actuator_executor_max{name="elastic(\"elastic\")-1",reactor.scheduler.id="elastic(\"elastic\")",} 0.885305336
actuator_executor_max{name="parallel(2,\"parallel\")-1",reactor.scheduler.id="parallel(2,\"parallel\")",} 0.333886792
actuator_executor_max{name="elastic(\"elastic\")-2",reactor.scheduler.id="elastic(\"elastic\")",} 0.008797581
actuator_executor_max{name="boundedElastic(\"boundedElastic\",maxThreads=20,maxTaskQueued=100000,ttl=60s)-2",reactor.scheduler.id="boundedElastic(\"boundedElastic\",maxThreads=20,maxTaskQueued=100000,ttl=60s)",} 0.150838484
actuator_executor_max{name="boundedElastic(\"boundedElastic\",maxThreads=20,maxTaskQueued=100000,ttl=60s)-1",reactor.scheduler.id="boundedElastic(\"boundedElastic\",maxThreads=20,maxTaskQueued=100000,ttl=60s)",} 0.094686523
actuator_executor_max{name="boundedElastic(\"boundedElastic\",maxThreads=20,maxTaskQueued=100000,ttl=60s)-0",reactor.scheduler.id="boundedElastic(\"boundedElastic\",maxThreads=20,maxTaskQueued=100000,ttl=60s)",} 0.060910884
actuator_executor_max{name="boundedElastic(\"boundedElastic\",maxThreads=20,maxTaskQueued=100000,ttl=60s)-3",reactor.scheduler.id="boundedElastic(\"boundedElastic\",maxThreads=20,maxTaskQueued=100000,ttl=60s)",} 0.043105767
```

## Expected Behavior
The Schedulers.enableMetrics() metrics option should generate names that are valid for prometheus, such as: `reactor_scheduler_id`.

## Actual Behavior
The Schedulers.enableMetrics() metrics option is generating invalid names such as: `reactor.scheduler.id`.

**Comment by simonbasle** [comment]
@shakuzen I thought that Micrometer would translate the tag names to something valid for each metrics backend?

**Comment by delta50** [comment]
According to this: https://micrometer.io/docs/concepts#_tag_naming you are correct, however the scheduler metric does not seem to get renamed.

**Comment by shakuzen** [comment]
Could someone provide a minimal project to reproduce this behavior? Indeed tag names should be converted to the convention for the given backend, as long as they are registered in the canonical form.

**Comment by simonbasle** [comment]
@delta50 can you provide @shakuzen with a simple to reproduce case, or instructions? If I understand correctly:
 - bare new Spring Boot project with Reactive Web and Actuator starters
 - add micrometer prometheus dependency
 - call `Schedulers.enableMetrics()`
 - call `Scheduler s = Schedulers.newParallel(8)` or something similar, and submit a task (`s.schedule(() -> foo())`)

Is that about it?

**Comment by delta50** [comment]
Sure, I will try and get something put together this week.

**Comment by delta50** [comment]
So I didn't realize it at first, but the issue is actually due to some additional code we are using in our projects. We add the prefix `actuator_` to all the metric names coming out of spring actuator to prevent them from colliding with other metric sources in prometheus. This code seems to have an issue with the scheduler metric specifically. I have created an example here: [https://github.com/delta50/SchedulerMetricsBug](https://github.com/delta50/SchedulerMetricsBug)

This might just be an edge case in our renaming code that we have not encountered before. I just wanted to post the information here for completeness.
