### ISSUE TITLE
some doOnError handlers are not executed as they should with cache() and subscribe()

### ISSUE THREAD

**Issue by a701440** [reactor/reactor-core#2059]
The test code below fails on version 3.3.3 and succeeds on version 3.2.2

    @Test
    public void testErrors() throws Exception {
        AtomicInteger callbackCount = new AtomicInteger();
        TestPublisher<Boolean> testPublisher = TestPublisher.create();
        Mono<Boolean> mono1 = Mono.from(testPublisher).doOnError(e -> {
            callbackCount.incrementAndGet();
            System.out.println("Mono1 onError");
        }).cache(); // if cache is removed behavior changes

        Mono<Boolean> mono2 = mono1.doOnError(e -> {
            callbackCount.incrementAndGet();
            System.out.println("Mono2 onError");
        });
        
        mono1.subscribe(); // fails on 3.3.3, succeeds on 3.2.2
        //mono1.subscribe(v -> {}, e -> {}); // succeeds on 3.3.3
        
        mono2.subscribe();
        testPublisher.error(new RuntimeException("Test"));
        assertEquals(2, callbackCount.get());
    }

**Comment by a701440** [comment]
It appears that when ErrorCallbackNotImplemented is thrown it bypasses some downstream callbacks when cache() is present. When cache() is removed we have two full subscriptions at the root and the callbackCount is 3 as expected. When subscribe() has error callback it does not throw ErrorCallbackNotImplemented exception and downstream callbacks are executed as expected. It looks like this behavior has changed between versions 3.2.2 and 3.3.3. We have actual failures in the app when testing with 3.3.3 due to this effect.

**Comment by a701440** [comment]
This test fails on 3.3.3, succeeds on 3.2.2:
`    @Test
    public void testErrors() throws Exception {
        AtomicInteger callbackCount1 = new AtomicInteger();

        TestPublisher<Boolean> testPublisher1 = TestPublisher.create();
        Mono<Boolean> mono1a = Mono.from(testPublisher1).doOnError(e -> {
            callbackCount1.incrementAndGet();
        }).cache(); // if cache is removed behavior changes
        Mono<Boolean> mono1b = mono1a.doOnError(e -> {
            callbackCount1.incrementAndGet();
        });

        mono1a.subscribe();
        mono1b.subscribe();
        testPublisher1.error(new RuntimeException("Test1"));

        // Below is the code identical to the code above
        // except the subscribe call has an error handler
        // the number of the doOnError calls is different from above
        AtomicInteger callbackCount2 = new AtomicInteger();

        TestPublisher<Boolean> testPublisher2 = TestPublisher.create();
        Mono<Boolean> mono2a = Mono.from(testPublisher1).doOnError(e -> {
            callbackCount2.incrementAndGet();
        }).cache(); // if cache is removed behavior changes
        Mono<Boolean> mono2b = mono2a.doOnError(e -> {
            callbackCount2.incrementAndGet();
        });

        mono2a.subscribe(v -> {}, e -> {});
        mono2b.subscribe();
        testPublisher1.error(new RuntimeException("Test2"));

        assertEquals(callbackCount1.get(), callbackCount2.get());
    }
`

**Comment by simonbasle** [comment]
This seems to have been fixed in 3.4.0 since we do not throw the `ErrorCallbackNotImplemented` anymore.
