### ISSUE TITLE
VirtualTimeScheduler does not run scheduled tasks since 3.3.3.RELEASE

### ISSUE THREAD

**Issue by elefeint** [reactor/reactor-core#2060]
## Expected Behavior
`VirtualTimeScheduler` runs scheduled tasks at certain intervals.

## Actual Behavior
At version `3.3.3.RELEASE`, `VirtualTimeScheduler` runs the task once and never again, even though virtual time elapsed.

## Steps to Reproduce
With `io.projectreactor:reactor-test:3.2.15.RELEASE`, the following test passes. After updating to `3.3.3.RELEASE`, it hangs.

```
@Test
public void isolateIssue() {
	Scheduler.Worker subscriptionWorker = VirtualTimeScheduler.getOrSet().createWorker();
	List<String> source = Stream.of("first", "second", "third").collect(Collectors.toList());


	StepVerifier.withVirtualTime(() -> {
		EmitterProcessor<String> fluxEmitter = EmitterProcessor.create();

		subscriptionWorker.schedulePeriodically(() -> {
			if (source.size() > 0)
				fluxEmitter.onNext(source.remove(0));
			else
				fluxEmitter.onComplete();
		}, 0, 10, TimeUnit.MILLISECONDS);
		return fluxEmitter;
	})
			.expectNext("first")
			.expectNoEvent(Duration.ofMillis(10))
			.expectNext("second")
			.expectNoEvent(Duration.ofMillis(10))
			.expectNext("third")
			.expectNoEvent(Duration.ofMillis(10))
			.verifyComplete();
}
```

## Possible Solution
No solutions, but I suspect #2017 may have something to do with this.

**Comment by simonbasle** [comment]
Indeed, this is due to [this line](https://github.com/reactor/reactor-core/pull/2017/files#diff-b45f567b43fa5c691c798935dfe08a6aR222) in the aforementioned change.

we need to introduce a `VirtualTimeScheduler#getOrSet(boolean)` variant, and use that one with `true` parameter` in the above factory method.

**Comment by simonbasle** [comment]
`has-workaround`: use the 3 parameter variant of `withVirtualTime` with `VirtualTimeScheduler::get` and `Long.MAX_VALUE` as second and third parameters
