### ISSUE TITLE
FluxProcessors not unsubscribing from parent on complete/dispose

### ISSUE THREAD

**Issue by OliverGavin** [reactor/reactor-core#2069]
I am using an `EmitterProcessor` (`emitter`) to drain a `Flux` (`parent`) created using `Flux.generate` (never ending) but it isn't working as expected.
When I call `onComplete()` on the processor it completes and terminates. However the parent is not unsubscribed from.
I need the termination to close a resource in the `Flux.generate`.

Is this a bug? Otherwise, what is the expected way to be able to complete the processor and unsubscribe from the parent?

## Expected Behavior
`FluxProcessor` should unsubscribe from parent when `onComplete()` or `dispose()` are called on the processor.

## Actual Behavior
`FluxProcessor` does not unsubscribe from parent when `onComplete()` or `dispose()` are called on the processor.
The result is that one cannot rely on parent being terminated or the downstream cancellation propagating back to the parent.

## Steps to Reproduce
This is example shows the issue with a `TestPublisher`:

```java
@Test
public void test() {
  Flux<Integer> parent = TestPublisher.<Integer>create().flux()
    .doOnComplete(() -> System.out.println("parent doOnComplete"))
    .doOnTerminate(() -> System.out.println("parent doOnTerminate"))
    .doOnCancel(() -> System.out.println("parent doOnCancel"))
    .publish()
    .refCount();

  EmitterProcessor<Integer> processor = EmitterProcessor.create();
  parent.subscribe(processor);
  processor
          .doOnComplete(() -> System.out.println("subscriber doOnComplete"))
          .doOnTerminate(() -> System.out.println("subscriber doOnTerminate"))
          .doOnCancel(() -> System.out.println("subscriber doOnCancel"))
          .subscribe();

  processor.onComplete();
}
```

The output is:
```
subscriber doOnComplete
subscriber doOnTerminate
```

## Possible Solution
Keep a reference to the subscription disposable in the `FluxProcessor` which can then be disposed of when `onComplete()` or `dispose()` are called on the processor.

## Your Environment
* Reactor version(s) used: 3.2
* JVM version (`java -version`): 1.8.0_231

**Comment by bsideup** [comment]
Since you're calling `parent.subscribe(processor)`, isn't it your responsibility to dispose this subscription when needed?

/cc @simonbasle

**Comment by OliverGavin** [comment]
How would you propose I do that given that I want to complete the processor stream rather than cancel it by disposing the parent?

To me it would be intuitive if completing a processor would unsubscribe from the parent. Perhaps I'm using the wrong implementation for my use case which is pulling data indefinitely, but with a mechanism to complete and drain the stream when the service needs to tear down.

Right now the only way I can do this is to drain, cancel the parent and catch the cancellation exception in the processor subscription and complete the stream instead which is ugly and not intuitive.

One of the main advantages of using a Processor for me is being able to control it based on external events such as a shutdown trigger by calling `onComplete()`. To me, completing the processor is a very different thing to cancelling the parent.

My understanding of `.publish().refCount()` was that I didn't have to worry about disposing the subscription if there was nothing listening.
