### ISSUE TITLE
Mono.toFuture(): invocation of cancel after completion.

### ISSUE THREAD

**Issue by anuchandy** [reactor/reactor-core#2070]
We have a code like below which does the following:

1. Create a local file
2. Download contents to this file
3. If the subscription is canceled or there is an error we remove the possibly partially written file

```java
final String fileName = "myLocalFile.txt";
Mono<String> fileDownloadMono = Mono.using(() -> new PrintWriter(fileName, "UTF-8"),
        new Function<PrintWriter, Mono<String>>() {
            @Override
            public Mono<String> apply(PrintWriter printWriter) {
                // Download from network.
                System.out.println("Downloading from network");
                String downloadedContent = "hello";
                // write to local file
                System.out.println("Writing to local file");
                printWriter.write(downloadedContent);
                return Mono.just(fileName);
            }
        },
        printWriter -> {
            printWriter.close();
        })
        .doFinally(signalType -> {
            if (signalType == SignalType.ON_ERROR
                || signalType == SignalType.CANCEL) {
                System.out.println("Unable to complete download/write to file, deleting unfinished file.");
                (new File(fileName)).delete();
            }
        });
```

This works fine. The issue we're facing is when we convert this Mono to a Future like below:

```java
fileDownloadMono.toFuture();
```

`toFuture()` operator cancels the Mono as soon as the Mono completes, which result in the removal of successfully completed file.

Code in `toFuture()` operator that cancel the Mono is [here](https://github.com/reactor/reactor-core/blob/c6b75f2578ee5f201ac06add2239322cc5b7bfcd/reactor-core/src/main/java/reactor/core/publisher/MonoToCompletableFuture.java#L59).

**Comment by simonbasle** [comment]
Yeah it doesn't sound like this is needed at all for a `Mono` publisher. Note that it would be necessary if the `MonoToCompletableFuture` (which is a `Subscriber`) was subscribed to eg. a `Flux`...

What I can do to guide any potential future use of this subscriber with anything else than a `Mono` is to add a constructor parameter that drives whether or not to cancel in `onNext`. (and of course `Mono.toFuture()` would prevent such cancellation).

**Comment by anuchandy** [comment]
thank you @simonbasle!
