### ISSUE TITLE
Primitive Specialization

### ISSUE THREAD

**Issue by sirinath** [reactor/reactor-core#209]
Boxing computing overhead, memory overhead and GC overhead is not acceptable in some cases. So it it possible to provide primitive specialised versions?

**Comment by smaldini** [comment]
In these case you can use Stream API and combine them with an outer flow via `Flux.fromStream`.

**Comment by sirinath** [comment]
Unless you have a specialised version of all APIs there is no way to eliminate boxing. Without specialization in core and internal data structures there is no material benefit of a specialized API as boxing will be triggered any way internally.

**Comment by smaldini** [comment]
That doesn't need to alter a generic core nor reactive stream specified Subscriber<T>, it will need an orthogonal approach, and for low latency concern the java util Stream API will certainly perform better.
