### ISSUE TITLE
Emit a value after a Mono<Void> completes? 

### ISSUE THREAD

**Issue by Pojahn-Netent** [reactor/reactor-core#2094]
I have a REST-endpont in my Spring Boot application:

```java
@GetMapping(...)
public Mono<ResponseEntity<Void>>  someRestEndpoint(String authToken) {
    return authService.authenticate(authToken)
        .flatMap(playerId -> playerService.doStuffOnAuthenticatedUser(playerId)  //Returns Mono<Void>
            .map(aVoid -> ResponseEntity.noContent()))
        .switchIfEmpty(Mono.just(ResponseEntity.unauthorized()));
}
```

Since `doStuffOnAuthenticatedUser` returns Mono< Void >(which means a null value), the map to `noContent` is never executed and I always get unauthorized. 

Is there any suitable operators to handle these cases?

**Comment by bsideup** [comment]
Yes. Use `Mono#thenReturn`:
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#thenReturn-V-
