### ISSUE TITLE
Make ReactorDebugAgent available as a "real" javaagent

### ISSUE THREAD

**Issue by leonard84** [reactor/reactor-core#2098]
## Motivation

Our operations team only wants to have JREs running in production, and ByteBuddy needs a JDK to install correctly (at least on Java 8, although we are having issues on Java 11 as well).

In https://github.com/reactor/reactor-tools there was a plan mentioned to make this available as a "real" java agent.
> Limitations
> 
> Java 8 users must use JDK instead of JRE:
> https://bytebuddy.net/javadoc/1.9.12/net/bytebuddy/agent/ByteBuddyAgent.html#install--
> 
> We plan to relax this requirement in future versions by shipping a "real" Java agent you can attach with the -javaagent: JVM flag.

## Desired solution

A way to run on a JRE with `-javagent ...`

**Comment by bsideup** [comment]
Hi @leonard84,

I just submitted #2104 for it :)

**Comment by bsideup** [comment]
That said, we've received a number of reports that it works fine on some JRE 8. Perhaps ByteBuddy have relaxed the requirement (I need to check), so I'd suggest checking whether the current one works okay and use it instead, to make it simpler.

> ByteBuddy needs a JDK to install correctly (at least on Java 8, although we are having issues on Java 11 as well).

What kind of issues, btw? Since Java 9, there is an attachment api and ByteBuddy uses it. If you have an issue with both Java 8 and 9+ then it must be something else.

**Comment by bsideup** [comment]
@leonard84 the PR is merged now.

Consider trying it before the release (the implementation is identical to the latest release, just the `premain` method is added) by downloading the latest SNAPSHOT:
https://repo.spring.io/snapshot/io/projectreactor/reactor-tools/3.3.5.BUILD-SNAPSHOT/

**Comment by Chr3is** [comment]
@bsideup the latest snapshot was successfully tested with:

`-javaagent:reactor-tools-3.3.5.BUILD-20200407.112022-14.jar`

Java-Version:
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```

Thanks for handling this request so fast! 👍

**Comment by bsideup** [comment]
@Chr3is thanks a lot for trying! 👍

**Comment by leonard84** [comment]
@bsideup if it was unclear my 👍 also meant that it worked for me.

**Comment by bsideup** [comment]
@leonard84 thanks for clarifying 👍 It will be included in the next week's release :shipit:
