### ISSUE TITLE
Question: shared context

### ISSUE THREAD

**Issue by msoub** [reactor/reactor-core#210]
Hello,

I wanted to know what is the best way to share a context between the threads created by reactor? For example, in my web app I'd like to have access to some security information from the request.

Thank you for your help

**Comment by smaldini** [comment]
In short there are a few patterns some of them explained in #117. It's not usually ideal especially when starting getting with this programming model. 
The better fix for this would require more thoughts and coordination with Spring Framework team to make sure we experience first hand these issues. In effect there are number of areas with these needs including security and tracing.

**Comment by smaldini** [comment]
I think we can do for now is provide more guidance over this and this is connected to #77 and the general story around our guides. We have just started something so expect us to include this in a draft soonish.

**Comment by simonbasle** [comment]
This will be solved by resolving #117 (work in progress in #447)
