### ISSUE TITLE
Out of box support for .flatMap(x-> reactiveAction(x).thenReturn(x))

### ISSUE THREAD

**Issue by bmd007** [reactor/reactor-core#2108]
During some reactive orchestration, I stumbled upon a pattern for which I'm wondering if there is any out of box support? 

So I want the code below:
```
    Mono.just("hello")
        .flatMap(hello -> reactiveAction(hello).thenReturn(hello))
        ..
        .;

```
to be turned into something like:
  ```
  Mono.just("hello")
        .coolOperation(this::reactiveAction)
        ..
        .;   
```

I can not use doOnNext since what I want to do inside reactiveAction is not a side effect. 
and reactive action is:
```
    Mono<Integer> reactiveAction(String text){
      return ....
    }

```

**Comment by simonbasle** [comment]
Your [stackoverflow question](https://stackoverflow.com/questions/61077400/how-to-avoid-flatmapx-reactiveactionx-thenreturnx) was the correct place to ask this, we try to limit github issues for bug reports and feature request discussions. I'll answer there.

**Comment by martin-tarjanyi** [comment]
Isn't this a feature request, though?

**Comment by simonbasle** [comment]
>  I'm wondering if there is any out of box support?

that was formulated more as a question, but yeah you're right could have been both. the SO question was answered first, so let's make that the single source of truth for this inquiry ;)
