### ISSUE TITLE
sink.onRequest is not called

### ISSUE THREAD

**Issue by a701440** [reactor/reactor-core#2113]
Trying to capture initial request count as a "parameter" in Mono creation chain
without passing it through the closure/context of some kind.
sink.onRequest does not seem to be called. Not sure how to rewrite this "properly".

```
Mono<Long> m = Mono.just(2);
m = m.flatMap(num -> Mono.create(sink -> {
  sink.onRequest(count -> {
    sink.success(num * count);
  }
}));
m.subscribe(res -> { assertEquals(4, res); }, e -> {}, () ->(), s->{s.request(2);});
```

**Comment by bsideup** [comment]
@a701440 could you please explain what are your trying to achieve?

**Comment by a701440** [comment]
I want to incorporate the initial requestNumber for the subscription as a parameter into the mono, something similar to what could be done with subscriber context or with a closure. Hypothetically speaking let's say mono represents a db request, I want to send down the number of rows to request using the subscription parameter.

**Comment by a701440** [comment]
Something similar to this test I guess:

    @Test
    public void testReuestNum() {
        AtomicLong requestCount = new AtomicLong();
        Mono.just(2).doOnRequest(rn -> requestCount.set(rn)).map(n -> n * requestCount.get())
                .subscribe( v -> {
                    assertEquals(4L, v.longValue());
                }, e-> {}, () -> {}, s -> {
                    s.request(2);
                });
    }

**Comment by simonbasle** [comment]
Note that the request that your `create` gets from within the `flatMap` is different from the one the main sequence gets. By default `flatMap` makes an unbounded (`Long.MAX_VALUE`) request to the inner `Mono`/`Flux` generated by the function.
Generally speaking, most operators can potentially modify the `request` signals (think eg. a buffer(3): being requested for 10 buffers translates to requesting 30 elements), which makes what you're trying to achieve a bit difficult. Especially, if you're making assumptions about the request pattern then I think you would need to own the whole pipeline (ie make sure no operator in the chain messes with the request, which by itself is hard to get)

**Comment by a701440** [comment]
I understand how operators can change the requestNumber as it's propagated. I guess my point is that for Mono produced by Mono.create there is no "legal" way to get the request count from the downstream at all, you have to hand-code it outside of the pipeline. Existence of MonoSink.onRequest implies that it would be called, but it is not called and that part feels like an ommision.

**Comment by simonbasle** [comment]
mhmh I cannot reproduce the fact that `onRequest` is not called at all, I answered assuming it was called with the seemingly wrong value, because executing your code gives me:

```
Expecting:
 <-2L>
to be equal to:
 <4L>
```

**Comment by a701440** [comment]
Try this test, it actually never completes.

    @Test
    public void testMono() throws Exception {
        Mono<Long> m = Mono.just(2L);
        m = m.flatMap(num -> Mono.create(sink -> {
            System.out.println("subscribe");
            sink.onRequest(count -> {
                System.out.println("onRequest " + count);
                sink.success(10L);
            });
        }));
        m.subscribe(
                res -> { System.out.println("result " + res); },
                e -> { System.out.println("error " + e);},
                () -> { System.out.println("complete");},
                s->{s.request(2); System.out.println("subscription");}
        );
        Thread.sleep(1000);
    }

**Comment by simonbasle** [comment]
tested with both 3.2.17 and 3.3.5 snapshots and it completes and outputs
```
subscription
subscribe
onRequest 9223372036854775807
result 10
complete
```

**Comment by a701440** [comment]
I am still on version 3.2.2 due to the issue https://github.com/reactor/reactor-core/issues/2059
I should have checked on the latest version.
