### ISSUE TITLE
FluxIterable.subscribe(CoreSubscriber<? super T> actual) fails since it calls iterable() 2 times

### ISSUE THREAD

**Issue by bratwurzt** [reactor/reactor-core#2117]
We are using apache ignite with reactor-core and since upgrade 3.2.12 to 3.3.3, with commit 73becb9d2dd061031025c0e69798f0196253bd40 in method in `FluxIterable.subscribe(CoreSubscriber<? super T> actual)` call `FluxIterable.checkFinite(iterable)` was added before `it = iterable.iterator();`.

The problem arises with ignite's `org.apache.ignite.internal.processors.cache.QueryCursorImpl.iterator` call, which may be called only once. Let me explain:
1. `FluxIterable.checkFinite(iterable)` calls `iterable.spliterator().hasCharacteristics(Spliterator.SIZED)`
2. that calls `Spliterators.spliteratorUnknownSize(iterator(), 0)` which
3. calls ignite's iterator() call and that "uses it up" for subsequent call of `it = iterable.iterator();` in `FluxIterable.subscribe(CoreSubscriber<? super T> actual)`

which then fails in ignite code with an error message of "Iterator is already fetched or query was cancelled."

## Expected Behavior
Should call iterator only once

## Actual Behavior
calls iterator() call 2 times

## Steps to Reproduce
Use any iterator() that my be called only once.

## Your Environment
Windows 10
JDK 1.8.0_172
ignite-core 2.8.0
reactor-core 3.3.3

If this is a normal scenario and ignite team should fix it, please comment and close and sorry for wasting your time.

**Comment by bsideup** [comment]
> Use any iterator() that my be called only once.

I don't think this conforms to the `Iterable` contract.

As a workaround of the Ignite's behaviour, you can "cache" the result of the `iterator()` call:
```java
Iterator<T> iterator = cursor.iterator();
return Flux.fromIterable(() -> iterator)
```

**Comment by claszz** [comment]
@bsideup 
I am also facing same issue. Just wanted to clarify what do you mean by "you can 'cache' the result of the iterator() call"
`Iterator<T> iterator = cursor.iterator();
return Flux.fromIterable(() -> iterator)`

Does this will iterator over Ignite cursor first and load all data into memory and then pass result on to Flux or it will in-directly invoke ignite cursor and works in reactive way, fetching data in batches or pages.

I have millions of records from Ignite query, if it is caching all records, then eventually may result into OutOfMemoryException as all data is loaded into memory.

**Comment by chemicL** [comment]
The situation should improve with #3297 improvements by @OlegDokuka
