### ISSUE TITLE
Make Context more accessible

### ISSUE THREAD

**Issue by martin-tarjanyi** [reactor/reactor-core#2118]
Currently [`Context`](https://projectreactor.io/docs/core/release/api/reactor/util/context/Context.html) can be accessed in a few ways. If I need it in the middle of the pipeline the options are cumbersome and for new users difficult to discover. I would argue that some new operators could make the API more user-friendly. 

## Motivation
`Mono.deferWithContext` is a nice addition if you need to access the Context at the beginning of the pipeline. I think it would be nice to have something similar when `Context` is needed to be accessed in intermediate operators.

## Desired solution
Not sure what is the best approach here. The solutions I can think of: 

1. Add overloaded versions of `doOnNext`, `doOnComplete`, `doOnError`, `doOnTerminate` which receive `BiConsumer` or `Consumer` (depending on the operator) which beside the error/next/nothing also makes the `Context` available. 

2. Create `...withContext` counterparts for all of these operators. This one is probably more consistent with the recent addition of `deferWithContext` operator.

Example:
```java
Mono.just("hello")
    .doOnErrorWithContext((error, context) -> {
            // use context here
    });
```

## Considered alternatives
The current ways to do this (as far as I know):

1. This is the one which is suggested in the reference docs. I found it a bit verbose for simple use cases and it's not possible (or just quite tricky) to use this for error/completion cases.
```java
Mono.just("hello")
    .flatMap(x -> Mono.subscriberContext()
                      .doOnNext(ctx-> {/*something with context*/})
                      .thenReturn(x));
```

2. This one I found on Stackoveflow in the past (now it is also present in the reference in the MDC section of the appendix). It works for all next/error/completion cases. However, I'm not sure if this the primary use case for this operator, which makes it difficult to discover. It also has some boilerplate which would be nice to skip.
```java
Mono.just("hello")
    .doOnEach(signal -> {
        Context context = signal.getContext();

        if (signal.isOnError()) // depending on when we want to log/do something
        {
            Throwable throwable = signal.getThrowable();
            // use context here
        }
    });
    }
```

## Additional context
I also have a use case where I want to trigger an action only on the first event (next or error or complete) and I need access to the `Context`. Currently, I do this with `doOnEach` and an `AtomicBoolean`. I understand it's probably not a common use case, but would be nice to have something in the API for this, as well. I think `doOnTerminateWithContext` would fit the bill.

**Comment by bsideup** [comment]
Since Reactor 3.3, there is also a very easy way to wrap any operator into context-accessible:
```java
myFlux
	.as(flux -> Flux.deferWithContext(context -> {
		return flux.doOnNext(i -> /* something with context */);
	}));
```

> 1. Add overloaded versions of doOnNext, doOnComplete, doOnError, doOnTerminate which receive BiConsumer or Consumer (depending on the operator) which beside the error/next/nothing also makes the Context available.

Since they can be wrapped with `deferWithContext`, I am not sure adding overloaded versions makes sense

> 2. Create `...withContext` counterparts for all of these operators.

That would be a nightmare to maintain and will explode the already big number of operators

**Comment by karim789** [comment]
> Since Reactor 3.3, there is also a very easy way to wrap any operator into context-accessible:
> 
> myFlux
> 	.as(flux -> Flux.deferWithContext(context -> {
> 		return flux.doOnNext(i -> /* something with context */);
> 	}));
> > 1. Add overloaded versions of doOnNext, doOnComplete, doOnError, doOnTerminate which receive BiConsumer or Consumer (depending on the operator) which beside the error/next/nothing also makes the Context available.
> 
> Since they can be wrapped with `deferWithContext`, I am not sure whether adding overloaded versions makes sense
> 
> > 2. Create `...withContext` counterparts for all of these operators.
> 
> That would be a nightmare to maintain and will explode the already big number of operators

Problem is that this is really ugly and cumbersome and it took me a long time to discover how to do that.
