### ISSUE TITLE
Consider cancelling the Subscription upon error in LambdaSubscriber

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#212]
This actually both affects `LambdaSubscriber` and `LambdaFirstSubscriber` in reactor.

In RxJava 2, a non-fatal error during the execution of the user-provided `onSubscribe` or `onNext` callback triggers a cancellation of the `Subscription` (eg. [here in onNext](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/subscribers/LambdaSubscriber.java#L64)).

**Comment by smaldini** [comment]
For a slight overhead it could be just safer to do that.
