### ISSUE TITLE
Publish percentiles metrics

### ISSUE THREAD

**Issue by n3wtron** [reactor/reactor-core#2133]
## Motivation
Expose the timer percentiles metrics (https://micrometer.io/docs/concepts#_histograms_and_percentiles)

## Desired solution
Having a method like `metricsWithPercentiles(Double ... percentiles)` that will expose the desired percentiles on the Timers.

## Considered alternatives
Modifying the current `metrics` method adding the vararg maintaining the retro compatibility

## Additional context
I've created this branch with the modifications & tests & docs :
https://github.com/n3wtron/reactor-core/tree/feature/micrometer-percentiles

## Workaround
Using the Micrometer filter functionality to identify the timers that need the percentiles.
The identification is made marking the flux/mono timer with a dedicated tag.

```
public static final String PERCENTILES_TAG = "percentiles";
....
registry.config().meterFilter(new MeterFilter() {

            @Override
            @NonNull
            public Meter.Id map(@NonNull Meter.Id id) {
                return MeterFilter.ignoreTags(PERCENTILES_TAG).map(id);
            }

            @Override
            public DistributionStatisticConfig configure(@NonNull Meter.Id id, @NonNull DistributionStatisticConfig config) {
                final String percentilesTag = id.getTag(PERCENTILES_TAG);
                if (!Strings.isBlank(percentilesTag)) {
                    double[] percentilesVarArg =  Arrays.stream(percentilesTag.split(",")).mapToDouble(Double::valueOf).toArray();
                    return DistributionStatisticConfig.builder()
                            .percentiles(percentilesVarArg)
                            .build()
                            .merge(config);
                }
                return config;
            }
        });
```

**Comment by simonbasle** [comment]
I don't think we'll have the bandwidth to add that level of tuning to the metrics right now, so the workaround needs to be put forward.

**Comment by theakshaypilania** [comment]
@simonbasle : Sorry to comment on a closed issue, but is there any workaround to do this as of now, I mean putting percentiles or any other metric somehow through Flux and Monos?

**Comment by simonbasle** [comment]
@theakshaypilania what do you mean by `putting percentiles or any other metric somehow through Flux and Monos`? You weren't able to take inspiration from the workaround code exposed above?

Note that most likely you'll need to work at the level of the Micrometer `Registry` (as of 3.4.0 it is easier to setup a registry other than the Micrometer `globalRegistry` as the default one for core operators, see `Metrics.MicrometerConfiguration`).

One important property of Reactor is to have (almost) 0 dependencies, so we cannot add Micrometer classes to the `Flux` or `Mono` APIs.

**Comment by theakshaypilania** [comment]
@simonbasle: Okay, I meant that using the .metrics() method with Flux/Mono, I checked that there is **[name].flow.duration** which shows maximum and total time, not percentiles or any other info which might be useful as well and unfortunately I haven't used Micrometer ever so not familiar with its APIs/workaround exposed above. In any case, I am sure that you're telling that we have to handle it ourselves like for e.g. using Micrometer Registry
