### ISSUE TITLE
Hot publishers can save memory effectively comparing with cold publishers?

### ISSUE THREAD

**Issue by jiemar** [reactor/reactor-core#2146]
Do Hot publishers save memory effectively comparing with cold publishers?
Because cold publishers have to keep all history elements at memory while hot publishers just keep the latest one.

Am i right ?

**Comment by simonbasle** [comment]
not necessarily. being cold means that each `Subscriber` receives its own set of signals. The data could come from a source other than memory like a remote server or a database), but being cold in these cases means that each subscriber triggers a request to the server or a query on the database (so the data can change between two subscriptions that are far apart).

(as a side note, we prefer that obvious questions like this be asked on stackoverflow, see https://github.com/reactor/.github/blob/master/CONTRIBUTING.md#question-do-you-have-a-question)
