### ISSUE TITLE
Polish Context-related APIs on Flux/Mono

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2148]
## Motivation
Dealing with `Context` can be confusing enough conceptually (due to the access happening by parent subscribers looking at their child subscriber's context), but the operators that deal with `Context` are piling up on the confusion:

 - `Mono.subscriberContext()` -> "materializes" the `Context`. A form of read, but does nothing if not connected somehow to the outer chain (typically used inside a `flatMap`
 - `subscriberContext(Context)` -> "writes" to the `Context`. Really creating a new instance of the `Context` from downstream, augmented with the pairs from the provided `Context`, as the new `Context` that will be reachable from upstream
 - `subscriberContext(Function)` -> same as the above, but the "write" producing the new `Context` instance is done through in a `Function`

## Desired solution
Provide better aliases / names for these operators and deprecate the old ones.
Names to be discussed.

**Comment by bsideup** [comment]
I wish we promote more use of `deferWithContext` (which makes it clear that the context is a subscription-time concept and is the same for the whole `Flux`/`Mono` returned from it) and less `zipWith(Mono.subscriberContext())`-like usage where devs think they can change the _current_ `Context`)

**Comment by simonbasle** [comment]
Definitely. `Mono.subscriberContext()` should be a niche case (but it has its use). Maybe visibly point to `deferWithContext` in the javadoc ?

**Comment by bsideup** [comment]
Since `Mono.subscriberContext()` == `Mono.deferWithContext(Mono::just)`, does it even need to exist at all?

**Comment by simonbasle** [comment]
ah good point we can get away with recommending that as an alternative to a deprecated `Mono.subscriberContext()` (very minor overhead there)

**Comment by simonbasle** [comment]
what do you think of using a `contextUpstream` prefix for the write methods?

 - `Mono.subscriberContext()` -> document `Mono.deferWithContext(Mono::just)` as an alternative
 - `subscriberContext(Context)` to be aliased to `contextUpstreamPutAll(Context)`
 - `subscriberContext(Function)` to be aliased to `contextUpstreamTransform(Function)`
 - why not add `contextUpstreamPut(Object key, Object value)`

And on the read path, add `Flux<Tuple2<Context, T>> contextMaterialize()` method

**Comment by bsideup** [comment]
@simonbasle my 2c:
- `Mono.subscriberContext()` - deprecate, `Mono.deferWithContext(Mono::just)` as a replacement
- `subscriberContext(Function)` - deprecate, if "mutate current context is really needed, `deferWithContext` to the rescue"
- `subscriberContext(Context)` - rename to `extraUpstreamContext(Context)` or similar. `putAll` sounds too mutable.
- `contextPutForUpstream(Object key, Object value)` - high probability of being used for putting N keys one by one - high overhead

> And on the read path, add `Flux<Tuple2<Context, T>> contextMaterialize()` method

Once again, what's wrong with `deferWithContext` or adding `Context` as an argument to `composeDeferred`?

**Comment by OlegDokuka** [comment]
What about `upstreamContext` or `mutateUpstreamContext` for naming?

**Comment by simonbasle** [comment]
> Once again, what's wrong with deferWithContext or adding Context as an argument to composeDeferred

Materializing the `Context` would have less overhead AND less boilerplate. It is a direct way to obtain the `Context` in your signature, so I'm quite sure it will help some people deal with information within the `Context`.

`Tuple2` are a bit awkward (@smaldini also asked for a similar operator, going as far as requesting a new interface to have something more meaningful than the `Tuple2`), sure. But this is still far easier to understand for the average developer than `flatMap+deferWithContext` I think. In any case, having both options doesn't hurt.

Compare:

```java
mysourceFlux.operator1()
   .operator2()
   .operator3()
   .contextMaterialize()
   .map(tuple -> process(tuple.getT1().getOrDefault("someKey"), tuple.getT2())
   .operator4()
   .operator5()
```
To:
```java
mysourceFlux.operator1()
   .operator2()
   .operator3()
   .flatMap(v -> Mono.deferWithContext(Mono::just)
       .map(ctx -> process(ctx.getOrDefault("someKey", "DEFAULT"), v))
   )
   .map(tuple -> process(tuple.getT1().getOrDefault("someKey", "DEFAULT"), tuple.getT2())
   .operator4()
   .operator5()
```

That said, maybe the most common case and thus highest value proposition is for when there's only one key to be extracted from the `Context`. So maybe instead we can do one or both of:

```java
Flux<R> contextExtract(Object key, Class<T2> clazz, BiFunction<T, T2, R> zipper);
Flux<Tuple2<T, R>> contextExtract(Object key, Class<R> clazz);
```


> `contextPutForUpstream(Object key, Object value)` - high probability of being used for putting N keys one by one - high overhead

Ok I'm on the fence about that argument. The `putAll` version is straightforward enough to be used without much difficulties in place of this one. On the other hand we can ensure this one is macro-fused to alleviate a bit of the issue?

> What about `upstreamContext` or `mutateUpstreamContext` for naming?

We talk about `Context` all the time. Starting the method names with the most relevant concept/word is better for API discoverability IMO.

**Comment by bsideup** [comment]
@simonbasle the comparison is wrong. The correct would be:
```java
mysourceFlux.operator1()
   .operator2()
   .operator3()
   .contextMaterialize()
   .map(tuple -> process(tuple.getT1().getOrDefault("someKey"), tuple.getT2())
   .operator4()
   .operator5()
```

To:
```java
mysourceFlux.operator1()
   .operator2()
   .operator3()
   .transformDeferred((flux, ctx) -> {
        Object fromContext = ctx.getOrDefault("someKey");
        return flux.map(it -> process(fromContext, it);
    })
   .operator4()
   .operator5()
```
(note how we _also_ optimized it, because now `getOrDefault` is executed only once, instead of doing it for each `v`. No tuples, beautiful code, easier to optimize.

> On the other hand we can ensure this one is macro-fused to alleviate a bit of the issue?

For that, we need the macro fusion as a concept. We don't have it yet.

> We talk about Context all the time. Starting the method names with the most relevant concept/word is better for API discoverability IMO.

Although I don't have an answer to this one yet, it is worth noting that it hurts the readability a lot.
For similar reason, we're not doing `mapFlat`, `mapConcat`, etc etc

**Comment by simonbasle** [comment]
> > We talk about Context all the time. Starting the method names with the most relevant concept/word is better for API discoverability IMO.
> 
> Although I don't have an answer to this one yet, it is worth noting that it hurts the readability a lot.
> For similar reason, we're not doing `mapFlat`, `mapConcat`, etc etc

Wtf? `flatMap` itself is the core concept here... `flatMap`+`flatMapDelayError` would be a more representative pair. So I want to group operators that relate to context under a consistent prefix, and chose an easy to guess prefix. `upstream` is a secondary concept, `context` is the primary concept. The operator we do on said context comes last. Think `skip` vs `skipLast` vs `skipUntil`

**Comment by simonbasle** [comment]
> > On the other hand we can ensure this one is macro-fused to alleviate a bit of the issue?
> 
> For that, we need the macro fusion as a concept. We don't have it yet.

Second wtf of the day. See `concatWith`, `mergeWith`, `or`, `startWith`, `zipWith`...

**Comment by simonbasle** [comment]
Ok, let's focus this issue on deprecating `subscriberContext` methods and providing aliases for the write variants (advertising `Mono.deferWithContext(Mono::just)` as the replacement of `Mono.subscriberContext()`)
