### ISSUE TITLE
Publisher-initiated Context

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2149]
## Motivation
The Reactor `Context` is defined per `Subscriber` and conceptually flows from downstream to upstream. (to be specific, an operator reads from the `Context` in the chain of subscribers by having the operator's `Subscriber` ask the child `Subscriber` for its `Context`).

The default `Context` for a `Subscriber` is `Context.empty()`, and each `subscriberContext(Context)` call in the chain enriches the `Context` that was last visible under it.

But some of Reactor features piggyback on the `Context`, despite influencing all subscriptions equally. This forces an awkward placement of said features (for instance, `doOnDiscard` must be placed as low in the chain as possible so that all compatible operators pick up the discard handler(s)).

## Desired solution
Have a publisher-level `Context` tuning operator that would end up changing that `Context.empty()` default to the last visible publisher `Context` upstream (in the assembly chain). Upon subscription, the publisher would be checked for a `Context` and that `Context` would be used.

Effectively, every `Subscriber` would then have a minimal initial `Context` that is driven by the `Flux` or `Mono`.

This enables for instance a source of `ByteBuf` to define its own `onDiscard` handler for these `ByteBuf` while guaranteeing that all operator Subscribers in the runtime chain will see that handler (provided the whole chain is a chain of vanilla Reactor publishers/subscribers).

An approach similar to `CoreSubscriber#currentContext()` on `CorePublisher` (but inspecting the parent publisher's context) is probably the way to go.

## Considered alternatives
Changing the `subscribe` protocol to pass the publisher-initiated `Context` was another possibility, but seems more complicated.

## Challenges
 - The publisher-contexts can be gradually discovered only if each publisher in the chain receives a reference to its parent publisher
 - All sites where a rightmost `CoreSubscriber` is created must be updated to fetch the publisher-`Context` and pass it to the `CoreSubscriber`. This includes inners in operators like `flatMap`.

**Comment by bsideup** [comment]
I wonder if "Publisher-initiated Context" can be as simple as:
```java
Flux<Integer> source = Flux.deferWithContext(ctx -> {
	AtomicReference<String> sessionIdRef = ctx.get("sessionId");

	return Mono
			.fromCallable(UUID::randomUUID)
	           // Create the value asynchronously
			.subscribeOn(Schedulers.boundedElastic())
			.doOnSuccess(it -> sessionIdRef.compareAndSet(null, it.toString()))
			.thenMany(Flux.range(0, 10));
});

// Then later
source.map(Object::toString)
      .as(flux -> Flux.deferWithContext(ctx -> {
	      AtomicReference<String> sessionIdRef = ctx.get("sessionId");

	      return flux.doOnNext(it -> {
		      System.out.printf("Received %s with sessionId: %s%n", it, sessionIdRef.get());
	      });
      }))
      .subscriberContext(Context.of("sessionId", new AtomicReference<String>()))
      .blockLast();
```

**Comment by smaldini** [comment]
@bsideup that's assuming you control the consumer side, but if you provide an api returning flux/mono you don't (e.g. webclient). 
WebClient is an interesting one because its typically a use case we have where we want to capture thread local when the user subscribe and pass that into the Webclient filter chain for tracing, security and other support.

**Comment by smaldini** [comment]
Defer Operators might be a big limitation: . Again using WebClient as an example that's the first thing done in the default ExchangeFunction. It's impossible in this situation to pass a context downstream before subscribe time: 

```java
Mono.defer(() -> someApi.monoCall().publisherContext(ctx -> ctx.put(xxx, yyy)))
         //...
         .subscriberContext(ctx -> ctx.put(xxx, ctx.get(xxx) + 1))
        .subscribe()
```
In that sample the publisher context is only materialized on subscribe anyway. i don't know how to get around this one without AOP, blocking or anything else that is within what the JVM can express...

**Comment by simonbasle** [comment]
after discussing the above with @smaldini, it appears that there is a fundamental and very impactful limitation to this idea, in the sense that it can be very common for a chain of operators to be dynamically built, with indirection that would break the ability to discover the publisher context:
 - multiple sources (`zip(source1, source2)`
 - inner publishers (`flatMap`, `bufferWhen`)
 - `defer` (which effectively makes it impossible to see the publisher context at the point of subscribe, since the real publisher hasn't yet been instantiated)

I'm afraid we'll have to abandon the idea.
