### ISSUE TITLE
add `Mono#optional` operator

### ISSUE THREAD

**Issue by 62mkv** [reactor/reactor-core#2150]
Currently, there's no easily accessible idiom for gaining `Optional` value out of a `Mono` publisher in a non-blocking manner. 

## Motivation

Consider a scenario, where some value has to be reactively retrieved and put into `.subscriberContext` for another pipeline to execute with. If we do it like this:  

```
        Mono<String> result = potentiallyEmptyMono
                .flatMap(value -> runReactiveAction().subscriberContext(Context.of("value", value)));
```

then, the `runReactiveAction` will not be executed at all, when the `potentiallyEmptyMono` turns out empty indeed; which clearly is not what we'd want here (we'd rather to execute an action with an empty Context in this case)

## Desired solution

a `Mono<Optional<T>> optional()` operator on a `Mono` type is proposed. Having this operator would allow to do smth like this: 

```
        Mono<String> result = potentiallyEmptyMono
                .optional()
                .flatMap(optional -> runReactiveAction()
                        .subscriberContext(optional.map(value->Context.of("value", value)).orElse(Context.empty())));
```

## Considered alternatives

Currently, the desired behaviour can be achieved with something like: 

```
        Mono<String> result = potentiallyEmptyMono
                .map(value -> Optional.of(value))
                .switchIfEmpty(Mono.just(Optional.empty()))
                .flatMap(optional -> runReactiveAction()
                        .subscriberContext(optional.map(value->Context.of("value", value)).orElse(Context.empty())));
```

## Additional context

The semantic of this operator would be quite simple and concise (matter of taste, though):
- on "next", remember the value and not emit anything
- on "complete", emit either `Optional.of(value)` if it was emitted by source; or `Optional.empty()` otherwise
- on "error", propagate source error

**Comment by simonbasle** [comment]
Remembering the value and not emitting anything might be dangerous though, and is not entirely needed. The `Mono` contract let us assume that once a value is emitted, the `Mono` is basically complete, so we could directly propagate `Optional.of(value)` in `onNext(T value)`. We just need to keep track of going through that method, so that `onComplete` only propagated `Optional.empty()` IFF there was no `onNext` previously.

**Comment by simonbasle** [comment]
I'm on the fence about that one. We don't really want to promote usage of `Optional` API inside of a Reactor chain, as that can become confusing to read (and Reactor is IMHO perfectly capable of replacing the `Optional` usage).

Consider this alternative approach, where you map-to-a-Context first:

```java
Mono<String> result = potentiallyEmptyMono
    .map(v -> Context.of("key", v))
    .defaultIfEmpty(Context.empty())
    .flatMap(c -> runReactiveAction().subscriberContext(c));
```

**Comment by 62mkv** [comment]
Eh. Understood.
What would you say about `.subscriberContext(Mono<Context> contextSource)` then? 
--
Sent from Mail.ru app for Android Tuesday, 19 May 2020, 06:50PM +03:00 from Simon Baslé  notifications@github.com :

**Comment by simonbasle** [comment]
The way `Context` resolution and writes is tied in the `Subscriber`'s lifecycle makes it particularly unlikely that such an async variant of `subscriberContext` is ever added, sorry. The reverse approach of asynchronously generating the value to be put in `Context` THEN triggering the context-depending process is better.
