### ISSUE TITLE
StepVerifier hangs on publisher error 

### ISSUE THREAD

**Issue by bijukunjummen** [reactor/reactor-core#2152]
StepVerifier appears to hang on a Mono error. This issue is shown in a simple unit test in the "Steps to Reproduce" section was noticed when upgrading the reactor-core that comes with Spring Boot from Spring Boot 2.2.4.RELEASE to 2.2.7.RELEASE.

## Expected Behavior
Test provided in the "Steps to reproduce" should have completed normally.

## Actual Behavior
The provided test should have worked but appears to fail(hangs) with the version of reactor-core packaged with spring-boot 2.2.7 (reactor-core-3.3.5.RELEASE)

## Steps to Reproduce
```java
    @Test
    void testMonoError() {
        StepVerifier.create(
                getSampleMono()
                        .flatMapIterable(s -> s)
                        .map(s -> s + " world")
                        .collectList()
                        .onErrorReturn(List.of())
        )
                .assertNext(list -> assertThat(list).isEmpty())
                .verifyComplete();
    }

    private Mono<List<String>> getSampleMono() {
        return Mono.error(new RuntimeException("An Exception"));
    }
```

## Your Environment

* Reactor version(s) used: 3.3.5.RELEASE
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`): Java 11
* OS and version (eg `uname -a`): Mac OSX

**Comment by bijukunjummen** [comment]
Happened to see this in the logs - 
```
java.lang.ClassCastException: class reactor.core.publisher.Operators$OnErrorSubscription cannot be cast to class reactor.core.Fuseable$QueueSubscription (reactor.core.publisher.Operators$OnErrorSubscription and reactor.core.Fuseable$QueueSubscription are in unnamed module of loader 'app')
```

**Comment by simonbasle** [comment]
the source of the issue is in #2111, introduced in [3.3.5](https://github.com/reactor/reactor-core/milestone/73)
