### ISSUE TITLE
Enabling metrics causes NPE or hanging on certain cases

### ISSUE THREAD

**Issue by EnricSala** [reactor/reactor-core#2160]
## Expected Behavior
Enabling metrics using `Mono#metrics` has no effect on the behavior of the `Mono`, other than enabling metrics.

## Actual Behavior
Enabling metrics using `Mono#metrics` may cause a `NullPointerException` or hanging on certain cases.

## Steps to Reproduce

```java
@Test
@Timeout(value = 10, unit = SECONDS)
void this_hangs() {
    StepVerifier.create(
                    Mono.fromSupplier(() -> List.of(1, 2, 3))
                            .metrics()
                            .flatMapIterable(Function.identity()))
            .expectNext(1, 2, 3)
            .verifyComplete();
}

@Test
void this_throws_NPE() {
    StepVerifier.create(
                    Mono.using(
                                    () -> "irrelevant",
                                    irrelevant -> Mono.fromSupplier(() -> List.of(1, 2, 3)),
                                    irrelevant -> {})
                            .metrics()
                            .flatMapIterable(Function.identity()))
            .expectNext(1, 2, 3)
            .verifyComplete();
}
```

## Possible Solution
Applying any of the following workarounds fixes both tests:
* Removing the `.metrics()` operator.
* Replacing `.flatMapIterable(Function.identity()))` with `.flatMapMany(Flux::fromIterable))`.
* Replacing `Mono.fromSupplier(() -> List.of(1, 2, 3))` with `Mono.just(List.of(1, 2, 3))`.

## Your Environment
* Reactor version: Dysprosium-SR7, 3.3.5.RELEASE.
* JVM version: openjdk 11.0.6 2020-01-14.

**Comment by simonbasle** [comment]
There is indeed an issue, at least with how the fuseable version of the metrics operator deals with `ASYNC` style of micro-fusion (which is the one which piggybacks on `onNext(null)` as a signal to trigger draining of the fused queue)
