### ISSUE TITLE
Conflicting documentation on work-stealing at ParrallelFlux

### ISSUE THREAD

**Issue by jvwilge** [reactor/reactor-core#2170]
There are two `runOn` methods in `ParallelFlux` (documentation quoted and problem area made bold)

`runOn(scheduler)` :

> Specifies where each 'rail' will observe its incoming values with **no** work-stealing and default prefetch amount.

`runOn(scheduler, prefetch)`:
> Specifies where each 'rail' will observe its incoming values with **possibly** work-stealing and a given prefetch amount.

Internally `run(scheduler)` calls `runOn(scheduler, Queues.SMALL_BUFFER_SIZE)` , so this seems to me that the first method also has possible work-stealing. 
When `prefetch` is very large this effectively prevents work-stealing, but I'm not sure if that's the intention here.

It looks like RxJava has the same Javadoc + code : https://github.com/ReactiveX/RxJava/blob/3.x/src/main/java/io/reactivex/rxjava3/parallel/ParallelFlowable.java#L350

**Comment by simonbasle** [comment]
Yes I think the javadoc of both methods can be aligned on the second one, or even refrain from mentioning work stealing at all?

**Comment by jvwilge** [comment]
I think it is useful information, otherwise you might think every rail gets an equal amount of elements regardless of the processing time.
