### ISSUE TITLE
Exception in GroupBy operator not caught

### ISSUE THREAD

**Issue by DavidDuwaer** [reactor/reactor-core#2175]
If the callback provided to the `Flux.groupBy(...)` operator throws an exception, this exception is not handled as expected. It is not caught by downstream`.onErrorContinue()` or `.onErrorResume()` operators (or `.retry()`, if applicable), but it always terminates the entire flux, and is thrown by the `.subscribe()` operator at the end.

Consider these two tests:

```
	@Test
	public void in_flux()
	{
		Flux.just("a", "b", "c", "shouldsee")
			.flatMap(aValue -> {
				if (aValue.equals("c"))
				{
					throw new RuntimeException();
				}
				return Mono.just(aValue);
			})
			.onErrorResume(throwable -> Mono.just("woops"))
			.doOnNext(aValue -> System.out.println(aValue))
			.subscribe();
	}
```
and
```
	@Test
	public void in_flux()
	{
		Flux.just("a", "b", "c", "shouldsee")
			.groupBy(aValue -> {
				if (aValue.equals("c"))
				{
					throw new RuntimeException();
				}
				return aValue;
			})
			.flatMap(aGroupOfStrings -> aGroupOfStrings)
			.onErrorResume(throwable -> Mono.just("woops"))
			.doOnNext(aValue -> System.out.println(aValue))
			.subscribe();
	}
```

## Expected Behavior
I would expect both tests to write at least "a", "b" and "shouldsee" to the log.

## Actual Behavior
The second test, with the callback of the GroupBy throwing the exception, never prints "shouldsee", for the flux terminates regardless of exception handling operators downstream from the GroupBy.

I think it is harmful that it is not caught because in a reactive application with several levels of reactive methods, this groupBy method may be buried in some deep subroutine, and even while being surrounded by the "reactive equivalent" of try/catch many times over, it can break the top-level routine.

* Reactor version(s) used: Reactor-core 3.2.10.RELEASE
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`): 13
* OS and version (eg `uname -a`): Windows

**Comment by simonbasle** [comment]
None of these examples should print "shouldSee". Per Reactive Streams, a Flux that emits the `onError` signal MUST stop emitting afterwards. In both `flatMap`and `groupBy` cases, an exception thrown from the lambda is converted into the `onError` signal of that same exception. `onErrorResume` switches to a backup Flux upon receiving that error, allowing the whole sequence to complete normally with "woops" in both cases.

If you want to get a trace of the exception, you need to do so in the `onErrorResume` (which is the reactive equivalent of a `catch`).

I do get an onErrorDropped log of the RuntimeException in the case of groupBy

**Comment by simonbasle** [comment]
The log about dropped error originates from the fact that `groupBy` attempts to notify both the main sequence and each open group (aka inner sequences) of the error. On the other side, flatMap stops consuming as soon as one of its inners is notified of an error (at which point it propagates said error). When the main coordinator or another inner receive a second error, flatMap logs what it considers an extraneous signal.

@akarnokd things go pretty much the same way in RxJava, but I was wondering if it ever was considered while developing groupBy to propagate the error _only_ to the main subscriber and simply `onComplete` the inner groups? cc @smaldini

**Comment by akarnokd** [comment]
The problem is that the main subscriber may stop listening to new groups and the active ones would succeed, thus you'd end up with the same undeliverable exception.
