### ISSUE TITLE
publish() and connect() without subscribers drains upstream()

### ISSUE THREAD

**Issue by jonenst** [reactor/reactor-core#2178]
The behavior of publish() and connect() changes a lot depending on whether you have subscribers when you call connect(). With one subscriber, it respects the downstream request. Without a subscriber, it drains the upstream.

## Expected Behavior

publish() and connect() without a subscriber should act like when there is a subscriber with no more request

## Actual Behavior

publish() and connect() without a subscriber acts like when there is a subscriber doing an unbounded request

## Steps to Reproduce

```java
package org.gridsuite.notification.server;

import org.reactivestreams.Subscriber;
import org.reactivestreams.Subscription;

import reactor.core.publisher.ConnectableFlux;
import reactor.core.publisher.Flux;

public class Aze {

    public static void testit(int req1, int req2) {
        Flux<Integer> f = Flux.<Integer, Integer>generate(() -> 0, (state, sink) -> {
            if (state > 4) {
                sink.error(new RuntimeException("Shouldn't happen"));
            }
            sink.next(state);
            return state + 1;
        }).log();
        ConnectableFlux<Integer> ff = f.publish(2);
        if (req1 > 0) {
            ff.subscribe((x) -> { }, (x) -> {
                System.out.println("ERROR");
            }, () -> { }, (s) -> {
                s.request(req1);
            });
        }
        ff.connect();
        if (req2 > 0) {
            ff.subscribe((x) -> { }, (x) -> {
                System.out.println("ERROR");
            }, () -> { }, (s) -> {
                s.request(req2);
            });
        };
    }
    public static void main(String[] args) throws Exception {
        System.out.println("request 1 before");
        testit(1, -1);
        System.out.println("request 1 after");
        testit(-1, 1);
    }

}
```

```
request 1 before
10:43:21.820 [main] DEBUG reactor.util.Loggers$LoggerFactory - Using Slf4j logging framework
10:43:21.852 [main] INFO reactor.Flux.Generate.1 - | onSubscribe([Fuseable] FluxGenerate.GenerateSubscription)
10:43:21.858 [main] INFO reactor.Flux.Generate.1 - | request(2)
10:43:21.859 [main] INFO reactor.Flux.Generate.1 - | onNext(0)
10:43:21.860 [main] INFO reactor.Flux.Generate.1 - | request(1)
10:43:21.860 [main] INFO reactor.Flux.Generate.1 - | onNext(1)
10:43:21.860 [main] INFO reactor.Flux.Generate.1 - | onNext(2)
request 1 after
10:43:21.860 [main] INFO reactor.Flux.Generate.2 - | onSubscribe([Fuseable] FluxGenerate.GenerateSubscription)
10:43:21.860 [main] INFO reactor.Flux.Generate.2 - | request(2)
10:43:21.860 [main] INFO reactor.Flux.Generate.2 - | onNext(0)
10:43:21.860 [main] INFO reactor.Flux.Generate.2 - | request(1)
10:43:21.860 [main] INFO reactor.Flux.Generate.2 - | onNext(1)
10:43:21.860 [main] INFO reactor.Flux.Generate.2 - | request(1)
10:43:21.860 [main] INFO reactor.Flux.Generate.2 - | onNext(2)
10:43:21.860 [main] INFO reactor.Flux.Generate.2 - | request(1)
10:43:21.860 [main] INFO reactor.Flux.Generate.2 - | onNext(3)
10:43:21.861 [main] INFO reactor.Flux.Generate.2 - | request(1)
10:43:21.861 [main] INFO reactor.Flux.Generate.2 - | onNext(4)
10:43:21.861 [main] INFO reactor.Flux.Generate.2 - | request(1)
10:43:21.865 [main] ERROR reactor.Flux.Generate.2 - | onError(java.lang.RuntimeException: Shouldn't happen)
10:43:21.868 [main] ERROR reactor.Flux.Generate.2 - 
java.lang.RuntimeException: Shouldn't happen
	at org.gridsuite.notification.server.Aze.lambda$1(Aze.java:14)
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.slowPath(FluxGenerate.java:262)
	at reactor.core.publisher.FluxGenerate$GenerateSubscription.request(FluxGenerate.java:204)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:137)
	at reactor.core.publisher.FluxPublish$PublishSubscriber.onSubscribe(FluxPublish.java:241)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:171)
	at reactor.core.publisher.FluxGenerate.subscribe(FluxGenerate.java:83)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:53)
	at reactor.core.publisher.FluxPublish.connect(FluxPublish.java:100)
	at reactor.core.publisher.ConnectableFlux.connect(ConnectableFlux.java:99)
	at org.gridsuite.notification.server.Aze.testit(Aze.java:30)
	at org.gridsuite.notification.server.Aze.main(Aze.java:46)
10:43:21.868 [main] DEBUG reactor.core.publisher.Operators - onNextDropped: 5
```

## Possible Solution
Not sure but I looked into the publish code, at some point it does a "len == cancel" to check if every subscriber cancelled and this is true for no subscriber but maybe should be false ?

## Your Environment

* Reactor version(s) used:
[INFO] |  |  \- io.projectreactor:reactor-core:jar:3.3.3.RELEASE:compile

* JVM version (`javar -version`):
java version "11.0.5" 2019-10-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode)

* OS and version (eg `uname -a`):
Linux gm0winl149.bureau.si.interne 5.1.18-200.fc29.x86_64 #1 SMP Mon Jul 15 16:09:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by simonbasle** [comment]
IIRC I tried to improve the situation but couldn't find an immediate solution. Since the intent of `connect()` is that the `ConnectableFlux` is ready and has the required number of subscribers set up, we'll have to keep the current behavior.

One possible workaround would be to set up a dummy 0-request `Subscriber` that can be set up before `connect()` (and cancelled later) 🤔

**Comment by jonenst** [comment]
Thanks for taking the time to look into this. I couldn't find in the docs that  "the intent of connect() is that the ConnectableFlux is ready and has the required number of subscribers set up". Maybe It's worth it to more explicitly document this (or maybe it's already documented and I just missed it) ?
So is it totally unsupported to subscribe() on a ConnectableFlux after connect() was called ? Should it throw an exception in this case ?

In my case, when my server starts, it does a ConnectableFlux.connect() (to setup connections to a rabbitmq queue. I only want to do this once and I want to do this eagerly). When people connect to my server, it leads to a call to subscribe() (so after the connect()) to handle their connection. What is the recommended approach for this use case if calling subscribe() after connect() is unsupported ?

Thank you for your time

**Comment by simonbasle** [comment]
Further subscriptions after the `connect()` point are indeed perfectly allowed. There are actually several flavors of `ConnectableFlux` (e.g. `Flux.publish()` vs `Flux.replay(int)`) which each define the behavior of what should happen in that case. Arguably, the initial request pattern upon calling `connect()` could also be considered part of the contract of each of these concrete implementations rather than that of `ConnectableFlux` common contract.

I'm arguing that in order to limit that initial request with `publish()`, right now the only way is to have a 0-request `Subscriber` in place before calling `connect()`.

**Comment by jonenst** [comment]
Thanks for the explanation. I'll let you decide if this can be just mentioned in the docs or if the code should be changed. Cheers
