### ISSUE TITLE
Do we even need multiple Processor implementations ? Discussing sinks again

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2179]
Here are the broad usage cases that I could think about:
 - continuing an API that takes a Subscriber as a Flux (or Mono) -> `UnicastProcessor` could fit the bill  (we'd probably need a simpler mono variant as well, UnicastMonoProcessor ?)
 - preventing a Publisher from being subscribed to multiple times -> `UnicastProcessor` again
 - multicasting a Publisher to several (late) subscribers -> can be achieved with `Flux.from(p).share()`
 - caching and replaying a Publisher to (several) late subscribers -> can be achieved with `Flux.from(p).replay(n)`
 - turning a Publisher to a Mono and cache its first signal for multiple subscribers -> can be achieved with `Mono.from(p).cache()`

So it looks more and more like we don't need a whole lot of these `FluxProcessor`s :thinking:

In a lot of cases, people start using FluxProcessors for a combination of their multicast properties and the ability to manually "feed" a Flux.
More and more people blessedly do the later through the processor's `Sink`, but the fact is that not everybody discovers that API, and having the `Subscriber` methods handy is a tempting way to shoot oneself in the foot.

Instead, given all the above, it would be beneficial to have standalone sink flavors that users can directly instantiate. It's not even clear that we'd need many flavors:

 - manually emit values to at most one Subscriber => introduce `UnicastFluxSink`, `UnicastMonoSink`
 - manually emit values to several Subscribers => unicastSink.share()
 - manually emit values to several Subscribers, replaying stuff to late subscribers => unicastSink.replay(n)
 
With a standalone sink, the first signal is like `connect()` => up to user to NOT call the sink until everything is properly subscribed.
That said `UnicastXxxSink` without a subscriber could also DROP, and we could use OnBackpressureStrategy or onBackpressure operators to tune that...

There's already been several iterations around this subject (#1169, #1170, #1053, #1308), but I've been questioning the nature of my reality lately, and wanted to challenge _all_ assumption and open the door to an approach a bit more radical.

**Comment by simonbasle** [comment]
cc @smaldini, @mp911de, @artembilan, @osi, @dfeist (I remember having discussions around processors with all of you)

**Comment by osi** [comment]
I think there's value in a standalone `Sink` API that's separate from Processors. To the extend that various processor implementations can be hidden/removed, that'd be a boon for new users. When I first started w/reactor it was a point of confusion, and as I'm introducing team-mates to the concepts, I'm having to warn them against using them (as it's often an implementation crutch versus creating a fully reactive flow).

Even the event-loop based processors could be thought of as a custom strategy for how multicast  happens.

**Comment by bruto0** [comment]
There's this use case for the UnicastProcessor: https://stackoverflow.com/questions/48598295/how-to-reconnect-reactornettywebsocketclient-connection
Actually using a modified version of it and sink without the flux implementation wouldn't help

**Comment by simonbasle** [comment]
@bruto0 to be clear, my intent is to have a `Sink` that has a `asFlux` method allowing other components in the system to view the sink as a `Flux`. A standalone sink could be unicast by default and require `publish`/`share`/etc to become multicast, or it could be multicast by default - this is still up for decision.

But I think this proposal would fit the bill for the case you expose, since said case doesn't subscribe the UnicastProcessor to a Publisher, it manipulates it directly (which is wrong btw and can lead to issues if calls are made in parallel).

**Comment by bruto0** [comment]
good idea then, a useful constraining of programmer's opportunities to shoot himself in the foot :)

as far as referred case from SO, UnicastProcessor needs a MPSC queue there to be safe, correct?

**Comment by simonbasle** [comment]
(for a stroll down memory lane, see issues #19 and #22 in https://github.com/reactive-streams/reactive-streams-jvm/issues/)

**Comment by artembilan** [comment]
In Spring Integration we use `MonoProcessor` to have a completion barrier, kinda the similar what we would have with `Future`.
One particular use-case is a `replyTo` message header:
```
	private static class MonoReplyChannel implements MessageChannel, ReactiveStreamsSubscribableChannel {

		private final MonoProcessor<Message<?>> replyMono = MonoProcessor.create();

		MonoReplyChannel() {
		}

		@Override
		public boolean send(Message<?> message, long timeout) {
			this.replyMono.onNext(message);
			this.replyMono.onComplete();
			return true;
		}

		@Override
		public void subscribeTo(Publisher<? extends Message<?>> publisher) {
			this.replyMono.switchIfEmpty(Mono.from(publisher));
			this.replyMono.onComplete();
		}

	}
```

In the other place we use an `EmitterProcessor` like this:
```
public FluxMessageChannel() {
		this.processor = EmitterProcessor.create(1, false);
		this.sink = this.processor.sink(FluxSink.OverflowStrategy.BUFFER);
	}

	@Override
	protected boolean doSend(Message<?> message, long timeout) {
		Assert.state(this.processor.hasDownstreams(),
				() -> "The [" + this + "] doesn't have subscribers to accept messages");
		this.sink.next(message);
		return true;
	}

	@Override
	public void subscribe(Subscriber<? super Message<?>> subscriber) {
		this.processor
				.doFinally((s) -> this.subscribedSignal.onNext(this.processor.hasDownstreams()))
				.subscribe(subscriber);
		this.subscribedSignal.onNext(this.processor.hasDownstreams());
	}
```

There is also another use-case:
```
	private static <T> Flux<Message<T>> adaptSubscribableChannelToPublisher(SubscribableChannel inputChannel) {
		return Flux.defer(() -> {
			EmitterProcessor<Message<T>> publisher = EmitterProcessor.create(1);
			@SuppressWarnings("unchecked")
			MessageHandler messageHandler = (message) -> publisher.onNext((Message<T>) message);
			inputChannel.subscribe(messageHandler);
			return publisher
					.doOnCancel(() -> inputChannel.unsubscribe(messageHandler));
		});
	}
```

In the mentioned above `FluxMessageChannel` we also use a `ReplayProcessor` for state management:
```
private final ReplayProcessor<Boolean> subscribedSignal = ReplayProcessor.create(1);
...
	public void subscribeTo(Publisher<? extends Message<?>> publisher) {
		this.upstreamSubscriptions.add(
				Flux.from(publisher)
						.delaySubscription(this.subscribedSignal.filter(Boolean::booleanValue).next())
						.publishOn(Schedulers.boundedElastic())
						.doOnNext((message) -> {
							try {
								send(message);
							}
							catch (Exception ex) {
								logger.warn("Error during processing event: " + message, ex);
							}
						})
						.subscribe());
	}
```

No more processors in Spring Integration.
Thanks

**Comment by smaldini** [comment]
Just another comment or nail in the coffin: Processors are used for custom operators flow like `takeUntil(Publisher)`, window etc. The processor contract itself is something I regret exposing, that was historically the first step to stages in the pipeline (see reactor 2). I think we will still need a `toProcessor` for some API accepting `Subscriber` as argument and for custom operator implementations but this should not be the entry point for users.
