### ISSUE TITLE
Order of execution of `doFinally`

### ISSUE THREAD

**Issue by fredwangwang** [reactor/reactor-core#2187]
The order of execution of doFinally is not what I expected.

Here is the code:
```
logger.info(Mono.just(1)
        .doFinally((s) -> logger.info("finally"))
        .flatMap(it -> Mono.fromFuture(CompletableFuture.supplyAsync(() -> {
                    logger.info("future");
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    return 2;
                }
                ))
        )
        .block()
);
```

## Expected Behavior

future <-- this get printed first
finally <-- this get printed 2 seconds later
2

## Actual Behavior

future <-- this get printed first
finally <-- this get printed immediately after
2 <-- this get printed 2 seconds later

## Possible Solution

I can get the expected behavior by:

1. chaining `doFinally` right after `Mono.fromFuture`:

    ```
    logger.info(Mono.just(1)
          .flatMap(it -> Mono.fromFuture(CompletableFuture.supplyAsync(() -> {
                      logger.info("future");
                      try {
                          Thread.sleep(2000);
                      } catch (InterruptedException e) {
                          e.printStackTrace();
                      }
                      return 2;
                  }
                  ))
                  .doFinally((s) -> logger.info("finally"))
          )
          .block()
    );
    ```

1. remove `fromFuture` to make everything on a single thread:
    ```
    logger.info(Mono.just(1)
            .doFinally((s) -> logger.info("finally"))
            .flatMap(it -> {
                        logger.info("future");
                        try {
                            Thread.sleep(2000);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                        return Mono.just(2);
                    }
            )
            .block()
    );
    ```

But this is not intuitive. I would assume doFinally happens the at the _last_ stage of the pipeline no matter which thread of execution it is on,
synchronized or asynchronized.

## Environment
Java 11
Reactor 3.3.0

**Comment by simonbasle** [comment]
It's the last stage of the pipeline _above it_. Basically, there is no way for the operator to know what happens downstream, even less to react to signals pushed downstream (by definition, as it is upstream). If it sees any of the `onComplete`, `onError` or `cancel` signals, it invokes the Consumer.

The correct solution is to just put it after the `flatMap`.
