### ISSUE TITLE
Introduce Flux.elapsedDuration()

### ISSUE THREAD

**Issue by ericbottard** [reactor/reactor-core#2195]
`Flux.elapsed()` currently returns time intervals expressed as `Longs` of milliseconds.
Following #1734, it should be possible to get sub-milliseconds emissions, and would be nice to be able to measure them.
The proposal is to emit `Tuple2<Duration, T>`, which is less error-prone. A duration is only two numbers internally so shouldn't be much worse than a boxed `Long`.

**Comment by bsideup** [comment]
If we're talking about a new method, we could as well do something like:
```java
class Timed<T> {
    long elapsed;

    <T> item;

    public long getElapsedNanos() { ... }
    public Duration getElapsedDuration() { ... }
}

class Flux<T> {
    public Timed<T> elapsedWhatever() { ... }
}
```

**Comment by ericbottard** [comment]
Would return a `Flux<Timed<T>>`, but yes. My initial point was two-fold:
- elapsed is stuck returning millis
- returning just a Long requires extra knowledge that we're dealing with millis, which a `Duration` clarifies.

If we want to be extra careful, we would store a Duration in Timed instead of a long, as Long.MAX_VALUE nanoseconds is limited to 292 years but...

**Comment by bsideup** [comment]
@ericbottard ooops, right. I fixed the code example.

> we would store a Duration in Timed instead of a long

This will require a second allocation (of `Duration`), while non-boxed `long` in `Timed` helps avoiding it. Since the timer (`System.nanoTime()`) returns `long`, and we subtract two, there is no problem with using `long` as the type.

**Comment by ericbottard** [comment]
Yes, I was aware of the attempt not to allocate too many objects, hence me being "extra careful".
There is the same problem with `Flux.timestamp()` though, and there we're not dealing with differences (Durations) but "absolute since epoch" so the problem becomes more real.

**Comment by simonbasle** [comment]
We could even sacrifice a bit of memory and have a `Timed<T>` class that covers both the needs of `timestamp` and `elapsed`, providing methods to get one or the other on top of the value itself. That's maybe 2 longs + 1 TimeUnit if we want to avoid storing `Duration`s altogether. Otherwise that's 1 `Duration` and 1 `Instant` I guess 🤔 

wdyt @bsideup @ericbottard @aneveu @violetagg ?

**Comment by bsideup** [comment]
@simonbasle sounds exactly like what I proposed here :D 
https://github.com/reactor/reactor-core/issues/2195#issuecomment-645258206

**Comment by simonbasle** [comment]
@bsideup yes, I'm just offering that it should wrap enough data to also allow `timestamp()` like usage on top of `elapsed()` like usage.

**Comment by bsideup** [comment]
@simonbasle ah, okay, I see 👍
