### ISSUE TITLE
repeatWhenEmpty hangs on cancel when discard hook is present

### ISSUE THREAD

**Issue by chringwer** [reactor/reactor-core#2196]
## Expected Behavior
It should be safe to cancel the sequence.

## Actual Behavior
Cancelling a sequence which is in a `repeatWhenEmpty()` loop will cause issues when a discard hook has been registered. In that case `Operators.onDiscardMultiple()` is invoked with the iterator used to keep track of the current iteration and the hook would be called for every remaining number up to `Long.MAX_VALUE`. 

## Steps to Reproduce
This test case will succeed when removing the `doOnDiscard()` operator.

```java
@Test
public void shouldCompleteEventually()
{
    StepVerifier.create(Mono.empty()
                            .repeatWhenEmpty(Repeat.once())
                            .doOnDiscard(PooledDataBuffer.class, DataBufferUtils::release))
                .thenAwait()
                .thenCancel()
                .verify(Duration.ofSeconds(5));
}
```

## Possible Solution
Probably we should treat the remaining iterations in a way that they can be safely discarded without bothering any application level hooks. Also, I guess `FluxStream` should not be considered "knownToBeFinite" if its size is `Long.MAX_VALUE`.

## Your Environment
* Reactor version(s) used: 3.3.6.RELEASE

**Comment by simonbasle** [comment]
The operator is an alias, it could use `.index()` rather than a `Stream` for its purpose, which would eliminate the issue (see #2014 for context of the iteration)
