### ISSUE TITLE
Mono with Either

### ISSUE THREAD

**Issue by ovu** [reactor/reactor-core#2198]
Hello,

I am using Reactor in Kotlin with the Arrow kt core library. I defined the following function, however It does not compile:
    fun test(): Mono<Either<String, String>> {
        return Mono.just("Hi").map { text -> text.right()
        }.onErrorResume { error ->
            Mono.just("error".left())
        }
    }
I get the following error:
Error:(39, 16) Kotlin: Type mismatch: inferred type is Mono<Either<Nothing, String!>!> but Mono<Either<String, String>> was expected
Error:(41, 18) Kotlin: Type inference failed. Expected type mismatch: inferred type is Mono<Either<String, Nothing>!> but Mono<out Either<Nothing, String!>!>! was expected

I am guessing it is something with the compiler and type checking. Maybe there is a workaround to write that kind of function? Or What am I doing wrong?

Thanks for your help!

**Comment by simonbasle** [comment]
Please ask questions, especially ones where the issue is likely to have a root cause in another library or language compiler, on [stackoverflow](https://stackoverflow.com/questions/tagged/project-reactor)
