### ISSUE TITLE
Separate consistency/concurrency testing from unit tests in reactor

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#220]
This should allows faster feedback on PR as currently builds on travis take up to 10mn.

**Comment by simonbasle** [comment]
started in [`3.0.4`](https://github.com/reactor/reactor-core/milestone/12?closed=1)

**Comment by smaldini** [comment]
I think we can consider that issue closed for now, we still remain below 5mn mark for any CI run now  and consistency tests are run on release only (or local tests).
