### ISSUE TITLE
Define Subscription Lifecycle in reference docs

### ISSUE THREAD

**Issue by anno1985** [reactor/reactor-core#2200]
## Documentation Issue

The reference docs state under section [9.8. "Adding a Context to a Reactive Sequence"](https://projectreactor.io/docs/core/release/reference/#context):
> This is an advanced feature that is more targeted at library developers. It requires good understanding of the lifecycle of a Subscription and is intended for libraries that are responsible for the subscriptions.

## Improvement Suggestion

There is no section on the concept of a `Subscription` in the TOC of the reference docs. The word "lifecycle" only appears twice. The actual lifecycle is not explained. (If there is a section about the signals sent, linking to it might help.)

## Additional context

Understanding the "advanced feature" of the `Context` is useful when using e.g. Spring Security, e.g. its [reactive method security feature](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#jc-erms), as Spring Security's `ReactiveSecurityContextHolder` uses reactor's `Context` to store its `SecurityContext`. (So, while possibly advanced, I don't think it's something only library developers will need to know about... :) )

**Comment by bsideup** [comment]
`Subscription`'s lifecycle is very well defined in the reactive streams specification:
http://github.com/reactive-streams/reactive-streams-jvm/

**Comment by simonbasle** [comment]
Perhaps as a first measure we can mention and link to the Reactive Streams spec in that reference guide comment along the mention of the `Subscription lifecycle`? I don't know if we can do far better than what's already there otherwise with the simple examples and full example.
