### ISSUE TITLE
Remove deprecated WorkQueueProcessor/TopicProcessor

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2208]
These two processors and their base class have been deprecated since 3.3.0.

**Comment by aphalke** [comment]
@simonbasle , what is alternative for this? And may I know reason for removal?

**Comment by chemicL** [comment]
@aphalke please consult the documentation https://projectreactor.io/docs/core/release/reference/#processors
Also, if you're interested in digging deeper, the javadoc of both mentioned classes contain reference to https://github.com/reactor/reactor-core/issues/2431 which contains useful links and discussion.

**Comment by simonbasle** [comment]
see also #1051 for a rationale behind the deprecation of these two particular processors.

direct and long term alternative if you're using the processors to connect to an existing Flux/Publisher source is also documented there:

 - WQP: `source.parallel().runOn(scheduler)`
 - TP: `source.publishOn(scheduler)`


### more context:

in the 3.3.x and 3.4.x line, these two classes have been copied to the `io.projectreactor.addons:reactor-extra` artifact (see https://github.com/reactor/reactor-addons repository)

in 3.4.x, _ALL_ processors have been deprecated (they are often misused because they expose a `Subscriber` API that is enticing to the users who generally overlook this is not thread-safe and expected to be used in respect to the Reactive Streams specification). The alternative for manual usage is the `Sinks` API. The processors have been marked for removal in 3.5.0 but this _might_ not happen as there has been some ask to keep them around a bit longer.

**Comment by aphalke** [comment]
Thanks @simonbasle . Went through the given links and got the reason behind removing multiple processor implementation. Reason we used workqueue processor with ring buffer was its blocking nature to avoid overwhelming consumers. If I am correct now similar can  be achieved with UnicastProcessor with custom queue with given size.

**Comment by aphalke** [comment]
Looks like UnicasProcessor as well deprecated.
