### ISSUE TITLE
Ensure that `Processors` and `Sinks` API can cover all now-deprecated `*Processor` use cases

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#2213]
The following usages need replacements that are unavailable in 3.4.0-M1:

- [x] `EmitterProcessor.create(1)` + `processor.sink(OverflowStrategy.ERROR)`:
    (Current workaround: `Processors.more().multicast(1)` + `processor.sink(OverflowStrategy.ERROR)`, but `sink` is deprecated)

**Comment by simonbasle** [comment]
In #2218 the first case above would become `FluxProcessor.fromSink(Sinks.unsafe().multicast().onBackpressureBuffer(1))` (currently work in progress)

**Comment by simonbasle** [comment]
To clarify, after #2319 the similar behavior can be done with a bit of boilerplate:

```java
if (many.tryEmitNext(1) == FAIL_OVERFLOW) {
    many.emitError(Exceptions.failWithOverflow());
}
```

**Comment by bsideup** [comment]
@simonbasle since `EmitterProcessor.create(1)` + `processor.sink(OverflowStrategy.ERROR)` can now be implemented with `onBackpressureError()` + `tryEmitNext` and so far no other requests popped up, perhaps we can close the issue now?

**Comment by simonbasle** [comment]
@bsideup indeed 👍
