### ISSUE TITLE
WorkQueueProcessor threads hangs if one thread takes too much time to process

### ISSUE THREAD

**Issue by AveshKaliya** [reactor/reactor-core#2225]
We are using WorkQueueProcessor for message processing, if one of the thread from pool takes too much time to process than other thread from pool is not taking any work from the queue.

WorkQueueProcessor is initilized with default WaitStrategy.liteBlocking(). We tried parking and blocking strategy but there no difference in result.

Earlier it was working fine, no such type of issues were produced.

Just change is before we were using Ubuntu 14 and now we are using Ubuntu 16.

* Reactor version(s) used: reactor-core-3.0.3.RELEASE
* JVM version (`javar -version`): 1.8
* OS and version (eg `uname -a`): Ubuntu 16

Do let me know if you require more information.

**Comment by bsideup** [comment]
@AveshKaliya `WorkQueueProcessor` is deprecated for removal. Consider using other `Processor` types.
