### ISSUE TITLE
Document Android 21 support

### ISSUE THREAD

**Issue by yschimke** [reactor/reactor-core#2227]
My experience is that the most recent Android toolchain (4.0 of android gradle plugin etc) supports down to Android SDK version 21.  This is a good baseline, e.g. matches OkHttp, Retrofit etc.

This example app shows Reactor core, with Netty and RSocket working and deployable  for Android https://github.com/rsocket/rsocket-demo-android-java8

So maybe worth firming up the Android policy?

**Comment by simonbasle** [comment]
I don't think so. The second we make it "official" people will have expectation that we have bandwidth to support it. If it works on Android, great. If it doesn't but the fix is a low hanging fruit, great. But we won't make any specific guarantee. There is currently a note about Android in the README, which mentions SDK 26.

**Comment by yschimke** [comment]
Yep, thought I'd raise with a positive signal.

I think it's a shame and something you should probably reconsider, given the size of the addressable developer market.  Without Android 21 it's not really a starter.  But since I'm not offering to support myself, happy for you to close.

Thanks for the quick feedback.

**Comment by simonbasle** [comment]
@yschimke I would say we can add a line in the Android mention in the README about android-gradle-plugin v4 desugaring feature _likely_ allowing reactor to be used on Android apps targeting API level 21 and above, in addition to the existing mention. Would you like to contribute a PR?

**Comment by simonbasle** [comment]
ie we don't commit, but we hint that, on top of API level 26+, there's a chance desugaring helps in 21-25 when using the most recent toolchain

**Comment by yschimke** [comment]
https://github.com/reactor/reactor-core/pull/2232

**Comment by simonbasle** [comment]
fixed in #2232
