### ISSUE TITLE
RxJava1Adapter is not working with RxJava1.2.0

### ISSUE THREAD

**Issue by beihaifeiwu** [reactor/reactor-core#223]
In the rx.Completable have the flowing code:
```java
    /**
     * @deprecated Use {@link OnSubscribe} instead.
     */
    @Deprecated // TODO Remove interface after 1.2.0 release. It was never a stable API. Provided only for migration.
    public interface CompletableOnSubscribe extends Action1<CompletableSubscriber> {

    }
```
and in the RxJava1Adapter which have:
```java
	/**
	 * Wraps a Publisher and exposes it as a CompletableOnSubscribe and ignores the onNext
	 * signals of the Publisher.
	 */
	private static class PublisherAsCompletable
			implements rx.Completable.CompletableOnSubscribe {

		final Publisher<?> source;

		public PublisherAsCompletable(Publisher<?> source) {
			this.source = Objects.requireNonNull(source, "source");
		}
```

So RxJava1Adapter will not working with RxJava 1.2.0 above, any plan to fix this ?

**Comment by akarnokd** [comment]
`Completable` is experimental and will change a bit again in 1.2.2. I wouldn't mind if Reactor's adapter didn't support it until stable to avoid the case when different libraries want to use different RxJava versions and then convert to Reactor.

**Comment by smaldini** [comment]
Hi @beihaifeiwu we are looking at externalizing this adapter and eventually leave the responsibility to  https://github.com/reactor/reactor-addons/reactor-adapter. There is a possible scenario where we would transparently support all various rxjava1 changes we are aware using static check on class presence.
