### ISSUE TITLE
Add flatMapIfFalse operator for convenient interface

### ISSUE THREAD

**Issue by hojongs** [reactor/reactor-core#2233]
## Motivation

When I take Mono<Boolean>, sometimes I need code like this

```kotlin
// kotlin code, but same issue also java
Mono.just(true)
    .flatMap { b ->
        if (b)
            Mono.just(it)
        else
            Mono.error(InvalidArgument())
    }
```

These code make code longer and reduce readability.
reactor provides rich operators and I expect some more operators can be added.

## Desired solution

Add Mono method `Mono<Boolean>.flatMapIfFalse(mono)` similar to Mono<T>.switchIfEmpty(mono)
I think it can be defined in both of Mono, Flux.
Example code is below. It simpler than original code.
```kotlin
Mono.just(true)
    .flatMapIfFalse(Mono.error(InvalidArgument())
```

## Considered alternatives

first code snippet.
## Additional context

- I also suggest more operators for Mono<Boolean>.
- maybe `flatMapIfTrue, returnIfFalse, returnIfTrue, mapIfTrue, mapIfFalse`.

**Comment by bsideup** [comment]
Have you tried Mono#handle?

**Comment by hojongs** [comment]
I tried but Mono#handle is similar to Mono#map or Mono#flatMap.
Let me show you some examples.
```kotlin
// with Mono#handle
                Mono.just(true)
                    .handle { b, u: SynchronousSink<Int> ->
                        if (b) u.next(1)
                        else u.error(IllegalArgumentException(""))
                    }
```
```kotlin
// with Mono#map
                Mono.just(true)
                    .map { b ->
                        if (b) 1
                        else throw IllegalArgumentException("")
                    }
```
So, My suggestion is here.
```kotlin
// with Mono#flatMapIfFalse I suggest
                Mono.just(true)
                    .flatMapIfFalse(Mono.error<Boolean>(IllegalArgumentException("")))
```
Additionally, I suggest one more.
```kotlin
// with Mono#errorIfFalse I suggest
                Mono.just(true)
                    .errorIfFalse(IllegalArgumentException(""))
```
I thought It is good that Adding more operators for Mono and Flux. so I suggested these operators.

**Comment by simonbasle** [comment]
We try to limit new operators to stuff that cannot be done by an existing operator or small combination of operators. I would suggest you add kotlin extension methods to your project, if you're that worried about the code overhead.

PS: your example doesn't make much sense to me since for the `flatMapIfFalse` there's nothing providing the value for the `true` branch.
