### ISSUE TITLE
Remove compilation warnings related to jsr305

### ISSUE THREAD

**Issue by ericbottard** [reactor/reactor-core#2234]
jsr305 is a compile time only library used by annotation processors. It not being accessible triggers some warnings that add noise to the build

**Comment by ericbottard** [comment]
Done in 85da74bc1f16b732ed9aa4a6b8b53e56970cf8b7

**Comment by chemicL** [comment]
I don't think it is necessary. The last person touching this line was @sdeleuze back in 2017 while working on Kotlin interoperability I believe. It seems to be an omission and can be safely removed. @sdeleuze do you remember any of this? Do you think we can remove this import? Thanks!

**Comment by sdeleuze** [comment]
Likely an unwanted side effect of the revert, should be removed I think indeed.

**Comment by chemicL** [comment]
Thanks @sdeleuze !
As a follow up, I opened #3510
