### ISSUE TITLE
Images in javadoc too big

### ISSUE THREAD

**Issue by natros** [reactor/reactor-core#224]
Chrome Browser
![flux__reactor-core_3_0_2_release_api_](https://cloud.githubusercontent.com/assets/4996289/19563186/09c916a2-96d7-11e6-8308-740f442cd9b2.png)

**Comment by smaldini** [comment]
Indeed the CSS class is not included in the jar and the rendering is unlike http://projectreactor.io/core/docs/api/, will have a look. Thanks for the report, we had a similar report from IDE users navigating to the javadoc, hopefully we'll address that soon.

**Comment by smaldini** [comment]
Should be fixed somehow via https://github.com/reactor/projectreactor.io/commit/8e5fc44c3471afdc542c9f95af7bfe95b02ce2f5
