### ISSUE TITLE
Fail build on fixable build warnings

### ISSUE THREAD

**Issue by ericbottard** [reactor/reactor-core#2240]
Now that we have [almost zero](https://github.com/reactor/reactor-core/commit/ce915285ae7ddbaa7bdd2f5676f36771ffe2f0ae) "fixable" build warnings, it would be a good time to make sure that none creep up again by making the build fail when they happen.

**Comment by simonbasle** [comment]
for the `Unsafe` use, I think `RingBuffer` should be removable as IIRC it was only used in the two deprecated processors that we just removed. There is a small group of classes associated with it that might make it look like the class is still used, so we need to double check that these are just a "closed circuit" that no public API can reach anymore.

**Comment by ericbottard** [comment]
I had another look at the `-Werror` flag, and it indeed fails on "proprietary API usage" warnings. The problem is, that warning can't be suppressed see eg https://stackoverflow.com/questions/13855700/suppress-javac-warning-is-internal-proprietary-api-and-may-be-removed-in-a-f/42406330#42406330.
So, while it's always a good thing to get rid of unused code, for this particular issue, it's either we get rid of 100% of them or we can't fail the build.

Another acceptable approach though, could be to scan the build output for the number of warnings (say, currently 16) and fail as soon as it goes further...

**Comment by simonbasle** [comment]
what happens if you fail-on-warnings, but you also configure the linter to not warn about proprietary API usage? does `-Werror` implicitly turn on all possible linter categories?

and do we have any proprietary API usage other than those in `RingBuffer` and associated removable classes ?

**Comment by ericbottard** [comment]
>but you also configure the linter to not warn about proprietary API usage

That's the thing: there is no flag for proprietary API usage :(

**Comment by ericbottard** [comment]
Closing as WONTFIX as there seem to be no simple way to disable this particular lint, or to grep the build output.
