### ISSUE TITLE
The noMicrometerTest gradle conf doesn't work as intended

### ISSUE THREAD

**Issue by ericbottard** [reactor/reactor-core#2251]
It seems the whole trick to test reactor when micrometer is *not* present on the classpath using a dedicated gradle configuration doesn't work as intended, giving a false sense of security.

We should
- dig into it
- fix it, preferably in accordance with a similar requirement for blockhound (both approaches should be consistent, and easy to follow)

**Comment by bsideup** [comment]
FYI the BlockHound tests are separated so that they get a separate classloader and not affect the "main" tests, per test (by using the forking).
There is no dependency exclusion required or anything like that, so it is simpler in that regard.

**Comment by ericbottard** [comment]
To clarify what seems to be the problem (but not the actual *source* of the problem), the 
```java
	@BeforeClass
	public static void assumeNoMicrometer() {
		Assumptions.assumeThat(Metrics.isInstrumentationAvailable())
		           .as("Micrometer on the classpath").isFalse();
	}
```

block in `MetricsNoMicrometerTest` seems to skip the tests. Its presence was required so that those tests don't fail in the *normal* configuration (living alongside all "regular" tests).
