### ISSUE TITLE
Architecture schema for Publishers and subscribers

### ISSUE THREAD

**Issue by aneveu** [reactor/reactor-core#2252]
## Documentation Issue
There is no architecture schema of the publishers and subscribers in reactor-core which might be useful to have an overview of existing implementations.

**Comment by simonbasle** [comment]
There was an attempt in #2254 but it has not made great progress and was impaired by Inkscape crashes when attempting to produce a SVG version. Binning this for now, we can always re-open if a greater motivator for such a diagram arises.
