### ISSUE TITLE
misdescription about flatMapIterable prefetch 

### ISSUE THREAD

**Issue by a8156268** [reactor/reactor-core#2257]
## Documentation Issue
this is the current description:
`prefetch - the maximum in-flight elements from each inner Iterable sequence`  
But, `Iterable` is not a publisher, so `prefetch` is not wort on it.
In fact, from source code，the `prefetch` is used as parameter to upstream.

## Improvement Suggestion
`the produced demand for upstream sources`

**Comment by simonbasle** [comment]
Yeah it should be something like `prefetch - the number of Iterables to request from the source upon subscription`
