### ISSUE TITLE
Could `Mono.block(Duration timeout)` throw `java.util.concurrent.TimeoutException`?

### ISSUE THREAD

**Issue by Mahoney** [reactor/reactor-core#2267]
`Mono.block(Duration timeout)` currently throws `IllegalStateException` if the timeout expires. This seems odd as a) it isn't an illegal state, it's a perfectly possible state that we're explicitly anticipating and b) the more correct `java.util.concurrent.TimeoutException` is thrown in similar circumstances when `Mono.timeout(Duration timeout).subscribe()` times out.

The code that throws the `IllegalStateException` is:
https://github.com/reactor/reactor-core/blob/232fe2e32bd6a99327b0f0f7b4efb4ca84f8e0e6/reactor-core/src/main/java/reactor/core/publisher/BlockingSingleSubscriber.java#L123

**Comment by simonbasle** [comment]
`TimeoutException` is a checked exception. It is not a problem on the `timeout` operator because it is not thrown but propagated through `onError`, but on `block` it would force us to add it to the signature of the method (and all current callers to declare a `catch` block).

**Comment by simonbasle** [comment]
Note that
```java
Mono.never()
    .timeout(Duration.ofSeconds(1))
    .block();
```
Throws a `Runtime(Reactive)Exception`, with the `TimeoutException` as the cause.
Maybe we could align on _that_ for `block(Duration)`?

This would at least bring consistency in how to deal with timeout exceptions in blocking code:

```java
try {
    longMono.block();
}
catch (SpecificRuntimeException sre) {
    //do something specific
}
catch (RuntimeException e) {
    if (Exceptions.unwrap(e) instanceof TimeoutException) {
        //deal with timeout
    }
    else {
        //generic exception
    }
}
```

**Comment by Mahoney** [comment]
Working in Kotlin, so I'd forgotten about the checked / unchecked problem. Though I guess it's a breaking change anyway as people might have code expecting an `IllegalStateException` for a timeout now...

I don't really have a clear solution, just wanted to raise it as something that confused me as a reactor newbie.

**Comment by simonbasle** [comment]
I'm inclined to leave it as is. The breaking change (or the breaking behavior that I suggested above) are IMO not worth it, especially considering that `block`ing is for corner cases only and is generally strongly discouraged.
