### ISSUE TITLE
feat(retry): Provide a retry.backoff with a maxBackoff parameter

### ISSUE THREAD

**Issue by davinkevin** [reactor/reactor-core#2276]
## Motivation

Following the upgrade to Reactor 3.3.6, I found out the `Mono#retryBackoff(long, duration, duration)` was deprecated,

I try to find an alternative to this method with the `Retry#backoff(long, duration)`, but there is no solution to define a minBackoff and maxBackoff in the provided method. In this case, the maxBackoff is defined with `Duration.ofMillis(Long.MAX_VALUE)` witch can be too long for me 😅.

## Desired solution

Having access to a method like this would be perfect: 

```java
public static RetryBackoffSpec backoff(long maxAttempts, Duration minBackoff, Duration maxBackoff) {
		return new RetryBackoffSpec(maxAttempts, t -> true, false, minBackoff, maxBackoff, 0.5d, Schedulers::parallel,
				NO_OP_CONSUMER, NO_OP_CONSUMER, NO_OP_BIFUNCTION, NO_OP_BIFUNCTION,
				RetryBackoffSpec.BACKOFF_EXCEPTION_GENERATOR);
	}
```

## Considered alternatives

As an alternative, I can copy/paste the definition and change it by myself, but we have to copy paste the `RetryBackoffSpec.BACKOFF_EXCEPTION_GENERATOR` too because it can't be accessed from external code.

## Additional context

Having the possibility to define such maxBackoff is very important for us because our clients, when they install our software, they can wait few days before making pieces accessible from each others… during this time, the backoff grows and without a max, they could have to wait few hours before the next try... which could be annoying.

**Comment by simonbasle** [comment]
I think you should be able to use `Retry.backoff(maxAttempts, minDuration).maxBackoff(maxDuration)`.

**Comment by davinkevin** [comment]
😍 I didn't notice this in the retry object 🤦‍♂️.
I will try it asap. 

You can close the issue if this is the way you want us to use the lib. 

BTW, very good rewrite of the retry API, 👍

**Comment by simonbasle** [comment]
> You can close the issue if this is the way you want us to use the lib.

Yes. Please re-open if something is missing, but I think you should be good with that method.

> BTW, very good rewrite of the retry API, 👍

Thanks a bunch, glad you like it 😄
