### ISSUE TITLE
Add Schedulers#dedicated / (newThread)

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#228]
Create a thread/executorservice per worker. But. Is that really useful @akarnokd given `Schedulers.elastic` ?

**Comment by dfeist** [comment]
Surely this should create a thread for each unit of work and not an `ExecutorService`.  Although, I'm not really sure what the use case for this is TBH?

**Comment by smaldini** [comment]
I was thinking about it, its a placeholder for something missing from rx.Schedulers. elastic should be more efficient with resource pooling but there are case or people just want to write kind of event loops or never ending stream that are singleton scope for the app. In this very case you might never release the thread until the end and so it defeats the purpose of elastic pooling.

**Comment by smaldini** [comment]
Also this is a role fulfilled in general by Topic and WorkQueueProcessor so we could just stick to improving the API and doc for these.

**Comment by smaldini** [comment]
Not fulfilling this for now as Schedulers.newSingle is enough.
