### ISSUE TITLE
Add `transformWithContext` as an in-chain alternative to `deferWithContext`

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2280]
## Motivation
Reading from the `Context` can be done in a source-like fashion thanks to `deferWithContext`, but in the middle of the operator chain one must either wrap the whole thing in deferWithContext (with is not likely to be possible, eg. the source might come from the "outside") or use `doOnEach` `Signal`, which is a bit harder to discover organically.

## Desired solution
`transformWithContext` would be a deferred transformation that allows the user to access the `Context` once, in a lambda in which the operator chain can be further composed.

Additional benefit is that accessing the `Context` is done once, where chaining `doOnEach#getContext()` would potentially traverse the chain of subscribers multiple times.

## Considered alternatives
An operator that materializes the `Context` along the data path (turning eg. a `Flux<T>` into a `Flux<Tuple2<Context, T>>`) was considered. See #2148 for a discussion why `transformWithContext` would likely still be a better alternative.

**Comment by bsideup** [comment]
@simonbasle can we discuss why not use `transformDeferred` with `BiFunction`? :) it has an advantage of being explicit about the deferred nature compared to `transformWithContext` (which _sounds_ like `transform` but with the `Context`, while in fact it needs to defer)

**Comment by simonbasle** [comment]
> can we discuss why not use transformDeferred with BiFunction?

This may cause issue with languages that have optional input parameters support like Kotlin, but I went with it in #2284, let's see.

**Comment by bsideup** [comment]
IIRC it was a problem with `Callable` (`{ return "yo" }`) vs `Function` (`{ return "yo"; }` with an implicit `it`), but `Function` and `BiFunction` should be fine.

cc @sdeleuze
