### ISSUE TITLE
Mono whenDelayError - incorrect or confusing documentation

### ISSUE THREAD

**Issue by martin-tarjanyi** [reactor/reactor-core#2289]
## Documentation Issue
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#whenDelayError-java.lang.Iterable-

> Aggregate given publishers into a new Mono that will be fulfilled when all of the given sources have completed. **If any Publisher terminates without value, the returned sequence will be terminated immediately and pending results cancelled.** Errors from the sources are delayed. If several Publishers error, the exceptions are combined (as suppressed exceptions on a root exception).

The highlighted sentence is not there in any of the other `when...` methods. More importantly, it doesn't seem to behave in the described way. Can you confirm this statement in the javadoc is incorrect and can be removed?

## Improvement Suggestion
Remove the sentence. Or alternatively replace it and emphasize that an empty Publisher will not cause cancellation for the rest of the Publsihers (as this behavior was not obvious for me).

## Additional context
Example code:
```java
Mono.when(Mono.empty(), Mono.delay(Duration.ofSeconds(2)).doOnNext(System.out::println)).block();
```
If the sentence were true, then the second Mono would not emit anything based on my understanding.

**Comment by simonbasle** [comment]
It looks like a mistake in the javadoc, indeed.
