### ISSUE TITLE
Unattributed code in RingBuffer

### ISSUE THREAD

**Issue by nitsanw** [reactor/reactor-core#229]
https://github.com/reactor/reactor-core/blob/master/src/main/java/reactor/core/publisher/RingBuffer.java

Looks like at some point this was forked from the @LMAX-Exchange disruptor, yet the copyright only acknowledges Pivotal

**Comment by smaldini** [comment]
The header was automatic indeed. It used to be there but since the class has been rewritten and parts of it moved around a few times it got lost at some point :(
Thanks @nitsanw !
