### ISSUE TITLE
Possible DirectProcessor-related regression on repeatWhenEmpty()

### ISSUE THREAD

**Issue by twoseat** [reactor/reactor-core#2291]
## Expected Behavior
The Cloud Foundry Java Client makes use of `repeatWhenEmpty()` when deploying apps. One tested scenario is a deployment that takes too long and causes a timeout. When running the tests this gives an expected `Application test-application-name timed out during staging` error.

## Actual Behavior
When run using `reactor-core 3.2.19` (via Spring Boot 2.1.16) we instead get `Can't deliver value due to lack of requests`. 

## Steps to Reproduce
Check out the java client project and run `./mvnw -Dtest=DefaultApplicationsTest#restageTimeout -DfailIfNoTests=false test`
Note that it only fails on the command line; IntelliJ works fine. One exception to that was when it briefly failed in IntelliJ, and I found that debugging breaks at certain points would cause it to pass again. This made me wonder if it was some sort of timing issue that the overhead of IntelliJ compared to Terminal might be affecting.

Via Simon Baslé we have the following, much simpler, reproducer:

```
	@Test
	public void cfclientIssue() {
		final Instant finish = Instant.now().plusSeconds(60);
		Mono.empty()
		    .hide()
		    .repeatWhenEmpty(iterations -> iterations
				    .map(iteration -> {
					    System.out.println("iteration #" + iteration);
					    return Duration.ofMillis(100 * Math.min(iteration, 20));
				    })
				    .flatMap(delay -> {
					    System.out.println("repeating with delay " + delay.toMillis());
					    if (Instant.now().isAfter(finish)) {
						    return Mono.<Long>error(new IllegalStateException("delay"));
					    }
					    return Mono
							    .delay(delay);
				    }, 1)
		    )
		    .log()
		    .block(Duration.ofSeconds(120));
	}
```

## Possible Solution
In my case changing this line (https://github.com/cloudfoundry/cf-java-client/blob/7ef9be7d1ef1920807e0cb94ca74f5cfa8798a4c/cloudfoundry-util/src/main/java/org/cloudfoundry/util/DelayUtils.java#L101) from `flatMap()` to `concatMap()` fixed the issue.

Comment from Simon: "somehow the concurrency of 1 causes trouble, I locally was able to reproduce, and switching to concurrency of 2 seemed to solve it"

**Comment by simonbasle** [comment]
best solution: use `concatMap(function, 1)`, or even simply `concatMap(function)`
