### ISSUE TITLE
Multiple calls to Mono.doOnSuccess if on reduce operation

### ISSUE THREAD

**Issue by jurna** [reactor/reactor-core#230]
Multiple calls to Mono.doOnSuccess is called (one with null, one with value) if reduce is used on Scheduled flux.
Test case: https://gist.github.com/jurna/353a2bd8ff83f0b24f0b5bc772077d61

**Comment by jurna** [comment]
Issue still exist (both in 3.0.3 and master). Provided unit test still fails. The one that is committed into reactor-core is changed slightly (changes in blockingOp) and passes.

**Comment by smaldini** [comment]
Ha misery it escaped our testing then, the initial fix we had locally did fix this version then we tried to include the updated design from @akarnokd and also made sure the test was testing parallelism (constant blocking wasn't showing parallelism). We'll have a look, very sorry about this, as a workaround you can hide() after reduce.

**Comment by smaldini** [comment]
Alternatively you can replace doOnSuccess by doOnNext
