### ISSUE TITLE
Enhance Javadoc diagram legend

### ISSUE THREAD

**Issue by philsttr** [reactor/reactor-core#2314]
## Documentation Issue

The diagram legend at the top of the Flux/Mono javadoc page is awesome.  However, the legend only mentions a very simple use case, and there are many other symbols used in the method diagrams that do not appear in the legend.

## Improvement Suggestion

It would be super-awesome if the legend included all symbols used in the method diagrams.

For example:
* Signal, and each Signal type (onNext, onSubscribe, onError, onComplete, etc)
* Triple right arrow.  [as seen here](https://projectreactor.io/docs/core/3.3.2.RELEASE/api/reactor/core/publisher/Mono.html#publishOn-reactor.core.scheduler.Scheduler-)
* Time
* The little horizontal oval with a dot in the middle [as seen here](https://projectreactor.io/docs/core/3.3.2.RELEASE/api/reactor/core/publisher/Mono.html#doOnError-java.util.function.Predicate-java.util.function.Consumer-)
* etc

**Comment by simonbasle** [comment]
I don't think the javadoc is the best place for this, but we should definitely include a link to a new section of the reference guide in which we explain how to read marble diagrams.

We have a `conventions.svg` that could be displayed in the reference guide, altough it is maybe a bit rough. and actually IIRC it doesn't include the symbol for `Scheduler` (the three orange triangles)

**Comment by rstoyanchev** [comment]
It would also be useful to link from the Javadoc of each operator to the legend. It could be something quite minimal and unobtrusive like a `<p><a href="...">Marble diagram</a>:` heading before or `<p><a href="...">Legend</a>` below the diagram.

**Comment by simonbasle** [comment]
> It would also be useful to link from the Javadoc of each operator to the legend. It could be something quite minimal and unobtrusive like a `<p><a href="...">Marble diagram</a>:` heading before or `<p><a href="...">Legend</a>` below the diagram.

@rstoyanchev in order to keep the PR focused on the diagram without the noise of changing the 400+ javadocs to link to the howto, let's consider that separately. If you still feel that is strongly beneficial, I can open a separate issue (one that can be tagged `good-first-issue`).
