### ISSUE TITLE
Deprecated processors should have a descriptive deprecated note

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#2317]
Currently, the deprecated processors have `@deprecated Prefer clear cut usage of Sinks`. but it does not say which one.

To easy the migration from Processors to Sinks API, we should add a better deprecation message per processor, with examples of how previous various constructs can be rewritten with this new Sinks API.

**Comment by rstoyanchev** [comment]
I think they used to be there but got lost in subsequent iterations.
