### ISSUE TITLE
Further refine the Sinks API: emitXxx vs tryEmitXxx

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2319]
## Motivation
The `emitXxx` API relying on users checking the return value is maybe too brittle, leaving too much room for users purely ignoring said return value.

## Desired solution
Double the API to offer a throw-vs-enum choice:
 - `void emitXxx()` which throws an exception
 - `Emission tryEmitXxx()` which doesn't throw but returns an `Emission`: the `try` prefix better conveys that failure mode is communicated through the returned enum

## Considered alternatives
 - Adding `orThrow()` to `Emission`, but it is easier to still ignore the `Emission` altogether

**Comment by bsideup** [comment]
Note from the call:

`emitXxx` should never block (unlike `EmitterProcessor`'s `onNext`) and fail fast. If busy loop is desired, one should use `tryEmitXxx`.

**Comment by simonbasle** [comment]
@reactor/core-team I wonder if the `exception` itself shouldn't be instead translated to an `emitError`... Do we _really_ want to throw as a first class citizen in a reactive context??

So `emitNext(t)`/`emitValue(t)` underlying failure conditions and reactions would be:
 - `FAIL_OVERFLOW` -> `Operators.discard(t)`, as well as `sink.emitError(backpressure overflow exception)`
 - `FAIL_TERMINATED` -> `Operators.onNextDropped(t)`
 - `FAIL_CANCELLED` -> `Operators.discard(t)`

For `emitError(e)`:
 - `FAIL_OVERFLOW` shouldn't happen
 - `FAIL_TERMINATED` -> `Operators.onErrorDropped(e)`
 - `FAIL_CANCELLED` -> do nothing

For `emitComplete()`/`emitEmpty()`:
 - `FAIL_OVERFLOW` shouldn't happen
 - `FAIL_TERMINATED` -> do nothing
 - `FAIL_CANCELLED` -> do nothing

If we really want to offer a possibility of throwing, the `.orThrow()` pattern on `tryEmitXxx` can be thought about again. wdyt?

**Comment by aneveu** [comment]
I think offering the `.orThrow()` pattern on `tryEmitXxx` would be interesting as it seems intuitive to me (one would usually expect a method to throw an exception after having tried something) and I like to idea to propose an `emitError(e)` instead of just throwing on `emitXxx`

**Comment by simonbasle** [comment]
I've added #2329 for the `orThrow()` improvement among others

**Comment by simonbasle** [comment]
note: `warn/api-change` only compared to M2. Most users should be fine keeping with `emitXxx`. Those who actually check the `Emission` will get a compilation error and can easily find spots to migrate to `tryEmitXxx`.
