### ISSUE TITLE
Make subscriber's ContextView available to signal callbacks

### ISSUE THREAD

**Issue by johncfranco** [reactor/reactor-core#2322]
Hello, I wrote a [small library](https://github.com/johncfranco/reactive-logger) that uses reactor-core, and along the way I noticed an opportunity for a new feature in the reactor-core API that would make my library easier to use, and I think it could make reactor-core a little easier to use in general, too.

The feature is making the subscriber's context available to the signal hooks connected to publishers through methods such as `doOnRequest`, `doOnNext`, `doOnComplete`, `doOnError`, `doOnCancel` and `doAfterTerminate`.
A [code example](https://github.com/johncfranco/reactive-logger/blob/develop/examples/reactor-netty/src/main/java/com/github/johncfranco/reactive/logger/examples/reactornetty/DelayService.java#L61) in my library uses `doOnCancel` to show how adding this capability could help make application code cleaner.

I wound up adding `...WithContext` versions of various `doOn*` methods.
In the `...WithContext` version of each method, the application callback takes an additional `ContextView` parameter.
Using a modified name rather than overloading the existing names avoids build errors arising from callbacks that are themselves overloaded with signatures having different numbers of parameters.
While such build errors can be resolved by an explicit cast, and while such overloaded callbacks seem unlikely to be common, I decided to play it safe.

### Some Implementation Notes

I started with `SignalPeek` and added a `CoreSubscriber<? super T>` parameter to each callback signature, then adjusted all references to the callback to pass the `CoreSubscriber` instance that was (almost always) already in scope at the point of use.
I added `CoreSubscriber<? super T>` rather than `ContextView` to minimize the impact on the existing hook support, and to avoid calling `currentContext()` unnecessarily.

I changed the implementations of the current `doOn*` methods in `Mono`, `Flux` and `ParallelFlux` affected by the `SignalPeek` changes to wrap the callback provided by the application with a lambda that fits the new signature but simply drops the new `CoreSubscriber` parameter.
The new `do*WithContext` methods wrap the application callback with a lambda that invokes the `currentContext()` method on the `CoreSubscriber` parameter to supply the `ContextView` parameter for the application callback.

There are other `do*` methods in `Mono` and `Flux`, such as `doFirst` and `doOnEach`, that don't use `SignalPeek`.
I left those alone for the time being: I thought it better to open this pull request first and find out what support exists for the main idea.
If the idea does receive support, I would be willing to add further changes for those methods to this pull request.

As for unit tests, the only new code is in the new `*WithContext` methods on `Mono`, `Flux`, and `ParallelFlux`.
My inclination would be to make three new files, `MonoSignalsWithContextTest`, `FluxSignalsWithContextTest` and `ParallelFluxSignalsWithContextTest`, and add tests specifically for the new `*WithContext` methods to those.
All the other changes seem to be covered by existing tests.
Would that be acceptable?

By the way, I'm new to reactor-core and to GitHub, but I've signed the Pivotal CLA.
I was confused about the proper procedure to follow and thought I should just open a pull request, but the repository wouldn't let me push my branch.

## Motivation
Give application callbacks access to the subscriber's context (through a `ContextView` parameter) so that they don't have to fish it out through some other means and save it to a local variable outside the chain.

## Desired solution
An overload of each `doOn*` method that accepts a callback that takes a `ContextView` parameter (in addition to any other parameters the callback for the original method takes).

## Considered alternatives
There is a workaround available, as shown in the [example](https://github.com/johncfranco/reactive-logger/blob/develop/examples/reactor-netty/src/main/java/com/github/johncfranco/reactive/logger/examples/reactornetty/DelayService.java#L61) I linked above, but it's ugly and seems error-prone.

## Additional context
I already implemented this locally, but found that I was not able to push my branch and open a pull request.  Do I need an administrator to give me permission to push branches?

**Comment by bsideup** [comment]
Hi @johncfranco,

Have you seen `transformDeferedContextual`?

**Comment by simonbasle** [comment]
> I already implemented this locally, but found that I was not able to push my branch and open a pull request. Do I need an administrator to give me permission to push branches?

On Github (and in git-based opensource work in general) you don't get rights to push directly to the primary repository (only trusted maintainers can do that). Instead, in Github terms you _fork_ the repository (making a copy specific to your account), then in that fork you create a feature-specific _branch_ out of the branch you want to work on (our maintenance branches are `3.2.x`, `3.3.x` and `master`), and start coding. Github will then allow you to push that branch to your fork and open a pull-request between the fork feature branch and the primary repository's target maintenance branch (eg. `johncfranco:myFeatureBranchForMaster` to `reactor:master`).

**Comment by simonbasle** [comment]
as for the idea of adding `Context[View]` to `doOnXxx` operators, we've thought about that for a long time and we've decided not to implement that feature. Mainly, we don't want to double the set of `doOn` operators.

Instead, we think that `deferContextual` and `transformDeferredContextual` provide two possible approaches that expose the `ContextView` at the start and middle of a chain of operators respectively.

Alternatively, there is the `doOnEach` operator that covers several other `doOn` through a single `Consumer<Signal>`, and said `Signal` has a `getContextView()` method. Only `onNext`, `onError` and `onComplete` signals are covered, though. (again, we just decided we wouldn't add a `doOnEach`-like operator that covers cancel and subscribe just for the purpose of accessing the context, as we now provide the deferContextual alternatives, see #1526)

**Comment by johncfranco** [comment]
@bsideup  or @simonbasle  could either of you explain how `transformDeferredContextual` takes care of the `doOnCancel` case?  I read #1526 but I still don't understand how to apply it to `doOnCancel`.

I think a widely-used library such as `reactor-core` is likely to face pressure to add ease-of-use features such as the extra `doOn*` overloads I proposed, but that's mainly intuition.  Now that I know they won't be available any time soon, I'll look into whether I can do anything in my library to make the workaround easier.

@simonbasle  thank you for setting me straight regarding the pull request protocol.  Rookie mistake!

**Comment by bsideup** [comment]
@johncfranco `Context` is a subscribe-time concept. You can as well rewrite your code with:
```java
return Flux.deferContextual(context -> {
        return log.info("delay {} requested", delayText)
                .zipWith(Mono.delay(delay))
                .elapsed()
                .map(Tuple2::getT1)
                .map(Duration::ofMillis)
                .map(Duration::toString)
                .flatMap(delayLengthText -> log.info("returning after delay {}...", delayLengthText)
                        .and(writeTextResponse(response, HttpResponseStatus.OK, delayLengthText)))
                .doOnCancel(() -> {
                    try (final MDCSnapshot snapshot = MDCSnapshot.of(log.readMDC(context).orElse(null))) {
                        log.imperative().info("delay request cancelled.");
                    }
                })
                .cancelOn(log.scheduler());
});
```

`transformDeferredContextual` just helps applying it in a middle of the chain:
```java
        return log.info("delay {} requested", delayText)
                .zipWith(Mono.delay(delay))
                .elapsed()
                .map(Tuple2::getT1)
                .map(Duration::ofMillis)
                .map(Duration::toString)
                .flatMap(delayLengthText -> log.info("returning after delay {}...", delayLengthText)
                        .and(writeTextResponse(response, HttpResponseStatus.OK, delayLengthText)))
                transformDeferredContextual((flux, context) -> flux.doOnCancel(() -> {
                    try (final MDCSnapshot snapshot = MDCSnapshot.of(log.readMDC(context).orElse(null))) {
                        log.imperative().info("delay request cancelled.");
                    }
                }))
                .cancelOn(log.scheduler());
```

**Comment by johncfranco** [comment]
@bsideup  belated thanks for your explanation.  Now I understand and see how `deferContextual` and `transformDeferredContextual` constitute a cleaner and more extensible approach than adding a separate overload for each signal handler, as I had done.  I've updated my library accordingly.
