### ISSUE TITLE
Explore a way to keep current `Schedulers` live while temporarily replacing the `Factory`

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2325]
## Motivation
Some tests might run with the `VirtualTimeScheduler` while other parts of the test infrastructure might also rely on decorating `Schedulers` (via the `Schedulers.Factory`) and keeping these decorated schedulers live for the duration of eg. a test class.

Unfortunately, setting up the `VirtualTimeScheduler` is destructive: it shuts down previously set schedulers.

## Desired solution
Add a way to capture the current live `Schedulers` and restore them.

This probably involves an object slightly different from the `Schedulers.Factory`, which responsability is to _create_ new `Schedulers`. Here we're talking about capturing a set of existing `Scheduler` instances (or rather likely `CachedScheduler`) in a black box object that can be passed back to `Schedulers` to restore said instances. The current `Factory` should probably also be saved.

## Considered alternatives
A special flavor of `Schedulers.Factory`, but that is impractical since the cached live schedulers are held by the `Schedulers` class directly, as package private `CachedScheduler` instances in atomic references.

## Challenges
There is no way around adding methods and specific support for that directly on `Schedulers`, since it is the class that holds live instances of `Scheduler`.

**Comment by rstoyanchev** [comment]
For more further background, see also https://github.com/spring-projects/spring-framework/issues/25529.
