### ISSUE TITLE
Can make `ParalleFlux.subscribe(CoreSubscriber<? super T>[])` public?

### ISSUE THREAD

**Issue by minwoox** [reactor/reactor-core#2328]
## Motivation
Hello! 😄 
I'm making hooks that propagate thread-local contexts in our [framework](https://github.com/line/armeria/) during the Reactor operations.
We already have a one for [RxJava](https://github.com/line/armeria/tree/armeria-0.99.9/rxjava3), but not for Reactor.
I have almost implemented the hooks for `Flux` and `Mono`, but I couldn't do it for `ParallelFlux`.
It's because I couldn't just delegate this method to the original `ParallelFlux`.
```
protected abstract void subscribe(CoreSubscriber<? super T>[] subscribers);
```
https://github.com/reactor/reactor-core/blob/v3.4.0-M2/reactor-core/src/main/java/reactor/core/publisher/ParallelFlux.java#L954
Is there any chance that we can make this method as public, please?

## Desired solution
Make `ParalleFlux.subscribe(CoreSubscriber<? super T>[])` public.

**Comment by simonbasle** [comment]
It is _protected_ though. Couldn't you create a wrapper by inheriting from `ParallelFlux`?

**Comment by minwoox** [comment]
Thanks for the reply!
Yeah, I'm trying to make a wrapper:
```java
class ParallelFluxWrapper extends ParallelFlux<Object> {

    private final ParallelFlux<Object> source;

    ContextAwareParallelFlux(ParallelFlux<Object> source, ...) {
        this.source = source;
        ...
    }

    ...

    @Override
    protected void subscribe(CoreSubscriber<? super Object>[] subscribers) {
        // Can't just do this because the method is not public.
        source.subscribe(subscribers);
    }
}
```
However, I can't just delegate `subscribe(...)` call to the original `ParallelFlux<Object>` because it's protected.
Also, it's hard for me to just implement the method since there are several `ParallelFlux` implementations.
So I thought changing the modifier of the method was the best option. 😄

**Comment by minwoox** [comment]
Thank you!
