### ISSUE TITLE
Add ForkJoinExecutorService support in fromExecutorService

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#233]

**Comment by dfeist** [comment]
Isn't it parallel, particularly when `parallelism <= cores`, that would benefit most from using ForkJoinPool instead of a pool of single-threaded executors with no work stealing?

**Comment by smaldini** [comment]
The work stealing happens at publishOn level (or subscribeOn) and all combinatory operators (or operators traversed by multiple thread, e.g. timed operators). @akarnokd didn't find any benefit in his benchmarks when we tried the various schedulers, however if you happen to use a Scheduler outside reactor Flux/Mono then it is going to fallback to your explaination.

**Comment by dfeist** [comment]
@smaldini Mind linking to the benchmarks here? I'd be interested to take a look...

**Comment by smaldini** [comment]
They are not online (I think ?) we were discussing over the first half of the year when David added Schedulers to RSC.

**Comment by rajinisivaram** [comment]
@smaldini @simonbasle What do I need to do for this one? Thanks.

**Comment by simonbasle** [comment]
Fixed in reactor-extras with commit reactor/reactor-addons@e3daa51
