### ISSUE TITLE
Flux#limitRequest vs Flux#take

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#2339]
I was expecting `Flux#limitRequest` to not cancel upstream when the request is fulfilled (otherwise, it is unclear why it exists when `Flux#take` does essentially the same).

The following snippet demonstrates the problem:
```java
Flux.range(0, 10)
    .log("range")
    .limitRequest(2)
    .log("limitRequest")
    .blockLast();
```

The output:
```
17:58:11.359 [main] INFO  limitRequest - request(unbounded)
17:58:11.359 [main] INFO  range - | request(2)
17:58:11.359 [main] INFO  range - | onNext(0)
17:58:11.359 [main] INFO  limitRequest - onNext(0)
17:58:11.359 [main] INFO  range - | onNext(1)
17:58:11.359 [main] INFO  limitRequest - onNext(1)
17:58:11.360 [main] INFO  range - | cancel() <-- cancelled right after receiving onNext(1)
17:58:11.360 [main] INFO  limitRequest - onComplete()
```

We should either deprecate `limitRequest` in favour of (more logical) `Flux#take` or make it not cancel.

**Comment by simonbasle** [comment]
Maybe this plan could work:
 - in 3.4.x:
   - alias `take(int)` to `takeEager(int)`
   - document that `take` will behave like `limitRequest` in 3.5.0
 - in 3.5.0:
   - replace behavior of `take` with that of `limitRequest`
   - deprecate `limitRequest`, earliest removal 3.6.0

**Comment by simonbasle** [comment]
to ensure consistency, we also need to check how other `takeXxx` operators behave. It would feel natural that the most common behavior wrt to upstream request ends up being the default behavior in `take(int)` itself, right?

**Comment by simonbasle** [comment]
The new plan is to introduce a `take(int, boolean limitRequest)` variant. This allows unambiguously replacing both `take(int)` and `limitRequest(int)`, which in turn means we can deprecate the `limitRequest` name right away.

Plus, apart from the unbounded request made by `take(n, false)`, the observable behavior of both variants doesn't vary that much, so it is safer to implement such a change.

The planned actions and recommended migration path are:

 - in 3.4.x:
   - 👤 switch all user code to the 2-arguments `take(int, boolean)`
   - 📝 `limitRequest` will be deprecated (in favor of `take(n, true)`)
   - 📝`take(int)` will continue behaving as is (ie `take(n, false)`)
 - in 3.5.0:
   - 📝`take(int)` will change behavior to `take(n, true)`
   - 👤 all remaining usage of `take(int)` should thus be changed to `take(n, false)`, and usages of either `limitRequest` or `take(n, true)` can now be changed to `take(n)`
   - that said, the unbounded behavior is an optimization so even if no change is made, the only observable difference should mostly be the amount requested upstream...
 - in 3.6.0 at the earliest
   - 📝 `limitRequest` is removed
