### ISSUE TITLE
SerializedManySink should not have a queue and fail fast on non-serialized access

### ISSUE THREAD

**Issue by bsideup** [reactor/reactor-core#2342]
The current implementation ignores the result of `tryEmitNext` in case of a non-serialized emission:

https://github.com/reactor/reactor-core/blob/b540b5d69735505f7ece6c1baebb8baa8a1e6895/reactor-core/src/main/java/reactor/core/publisher/SinksSpecs.java#L158-L161

We should consider adding something like `Emission.FAIL_NON_SERIALIZED` that will fail fast and signal non-serialized access, and that's the best effort we can make instead of queuing the emissions and returning `Emission.OK`.

**Comment by bsideup** [comment]
Reproducer:
```java
DirectProcessor<Object> processor = DirectProcessor.create();
SerializedManySink<Object> manySink = new SerializedManySink<>(processor, Context::empty);

CompletableFuture<Object> muchFuture = processor.doOnNext(o -> {
	assertThat(processor.isTerminated()).as("terminated").isFalse();
	// Transition to the TERMINATED state
	processor.emitComplete();
	assertThat(processor.isTerminated()).as("terminated").isTrue();
	assertThat(processor.tryEmitNext("second")).as("direct emit").isEqualTo(Emission.FAIL_TERMINATED);

	assertThat(manySink.wip).as("wip").isNotZero();
	assertThat(manySink.tryEmitNext("second")).as("second").isEqualTo(Emission.FAIL_TERMINATED);
}).single().toFuture();

assertThat(manySink.tryEmitNext("first")).as("first").isEqualTo(Emission.OK);
muchFuture.get(5, TimeUnit.SECONDS);
```
```
org.opentest4j.AssertionFailedError: [second] 
Expecting:
 <OK>
to be equal to:
 <FAIL_TERMINATED>
```

**Comment by simonbasle** [comment]
doesn't it defeat the purpose of having a serialized wrapper that is supposed to do the external synchronization for you?

**Comment by bsideup** [comment]
@simonbasle I don't think we can have such (see my previous comment with the reproducer)

There is still a benefit of having it (the WIP check), but IMO that's the best we can provide
