### ISSUE TITLE
Window operator behaves differently, than the JavaDoc diagram suggests, when boundary publisher completes

### ISSUE THREAD

**Issue by j-mok** [reactor/reactor-core#2346]
## Documentation Issue
Documentation for the `window` operator that takes a boundary-signalling publisher as an argument ([here](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#window-org.reactivestreams.Publisher-)) has a diagram that suggests that a completion signal from the `boundary` publisher is effectively ignored. Specifically, the blue signal from the source gets emitted in the latest window after the `boundary` publisher completes.

In reality completion signal from the `boundary` publisher completes both the latest window and the whole windows flux (verified with 3.3.9.RELEASE). This behavior seems to correspond with the textual description of the `boundary` parameter:

> boundary - a Publisher to emit any item for a split signal and **complete to terminate**

## Improvement Suggestion
Fix the diagram so that it is consistent with textual docs and actual behavior.

## Additional context

![2020-08-28 10_08_08-Flux (reactor-core 3 3 9 RELEASE) - Vivaldi](https://user-images.githubusercontent.com/24955615/91537439-98c7ba80-e916-11ea-9f8e-9881af24126e.png)

**Comment by simonbasle** [comment]
The merge commit that fixes this in 3.3.x is 847bbb49c93be59da0279732d8787170dabda9e1 (released in `3.3.11.RELEASE`)
