### ISSUE TITLE
Explain concept of Fusion and Workers

### ISSUE THREAD

**Issue by magware-dev** [reactor/reactor-core#2349]
The documentation at https://projectreactor.io/docs/core/release/reference/ is amazing, because it also explains core concepts of reactive programming.

I am currently learning project reactor and want to point out two things that I struggle with and can not find documentation for.

## Documentation Issue

**Fusable Interface**: It shows up when using the `.log()` operation and also while browsing the core-code, many methods use the `reactor.core.Fuseable` interface (often in `instanceof` checks). Apparently a Publisher can be Fusable and I would like to know what that means.

**Worker Interface**: When looking into the Schedulers there is the `reactor.core.scheduler.Scheduler.Worker` interface. I found some doc about Schedulers (4.5), but no real mention of the Workers. As far as I understand, all operations request a Worker from a Scheduler to run and it looks like they play a really important role. So my suggestion is to mention them in the 4.5 Schedulers sections.

## Improvement Suggestion

Add "Fusable" and "Scheduler.Worker" sections to the doc that explains those concepts.

**Comment by chemicL** [comment]
When it comes to `Scheduler.Worker`, I think the Javadoc is quite sufficient to grasp the idea. E.g.

	/**
	 * Creates a worker of this Scheduler.
	 * <p>
	 * Once the Worker is no longer in use, one should call dispose() on it to
	 * release any resources the particular Scheduler may have used.
	 *
	 * It depends on the implementation, but Scheduler Workers should usually run tasks in
	 * FIFO order. Some implementations may entirely delegate the scheduling to an
	 * underlying structure (like an {@link ExecutorService}).
	 *
	 * @return the Worker instance.
	 */
	Worker createWorker();

For operator fusion and the significance of the `Fuseable` interface:

* some Javadoc explanations are provided too
* @akarnokd wrote comprehensive articles about operator fusion and repeating these would be quite an undertaking, so I'll just leave the links: [Operator-fusion (Part 1)](https://akarnokd.blogspot.com/2016/03/operator-fusion-part-1.html), [Operator-fusion (part 2 - final)](https://akarnokd.blogspot.com/2016/04/operator-fusion-part-2-final.html)

Leaving the above for future seekers, but with the fact that for almost 4 years nobody picked this up, I don't think we'll find the time to explain these internals more. Perhaps someone decides to do so in the future - we can always welcome a PR :)
