### ISSUE TITLE
Error in marble diagram for Mono.transformDeferred

### ISSUE THREAD

**Issue by bbukaty** [reactor/reactor-core#2358]
In the documentation for `Mono.transformDeferred`, specifically in the marble diagram:
![image](https://user-images.githubusercontent.com/19913542/92152643-de352d80-edd7-11ea-8a20-43dbc33e089a.png)

the illustration shows the second subscriber getting a stream with two elements, but if I understand this example's usage of `repeat`, there should be three elements.

Here's the source for this marble diagram in this repo:
[https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/doc-files/marbles/transformDeferredForMono.svg](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/doc-files/marbles/transformDeferredForMono.svg)

If I'm correct and this is an error, `Flux.transformDeferred` has a similar issue.

**Comment by ericbottard** [comment]
Targeting 3.3.x branch.

There is indeed an error with the diagram (should show 3 circles as you pointed out). Even more so, the `Mono.transformDeferred()` only accepts a Mono producing function, so `repeat` is not a good example.

Will update both.
