### ISSUE TITLE
Mono.log() leads to high memory consumption 

### ISSUE THREAD

**Issue by ahiltenkamp** [reactor/reactor-core#2370]
Using  `Mono.log()` creates for each Mono / Source operator a new Logger in logging frameworks like Logback even when the log level is set to error.  Logger frameworks like Logback keep a Logger Repositioy / Cache which will be filled with a lot of Loggers until, in the worst case, an `OutOfMemoryError `

 ```
    @Test
    public void test() {
        final int count = 10;
        
        for (int i = 0; i < count; i++) {        
            var mono = Mono.just("sample string")
                    .map(s -> s);
            mono.log();
            mono.block();
        }
        
        ch.qos.logback.classic.LoggerContext lc = 
                (ch.qos.logback.classic.LoggerContext)org.slf4j.impl.StaticLoggerBinder.getSingleton()
            .getLoggerFactory();
        
        var size = lc.getLoggerList().stream()
            .map(l -> l.getName())
            .filter(n -> n.startsWith("reactor.Mono.MapFuseable."))
            .collect(Collectors.toList())
            .size();
        
        assertEquals(count, size);
    }

```
Increase `count` in the test and you, depending on your heap size, you'll get an `OutOfMemoryError`.

Potential "Real World" usage:  
 ```
WebClient webClient = ...; 
webClient.get()
                .uri("http://example.net")
                .retrieve()
                .bodyToMono(String.class)
                .log();
 ```

In my opinion at least it should be documented that using this method can cause massive memory problems when used in real / live applications.

**Comment by simonbasle** [comment]
You can A) directly provide a reactor `Logger` instance or B) set logging with a `String category`, which may reuse an existing similarly-named logger in the underlying repository.
