### ISSUE TITLE
Publish() and Connect() change their buffering behavior after the first subscribe and cancel

### ISSUE THREAD

**Issue by jonenst** [reactor/reactor-core#2379]
## Expected Behavior
The buffering behavior should be the same between the case where there has not been a subscription, and the case where there has been a subscription which was later cancelled. This makes server behave differently between when they start and when at least one client has connected/disconnected, which is very error prone.

## Actual Behavior
The buffering behavior changes after the subscribing and cancelling.

## Steps to Reproduce

```java
package com.mycompany.app;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

import reactor.core.Disposable;
import reactor.core.publisher.ConnectableFlux;
import reactor.core.publisher.EmitterProcessor;

public class AppTest 
{
    @Test
    public void test()
    {
        EmitterProcessor<String> emitter = EmitterProcessor.create();

        ConnectableFlux<String> cf = emitter.publish();
        cf.connect();

        //This "BEFORE" message is discarded
        emitter.onNext("BEFORE");

        boolean[] afterSeen = new boolean[1];
        Disposable d1 = cf.log().subscribe(str -> {
            if ("BEFORE".equals(str))
                throw new RuntimeException("should not see messages before subscription");
            afterSeen[0] = true;
        });

        afterSeen[0] = false;
        emitter.onNext("AFTER");
        assertTrue(afterSeen[0]);

        d1.dispose();

        //This "BEFORE" message is *NOT* discarded
        emitter.onNext("BEFORE");

        Disposable d2 = cf.log().subscribe(str -> {
            if ("BEFORE".equals(str))
                throw new RuntimeException("should not see messages before subscription");
        }); // crashes, "BEFORE" is buffered and delivered here

        afterSeen[0] = false;
        emitter.onNext("AFTER");
        assertTrue(afterSeen[0]);

        d2.dispose();
    }
}
```

## Possible Solution
Always discard messages, or always buffer them when there are no current subscriptions. (In my case, I want to discard the messages; but I can so that by manually subscribing right after connect(); so maybe always buffer is preferable)

## Your Environment

* Reactor version(s) used: 3.3.9
* Other relevant libraries versions (eg. `netty`, ...): no other libraries
* JVM version (`javar -version`): openjdk version "1.8.0_232" AND openjdk version "11.0.7" 2020-04-14
* OS and version (eg `uname -a`): linux  5.1.18-200.fc29.x86_64

**Comment by simonbasle** [comment]
The `EmitterProcessor` itself has multicast capabilities and has its own "hot" behavior, so publishing and connecting it doesn't make much sense. Does your real usecase combine `EmitterProcessor` and `publish().connect()`?

**Comment by jonenst** [comment]
Hi @simonbasle , sorry I didn't see your message. My use case was writing a server that accepts websocket connections and relays messages from a single activemq queue to all the currently connected websockets. It uses spring cloud stream to read messages from the queue by declaring a Consummer<Flux> bean, so I don't know what kind of flux I'm getting (although I think that I debugged it and saw that spring cloud stream was using an emiterProcessor, hence the issue). The code is available here if you are interested and have any advice: https://github.com/gridsuite/notification-server/blob/master/src/main/java/org/gridsuite/notification/server/NotificationWebSocketHandler.java
