### ISSUE TITLE
`Flux#then(Mono<V>)` can be ambiguous with `Flux#then(Publisher<Void>)`

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#238]
When passing in a `Mono<Void>` to `Flux#then(Mono<V>)`, the compiler complains that the call is ambiguous, citing the `Flux#then(Publisher<Void>)` method.

**Comment by simonbasle** [comment]
One possible solution would be to rename the `then(Mono<V>)` method with a different name so the ambiguity is removed. However that would reintroduce an API dissymmetry with the `Mono` class (see #198, cc @ericbottard)

**Comment by simonbasle** [comment]
after discussing it with @smaldini and @sdeleuze, we'll wait for 3.1.0 to introduce the `then(Mono<V>)` signature to `Flux` (won't make it to 3.0). The clashing signature with `Publisher<Void>` will be renamed `thenEmpty`.

**Comment by smaldini** [comment]
I propose this: 
- Mono.then(function) -> then
- then(publisherVoid) -> thenEmpty
- then(Supplier<publisherVoid>) -> thenEmpty(defer(() -> publisher)) // remove Supplier alias
- then(mono) -> then(mono)
- then() -> thenEmpty
- then(Supplier<mono>) -> then(defer(() -> mono))  // remove Supplier alias
- thenMany(Supplier<Publisher<V>>) -> thenMany(defer(() -> publisher))  // remove Supplier alias
- thenMany(Publisher<V>) -> thenMany(publisher<V>)

cc @sdeleuze @nebhale @ericbottard

**Comment by smaldini** [comment]
Deprecation tracked in #323
