### ISSUE TITLE
`Flux#collect` do collect when empty

### ISSUE THREAD

**Issue by ghkim3221** [reactor/reactor-core#2381]
From the empty `Flux`, there is `onNext` signal when calling `collect`. Is this intended?

## Expected Behavior

Success this unit test:

```kotlin
@Test
fun test() {
    StepVerifier.create(Flux.empty<String>().collect(Collectors.joining(",")))
        .verifyComplete()
}
```

## Actual Behavior

Could not make a successful behavior even if expect next.

```kotlin
@Test
fun test() {
    StepVerifier.create(Flux.empty<String>().collect(Collectors.joining(",")).log())
        .expectNext()
        .verifyComplete()
}

// exception
// expectation "expectComplete" failed (expected: onComplete(); actual: onNext())

// log
// reactor.Mono.StreamCollector.1           : | onSubscribe([Fuseable] MonoStreamCollector.StreamCollectorSubscriber)
// reactor.Mono.StreamCollector.1           : | request(unbounded)
// reactor.Mono.StreamCollector.1           : | onNext()
// reactor.Mono.StreamCollector.1           : | cancel()
// reactor.Mono.StreamCollector.1           : | onComplete()
```

## Steps to Reproduce

```java
@Test
public void repoCase() {
    StepVerifier.create(Flux.<String>empty().collect(Collectors.joining(",")))
        .expectNext()
        .verifyComplete()
}
```

## Possible Solution

I don't know yet 😢 

## Your Environment

* Kotlin 1.4.0
* Reactor version(s) used: 3.3.8
* Other relevant libraries versions (eg. `netty`, ...): `spring-boot-starter-webflux:2.3.2`
* JVM version (`javar -version`):
```
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
* OS and version (eg `uname -a`):
```
Darwin AL01540922.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
```

**Comment by simonbasle** [comment]
`expectNext(T...)` takes a vararg. Here the array is empty, and so `expectNext` assume you don't really expect any `onNext` signal. But `collect` does produce an `onNext` signal on an empty source: the empty `String`.

`expectNext("")` will fix the test, validating the intended behavior.
