### ISSUE TITLE
Let `AutoDisposableRule` implement JUnit5 `(Before|After)EachCallback`

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2388]
## Motivation
`@Rule` isn't applicable in JUnit5 anymore, there's just partial support of `@ExternalResource` through legacy compatibility artifact.

## Desired solution
The `AutoDisposableRule` could implement the necessary callbacks from JUnit5 and be directly used with the `@RegisterExtension` canonical JUnit5 mechanism, in addition to `@Rule` in JUnit4.

**Comment by ericbottard** [comment]
Done as part of https://github.com/reactor/reactor-core/issues/2344

**Comment by ericbottard** [comment]
This has been rewritten as a JUnit 5 Extension
