### ISSUE TITLE
DelayElement with Batches of Data in Parallel

### ISSUE THREAD

**Issue by apratim001** [reactor/reactor-core#2391]
Currently there is support to emit elements from a Flux of data with a constant delay of any duration. But this setup only supports emission of a Single element. There is no provision of emitting a Batch of elements(say 4-5 at one go) with this delayElement method. 

## Motivation

Currently we are reading from a Flux source which will be emitting a few thousand records, and with delay, the time taken to reach to the final element will be very high and we were trying to read elements in batches and that too with some delay in between batches.
## Desired solution

It would be great if there is the provision of emitting a batch of elements at a specified delay maybe with a modified version of the same delayElements method.

**Comment by simonbasle** [comment]
I think `windowTimeout` would fit the bill here, just `concatMap` the windows afterwards to get back to a `Flux<T>`. Or alternatively, `buffer(n).delayElements(duration).concatMapIterable(Function.identity())`.

**Comment by apratim001** [comment]
Thanks Simon, buffer does work. 

But it would have been a wee bit more helpful if we had another overload for delayElements as delayElements(duration, noOfElements) where noOfElements are number of elements produced at every go.

**Comment by simonbasle** [comment]
nope, we favor composition of operators that are good at one particular thing over adding overloads for corner cases. thanks for confirming `buffer` works.
