### ISSUE TITLE
Make Sinks.Many-One-Empty Scannable for TERMINATED/CANCELLED

### ISSUE THREAD

**Issue by JamesChenX** [reactor/reactor-core#2394]
## Motivation

We need to know whether a sink has been disposed and **the feature is supported by FluxProcessor** but it is deprecated as mentioned in 3.4.0-RC1 so we don't resort to it.

## Desired solution

Solution: 
Expose a public method like "isDisposed" to indicate whether a sink has been disposed.

```
Sinks.Many<Object> sink = Sinks.many().unicast().onBackpressureBuffer();
sink.tryEmitComplete();
boolean isDisposed = sink.isDisposed(); // We want something like this
```

## Considered alternatives

No. It's also unacceptable if we have to introduce a variable to indicate whether a sink has been disposed by ourselves.

## Additional context

version: reactor-core-3.4.0-RC1

**Comment by simonbasle** [comment]
Isn't that what the `Emission` returned by `tryEmitComplete()` is for? With `tryEmitComplete() == FAIL_TERMINATED` for instance... Granted, technically you'd also want to check for `Emission.FAIL_CANCELLED` as well.

Looking at eg. `EmitterProcessor#isDisposed()`, it is currently equivalent to `isTerminated() || isCancelled()`, so you'd have to check `tryEmitComplete()` for `Emission.FAIL_TERMINATED` OR `Emission.FAIL_CANCELLED` results.

> It's also unacceptable if we have to introduce a variable to indicate whether a sink has been disposed by ourselves.

In that case, maybe a helper method on the `Emission` would fit the bill, like `isIn(Emission... acceptableResults)`?

```java
boolean isDisposed = sink.tryEmitComplete().isIn(FAIL_TERMINATED, FAIL_CANCELLED);
```

**Comment by JamesChenX** [comment]
@simonbasle The code mentioned above is just an example. In our real projects, we just expose the sink instance in a class so that other codes can use the sink instance as they expected and we don't know whether these codes will dispose it or not. So it's impractical for us to get the return value of tryEmit*.

And although we can make the sink instance private and expose methods to manage, its lifecycle it's troublesome and it's should be done by the sink itself.

**Comment by simonbasle** [comment]
So far the `Sinks.Many` interface doesn't expose `isDispose()`, but it doesn't implement `Disposable` at all either. Using the sink amounts to calling `tryEmitNext`/`tryEmitComplete()`...

Can you clarify in a scenario where class `A` creates the sink and shares it with class `B`, in what case would class `A` need to verify the disposed status of the sink?

`if (!sink.isDisposed()) emitComplete()` is brittle, because between the two calls the sink might get disposed. `Emission result = sink.tryEmitComplete()` is more atomic in that sense, so `B` code that relies on the sink not being disposed should use `tryEmitComplete`. If `A` also uses `tryEmitComplete()`, both will be able to react if the other has terminated the sink.

**Comment by JamesChenX** [comment]
It's also acceptable for us to know the status of a sink and check if the sink has been disposed by ourselves as I notice each sink implementation maintain a "state".

Our scenario:

Our project is an instant messaging project.
The server has a class named "UserSession" that holds a sink for inbound pending user messages.
(UserSession: every online user has their own UserSession instance
The sink: If user A wants to send a message to user B, the server will emit the message via the sink for user B)

The project also has a heartbeat mechanism meaning that if the client (user) doesn't send a heartbeat to the server in a specified time, the server needs to close the sink and the session actively. For each timer task, **they need to know if the session has been closed (we want to depend on the state of the sink so that we don't need to repeat the job that the underlying FluxProcessor has done the job to use a variable to indicate the status of the sink)**. If the session has been closed, the timer task should do nothing and if the session is open, the timer task will recurse (The timer task is one-shot. BTW, we use HashedWheelTimer of Netty) or close the session.

The code looks like:
![image](https://user-images.githubusercontent.com/44962329/93949851-5017eb80-fd74-11ea-8318-b9560c0389a8.png)

For the reasons above the heartbeat task timer needs to know whether the sink has been disposed (it's very easy for Processor to check if the Processor has been disposed by "myProcessor.isDisposed()")

**Comment by simonbasle** [comment]
we'll probably have `Sinks.Many|One|Empty` implement `Scannable`, as a middle ground that doesn't encourage using getters over more atomic check of `tryEmitXxx` results. `session.isOpen()` I guess could then delegate to `sink.scan(Attr.TERMINATED) && sink.scan(Attr.CANCELLED)`.

**Comment by JamesChenX** [comment]
It is acceptable and should help other developers migrated from Processor. Thanks for your help.

**Comment by rupweb** [comment]
Please can you take a look at https://stackoverflow.com/questions/66464896/in-reactor-sinks-many-what-is-equivalent-to-emitterprocessor-oncancel
