### ISSUE TITLE
Cancel is invoked on retry

### ISSUE THREAD

**Issue by winster** [reactor/reactor-core#2396]
```
Mono<Object> mono = Mono.error(new Exception()).doOnCancel(() -> log.info("doOnCancel")).retryWhen(Retry.backoff(2, Duration.ofSeconds(3)));
        StepVerifier.create(mono).verifyError();
```

Above code will log `doOnCancel`. Is this a bug?
Is it related to https://github.com/reactor/reactor-netty/issues/741 ?

**Comment by simonbasle** [comment]
Yes, that is intended. Technically, we have to accommodate the possibility that the companion `Flux` (the one that drives retries) can be completed / errored independently from a source signal. To do that, the source is cancelled whenever said companion terminates.
