### ISSUE TITLE
Make GroupedFlux#key non-nullable

### ISSUE THREAD

**Issue by camsteffen** [reactor/reactor-core#2397]
It looks like this was intended to be done but was forgotten. I couldn't find any possibility for null in the current implementations of `GroupedFlux`.

History: #730, #748, e01c738

**Comment by simonbasle** [comment]
Indeed, if the `#key` can be proven to be non-null 👍 
I don't remember exactly what the deal was with the original issue and using `String` as a key...

This would target 3.4.0 for safety, since technically downstream projects could implement `GroupedFlux` with a null key...

**Comment by camsteffen** [comment]
> Would you like to submit a PR @camsteffen ?

Done!
