### ISSUE TITLE
Round of Operator promotion from Stream to Flux/Mono

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#24]
Initial feedbacks and new capabilities in Stream are encouraging some selected promotions/additions from Stream API to Mono/Flux.
Likely candidates for vote :
- [ ] `Mono#justOrEmpty`
- [ ] `Mono#concatWith`
- [ ] `Mono#timeout`
- [ ] `Flux#timeout`
- [ ] `Mono#cache`
- [ ] `Flux#cache`
- [ ] `Flux#single`
- [ ] `Flux#take`
- [ ] `Flux#filter`
- [ ] `Mono#repeat`
- [ ] `Mono#repeatWhen`
- [ ] `Flux#repeat`
- [ ] `Mono#afterComplete(Supplier)`

**Comment by sdeleuze** [comment]
`Mono#after` already exists, isn't it?

**Comment by smaldini** [comment]
`Mono#after` exists but doesn't react only on complete (it does react on error too). Both behavior being acceptable, this is a valid user request (not mine).

**Comment by sdeleuze** [comment]
Ok I see the need, but I don't realy like the API proposed. What about adding just `Mono<Void> afterComplete()`?

**Comment by smaldini** [comment]
`afterComplete()` works too , updating

**Comment by sdeleuze** [comment]
:+1:

**Comment by rstoyanchev** [comment]
I'm sure all of these come from actual cases encountered but I'm not in favor of voting in bulk. At the risk of a extra formality could we follow a more regular routine where a ticket is created (preferably by whoever has the case) to request an operator. This allows a more focused discussion and hopefully better decisions. It also leaves a trail for anyone to see or comment on. If we agree I'd be happy to make the case for `justOrEmpty` and `cache`.

**Comment by smaldini** [comment]
Sure @rstoyanchev I actually just tried to keep them somewhere and didn't take the time to do separate issues.

**Comment by rstoyanchev** [comment]
Okay so I've created #25 and #26. Let's close this one and have separate tickets drive the request for additional ones. They all look useful, and have some thoughts on a few, but since we are trying to keep a distinction between Core and Stream, it would be better if we discussed them in context individually.

**Comment by smaldini** [comment]
Ok @nebhale if you can re-refer to afterComplete in a separate issue to keep track of it :+1:

**Comment by smaldini** [comment]
@sdeleuze if you can track `take` and anything else you had in mind in separate issues too.

**Comment by smaldini** [comment]
Extra note, implementing mono operators only actually save the operator cost most of the time, double implementing to Flux forces to migrate operator as in Stream to core
