### ISSUE TITLE
doFinally of Flux is not working with Java 11

### ISSUE THREAD

**Issue by fintechee** [reactor/reactor-core#2403]
Hi,

I encountered an issue.

Flux.from(jmsConfiguration.getStreamQuotesSource()).onBackpressureDrop().map(Message::getPayload).doFinally(data->{})
doFinally was not triggered after I terminate the browser tab or refresh the page.

It worked with Java 8, but doesn't work with Java 11.
Please help me solve it, many thanks.

**Comment by simonbasle** [comment]
what browser? what page? what is `jmsConfiguration`? There's nothing in here for us to work with, and the fact that it works on Java 8 makes it unlikely that Reactor is the root cause here.

**Comment by fintechee** [comment]
All browsers.
what page? The pages sent XHR that involved server-sent-event
jmsConfiguration is a JMS configuration class and getStreamQuotesSource returned an object to provide the stream.
BTW, I have found another alternative to bypass solving the problem.
