### ISSUE TITLE
Replay processor with timeout doesn't evict on terminal signal

### ISSUE THREAD

**Issue by Alexander-Nalbandyan** [reactor/reactor-core#2413]
## Expected Behavior
According to the documentation of ReplayProcessor with timeout it should evict on terminal signal if the age of item exceeds the maxAge but that doesn't happen. 

> Note that terminal signals (onError and onComplete) trigger eviction as well. For example, with a max age of 5, the first item is observed at T=0, then an onComplete signal arrives at T=10. If an subscriber subscribes at T=11, it will find an empty ReplayProcessor with just an onCompleted signal.

## Actual Behavior
As described above elements didn't get evicted from ReplayProcessor with timeout on terminal signal.

## Steps to Reproduce

```java
@Test
public void repoCase() {
 final ReplayProcessor<String> replayProcessor = 
  ReplayProcessor.createTimeout(Duration.ofSeconds(5));
  replayProcessor.onNext("test1");
  Uninterruptibles.sleepUninterruptibly(Duration.ofSeconds(10));
  replayProcessor.onComplete();
  Uninterruptibles.sleepUninterruptibly(Duration.ofSeconds(1));
 //It must not print item according to the doc but it does print "test1"
  replayProcessor.subscribe((str) -> System.out.println(str));
}
```

## Your Environment

* Reactor version(s) used: 3.3.8.RELEASE
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`): openjdk version "11.0.7" 2020-04-14
* OS and version (eg `uname -a`): 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by simonbasle** [comment]
It looks like a mistake in the documentation, as far as we can see it never behaved that way (although we're currently double-checking that, hopping on a time machine to rewind to 2016 and run your reproduction case with the Gradle from back then 😄)
