### ISSUE TITLE
deprecated members are hidden from javadoc

### ISSUE THREAD

**Issue by ericbottard** [reactor/reactor-core#2416]
3.4 introduces a number of new operators and APIs, and sometimes deprecates others.
Sadly, those are hidden from the generated javadoc, making it hard for users to understand how to migrate.

**Comment by simonbasle** [comment]
The deprecated members were excluded from javadoc in #1742, a debatable decision to remove traces of the 2 processors from the html javadoc. This was mistakenly backported to 3.2.x in #2156. We can either reintroduce deprecated members across the board or focus on 3.4 (with 3.2 reaching EOL and 3.3 having only the undesirable processors as deprecated).

**Comment by ericbottard** [comment]
There's also a way to exclude specific classes (as done for BlockHound)
