### ISSUE TITLE
Deadlock when computation heavy calculation after connect in for ConnectableFlux

### ISSUE THREAD

**Issue by Azbesciak** [reactor/reactor-core#2423]
Hello, I faced an issue with connectable flux - when there is a computation heavy process done after subscribers are connected, there is a deadlock (`doFinally` is not called for example). However, if you made this computations before connect - it works.
Sample code is placed in the repository, also most important code below:

```kotlin
fun main() {
    val processor = Schedulers.newSingle("example-publish")
    Flux.fromIterable(listOf(Flux.fromIterable(List(100000) { it })))
        .flatMap {
            val processed = it.publishOn(processor)
                .flatMap { if (it % 4 == 0) Mono.just(it) else Mono.empty()  }
                .doOnComplete { println("completed") }
                .publish()
            val sub = MockSub()
            processed.doOnSubscribe(sub::onSubscribe)
                .doOnError(sub::onError)
                .doOnComplete(sub::onComplete)
                .subscribe() // because subscribe(subscriber) does not work
//            if uncommented, it still works
//            Thread.sleep(1000)
            processed.connect()
//            if uncommented, it does not work
//            Thread.sleep(1000)
            processed
        }.doFinally {
            println("FINALLY")
            processor.dispose()
        }.blockLast()
}
```

instead of `Thread.sleep()` you can also call after `connect` the code like below 
```kotlin
val mutableList = mutableListOf<Int>()
repeat(11000000) {
    mutableList.add(it)
}
println("ADDING FINISHED")
```
the result will be the same - printed "ADDING FINISHED" but not "FINALLY"

## Expected Behavior
I suppose it should not cause deadlock

## Actual Behavior
it hangs

## Steps to Reproduce
https://github.com/Azbesciak/ConnectableFluxDeadlock

## Your Environment

* Reactor version(s) used: 3.3.10.RELEASE, 
* Other relevant libraries versions (eg. `netty`, ...): gradle 6.6.1 / wrapper is 6.3
* JVM version (`java -version`): openjdk version "14" 2020-03-17OpenJDK Runtime Environment (build 14+36-1461)
* OS and version (eg `uname -a`): Windows 10.0.18363.1082

**Comment by simonbasle** [comment]
Reactor-core is developed using java 8, please refrain from submitting snippets in other languages like kotlin or higher versions of java 🙏 

sleeping inside a reactive operator is considered an harmful antipattern. busy looping to a point where it is equivalent to sleeping too. it typically leads to... (live|dead)locks !

also, in your snippet you seem to create an inner sequence for the `flatMap` that is hot. you subscribe to it yourself from within the `flatMap` (another antipattern) and then `connect()`. But you return the inner sequence to the `flatMap` after the `connect` (obviously). Introcuding a `sleep` there further delays the time between the inner sequence subscription (through `connect`) and the `flatMap`'s subscription to the `publish`ed version. So at best the `flatMap` would only see termination event.

why not use `.publish().refCount(2)` ?
