### ISSUE TITLE
how to learn

### ISSUE THREAD

**Issue by xiaojiejava** [reactor/reactor-core#244]
i don't know how to learn reactor? its document is less

**Comment by sdeleuze** [comment]
The best way currently is follwing https://github.com/reactor/lite-rx-api-hands-on/, a reference documentation will come shortly.

**Comment by smaldini** [comment]
We started referencing in our preprod test site a few contents (http://next.projectreactor.io/learn), we expect a certain completion by 3.1.0.
We also expect the new ongoing reference guide effort to be referenced here

**Comment by simonbasle** [comment]
See the comment above and issue #404 (no pun intended) for tracking progress of the reference guide ;) Closing this issue for now.
