### ISSUE TITLE
upgrade to latest gradle 

### ISSUE THREAD

**Issue by ericbottard** [reactor/reactor-core#2445]
At the time of writing, gradle 6.7 is available.

`compileOnlyApi` is a new configuration scope that may be of interest to our build.

**Comment by simonbasle** [comment]
I have just tested `compileOnlyApi` (after switching all submodules except `benchmarks` to `java-library` instead of `java` plugin since the new scope is only available for java-library).

Unfortunately it produces a `pom.xml` with an entry for the `compileOnlyApi` dependency.

**Comment by simonbasle** [comment]
Gradle 6.7 reports a deprecated API usage warning, which comes from jcstress plugin so I reported https://github.com/jerzykrlk/jcstress-gradle-plugin/issues/32

**Comment by simonbasle** [comment]
migration to Gradle 7.4 has happened a while ago, closing this
