### ISSUE TITLE
Add Mono.blockSingle()

### ISSUE THREAD

**Issue by dnault** [reactor/reactor-core#2460]
## Motivation

Mono.block() and Mono.block(Duration) are both annotated with `@reactor.util.annotation.Nullable`. IntelliJ IDEA (and possibly other IDEs and static analysis tools) warns when the returned value is used without a null check.

I'd like to concisely express an expectation that a `block` call will return a non-null value, without having the IDE complain.

## Desired solution

Add new `Mono.blockSingle()` and `blockSingle(Duration)` methods that either return a non-null value, or throw `NoSuchElementException`.

## Considered alternatives

* You can chain call `Mono.single().block()`, but the IDE will still warn that the result may be null.

* You can call `Objects.requireNonNull(Mono.block())`, but that's noisy and cumbersome.

**Comment by simonbasle** [comment]
I need to consider this, but adding convenience to the blocking APIs is a bit contrary to our intrinsic goal of having users avoid them as much as possible...

**Comment by bsideup** [comment]
What about `myMono.blockOptional().get()`?

**Comment by dnault** [comment]
> What about `myMono.blockOptional().get()`?

@bsideup As an alternative to `myMono.blockSingle()`? It suffers from a similar problem. IntelliJ warns that "Optional.get() is called without ifPresent() check".

**Comment by simonbasle** [comment]
I agree that would be the best solution, since you benefit from the whole `Optional` API (including `ifPresent`, but also `map`, `orElse`, `orElseThrow`). with a `blockSingle()`, you'd still get an error in case of empty source, which can be emulated by eg. `.blockOptional().orElseThrow(NoSuchElementException::new)`.
