### ISSUE TITLE
Add Mono<T> switchIfEmpty(Supplier<Mono<? extends T>> alternate)

### ISSUE THREAD

**Issue by danieleguiducci** [reactor/reactor-core#2464]
Mono class, consider adding new methods.

## Motivation
Sometimes I need to fetch a row from a database, and I don't have find it I need to run a completely different branch of execution.
With the current possibility I can only use `switchIfEmpty(Mono<? extends T> alternate)` which requires me to define the whole alternative branch in that Mono.
Example:
```java
    private class Session {
        private final Request request;

        public Session(Request request) {
            this.request = request;
        }

        public Mono<Boolean> start(Request request) {
            return dao.findById(request.getId())
                    .flatMap(this::doUpdate)
                    .switchIfEmpty(this.doCreate()); // this would work, but it needs to run the whole method
        }

        private Mono<Boolean> doUpdate(Account account) {
            account.setLastConnectedTime(Instant.now());
            return dao.save(account);
        }


        private Mono<Boolean> doCreate() {
            var account = new Account();
            account.setId(request.getId());
            account.setLastConnectedTime(Instant.now());
            // Do something else complex
            return dao.save(account);
        }
    }
```

## Desired solution
Adding `Mono<T> switchIfEmpty(Supplier<Mono<? extends T>> alternate)` would solve it.

```java
    private class Session {
        private final Request request;

        public Session(Request request) {
            this.request = request;
        }

        public Mono<Boolean> start(Request request) {
            return dao.findById(request.getId())
                    .flatMap(this::doUpdate)
                    .switchIfEmpty(this::doCreate); // The whole method would be called only if the previous Mono is empty.
        }

        private Mono<Boolean> doUpdate(Account account) {
            account.setLastConnectedTime(Instant.now());
            return dao.save(account);
        }


        private Mono<Boolean> doCreate() {
            var account = new Account();
            account.setId(request.getId());
            account.setLastConnectedTime(Instant.now());
            // This branch can do more complex calls 
            return dao.save(account);
        }
    }
```

This new method would work similar to existing flatMap which takes a Function, and the doCreate method is only called when the entity is not found in the database. That's particularly important when the switchIfEmpty needs to switch to a different execution and complex branch.

Thank you.

Kind regards,
Daniele

**Comment by simonbasle** [comment]
`Mono`s are meant to be lazy by default. You'd need to take that into account when writing `doCreate()` since it returns a `Mono`. What if that `Mono` is resubscribed to for instance?

The way to go here is to use `Mono.defer(() -> { /* rest of doCreate body */})`.

**Comment by danieleguiducci** [comment]
Yes, but also the method `dao.findById(id)` returns a Mono, so, when the Mono is resubscribed also the method `findById` is recalled and it does return something it will call doUpdate, otherwise if it does return an Empty mono it will call doCreate.

The first implementation I posted above, would work because it does define an empty entity but the dao.save method is not called immediately.

The correct solution would be using the Mono.defer as you mentioned before.
```java
return dao.findById(request.getId())
                    .flatMap(this::doUpdate)
                    .switchIfEmpty(Mono.defer(this::doCreate));
```

I was wondering if adding the switchToEmpty(Supplier) would be beneficial for other people out there.

Thank you.

Kind regards,
Daniele
