### ISSUE TITLE
Reference guide still mentions very old Bismuth-RELEASE BOM

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2470]
In the reference guide, the sections guiding on how to add the BOM using Maven and Gradle still reference `Bismuth-RELEASE`.

The current latest BOM is `2020.0.0`, with `Dysprosium-SR13` a close second (and the one most people should have in prod right now).

The README of the project is updated on each release, but indeed the reference guide mention of the release train has been overlooked :(

**This issue targets the `3.3.x` branch, and as such the latest is `Dysprosium-SR13`**, to be updated at the next release to SR-14.

**Comment by simonbasle** [comment]
Side note:

> Careful ! BOMs that are named after the codename (up to Dysprosium) use -RELEASE for the FIRST release of the cycle, then incremental -SRxxx suffixes. So Bismuth-RELEASE and Dysprosium-RELEASE are respectively the OLDEST releases in the Bismuth and Dysprosium cycle. We're at Dysprosium-SR13 as of last week, and we've even released 2020.0.0 (new version scheme, see projectreactor.io/docs/core/release/reference/index.html#getting-started-understanding-bom, which should show a more consistent progression: 2020.0.0 < 2020.0.1 < 2020.0.2...)

**Comment by simonbasle** [comment]
cc @jongmin92

**Comment by ericbottard** [comment]
Should we come up with a (more powerful) `bumpVersionsInReadme` task that also looks at asciidoc files?

**Comment by simonbasle** [comment]
yeah, I explored that in #2474
