### ISSUE TITLE
what is the difference between these two variables

### ISSUE THREAD

**Issue by sadiqhabib** [reactor/reactor-core#2476]
https://github.com/reactor/reactor-core/blob/332b18ba2cf25ff9d93d01456d6ec79f30a61ccc/reactor-core/src/main/java/reactor/core/publisher/FluxCreate.java#L396

TERMINATED and CANCELLED are the same then why not directly `Disposables.disposed();`

**Comment by simonbasle** [comment]
`Disposables.disposed()` creates a new instance, so these two constants hold different instances, which are compared by reference in compareAnSwap operations in order to provide atomic guards.
