### ISSUE TITLE
Document the `Mono` contract very explicitly

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2481]
see discussion in #2078

the `Mono` contract is:

A `Publisher` that emits either:
 - `onNext(t)` + `onComplete()`
 - `onComplete()`
 - `onError()`

`Mono.never()` is the notable exception to that, but is more of a corner case.

One thing to make very explicit is that `onNext(t)`+`onError(throwable)` is forbidden.

**Comment by simonbasle** [comment]
> This has come up in the past. Since `Mono` is not part of the rs spec it
seems that contract is not defined clearly enough, the javadoc leaving too
much room for interpretation:
A Reactive Streams Publisher (...) that completes successfully by emitting
an element, or with an error.
>
> Looking at sources it is clearly enforced, though, and another
manifestation of that contract is that all of core mono implementations
directly call `onComplete` upon propagating `onNext`, or that Mono.from
subscriber will enforce that contract.
We should definitely make that more prominent in the docs.

**Comment by ericbottard** [comment]
Another thing that may be very explicit (as you say from the implementations @simonbasle) is that `onComplete()` is called __right after__ `onNext()`, _i.e._ there can't be a delay (in practice) between the two.

**Comment by ericbottard** [comment]
Also revise diagram in https://projectreactor.io/docs/core/release/reference/#mono

**Comment by simonbasle** [comment]
> Another thing that may be very explicit (as you say from the implementations @simonbasle) is that `onComplete()` is called **right after** `onNext()`, _i.e._ there can't be a delay (in practice) between the two.

yes, maybe we should hint at that although that is more of an expectation rather than a hard rule. something along the lines of:

> Most `Mono` implementations are expected to immediately call `onComplete` on their `Subscriber` after having called `onNext`. `Mono.never()` is an outlier: it doesn't emit any signal, which is not technically forbidden although not terribly useful outside of tests. `onNext`+`onError` is explicitly forbidden.
