### ISSUE TITLE
flatMapSequential marble diagram

### ISSUE THREAD

**Issue by UgiR** [reactor/reactor-core#2482]
In the [marble diagram for flatMapSequential](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#flatMapSequential-java.util.function.Function-), the first green square is depicted as being emitted downstream when the first green circle is received. However, the emission of the green square should happen when it is emitted by the corresponding 'inner' publisher.

**Comment by ericbottard** [comment]
Good catch! Thanks for taking the time to report this issue, created a PR.
