### ISSUE TITLE
Mono#doOnSuccess marble diagram broken

### ISSUE THREAD

**Issue by UgiR** [reactor/reactor-core#2483]
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#doOnSuccess-java.util.function.Consumer-

![image](https://user-images.githubusercontent.com/33397860/98622825-0194c100-22d0-11eb-8705-b86d3bff7089.png)

**Comment by simonbasle** [comment]
thanks for reporting this, there is indeed something very wrong with that diagram 🤣
