### ISSUE TITLE
subscriberContext() thread seems sensitive to position relative to subscribeOn()

### ISSUE THREAD

**Issue by rubasace** [reactor/reactor-core#2484]
Javadoc for `subscriberContext` states: 

> The {@link Context} propagation happens once per subscription (not on each onNext): it is done during the {@code subscribe(Subscriber)} phase, which runs from the last operator of a chain towards the first.

My understanding is that `subscriberContext()` should be executed on the same thread the subscription happens. However, it seems to be dependant on its position relative to `subscribeOn()`.

## How to reproduce

For example: 

```java
Mono.just("blabla")
    .doOnNext(e -> System.out.println("doOnNext: " + Thread.currentThread().getName()))
     .subscriberContext(context -> {
        System.out.println("subscriberContext (above subscribeOn): " + Thread.currentThread().getName());
        return context;
     })
    .subscribeOn(Schedulers.parallel())
    .subscriberContext(context -> {
        System.out.println("subscriberContext (bellow subscribeOn): " + Thread.currentThread().getName());
        return context;
    })
    .subscribe();
```

I'm expecting the following output:

main: main
subscriberContext (bellow subscribeOn): parallel-1
subscriberContext (above subscribeOn): parallel-1
doOnNext: parallel-1

Instead, I'm observing the following:

main: main
subscriberContext (bellow subscribeOn): main
subscriberContext (above subscribeOn): parallel-1
doOnNext: parallel-1

For some reason, `subscriberContext()` only uses the `subscribeOn()` thread when placed to the right (bellow), but not when placed to the left (above). 

Is this the expected behaviour?

## Used versions

* Reactor version(s) used: 3.3.9.RELEASE

**Comment by bsideup** [comment]
It is absolutely an expected behaviour. `subscriberContext` is Thread agnostic.

> My understanding is that `subscriberContext()` should be executed on the same thread the subscription happens.

No, there isn't such limitation. `subscriberContext` will be executed on the same thread as `subscribe()` call.

**Comment by rubasace** [comment]
> subscriberContext will be executed on the same thread as subscribe() call.

@bsideup do you mean it will always be executed on the same thread as `subscribe()`? Cause, on my example, that only happens if called to the right of `subscriberContext()`, but not to the left.

**Comment by bsideup** [comment]
in your example, there are 5 `subscribe`s :)

Just 4 out of 5 are "hidden" behind the operators (`subscriberContext`, `subscribeOn`, `doOnNext`)

So, I am referring to `subscribe` from `subscribeOn`, that will be executed on one of the parallel threads

**Comment by bsideup** [comment]
JFYI it is called "downstream" and "upstream", what you call left/right :)

**Comment by rubasace** [comment]
@bsideup thanks for clarifying the naming :) 

I'm sorry as I'm not sure I'm fully understanding. 

What I understand from what you are saying is that  `subscriberContext()` will be executed on the same thread as the `subscribe()` call from `subscribeOn`, therefore `parallel-x` on my example. 

If that's right, what I don't understand is why only one of my `subscriberContext()` calls is being executed on `parallel-1`, when the other is being executed on `main`.

**Comment by rubasace** [comment]
So, mainly, my question is: should `subscribeOn()` **only affect upstream** `subscriberContext()` calls or should it affect **both upstream and downstream** ones?

**Comment by bsideup** [comment]
Let me try to illustrate this for you:
```java
[parallel-1] Mono.just("blabla")
[parallel-1]     .doOnNext(e -> System.out.println("doOnNext: " + Thread.currentThread().getName()))
[parallel-1]      .subscriberContext(context -> {
[parallel-1]         System.out.println("subscriberContext (above subscribeOn): " + Thread.currentThread().getName());
[parallel-1]         return context;
[parallel-1]      })
[.       main]    .subscribeOn(Schedulers.parallel())
[.       main]    .subscriberContext(context -> {
[.       main]        System.out.println("subscriberContext (bellow subscribeOn): " + Thread.currentThread().getName());
[.       main]        return context;
[.       main]    })
[.       main]    .subscribe()
```

`subscribeOn` moves the `subscribe` call to the provided scheduler, and the subscription continues on that thread.

**Comment by rubasace** [comment]
Got it! thanks for the detailed explanation @bsideup 

I see that each step on the pipeline calls `subscribe()` and by applying `subscribeOn()` we change the thread on which that `subscribe()` happens, but only upstream. 

I was mistaken because `subscribeOn()` affects `doOn()` and `map()` operators both upstream and downstream (from the beginning until the next occurrence of `publishOn()`). 

Also, it's mentioned in the documentation that the placement of `subscribeOn()` doesn't matter:

>  But the placement of publishOn in the chain matters, while the placement of subscribeOn does not

However, this seems to be partially right, if it only affects downstream `subscribe()` calls. Maybe documentation could be a bit more specific?
