### ISSUE TITLE
Provide easier way of customizing timeout message

### ISSUE THREAD

**Issue by rubasace** [reactor/reactor-core#2489]
By default, the `.timeout()` operator emits a `TimeoutException` with a message saying that an item or terminal signal isn't observed within the configured time. 

In some cases, it would be useful to be able to give a better semantic value to the message, something like `Timeout while calling service A`.

Currently, the only way I know I can do this is by doing `.timeout(Duration.ofMillis(900), Mono.error(() -> new TimeoutException("Timeout while calling service A"))`.

It would be nice to have an alternative method `.timeout(Duration.ofMillis(900, "Timeout while calling service A")` or similar.

**Comment by bsideup** [comment]
@rubasace have you considered using `onErrorMap`?

**Comment by rubasace** [comment]
@bsideup I have. It's similar solution to the fallback one I mentioned above. We still have to handle an extra `TimeoutException` or similar exception to just fail in the same way but with a custom message.

**Comment by rubasace** [comment]
PS: when I said `the only way I know` I mean `the easiest way I know`

**Comment by simonbasle** [comment]
I don't know about that one. We already have a _lot_ of `timeout` overloads so unless there is a more compelling reason to add it than "it would be useful", I'm not inclined to add this option.

Even if we did, we wouldn't want to add it to all overloads, so it would probably make most sense to add it to the most "complex" overload (`timeout(Publisher<U> firstTimeout, Function<? super T, ? extends Publisher<V>> nextTimeoutFactory)`), further reducing the convenience compared to the alternative solutions you've found.

**Comment by rubasace** [comment]
@simonbasle I see. In my teams projects it's just about that, we need to customize the message 100% of the time and it just feels wrong having to create extra steps for customizing the default exception. But maybe this is just something relevant for us and not a reason good enough. So feel free to close the ticket if you see no value :)

**Comment by simonbasle** [comment]
@rubasace ok then closing this, as your case is more niche and the solution you found is not wrong.
