### ISSUE TITLE
Rework introspection interfaces (Receiver, Producer, Trackable etc)

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#249]
**Background**
The introspection interfaces are largely implemented by inner classes of operators. There is too many of them and despite the interfaces, introspection of an operator chain isn't terribly easy.

**Goal**
More coherent introspectability, single interface, better means of navigating the whole chain.
`Scannable` achieves that by defining standard attributes in `Attr`, among which some can be used to recursively visit the operator chain (`ACTUAL` and `PARENT` notably).

This is further eased by the `parents()`, `actuals()` and `inners()` method, which return a `Stream` of `Scannable`, allowing all sorts of filtering and transformations along the way.

**Benefits**
 - single coherent interface
 - easily added to an existing operator by simply implementing `scan`. Traversal is ensured as long as `PARENT` and `ACTUAL` are mapped.
 - `inners()` allow to jump into inner subscribers like in the case of a `flatMap` for instance.

**Removed features**
The new introspection capacity dropped support of `limit()` and `expectedFromUpstream()` for a couple reasons : they were not consistently well implemented and they are not as useful as a simple `capacity/prefetch - buffered` calculation.

**Comment by simonbasle** [comment]
Copying a little bit of background from #502 into the description here for posterity and readability 😉
