### ISSUE TITLE
thenReturn documentation doesn't describe behavior for errors

### ISSUE THREAD

**Issue by bbukaty** [reactor/reactor-core#2494]
## Documentation Issue
from reading the [documentation for Mono.thenReturn](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#thenReturn-V-), I got the impression that if the previous Mono completed with an error, it would be discarded and the return value would be returned instead. After experimenting I learned this is not the case, and errors in the preceding pipeline will skip the thenReturn operator and be propagated downstream.

## Improvement Suggestion

Clarify the error handling behavior of the thenReturn operator in the text of the documentation entry, using [the entry for Mono.then](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#then--) as an example. Modifying the marble diagram in a similar fashion would also be helpful, but is not critical for clarity of behavior.

**Comment by simonbasle** [comment]
yeah, all the `then*` operators behave the same: they ignore `onNext`, propagate `onError` as is and trigger the alternative source of `onNext` upon receiving `onComplete`. Would you like to submit a PR?

**Comment by bbukaty** [comment]
Sure, I'm just a bit unfamiliar with the repo structure. It wasn't immediately obvious to me where the file is where I'd want to make such a change. If you point me in the right direction I'd be happy to.

**Comment by simonbasle** [comment]
`Mono` is a big file, `thenReturn` is here: https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/Mono.java#L4256
