### ISSUE TITLE
The behavior of Flux#subscribe() is inconsistent with Sinks.Many.currentSubscriberCount()

### ISSUE THREAD

**Issue by JamesChenX** [reactor/reactor-core#2496]
## Expected Behavior

Flux#subscribe should not throw "IllegalStateException: UnicastProcessor allows only a single Subscriber" if the return value of Sinks.Many.currentSubscriberCount() is 0.
## Actual Behavior

Flux#subscribe throws "IllegalStateException: UnicastProcessor allows only a single Subscriber" even if the return value of Sinks.Many.currentSubscriberCount() is 0.

## Steps to Reproduce

```java
Sinks.Many<Integer> sink = Sinks.many().unicast().onBackpressureBuffer();
Flux<Integer> flux = sink.asFlux();
Disposable subscriber = flux.subscribe();
System.out.println(sink.currentSubscriberCount()); // 1
subscriber.dispose();
System.out.println(sink.currentSubscriberCount()); // 0

flux.subscribe(); // The code will throw "IllegalStateException: UnicastProcessor allows only a single Subscriber"
```

## Your Environment

* Reactor version(s) used: 3.4.0
* JVM version (`javar -version`): JDK 11

**Comment by bsideup** [comment]
Unicast `Sink` can only be subscribed once, that's by design. It won't "reset" its state when you unsubscribe.
