### ISSUE TITLE
Flux is hanging when there is a runtime exception thrown in handle operator

### ISSUE THREAD

**Issue by koldat** [reactor/reactor-core#2498]
## Expected Behavior
handle fusion operator should propagate runtime exception thrown.
## Actual Behavior
It does not propagate exception (signal is ignored) thus flux stops responding.

## Steps to Reproduce
```java
    @Test
    public void runtimeExceptionFused() {
        // Check issue that for fuseable and Exception thrown inside handle it did not propagate signal -> hanging flux
        //  and throws IllegalStateException: Timeout on blocking read
        Assertions.assertThatThrownBy(() -> {
            Flux.range(0, 10)
                .handle((v, sink) -> {
                    throw new NullPointerException("boom");
                })
                .blockLast(Duration.ofSeconds(1));
        }).isInstanceOf(NullPointerException.class).hasMessageContaining("boom");
    }
```

## Possible Solution
Fix is in PR #2497

**Comment by simonbasle** [comment]
0f1dc8f is actually merging this into `3.3.12.RELEASE`, so this fix will be released in:
 - [`3.2.22.RELEASE`](https://github.com/reactor/reactor-core/milestone/93)
 - [`3.3.12.RELEASE`](https://github.com/reactor/reactor-core/milestone/91)
 - [`3.4.1`](https://github.com/reactor/reactor-core/milestone/92)
