### ISSUE TITLE
Add (re)connectable Mono abstraction

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2501]
## Motivation
In RSocket, there is a `ReconnectMono` abstraction that has proven useful. Conceptually, this seem very close to what is done in `ConnectableFlux`, with the additional capacity to manually disconnect.

The concept seem useful to other downstream projects like R2DBC, and could also serve as foundation for caching / memoization operators in `Mono` (eg. to introduce cache invalidation).

As a result, introducing a `ConnectableMono` abstraction seems to be the way to go, reusing concepts from `ConnectableFlux` but with twists that only apply to `Mono`.

## Desired solution

 - [ ] Introduce `ConnectableMono` abstract class
  - `connect()` method -> directly connects, no connect notification
  - `connect(BiConsumer<T, Disposable>)` -> connect and notify the biconsumer when connection is done AND a value is resolved. close but mono-specific equivalent to `ConnectableFlux.connect(Consumer<Disposable>)`
  - `reset()` method, or similar
 - [ ] Add a package-private concrete implementation for memoization / cache (eg.`CacheConnectableMono`)
  - in spirit, this sounds similar to `FluxReplay`
  - no-argument factory/operator for unlimited caching of the value
  - `BiConsumer<T, Disposable>` factory to automate `reset()` via an event listener on `T`
  - `Predicate<T>` factory to automate `reset()` via a check each time a new subscriber comes in
 - [ ] Add a `ConnectableMonoHide` and `ConnectableMonoLift` concrete implementations
 - Consider adding utility facade like `refCount` (later on probably)

### 1. should we distinguish cancel vs reset ?

Cancel would be “cancel before the source has produced a value”, whereas `reset` is “discard the value if there’s one and wait for `connect()` again.

(initial thoughts: no)

### 2. should the reset work if the source produced an onError ?

(initial thoughts: yes)

### 4. do we still want to capture/cache `onError` (failure) and `onComplete` (empty) monos

100% coverage of current `cache` variants? notably the ones that allow caching the errors ? (I think it could be achieved with materialized source)

### 5. how to expose the `CacheConnectableMono` in the Mono API ?
`cache()` is already taken, maybe a good occasion to introduce the word `memoize` ?

## Considered alternatives
A 1-1 port of RSocket's `ReconnectMono` was deemed unadvisable, as it is preferable to reuse concepts already introduced in `Flux`/`ConnectableFlux`.

**Comment by simonbasle** [comment]
cc @OlegDokuka

**Comment by simonbasle** [comment]
cc @OlegDokuka and @rstoyanchev.

@mp911de @acogoluegnes this could also be of interest to you in r2dbc and reactor-rabbitmq respectively

**Comment by bsideup** [comment]
> connect and notify the biconsumer when connection is done AND a value is resolved
> 3. do we need a `ConnectableMono#connect(Consumer<Disposable>)` ?

What if resolving takes a significant time, and the consumer decides to cancel it?

> 1. should we distinguish cancel vs reset ?

It may help when downstream isn't aware of the caching upstream and cancels no matter what.

> 4. do we still want to capture/cache `onError` (failure) and `onComplete` (empty) monos

Would be helpful for "fail fast" scenarios

> 5. how to expose the `CacheConnectableMono` in the Mono API ?
`memoize` sounds okay 👍

**Comment by OlegDokuka** [comment]
> What if resolving takes a significant time, and the consumer decides to cancel it?

Yeah. That is a possible scenario. Initially, I was thinking of the `ConnectableMono` exposing `Disposable`, but then we ended up on 1 to 1 API as in `ConnectableFlux`, thus, in order to dispose of such a subscription, one would have to hack this. As a compromise, we can return Disposable as a result of the `connect` method call. 

Does anybody remember why `connect` has a `void connect(Consumer<Disposable>)` API instead of `Disposable connect()`?


> do we still want to capture/cache onError (failure) and onComplete (empty) monos

Here, the point was on "is an error from the original `Mono` source recoverable`. E.g. `Mono.from(someSource).reconnect().connect() // -> ends with someSource -> onError`. Should `.reset()` invalidate received error and allow the next `.connect()` to re-subscribe to the `someSource` again. In general, there a 2 options -> 
1) Forbid `reconnect` to recover from the `onError` via `reset` call. As a comporimisem, by accomplishing `Mono.from(someSource)` with `.retry()` operator, we can emulate similar behavior. In that case, an error will never gets to the `reconnect` operator. If the last Downstream timeouts -> it cancels the original subscription of `someSource` + `retry`. The new subscriber will try to subscribe to `someSource` up on subscription again.

2) allow `reconnect` to recover from errors by calling `reset`

**Comment by simonbasle** [comment]
ok so that makes me think we _do_ need to distinguish "cancel" vs "reset". The true "cancel from downstream" aspect would probably be managed by a separate operator similar to `refCount` in `ConnectableFlux` though, but we should be able to expose a way to just "stop connecting unless data has been received"

Here are some more thoughts, notably on error patterns and handling cancellations from subscribers (as opposed to explicit `dispose()` or `reset()` calls):

I don't know if `void ConnectableFlux#connect(Consumer<Disposable>)` has a legitimate use case that cannot be covered by `Disposable ConnectableFlux#connect()` (which _does_ exist). I have the feeling that we can cover the whole ground with just `Disposable connect()` and `Disposable connect(BiConsumer<T, Disposable>)` (note the added returned `Disposable`).

We'd have:
 1. both methods returning a `Disposable` to represent the current attempt at `connect`ing, only valid until the first data signal (`onNext`, `onComplete`, `onError`) is received. we'll call that one the **cancelConnect** one.
 2. one `Disposable` in the `BiConsumer` that just maps 1-1 to the `reset()` method. we'll call that one the **reset**.

In `Disposable connect()`, the user signal no particular interest in automating `reset()` (ie. they will call it explicitly if needed).

In `Disposable connect(BiConsumer)` the user signals they expect a `onNext` and they should be notified of such an `onNext` in order to automate `reset()` through that element. `reset()` calls are still possible.

Downstream cancellations should always remove the subscriber from the array, but in the case of `autoCancel` like facade, it would _only invoke the **cancelConnect**_. That is to say, it wouldn't automatically `reset()` the cache if it has already been resolved.

We could always add an `autoReset` operator if the need arises.

### error patterns
I see three main patterns as to how one could want to deal with an error in the source:

1. transient error: the error is retried for a while (ie. with maxRetries) but can ultimately be allowed to reach the `ConnectableMono`, which enters `terminated` state and will replay it. If the user knows that the error is transient and wants to `reset()` the state manually, eg. an hour later, they can do so. 
2. final error: the error is directly propagated to the `ConnectableMono`, a manual `reset()` will be needed
3. errors must not be stored: the source will need to have infinite retries enabled. at that point, if errors are continuous, the downstream can use `Disposable` returned from `connect` to abandon.

In that light, I think capturing error monos and empty monos should be allowed.

One can avoid capturing empty only by using `single()`, and avoid capturing both error and empty by using `single().retry()`.

### downstream notifications
When valued/terminated state has been reached, new downstream subscribers should immediately get replayed so there is no interaction with **reset**, and by definition **cancelConnect** is NO-OP at that point.

When the connection is still ongoing and there's latency in getting the first signal, there could be a call to **cancelConnect** while attached subscribers haven't terminated. In that case, provided these are not cancelled, they should receive a `CancelException`.

**Comment by simonbasle** [comment]
this is likely superseded by `MonoCacheInvalidateWhen` in #2717
