### ISSUE TITLE
Add a `doFinally` operator that executes once after completion/error/cancel

### ISSUE THREAD

**Issue by kdvolder** [reactor/reactor-core#251]
Example code:

```
    public static Mono<String> validateCredentials() {
        return validateCredentialsHelper("Hello", "Stefane")
        .doOnSubscribe((e) -> {
            System.out.println("Starting validation...");
        })
        .doAfterTerminate((result, error) -> {
            System.out.println("Validation terminated: "+result+", "+error);
        });
    }

    private static Mono<String> validateCredentialsHelper(String string, String string2) {
        return Mono.delay(Duration.ofSeconds(1))
        .then((x) -> Mono.just(string+" "+string2));
    }

    public static void main(String[] args) throws Exception {
        System.out.println("Triggering...");
        validateCredentials().subscribeOn(Schedulers.elastic()).subscribe((result)-> System.out.println("result: "+result));
        System.out.println("Triggered!");


        while (true) {
            Thread.sleep(2000);
        }
    }
```

Example output:

```Triggering...
Triggered!
Starting validation...
result: Hello Stefane
```

Notice that it does not print the 'Validation Terminated' message.

**Comment by praseodym** [comment]
I think I've seen this issue happening as well.

**Comment by smaldini** [comment]
Linked #246

**Comment by smaldini** [comment]
Workaround - use doOnNext and doOnError

**Comment by kdvolder** [comment]
There was a bit of discussion in slack about maybe `doAfterTerminate` including cancel as well. 

I think, yes, it should. What I'm looking for is an operator that always execute some cleanup code *no matter what* after the mono somehow ends its processing. Be that via a successful completion, being canceled, or an error. It would be nice if this cleanup code can distinguish error from cancel from success and only executes once.

It is not very convenient to try and cobble that together yourself as combination of `doOnNext`, `doOnError` and `doOnCancel`. The tricky part is there that if you add both `doOnNext` and `doOnCancel` then... on a successful completion its not clear whether `doOnCancel` will be called. In some cases it might (when the subscriber cancels eagerly after consuming the only result), or not.

So a 'bug-free' pattern to achieve this without potentially executing your clean-up code multiple times (once onNext and once more onCancel) isn't trivial.

**Comment by simonbasle** [comment]
We think this warrants a new operator, `doFinally`, that will execute after onComplete, onError and cancel (but only once). The operator will receive the `SignalType` that triggered it, but no further values.

**Comment by simonbasle** [comment]
this should be aligned with the `BaseSubscriber` behavior (which is slightly changed by #279)
