### ISSUE TITLE
Context and doOnEach operator behaviour is strange

### ISSUE THREAD

**Issue by TheoCadoret** [reactor/reactor-core#2515]
Behaviour of the doOnNext operator seems strange when it comes to context transmission, see the example below :

## Expected Behavior
Well I can't say I fully understood the concept of context so I let you decide what should happen

## Steps to Reproduce

In this test, results are different whether you run it on sthMonoWithOnEach or sthMono. The first fails while the second succeeds. Which seems strange to me. 

```java
@Test
	void testDoOnEach() {

		Mono<Void> sthMonoWithOnEach = Mono.just("sth")
				.doOnEach(s -> {})
				.flatMap(sth -> Mono.just("other").then()
						.contextWrite(ctx -> ctx.put("test", "testValue")));

		Mono<Void> sthMono = Mono.just("sth")
				.flatMap(sth -> Mono.just("other").then()
						.contextWrite(ctx -> ctx.put("test", "testValue")));

		StepVerifier.create(sthMono)
				.expectAccessibleContext()
				.contains("test", "testValue")
				.then()
				.verifyComplete();
	}
```

## Your Environment

* Reactor version(s) used: reactor-test:3.4.0 
* JVM version (`javar -version`): 10
* OS and version (eg `uname -a`):Darwin Kernel Version 19.6.0

**Comment by bsideup** [comment]
@TheoCadoret `Context` is a bottom-up concept and happens at subscription time (hence "subscriber Context").
Your `contextWrite` inside `flatMap` changes the context for `.then()` and `Mono.just("Other")` but not the outer chain.

**Comment by TheoCadoret** [comment]
Ok, but why does it behaves differently whether there is a doOnEach() or not ?

**Comment by bsideup** [comment]
@TheoCadoret ah, I didn't catch, sorry. It is not about `doOnEach`, but the fact that `Mono.just` is `Fuseable` and can be "optimized" to "scalar" behaviour. Try adding `.hide()` after outer `Mono.just()` and it would also fail.

Although the fact that the inner context gets propagated is... weird. Let me have a look

**Comment by simonbasle** [comment]
6d5656f / #2518 doesn't fix things but is an improvement for investigating similar cases in the future.

**Comment by simonbasle** [comment]
What happens is that `flatMap` sees the `Flux.just` source is representing a readily available single value, so it tries to remove itself from the equation by directly connecting its outer `Subscriber` to the result of the mapping `Function`. It is equivalent to:

```java
String sourceValue = ((Callable) Mono.just("sth")).call();
Function f = sth -> Mono.just("other").then().contextWrite(ctx -> ctx.put("test", "testValue"));
Mono outer = f.apply(sourceValue);

StepVerifier.create(outer);
```

So as you can see, now `StepVerifier` sees the context defined inside the `Function`.

This behavior is suppressed by `doOnEach`, but would also be explicitly suppressed by you adding a `.hide()` after the initial `Mono.just`.
