### ISSUE TITLE
Group By issue when large amount of groups

### ISSUE THREAD

**Issue by deblockt** [reactor/reactor-core#2539]
I'm trying to do the following with the groupby:
  - input many kafka event (each event is for a customer order)
  - I want to be able to treat each customer order in parrallel, but run events sequentialy for each customer order

For exemple: 
  - event1 : customer order 1 -> add product
  - event2: customer order 1 -> add another product
  - event3: customer order 2 -> add product
  - event4: customer order 2 -> add another product

I want that event1 and event 2 are  treated sequentially same for event3 and event4. But the group (event1, event2) and (event3, event4) can be treated in parrallel.

To do that I have tried something like that: 
``` java
public void startReadEvents() {
        Flux.defer(this.kafkaReceiver::receive)
            .doOnNext(record -> log.info("before group by {}", record))
            .groupBy(record -> record.customerOrderId())
            .flatMap(this::runRecordsInOrder)
            .subscribe();
}
private Publisher<?> runRecordsInOrder(Flux<ReceiverRecord<String, GenericRecord>> records) {
    return records
        .flatMapSequential(this::runHandler);
}

private Mono<Void> runHandler(ReceiverRecord<String, GenericRecord> record) {
    return Mono.delay(Duration.ofMillis(new Random().nextInt(100)))
                .then(Mono.defer(() -> log.info("end of the treatment")));
}
```

## Expected Behavior

work with few or many events

## Actual Behavior

If I send 10 events, all is ok, treatment is done and there are no issue.
If I send 500 events, the log `before group by` is display, and the log `end of the treatment` is not displayed.

## Your Environment

* Reactor version(s) used: 3.3.RELEASE
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`): 11
* OS and version (eg `uname -a`): ubuntu

**Comment by simonbasle** [comment]
this is a documented limitation of `groupBy`, see the javadoc and issues like #596 for example
