### ISSUE TITLE
Offer a hook based `Subscriber` for intermediate use case where `request` is needed

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#254]
When writing a simple `Subscriber`, use of lambda-based overrides is good and simple enough. However, as soon as a library user needs to issue `request(n)` manually, things get a little bloated: an anonymous `Subscriber` needs to be written, the `Subscription` captured and reused in onNext to perform `request`. The next best option is to use `Operators.SubscriberAdapter`, which is overkill and almost more bloated.

An intermediate option like a base `Subscriber` implementation that captures the `Subscription` and exposes the `request` method would make sense in this context. It would contain hooks for the `Subscriber` methods (as the actual implementations of these methods would include boilerplate code).

Usage pattern would look like this:
```java
intFlux.subscribe(new BaseSubscriber<Integer>() {

	@Override
	protected void doOnSubscribe(Subscription subscription) {
		request(1);
	}

	@Override
	public void doOnNext(Integer integer) {
		System.out.println("got " + integer);
		if (integer < 10)
			request(1);
		else
			cancel();
	}
);
```

**Comment by smaldini** [comment]
I wonder if it might just superseed the actual OperatorAdapter in 3.1

**Comment by simonbasle** [comment]
@smaldini I don't think so, as `SubscriberAdapter` (if that's what you meant) is both a `Producer` and a `Receiver`. It has slightly more complicated semantics I believe.. That said, if you think it can be replaced by this simplified version, why not. The other thing is, should we advertise the `BaseSubscriber` somehow? (say in the javadoc of `Flux#subscribe(Subscriber)`?
