### ISSUE TITLE
Flux groupBy followed by sort on group key hangs

### ISSUE THREAD

**Issue by igorbolic** [reactor/reactor-core#2546]
When using Flux publisher with followed by `groupBy` and `sort` on the group key everything works fine if the number of emitted elements is `less or equal to 258`. If I have more emitted elements the flow hangs and never finishes.

## Expected Behavior
The flow should complete regardless of the size of the emitted elements from the publisher.

## Actual Behavior
Flow hangs on `sort` and never completes.

## Steps to Reproduce

```java
@Test
void reproCase() {
  var size = 259L; // > 258 (reactor.util.concurrent.Queues.SMALL_BUFFER_SIZE + 2)
  var values = LongStream.rangeClosed(1, size)
      .mapToObj(it -> new ValueHolder(it, it % 2 == 1));

  var flow = Flux.fromStream(values)
      .groupBy(ValueHolder::isOdd)
      .sort(Comparator.comparing(GroupedFlux::key))
      .concatMap(it -> {
        System.out.println(it.key());
        return it;
      })
      .doOnNext(System.out::println);

  StepVerifier.create(flow)
      .expectNextCount(size)
      .verifyComplete();
}

static record ValueHolder(Long value, boolean isOdd) {
}
```

## Possible Solution

This seems to be related to `reactor.util.concurrent.Queues.SMALL_BUFFER_SIZE`. If there are more than 
`Queues.SMALL_BUFFER_SIZE + 2` elements being emitted, the flow hangs and never completes.

## Your Environment

* Reactor version(s) used: 3.4.0
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`javar -version`): OpenJDK 15.0.1 2020-10-20
* OS and version (eg `uname -a`): Darwin xxxxxx 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64

**Comment by simonbasle** [comment]
Hi @igorbolic, thanks for the report.
This is in fact a known and [documented](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/Flux.java#L5448) limitation of `groupBy` when the number of open groups grows large and not all live groups are consumed (as in requested).
