### ISSUE TITLE
FluxSwitchMap infinite while loop causes high CPU usage

### ISSUE THREAD

**Issue by TunaYagci** [reactor/reactor-core#2554]
## Expected Behavior
Loop should not stuck in an infinite loop and should not cause high cpu usage.

## Actual Behavior
We realised this problem on production and our CPUs were randomly spiking.
After some investigation with heap dumps, we have found the problem is on `FluxSwitchMap#drain` or `FluxSwitchMap line 353`, where it does:  
```java
Object second;
while((second = q.poll()) == null) {
}
```
This causes a high cpu and we have to restart our application to stop this (otherwise its never recovered for days).

![Screenshot 2021-01-11 at 16 20 27](https://user-images.githubusercontent.com/11725130/104200502-0b9a8380-5429-11eb-85e0-65bae14be352.png)

Screenshot above shows one of our pods in production, where it spikes to that CPU level for days until we notice and restart the application.

![Screenshot 2021-01-12 at 11 01 18](https://user-images.githubusercontent.com/11725130/104299563-ac3e8100-54c5-11eb-96ca-8ca9c83a804e.png)

Screenshot above shows one of the pods has doubled the CPU spike. This means **both parallel threads are in deadlock.**

## Steps to Reproduce

This is not our source code but I tried to repeat it in a junit4 test.
I'm not the best in repeater codes so **please run it more than once if it succeeds.** I know that its a race condition and it happens randomly. That's why I repeat the StepVerifier for many time.

While running the test, at some point it stops printing the numbers and CPU spikes. That means the thread is stuck on that while loop.

```java
 @Test(timeout = 120_000)
    public void test() {
        Flux<Integer> integerFlux = Flux.range(0, 20)
                .delayElements(Duration.ofMillis(2))
                .switchMap(s -> Flux.range(0, 20).delayElements(Duration.ofMillis(1)))
                .doOnNext(a -> System.out.println(a));

        for (int i = 0; i < 1000; i++) {
            StepVerifier.create(integerFlux)
                    .thenConsumeWhile(a -> true)
                    .verifyComplete();
        }
    }
```

## Your Environment

- Spring Boot 2.2.6
- Spring Boot 2.4.1 (both versions fail)
- reactor-core-3.3.4.RELEASE
- openjdk8

**Comment by TunaYagci** [comment]
@OlegDokuka i can provide more metrics or configurations if you need.

**Comment by OlegDokuka** [comment]
Thanks, @TunaYagci! So far I know where is the root cause of that issue, thus, stay tuned, I will keep you updated!

**Comment by TunaYagci** [comment]
Hey @OlegDokuka how is it going?

**Comment by OlegDokuka** [comment]
@TunaYagci fighting with some race conditions in the reworked impl. Feel free to look at the following PR to track the progress -> https://github.com/reactor/reactor-core/pull/2596/files

**Comment by TunaYagci** [comment]
@OlegDokuka I thought it was a small bug but looks like you had to do a complete rework on FluxSwitchMap. Thanks a lot for this! I'll keep an eye on this PR!

**Comment by OlegDokuka** [comment]
@TunaYagci we merged a new effort and we release it next Monday. In order to start using the new SwitchMap impl, you would need to set `.switchMap(mapperFn, 0)` prefetch to 0 (second param in the example)

**Comment by TunaYagci** [comment]
huge thanks to @OlegDokuka and @simonbasle for your efforts! I will test it when you release and update this issue with my findings.
