### ISSUE TITLE
ArrayIndexOutOfBoundsException is thrown from Flux#firstWithValue(Iterable<? extends Publisher<? extends I>> sources)

### ISSUE THREAD

**Issue by dmitry-saraykin** [reactor/reactor-core#2557]
Flux#firstWithValue(Iterable<? extends Publisher<? extends I>> sources) throws ArrayIndexOutOfBoundsException.

## Expected Behavior

Behaviour should be the same as for the method which accepts vararg Flux#firstWithValue(Publisher<? extends I> first, Publisher<? extends I>... others)

## Actual Behavior

ArrayIndexOutOfBoundsException is thrown

## Steps to Reproduce

```java
@Test
void reproCase() {
    Flux.firstWithValue(Arrays.asList(Mono.just(1), Mono.empty())).blockFirst();
}
```

## Your Environment

* Reactor version(s) used: 3.4.2
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): 11.0.3
* OS and version (eg `uname -a`): OSX

**Comment by simonbasle** [comment]
This is indeed a bug, when initially passing an `Iterable` of sources that is smaller than 8 (and in other cases, when the provisional array internal to the constructor is extended).

In `FluxFirstWithValue.subscribe`, the `sources` array is sparse and so its `length` is unreliable. The method goes on to use it nonetheless.

It could instead either take `int n` as an additional parameter (the `n` variable is up-to-date and passed to the coordinator's constructor already) or rely on `subscribers.length` exclusively.
