### ISSUE TITLE
Mono.subscriberContext methods are deprecated, but javadoc do not describe use what to replace them

### ISSUE THREAD

**Issue by rainmanhhh** [reactor/reactor-core#2572]
Mono.subscriberContext methods are deprecated, but javadoc do not describe use what to replace them

currently I use ContextHolder (with Mono.subscriberContext in it) to hold request object. what's the right way to do it in new version?

**Comment by simonbasle** [comment]
The javadoc _does_ describe alternatives to these deprecated methods:

![image](https://user-images.githubusercontent.com/6986166/105889515-8ad5ad00-600e-11eb-8597-217e73c28f4f.png)

**Comment by simonbasle** [comment]
For `Mono.subscriberContext()`, ideally you would rework the code a bit to use `Mono.deferContextual(ctx -> codeThatUsesContext)`. As stated in the javadoc `deprecated` entry, a quickfix is to replace `Mono.subscriberContext()` with `Mono.deferContextual(Mono::just)`.

**Comment by kasunsk** [comment]
`Mono.subscriberContext()` can be replaced with `Mono.deferContextual(Mono::just)` as the javadoc. 
If you are using kotlin, you can use `Mono.deferContextual { ctx -> Mono.just(ctx)}`

**Comment by ashrafsarhan** [comment]
`Mono.subscriberContext()` has been removed, use `Mono.contextWrite()` instead

**Comment by spartanhooah** [comment]
`Mono.contextWrite()` doesn't exist as far as I can tell (in reactor-core 3.6.2).

**Comment by chemicL** [comment]
@spartanhooah 
* https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#contextWrite-reactor.util.context.ContextView-
* https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#contextWrite-java.util.function.Function-

**Comment by spartanhooah** [comment]
Oh, derp, I wasn't thinking of a static context. I'm aware the issue is closed and old.
