### ISSUE TITLE
Mono.cache(duration, duration, duration) does not allow to pass a Scheduler

### ISSUE THREAD

**Issue by a701440** [reactor/reactor-core#2580]
Need another overload to match available MonoCacheTime constructor.

**Comment by simonbasle** [comment]
hi @a701440,
are you talking about the variant with the `Function`s` and `Supplier`s ? (just to be sure)
would you like to submit a PR ?

**Comment by a701440** [comment]
Yes basically function Mono.cache(ttlForValue, ttlForError, ttlForEmpty) does no have an overload that takes a Scheduler.
There is simpler one Mono.cache(ttl, timer). I think it's a matter of adding a new overload, there is already corresponding constructor.

**Comment by mickeelm** [comment]
@a701440 Will you submit a PR for this? Just browsing through the "good first issue"-issues and it's an easy fix but you brought it up so I don't wanna "steal" it if you're going to submit a PR :)

**Comment by vasantteja** [comment]
Hey I am interested to contribute can I work on this.

**Comment by simonbasle** [comment]
@mickeelm since the OP hasn't answered and you're the one who expressed interest in contributing first, please go ahead and open a PR 👍 (or answer here if you're not available anymore)

**Comment by mickeelm** [comment]
Great, I'll have it done today or tomorrow - which branch should I aim the PR at?
