### ISSUE TITLE
The order between doAfterTerminate and doOnError changes behavior when an error occurs

### ISSUE THREAD

**Issue by eze210** [reactor/reactor-core#2584]
## Actual Behavior
When an exception is thrown in a doOnNext callback:
* If doAfterTerminate is invoked before doOnError, the callback is called.
* If doOnError is invoked before doAfterTerminate, the callback is **not** called.

## Expected Behavior
The callback should be called in both cases.

## Steps to Reproduce
```java
  // This test passes
  @Test
  public void doAfterTerminateBeforeDoOnError() {
    AtomicBoolean afterTerminateCalled = new AtomicBoolean(false);
    AtomicBoolean doOnErrorCalled = new AtomicBoolean(false);
    Mono.just(5)
        .doOnNext(five -> {
          throw new NullPointerException();
        })
        .doAfterTerminate(() -> afterTerminateCalled.set(true))
        .doOnError(err -> doOnErrorCalled.set(true))
        .subscribe();
    assertThat(afterTerminateCalled.get(), is(true));
    assertThat(doOnErrorCalled.get(), is(true));
  }

  // This one fails
  @Test
  public void doAfterTerminateAfterDoOnError() {
    AtomicBoolean afterTerminateCalled = new AtomicBoolean(false);
    AtomicBoolean doOnErrorCalled = new AtomicBoolean(false);
    Mono.just(5)
        .doOnNext(five -> {
          throw new NullPointerException();
        })
        .doOnError(err -> doOnErrorCalled.set(true))
        .doAfterTerminate(() -> afterTerminateCalled.set(true))
        .subscribe();
    assertThat(afterTerminateCalled.get(), is(true));
    assertThat(doOnErrorCalled.get(), is(true));
  }
```

## Possible Solution
Use doFinally instead of doAfterTerminate, or use them in the working order.

* Reactor version(s) used: 3.2.12.RELEASE

**Comment by ericbottard** [comment]
This behavior has been changed in the 3.4.x line. Both tests will now pass.

**Comment by simonbasle** [comment]
to add to what @ericbottard said, it could only be changed in 3.4 because it was a breaking behavioral change. also, as a possible workaround and general best practice, try to use `subscribe(Consumer<T>, Consumer<Throwable>)` at a minimum, rather than `subscribe()`.
