### ISSUE TITLE
windowUntilX runs out of request/prefetch if windows are not fully drained

### ISSUE THREAD

**Issue by bruto1** [reactor/reactor-core#2585]
When windows are cancelled prematurely without first signaling sufficient request upstream, the source can eventually run out of request and cease emitting elements

## Expected Behavior
Test passes

## Actual Behavior
Test hangs
replacing take(1) with sampleFirst or equivalent filter is a viable workaround that drains the window to completion

```java
@Test
void reproCase() {
        Flux.range(0, 400)
            .log("source")
            .windowUntilChanged(i -> i / 10)
            .log("windowUntilChanged")
            .concatMap(win -> win.log("win")
                                 .switchOnFirst((first, all) -> all.take(1)))
            .log("out")
            .as(StepVerifier::create)
            .expectNextCount(40)
            .verifyComplete();
}
```

Reactor v 3.4.0

seems to be related to https://github.com/reactor/reactor-core/issues/1017

**Comment by bruto1** [comment]
if this is to be fixed, then I suppose it can be done by tracking whether or not the most recent window was cancelled and requesting 1 upon receiving each new element from upstream until there's a new window

**Comment by bruto1** [comment]
Described workaround does the thing in this exaggerated case, but if I do drain switchOnFirst's source a bit and cancel sometime later, a different solution is required
Some wrapper for switchOnFirst to create unbounded request before cancellation happens would work, I suppose

**Comment by simonbasle** [comment]
@bruto1 I think this should probably be better documented, but I don't think lack of request should implicitly drop...

for that particular use-case, I think you could achieve the same pattern as `take(1)` without the backpressure issues by replacing it with `.onBackpressureDrop().limitRequest(1)`. that way there won't be a cancellation, the window will be requested in an unbounded manner and unconsumed elements will be dropped.

wdyt? do you feel mentioning this in the documentation would suffice? (the operator combination above could be in the reference guide's FAQ as well)

**Comment by bruto1** [comment]
yes, it would be useful
as long as I can implement my case without too much hassle, it's fine
and explicit dropping of elements is better than implicit

**Comment by bruto1** [comment]
Came around to actually trying it, @simonbasle 

Unbounded or simply exaggerated request to window (like with onBackpressureBuffer()) DOES NOT translate to similar request to upstream - it is capped by WindowPredicateMain
The only solution I was able to come up with was making my own version of windowUntilChanged with unbounded prefetch
```
    public static <T, V> Flux<Flux<T>> windowUntilChangedUnbounded(
        Flux<T> upstream,
        Function<? super T, ? super V> keySelector
    ) {
        return windowUntilChanged(upstream, keySelector, Integer.MAX_VALUE);
    }

    public static <T, V> Flux<Flux<T>> windowUntilChanged(
        Flux<T> upstream,
        Function<? super T, ? super V> keySelector,
        int prefetch
    ) {
        return windowUntilChanged(upstream, keySelector, Flux.equalPredicate(), prefetch);
    }
```
Works for async and not very copious sources like mine, but cannot be recommended as universal solution

Ideas on other ways to drain (and ignore) the remainder of a prematurely cancelled window are welcome

**Comment by bruto1** [comment]
maybe add an argument to window operators that would toggle 'drain on window cancellation' behaviour on explicitly?

**Comment by bruto1** [comment]
@simonbasle let's come up with a decision on how to deal with this and I will try implementing it

**Comment by OlegDokuka** [comment]
> @bruto1 I think this should probably be better documented, but I don't think lack of request should implicitly drop...

I guess what is said is that `request(1)` does not guarantee that the new window will be generated right after the upstream has emitted a `onNext`. The current implementation continues to check the predicate and generate a new `windowFlux` only after the condition is satisfied. 

That said, we need to choose one of the strategies:

1. Create a new WindowFlux right after the previous one was canceled
2. drain elements 1-by-1  from the upstream until the condition is met and the new window is created.

The simples (as a hotfix) is draining 1-by-1 as it was suggested by @bruto1

**Comment by bruto1** [comment]
groupBy behaviour from window operator would be more counter-intuitive than simply dropping remaining elements, at least for me :)
