### ISSUE TITLE
Add access to the original lifter function from xxxLift Publishers

### ISSUE THREAD

**Issue by robotmrv** [reactor/reactor-core#2594]
## Motivation

Currently there is no way to access to the original lifter function from the Publisher level which was produced by `Operators#liftPublisher`.  
This forces users to copy paste related `reactor-core` logic if they want distinguish their Lifter operators from others at assembly time. 
For example there is such [copy](https://github.com/spring-cloud/spring-cloud-sleuth/blob/f49cd5e9b09fa4a0763c29c5b6eca1c46be827f9/spring-cloud-sleuth-instrumentation/src/main/java/org/springframework/cloud/sleuth/instrument/reactor/ReactorHooksHelper.java#L179-L461) of the logic in https://github.com/spring-cloud/spring-cloud-sleuth/pull/1830.

## Desired solution
Add scannable attribute to the all xxxLift `Publisher`s that returns original lifter function so user could make checks on it and access its state if needed.
```java
Publisher p = ...; 
Object lifter = Scannable.from(p).scanUnsafe(LIFTER);
if (lifter instanceof MyLifterType) {
....
}
```
This could be achieved relatively easy (add a field to `reactor.core.publisher.Operators.LiftFunction` and Scannable Attribute to the all xxxLift `Publisher`s).

This would simplify usage of `onEachHook` and `Scannable.Attribute.RUN_STYLE` together and optimizations like `OptimizableOperator` could be still applied.

## Considered alternatives

copy paste logic from `Operators#lift` and friends
## Additional context

This is proposed in scope of Spring Sleuth `reactor-core` instrumentation optimization https://github.com/spring-cloud/spring-cloud-sleuth/pull/1830 to reduce and simplify code.

**Comment by simonbasle** [comment]
I'm not sure an attribute dedicated to `lift` would be the best solution. Do you absolutely need access to the lifter `Function` btw? ie. should the attribute be an `Attr<Function<CoreSubscriber, CoreSubscriber>>` or can it be something simpler like eg. `Attr<String>`?

**Comment by robotmrv** [comment]
For my case I need to know at assembly time that current Publisher is Lifter or not, and if it is "my" lifter.  
The simplest solution is to have access to the original lift function.   
If current Publisher has such attribute then it is lifter.  
If lift function is my class - it is my lifter  

I need to know that current Publisher is lifter because `xxxLift` Publishers delegate `RUN_STYLE` evaluation to the `source` so for the case when there are two or more `onEachOperator` s to avoid unnecessary wrappings I need traverse up to the source and check If it was already decorated with my lift function.  

> should the attribute be an Attr<Function<CoreSubscriber, CoreSubscriber>> or can it be something simpler like eg. Attr<String>?

Another way is to add some marker / name attr to the lift Publisher but it would require more arguments in `Operators#lift` or some strict rules about calculation of this marker value (in addition calculation could cause additional allocations).

I agree that signature like `BiFunction<?, CoreSubscriber, CoreSubscriber>` is not nice for scannable attr (maybe just `Object` would be better or just `Class<?>`).  

>Do you absolutely need access to the lifter Function btw?

For my case it is Ok to have any marker type (String, Class, Object...).  

I suggest original lift function (i.e. the function that was passed as an argument to the `Operators#lift`) as marker because it does not require additional calculation / allocation, additional arguments and you can access its state (that could be helpful for some cases but is not mandatory)

**Comment by simonbasle** [comment]
Caveats:
One challenge is that we have two parallel APIs: `Operators.liftScannable` and `Operators.liftPublisher`.
Both of these return a `LiftFunction`, but the only role of said function is to be called by onEachOperator hook, or `transform`, to produce a new `Publisher` of the right type.

You as the user have no control over the `LiftFunction`, and it is lost at runtime once the hooks have been applied.

The `Function` you pass to create the `LiftFunction` is not entirely reliable either, since in the case of `liftScannable` it is wrapped in a lambda that extracts the `Scannable` from the `Publisher` (and some Publishers might not be scannable!).

If the `Function` takes a `Publisher` input, then that instance will be the one passed to the `xxxLift` Publishers and you can reach it.

With these caveats in mind, after thinking about it further, I would be ok exploring a dedicated `LIFTER` attribute of type `Attr<String>` (default value probably `null`, would be a lambda reference `toString()` for any lifter created via `Operators.liftScannable`). Wdyt?

**Comment by robotmrv** [comment]
>The Function you pass to create the LiftFunction is not entirely reliable either, since in the case of liftScannable it is wrapped in a lambda that extracts the Scannable from the Publisher (and some Publishers might not be scannable!).

Yes I understand your caveats.  
This is why I propose return just `Object`, or `Class` of the original argument from `Operators#lift/Publisher`, as you cannot be sure if it is scannable or publisher variant of the function.  

>  I would be ok exploring a dedicated LIFTER attribute of type Attr<String> (default value probably null, would be a lambda reference toString() for any lifter created via Operators.liftScannable)

It would solve my problem.    
but lambda `toString()` allocates on every invocation. This is what I want to avoid. It would not be a problem for my function as I just override `toString()` but for unaware implementations it is the case. Would it be cached in `LiftFunction`?   

So `Scannable.from(p).scan(LIFTER)` for `xxxLift` Publishers returns `lifter.toString()` and for other Publishers returns `null`.

I am ok with this solution

**Comment by simonbasle** [comment]
Yeah I guess the `xxxLift` Publishers could cache the `toString()` of the `lifter` `BiFunction` they receive. But really I think it fine to work on the following assumption/restriction: if you care about allocations of `scan(Attr.LIFTER)`, just implement a `BiFunction` that has a meaningful `toString` AND make sure to use `Operators.scanPublisher`.
