### ISSUE TITLE
Support creating `Mono` from `java.util.Optional` and "nullable" values

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-core#26]
Reactor Core  is not Java 8+ yet, however it should be able to detect and do the right thing when `Optional` is passed into `Mono.just(T)` much like Spring Framework is Java 6+ but supports `Optional` in a number of places.

Related to that is the question how to deal with creating a `Mono` from a potentially "nullable" value which may be the case when the value is obtained from a source that could return `null` (e.g. resolving a query string parameter for an HTTP request from a Map). One then has to do something like `return (value != null ? Mono.just(value) : Mono.empty())`.

If `Mono.just(T)` supports `Optional` then one could do `return Mono.just(Optional.ofNullable(value))` and that might just be good enough vs an explicit additional operator such as `justOrEmpty(T)`. In any case it makes sense to consider any solution in the context of both `Optional` and "nullable" values.

**Comment by smaldini** [comment]
Mono.just() should stay T without conversion as per the convention it follows (e.g. Mono.just(Callable) vs Mono.fromCallable(Callable)). 
In a dedicated justOrEmpty, we could very much add a resolution as in converters and DependencyUtils to detect Optional presence and handle it.

**Comment by rstoyanchev** [comment]
Okay that sounds good to me with `just(T)` remaining strict and keeping the original value intact.

**Comment by smaldini** [comment]
Fixed by https://github.com/reactor/reactor-core/commit/c105856c6421b9d206c4437b2b9a0efa0407828e and https://github.com/reactor/reactor-core/commit/5e2b0bc61dfaacc1a25ff4e7a709fb3e31ebd8f9
