### ISSUE TITLE
Couldn't find changelog

### ISSUE THREAD

**Issue by qrilka** [reactor/reactor-core#2605]
I couldn't find release notes or changelog for the project. Is this intended or maybe I just  missed some location?

**Comment by simonbasle** [comment]
release notes are published in github releases: https://github.com/reactor/reactor-core/releases/

**Comment by simonbasle** [comment]
(marked as `invalid` just to indicate this issue not being fixed by a commit is "normal")

**Comment by qrilka** [comment]
Ok, thanks.
I see one downside of this decision though - you can't grep Github releases from a local git clone.
