### ISSUE TITLE
Deprecation clean ups in 3.7.0

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2608]
3.6.0 is the **earliest** version at which these deprecation can be removed (add to the list as relevant).

For reference:

 - #2596 : switchOnNext and switchMap with prefetch parameter

## Deprecated APIs to be `actually removed` in 3.6.0:
_Add entries to the list below once a decision has been made to remove deprecations from 3.4.x and earlier to 3.6.0:_
 - [ ] #2607 (following up on #2596)

**Comment by chemicL** [comment]
There are no immediate plans to remove deprecated methods. If they're not limiting us from moving forward, we can keep some deprecations longer. Closing the issue.
