### ISSUE TITLE
Use of JDK deprecated API in reactor.core.publisher.Traces$SharedSecretsCallSiteSupplierFactory$TracingException

### ISSUE THREAD

**Issue by RamCohen** [reactor/reactor-core#2623]
Hi,

reactor.core.publisher.Traces$SharedSecretsCallSiteSupplierFactory$TracingException is using two JDK deprecated APIs:
sun.misc.JavaLangAccess and sun.misc.SharedSecrets

see http://openjdk.java.net/jeps/260

and https://stackoverflow.com/questions/46612648/javalangaccess-and-sharedsecrets-in-java-9

**Comment by simonbasle** [comment]
Hi @RamCohen,
This is on purpose, we have stubs in place that should allow the `Traces` class to pick the best available strategy:
 - on Java 8, use `SharedSecrets`
 - on Java 9, use `StackWalker` API
 - worst case scenario: fallback to `StackTraceElements[]` array
