### ISSUE TITLE
Consistent `delay` behavior in Flux and Mono

### ISSUE THREAD

**Issue by bijukunjummen** [reactor/reactor-core#263]
I feel that the `delay` operator in `Flux` and `Mono` behave in an inconsistent way. Whereas this is correct for `Flux`:

```java
Flux<String> stringFlux = Flux.just("test").delay(Duration.ofSeconds(1));
```

this is NOT consistent for `Mono` - the following does not work(fails type check):
```java
Mono<String> stringMono = Mono.just("test").delay(Duration.ofSeconds(1));
```

I feel that they should behave consistently.

**Comment by akarnokd** [comment]
What do you mean by "NOT correct"?

**Comment by bijukunjummen** [comment]
Sorry wrong statement @akarnokd , meant not consistent, modified now.

**Comment by akarnokd** [comment]
`Mono.delay()` is a static method that emits 0L after the given time has passed. You should see a warning in your IDE about calling a static method on an instance of `Mono.just("test")`.

**Comment by bijukunjummen** [comment]
Yes, I understand that @akarnokd - I understand that for 
```Mono<String> stringMono = Mono.just("test").delay(Duration.ofSeconds(1));``` the static `delay` gets called.

Let me try and contrast the behavior with with Rx-java where delay for Observable and Single behaves the same way:
```
Observable<String> stringObs = Observable.just("test").delay(1, TimeUnit.SECONDS);
Single<String> stringSingle = Single.just("test").delay(1, TimeUnit.SECONDS);
```

This is the consistency that I am looking to see in `delay` method of both `Flux` and `Mono`

**Comment by smaldini** [comment]
We can flag the flux.delay for 3.1 update into (delayEach) or just remove it.

**Comment by simonbasle** [comment]
This is the way we went for now:
 - deprecated `Flux` methods `delay` and `delayMillis`
 - introduced `delayElements` and `delayElementsMillis` instead
 - introduced `delayElement` to `Mono`: an instance method similar to delayElements in Flux
 - `Mono.delay` is still the same static factory method
