### ISSUE TITLE
And operator continues to next publisher no matter there was an error in the chain

### ISSUE THREAD

**Issue by nicoabie** [reactor/reactor-core#2634]
Basically I have:

```java
private Mono<Void> validateShipmentContent(ShipmentContentDTO shipmentContentDTO) {
	if (shipmentContentDTO != null) {
		return shipmentContentValidator.validate(shipmentContentDTO)
			.and(v -> shipmentValueValidator.validate(shipmentContentDTO.getDeclaredValue()));
	} else {
		return Mono.empty();
	}
} 
```

Why does it continue with shipmentValueValidator if shipmentContentValidator have failed first?

Is there any way to have the desired behaviour?

## Expected Behavior

It won't continue executing the chain

## Actual Behavior

it does continue

**Comment by simonbasle** [comment]
What are you observing _exactly_?

If you see that both validators get subscribed, then it is normal: `and` doesn't "continue with". It attempts to subscribe/run the two side and waits for both of them to complete.

In this form, it should however result in an `onError` as soon as one side errors.

**Comment by simonbasle** [comment]
NB: if you want to apply the validators in sequence, chain them using `validator1.then(validator2)` instead.

**Comment by nicoabie** [comment]
So if I use "then" and the first validator results in an error, that error would be propagated and the second validator would not be ran?

**Comment by simonbasle** [comment]
Indeed, it will break and not execute the second validator. then only
continues if the left hand side completed successfully (oncomplete)

**Comment by nicoabie** [comment]
With the example provided and other times we used then, it executes always

**Comment by simonbasle** [comment]
Without more insight into your classes, I cannot really help you here.
Are you sure the `Mono`s returned by your validator functions are correctly constructed?
Are you sure what you're seeing is not A) an eagerly captured value when constructing the validation Monos or B) an invocation of the *method* `validate`, which is always happening by definition even if the underlying `Mono` won't be doing anything until subscribed?

Here is a very simple test demonstrating that `then` fails on an `onError`:

```java
	@Test
	void validatorThenValidator() {
		AtomicReference<String> ref = new AtomicReference<>();

		Mono<Void> step1 = Mono.just("step1")
				.delayElement(Duration.ofSeconds(1))
				.map(v -> { throw new IllegalStateException("boom-" + v);})
				.then();

		Mono<Void> step2 = Mono.just("step2")
				.doOnNext(v -> ref.set(v))
				.then();

		Mono<Void> validators = step1.then(step2);

		assertThatIllegalStateException()
				.isThrownBy(validators::block)
				.withMessage("boom-step1");

		assertThat(ref).as("step2 not executed").hasValue(null);
	}
```

Also, I've just noticed something fishy in your code: why the `v ->` in the `and` call?
What does the `shipmentValueValidator.validate` method return?

You're essentially constructing an inline `Publisher` here that will receive a subscribe notification `v` and *do nothing with it*... Hopefully this is a typo in this issue.

**Comment by nicoabie** [comment]
This is the first validator that gets executed:

```java
@Component
public class ShipmentContentValidator implements Validator<ShipmentContentDTO> {
	@Override
	public Mono<Void> validate(ShipmentContentDTO object) {
		if (object.getDeclaredValue() == null) {
			return Mono.error(new ValidationException("invalid.dto", "The [declared_value] of the shipment content is mandatory"));
		} else {
			return Mono.empty();
		}
	}
}
´´´
`getDeclaredValue() returns ShipmentValueDTO`

I want to only check the second validator if the declared value is different than null:

```java
public class ShipmentValueValidator implements Validator<ShipmentValueDTO> {
	@Override
	public Mono<Void> validate(ShipmentValueDTO object) {
		if (object.getCurrency() == null) {
			return Mono.error(new ValidationException("invalid.dto", "The [currency] of shipment value is mandatory"));
		} else if (object.getAmount() == null) {
			return Mono.error(new ValidationException("invalid.dto", "The [amount] of shipment value is mandatory"));
		} else if (object.getAmount().compareTo(BigDecimal.ZERO) <= 0) {
			return Mono.error(new ValidationException("invalid.dto", "The amount of the shipment value must be positive"));
		} else {
			return Mono.empty();
		}
	}
}
```

Using "and" or "then" the ShipmentValueValidator gets executed anyway even if the first validator fails with an error

```java
private Mono<Void> validateShipmentContent(ShipmentContentDTO shipmentContentDTO) {
		if (shipmentContentDTO == null) {
			return Mono.empty();
		} else {
			return shipmentContentValidator.validate(shipmentContentDTO)
					.then(shipmentValueValidator.validate(shipmentContentDTO.getDeclaredValue()));
		}
	}
```

Here the shipmentContentDTO has a declaredValue of null so I'm returning a Mono.error with the proper exception.

And when `ShipmentValueValidator` is ran I get a null pointer exception in `object.getCurrency()`

**Comment by simonbasle** [comment]
Mmh so you're not applying the validator on the same object, that's one thing I didn't notice in your original example, my bad.

The trouble here is that your constructing the `Mono`s by eagerly extracting the very same data that you wanted to validate with the first validator in the first place.

The error is not in the chain. It is in the _assembling_ of the chain. And it is made worse/hidden away by the usage of `Mono<Void>`, which breaks the relationship between the `ShipmentContentDTO` and `ShipmentValueDTO` validators.

The fact that your `validate` methods are eagerly evaluating the input DTO doesn't help, because the way you assemble the chain means that both `validate` methods will be invoked at assembly time, so they both use the shipmentContent immediately. Nothing has run in Reactor at this point, so yeah the second validator will encounter an NPE.

I'm not sure there is any benefit in using a `Mono` return type vs a plain `Consumer` or `Predicate` here, but it might make more sense if you do plan on having asynchronous validators. If that's the case, here is what I'd recommend: you need to make it so the extraction of the valueDto is lazy.

Depending on what you want to do with the original value once it has passed the checks, I'd consider switching the validators from `Mono<Void>` to `Mono<ShipmentContentDTO>` (even for the second one). 

```java
//I'm assuming this starts from a `Mono<ShipmentContentDTO>`
Mono<ShipmentContentDTO> someShipmentToCheck;

// if you have static set of validators you know upfront, you'd do:
Mono<ShipmentContentDTO> checkedOrFail = someShipmentToCheck
    .flatMap(shipmentContentHasValue::validate)
    .flatMap(shipmentValueValidator::validate)
    .flatMap(shipmentRegisteredAtPortAuthority::validate); //this one is async

// if you need to apply arbitrary (but ordered) collection of validators, you'd rather do:
Mono<ShipmentContentDTO> checkedOrFail2 = someShipmentToCheck
    .flatMap(dto -> {
        Mono<ShipmentContentDTO> validate = Mono.just(dto);
        for(Validator<ShipmentContentDTO> v : validators) {
            validate = validate.flatMap(v::validate);
        }
        /* that's an automatic way of constructing:
        just(dto)
            .flatMap(original -> val1.validate(original))
            .flatMap(passedVal1 -> val2.validate(passedVal1))
            .flatMap(passedVal1And2 -> val3.validate(passedVal1And2)); */
        return validate;
    });
```

With that approach, here is what `shipmentValueValidator` and `shipmentRegisteredAtPortAuthority` implementations might look like:

```java
public class ShipmentValueValidator implements Validator<ShipmentContentDTO> {
	@Override
	public Mono<ShipmentContentDTO> validate(ShipmentContentDTO shipment) {
        ShipmentValueDTO object = shipment.getDeclaredValue();
        assert object != null;

		if (object.getCurrency() == null) {
			return Mono.error(new ValidationException("invalid.dto", "The [currency] of shipment value is mandatory"));
		} else if (object.getAmount() == null) {
			return Mono.error(new ValidationException("invalid.dto", "The [amount] of shipment value is mandatory"));
		} else if (object.getAmount().compareTo(BigDecimal.ZERO) <= 0) {
			return Mono.error(new ValidationException("invalid.dto", "The amount of the shipment value must be positive"));
		} else {
			return Mono.just(shipment); //we reinject the shipment in the loop
		}
	}
}
```

```java
public class PortAuthorityValidator implements Validator<ShipmentContentDTO> {
	
    @Inject
    PortAuthorityService portAuthorityService;

	@Override
	public Mono<ShipmentContentDTO> validate(ShipmentContentDTO shipment) {
        String trackingNumber = shipment.getTrackingNumber();
        
        //this is still a sync check, validation could have been covered with a Predicate or Consumer up until then
		if (trackingNumber == null) {
			return Mono.error(new ValidationException("invalid.dto", "The [trackingNumber] of shipment is mandatory"));
        }

        //this is an example of an async part justifying the `Mono` return type
        return portAuthorityService
            .hasTrackingNumberRegistered(trackingNumber) //answers asynchronously via a `Mono<Boolean>`
            .map(registered -> {
                if (!registered) throw new ValidationException("invalid.dto", "The [trackingNumber] of shipment is not known to port authority"));
                else return shipment; //shipment is valid
             });
	}
}
```

The only caveat is that order matters / there is some assumption or redundancy in the validators themselves.

**Comment by simonbasle** [comment]
I'm pretty confident at this point there is no issue in Reactor, so hopefully the above will have you pointed in the right direction. Closing this as invalid. Good luck! (don't hesitate to ask questions on stackoverflow and gitter if you want help from the community in further designing your validation)
