### ISSUE TITLE
Mono.single() fails to detect missing item when combined with Mono.fromSupplier()

### ISSUE THREAD

**Issue by j-mok** [reactor/reactor-core#2635]
According to [documentation](https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html#fromSupplier-java.util.function.Supplier-) it is perfectly legal to return `null` from the supplier in a supplier-backed mono. This results in an empty mono. When we chain that with the `single()` operator the latter doesn't enforce a single value from the upstream mono by emitting an error, but instead simply relays the _complete_ signal downstream.

## Expected Behavior

`Mono.fromSupplier(() -> null).single()` emits `NoSuchElementException` error.

## Actual Behavior

`Mono.fromSupplier(() -> null).single()` completes.

## Steps to Reproduce

```java
@Test
void reproCase() {
StepVerifier.create(
                Mono.fromSupplier(() -> null)
                    //.hide()       // Uncomment to make the test pass
                    .single())
                    .expectErrorMatches(err -> err instanceof NoSuchElementException)
                    .verify();
}
```

## Possible Solution
It seems there's some kind of incorrect internal reaction between the two operators, as sliding `hide()` between them fixes behavior.

## Your Environment

* Reactor version(s) used: 3.4.3
* JVM version (`java -version`): 1.8.0_242
* OS and version (eg `uname -a`): Win10

**Comment by simonbasle** [comment]
This typically looks like a bug with fusion, we'll look into it. Probably affects 3.3.x as well.

**Comment by OlegDokuka** [comment]
@j-mok this is fixed and will be available with the next release

**Comment by j-mok** [comment]
Great, thanks!
