### ISSUE TITLE
Is there a Chinese community somewhere

### ISSUE THREAD

**Issue by KATKrazy** [reactor/reactor-core#2637]
like a Wechat group or something

-------------------------------------------------

是否有中文的社区？比如一个微信群或者其他性质的社区。

**Comment by simonbasle** [comment]
Not anything official. We have documented support and community channels in https://github.com/reactor/.github/blob/master/SUPPORT.adoc

**Comment by kevinten10** [comment]
Look https://github.com/reactivegroup
