### ISSUE TITLE
Add Flux.doOnEach(Subscriber s)

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#264]
When you need to perform do something per-signal (data or error) you'll typically use, `doOnNext` and `doOnError`, but there are cases where you have a listener that needs to receive both signals.

Currently to receive both signals you need to use two sequential operators; `doOnNext` and then `doOnError`. A `doOnEach(Consumer<? super T> e, Consumer<? super Throwable> t)` method would be more convenient but I understand it's potentially debatable how much sense it makes to expand API surface area for this convenience method. 

**But**, when the listener that needs to receive data and error signals implements Subscriber I see a significant advantage in using ` doOnEach(Subscriber s)` rather than needing to do:

```
.doOnNext(event -> subscriber.onNext(event))
.doOnError(e -> subscriber.onError(throwable))
```

(RxJava expose both versions of `doOnEach` described above.)

**Comment by simonbasle** [comment]
@smaldini and I think the `Subscriber` parameter is confusing and would risk sharing the state of the subscriber to several sources.
Having `doOnEach(nextConsumer, errorConsumer)` doesn't make much sense outside of `Mono`, which already has it in the form of `doOnTerminate`.

That said, adding the following probably makes sense:
  - a `doOnEach(next, error, complete)`
  - a `doOnEach(Consumer<Signal<T>>)` version (notified of subscription, next, error and complete in a single callback receiving `Signal`)

**Comment by simonbasle** [comment]
@dfeist @smaldini see the related PR #288

**Comment by dfeist** [comment]
@simonbasle I'm not convinced that using `Subscriber` is a bad idea, can you expand on what the issue is?

**Comment by simonbasle** [comment]
you probably don't have a proper `Subscriber`, in the sense that it doesn't `subscribe` to anything and doesn't play with backpressure, *or at least it shouldn't*. The natural temptation of passing in a good citizen `Subscriber` that isn't tailored for this specific operator is too high. We don't want to expose that with a javadoc comment as the only guard against abuse.

on the other hand, the Signal-based method feels more advanced from the get go, and the temptation is reduced there. The interesting thing is that `Signal` is a `Consumer<Subscriber>`, so here you go, you have a short way of tying your very specific `Subscriber` with a `doOnEach`.

I'll update the PR with such an example, and remove the lambda based addition.
