### ISSUE TITLE
Flux.mergeOrdered does not propagate onError when it happens

### ISSUE THREAD

**Issue by koldat** [reactor/reactor-core#2640]
Flux.mergeOrdered does not propagate onError when it happens, but on the end of all inner fluxes. In case it is very long running, it can cause huge latencies in calculations as these are not notified soon some nested flux failed. It is even genrating values that are not correct as it cannot know order in case one inner flux fails. It simply treat is as completed.

## Expected Behavior
mergeOrdered should emit onError immediately and call cancel on inner fluxes.

## Actual Behavior
If plays completely all inner fluxes. In case one fail it just ignore it (treat as completed).

## Steps to Reproduce
This example Should fail on number 2, but continue to evaluate and fails on end. It is simulating slow generator using delayElements.

```java
    @Test
    public void test() {
        try {
            Flux<Integer> source1 = Flux.range(0, 20).delayElements(Duration.ofMillis(100));
            Flux<Integer> source2 = Flux.range(0, 20)
                .<Integer>handle((v , sink) -> {
                    if (v < 2) {
                        sink.next(v);
                    } else {
                        sink.error(new NumberFormatException());
                    }
                });
            
            Flux
                .mergeOrdered(1, (i1, i2) -> i1.compareTo(i2), source1, source2)
                .log()
                .limitRate(1)
                .blockLast(Duration.ofSeconds(3));
        } catch (Exception e) {
            e.printStackTrace();
            throw e;
        }
    }
```

```
Output:
10-03-2021 11:33:29.421 [main] INFO  reactor.Flux.PublishOn.1.info - | onSubscribe([Fuseable] FluxPublishOn.PublishOnSubscriber)
10-03-2021 11:33:29.426 [main] INFO  reactor.Flux.PublishOn.1.info - | request(unbounded)
10-03-2021 11:33:29.429 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(0)
10-03-2021 11:33:29.429 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(0)
10-03-2021 11:33:29.429 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(1)
10-03-2021 11:33:29.430 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(1)
10-03-2021 11:33:29.434 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(2) <-- It should fail HERE
10-03-2021 11:33:29.434 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(3)
10-03-2021 11:33:29.435 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(4)
10-03-2021 11:33:29.435 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(5)
10-03-2021 11:33:29.435 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(6)
10-03-2021 11:33:29.435 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(7)
10-03-2021 11:33:29.435 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(8)
10-03-2021 11:33:29.435 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(9)
10-03-2021 11:33:29.435 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(10)
10-03-2021 11:33:29.436 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(11)
10-03-2021 11:33:29.436 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(12)
10-03-2021 11:33:29.436 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(13)
10-03-2021 11:33:29.436 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(14)
10-03-2021 11:33:29.436 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(15)
10-03-2021 11:33:29.436 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(16)
10-03-2021 11:33:29.436 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(17)
10-03-2021 11:33:29.436 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(18)
10-03-2021 11:33:29.437 [main] INFO  reactor.Flux.PublishOn.1.info - | onNext(19)
10-03-2021 11:33:29.437 [main] ERROR reactor.Flux.PublishOn.1.error - | onError(java.lang.NumberFormatException)
10-03-2021 11:33:29.439 [main] ERROR reactor.Flux.PublishOn.1.error - 
java.lang.NumberFormatException: null
	at com.ca.apm.common.MergeOrderedTest.lambda$0(MergeOrderedTest.java:37)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.tryOnNext(FluxHandleFuseable.java:103)
	at reactor.core.publisher.FluxRange$RangeSubscriptionConditional.slowPath(FluxRange.java:303)
	at reactor.core.publisher.FluxRange$RangeSubscriptionConditional.request(FluxRange.java:258)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.request(FluxHandleFuseable.java:243)
	at reactor.core.publisher.FluxMergeOrdered$MergeOrderedInnerSubscriber.onSubscribe(FluxMergeOrdered.java:364)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onSubscribe(FluxHandleFuseable.java:148)
	at reactor.core.publisher.FluxRange.subscribe(FluxRange.java:65)
```

* Reactor version(s) used: Reactor Core 3.3.12

**Comment by koldat** [comment]
@simonbasle I found in unit tests that is is defined behavior. It seems not much useful for our use case. Can I add at least "delayErrors" as an option?

**Comment by OlegDokuka** [comment]
@koldat it sounds like something related to #2631. Can you please check if this is still an issue with the latest snapshot?

**Comment by OlegDokuka** [comment]
@koldat sounds like a good compromise. Do you want to create a PR?

**Comment by yamass** [comment]
I also just ran across this behavior. 

We are using mergeOrdered for Fluxes of live data, so they theoretically never end. Due to this unexpected behavior, we will need to review all our usages of mergeOrdered, since the calculations that we do downstream might be completely off when a single flux fails and goes unnoticed.

This is a very severe problem for us.

By the way, I reduced it to an even simpler unit test:

```
	@Test
	public void mergeOrdered() throws Exception {
		StepVerifier.create(Flux.mergeOrdered(
				Comparator.comparing(x -> x),
				Flux.error(new RuntimeException("foobar")),
				Flux.<String>never()
		).log())
				.verifyError();
	}
```

**Comment by yamass** [comment]
@OlegDokuka I'd appreciate if you could review the category of this ticket. This behavior is so unexpected an undocumented that I think many projects rely on it working a different way than it actually does.

**Comment by koldat** [comment]
@yamass I started work on PR, but then we decided to stop use (were not able to wait for release) of this operator so sorry I did not send it. Let me check again it should be a couple of lines. I will try to send patch today.

**Comment by yamass** [comment]
That would be awesome! Thanks!

**Comment by koldat** [comment]
I have sent pull request #2719 , let me know if it looks good or if any changes are required.

**Comment by yamass** [comment]
@koldat Works great! Thanks a lot!
@OlegDokuka 🙏

**Comment by simonbasle** [comment]
I'm not sure what's the best way to introduce the delayError vs no delayErrors to the current API. we moved away from `boolean delayError` parameter pattern, in favor of the `delayError` suffix, back in 3.1.0 (#480). The trouble in the current situation is that the no-parameter means "delay errors" whereas we'd like it to mean "don't delay errors"... We cannot change that behavior until 3.5.0, though.

We _can_ introduce `mergeOrderedDelayErrors`. I suppose we still need to offer a temporary way to disable delayErrors in 3.4.x in the meantime, as 3.5.0 won't happen until next year (with an M1 probably end of 2021)...

**Comment by simonbasle** [comment]
that one is complicated to deal with in the 3.4 timeline. even though the misalignment compared to other merge APIs was unfortunate, this is not a bug: the operator is working as originally intended.

there is another factor which could inform the decision: we're thinking about a reorganization of operators that have a big number of variants and overloads, for which `merge*` qualifies, in an upcoming 3.5/4.0 (with probably a first milestone at the end of this year)... this could be a good opportunity to change the behavior and provide both options, but that won't be possible until that new alternative API is introduced.

 - in order to fix it _now_, we'd need a clean slate and that means reintroducing the operator under a different name. @yamass offered `mergePickSmallest`. I propose `mergeComparing`.
 - the other choice is to wait for the next major, where the current API will likely get deprecated and offered through a slightly different path, at which point we can introduce both variants and have the suffix-less one "change" default behavior (ie. fail fast).

@yamass if the later solution is the one taken on, it would probably mean you need to maintain @koldat's version in your own codebase if you depend on a fix while still on 3.4.x...

**Comment by koldat** [comment]
@simonbasle I can introduce mergeComparing. Should I introduce just the absolute minimum (one or two variants) so that you will not need to keep the compatibility for 3.5/4.0? Are you OK with this list?

```java
	public static <T> Flux<T> mergeComparing(int prefetch, Comparator<? super T> comparator, Publisher<? extends T>... sources);
	public static <T> Flux<T> mergeComparing(Comparator<? super T> comparator, Publisher<? extends T>... sources);
	public static <I extends Comparable<? super I>> Flux<I> mergeComparing(Publisher<? extends I>... sources);

	public final Flux<T> mergeComparingWith(Publisher<? extends T> other, Comparator<? super T> otherComparator);
```

**Comment by simonbasle** [comment]
@koldat that and a single `mergeComparingDelayError(int prefetch, Comparator, Publisher...)` sounds good.

The `mergeComparingWith` will inherit the delayError behavior if its source is a mergeComparing already, and otherwise default to the base behavior (which is now fail fast), just like other mergeWith operators.

**Comment by yamass** [comment]
@simonbasle `mergeComparing` sounds very good to me.

@koldat Thank you so much for your help.

We really would love to _not_ have to maintain my own branch of reactor. So having a separate name an with an absolute minimum implementation is great news for us.

**Comment by simonbasle** [comment]
> We really would love to _not_ have to maintain my own branch of reactor.

for future reference, you don't have to fork reactor-core to implement custom operators. the equivalent of the `FluxMergeOrdered` class in this case can be implemented in your codebase and applied in an otherwise vanilla reactor code chain by using `Flux#transform`.

**Comment by yamass** [comment]
@simonbasle You are right, that's always an option (in fact, we are using this operator already).
