### ISSUE TITLE
java11 compatibility

### ISSUE THREAD

**Issue by oferbaranes** [reactor/reactor-core#2641]
Hello,
When checking compatibility to java11 using jdep, that was the output:
jdeps.exe -jdkinternals c:\Users\ofer.baranes\Downloads\reactor-core-3.4.3.jar
		reactor-core-3.4.3.jar -> JDK removed internal API
		   reactor.core.publisher.Traces$SharedSecretsCallSiteSupplierFactory$TracingException -> sun.misc.JavaLangAccess                            JDK internal API (JDK removed internal API)
		   reactor.core.publisher.Traces$SharedSecretsCallSiteSupplierFactory$TracingException -> sun.misc.SharedSecrets                             JDK internal API (JDK removed internal API)

		Warning: JDK internal APIs are unsupported and private to JDK implementation that are
		subject to be removed or changed incompatibly and could break your application.
		Please modify your code to eliminate dependence on any JDK internal APIs.
		For the most recent update on JDK internal API replacements, please check:
		https://wiki.openjdk.java.net/display/JDK8/Java+Dependency+Analysis+Tool

		JDK Internal API                         Suggested Replacement
		----------------                         ---------------------
		sun.misc.JavaLangAccess                  Removed. See http://openjdk.java.net/jeps/260
		sun.misc.SharedSecrets                   Removed. See http://openjdk.java.net/jeps/260 

Would there be a compatible version to java 11? If so then When?
Is there any way to evaluate if this code would not be reachable on specific project?

Thanks
Ofer

**Comment by OlegDokuka** [comment]
Hi @oferbaranes!

Thank you for asking!

Project Reactor is fully [JDK 9+ compatible](https://github.com/reactor/reactor-core/blob/master/reactor-core/build.gradle#L269) though it looks like it uses `sun.misc.*` packages. 

The magic happens at the [runtime](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/Traces.java#L77) and we do not use those packages if we know we are JRE9+.

**Comment by OlegDokuka** [comment]
@oferbaranes let me know if you need this ticket opened

**Comment by oferbaranes** [comment]
Thanks it's ok with me
