### ISSUE TITLE
Ability to subscribe to delayUntil flux on other schedulers

### ISSUE THREAD

**Issue by pavanpkp33** [reactor/reactor-core#2642]
Hi,

Today, when I introduce a delayUntil operator in my flux chain, it automatically subscribes on schedulers.parallel. Can we have a behavior to specify the schedulers for it to subscribe on?

I have a series of long running tasks which are inter dependent. So the execution result from previous task is used in the next. I have these list of tasks in a list and do the following.

    return Flux.fromIterable(taskList) 
        .delayUntil(reactiveTask -> reactiveTask.run(ctx)) //automatically moves to schedulers.parallel
        .doOnCancel(() -> log.info("Task cancelled"))
        .doOnComplete(() -> log.info("Completed flow"))
        .then(Mono.just(ctx));
   

For lower number of concurrent requests, this works fine but at scale, the response times increases. Do we have a way to handle this currently or is it planned in future release?

Thanks

@simonbasle  requesting your comment.

**Comment by OlegDokuka** [comment]
@pavanpkp33 `delayUntil` specify any particular scheduler to subscribe on and does not use it inside its logic. You may always override the scheduler on which you want to subscribe using `subscribeOn` or on which you want to observe events using `publishOn`.

The main reason why you see your events on another publisher can be that your `reactiveTask` is publishing events on the Parallel scheduler. If you enhance it with `publishOn(anotherScheduler)` or put `publishOn` after the `delayUntil` you will ensure that you are doing the work on the proper scheduler

**Comment by OlegDokuka** [comment]
closed that ticket as it is a good candidate for StackOverflow or gitter discussion. @pavanpkp33 let me know if you need this ticket opened or feel free to reopen it just in case
