### ISSUE TITLE
provide common `StateMachine` impl for Flux and Mono

### ISSUE THREAD

**Issue by OlegDokuka** [reactor/reactor-core#2647]
Experiment with an abstraction that helps building the internals of operators, with bitmasks

**Comment by chemicL** [comment]
For the record, #3634 includes some general methods that could be extracted to a common class if needed in the future.

For now I'll close this issue as it has not been picked up for some time and re-writing existing mechanisms to use a new abstraction is not planned currently. If there's more work around these areas it would definitely be a nice-to-have.
