### ISSUE TITLE
Use functional style to encapsulate `instanceof` operation.

### ISSUE THREAD

**Issue by kevinten10** [reactor/reactor-core#2653]
I want to discuss with you about the reactor-core source code format.

There are a lot of use of `instanceof` operations, E.g:
`if (source instanceof Fuseable)`
`if (this instanceof Fuseable)`
`if (a[0] instanceof Fuseable)`
`if (out instanceof Fuseable)`
In most cases, it is followed by an `if-else` structure, which is `Supplier` or `Runnable`

**Reactor provides chain programming style externally, why not use this style internally?**

we can use:
```
IsFuseable(this/source)
    .map(()-> Supplier/Runnable)
    .orElse(()-> Supplier/Runnable)
```

Of course, we can provide an abstract class `InstanceOfOperator(Object, Class)`, and provide `FuseableOperator/FluxOperator` these implementations.

I understand that this will help put the `if-else` branch on the same indentation structure.
At the same time, it is helpful for unified management of `instanceOf` conversion, rather than abuse of `instanceOf` in the code.

**Comment by kevinten10** [comment]
I want to hear your opinion

And if necessary, I can provide a corresponding PR. And the code style will refer to [vavr](https://github.com/vavr-io/vavr)

**Comment by simonbasle** [comment]
Reactor implementation classes are low level and are all about using the most efficient and performant patterns. Once key concern we have is to avoid creating unnecessary garbage to reduce GC pressure. This goes contrary to that goal.

**Comment by kevinten10** [comment]
Thanks for your reply! I understand what you mean.

If we migrate to JDK11 ZGC, will small objects with short life cycles have minimal impact on performance?

Maybe we can adopt this approach in the future..

**Comment by simonbasle** [comment]
We'll keep that in mind, although a switch to JDK11+ for the baseline is not scheduled yet.
