### ISSUE TITLE
Avoid infinite discard loop on fused infinite fromStream/fromIterable

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#2654]
Currently, operators can call `Operators.discardQueueWithClear(q)` even if the `q` is actually a `QueueSubscription` on which fusion has been negotiated.

If no discard handler has been defined in the `Context`, `q.clear()` is invoked which is fine.

However, if an actual discard handler has been defined in the `Context`, we go into a loop of `q.poll()` until the queue is drained.

This is problematic if the `Queue` is actually an `IterableSubscription` acting as a facade over an infinite generator. The logic then goes into an infinite loop.

We're currently thinking about defining the `Mono` fusion contract more strictly (#2636), which might improve the situation.

That said, it might not be necessary to change anything in the `Operators.discardQueueWithClear` for this particular case. If `poll()` loop is interrupted when `cancelled` and the `knowToBeFinite` flag is `false`, this should fix the issue (including with Kotlin's `generate(1).asIterable()`).

See also rsocket/rsocket-java#992 for the original issue leading to an infinite loop.

## Steps to Reproduce
```java
	@Test
	void iterableFromInfiniteGenerator() {
		class Generator implements Iterable<Integer> {

			final int seed;

			Generator(int seed) {
				this.seed = seed;
			}

			@NotNull
			@Override
			public Iterator<Integer> iterator() {
				return new Iterator<Integer>() {
					int value = seed;

					@Override
					public boolean hasNext() {
						return true;
					}

					@Override
					public Integer next() {
						return value++;
					}
				};
			}
		}

		Generator one = new Generator(1);

		//smoke test: this Iterable is indeed NOT SIZED
		assertThat(one.spliterator().hasCharacteristics(Spliterator.SIZED)).as("spliterator not sized").isFalse();

		AtomicInteger discardCount = new AtomicInteger();

		Flux.fromIterable(one)
		    .filter(i -> true)
		    .publishOn(Schedulers.single())
		    .take(10)
		    .doOnDiscard(Integer.class, i -> discardCount.incrementAndGet())
		    .blockLast(Duration.ofSeconds(1));

		assertThat(discardCount)
				.as("discardCount")
				.hasValue(0);
	}
```

This also affects `fromStream`, which is based on `FluxIterableSubscription` as well.

**Comment by OlegDokuka** [comment]
related #2626 #2636
