### ISSUE TITLE
Should FluxUsingWhen / MonoUsingWhen subscribe to asyncCancel if cancelled before resourcePublisher has emitted?

### ISSUE THREAD

**Issue by andreisilviudragnea** [reactor/reactor-core#2661]
For the moment, the `Pool.withPoolable()` method from `reactor-pool` does not subscribe to `asyncCancel` if the `Flux.usingWhen()` inside is cancelled before `resourcePublisher` has emitted its value.

Is this a `Flux.usingWhen()` bug, a `Pool.withPoolable()` bug or neither.

I have provided a `Mono.usingWhen()` example [here](https://github.com/andreisilviudragnea/project-reactor-bugs/blob/master/src/test/java/com/example/MonoUsingWhenBugTest.java). The test passes if you un-comment `doOnCancel()`.

I have tried to fix https://github.com/reactor/reactor-pool/issues/124 [here](https://github.com/andreisilviudragnea/project-reactor-bugs/blob/master/src/test/java/com/example/ReactorPoolBugTest.java), but failed.

This issue also relates to https://github.com/reactor/reactor-core/issues/1233.

## Desired solution

`FluxUsingWhen` / `MonoUsingWhen` should at least document what happens on cancellation if the resource has already been emitted or not.

At the moment, I do not know how to fix the https://github.com/reactor/reactor-pool/issues/124 bug only by using existing operators in a clever manner. I do not think this is possible. So the only solution is to subscribe to `asyncCancel` if cancelled before `resourcePublisher` has emitted from inside `FluxUsingWhen` / `MonoUsingWhen` implementation.

**Comment by simonbasle** [comment]
The `asyncCancel` handler is a `Function`, actually deriving "how to release" from the value. If the value hasn't been emitted, then there is nothing to process. I don't think the bug really lies here
