### ISSUE TITLE
What is the alternative to getPending() from EmitterProcessor using Sinks.many().multicast().onBackpressureBuffer()

### ISSUE THREAD

**Issue by antonalechnovic** [reactor/reactor-core#2664]
When upgrading to reactor 3.4.4 , the  _EmitterProcessor_ got deprecated , there is no suggestion on what to use for:
 _EmitterProcessor::getPending_  ("Returns: the number of parked elements in the emitter backlog.")
 
 On the class documentation it is suggested to replace entire processor with:
 
  _Sinks.many().multicast().onBackpressureBuffer()_
  
  but i can't find alternative method to _getPending_

## Documentation Issue
Deprecated note doesn't state what is the alternative as entire class is deprecated

**Comment by simonbasle** [comment]
This is available as `Scannable.from(sink).scan(Attr.BUFFERED)` currently.

**Comment by simonbasle** [comment]
Actually, `Sinks.Many` extends `Scannable` so we can do `sink.scan(Attr.BUFFERED)` directly.

**Comment by antonalechnovic** [comment]
Thank you, :bow:
