### ISSUE TITLE
Typo in example code

### ISSUE THREAD

**Issue by somebodil** [reactor/reactor-core#2665]
## Documentation Issue

In https://projectreactor.io/docs/core/release/reference/index.html#_fallback_method

```
Flux.just("key1", "key2")
    .flatMap(k -> callExternalService(k) 
        .onErrorResume(e -> getFromCache(k)) 
    );
```

## Improvement Suggestion
```
Flux.just("key1", "key2")
    .flatMap(k -> callExternalService(k))
    .onErrorResume(e -> getFromCache(k));
```

**Comment by simonbasle** [comment]
After reviewing your suggestion, the original snippet is laid out as intended, and the suggestion wouldn't even compile. `k` is only available inside the lambda passed to `flatMap`.

Even if it worked, there would be a subtle but important difference between chaining the `onErrorResume` on `callExternalService(k)` vs on the whole `flatMap(...)`: it allows to deal with all errors even if both `key1` and `key2` trigger an error.

Putting it on the `flatMap` would cancel the sequence and potentially not process `key2` if something went wrong with `key1`.

What you intended to suggest would be the reactive equivalent of:

```java
String v1 = null;
String v2 = null;
try {
    v1 = processKey(key1);
    try {
        v2 = processKey(key2);
    }
    catch (Throwable e) {
        v2 = getFromCache(key2);
    }
}
catch (Throwable e) {
    v1 = getFromCache(key1);
}
```
which can leave `v2` to `null` if processing key1 fails.
