### ISSUE TITLE
GroupBy hangs when used with TakeUntil on version 3.3.13.RELEASE

### ISSUE THREAD

**Issue by TunaYagci** [reactor/reactor-core#2675]
Flux.groupBy function hangs (waits infinitely) if used with Flux.takeUntil method.

## Expected Behavior
It should continue processing.

## Actual Behavior
It waits infinitely.

## Steps to Reproduce

```java
    @Test
    void test() {
        StepVerifier.create(
                Flux.just(0, 1, 2, 3)
                        .groupBy(f -> f / 2, 1)
                        .flatMap(a -> a.takeUntil(i -> i % 2 == 1)))
                .expectNext(0, 1, 2, 3)
                .expectComplete()
                .verify(Duration.ofMillis(500));
    }
```

## Expected Behaviour for code above

* It should group `0, 1 ` and then `2, 3` (by function `f/2`)
* the number 0 should not be emitted until number 1 is requested
* After 1 arrives the numbers 0 and 1 should be emitted
* The number 2 should not be emitted until number 3 is requested
* After 2 arrives the numbers 2 and 3 should be emitted

## Possible Solution
Using version `3.3.12.RELEASE` solves it. I believe it's caused by this PR: https://github.com/reactor/reactor-core/pull/2450

## Your Environment

* Reactor version(s) used: Starts from `3.3.13.RELEASE`
* Other relevant libraries versions (eg. `netty`, ...): `reactor-test`
* JVM version (`java -version`): 8, 11
* OS and version (eg `uname -a`): Mac OSX Catalina, Alpine Linux

**Comment by TunaYagci** [comment]
I'm not sure if this is a duplicate of https://github.com/reactor/reactor-core/issues/2138. Please close this one if so.

**Comment by simonbasle** [comment]
Yeah it looks like there is a replenishing issue when the group cancellation coincides exactly with the amount requested to upstream.
