### ISSUE TITLE
Concurrency limit for Monos

### ISSUE THREAD

**Issue by skorhone** [reactor/reactor-core#2678]
## Motivation
Given that many frameworks (e.g. spring cloud) provide interfaces for handling workload as Monos and that not every backend system can tolerate massive amount of parallel requests, having an option to limit concurrency of Monos would be beneficial. We've already managed to crash some of backends in load testing by driving too much parallel requests on them.

Now someone may think, that we should cap the upstream (flux). And here is the problem, flux diverges at point where it's already mapped to a Mono by framework. Adding a limit to upstream flux would add a global limit. Also, some systems may not handle load peaks too well. Distributing the peak over time by applying concurrency limit just makes sense (I think).

## Desired solution
Simple interface for creating concurrency restrictions. Following code fragment would create a concurrency limiter with concurrency limit of 5. It runs toUpperCase() method using concurrency the limit. toLowerCase() is not affected by the limit

    Mono<String> monoToLimit = Mono.just("value").map(v -> v.toUpperCase());
    ConcurrencyLimiter limiter = ConcurrencyLimiter.createWithLimit(5);
    limiter.limit(monoToLimit).
        map(v -> v.toLowerCase());
   

## Considered alternatives
Using a pool (reactor-pool) with dummy objects (e.g pool of integers). Pool seems to be quite heavy weight object for the purpose and abstraction is not correct.

## Additional context
I've already created a solution for this. But considering that you may have better ideas on how-to tackle this problem, I'll keep it to myself for now :-)

**Comment by simonbasle** [comment]
This looks like something an external library could offer, better than in `reactor-core`.

Have you explored libraries like `Resilience4J`? I know they have reactive APIs...

Otherwise, I can maybe see this being added to the `reactor-pool` project, as a complement to the pool, but as a last resort.

**Comment by skorhone** [comment]
I hadn't looked at Resielence4J previously. It has a feature called bulkhead, which can be used for limiting concurrency. However, it seems to be blocking implementation that utilizes its' own thread pool in the background. Having a dedicated thread pool for waiting doesn't sound right in reactive application

**Comment by simonbasle** [comment]
maintainers of Resilience4J might be interested if you have a more reactive pattern to offer for their Reactor integration/version. For now, I don't think that belongs to reactor-core.

Another potential thing to look at is Netflix's Concurrency Limits project, although it is not maintained anymore, the algorithms used as still relevant.

Finally, a pool from reactor-pool can indeed be used to that effect, with a bit more overhead.

I don't think we have the bandwidth to maintain a leaner tailor-made structure right now to be honest.
