### ISSUE TITLE
Mono.share() is canceled on subscription disposal

### ISSUE THREAD

**Issue by yamass** [reactor/reactor-core#2680]
## Expected Behavior

When doing `var sharedMono = innerMono.share()`, the `innerMono` should not be canceled if calling `sharedMono.subscribe().dispose()`.

At least, that's what the JavaDoc for `Mono.share()` suggests: `It's worth noting this is an un-cancellable Subscription.`

## Actual Behavior

The `innerMono` is canceled. 

## Steps to Reproduce

```
		Mono.create(monoSink -> {
			monoSink.onCancel(() -> {
				System.out.println("CANCELED");
			});
			monoSink.success("asdf");
		})
				.subscribeOn(Schedulers.boundedElastic())
				.share()
				.subscribe()
				.dispose();

		Thread.sleep(1000);
```
Prints `CANCELED`.

By the way, `innerMono.cache().subscribe().dispose` does NOT cancel `innerMono`, although the JavaDoc makes no statement about cancellation behavior... (just replace `share()` with `cache()` in the example.

## Possible Solution

This might be a bug in the implementation or documentation, or simply me not understanding the documentation right.

Please also note that the marble diagram for `share()` needs a fix, too. (see its `cancel()` arrow)

Also, please consider documenting the cancellation behavior of `cache()`.

Meanwhile, I will use `cache()` as a workaround. It might actually also make sense to document the difference between these two methods.

Thanks a lot!

## Your Environment

* Reactor version(s) used: 3.4.5
* JVM version (`java -version`): 14.0.1
* OS and version (eg `uname -a`): MacOS 11.2.3

**Comment by simonbasle** [comment]
we need to backtrack a bit, ensure which behavior is the "correct" one and better document the two operators behavior in face of cancellation, indeed.

**Comment by simonbasle** [comment]
I'm not sure what to do here in terms of timeline / milestone for changing this.
Can we consider that `Flux.share().subscribe()` returning a `Disposable` that is the same for all subsequent subscriptions() and effectively terminates the underlying processor a bug?

Opened #2756 to explore a potential fix
