### ISSUE TITLE
Repeat depend on the last emitted element

### ISSUE THREAD

**Issue by vipcxj** [reactor/reactor-core#2702]
## Motivation

I need to repeat a task with a boolean return value. And stop when the return value is true.
But it seems that the current `repeat` api not work. I have search the network and issues.
I found this #414 . @simonbasle said it is impossible for `retry`, but what about repeat? It seems that `repeat` not work too.

## Desired solution

I need a workaround.

## Considered alternatives

Add a new api, such as `redo`
```java
Mono.defer(() => {
   if (...) return Mono.just(false);
   else return Mono.just(true);
}).redoWhen(emitted -> !emitted)
```
or with a backoff and timeout
```java
Mono.defer(() => {
   if (...) return Mono.just(false);
   else return Mono.just(true);
}).redoWhen(emitted -> !emitted, 1000, 1000 * 30)
```

**Comment by simonbasle** [comment]
another workaround without the use of the exception trick: maintain state in a `defer`:

```java
@Test
void test() {
	AtomicInteger source = new AtomicInteger(10);
	Mono<Integer> mono = Mono.fromCallable(source::decrementAndGet).hide();

	Flux<Integer> repeated = Flux.defer(() -> {
		//we need a defer so that each subscriber to the outer Flux
		//gets its own AtomicBoolean and doesn't share state
		AtomicBoolean continueFlag = new AtomicBoolean(true);

		return mono.doOnNext(v -> {
			//using side-effect to update the subscriber-specific state used to stop repeating
			if (v == 3) {
				System.out.println("stopping after " + v);
				continueFlag.set(false);
			}
		})
		//by doing the conditional repeat inside the defer, we can use the continueFlag state
		.repeat(continueFlag::get);
	});

	repeated.log().blockLast();
}
```

**Comment by vipcxj** [comment]
Thanks, this should be an acceptable workaround, but I think it's better to provide an off-the-shelf API for such a common feature. After all, not everyone is lucky enough to get your reply.

**Comment by na-le** [comment]
I have this issue too and wonder how the workaround can help.
(I don't want to use the first workaround that throws an exception because I think it's strange and not clean and can affect the performance in case of loop that should run all the time)

I want to pall our message broker and in case I get empty results, to poll again:

without reactive (psudo code) :
```
       var records = consumer.poll()
        while (records.isEmpty) {
            records = consumer.poll()
        }
```

how can I implement it with Mono?

**Comment by elrob** [comment]
I think `takeUntil` or `takeWhile` work in this scenario.

```java
Mono.defer(() -> doSomethingWhichReturnsMonoFoo())
    .repeat()
    .takeUntil(foo -> conditionMet(foo));
```
