### ISSUE TITLE
Ability to destruct tuples when using Kotlin

### ISSUE THREAD

**Issue by PojahnM** [reactor/reactor-core#2704]

**Comment by simonbasle** [comment]
looks like this would belong to `reactor/reactor-kotlin-extensions` ?
please also provide more details, as per the [issue template](https://github.com/reactor/reactor-core/issues/new?assignees=&labels=triage%2Fenhancement%3Aquestion%3A&template=enhancement---suggestion.md&title=)

**Comment by PojahnM** [comment]
You're right. This should be in kotlin extensions.
