### ISSUE TITLE
Inconsistent retry behaviour of Sinks.Multicast, between one or more subscribers

### ISSUE THREAD

**Issue by PMacho** [reactor/reactor-core#2712]
`Sinks.Multicast` in combination with `switchMap` and `retry` behaves different when there is one subscriber compared to when there are multiple subscribers.

## Expected Behavior

The following two show cases should either both fail, or both succeed:

```
    @Test
    void retryMulticastFluxWithSwitchMapShowcase() throws InterruptedException {
        final int cycles = 5;
        final int messagesPerCycle = 10;
        final int messagesWithoutError = 8;

        Sinks.Many<Integer> sink = Sinks.many().multicast().onBackpressureBuffer(10, false);
        AtomicInteger counter = new AtomicInteger(0);

        CountDownLatch countDownLatch = new CountDownLatch(cycles * messagesWithoutError);
        Queue<String> messageSink = new ConcurrentLinkedQueue<>();

        sink
                .asFlux()
                .switchMap(i -> Flux
                        .range(0, messagesPerCycle)
                        .delayElements(Duration.ofMillis(10))
                        .flatMap(j -> j == messagesWithoutError
                                ? Mono.error(new Throwable("ANY"))
                                : Mono.just(toMessage(i, j))
                        )
                )
                .doOnNext(messageSink::offer)
                .retryWhen(Retry
                        .indefinitely()
                        .doBeforeRetry(retrySignal -> sink.tryEmitNext(counter.getAndIncrement()))
                )
                .subscribe(next -> countDownLatch.countDown());

        sink.tryEmitNext(counter.getAndIncrement());

        countDownLatch.await();

        assertSink(cycles, messagesWithoutError, messageSink);
    }

    @Test
    void retryMulticastFluxWithSwitchMapAndTwoSubscribersShowcase() throws InterruptedException {
        final int cycles = 5;
        final int messagesPerCycle = 10;
        final int messagesWithoutError = 8;

        Sinks.Many<Integer> sink = Sinks.many().multicast().onBackpressureBuffer(10, false);
        AtomicInteger counter = new AtomicInteger(0);

        CountDownLatch countDownLatch1 = new CountDownLatch(cycles * messagesWithoutError);
        Queue<String> messageSink1 = new ConcurrentLinkedQueue<>();
        Queue<String> messageSink2 = new ConcurrentLinkedQueue<>();

        sink
                .asFlux()
                .switchMap(i -> Flux
                        .range(0, messagesPerCycle)
                        .delayElements(Duration.ofMillis(10))
                        .flatMap(j -> j == messagesWithoutError
                                ? Mono.error(new Throwable("ANY"))
                                : Mono.just(toMessage(i, j))
                        )
                )
                .retryWhen(Retry
                        .indefinitely()
                        .doAfterRetry(retrySignal -> sink.tryEmitNext(counter.getAndIncrement()))
                )
                .doOnNext(messageSink1::offer)
                .subscribe(next -> countDownLatch1.countDown());

        sink
                .asFlux()
                .switchMap(i -> Flux
                        .range(0, messagesPerCycle)
                        .delayElements(Duration.ofMillis(5))
                        .flatMap(j -> Mono.just(toMessage(i, j)))
                )
                .doOnNext(messageSink2::offer)
                .subscribe();

        sink.tryEmitNext(counter.getAndIncrement());

        countDownLatch1.await();

        assertSink(cycles, messagesWithoutError, messageSink1);
        assertSink(cycles, messagesPerCycle, messageSink2);
    }

    private void assertSink(int cycles, int messagesWithoutError, Queue<String> sink) {
        List<String> expected = IntStream
                .range(0, cycles)
                .boxed()
                .flatMap(cycle -> IntStream
                        .range(0, messagesWithoutError)
                        .mapToObj(messageCounter -> toMessage(cycle, messageCounter))
                )
                .collect(Collectors.toList());
        org.junit.jupiter.api.Assertions.assertTrue(expected.size() <= sink.size());
        assertThat(sink).containsAll(expected);
    }

    private String toMessage(int i, int j) {
        return "" + i + ": " + j;
    }
``` 

## Actual Behavior

The first test succeeds, while the second one waits indefinitely. This is, since after the retry the first subscriber doesn't receive `onNext` signals from the `sink` any more.

## Steps to Reproduce

s. above

## Possible Solution

There are many interesting cases:

1. Both tests wait indefinitely if the `Sink` is defined with `autoCancel=true`.
2. The second test succeeds when `retryWhen` happens inside `switchMap`.
3. Both tests succeed for `Sinks.many().replay()`. 

## Your Environment

* Reactor version(s) used: 3.4.4
* JVM version (`java -version`): 1.8.0_232

**Comment by simonbasle** [comment]
I think the actual issue is that `doAfterRetry` of `RetryWhen` is misleading: it doesn't really add a pure side effect, but is susceptible to the same caveat as its `doAfterRetryAsync` counterpart: it transforms the signal that is emitted in the companion publisher, so it effectively delays the retry.

Long story short: your attempt at triggering the switchMap inside `doAfterRetry` cannot work.

What happens, as advertised by the `Sinks.many().multicast().onBackpressureBuffer` javadoc, is that the second subscriber receives the signal from the sink, as triggered from inside `doAfterRetry`. THEN the retry resubscription occurs, and subscriber1 doesn't see any sink trigger (since it was already "consumed" by subscriber2, and that flavor of sink doesn't replay early signals unless there is 0 subscriber).

When only 1 subscriber is used, which errors, it detaches itself from the sink and the sink is back to the state where it has 0 subscriber, so it buffer a few (10 per your configuration) elements.

When `autoCancel=true`, the sink itself stop accepting new data once it reaches 0 subscribers, which is even worse.

That also explain why it works with `replay()`, which has the semantic of replaying that sink signal to the switchMap.

**Comment by PMacho** [comment]
@simonbasle 
Thank you for the clear explanation. 

In the mean time, I actually figured that `doAfterRetry` is not really after retry but just adds an operator to the companion, thus still gets called before actually calling `resubscribe()` of the `main` publisher. As you said, this name is really quite misleading, even though the javadoc of `doAfterRetryAsync` says "thus delaying the resulting retry trigger with the additional Mono" .
Yet, the explanation about the subscriber count really helped, especially "sink doesn't replay early signals unless there is 0 subscriber".

For the record: Wouldn't it be possible to really add behaviour after retries, like `retryWhen(Retry retrySpec, Consumer<T> doAfterRetry)`?

**Comment by simonbasle** [comment]
I think you probably want to explore checking state in a `doFirst` or `defer` at the source, rather than trying to trigger side effects from `retryWhen` and reacting to these side effects in `switchMap`. I'm not inclined to add such a variant, at least not until more obvious use cases surface.

**Comment by PMacho** [comment]
@simonbasle Thanks for the hint. In the mean time, I have a working solution that actually does check its own state and defers requests accordingly. Took me some time however, to build that up. Anyways, thank you.
