### ISSUE TITLE
Reactor Mono:blockOptional have some issue with spring actuator 

### ISSUE THREAD

**Issue by toannh0104** [reactor/reactor-core#2713]
Reactor Mono:blockOptional not work when set this configuration `management.endpoints.enabled-by-default=true`

## Expected Behavior
Mono:blockOptional should work with `management.endpoints.enabled-by-default=true`

## Actual Behavior
Mono:blockOptional is not work when `management.endpoints.enabled-by-default=true` is present 

## Steps to Reproduce

```java
        val responses = configurationClient.getData() // return json object 
                .flatMap { it.bodyToMono(object : ParameterizedTypeReference<GeneralResponse<Array<ObjectResponse>>>() {}) 
                 }
                .map { it.data }
                .blockOptional()  // exception this line 
                .orElse(emptyArray())!!
```

## Possible Solution
Workaround is set `management.endpoints.enabled-by-default=false`

## Your Environment
- Microservice
- Spring cloud configuration
- Spring boot 2.3.9.RELEASE
- Spring cloud Hoxton.SR10

* Reactor-core 3.3.14
* Other relevant libraries versions: Netty 4.1.59
* JVM version (`java -version`): 1.8
* OS and version (eg `uname -a`): macos catalina

**Comment by simonbasle** [comment]
what do you expect? what is the exception? what do you mean by "work normal"?

it seems it has less to do with `blockOptional` than it has to do with the sequence emitting an unexpected `onError(Throwable)`.

there is nothing inherently wrong with `blockOptional` throwing , since it is a bridge between the imperative and reactive worlds: throwing is the correct way for it to translate a reactive `onError` event to the imperative world.

So without any information on the exception that is propagated, this issue is pretty much useless 🤦

**Comment by toannh0104** [comment]
I mean this method `.blockOptional()` is not work with spring actuator property `management.endpoints.enabled-by-default=true` 

note, above code work well with `management.endpoints.enabled-by-default=false`

**Comment by simonbasle** [comment]
where do you call that code? blocking should be a deliberate and last resort decision in any reactive application...

**Comment by toannh0104** [comment]
did you try to reproduce before closing the ticket?

**Comment by simonbasle** [comment]
- you provide a snippet of code that is not runnable as is and you give no indication at what exactly you are doing, and where you are running this piece of blocking code, which is a critical piece of information
 - you just say "it doesn't work" and "unexpected behavior" but fail to say which exception / fail to provide a stacktrace
 - it is hard to make sense of some of the sentences you make (what's "netty server's console" for example? are you saying you have multiple applications running in several terminals? what do you mean by  "I turn off the Netty server"?)
 - good of you to have opened a stackoverflow question, but you've made the same mistakes in there that in this issue (and oh surprise the first comment you got is "what is the exception")

> have you try to reproduce it before closing the ticket?

No, how could I even begin to reproduce with the information you have provided? I've tried to get more information from you and didn't, so I closed this low-effort issue.

**Comment by simonbasle** [comment]
To be clear, I don't expect there is anything wrong with `blockOptional`. It is a very straightforward piece of code: wait for an `onComplete` or `onError` terminal signal and throw the exception if any. It is also clearly not a method that should be used willy-nilly in a reactive application, as it goes back to an imperative and blocking mode of operations.

I'll happily reopen the issue if you end up providing relevant information, although at that point I expect stackoverflow to be a better place to resolve this.

**Comment by toannh0104** [comment]
The issue is solved, I believe the root cause is not related to Mono or spring actuator its self but might some others.
1. **centralizeConfigurationClient.getClientSignatureKeys() => this is GET request always return Mono<ClientResponse> 200-success**
2. when **management.endpoints.enabled-by-default=true** is present spring boot application still work fine but It mights introduce a conflict somewhere that I still don't know exactly where is it
3. What I'm expecting here is this snipcode should throw some exceptions that what is happening when convert to the  reactive worlds but It **doesn't throw any exceptions** that y very hard to know what wrong  
```        
val keyResponses = centralizeConfigurationClient.Data()
    .flatMap { it.bodyToMono(object : ParameterizedTypeReference<GeneralResponse<Array<ObjectResponse>>>() {}) 
     }
    .map { it.data }
    .blockOptional()
    .orElseThrow()!!
```

If It throws some exceptions, I may not here to ask for some bits of help from you guys. 
Anyway, thank you for take sometime to investigate this issue
