### ISSUE TITLE
Major Performance Degradation from 3.4.1 to 3.4.7 with groupBy and take(Duration) with flatMap

### ISSUE THREAD

**Issue by Sage-Pierce** [reactor/reactor-core#2730]
I have noticed a major performance degradation in a use case I have with `groupBy` followed by `take` on each group and flat mapping them.

Note that I think this issue _may_ be related to my issue from #2352, and I am using very similar test/sample code to show this issue.

Code:
```java
    @Test
    public void test() throws Exception {
        AtomicLong upstream = new AtomicLong(0L);
        AtomicLong downstream = new AtomicLong(0L);
        CountDownLatch latch = new CountDownLatch(1);

        Scheduler scheduler = Schedulers.single(Schedulers.boundedElastic());

        Flux.fromStream(Stream.iterate(0L, (last) -> (long) (Math.random() * 4096)))
            .flatMap(number -> Flux.concat(
                Mono.just(number),
                Mono.just(number).delayElement(Duration.ofMillis((int) (Math.random() * 2000)))),
                4096)
            .take(Duration.ofSeconds(30L))
            .doOnNext(next -> upstream.incrementAndGet())
            .publishOn(scheduler)
            .groupBy(Function.identity())
            .flatMap(groupFlux -> groupFlux.take(Duration.ofSeconds(1L), scheduler)
                .take(2)
                .collectList(), 16384)
            .map(Collection::size)
            .subscribe(downstream::addAndGet, System.err::println, latch::countDown);

        latch.await();
        System.out.println("Number emitted: " + downstream.get());
        assertEquals(upstream.get(), downstream.get());
    }
```

When run with reactor-core 3.4.1, this test passes and emits/processes on the order of 100,000s of events on my local machine. With versions 3.4.2 through 3.4.5, it flat-out **hangs**. With versions 3.4.6 through 3.4.7, it doesn't hang, but only processes on the order of 1,000s of events.

It _looks_ like changes from #2450 might be causing the hang in versions 3.4.2 through 3.4.5

I _think_ that changes from #2681 might have fixed the hanging, but now left with massive degradation in performance in comparison to 3.4.1

## Expected Behavior
There should be no noticeable performance difference from 3.4.1 to 3.4.6+

## Actual Behavior
Two orders of magnitude reduction in processing speed.

## Steps to Reproduce
See code above in summary

## Possible Solution
I _think_ there is an issue in `groupBy` with number of active groups, but that's only a best guess so far.

## Your Environment
* Reactor version(s) used: 3.4.7
* JVM version (`java -version`): 1.8_172
* OS and version (eg `uname -a`): Mac OS Catalina

**Comment by Sage-Pierce** [comment]
After digging in more, it appears to be the case that after a bit of time, there is only ever one active group/`UnicastGroupedFlux` at a time.

FYI @simonbasle @OlegDokuka as you both are probably more advanced in the code flow here than I am

**Comment by simonbasle** [comment]
> After digging in more, it appears to be the case that after a bit of time, there is only ever one active group/`UnicastGroupedFlux` at a time.

if you are debugging and inspecting the value of `GROUP_COUNT`, it is offset by 1 as long as the upstream is active / connected to. ie if there are 0 groups active but the upstream is not completed nor cancelled, that counter would be at 1. It is incremented each time an inner group is started, and decremented back when said group is cancelled (or completes because source completed). It can only reach zero if either the upstream completes or the downstream cancels the whole flow while no active inner groups are open.

**Comment by Sage-Pierce** [comment]
Sorry, should have been more clear: Yes, I was observing the group count, and it consistently gets to 1 while running the example code (versions 3.4.6+) and once it gets in to that state, it only ever oscillates between 1 and 2, hence my observation that there's only one active group at a time.

When run with 3.4.1, the group count stabilizes around 12 or so on my local box

**Comment by simonbasle** [comment]
the replenishing in #2681 is done as `s.request(1)`. this is suspiciously aligned with the fact that you observe only one active group.

by using `s.request(Operators.unboundedOrPrefetch(prefetch))`, it should bump the performance back to what was observed in 3.4.1 🎉 

one thing though: keep in mind your repro case is a worst-case scenario as it produces as many groups as there are incoming values...

**Comment by Sage-Pierce** [comment]
Wahoo 🥳  I'd had a feeling it had something to do with that replenishing of `s.request(1)`, but couldn't quite put together that it should have been the prefetch. It seems to make sense that the prefetch should rather be used if/when the last group is canceled. However, this is all at the very edge of my knowledge of the inner workings of Reactor 😅 

I do wonder though: Is it correct to use `prefetch` rather than some function of `prefetch` and `requested`? Couldn't `requested` (I believe representing number of outstanding group requests) be less than `prefetch`? Or maybe I'm missing the math that says this isn't a problem or can't happen?

**Comment by simonbasle** [comment]
prefetching can be conceptualized as requesting more from upstream than downstream itself requested, so no this shouldn't be a problem.
