### ISSUE TITLE
Grafana dashboard for Reactor metrics

### ISSUE THREAD

**Issue by patpatpat123** [reactor/reactor-core#2731]
Hello Reactor Team,

First post, so first of all, thank you for this incredible project.

Once the project with this line of code: ```Schedulers.enableMetrics();```, we can see out of the box many useful metrics.
This is already very cool by itself.

The metrics are:

```
executor_active_threads

executor_completed_tasks_total
executor_queued_tasks
executor_queue_remaining_tasks

executor_pool_core_threads
executor_pool_max_threads
executor_pool_size_threads

executor_scheduled_once_total
executor_scheduled_repetitively_total

executor_seconds_max
executor_idle_seconds_max

```

And it is very well divided by **parallel** vs **boundedElastic**, which is also well explain by https://projectreactor.io/docs/core/release/reference/#schedulers

Those metrics are currently a bit overwhelming to understand, and instead of not knowing what to do with them, can Reactor Team provide a guidance Grafana dashboard please?

Many open source project with metrics will propose some kind of default dashboard.

Some sort of Grafana dashboard, where those metrics are represented by graphs and dashboards will definitely help.

Thank you

**Comment by simonbasle** [comment]
hi @patpatpat123, thanks for the kind words!

there is actually a demo project that has Grafana dashboard definitions: https://github.com/reactor/reactor-monitoring-demo

hope this helps 👍 

(I'm labelling as _declined_ but that's just to keep a status label on closed issues)

**Comment by patpatpat123** [comment]
Many thanks
