### ISSUE TITLE
subscribeOn does not work with delayElements (but publishOn does)

### ISSUE THREAD

**Issue by hyhugh** [reactor/reactor-core#2739]
```java
Mono.just(1)
                .repeat()
                .delayElements(Duration.ofSeconds(1))
                // this line should be invoked by the parallel scheduler due to the delayElements
                .doOnEach(s -> System.out.println(Thread.currentThread().getName()))
                .subscribeOn(Schedulers.boundedElastic())
                // expect this to be running on boundedElastic scheduler
                .subscribe(
                        s -> System.out.println(Thread.currentThread().getName())
                );
```

## Expected Behavior

The lambda in `subscribe` runs on `boundedElastic` pool.

## Actual Behavior

it runs on `parallel` scheduler (which is used by the `delayElements`)

## Possible Solution

A `publishOn` here does work tho. If I replace the `subscribeOn` with a `publishOn` the lambda that is passed into `subscribe` will then execute on the `boundedElastic` scheduler as I specified.

## Your Environment

* Reactor version(s) used:  3.4.7
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`):  openjdk 11.0.11 2021-04-20
* OS and version (eg `uname -a`): archlinux on WSL2, `Linux desktop 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 GNU/Linux`

**Comment by simonbasle** [comment]
`delayElements`, like all operators that deal with time, must operate on a scheduler. by default it picks `Schedulers.parallel()`. You can customize that by passing your `Scheduler` of choice.

**Comment by simonbasle** [comment]
the path of execution of a reactive chain goes from bottom all the way to the top at first, during the subscription phase. It is during this phase that `subscribeOn` switches threads, so operators upstream of it (that is `just`, `repeat`, `delayElements` and `doOnEach`) now subscribe in a thread from the boundedElastic `Scheduler`.

Then data starts flowing through the pipeline (`onNext` event(s)).

`just` and `repeat` don't switch threads during this phase, but `delayElements` does.

From there on, all downstream-directed events (`onNext`, `onComplete`, `onError`) run on the default `Scheduler` picked by `delayElements` (which must like all time-related operators pick a `Scheduler` without the ability to make any assumption about the current one).

That includes the `onNext` `Consumer` of the lambda-based `subscribe` call, so everything is working as intended. Indeed, adding a `publishOn` downstream of `delayElements` is the way to go if you want to change that. Or alternatively, you can specify a `Scheduler` to use in `delayElements` directly.
