### ISSUE TITLE
Metrics executor_* disappeared for Spring Cloud Jubilee + SpringBoot 2.6.0-M1

### ISSUE THREAD

**Issue by patpatpat123** [reactor/reactor-core#2752]
Hello Reactor Team,

Just wanted to highlight an issue observed after an upgrade.
The app was Ilford + SpringBoot 2.5.x and working fine.
Out of the box, it has great metrics, with ```Schedulers.enableMetrics();``` such as 

```
executor_active_threads

executor_completed_tasks_total
executor_queued_tasks
executor_queue_remaining_tasks

executor_pool_core_threads
executor_pool_max_threads
executor_pool_size_threads

executor_scheduled_once_total
executor_scheduled_repetitively_total

executor_seconds_max
executor_idle_seconds_max
```

No code change, just version bump up to Jubilee + SpringBoot 2.6.0-M1.
Now: some metrics are still here, but with value 0.
Some metrics disappeared entirely.

This one is still working with correct value:

```
# HELP executor_queue_remaining_tasks The number of additional elements that this queue can ideally accept without blocking
# TYPE executor_queue_remaining_tasks gauge
executor_queue_remaining_tasks{name="application",}
```

Those are now all flat 0
```
# HELP executor_active_threads The approximate number of threads that are actively executing tasks
# TYPE executor_active_threads gauge
executor_active_threads{name="application",} 0.0
# HELP executor_completed_tasks_total The approximate total number of tasks that have completed execution
# TYPE executor_completed_tasks_total counter
executor_completed_tasks_total{name="application",} 0.0
# HELP executor_queued_tasks The approximate number of tasks that are queued for execution
# TYPE executor_queued_tasks gauge
executor_queued_tasks{name="application",} 0.0
# HELP executor_pool_size_threads The current number of threads in the pool
# TYPE executor_pool_size_threads gauge
executor_pool_size_threads{name="application",} 0.0
# HELP executor_seconds  
# TYPE executor_seconds summary
executor_seconds_count{name="application",} 0.0
executor_seconds_sum{name="application",} 0.0
# HELP executor_seconds_max  
# TYPE executor_seconds_max gauge
executor_seconds_max{name="application",} 0.0
# HELP executor_idle_seconds  
# TYPE executor_idle_seconds summary
executor_idle_seconds_count{name="application",} 0.0
executor_idle_seconds_sum{name="application",} 0.0
# HELP executor_idle_seconds_max  
# TYPE executor_idle_seconds_max gauge
executor_idle_seconds_max{name="application",} 0.0
```

Could you please help triage if this is an issue and how to fix it please?
Thank you

**Comment by simonbasle** [comment]
Nothing has recently changed in core metrics. These metrics are generated by wrapping the underlying `ExecutorService`s used by different `Schedulers` with a Micrometer-native decorator.

Maybe the switch to Jubilee / Boot 2.6 caused the Micrometer dependency and effective version to change?

**Comment by patpatpat123** [comment]
Hello Simon,

Indeed, the Jubilee + SpringBoot 2.6 bump had Micrometer bumped to 1.8.0-M1 as well.
Do you believe this is a Micrometer, or SpringBoot related issue, and not a ReactorCore one? 
In which I will be happy to close the issue here and follow up with them.

Thank you for looking at this.

**Comment by simonbasle** [comment]
I would follow up with Micrometer first.
Reactor-Core assumes that Micrometer is from the 1.7 line, so there might be an incompatible change in 1.8 that explains what you observe.

**Comment by patpatpat123** [comment]
Got it, thanks!

**Comment by simonbasle** [comment]
actually @patpatpat123 reactor references Micrometer 1.3.0 as its baseline.
