### ISSUE TITLE
spring boot reactor not logging request id contextually

### ISSUE THREAD

**Issue by fatagun** [reactor/reactor-core#2753]
I would like to propogate `requestId` through streams. Below is my end point. 

```
    @PostMapping(value = "/graphql")
    public Mono<ResponseEntity<ApplicationResponse>> execute(@RequestBody GraphQLRequestBody graphQLRequestBody) {

        final String requestId = UUID.randomUUID().toString().toUpperCase().replace("-", "");

        return Mono.fromCompletionStage(graphql.executeAsync(ExecutionInput.newExecutionInput()
                .query(graphQLRequestBody.getQuery())
                .operationName(graphQLRequestBody.getOperationName())
                .build()))
                .map(ExecutionResult::toSpecification)
                .map(stringObjectMap -> new ResponseEntity<>(new ApplicationResponse(requestId,
                         ((Map<String, Object>) stringObjectMap.get("data"))), HttpStatus.OK))
                .doOnEach(logOnNext(
                        res -> logger.info("processing.."))
                )
                .contextWrite(ctx-> ctx.put("CONTEXT_KEY", requestId));
    }
```

I am using `logOnNext` as documented [here](https://projectreactor.io/docs/core/release/reference/#faq.mdc). 

```
  public static <T> Consumer<Signal<T>> logOnNext(Consumer<T> logStatement) {
        return signal -> {
            if (!signal.isOnNext()) return;
            Optional<String> toPutInMdc = signal.getContext().getOrEmpty("CONTEXT_KEY");

            toPutInMdc.ifPresentOrElse(tpim -> {
                        org.slf4j.MDC.put("CONTEXT_KEY", tpim);
                        logStatement.accept(signal.get());
                    },
                    () -> logStatement.accept(signal.get()));
        };
    }
```

on subsequent classes such as `Service` or `Repository` classes. I am unable to capture `requestId`.
However, it does capture for `execute` method of the stack. 

Why is it not capturing context? I am writing to context. Below is a sample of `Service` class method.

```
    @Override
    public Mono<ClusterIdAndClientNameDTO> getClusterIdFromClientId(final String clientId) {
        
        return clusterMetadataRepository.getClusterIdFromClientId(clientId)
                                         // HERE ; context is empty. unable to find request id. 
                                        .doOnEach(logOnNext(res -> log.info("processing.."))
        );
    }
```

can you please elaborate?

**Comment by simonbasle** [comment]
`Context` propagation isn't propagation per-se, but rather the ability for an operator up the chain to peek to its downstream operator and see if it defines `Context` entries. So in the case of your `execute` endpoint, for example, the first `map` would ask the context of the second `map`, which would delegate down to `doOnEach`, which would peek at `contextWrite` which returns a `Context` augmented with the `CONTEXT_KEY`...

From that, we see that `doOnEach` sees the `Context` written by `contextWrite`.

What I fail to see is how `getClusterIdFromClient` `Mono` is connected to that reactive chain in `execute`?

If it is not connected and made part of the chain in a reactive way (eg. via a `flatMap`), then it cannot "peek" at the right `Context` and cannot see the effect of `contextWrite`.
