### ISSUE TITLE
IllegalStateException: Too many subscribers for FluxMergeSequential on item

### ISSUE THREAD

**Issue by rickle-msft** [reactor/reactor-core#2754]
We have a customer who is occasionally hitting the exception in the title. This is coming from FluxMergeSequential:MergeSequentialMain:onNext when the subscribers queue cannot accept the item offered. From my understanding of the code, it seems it should be impossible to hit this exception as the queue is configured to be max of prefetch and maxConcurrency and only maxConcurrency number of items are requested from the upstream subscription at a time. Hence, I believe the queue should never be able to overflow. The fact that it is an IllegalStateException further leads me to believe this code path is not intended to be executed. 

## Expected Behavior
No exception should be thrown

## Actual Behavior
An exception is thrown 

## Steps to Reproduce

```java
@Test
void reproCase() {
        Flux.range(0, 256)
            .flatMapSequential(i -> {
                if (i == 0) {
                            Thread.sleep(20000);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                        sink.success(0);
                    }).subscribeOn(Schedulers.parallel()));
                }
                return Flux.just(i);
            })
        .doOnNext(System.out::println)
        .blockLast();
}
```

The only way I have been able to observe this behavior is breaking in the above mentioned method when the queue is full and using the debugger to add an extra item to get it to over flow. I understand this is a rather artificial reproduction, however, I am first hoping to understand whether this is even a legitimate code path that we should be handling, if it indicates some sort of poor backpressure management in our code, or if it may indicate a bug in reactor. 

## Your Environment
* Reactor version(s) used: 3.4.6
* JVM version (`java -version`): JDK 11.0.6
* OS and version (eg `uname -a`): Windows 10 Enterprise 21H1

Thank you for your help!

**Comment by simonbasle** [comment]
from the git commit that introduced this exception, this is indeed intended as a safeguard and not a normal thing to happen. do you know what the upstream looks like? it is possible a custom `Publisher` is used that doesn't respect the backpressure and overflows the `flatMapSequential` with at least one more item than requested?

the request pattern is indeed `maxConcurrency` (the size of the queue) then in the drain loop it requests one more source element to flatmap from once an inner `Flux` is done.

**Comment by rickle-msft** [comment]
@simonbasle Thank you for your response and apologies for the delay. For some reason I was expecting an email on the issue and wasn't checking here for an update. 

There is an internal implementation of a `StorageBlockingSink`, which is a type we have that contains an instance of `Sinks.Many` initialized as `Sinks.many().unicast().onBackpressureBuffer(writeLimitQueue)` 
`writeLimitQueue` in this case is effectively an instance of `LinkedBlockingQueue` that has had its `offer(T)` method overridden to call `put(T)` instead to block more directly. The explanation of this is given in line as:

> The Reactor implementation of Sinks(UnicastProcessor).tryEmitNext (see usage below) makes a call to
        queue.offer(). The desired functionality of tryEmitNext is for it to block on backpressure until there is
        space in the queue. Since this code is called from user thread on BlobOutputStream.write and blocking on that
        API until data can be written is ok, this is the simplest way to get desired behavior. 

We were also seeing some cases where writing to this sink failed. It wasn't clear, though, if this was coming from the overflow mentioned above or some other timeouts due to network latency

**Comment by simonbasle** [comment]
`tryEmitNext` is in no way intended to delegate to a blocking method. It seems you are doing funky things in your custom implementation(s), so if I were you I would look on that side of things.

**Comment by rickle-msft** [comment]
@simonbasle Could you please provide some guidance here or on another channel as to what best practices are? We are happy to update our implementation, but we arrived here after a good amount of research and investigation, so we aren't sure where to move next. I have also posted on the gitter but haven't met much of a response.

**Comment by simonbasle** [comment]
I wonder if the Sink has anything to do with this issue, in the end... There is too little information, even after having taken a look at the azure SDK sources.

Have you been able to precisely identify which of the several usages of `flatMapSequential` was failing?
And what was the concrete `Subscription` passed to said failing flatMapSequential?

By the way, I see a number of usage that follows the `flatMapSequential(mapper, 1, 1)` pattern. I don't think that makes much sense, and it would be more efficient to directly use `concatMap` in these cases (since there is no effective concurrency due to the first `1` parameter).
