### ISSUE TITLE
While loop implementation

### ISSUE THREAD

**Issue by xdrsynapse** [reactor/reactor-core#2759]
## Motivation
We're implementing a state machine flow with scripting, and in one of our controllers we need a Loop Controller then when meets a condition run a list of subcontrollers.

```
public Publisher execute(Blackboard blackboard) {
        return Mono.defer(() -> {
            boolean match = condition.match(blackboard);
            if(!match) {
                return Mono.empty();
            }

            return Flux.fromIterable(controllers)
                    .concatMap(controller -> controller.execute(blackboard))
                    .repeat(() -> condition.match(blackboard))
                    .then();
        });
    }
```

The code above is what're using, but it's not very 'clean', since we're repeating condition.match twice.

## Desired solution
A proper implementation or a guide of how it would be best to do it with reactor at the moment.

**Comment by simonbasle** [comment]
There have been internal talks of doing a state-machine operator a while ago, but it was never formalized. We would need more in detail requirements of what it would look like in terms of operator signature and behavior, in your opinion.

Some such operator exist in the RxJava ecosystem of extra libraries (not the vanilla RxJava library though), like https://github.com/davidmoten/rxjava2-extras#statemachine.

There are caveats, quoting from [this stackoverflow answer](https://stackoverflow.com/questions/46065133/state-machine-using-rxjava):

> While it is possible to implement a state machine in RxJava, it gets very ugly, very quickly. You can use the switchMap() operator to select some of the branching paths, and you can use several other operators to branch and merge.
> 
> Most of the issue is that state machine transitions tend to look more like go to than structured programming, and they tend not to resemble functional programming at all.

**Comment by xdrsynapse** [comment]
Thanks for your fast answer @simonbasle !

I imagine that it could look like: 
```
    @Override
    public Publisher<Object> execute(Blackboard blackboard) {
        return Mono.doWhile(condition.match(blackboard))
                .concatMap(controller -> controller.execute(blackboard));
    }
```
Internally it could have a generator like FluxRange (tecnichally it's a iteration loop).

It's true that the code can get very ugly quickly, but maybe a very simple StateMachine could work since we're working with WebFlux to guide a small game flow with simple commands.

**Comment by simonbasle** [comment]
we don't think we'll implement this in the near future, unless a third party wants to work on designing and implementing this.
