### ISSUE TITLE
Execution sometimes stalls with uncaught exception when stream provided to Flux.fromStream throws

### ISSUE THREAD

**Issue by joshng** [reactor/reactor-core#2761]
When constructing a test to exercise a custom Subscriber's error-handling logic, I encountered this scenario wherein the exception thrown by my source-stream is __sometimes__ (but not always, apparently depending on the concurrent execution-order) handled incorrectly. When this happens, the error is treated as an "uncaught exception" (ie, logged and dropped) by reactor-core, rather than being pushed through the pipeline via the expected `onError` callbacks. Afterwards, the stream hangs, presumably do to the `request` capacity apparently being dropped.

## Expected Behavior
When an exception is thrown by application-code in the context of processing an event-stream, the exception should be surfaced back to the appropriate application-facing callbacks, and induce the stream to be terminated.

## Actual Behavior
The exception was conveyed to the `Schedulers` uncaught-exception facility, without correctly terminating the stream.

## Steps to Reproduce
I suspect the minimal conditions for reproducing this involve an iterable/stream that throws an exception in the context of fulfilling an asynchronously-issued `request`. Here's a small test to illustrate:

```java
@Test
void reproCase() {
     CountDownLatch thrown = new CountDownLatch(1);
    Iterator<Integer> throwingIterator = new Iterator<>() {
      int count = 0;

      @Override
      public boolean hasNext() {
        return count < 3;
      }

      @Override
      public Integer next() {
        if (++count > 2) {
          thrown.countDown();
          throw new RuntimeException("boom");
        } else {
          return count;
        }
      }
    };


    CompletableFuture<Throwable> error = new CompletableFuture<>();
    CountDownLatch terminated = new CountDownLatch(1);
    Subscriber<Integer> simpleAsyncSubscriber = new BaseSubscriber<>() {
      @Override
      protected void hookOnSubscribe(Subscription subscription) {
        request(1);
      }

      @Override
      protected void hookOnNext(Integer value) {
        // proceed on a different thread
        CompletableFuture.runAsync(() -> request(1));
      }

      @Override
      protected void hookOnError(Throwable throwable) {
        error.complete(throwable); // expected to be called, but isn't
      }

      @Override
      protected void hookOnComplete() {
        error.complete(null); // not expected to happen
      }
    };

    Flux.fromStream(StreamSupport.stream(Spliterators.spliteratorUnknownSize(throwingIterator, 0), false))
            .publishOn(Schedulers.boundedElastic())
            .doOnTerminate(terminated::countDown)
            .subscribe(simpleAsyncSubscriber);

    assertThat(thrown.await(3, TimeUnit.SECONDS)).isTrue(); // succeeds

    ////////// fails: ////////////
    assertWithMessage("Pipeline should terminate").that(terminated.await(2, TimeUnit.SECONDS)).isTrue();

    Throwable caught = assertDoesNotThrow(() -> error.get(2, TimeUnit.SECONDS));
    assertThat(caught).isNotNull();
    assertWithMessage("Error should flow downstream").that(caught).hasMessageThat().isEqualTo("boom");
}
```

## Possible Solution

By my reading, the issue appears to arise due to a lack of appropriate error-handling around one of these lines:
1. https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/publisher/FluxPublishOn.java#L376
1. https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/publisher/FluxIterable.java#L408

Here's the stacktrace logged by `Schedulers.defaultUncaughtException`:

```
2021/09/02 12:19:18.580 ERROR (    boundedElastic-1) [ore.scheduler.Schedulers] - Scheduler worker in group main failed with an uncaught exception
java.lang.RuntimeException: boom
	at PipedStreamSubscriberTest$1.next(PipedStreamSubscriberTest.java:93)
	at PipedStreamSubscriberTest$1.next(PipedStreamSubscriberTest.java:81)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at reactor.core.publisher.FluxIterable$IterableSubscription.isEmpty(FluxIterable.java:408)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runSync(FluxPublishOn.java:376)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:524)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
```
## Environment
* Reactor version(s) used: 3.4.9
* JVM version (`java -version`): openjdk version "11.0.11" 2021-04-20
* OS and version (eg `uname -a`): Darwin Kernel Version 19.6.0

**Comment by simonbasle** [comment]
yes, I think the best way to fix this is to enclose the `isEmpty()` call in `FluxPublishOn` in a try/catch block, similar to other usages of the queue in the `runXxx` methods.

**Comment by simonbasle** [comment]
This most probably also affects 3.3, so `3.3.x` branch would be a good target branch for fixing this.

**Comment by simonbasle** [comment]
actually, isn't there a fundamental issue in the way your custom `Iterator` is implemented? If `hasNext()` returns `true`, should the `next()` method be allowed to throw at all @joshng?

**Comment by joshng** [comment]
Hmm, we might hope that `next` would never throw an exception if `hasNext` returns `true`, but I'd recommend that a robust execution framework shouldn't rely on this being a safe assumption in all cases. While the javadoc for `hasNext` does seem to imply this as a contract (_"returns true if next would return an element rather than throwing an exception"_), I can point to a clear violation in the JDK libraries: the `next` method for many JDK-provided collection iterators may throw `ConcurrentModificationException` under certain circumstances:

```java
    var list = new ArrayList<String>();
    list.add("abc");
    Iterator<String> it = list.iterator();
    it.hasNext();     // true
    list.remove(0);
    it.next();        // throws ConcurrentModificationException
```

One might argue that this is misbehaving application-code -- I'm sure it's documented somewhere that the underlying collection must not be modified while the iterator is in use -- but the fact remains that this exception violates that `Iterator.next` documentation, and naive developers certainly make this sort of mistake in multithreaded contexts, where such issues may not be readily exposed by straightforward testing. In such an event, I'd anticipate that the maintainer would appreciate having the exception surfaced via `onError`, rather than have it cause the application to quietly stall out.

Here's another example that violates this assumption (closer to my own situation), involving an iterator that yields values from an I/O stream, from the popular avro serialization library: https://github.com/apache/avro/blob/328c539afc77da347ec52be1e112a6a7c371143b/lang/java/avro/src/main/java/org/apache/avro/file/DataFileStream.java#L238

In practice, I think that the supposed Iterator "contract" emerges as being pretty unnatural when implementing custom `Iterators`, because it demands complex state-management to compute and cache each element in `hasNext`, but **only once** for each call to `next`. (I've often used guava's `AbstractIterator` to handle this complexity, but I suspect many straightforward Iterator implementations wouldn't do this "correctly". It's just so much simpler to merely check protocol state in `hasNext`, and then perform the real fallible work in `next` to yield each successive element.)

As such, I don't think we should assume that every application will behave as expected. Indeed, I suspect that a more accurate interpretation of the real-world `Iterator.hasNext` contract would be:
> _"returns true if next would return an element rather than throwing **NoSuchElementException**"_

(ie: `next` might throw just about any RuntimeException; buyer beware!)

Finally, more generally, I think it's best to arrange for library/framework code logic to _never_ assume that any code provided by the consuming application will run without exceptions. The framework should defend against application bugs, and surface such issues in a uniformly predictable manner that lets the application apply central error-handling policies. Otherwise, it's easy to imagine a quiet stall-out that causes subtle production issues in hard-to-anticipate edge cases.

**Comment by simonbasle** [comment]
fair enough.

Note that if you actually work with an `Iterator`, I'd recommend using `Flux.fromIterable` instead.

With streams, we convert their `Spliterator` to an `Iterator` anyway, which means here we end up with `iteratorWrapper(spliteratorWrapper(iterator))`.
Furthermore, by converting the original `Iterator` by going through the hoops of creating a `spliteratorUnknowSize`, the Spliterator wrapper ends up peeking ahead in the underlying `Iterator` via `#next()` rather than `hasNext()`, even for the outer `Iterator`'s `#hasNext()` method.

**Comment by simonbasle** [comment]
Can we just make `FluxIterable`'s `isEmpty` more defensive against the `Iterator`'s `hasNext()` method call?

`isEmpty()` will be used during fusion, driving calls to `poll()`. Operators know to deal with a throwing `poll()`, but assume `isEmpty()` to be a safe call.

If `FluxIterable#isEmpty()` is changed to `return false` when the `hasNext()` throws, then most operators would then call `poll()` and we can probably assume that leads to a `next()` call that would also `throw`, letting the caller turn that exception into an `onError` signal.

What do you think?

**Comment by simonbasle** [comment]
having tested the above with the provided snippet, it isn't entirely satisfactory since the original exception gets replaced by a `NoSuchElementException` when subsequently calling `next()` from the poll()...

I have submitted a PR that "simply" stores the exception when caught from within `isEmpty`, to be re-thrown in `poll()`. That's a bit of a shame because it only caters to that corner case in fusion, but eh 🤷

**Comment by OlegDokuka** [comment]
I think there is a fundamental problem here. 
`hasNext` never should throw an exception. If it is throws - it is an implementation issue. And I'm not sure it is a good idea to make a framework that ensures that everything that does not throw an exception by contract may throw it.

In this particular scenario, we deal with a Stream wrapping iterator transformed to the iterator, and an exception is flowing from the Stream API, which is absolutely unexpected behavior. Not sure, this is a JDK bug but it's definitely not something event expected by JDK Stream implementation. 

> the next method for many JDK-provided collection iterators may throw ConcurrentModificationException

This is true, and we handle that scenario by wrapping our `poll` method with a try-catch block. However, I'm afraid that `hasNext` throwing an exception is not something well presented in any JDK library and we can all agree that it is uncommon to see try-catch around `hasNext` call.

I suggest that in this particular example, the fundamental problem is either on the JDK level or at the implementation level and even though we can provide a workaround this workaround is not something that should be in a framework working with an iterator by its defined contract
