### ISSUE TITLE
onErrorDropped for Flux.switchOnFirst with two flatMaps

### ISSUE THREAD

**Issue by jGleitz** [reactor/reactor-core#2765]
We are observing dropped errors in our application under certain circumstances. The error seems to be related to having two `flatMap`s inside a `switchOnFirst` operator.

## Expected Behavior

We can transform the Flux passed to the `transformer` of `switchOnFirst` using multiple `flatMap`s and `onErrorDropped` will not be called.

## Actual Behavior

If using more than one `flatMap`, and the second one fails, `onErrorDropped` will be called.

The test case below fails because `onErrorDropped` is called with a `CancellationException`:

```
expected: <null> but was: <java.util.concurrent.CancellationException: FluxSwitchOnFirst has already been cancelled>
Expected :null
Actual   :java.util.concurrent.CancellationException: FluxSwitchOnFirst has already been cancelled
```

## Steps to Reproduce

```java
class SwitchOnFirstFlatMapTest {
    @Test
    void switchOnFirstWithInnerFlatMap() {
        AtomicReference<Throwable> droppedError = new AtomicReference<>();
        Hooks.onErrorDropped(droppedError::set);

        Flux<Integer> switchOnFirstDoubleFlatMap = Flux.just(1, 2, 3)
            .switchOnFirst((signal, innerFlux) ->
                signal.hasValue()
                    ? innerFlux
                        .flatMap(checkAtLeast(signal.get())) // remove this line and everything works
                        .flatMap(value -> error(new IllegalArgumentException("this fails!")))
                    : innerFlux
            );

        StepVerifier.create(switchOnFirstDoubleFlatMap)
            .verifyError(IllegalArgumentException.class);

        assertNull(droppedError.get());
    }

    private static Function<Integer, Mono<Integer>> checkAtLeast(int minimum) {
        return input ->
            input < minimum
                ? error(new IllegalArgumentException("too small!"))
                : just(minimum);
    }
}
```

Notice that if the `.flatMap(checkAtLeast(signal.get()))` is removed, `onErrorDropped` will not be called!

## Possible Solution

I lack the insight to understand the problem. While debugging, I noticed that `AbstractSwitchOnFirstMain` calls `onError` with a `CancellationException` twice: First [in `sendFirst`](https://github.com/reactor/reactor-core/blob/1674372fff1cdaa03e9747eb3570ce557086175d/reactor-core/src/main/java/reactor/core/publisher/FluxSwitchOnFirst.java#L691), and later [at the end of `subscribe`](https://github.com/reactor/reactor-core/blob/1674372fff1cdaa03e9747eb3570ce557086175d/reactor-core/src/main/java/reactor/core/publisher/FluxSwitchOnFirst.java#L676). The second time the `CancellationException` is sent, the `flatMap` is already `done` because of the first `CancellationException`, and hence calls `onErrorDropped`.

## Your Environment

* Reactor version(s) used: 3.4.10-SNAPSHOT
* Other relevant libraries versions (eg. `netty`, ...): none
* JVM version (`java -version`): `openjdk version "1.8.0_292"`
* OS and version (eg `uname -a`): `Linux Lovelace 5.11.0-31-generic #33-Ubuntu SMP Wed Aug 11 13:19:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by simonbasle** [comment]
Thanks for the report @jGleitz, we were able to fix it right on time for the next release 👍
