### ISSUE TITLE
Cleanup handler is not subscribed/called if Mono/FluxUsingWhen is cancelled before resource is emitted

### ISSUE THREAD

**Issue by hyhugh** [reactor/reactor-core#2769]
If a `*.usingWhen` is cancelled before resource publisher emits anything, the cleanup handler then will not be called, but the resource publisher will still be called even after cancellation.

## Expected Behavior

either the resource publisher is not called, or the cleanup handler is called.

## Steps to Reproduce

```java
public void testUsingWhen() {
        // sync on this just to make sure print + opeartion are groupped together
        Integer i = 1;
        var sub = Flux.usingWhen(Mono.<Integer>create(sink -> {
            synchronized (i) {
                System.out.println("Emitting");
                sink.success(1);
                System.out.println("Emitted");
            }
        }), s -> Flux.just(s), s -> {
            System.out.println("Cleaning Up");
            return Mono.empty();
        }).subscribeOn(Schedulers.boundedElastic()).subscribe();
        synchronized (i) {
            System.out.println("disposing");
            sub.dispose();
            System.out.println("disposed");
        }
    }
```

and the output (sometimes depending on which runs first) is 
```
disposing
disposed
Emitting
Emitted
```

This indicates the resource publisher is called after `dispose` but the cleanup handler is not called as not `Cleaning Up` is printed. If we emit anything that needs a cleanup this behaviour can cause resource leaks. 

## Your Environment

* Reactor version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`):
* OS and version (eg `uname -a`):

**Comment by simonbasle** [comment]
the `usingWhen` never sees the value, so since its cleanup support is based on applying a `Function` to the value, it has nothing to do.

that's because the inner `Flux.create` DOES get cancelled before the emission is performed. 

unfortunately, the sink's `success(T)` method doesn't provide feedback.

internally, `Mono.create`'s `MonoSink` detects the cancellation and deals with it by passing the value to `Hooks.onNextDropped`.

You can see it by adding `Hooks.onNextDropped(System.err::println);` at the beginning of the test...

I assume this is an oversimplification aimed at modelling your actual code? What is the actual source used in `usingWhen`? If it is a `Flux.create`, can you tell us more about the adapted source's characteristics?

**Comment by hyhugh** [comment]
Hi Simon, thanks for your reply!

What I'm trying to achieve here is similar to the code recommended here https://stackoverflow.com/a/68546093. We wanted to initialise a connection to database (but not using r2dbc) and clean up the connection properly after some operations/stream of data. 

We initially used the pattern below
```
Mono.create(sink -> {
            // initialise connection to db (which needs cleanup)
            // sink.success(cxn); // if success
            // sink.error(e) // if err
        }).flatMapMany(cxn -> {
            // grab data using cxn
            return Flux.just(1) // return some data
                .doFinally(s -> {/*cleanup*/});
        });
```
Then we realise if the flux is cancelled immediately after subscribing, the `flatMapMany` part will not be executed at all so the connection is never closed.

then after some googling, I found some recommending using `Flux.usingWhen` to handle resource cleanup as the link above, then I found the new implementation has the very same issue.

Sorry for being a noob in the reactive programming world, but what is the recommended way to handle objects that need cleanup when using `Flux`? should I lift the connection variable to some local storage and then use `doFinally`  on the Mono that initialises the connection to properly close a connection? Or is using `onNextDropped` hook the recommended way to cleanup resources? (I do realise it's mentioned in the reference guide)

**Comment by simonbasle** [comment]
in the present case, the most fireproof way of dealing with that would be to register a `Hooks.onErrorDropped` hook and add a `.doOnDiscard` operator to the chain.

I might need to consider that `Mono.create` case further, see if _discarding_ is better suited than `onNextDropped` (which is usually reserved for illegal sequence of Reactive Stream events, like `onNext` after an `onComplete/onError`).

if that is the case, then ultimately the `onErrorDropped` hook would become unnecessary and the `.doOnDiscard` would suffice.

**Comment by simonbasle** [comment]
I'll at least enhance the `Mono.create` sink so that if a `success(T)` call is made after a cancellation, the value will be passed to `doOnDiscard` hooks rather than `onErrorDropped`.

**Comment by hyhugh** [comment]
Thanks heaps Simon!
