### ISSUE TITLE
Cannot create a replay sink with zero size

### ISSUE THREAD

**Issue by osi** [reactor/reactor-core#2772]
## Expected Behavior

Can create a sink using 
```
Sinks.many().replay().limit(0)
```
To get a sink that:
 - Does not store any values for late subscribers
 - Allows error-free publication when no subscribers
 - Allows subscribers to come-and-go

## Actual Behavior

Fails with
```
java.lang.IllegalArgumentException: historySize must be > 0
```

This is caused by #2741 , specifically,

> This is not entirely ideal, but we're making the bet here that nobody actually uses `historySize == 0` in the `Sinks` side of things, since it is a younger API.

I'm using it 😀

**Comment by osi** [comment]
A workaround appears to be to use
```
Sinks.many().replay().limit(Duration.ZERO)
```

**Comment by simonbasle** [comment]
@osi do you feel the workaround could be the recommended way of achieving this ?
`Duration.ZERO` is a bit more logical-sounding than `limit=0`, maybe?

Otherwise we can look into reintroducing support for `limit = 0`.

cc @OlegDokuka

**Comment by osi** [comment]
I'm fine with the workaround being the recommended way of achieving this. 

More explicit support for this would be nice, but also not required.

(I use this construct in some of my test code when simulating external services)

**Comment by simonbasle** [comment]
so as a first remediation, we could just document this workaround in the javadoc?

if more production-like usecases surface later on we can consider adding a sink implementation that re-enables each usecase.

**Comment by osi** [comment]
Yes, I think documentation sufficient for now, and javadoc feels like an appropriate place for it.
