### ISSUE TITLE
Use doOnNext multiple times

### ISSUE THREAD

**Issue by Yevhenii-Melnyk** [reactor/reactor-core#278]
I was trying to change a little reactor samples from [here](https://github.com/reactor/reactor-samples/blob/master/src/main/java/org/projectreactor/samples/FluxSamples.java) and I'm a little confused with the behaviour I get.

So first the code looks like this:

	EmitterProcessor<String> stream = EmitterProcessor.<String>create().connect();
	Flux<String> flux = stream
			.doOnNext(s -> System.out.println("1  " + s))
			.doOnNext(s -> System.out.println("2  " + s));
	flux.subscribe();
	stream.onNext("Hello");

This code prints two lines as expected:

	1 Hello
	2 Hello

But if I add an intermediate variable pretending I get it from some method or for readability, the code starts to behave differently.

    EmitterProcessor<String> stream = EmitterProcessor.<String>create().connect();
    Flux<String> flux = stream
            .doOnNext(s -> System.out.println("1 " + s));
    flux.doOnNext(s -> System.out.println("2 " + s));
    flux.subscribe();
    stream.onNext("Hello");

The code above gives only one line of output, that is:

	1 Hello

How is this possible?

**Comment by smaldini** [comment]
The core principle sticks to functional programming and reactive extensions basics, you build a chain that you have to subscribe interest in sequence. Effectively a subscription state materialize when at the very end/right you call subscribe(?options) so in your case you have to 
"doOnNext(s -> xxxx).subscribe(xx)", otherwise its like you have prepared 2 flows to be subscribed and you actually subscribed without any of these preparations.

**Comment by Yevhenii-Melnyk** [comment]
My bad. I see the point now. The flux is unmodifiable itself and produces new instance on each operation.

**Comment by smaldini** [comment]
Exact!

**Comment by smaldini** [comment]
And its not your bad, its our bad, we are working on that, A Reactor tutorial is scheduled for release on InfoQ this week that will help clarify hopefully. Meanwhile don't hesitate to try out the mini tutorial on https://github.com/reactor/lite-rx-api-hands-on or see higher level examples like the last spring data ones (https://spring.io/blog/2016/11/28/going-reactive-with-spring-data) or Spring 5 app https://github.com/bclozel/spring-reactive-university/tree/master/src/main/java/com/example.

**Comment by Yevhenii-Melnyk** [comment]
Thank you for great answers!

**Comment by smaldini** [comment]
NP!
