### ISSUE TITLE
viable alternative to onBackpressureError() in 3.4 or 3.5

### ISSUE THREAD

**Issue by matyasberry** [reactor/reactor-core#2781]
## Motivation

Imagine you have lots of subscribers. Some of them are fast, some slow (especially if connected over the network).
We'd like to keep pushing data to fast subscribers on a best effort basis, but don't want ourselves to be limited by slow subscribers.
Dropping parts of the data to slow subscribers using `Sinks.many().directBestEffort()` is a rather bad choice, as the subscribers  may or may not detect this data-loss and it may create consistency issues for them. In a FAIL_FAST world, we consider it safer to drop the slow subscriber immediately.

Similarly, dropping the fast subscribers just because there is a single slow subscriber is unjustified collateral damage in many cases.

Unfortunately, `onBackpressureError()` is gone and `DirectProcessor` is slated for removal. Moreover, forward looking implementations of the Sink do not offer an easy way to provide our own strategies deciding what to do when encountering slow subscribers.

## Desired solution
1. Provide a comparable alternative to `onBackpressureError()`, or
2. let the user specify a policy, e.g.
`Sinks.many().directBestEffort(BackPressurePolicy policy)` where `BackPressurePolicy` is defined like
```
enum BackPressurePolicy {
   CANCEL_SINK
   DROP_ALL,
   DROP_SINGLE,
   IGNORE
}
```
3. Alternatively, make the `tryEmitNext()` methods overridable.
Some more thought could be given whether emission should be transactionally (all-or-nothing) or indeed best-effort.

**Comment by simonbasle** [comment]
@matyasberry what do you mean `onBackpressureError()` is gone?

**Comment by matyasberry** [comment]
So it seems I misunderstood https://github.com/reactor/reactor-core/pull/2376 since I could not find `Sinks.many().onBackpressureError()`. I have now realized it is on `Sinks.one().onBackpressureError()`.

In any case, we'd like to achieve the behavior described through `Sinks.many()`. 
Or, if it's simpler, it's enough to publish from a single thread to multiple subscribers with the behavior that if any of the subscribers have no demand, we cancel it.

**Comment by simonbasle** [comment]
can you provide an example of code you'd like to migrate? I thought you were talking about `Flux#onBackpressureError()` which could be applied to a `Sinks.many()` wherever it is viewed `asFlux()`.

**Comment by matyasberry** [comment]
```java
public class DroppingPublisher implements CorePublisher<Element> {
  private Many<Fragment> sink = Sinks.unsafe().many().multicast().onDirectBestEffort();
  private Flux<Fragment> subHandler = sink.asFlux();
//...
  
  @Override
  public void subscribe(Subscriber<? super Element> actual) {
    subHandler.subscribe(actual);
  }
  
  @SuppressWarnings({"rawtypes", "unchecked"})
  @Override
  public void subscribe(CoreSubscriber<? super Element> actual) {
    subHandler.subscribe(actual);
  }


  @Override
  public void tryNext(Element element) {
    if (isDisposed()) {
      LOGGER.warn("[tryNext] publisher is disposed, dropping : " + element);
      return;
    }
    // need to be aggressive here and drop subscribers that have no demand
    sink.tryEmitNext(element);
  }
}
```

**Comment by simonbasle** [comment]
I meant, what do you have currently that uses some form of `onBackpressureError()` ?

**Comment by simonbasle** [comment]
Regarding `MultiSubscriber`, I don't think that is the best approach as, as you've discovered, this implies some support from the `Sink`.

You could implement your own `Sink.Many<T>`, but that's not likely a great solution either.

But what you can do is put `Flux#onBackpressureDrop()` behind every subscriber:

```java
Sink.Many<T> mySink = Sinks.many().multicast().onDirectBestEffort();

Disposable sub1 = mySink.asFlux().onBackpressureError().someFastChain().subscribe(...);
Disposable sub2 = mySink.asFlux().onBackpressureError().someSlowChain().subscribe(...);
Disposable sub3 = mySink.asFlux().onBackpressureError().someFastEnoughChain().subscribe(...);

EmitResult result = mySink.tryEmitNext(someT);
//check result
```

`onBackpressureError()` will ensure that the request, from the sink perspective, is always high enough, so `result` won't be `FAIL_OVERFLOW`. But if you try to emit when eg. `sub2` chain is having trouble keeping up, then that part of the chain will get an `onError`.

At the same time, `onBackpressureError` will cancel sub2 subscription to the sink, effectively removing sub2 chain from its subscribers.

**Comment by matyasberry** [comment]
So instead of having multiple subscribers to a single Flux, you suggest to have multiple Flux (each with a single subscription) fed by a single SINK. Interesting.
Will it be possible to manage/count/cancel the subscriptions also from the other end (from the Sink's end)?
Are there any other disadvantages of this approach, that I should be aware?

**Comment by simonbasle** [comment]
yes, via `Sinks.Many#currentSubscriberCount()`

**Comment by matyasberry** [comment]
Did a quick test, but it does not seem like working:
```java

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.mockito.Mockito.mock;
import org.reactivestreams.Subscription;
import reactor.core.CoreSubscriber;
import reactor.core.publisher.Sinks;

/**
 *
 */
public class AggressivePublisherTest {

  static class AggressivePublisher {

    private Sinks.Many<Fragment> sink = Sinks.unsafe().many().multicast().directBestEffort();

    public void subscribe(CoreSubscriber<? super Fragment> actual) {
      sink.asFlux().onBackpressureError().subscribe(actual);
    }

    public void tryNext(Fragment fragment) {
      sink.tryEmitNext(fragment);
    }

  }

  @Test
  public void testNoBackpressure() throws InterruptedException {
    final int count = 256;
    Fragment f = mock(Fragment.class);
    AggressivePublisher cut = new AggressivePublisher();
    PacedSubscriber fast = new PacedSubscriber(0);
    PacedSubscriber slow = new PacedSubscriber(100);
    cut.subscribe(fast);
    cut.subscribe(slow);
    Thread source = new Thread() {
      @Override
      public void run() {
        for (int i = 0; i < count; i++) {
          cut.tryNext(f);
        }
      }
    };
    source.start();
    source.join();
    Assertions.assertEquals(count, fast.received);
    Assertions.assertEquals(10, slow.received);
  }

  static class PacedSubscriber implements CoreSubscriber<Fragment> {

    final int waitMs;
    int received = 0;
    Subscription s;

    public PacedSubscriber(int waitMs) {
      this.waitMs = waitMs;
    }

    @Override
    public void onSubscribe(Subscription s) {
      this.s = s;
      this.s.request(10);
    }

    @Override
    public void onNext(Fragment t) {
      received++;

      if (waitMs > 0) {
        try {
          Thread.sleep(waitMs);
        } catch (InterruptedException ex) {
          //
        }
      }
      this.s.request(1);
    }

    @Override
    public void onError(Throwable thrwbl) {
      thrwbl.printStackTrace();
    }

    @Override
    public void onComplete() {
      // ignore
    }

    public int getReceived() {
      return received;
    }
  }

}
```

**Comment by matyasberry** [comment]
Thank you, this works.
