### ISSUE TITLE
Please consider making it easier for GraalVM to see these types

### ISSUE THREAD

**Issue by joshlong** [reactor/reactor-core#2796]
Right now the GraalVM compiler has trouble seeing the [three types reflectively instantiated in `Traces`](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/publisher/Traces.java#L54 ) at compile time and they're not present in the resulting build. This causes a runtime failure. I think the GraalVM compiler would have less trouble if the classes were not strings but were `.class` literals instead.

**Comment by simonbasle** [comment]
Supposedly, only one of these three types can correctly load at runtime, and it depends on the underlying JVM. These were intended as a way to use the JVM's most performant way to get stacktraces...

Just referencing the `.class` might work though 🤔

**Comment by simonbasle** [comment]
@joshlong can you provide a simple "test" to reproduce the exact issue?

I've just generated a webflux + spring-native project on start.spring.io (gradle/java11), installed the latest GraalVM using homebrew and ran `gu install native-image`, checked that `gradle -q javaToolchains` finds the graalvm installation and ran `gradle nativeRun` and it worked...

My application is a `TracesControllers` that I merely invoke from `main()`:

```java
@RestController
public class TracesController {

	@GetMapping("/trace")
	public Mono<String> trace() {
		String trace = Mono.just("foo").checkpoint().as(Scannable::from).stepName();
		return Mono.just(trace)
			.log();
	}
}
```

```java
@SpringBootApplication
public class ReactorGraalvmTestApplication {

	public static void main(String[] args) {
//		SpringApplication.run(ReactorGraalvmTestApplication.class, args);

		System.out.println(new TracesController().trace().block());
	}

}
```

**Comment by simonbasle** [comment]
for future reference, [here](https://github.com/reactor/reactor-core/pull/2798#issuecomment-931975332) is the comment from @sdeleuze suggesting a configuration file content.

**Comment by simonbasle** [comment]
closing for lack of response
