### ISSUE TITLE
Flux one to many zip

### ISSUE THREAD

**Issue by SujanKumarMitra** [reactor/reactor-core#2802]
Imagine there are two fluxes
```
F1 = [A,B,C]
F2 = [1,2,3]
```
I need to zip them in this fashion
```
F3 = [A1,A2,A3,B1,B2,B3,C1,C2,C3]
```
**Note: One element in F1 is yielding F2, (F2 is not a static flux)**
Currently, no operators support that.

A code example:
```
Flux<Type1> type1Flux = // some source
Flux<Type2> type2Flux = type1Flux.concatMap(this::someOperation)
Flux<Tuple2<Type1,Type2>> = // which operator??
```

**Comment by simonbasle** [comment]
this sounds like a [stackoverflow](https://stackoverflow.com/questions/tagged/project-reactor) question (we favor SO rather than issues for questions)

wouldn't you be able to merely `map` inside the `concatMap`?

```java
Flux<Type1> type1Flux = // some source
Flux<Tuple2<Type1,Type2>> f3 = f1.concatMap(left -> 
    this.someOperation(left).map(right -> Tuples.of(left, right)
);
```

**Comment by SujanKumarMitra** [comment]
> wouldn't you be able to merely `map` inside the `concatMap`?

Yes, in the end, I did that.
