### ISSUE TITLE
When FluxHandle sink.error(ex) is used the data value is not passed to onOperatorError hook

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#282]
My understanding is that the following should really behave the same. (should they?)

`.handle((d, sink) -> d.error(exception))`

`.handle((d, sink) -> { throw Exceptions.propagate(ex); }`

They don't because when `error(exception)` is used `Operators.onOperatorError()` is called in the `error(t)` method rather than in `tryOnNext` before calling `actual.onError()` where the data value is available in context.

**Comment by dfeist** [comment]
@simonbasle See PR for this here: https://github.com/reactor/reactor-core/pull/285

I didn't add test for all fusion variants, though, really this tests should use https://github.com/junit-team/junit4/wiki/Parameterized-tests and been paramatized for each fusion type to make them easy to write and ensure full coverage.

**Comment by simonbasle** [comment]
@dfeist parameterized tests could be a good idea, but the difficulty is that 1) JUnit parameterizes **all** the test methods in a given test class and 2) the parameters could only be the type of source to use, it would still be up to the test method to correctly choose which `Flux` to create (as they all use different operators, etc...). That said, maybe it would still provide better readability.

**Comment by dfeist** [comment]
Some re-org might need to done to seperate tests that should be parameterized and those that shouldn't agree. But in the long run, parameterizing is not only going to give better readability, but also better coverage as testing operators with each variant becomes easier and therefore more commonplace.  Of course it also makes it easier for people like me to add test cases without needing to add a test method for every fusion variant :-)

Was just a side comment, though.  Let me know if need anythng else in this PR..

**Comment by simonbasle** [comment]
I just experimented with this enum as a possible parameter:

```java
/**
 * An enumeration of different possible flavors of publishers, in terms of fuseability,
 * that can be tested by a {@link org.junit.runners.Parameterized} test case.
 */
public enum FusionTestTypes {

	NORMAL, CONDITIONAL, FUSEABLE, CONDITIONAL_FUSEABLE;

	public <T> Flux<T> decorate(Flux<T> source) {
		switch (this) {
			case NORMAL:
				return source.hide();
			case CONDITIONAL:
				return source.hide()
				             .filter(v -> true);
			case CONDITIONAL_FUSEABLE:
				return source.filter(v -> true);
			case FUSEABLE:
			default:
				return source;
		}
	}

	public <T> Mono<T> decorate(Mono<T> source) {
		switch (this) {
			case NORMAL:
				return source.hide();
			case CONDITIONAL:
				return source.hide()
				             .filter(v -> true);
			case CONDITIONAL_FUSEABLE:
				return source.filter(v -> true);
			case FUSEABLE:
			default:
				return source;
		}
	}
}
```
cc @smaldini 

There's also [JUnitParams](http://pragmatists.github.io/JUnitParams/) that could give even better readability. In the meantime, please see my review comment I think there's a couple calls to `onOperatorError` that are missing...

**Comment by dfeist** [comment]
@simonbasle We might need to reopen this one as I'm not 100% sure the behaviour introduced as part of this fix, is fully inconsistent with when an error is signalled in other places.  Can you review my initial assertion with @smaldini ?

The concern I have is regarding consistency with the following, which I don't believe use the `onOperatorError` hook: 
- `Mono.create(sink -> sink.error(e))` (not really an operator..)
- `.concapMap(event -> error(e))`

If this does need to be rolled back, is there any other way I can hook into errors being signalled from `handle()` and `concatMap` in order to wrap them as is required for my use case?  Throwing the exception instead of signalling it would work for `handle()` but not for `concatMap()`.

**Comment by smaldini** [comment]
Do you mean there needs to be a separate issue to review the onOperatorError calls ?

**Comment by dfeist** [comment]
No, I'm looking for your thoughts on when `onOperatorError` should be being used:
- **i)** Only when an operator fails by an error condition or because an exception is propagated by users from within function/consumer.
- **ii)** The above, plus when an error is emitted somehow within an operator. e.g. via sink in `handle()` or via returning `error()` in `concatMap`.

If the answers is **i)** then this change in this PR should probably be rolled back shouldn't it?

If the answers is **ii)** then we might be missing some calls to `onOperatorError` e.g. in `concatMap` and should create a separate issue to review these.

**Comment by smaldini** [comment]
I think this has been covered with the review of onOperatorError use in the last releases. If we find a specific issue that doesn't trigger onOperatorError, it is not intended and should be filled as a bug.
