### ISSUE TITLE
Unexpected CancellationException: FluxSwitchOnFirst has already been cancelled) under particular circumstances

### ISSUE THREAD

**Issue by bruto1** [reactor/reactor-core#2829]
as it says in the subject, manifests similarly to https://github.com/reactor/reactor-core/issues/2765 but under different conditions

## Expected Behavior
No exception

## Actual Behavior
Unexpected CancellationException

## Steps to Reproduce (a bit contrived, pls don't judge):
```java
@Test
void reproCase() {
        var sofTerminalSignal = Sinks.one();

        Flux.just(1, 2, 3)
            .log("source")
            .switchOnFirst((first, all) -> {
                var r = all.log("SOF")
                           .doFinally(sig -> sofTerminalSignal.emitValue(sig, (signalType, emitResult) -> false))
                           .replay()
                           .refCount();
                return Flux.merge(
                               r.log("replay1").then().cast(Integer.class),
                               r.log("replay2").take(2)
                           )
                           .log("merged")
                           .next();
            })
            .as(StepVerifier::create)
            .expectNext(1)
            .verifyComplete();

        StepVerifier.create(sofTerminalSignal.asMono())
                    .expectNextMatches(sig -> sig != ON_ERROR)
                    .verifyComplete();
}
```

haven't figured out how to make it cleaner with expectNoDroppedErrors, but it works like this too

In my production code and integration tests this exception is sometimes dropped and sometimes not due to greater complexity and and more timing variances, I guess

## Your Environment
* Reactor version(s) used: 3.4.11
* JVM version (`java -version`): openjdk-11+28_windows-x64

**Comment by OlegDokuka** [comment]
This behavior is expected since the inner flux completes earlier than the upstream does. That said the implementation on the reception of onComplete signals from the inner tries to cancel upstream, which in turn tries to make sure that inner is also terminated (since the execution is sync, completely comes before the actual cancel signal is being propagated) 

You may disable that if you know for sure that the inner pipe is just a transformation of the original upstream (no breakage of the functional chain or returning another Flux not derived from the original one):

```
@Test
void reproCase() {
        var sofTerminalSignal = Sinks.one();

        Flux.just(1, 2, 3)
            .log("source")
            .switchOnFirst((first, all) -> {
                var r = all.log("SOF")
                           .doFinally(sig -> sofTerminalSignal.emitValue(sig, (signalType, emitResult) -> false))
                           .replay()
                           .refCount();
                return Flux.merge(
                               r.log("replay1").then().cast(Integer.class),
                               r.log("replay2").take(2)
                           )
                           .log("merged")
                           .next();
            }, false) // <- explicitly say to not cancel upstream on the inner termination
            .as(StepVerifier::create)
            .expectNext(1)
            .verifyComplete();

        StepVerifier.create(sofTerminalSignal.asMono())
                    .expectNextMatches(sig -> sig != ON_ERROR)
                    .verifyComplete();
}
```

**Comment by bruto1** [comment]
thanks for the advice, will put it to use
