### ISSUE TITLE
Add .transformEach() in ParallelFlux to support Function<Publisher<U>, Publisher<V>>

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#283]

**Comment by akarnokd** [comment]
https://github.com/reactor/reactor-core/blob/master/src/main/java/reactor/core/publisher/ParallelFlux.java#L912

**Comment by dfeist** [comment]
Sorry, yes it there.

Now i look at it more closely by issue is that it expects and `Function<? super ParallelFlux<T>, ParallelFlux<U>>` and not  `Function<? super ParallelFlux<T>, ? extends Publisher<V>> composer` so it can't be used for chaining in the same way as you would with Flux where you want to apply a Flux transform.

**Comment by dfeist** [comment]
@akarnokd This is what I'd expect, or does it not make sense or is incompatible with parallel version of Flux?

https://github.com/reactor/reactor-core/pull/284

**Comment by dfeist** [comment]
See comments on PR.

**Comment by dfeist** [comment]
@smaldini suggested `.transformEach`

**Comment by dfeist** [comment]
Not sure `transformEach` works given `each` is normally used for per-event. Would need to be something like `transformRail`..  any thoughts @smaldini  ?

**Comment by smaldini** [comment]
agree @dfeist transformEach is maybe a false good idea indeed, transformRail is maybe just enough we name them rail anyway.
