### ISSUE TITLE
FluxOnAssembly$OnAssemblyException is no longer serializable due to introduction of class ObservedAtInformationNode

### ISSUE THREAD

**Issue by trettstadtnlb** [reactor/reactor-core#2831]
## Expected Behavior

The desired behavior is that exceptions thrown should be serializable. This was the case up to version 3.4.10.
## Actual Behavior

Since the class `ObservedAtInformationNode` was introduced here (https://github.com/reactor/reactor-core/commit/df44a2de82a94a4ca5f48b76a4c191deb07ce885#diff-dae5ee5b30b2e0ba5c890a5d525f1d8823f3c5604eb76d4c71140b698d996345R236), serializing an `OnAssemblyException` fails with a `java.ioNotSerializableException: reactor.core.publisher.FluxOnAssembly$ObservedAtInformationNode`

## Steps to Reproduce

```java
@Test
void reproCase() {
    Hooks.onOperatorDebug();
    IllegalStateException sharedError = new IllegalStateException("shared");
    Flux<String> source = Flux.error(sharedError);
    Flux<String> chain1 = source.map(String::toLowerCase).filter(s -> s.length() < 4);
    Flux<String> chain2 = source.filter(s -> s.length() > 5).map(String::toUpperCase);

    Mono<Void> when = Mono.when(chain1, chain2);

    assertThatIllegalStateException()
        .isThrownBy(when::block)
        .withMessage("shared")
        .isSameAs(sharedError);

    assertThat(sharedError.getSuppressed()).hasSize(2);
    Throwable first = sharedError.getSuppressed()[0];
    Throwable second = sharedError.getSuppressed()[1];

    assertThat(first).isInstanceOf(FluxOnAssembly.OnAssemblyException.class);

    OutputStream baos = new ByteArrayOutputStream();
    ObjectOutputStream objectOutputStream = new ObjectOutputStream(baos);
    objectOutputStream.writeObject(sharedError);
}
```

## Possible Solution

If possible, make `ObservedAtInformationNode` serializable.

## Your Environment

* Reactor version(s) used: 3.4.11
* Other relevant libraries versions (eg. `netty`, ...): none
* JVM version (`java -version`):  openjdk-11.0.9_11
* OS and version (eg `uname -a`): Microsoft Windows 10 Pro (10.0.19043 Build 19043)

**Comment by simonbasle** [comment]
this should be doable without too much trouble. do you want to submit a PR @trettstadtnlb ?

**Comment by trettstadtnlb** [comment]
I created a PR: https://github.com/reactor/reactor-core/pull/2833
