### ISSUE TITLE
StepVerifier#thenConsumeWhile about skipping onNext signal

### ISSUE THREAD

**Issue by phantasmicmeans** [reactor/reactor-core#2832]
## Motivation
I'm curious about the StepVerifier#thenConsumeWhile operator 

<img src="https://user-images.githubusercontent.com/20153890/140155267-9e4cdbaa-7c83-49b4-a882-39913d02bfbd.png" width=500>

I know this works based on the onNext signal, and it doesn't seem to work with an empty signal such as FluxEmpty.

```java
@Test
public void test() {
	Flux<Integer> i = Flux.empty();
	StepVerifier.create(i.log())
			.thenConsumeWhile(it -> {
				System.out.println("TEST"); // no excute 
				return true;
			})
			.verifyComplete();
}
// thenConsumeWhile's consumer never execute, but the test will always succeed
```

I'm not sure if it's a related [PR](https://github.com/reactor/reactor-core/pull/2764/files#diff-997d6cb72581d10a2ea63ae69d6db20c7a11e8a9e332dca0441a6b98bfca2a96R2523), but in this case, there is no onNext signal anyway, so thenConsumeWhile is not needed at all. (Perhaps that's why the test method name is `collectEmptyAndNoopConsumeWhile_detectsMissingNext`)

Anyway when testing a flux sequence, there are often cases where we want to test by same logic like thenConsumeWhile. and since the flux sequence can return empty, it would be nice if there was a way to test this too.

## Considered alternatives
Is there any good operator other than checking if the sequence is empty with recordWith and consumeRecordedWith like the code in PR?

If the test target always needs to return 1 item, we can use the single operator. (e.g. `StepVerifier.create(something().single())` and If the test target needs to return at least one item, I think there is a way to collect and check the size first.

<br>

So I mean, what do you think of the new operator combining consumeNextWith and thenConsumeWhile? (e.g. consumeNextWhile)

Something to test with same logic while also checking for empty in flux sequence

## Your Environment
Reactor version(s) used: 3.3.9
Other relevant libraries versions (eg. netty, ...):  netty, spring-boot 2.3.3 
JVM version (java -version): openjdk-11
OS and version (eg uname -a): MacOS BigSur

**Comment by simonbasle** [comment]
`thenConsumeWhile` is intended to "skip" uninteresting items that come in an unknown number. it should be pretty niche.

if you do need to assert the number of items, collecting them is indeed an option.

another option would be to use an `AtomicInteger`, increment it in the predicate and assert the count after the `StepVerifier#verify()`. This would allow detecting empty publisher under test since the count would then be at 0.

keep in mind that there's no such thing as an "empty signal": `Flux.empty()` is just the abscence of `onNext()` by definition, and since `thenConsumeWhile` is intrinsically triggered by `onNext()` it isn't triggered at all in your case.

**Comment by phantasmicmeans** [comment]
Sorry, 'empty signal' is a translation error.

If we need to prevent the test target from returning the empty publisher, I wrote down some example codes below, including the tips you gave me.

```java
@Test
public void test1() {
	AtomicInteger aInteger = new AtomicInteger(0);
	Flux<Integer> flux = Flux.empty();
	StepVerifier.create(flux.log())
			.thenConsumeWhile(integer -> {
				// no execute
				System.out.println("test1");
				aInteger.incrementAndGet();
				assertThat(doSomething(integer)).isTrue();
				return true;
			})
			.verifyComplete();
	assertThat(aInteger.get()).isGreaterThan(0);
}

@Test
public void test2() {
	Flux<Integer> flux = Flux.empty();
	StepVerifier.create(flux.log())
			.recordWith(ArrayList::new)
			.consumeRecordedWith(list -> {
				// execute
				System.out.println("test2");
				assertThat(list.size()).isGreaterThan(0);
				list.forEach(v -> assertThat(doSomething(v)).isTrue());
			})
			.verifyComplete();
}

@Test
public void test3() {
	Flux<Integer> i = Flux.empty();
	StepVerifier.create(i.log().collectList())
			.consumeNextWith(list -> {
				// execute
				System.out.println("test3");
				assertThat(list.size()).isGreaterThan(0);
				list.forEach(v -> assertThat(doSomething(v)).isTrue());
			})
			.verifyComplete();
}

private boolean doSomething(int a) {
	System.out.println("doSomething : " + a);
	/** blabla.. **/
	return true;
}
```

<br>

Isn't it a little uncomfortable to collect as a list or use AtomicInteger?

There are 'assertNext' or 'consumeNextWith', which are operators that verify whether an onNext signal occurs, but this can only be checked for one item.

Can't we verify the entire flux sequence at once as in the example below?


```java
@Test
public void test4() {
	Flux<Integer> i = Flux.empty();
	StepVerifier.create(i.log())
			.consumeNextWhile(integer -> {
				System.out.println("test4");
				assertThat(doSomething(integer)).isTrue();
			})
			.verifyComplete();
}
```

**Comment by simonbasle** [comment]
I would suggest a single assertNext followed by thenConsumeWhile in that case, to check 1 or more elements that all match a criteria
