### ISSUE TITLE
API call error: Did not observe any item or terminal signal within 5000ms (and no fallback has been configured)

### ISSUE THREAD

**Issue by dinesh-nithyanandam** [reactor/reactor-core#2837]
Hi Team,

I would like ask for a critical help and necessary guidance here:
we are using two service which is completely written in spring-webflux and while invoking/calling from service A to service B, we are seeing below error and we are unable to debug further and hard to nail down to what could be ideal root cause for this, Any hints or pointers would certainly help in a big way

**API call error: Did not observe any item or terminal signal within 5000ms (and no fallback has been configured)**

**Comment by simonbasle** [comment]
There is nothing to help us debug here, other than the fact that his message is tied to the `Flux|Mono.timeout(Duration)` operator.
Frankly it doesn't even look like a bug in that light.

Note that questions are best answered on [stackoverflow](https://stackoverflow.com/questions/tagged/project-reactor) as per our [CONTRIBUTING.md](https://github.com/reactor/.github/blob/5d9a06b4ba8cdbec3ae746014c7d206619228aa6/CONTRIBUTING.md#question-do-you-have-a-question)

**Comment by rajxd** [comment]
Hey @dinesh-nithyanandam Have you got the solution of it?
