### ISSUE TITLE
SinkManyBestEffort: performance improvement suggestion for add/remove methods

### ISSUE THREAD

**Issue by bgrooot** [reactor/reactor-core#2842]
## Motivation

-  Each time the add/remove function is run, it creates a new `subscribers` array.
- This affects performance.

## Desired solution

- Avoid re-creating the array by using a data structure with a dynamic size.

## Considered alternatives

- Use the type of `subscriber` as a java collections rather than an array
  - ex) `volatile List<DirectInner> subscribers;`
  - It seems like you could consider the Map type to optimize finding elements in the remove method.
  - Also it looks like you could use concurrent collections.

## Additional context

Running time on my PC was as follows.
```java
val count = 10000

//270ms
fun createArray() {
    val start = LocalDateTime.now()

    Flux.range(1, count)
        .doOnNext { 
            val b = IntArray(it) 
            b[it - 1] = it
        }
        .blockLast()

    println(ChronoUnit.MILLIS.between(start, LocalDateTime.now()))
}

//4ms
fun usingList() {
    val list = mutableListOf<Int>()
    val start = LocalDateTime.now()
    
    Flux.range(1, count)
        .doOnNext { list.add(it) }
        .blockLast()

    println(ChronoUnit.MILLIS.between(start, LocalDateTime.now()))
}
```

**Comment by simonbasle** [comment]
Compared to a `List` or `Map`, the array is memory-efficient and can be used with atomic operations like `getAndSet`.
It also allows us to use 0-sized constant arrays as flags to atomically detect initial EMPTY state and final TERMINATED states.
For the kind of algorithms that we use internally, these properties are very important. Copy-on-write and immutability are also cornerstones of these algorithms.

So the array solution provides better trade-offs than a full-blown collection (which would need to be thread safe and non-blocking, further complicating the choice of collection).

**Comment by bgrooot** [comment]
Thank you for your kind answer.
`Copy-on-write` becomes slow when subscribers are added in bulk.
Can I understand as a considered circumstance or limitation?
