### ISSUE TITLE
Wrong marble diagram for Flux.mergeComparing() and friends

### ISSUE THREAD

**Issue by rschuerer-realnetworks** [reactor/reactor-core#2848]
## Documentation Issue

The marble diagrams for `Flux.mergeComparing()` and friends are wrong. The shown result `Flux` has the correct ordering, but wrong timing.

For example, look at [mergeComparingNaturalOrder.svg](/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/publisher/doc-files/marbles/mergeComparingNaturalOrder.svg) :

When "4" is received from the 2nd input flux, "3" cannot be emitted yet, because there is currently no element available from the 1st flux to compare it to.

The actual (and correct) behavior is that "3" (and "4") are only emitted when "5" is received from the 1st flux.

Affected diagrams:
* `mergeComparingNaturalOrder.svg`
* `mergeComparing.svg`
* `mergeComparingWith.svg`

## Improvement Suggestion

Fix the diagram.

**Comment by simonbasle** [comment]
good catch, will fix these 👍
