### ISSUE TITLE
SinkManyBestEffort add or remove array operation is too slow.

### ISSUE THREAD

**Issue by realzero0** [reactor/reactor-core#2873]
## Motivation
I've been creating a service that is needed very high performance when adding or remove new subscribers on SinkManyBestEffort.
But the performance is poorer than expected...
I think almost all Sink add or remove operations are using Arrays..
If I add or remove more than 500 subscribers within a second, CPU got 100%..

I changed it to use ConcurrentHashmap and now I can add or remove more than 7000 subscribers within a second..

I understand you needed arrays to make the sink thread-safe. 
It might be better if we can have another implementation of SinkManyBestEffort that has different data structure for adding or removing performance..

## Desired solution
other implementation of SinkManyBestEffort that is using different data structure and much faster when adding or removing subscribers..

## Considered alternatives
I've implemented SinkManyBestEffort on my own and used it.

**Comment by OlegDokuka** [comment]
Hey @realzero0. 

It is a known problem and so far the answer - `SinkManyBestEffort` is not designed for intensive subscription/subscription scenario. 

> I think almost all Sink add or remove operations are using Arrays.

The array here is used to achieve a low memory footprint especially assuming that all subscribers are there for a long period of time.

You should create your own Sink implementation to support your scenario for now. 
However, maybe we will consider adding some standard things.
