### ISSUE TITLE
retry inconsistent behavior

### ISSUE THREAD

**Issue by MichaelNesterenko** [reactor/reactor-core#2879]
I was playing around retries and found an inconsistency in retries behavior:

```
		Flux.just(1, 2, 3)
			.doOnNext(i -> {
				if (i > 1) throw new IllegalStateException();
			})
			.retry(2) // <-- ok when retry count is 1
			.doOnEach(i -> System.out.println("after retry: " + i))
			.subscribe(
				i -> System.out.println("subscriber: " + i),
				e -> System.out.println("error-complete " + e),
				() -> System.out.println("success-complete"),
				s -> {
					s.request(1);
					s.request(1);
					s.request(1);
				}
			);
```

## Expected Behavior

When retry count is 1 this flux is completed with an error:

```
after retry: doOnEach_onNext(1)
subscriber: 1
after retry: doOnEach_onNext(1)
subscriber: 1
after retry: onError(java.lang.IllegalStateException)
error-complete java.lang.IllegalStateException
```

Same should happen when retry count is > 1 (e.g. 2)

## Actual Behavior

Flux is never completed:
```
after retry: doOnEach_onNext(1)
subscriber: 1
after retry: doOnEach_onNext(1)
subscriber: 1
after retry: doOnEach_onNext(1)
subscriber: 1
```

## Steps to Reproduce

just run the code

## Your Environment

* Reactor version(s) used: 3.4.13
* JVM version (`java -version`): 17.0.1

**Comment by simonbasle** [comment]
this works as intended I think. What you see stems from the fact that you `request` for 3 elements, and that request is made _to the retry `Flux`_. After two attempts, the request is exhausted and backpressure kicks in right before it would have generated element `2` in attempt `#2` (which is the element that causes the exception). so the flux just hangs.

request more from that same chain and it would continue retrying.

you can observe the request patterns at each steps by adding `doOnRequest` or `log` operators here and there. 

when in doubt about some behavior of a non-trivial chain of operators, prefer asking on [stackoverflow](https://stackoverflow.com/tags/project-reactor/) first 🙏
