### ISSUE TITLE
Concurrent Exception: disconnected

### ISSUE THREAD

**Issue by Stefan16394** [reactor/reactor-core#2881]
Hi all. We are using project reactor in our project and recently we started getting some ConcurrentException: disconnected exceptions. By looking at the logs we noticed that there are cases where we get complete signal and new subscription request roughly at the same time. It seems that while complete signal triggers flux disposing, new subscription gets processed at the same time, which produces the above concurrent exception. We tried adding grace period to refCount(1,Duration.ofSeconds(n)), but the exception still happens from time to time. Would greatly appreciate some help on how to fix this problem? Thanks.

## Actual Behavior

java.util.concurrent.CancellationException: Disconnected
Caused by: java.util.concurrent.CancellationException: Disconnected
at reactor.core.publisher.FluxReplay$ReplaySubscriber.dispose(FluxReplay.java:1287)
at reactor.core.publisher.FluxRefCountGrace.timeout(FluxRefCountGrace.java:151)
at reactor.core.publisher.FluxRefCountGrace$RefConnection.run(FluxRefCountGrace.java:174)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:69)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduedThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecuotr.runWorker(ThreadPoolExecutor.jav:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
## Steps to Reproduce

```java
	public static void main(String[] args) throws InterruptedException {
		Flux<String> flux = Flux.<String>create(sink -> {
					sink.next("test");
					sink.next("test1");
					sink.next("test2");
					sink.onDispose(() -> {
						System.out.println("disposing...");
						try {
							// simulating slow disposing
							Thread.sleep(2000);
						} catch (InterruptedException e) {
							e.printStackTrace();
						}
					});
				})
				.replay(1)
				.refCount(1);

		Disposable subscribe = flux.subscribe();
                // thread that disposes above subscription
		Thread thread = new Thread(new DisposeTask(subscribe));
                // thread that subscribes again at the same time when the above thread calls subscription.dispose()
		Thread thread1 = new Thread(new SubscribeTask(flux));
		thread.start();
		thread1.start();
		new CountDownLatch(1).await(1, TimeUnit.MINUTES);
	}


}

class DisposeTask implements Runnable{
	private Disposable disposable;

	public DisposeTask(Disposable disposable){
		this.disposable = disposable;
	}
	@Override
	public void run() {
		disposable.dispose();;
	}
}

class SubscribeTask implements Runnable{
	private Flux<String> flux;
    public SubscribeTask(Flux<String> flux){
		this.flux = flux;
	}
	@Override
	public void run() {
		flux.subscribe(e->{
			System.out.println("Here" + e);
		});
	}
}
```

## Your Environment

* Reactor version(s) used:
3.3.10.RELEASE
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`):
1.8
* OS and version (eg `uname -a`):
Windows and Linux

**Comment by simonbasle** [comment]
Using the `refCount` variant with a grace period `Duration` is the intended fix in that case. Have you tried increasing the grace period ?

Note that "simulate slow disposing" might also be a possible cause. Ideally, onDispose callback of the sink should not block the actual internal disposing of the sink. Maybe that can be replaced by a task submitted to a common reaper thread (or its own dedicated thread if there are not a large number of such sinks in your app)?

All in all I don't believe there is a bug here (concurrent connections vs disconnections should be solved by a grace period), so I'm closing with "has workaround". Please provide more investigative data if you believe there is a bug.

NB: the latest 3.3.x version is `3.3.22`, so I would also upgrade to that version asap
