### ISSUE TITLE
Difference between as and transform

### ISSUE THREAD

**Issue by kitkars** [reactor/reactor-core#2898]
Hi Team,

I am trying to understand the difference between ` .transform` and `.as` function. They seem to behave almost same. Unfortunately I could not get it from the doc.

**Case 1:**  Both produces same output.

        Flux.just(1)
                .as(m -> Flux.just('a',2,3))
                .doOnNext(System.out::println)
                .subscribe();  // output: a,2,3

        Flux.just(1)
                .transform(m -> Flux.just('a',2,3))
                .doOnNext(System.out::println)
                .subscribe();  // output: a,2,3

**Case 2:** **as** still produces same output. **transform** just produces 'a'.

        Mono.just(1)
                .transform(m -> Flux.just('a',2,3))
                .doOnNext(System.out::println)
                .subscribe();  // output: a

        Mono.just(1)
                .as(m -> Flux.just('a',2,3))
                .doOnNext(System.out::println)
                .subscribe();  // output: a,2,3

Case 3:  The below transform example works great. I can still replace `.transform` into `.as` to get the same output.

https://projectreactor.io/docs/core/release/reference/index.html#advanced-mutualizing-operator-usage

**Comment by OlegDokuka** [comment]
Hi @kitkars!

The better place to ask such questions is StackOverflow. 
Thanks for understanding.

Oleh
