### ISSUE TITLE
Releases should not be compiled against snapshot dependencies

### ISSUE THREAD

**Issue by wilkinsona** [reactor/reactor-core#291]
3.0.3.RELEASE was compiled against `io.projectreactor:jsr166:1.0.0.BUILD-SNAPSHOT`. To ensure that builds are repeatable, releases should only be compiled against tagged and released dependencies and not against snapshots. I'd really like this to be fixed for 3.0.4, please.

To ensure that this sort of problem doesn't occur, I'd recommend configuring the build so that snapshots repositories are not available when doing a release. Spring Integration's build [has an example of how to do this](https://github.com/spring-projects/spring-integration/blob/295d609eb3e792a50594fab9d5b374dacb0c8844/build.gradle#L32-L38).

**Comment by simonbasle** [comment]
keeping this issue open as the suggestion of excluding snapshot repositories from RELEASE builds hasn't been implemented.
@wilkinsona note that a `io.projectreactor:jsr166:1.0.0.RELEASE` was released by @smaldini and `3.0.4.RELEASE` uses it ;)
