### ISSUE TITLE
Prefix internal thread pool's name with `reactor`?

### ISSUE THREAD

**Issue by hepin1989** [reactor/reactor-core#2944]
reactor.core.scheduler.Schedulers#PARALLEL
![image](https://user-images.githubusercontent.com/501740/156160147-24c35d39-7dd6-4338-ae7f-2f505f092129.png)
![image](https://user-images.githubusercontent.com/501740/156160180-8c41dee8-b941-4f39-ab77-66bf06381ad0.png)
I think it would be more accisiable with `reactor-parallel`.

**Comment by simonbasle** [comment]
That would have been a good idea at the beginning, but I'm not sure it's a good idea to change the representation and names now that this has been in production for 5 years...

Closing this as `declined`, and this can be reopened if there is stronger push for such a subtly breaking change.
