### ISSUE TITLE
Use more specific exception to signal queue overflow

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#295]
By using an `IllegalStateException` to signal queue overflow, for example, when using `reactor.core.publisher.FluxSink.OverflowStrategy#ERROR` it makes it impossible to differentiate between this specific overflow condition, which you may want to handle in a specific way (e.g. server busy error) with other potentially more serious `IllegalStateException`'s.

I propose using a `BufferOverflowException` for this. This can still extend `IllegalStateException` if this makes sense.

(Also ensure consistent use of `reactor.core.Exceptions#failWithOverflow`)

**Comment by dfeist** [comment]
Actually java already has an exception that could potentially be used: `java.nio.BufferOverflowException`

**Comment by smaldini** [comment]
Seems legit, although breaking but the unpractical reason mentioned in the issue leaves little chance that exception was actually leveraged so far.

**Comment by dfeist** [comment]
@smaldini It wouldn't really be breaking if we extended `IllegalStateException`, which might be a good idea anyway..

**Comment by smaldini** [comment]
Surface API 💃

**Comment by dfeist** [comment]
👍 Either way, it vote against leaving this until 3.1 if at all possible.

**Comment by simonbasle** [comment]
@smaldini @dfeist if we don't want to extend the API surface (by adding a new public class), how about introducing a package-private `OverflowException extends IllegalStateException` along with a static checker method `isOverflow(Throwable t)` in `Exceptions`?
We can later make the exception class public if it becomes important.

**Comment by dfeist** [comment]
That would work for 3.0.4 at least, but TBH I'm not sure what the issue with adding a new public class is if it's clearly needed, as long as it doesn't break compatibility.

**Comment by dfeist** [comment]
@simonbasle @smaldini  Can we use this exception more explicitly in 3.1 now, rather than hiding it?  e.g. in FluxSink i'd expect to read:
```
		/**
		 * Signal an {@link OverflowException} when the downstream can't keep up
		 */
		ERROR,
```

This is clearer and also allows users to catch exceptions caused by the specific issue. IllegalStateException is too generic!
