### ISSUE TITLE
java.lang.ClassCastException: reactor.core.publisher.MonoOnAssembly cannot be cast to reactor.core.publisher.MonoProcessor

### ISSUE THREAD

**Issue by dzharikhin** [reactor/reactor-core#2970]
Getting exception in runtime:
`java.lang.ClassCastException: reactor.core.publisher.MonoOnAssembly cannot be cast to reactor.core.publisher.MonoProcessor`
when using `ReactorDebugAgent` from reactor-tools
Exception raises on usage of deprecated method toProcessor

## Expected Behavior

No exception occurs
## Actual Behavior

`java.lang.ClassCastException: reactor.core.publisher.MonoOnAssembly cannot be cast to reactor.core.publisher.MonoProcessor`
## Steps to Reproduce

PRECONDITION: enable `ReactorDebugAgent`
```java
@Test
void reproCase() {
  Mono.delay(Duration.ofSeconds(3))
                .toProcessor()
                .block()!!
}
```
## Your Environment

* Reactor version(s) used: 3.4.13
* Spring-boot: 2.6.2
* JVM version (`java -version`): openjdk 13.0.10 2022-01-18, OpenJDK Runtime Environment Zulu13.46+15-CA (build 13.0.10+5-MTS)
* Kotlin: 1.6.0
* OS and version (eg `uname -a`): macos 12.2.1

**Comment by simonbasle** [comment]
Hi @dzharikhin, I wasn't able to reproduce this issue.
Could you provide a small project that can reproduce it with a simple checkout and build ?
(including explicit steps to activate the debug agent, etc...)
Also, please just use Java in that repro, and consider bumping reactor's version to the latest `3.4.16`.

**Comment by dzharikhin** [comment]
Hi, thank you for your attention
Here is the example project based on Java: https://github.com/dzharikhin/reactor-issue-2970
