### ISSUE TITLE
"Natural" `last()` method in `Flux` to allow for clean error handling

### ISSUE THREAD

**Issue by PMacho** [reactor/reactor-core#2978]
"Natural" `last()` method in `Flux`

## Motivation

At the moment, there are two methods to find the last element of a Flux. In case of an empty `Flux`, the  `last()` method signals `NoSuchElementException` and the `last(T defaultValue)` returns the provided default.
This behaviour kind of resembles the behaviour of classical arrays, just throwing `OutOfBoundsException` and leaving the user with possibly catching this and returning a default. 

## Desired solution

From a reactive streams perspective, I however think, this is not the most natural way to handle such a situation. I think, the last signal of an empty source of signals is just no signal. If the user wants to provide a fallback, he should do this reactively with `switchIfEmpty(Mono<? extends T> alternate)`.

I.e., I suggest to change the behaviour of `last()` to just complete, if there are no `next` signals and to remove the method `last(T defaultValue)`, or at least change the latter to do `last().switchIfEmpty(Mono.just(defaultValue))`.

Especially, thinking about prepared pipelines, within a library, this would allow for way cleaner opting-in of defaults by the user. To be more precise. At the moment, we do the following:

    class AnyClass<T> {

        private final Mono<T> defaultSignal;    

        public AnyClass(Mono<T> defaultSignal) {
            this.defaultSignal = defaultSignal;
        }

        public AnyClass() {
            this(Mono.empty());
        }

        public Mono<T> anyMethod() {
            Flux<T> flux = ...;
            return flux.last().onErrorResume(throwable -> {
                if (throwable instanceof NoSuchElementException)
                    return defaultValue;
                else
                   return Mono.error(throwable);
            })
       }
    }

Thus, the implemented logic depends on the kind of error signal, which, I think, is generally no good style, for multiple reasons (not optimizable, imperative, badly readable, ... ). Plus, we are kind of rebuilding the already existing functionality of `switchIfEmpty`. Further, the `flux` itself might signal `NoSuchElementException`, what would lead to unpredictable behaviour. With the suggested improvement, the returning line in the above code would be:
    
     flux.last().switchIfEmpty(defaultSignal);

## Considered alternatives

see above

**Comment by simonbasle** [comment]
if `source.last()` is empty, then we're sure that `source` itself is empty. Thus the above can be obtained by doing `source.switchIfEmpty(defaultSignal).last()`.

**Comment by PMacho** [comment]
`source.switchIfEmpty(defaultSignal).last()` will still signal an error if `defaultSignal = Mono.empty()`, which is kind of inconsistent, especially thinking about `Flux.empty().switchIfEmpty(Mono.empty()).last()`.

I however see the point of changing an already established API.
