### ISSUE TITLE
Flux.from Iterable skips a Row while reading CSV rows

### ISSUE THREAD

**Issue by dharmic6** [reactor/reactor-core#2979]
```
import com.opencsv.CSVParserBuilder;
import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import com.opencsv.ICSVParser;
import org.apache.commons.io.IOUtils;
import org.junit.Test;
import reactor.core.publisher.Flux;
import reactor.test.StepVerifier;

import java.io.InputStreamReader;

import static java.nio.charset.StandardCharsets.UTF_8;

public class EmitterProcessorTest {

    @Test
    public void test() {

        ICSVParser csvParser = new CSVParserBuilder()
                .withSeparator('|')
                .build();
        String initialString = "header|header2\n" +
                "1|2\n" +
                "3|4\n" +
                "5|6";
        CSVReader csvReader = new CSVReaderBuilder(new InputStreamReader(IOUtils.toInputStream(initialString, UTF_8)))
                .withCSVParser(csvParser)
                .build();

        StepVerifier.create(Flux.fromIterable(csvReader))
                .expectNextCount(4).verifyComplete();


    }
}
```

## Expected Behavior
Supposed to return 4 rows. 

## Actual Behavior
Returns only 3 rows. top row goes missing.
java.lang.AssertionError: expectation "expectNextCount(4)" failed (expected: count = 4; actual: counted = 3; signal: onComplete())

Previous version (2.2.6) returns all 4 rows.

## Steps to Reproduce
Please run the above test

## Possible Solution
Below is a temporary solution till we have a permanent fix.
```
Mono.fromCallable(csvReader::peek).concatWith(Flux.fromIterable(csvReader))
```

## Your Environment

* Reactor version(s) used: 3.4.15
* Other relevant libraries versions (eg. `netty`, ...): 4.1.74.Final
* JVM version (`java -version`): 1.8
* OS and version (eg. `uname -a`):
* opencsv.version: 5.6 
* commons-io.version: 2.11.0

**Comment by violetagg** [comment]
@dharmic6 I moved the issue from reactor-netty to reactor-core as it is not related to Reactor Netty.

**Comment by simonbasle** [comment]
It appears that OpenCsv's `CsvReader#iterator()` is a side-effecting method. The mere act of obtaining an `Iterator` makes the `CsvReader` read the next line. This is incompatible with Reactor's `fromIterable` operator.

see the javadoc section:
```java
/**
	 * This operator inspects the {@link Iterable}'s {@link Spliterator} to assess if the iteration
	 * can be guaranteed to be finite (see {@link Operators#onDiscardMultiple(Iterator, boolean, Context)}).
	 * Since the default Spliterator wraps the Iterator we can have two {@link Iterable#iterator()}
	 * calls. This second invocation is skipped on a {@link Collection} however, a type which is
	 * assumed to be always finite.
	 */
```
