### ISSUE TITLE
Add a new param `MetricsOptions` in `Mono#metrics` and `Flux#metrics` for users to customize name and enabled status

### ISSUE THREAD

**Issue by JamesChenX** [reactor/reactor-core#2990]
## Motivation

We want `MetricsOptions` to customize name and enabled status because: 
1. The default metric name is named from the perspective of `reactor-core` but we, users, may want to name these names from our business or feature perspective. e.g. `[name].subscribed` (default) to `[name].called`.
2. We want to disable some unused metrics so that we don't need to pay for them.

## Desired solution

Provide a `MetricsOptions` for `metrics()`

Pesudocode:
```java
Mono.just(1)
        .metrics(MetricOptions.getDefault()
                .subscribed()
                    .name("called")
                .flowDuration()
                    .disabled(true))
```

**Comment by simonbasle** [comment]
thanks for the suggestion @JamesChenX !

As a side note, I'd be interested in learning how you use Flux/Mono-level metrics, and how important and useful you think these are. Ever since I added them, my feeling has been that these are not that interesting because the level of granularity is too thin.

I'm not sure it is worth investing more in the `metrics()` operator for such configurability, to be honest.

The cost of the unused metrics is not entirely removed by the following workaround, but using `MeterFilter` should help:

```java

	@Test
	void meterNameCanBeTransformed() {
		SimpleMeterRegistry reactorDedicatedRegistry = new SimpleMeterRegistry();
		reactorDedicatedRegistry.config().meterFilter(new MeterFilter() {

			@Override
			public MeterFilterReply accept(Meter.Id id) {
				if (id.getName().endsWith(METER_FLOW_DURATION)) return MeterFilterReply.DENY;
				return MeterFilter.super.accept(id);
			}

			@Override
			public Meter.Id map(Meter.Id id) {
				if (id.getName().endsWith(METER_SUBSCRIBED)) {
					return new Meter.Id(id.getName().replace(METER_SUBSCRIBED,".called"),
						Tags.of(id.getTags()), id.getBaseUnit(), id.getDescription(), id.getType());
				}
				return id;
			}
		});
		
		Metrics.MicrometerConfiguration.useRegistry(reactorDedicatedRegistry);
		io.micrometer.core.instrument.Metrics.globalRegistry.add(reactorDedicatedRegistry);

		Flux<Integer> source = Flux.range(1, 123)
			.hide();

		new FluxMetrics<>(source).blockLast();

		Meter subscribedMeter = registry
			.find(REACTOR_DEFAULT_NAME + METER_SUBSCRIBED)
			.meter();

		assertThat(subscribedMeter).as("subscribed meter with default name").isNull();

		Meter calledMeter = registry
			.find(REACTOR_DEFAULT_NAME + ".called")
			.meter();

		assertThat(calledMeter)
			.as("subscribed meter with customized name")
			.isNotNull()
			.isInstanceOf(Counter.class);

		Meter flowDurationMeter = registry
			.find(REACTOR_DEFAULT_NAME + METER_FLOW_DURATION)
			.meter();

		assertThat(flowDurationMeter).isNull();
	}
```

**Comment by JamesChenX** [comment]
Thanks for the detailed explanation @simonbasle!

### How you use Flux/Mono-level metrics
We use the `.metrics()` for our RPC implementation currently, e.g. when an RPC client sends requests, we want collects metrics from it:
```java
Mono<T> responseMono = client.sendRequest(request, requestBody)
             .name("rpc.request")
             .tag(METRICS_TAG_REQUEST_NAME, request.name())
             .tag(METRICS_TAG_REQUEST_TARGET_NODE_ID, memberId)
             .metrics()
             .subscribe(...);
```
* the current metric name for counting the sent RPC requests is `rpc.request.subscribed` which isn't accurate for our cases, and we want to name it `rpc.request.sent`.
* We want to disable some other metrics provided by `reactor-core` because： 1. it takes more system resources; 2. it makes the metrics data a little confusing when we export them to Prometheus UI report because some metrics are meaningless and unused for our cases.

### How important and useful you think these are
The feature will make our metrics names meaningful and consistent because our server has a lot of metrics that are not just provided by `reactor-core`. And we also provide the metrics data for our users, but the names are a little confusing for them.
So this feature is just an `enhancement` and not `required` feature. The workaround you commented on can work but it's not an elegant way to do it so if `reactor-core` can allow users to customize their names and enabled status, which will be more robust and elegant.
