### ISSUE TITLE
Rename TestSubscriber#awaitAndAssertValues(With)

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor-core#30]
After more thoughts and feedback after my Hands-On, I think we should rename `TestSubscriber#awaitAndAssertValues` to something like `TestSubscriber#awaitAndAssertNextValues` or `TestSubscriber#awaitAndAssertNext` because current name is misleading. Same thing for `TestSubscriber#awaitAndAssertValuesWith`.

**Comment by rstoyanchev** [comment]
Another option would be to add `awaitCount` or `awaitValueCount` and then drop the awaitAndAssertXxx variants altogether.  Also with Java 8 long + TimeUnit could be just `Duration`.

**Comment by sdeleuze** [comment]
Good idea !

**Comment by sdeleuze** [comment]
I am wondering if we are not going to have issues like more values received between `awaitCount` and `assertValues`... Any thoughts @smaldini ?

**Comment by smaldini** [comment]
yeah you might have to loosen the rule of assertCount and Values to work on mimimums. Unless you specifically asked for N with request, nothing prevents N + 1 and N + 2 between 2 calls.

**Comment by sdeleuze** [comment]
I have made a PR, I made a try with shorter names but that was not a good idea IMO.

https://github.com/reactor/reactor-core/pull/32
