### ISSUE TITLE
Add Mono<Tuple<T1, T2> Mono.and(Function<T, Mono<T2>> function)

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#300]
Add
```
Mono<Tuple<T1, T2> Mono.and(Function<T, Mono<T2>> function)
```

The following
```mono.and(request -> handleRequest(request));```

is more concuse and understandable than:

```.then(request -> handleRequest(request).map(response -> Tuples.of(request, response)))```

**Comment by smaldini** [comment]
Legit operator request we'll consider 
/cc @nebhale, looks like your thenKeep().

**Comment by smaldini** [comment]
To be renamed zipWith
