### ISSUE TITLE
Reference Guide not using screen space optimally in portrait mode

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#3011]
The mobile / portrait version of the reference guide is not making great use of horizontal space.

When I zoom out on my mobile phone, paragraphs are visibly smaller than the available space. It seems it has something to do with a couple tables, notably one in the Kotlin section. These tables take the whole width of screen estate while the rest of the content seem stuck with using only a fraction of it 😢

I tried to drill down into the css and rendering using dev tools but couldn't find why it ends up this way.

See also #2784 and #3009

**Comment by tmyksj** [comment]
Thank you very much for opening the issue. I will try and investigate it.

**Comment by hjsfdhkjsafh** [comment]
The same happened to me so I very much agree.
