### ISSUE TITLE
`Mono.from(Flux)` doesn't invoke the `onComplete` callback of the given Flux

### ISSUE THREAD

**Issue by woodyn1002** [reactor/reactor-core#3024]
## Expected Behavior

`Mono.from(Flux).subscribe()` must invoke the `onComplete` callback of the given Flux.

## Actual Behavior

It doesn't invoke the `onComplete` callback. Same on the `onTerminate` callback.
Otherwise, `Mono.from(Mono)`, `Flux.from(Flux)` and `Flux.from(Mono)` work successfully.

## Steps to Reproduce

```java
@Test
void reproCase() {
    AtomicInteger integer = new AtomicInteger(0);

    Mono.from(Flux.fromIterable(List.of(""))
                    .doOnComplete(() -> integer.incrementAndGet()))
            .subscribe();

    assertThat(integer.intValue(), is(1));
}
```

## Your Environment

* Reactor version(s) used: 3.3.14, 3.4.17
* Other relevant libraries versions (eg. `netty`, ...): none
* JVM version (`java -version`): openjdk version "17" 2021-09-14
* OS and version (eg `uname -a`): Darwin MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64

**Comment by simonbasle** [comment]
works as intended. you are putting the `doOnComplete` operator on the `Flux`, which gets cancelled by `Mono.from(Flux)` after the first element is emitted. If you put `doOnComplete` at the level of the mono rather than the flux, it will work.
