### ISSUE TITLE
Support BiConsumer Chaining in Schedulers.onHandleError

### ISSUE THREAD

**Issue by alzimmermsft** [reactor/reactor-core#3038]
## Motivation

`Schedulers` provider the ability to configure a handler when the `Scheduler` handles an error. Right now, it isn't possible to determine whether a handler has already been added and setting the handler is a full replacement, so if multiple libraries interact with `Schedulers` it's possible for them to overwrite each other's handler.

## Desired solution

`Schedulers.onHandleError` should check if a handler has already been added and use `BiConsumer.andThen` to chain the handlers, if a handler has already been set, preventing multiple calls from overwriting each other.

This already occurs in other areas such as [`Hooks`](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/publisher/Hooks.java#L175).

## Considered alternatives

Another solution would be allowing the current handler to be inspected. But, this isn't as convenient as this pushes handling to not overwrite existing handlers to the caller, which may not know how the handler is used internally.

## Additional context

[`Schedulers.onHandleError`](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/scheduler/Schedulers.java#L518)

**Comment by simonbasle** [comment]
This should be easy enough to add. The legacy method can be considered an anonymous part of the hook, allowing keyed parts to be additive even if someone calls the no-key variant.
