### ISSUE TITLE
Add Context API for writing from a `Map`

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-core#3080]
For the work on the upcoming [context-propagation](https://github.com/micrometer-metrics/context-propagation) API, it would be useful to have some small improvements added for more optimal reading and writing from and to a `java.util.Map`.

~For reading, add some iteration based option, e.g. `forEach(BiConsumer<K, V>)`, as an alternative to the existing `stream()` of map entries.~ (note: now tracked in #3094)

For writing, the option to use `context.putAll(map)` as an alternative to `Context.of(map).readOnly()` to avoid the need for a `ContextView` wrapper.

**Comment by simonbasle** [comment]
For the implementation of this change, a few things to keep in mind:
 - there are multiple reactor-core implementations of `Context[View]`: `Context0`, `Context1`..`Context5` and then the general-purpose `ContextN`
 - all keys and values MUST NOT be null. we can imagine that for `putAll(Map)` null keys and null values might get ignored. or throw an NPE, like it is the case with `put`.
 - Small context implementation holds key-value pairs in fields (eg. `Context4` has 4 `keyX` fields and 4 `valueX` fields)
 - `ContextN` extends `LinkedHashMap` internally. the mutative operations are never exposed _so far_ but it means that:
   - whatever new API, it has to be compatible with `Map` API if the names overlap (`forEach` should be good)
   - new APIs cannot delegate to the map API if it makes mutation accessible

**Comment by simonbasle** [comment]
`Context putAll(Map)` isn't going to be possible as the signature will clash with `void putAll(Map)` from `Map` supertype in `ContextN`. How about `putAllMap`?

**Comment by simonbasle** [comment]
Arguably It is a bit of an implementation detail that `ContextN` extends `LinkedHashMap`, but it allows for a few optimizations when dealing with various `reactor-core` contexts. So removing that superclass makes the implementation way more complex than if we just choose a different name.

**Comment by rstoyanchev** [comment]
Yes, I thought about the fact, it's not obvious from the `Contract` why it is a different name. It's more for internal, performance reasons I guess, but the name is reasonable enough and starts with `putAll` so it's not like you can miss it.
