### ISSUE TITLE
A .validate operator

### ISSUE THREAD

**Issue by lynch19** [reactor/reactor-core#3085]
## Motivation

A common use case when working with data streams (especially within APIs) is the need for validation. The `javax.validation.Validator` interface has become the standard way of validating, similar to `Logger` within the logging area.

## Desired solution

Exactly as for what's offered for logging in Reactor (e.g. `Flux<T> log(Logger logger)`), I suggest the addition of `Flux<Set<ConstraintViolation<T>>> validate(Validator validator)`. Since returning `Set<ConstraintViolation<T>>` can be a little wierd and uncomforable in some cases, I also suggest 
 `Flux<T> validate(Validator validator, Predicate<Set<ConstraintViolation<T>>> validationBasedFilter, BiConsumer<Set<ConstraintViolation<T>>> validationsHandler)` which takes:

1. `Validator validator` - the validator implementation
2. `Predicate<Set<ConstraintViolation<T>>> validationBasedFilter` - a filter for each item, based on all of the contraint violations.
3. `BiConsumer<T, Set<ConstraintViolation<T>>> validationsHandler` - a custom handler that enables the user to perform operations like logging, doing some IO tasks like writing the message to a database, and more.

## Considered alternatives

Documenting more about the regular usage of validations with Reactor, since it's not clear enough yet.

## Additional context

A [related Stackoverflow question](https://stackoverflow.com/questions/57637576/including-validation-into-a-reactive-chain-with-project-reactor).

**Comment by simonbasle** [comment]
There is nothing special about `Validator` that we want to support and need an operator for. Keep in mind it is not a goal of this library to support every single class in the Java ecosystem, particularly not `javax` ones.
You say `javax.validation.Validator` is the standard way, other say hibernate validation, and soon everybody asks for support and examples around their library of choice...
we'll keep reactor-core generic, both in terms of operators and documentation on using said operators.
