### ISSUE TITLE
Tasks executed on VirtualTimeScheduler never get disposed

### ISSUE THREAD

**Issue by mdindoffer** [reactor/reactor-core#3088]
## Expected Behavior
Tasks scheduled on the `VirtualTimeScheduler` should have a disposed flag set after they are finished.
Also, manually disposing a task should result in setting the `isDisposed` flag.

## Actual Behavior
Tasks scheduled on the `VirtualTimeScheduler` return a simple lambda implementation that is always non-disposed, no matter if the task is completed, or if you manually call `.dispose()`. This makes unit tests using the virtual time unable to test whether certain tasks have been completed or not.

## Steps to Reproduce

```java
@Test
void runTest() {
	VirtualTimeScheduler vtScheduler = VirtualTimeScheduler.create();
	Scheduler.Worker virtualTimeWorker = vtScheduler.createWorker();

	Disposable schedulerDisposable = virtualTimeWorker.schedule(() -> System.out.println("Executing runnable"));

	vtScheduler.advanceTime();
	System.out.println("Disposable isDisposed: " + schedulerDisposable.isDisposed());
	schedulerDisposable.dispose();
	vtScheduler.advanceTime();
	System.out.println("Disposable isDisposed after explicit dispose: " + schedulerDisposable.isDisposed());
}
```

## Possible Solution
I think the disposable returned from the VirtualTime worker should be not just a simple lambda, rather it should actually implement the `Disposable` interface and override the methods to keep track of the `disposed` status.

## Your Environment
* reactor-test 3.4.18

* Reactor version(s) used: 3.4.18
* JVM version (`java -version`): 
```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)
```

* OS and version (eg `uname -a`):
```
Linux mao-Precision-3551 5.15.0-33-generic #34~20.04.1-Ubuntu SMP Thu May 19 15:51:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by simonbasle** [comment]
good enhancement idea, and it shouldn't be too hard to implement on the `3.4.x` branch 👍 would you like to try and contribute it @mdindoffer?

**Comment by mdindoffer** [comment]
@simonbasle sure, PTAL #3097
