### ISSUE TITLE
Add an otherwiseGet() method to Mono

### ISSUE THREAD

**Issue by marianogonzalez** [reactor/reactor-core#309]
Right now Mono has an otherwiseReturn() method which allows setting a default value in case of an empty mono.

The problem with that is that sometimes the default value is dynamic and requires some processing. With this approach, that processing needs to be performed before hand even if the mono will end up not being empty.

It'd be great to have a Mono.otherwiseGet() method, which behaves similar to java.util.Optional#orElseGet(Supplier<T>)

**Comment by simonbasle** [comment]
You could use `otherwise(...)` since the function is lazily evaluated:
`otherwise(t -> Mono.just(myLazyMethodCall())`

**Comment by marianogonzalez** [comment]
Hello,

Please correct me if I'm wrong but otherwise is executed when the Mono completes with error. The case I'm mentioning is the case in which it complains without a value. What I'm looking for is a way of applying the same patter but for the defaultIfEmpty(T) method.

Thanks

**Comment by smaldini** [comment]
Would the current ```mono.otherwiseIfEmpty(Mono.fromCallable(() -> c)``` help ?

**Comment by marianogonzalez** [comment]
yes, that should do it. I still believe that a shortcut method would be handy though.

Thanks!
