### ISSUE TITLE
Update reactor.core.publisher.Operators to accept ContextView instead of Context

### ISSUE THREAD

**Issue by bruto1** [reactor/reactor-core#3096]
SynchronousSink has currentContext() marked as deprecated in favor of contextView(), but other classes using Context have not followed suit.
Therefore, there's currently no way to resolve deprecation warning in Flux.handle if you want to use Operators.onDiscard, for example

**Comment by simonbasle** [comment]
if you're specifically talking about `Operators.onDiscard*` methods, there is unfortunately no good way of massaging `ContextView` back into these signatures. we _could_ duplicate the methods with `ContextView` signatures, but these methods are primarily intended for *operator implementations*, not to be used within higher-level parts of the API like user-provided lambdas.

if you want to use these methods in the `handle` lambda, one workaround is to use `Context.of(sink.contextView())`, like in:
```java
Flux.empty()
	.handle((v, sink) -> {
		Operators.onDiscard(v, Context.of(sink.contextView()));
	});
```
