### ISSUE TITLE
SingleTimedScheduler doesn't reject immediately on shutdown

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#311]

**Comment by simonbasle** [comment]
`on-hold` until #451 is done, `need-more-info` because not sure if still relevant... Not sure what this issue was referring to (doesn't seem to be a `dispose()` followed by `schedule(...)` as these are correctly REJECTED).

**Comment by smaldini** [comment]
I think its related to the scheduler or worker shutdown directly not being checked in later schedule.

**Comment by simonbasle** [comment]
couldn't reproduce after changes in #451, will close for now
