### ISSUE TITLE
`flapMap` hangs when lambda of lambda

### ISSUE THREAD

**Issue by andriperalt** [reactor/reactor-core#3135]
We incorrectly implemented a `flatMap` in a very standard `Flux` stream. Still, instead of getting an error because of the mistake, the application never executes the code inside the `flatMap` and just hangs.

I don't know if this is a bug, but if someone can provide advice, it will be great!

## Expected Behavior
Compilation error.

## Actual Behavior
`Flux.blockLast()` never completes.

## Steps to Reproduce
Basic example (notice the **second** `flatMap`):

```java
import org.reactivestreams.Publisher;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

public class ReactorFlapMapBug {

  public ReactorFlapMapBug() {
    Flux.just("A", "B", "C")
        .flatMap(this::printElement)
        .flatMap(e -> x -> printElementAgain(e))
        .blockLast();
  }

  public static void main(String[] args) {
    new ReactorFlapMapBug();
  }

  private Publisher<String> printElement(String element) {
    return Mono.fromCallable(() -> {
      System.out.println("first time: " + element);
      return element;
    });
  }

  private Publisher<String> printElementAgain(String element) {
    return Mono.fromCallable(() -> {
      System.out.println("again: " + element);
      return element;
    });
  }
}
```
Output:
```shell
first time: A
first time: B
first time: C
```

## Your Environment

* Reactor version(s) used: 3.4.21
* JVM version (`java -version`): Eclipse Temurin version 11.0.14
* OS and version (eg `uname -a`): Linux 5.18.15-hardened1-1-hardened 1 SMP PREEMPT_DYNAMIC Sun, 31 Jul 2022 22:08:08 +0000 x86_64 GNU/Linux

**Comment by simonbasle** [comment]
there's nothing we can do here. you provide a `Function` (first lambda) which signature must go from a `String` (`e`) to a `Publisher<X>`. You then provide a _second_ lambda, and the compiler accepts that as a `Publisher` (which is effectively a functional interface). The compiler interprets `x -> printElementsAgain` as the implementation of the `subscribe` method.
furthermore, in this lambda, the input `x` is completely ignored. Since the expected return type of the method is `void`, the implementation is deemed correct.

but indeed, it is not. The contract for `subscribe` is to provide the `x` subscriber with a `Subscription` object.

best way to show what's going on and to unstuck the sample is to turn `x -> printElementsAgain(e)` into:
```java
.flatMap(e -> x -> {
					System.out.println(x);
					printElementAgain(e); // result was previously ignored
					Operators.complete(x);
				})
```

**Comment by simonbasle** [comment]
of course the obvious solution is to fix the nested lambda mistake.

for science, you can "connect the chains" artificially by tricking the `printElementsAgain` mono into thinking it is part of the chain:
```java
.flatMap(e -> x -> printElementAgain(e).subscribe(x))
```
this is profoundly useless, but demonstrates that `x` is a subscriber (created by the flatmap)

**Comment by andriperalt** [comment]
> there's nothing we can do here. you provide a `Function` (first lambda) which signature must go from a `String` (`e`) to a `Publisher<X>`. You then provide a _second_ lambda, and the compiler accepts that as a `Publisher` (which is effectively a functional interface). The compiler interprets `x -> printElementsAgain` as the implementation of the `subscribe` method. furthermore, in this lambda, the input `x` is completely ignored. Since the expected return type of the method is `void`, the implementation is deemed correct.
> 
> but indeed, it is not. The contract for `subscribe` is to provide the `x` subscriber with a `Subscription` object.
> 
> best way to show what's going on and to unstuck the sample is to turn `x -> printElementsAgain(e)` into:
> 
> ```java
> .flatMap(e -> x -> {
>   System.out.println(x);
>   printElementAgain(e); // result was previously ignored
>   Operators.complete(x); // this provides an empty subscription and completes the subscriber immediately
> })
> ```

Thank you for the detailed explanation!
