### ISSUE TITLE
Propagate cancel signal on Mono to wrapped CompletableFuture 

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor-core#3138]
Currently, `Mono#fromFuture` uses `MonoCompletionStage`, and `CompletionStage` does not have a `cancel` method. As a result, even if the `Mono` is cancelled, the future is never made aware of it.

**Comment by OlegDokuka** [comment]
@rstoyanchev hah! it is already fixed in 3.5.x by #3081. Do we need that backported into 3.4?

**Comment by rstoyanchev** [comment]
Nice :+1: ! Yes please, a targeted backport of the cancellation propagation to CompletableFuture would be great indeed. The above linked issue is with Spring for GraphQL 1.0 and Reactor 3.4.x so that would help there.

**Comment by OlegDokuka** [comment]
closed with #3146
