### ISSUE TITLE
can't multi thread when on ECS

### ISSUE THREAD

**Issue by Elle-Q** [reactor/reactor-core#3139]
I was parsing a big size file using flux. Here is the main code 
![974279d40876c9dd6e6b90c8fd14d0c](https://user-images.githubusercontent.com/33471396/183279111-e025aeb4-43b5-43bf-8452-da68b4467959.jpg)

I want it to run in multi-threads, which .parallel() -> runOn.boundElastic() can do that.

It works fine on my personal pc, as shown in the pic, there are 5 threads running concurrently.
![daa1297a6d71ce521dd74a0e0602576](https://user-images.githubusercontent.com/33471396/183279119-c18b0c59-49c2-49e0-b700-e78ad364c17f.jpg)

But when it is deployed on ECS, things goes different. There is just one single thread running.
![4c81e1d74d3e0230134485e77f38dc7](https://user-images.githubusercontent.com/33471396/183279126-67a39097-e328-42e6-95f1-a1fea261fef1.jpg)

As I made some tests on Ecs, I found that when I requested 500m(millicores) CPU, there is one thread, and when I requested 2000m CPU, there are two threads running.

But how come it related to CPU millicores on ECS?

And what am I supposed to do to make it running on multi-threads, like 10 or more?

**Comment by simonbasle** [comment]
looks like this was asked in parallel on stackoverflow (which is what we recommend 👍) and answered there: https://stackoverflow.com/questions/73265321/reactor-flux-cant-multi-thread-when-on-ecs
