### ISSUE TITLE
Improved support for push/pull Publishers (via request callback on FluxSink?)

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#314]
Currently `Flux.create` provides support for hot publishers that are unable to respond to demand.   and simply emit events. `Flux.generate` provides support for cold publishers that respond to demand and are able to guarantee a `next()` for each `request()`.

Not all publishers fit into these two categories IMO, and there are some publishers that will be able to respond to demand (and this is preferred) but won't always have a message available to `next()` in response to this demand and may need to instead accumulate this demand until it is able to satisfy it thus has a contract whereby they emit at will up to pending demand.  I see this as a push/pull hot publisher used when the source system supports some kind of basic flow control.

One option that I and @smaldini discussed was adding a request callback to `FluxSink`, there might be other better approach, though.

`Flux.create(s -> s.onRequest(demand -> s.next(xx)) )`

Another way of supporting this might be using something similar to the following, where the consumer implementation can emit events when they become available, up to a maximum of `long` times.

`Flux.generate(BiConsumer<Long, SynchronousSink<T>> generator)`

**Comment by akarnokd** [comment]
This doesn't work. First it is still a cold Publisher, second you have to fulfill the request amount of the downstream or terminate the sequence, otherwise it will hang.

**Comment by dfeist** [comment]
@akarnokd Does it necessarily have to be implemented with 1 next() per request() contract though?

Alternatively, how do you suggest working with use cases that don't fit into the 100% cold (e.g. range) or hot (ui/socket events)?  An example is JMS:

- You can treat JMS as a hot source and use a `MessageListener`, but if events are generated faster than they are consumed, then you either have to block the (broker) listener thread, which isn't good or nack the message on back-pressure which will cause repeated redelivery and eventually the message being put on a dead letter queue is load is sustained.
- Alternatively, you can use JMS polling and pull messages from the queue when there is demand, but doing this with `Flux.generate` is not possible because there may not always be a message available when there is demand, and blocking, of course, isn't an option.

What is needed here is a publisher that can receive and accumulate demand, and has a contract whereby it can push via `next` at will, but only up to pending demand.

**Comment by akarnokd** [comment]
As far as I remember, JMS has a delivery mode that allows explicit acknowledging each message, which you can use to turn requests into acknowledgements, but not with FluxCreate.

**Comment by dfeist** [comment]
I don't see the relationship between downstream demand and JMS client acknowledgement, to be honest.  You'd want to use client acknowledgement anyway, because auto acknowledgement is only really suitable with a synchronous message listener, but it doesn't help with back-pressure as un-acknowledged message can just back up and will timeout if load is sustained.

Anyhow regardless of JMS secifics I think the use case is fairly clear. If this is provided for by FluxCreate, a new Flux factory method, is what need analysed and decided.
