### ISSUE TITLE
Supporting context-propagation ContextSnapshot restore with an operator

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#3149]
The goal of this feature request is to support `context-propagation` library, and more specifically the restoration of a `ContextSnapshot` into `ThreadLocal`s, in a more integrated fashion.

Namely, we would like to somehow wrap user-provided "functions" (or actually any functional interface required in the Flux/Mono API) so that each restores the thread locals from the Reactor `Context` (and clears after itself).

The onus can be put on the users themselves by providing some facility to perform the wrapping, or can be implicit.

## Considered Alternatives

Broad alternatives

1. explicit wrapping: a `FunctionalWrappers` instance is exposed to the user which must wrap each of her functions using said instance. one instance per `ContextView`/subscription
2. implicit wrapping within scope: define boundaries within which operators could discover a flag, instructing them to wrap any function passed as input when Subscriber is created
3. spec/builder approach: expose what looks like a subset of the `Flux` API, except it just defines a blueprint that will be applied at subscription time with additional wrapping of the user-provided functions

**Comment by simonbasle** [comment]
# Explicit approach

## Expected API
The API is close to `transformDeferredContextual`, except it doesn't expose the `ContextView` but rather a `Wrappers` instance capable of wrapping any functional type.

```java
aStringFlux.withFunctionalWrappers(
    source, wrapper -> source.map(wrapper.function(
        v -> v.length()
    ))
)
```

## Caveats
The wrapping resets thread locals the moment the function has finished. This could be hard to grasp for some users, eg. when wrapping a `Function<T, Flux<R>>` for a `flatMap`. In that case, the threadlocals wouldn't be visible at subscription time in the returned inner `Flux`, since it would be subscribed to by flatMap AFTER the function has returned.

This approach also cannot work if the "scoped" chain of operators is built by third-parties that are not aware of the `Wrappers` instance.

**Comment by simonbasle** [comment]
# Scope with Implicit Flag approach

## Where to put the Flag and how to define its range

One place is the Reactor `Context`. It then boils down to putting the flag inside context towards the "end" of the sub-chain and removing it towards the beginning.

Another idea would be to consider this flag as "Publisher-level configuration". There is currently no support for this so it implies A LOT of work, with a lot of potential caveats/blind spots.

## Expected API
We could introduce a new operator or use the `transformDeferredContextual` name, except not with a `BiFunction`:

```java
flux
    .transformDeferredContextual(f ->
        f.map(v -> v)
    );
```
The `contextual` suffix without a `Context` parameter hints at the implicit behavior. 

Another option is to have a pair of scope-bounding operators:

```java
flux
    .startScope()
    .map(v -> v)
    .endScope();
```

In both cases, if `Context`-based this would be similar to doing the following:
```java
flux
    .contextWrite(c -> c.delete(SCOPED_KEY)
    .map(v -> v)
    .contextWrite(c -> c.put(SCOPED_KEY, SOMETHING);
```

Behind the scenes, `transformDeferredContextual(Function)` is more of an alias for `transformDeferred` since it doesn't really need the context: `contextWrite` operators will take care of things.

Note that `Publisher`-level configuration would likely need similar pairing of operators as `startScope()` and `endScope()`.

## Caveats
In the `Context`-based approach:
 - cognitive dissonance: from the perspective of the user, the scope is  in order START-op1-op2-op3-END. but in reality it is reverted, more like REMOVE_FLAG-op1-op2-op3-PUT_FLAG
 - virality: like `Context`, the flag would "propagate" inside inner chains, like eg. in a `flatMap`. is that desirable? can it be reasoned about by users?
 - one needs to be careful not to blindly remove the flag towards the beginning of the scope: what if we're in a nested scope (which is possible since we don't constraint which operators can be called within the scope)?
 - with pair of operators, in addition to nesting, there's now the possibility that one uses `endScope()` but not `startScope()`. while it might seem like an innocent mistake, it is actually a big one: `endScope()` would need to be the one that actually puts the flag in the context (because it reads like it should be at the bottom of the chain, and we're using `Context` which flows backwards). this trick means that forgetting `startScope()` would make the flag active all the way up to the top of the chain


In the `Publisher`-based approach:
 - if the flag lives on _an arbitrary parent_ `Publisher`, then it _cannot_ be visible from inner publishers like eg. in a `flatMap` (which might make this easier to reason about)
 - the config flag should be inherited from the parent, or visible in the parent, which implies it is always retained until `Publisher#subscribe`
 - if as little as one operator which doesn't support exposing this flag (or its parent's flag) is injected in the chain, it can break the whole thing
 - one needs to be careful not to blindly remove the flag towards the _end_ of the scope: what if we're in a nested scope (which is possible since we don't constraint which operators can be called within the scope)?
 - forgetting the `endScope()` means the rest of the chain sees the flag, but that's rather more acceptable than when it leaks backwards

**Comment by simonbasle** [comment]
# Sub-API approach

## Expected API

```java
???
```

## Caveat

Need to come up with a signature that the type system understands rather than ending up with something that users will need to massage into the type system.

`Consumer<Spec<T, R>>` approach doesn't work because of this. the compiler can't know which pseudo-operators the user will invoke, so it cannot know in advance the output type `<R>` of the spec.

**Comment by simonbasle** [comment]
# (4) Implicit restoration support in a couple of selected operators

Focusing eg. on `tap` and `handle` could be a way to offer 0-config option.

Explored in #3180 

### Caveat
Very limited set of operators supporting this: how to communicate to the users that no, we won't add implicit support into more operators. (this is something that comes up regularly with the context-exposing variants: "can I have myFavoriteOperator overload with an exposed `ContextView`?")

**Comment by chemicL** [comment]
This has been completed with #3180 and later evolved into automatic context propagation with #3335 and following improvements.
