### ISSUE TITLE
Add an operator to compute the difference between two sorted fluxes

### ISSUE THREAD

**Issue by plcarmel** [reactor/reactor-core#3176]
Add an operator to compute the difference between two sorted fluxes, just like mergeComparingWith computes the union of two fluxes.

It could be called ``diffComparingWith``.

## Motivation
Were I work, we already have an implementation of this that computes the difference between to fluxes we don't necessarily want to iterate to the end.

I'd like to move that out of our codebase though, to make it visible in the documentation of Project Reactor.

## Desired solution
Like I said, I already have an implementation for this. It would need to be reworked to align it as much as possible with what has been done for mergeComparingWith.

I could create a PR for this if you think this is a good idea.

**Comment by simonbasle** [comment]
thanks for the suggestion @plcarmel. I'm a bit cautious about that one.
how complex is your implementation?

I don't think this is a good candidate for a reactor-core level operator, which should be generic enough that it adapts to all sorts of corner cases. my gut feeling is that a generically adaptable "diff between 2 fluxes" algorithm is going to be incredibly complex, and a heavy load to maintain vs something that is tailor-made for your use case and that use case only.

**Comment by plcarmel** [comment]
Obviously, the devil will be in the details, but right now the implementation is quite simple.

We use a prefetch of 1 when we need more data, which simplifies things a lot.

Let's say we want to compute ``f = a - b`` where ``f``, ``a`` and ``b`` are publishers, here is the algorithm:

---
**``f.subscribe(s)``**
Standard eager subscription pattern.

When ``f`` is subscribed to using subscriber ``s``
* create subscription ``su`` and call ``s.onSubscribe(su)``.
* subscribe to ``a`` and ``b`` using subscribers ``sa`` and ``sb`` and save subscriptions as ``sua`` and ``sub``.

---
**``su.request(n)``**
We simply forward the ``request(n)`` signal to ``sua``.

---
**``sa.onNext(v)``**
* Save value v in queue ``qa``.
* Call ``processQueues()``.

---
**``sb.onNext(v)``**
* Save value v in queue ``qb``.
* Call ``processQueues()``.

---
**``processQueues()``**
As long as we didn't receive a ``su.cancel()`` signal, that ``qa``is non-empty and that (``qb`` is non-empty or ``sb`` received a ``onComplete()`` signal) call ``processQueues1()``.

---
**``processQueues1()``**
* Let ``x`` be the first value of ``qa``, it can never be null.
* Let ``y`` be the first value of ``qb``, it can be null if ``sb`` received a ``onComplete()`` signal.

* if ``y`` is null or ``x`` ≤ ``y``, then it means the value is only in ``a``, or in both ``a`` and ``b`` so
  * remove the first value of ``qa`` (which is ``x``), because we wont need it anymore.

* if ``x`` ≥ ``y``, then it means ``b`` didn't caught up to ``a`` and ``y`` is a value that will be ignored, so
  * remove the first value of ``qb`` (which is ``y``), because we wont need it anymore.
  * unless ``sb`` received the ``onComplete()`` signal, send a ``sub.request(1)`` signal to replenish ``qb``.

* if ``x`` < ``y``, then send a ``su.next(x)`` signal, because the value is only in ``a``.

* if ``x`` = ``y`` and ``sa`` didn't receive a ``onComplete()`` signal, then send a ``sua.request(1)`` signal to replace the value that we threw away.

**Comment by plcarmel** [comment]
Here is our implementation:

```java
import java.util.Comparator;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.ConcurrentLinkedQueue;

import org.reactivestreams.Publisher;

import reactor.core.publisher.BaseSubscriber;
import reactor.core.publisher.FluxSink;

public class DifferenceProducer<T>
{
    private final Comparator<T> comparator;
    private final Subscriber subscriberA;
    private final Subscriber subscriberB;
    private final FluxSink<T> sink;
    private boolean isCancelled = false;

    public DifferenceProducer(Comparator<T> comparator, Publisher<T> a, Publisher<T> b, FluxSink<T> sink)
    {
        this.comparator = comparator;
        this.sink = sink;
        subscriberA = new Subscriber();
        subscriberB = new Subscriber();
        sink.onRequest(this::request);
        sink.onCancel(this::cancel);
        a.subscribe(subscriberA);
        b.subscribe(subscriberB);
    }

    private void request(long n)
    {
        if (!isCancelled)
        {
            subscriberA.request(n);
        }
    }

    private synchronized void processQueues()
    {
        while (!isCancelled)
        {
            var a = subscriberA.peek();
            var b = subscriberB.peek();
            var isAReady = a.isPresent() || subscriberA.isComplete();
            var isBReady = b.isPresent() || subscriberB.isComplete();
            if (!isAReady || !isBReady)
            {
                break;
            }
            if (a.isEmpty())
            {
                sink.complete();
                break;
            }
            else
            {
                process1(a.orElseThrow(), b);
            }
        }
    }

    private void process1(T a, Optional<T> optionalB)
    {
        var cmp = (int) optionalB.map(b -> comparator.compare(a, b)).orElse(-1);
        if (cmp <= 0)
        {
            subscriberA.pop();
        }
        if (cmp >= 0)
        {
            subscriberB.pop();
            if (!subscriberB.isComplete())
            {
                subscriberB.request(1);
            }
        }
        if (cmp < 0)
        {
            // values increase, so there is no hope of ever seeing that value again in B
            sink.next(a);
        }
        if (cmp == 0 && !subscriberA.isComplete)
        {
            // we consumed a value from "a" without producing one in return, so we need to ask for more
            subscriberA.request(1);
        }
    }

    private void cancel()
    {
        if (!isCancelled)
        {
            isCancelled = true;
            subscriberA.cancel();
            subscriberB.cancel();
        }
    }

    class Subscriber extends BaseSubscriber<T>
    {
        private final ConcurrentLinkedQueue<T> received = new ConcurrentLinkedQueue<>();

        private T last;
        private boolean isComplete;

        @Override
        protected void hookOnNext(T value)
        {
            if (last != null && comparator.compare(last, value) > 0)
            {
                throw new IllegalArgumentException("Values must be increasing");
            }
            last = value;
            if (!isCancelled)
            {
                received.offer(value);
                processQueues();
            }
        }

        @Override
        protected void hookOnComplete()
        {
            isComplete = true;
            if (!isCancelled)
            {
                processQueues();
            }
        }

        public boolean isComplete()
        {
            return isComplete;
        }

        @Override
        protected void hookOnError(Throwable throwable)
        {
            sink.error(throwable);
        }

        public Optional<T> peek()
        {
            return Optional.ofNullable(received.peek());
        }

        public void pop()
        {
            Objects.requireNonNull(received.poll());
        }
    }
}
```

**Comment by simonbasle** [comment]
thanks for providing the details @plcarmel. this could help other people with a similar use case and for whom the compromise of using a FluxSink + BaseSubscriber is acceptable.

I maintain my previous assessment that we're not ready to introduce such an operator in the core API and will close this issue for now.
