### ISSUE TITLE
allow to customize value comparison for "StepVerifier.expectNext" 

### ISSUE THREAD

**Issue by 62mkv** [reactor/reactor-core#3181]
## Motivation

Let's say we have a test suite along the following lines: 
- an object is created, one of the fields is initialized with `Instant.now()`, saved into variable `expected`
- object is persisted into db
- object is read from the db (with `r2dbc`), 
- compared with `expected` using `StepVerifier...expectNext`

Sometimes, there will be sub-millisecond discrepancy between value that is stored in variable, and value read from the db: 
```
expected value: ... accountInfoUpdated=2022-09-05T09:53:01.686645Z,    registrationDate=2022-09-05T09:53:01.686645Z
actual value:   ... accountInfoUpdated=2022-09-05T09:53:01.686644500Z, registrationDate=2022-09-05T09:53:01.686644500Z
```

For some users (like ourselves) such difference in value would not be critical. But those tests are failing and there's no easy solution for that. 

## Desired solution

`assertj` has capabilities to customize object comparison for the assertion properties, in this case one could use https://www.javadoc.io/doc/org.assertj/assertj-joda-time/latest/org/assertj/jodatime/api/LocalDateTimeAssert.html#isEqualToIgnoringMillis-org.joda.time.LocalDateTime- .

Currently, object comparison for `.expectNext()` in `StepVerifier` is *only* implemented using `Objects.equals`: https://github.com/reactor/reactor-core/blob/d15ac6f07007bcdd675dac7c0ee86e058e0a261a/reactor-test/src/main/java/reactor/test/DefaultStepVerifierBuilder.java#L511

I would like to suggest adding capability to customize object comparison (maybe, type-dependent) using `StepVerifierOptions` object. 

## Considered alternatives

1. One could manually "trim" timestamp values after retrieval before using `.expectNext()`
2. Another alternative is to use `.expectNextMatches()` (with `AssertJ` or some other assertion librarly) instead

Both of these alternatives suffer from having to re-write every impacted expectation.

**Comment by OlegDokuka** [comment]
@62mkv for not we will reject that request since as I mentioned it does not add missing functionality and has an alternative solution. We will reevaluate this if we will see more similar request.

Cheers
