### ISSUE TITLE
BlockHound flags blocking `dispose` call

### ISSUE THREAD

**Issue by nathankooij** [reactor/reactor-core#3210]
We have a test involving a `Flux#bufferTimeout` which in certain scenarios can result in BlockHound flagging the internal [dispose call of the timer](https://github.com/reactor/reactor-core/blob/0d40eb127b5a062cdfacd6c5fd2d4874d694309e/reactor-core/src/main/java/reactor/core/publisher/FluxBufferTimeout.java#L275) used by that operator (when the batch size limit of the operator is hit). This can happen when the created worker is backed by a thread which is not the same thread as the one calling `dispose` as a lock to the backing work queue (to remove the task) might need to be acquired when the [`ScheduledFutureTask` is cancelled](https://github.com/reactor/reactor-core/blob/0d40eb127b5a062cdfacd6c5fd2d4874d694309e/reactor-core/src/main/java/reactor/core/scheduler/WorkerTask.java#L150). It's acquiring this lock that sometimes might result in a blocking call, when it's already owned by the backing thread because e.g. it's waiting/picking up a new task.

Also happy to open a PR for this. :)

## Expected Behavior

The BlockHound integration should have an explicit exclusion for `WorkerTask#dispose` like how there already exists one for `SchedulerTask#dispose`, and thus should not flag this case at all.

## Actual Behavior

BlockHound flags the blocking call, which results in an uncaught exception in the scheduler.

## Steps to Reproduce

This test is similar to the one already provided in `ReactorBlockHoundIntegrationTest#shouldNotReportScheduledFutureTask`. However, that one is no longer functioning since `RaceTestUtils#race` defaults to the bounded elastic scheduler now on which blocking is allowed. Thus, I explicitly schedule on the parallel scheduler. Moreover, since it's not actually a race condition between `dispose` calls, I've also tweaked the scheduling of the worker to be at millisecond intervals. This increases the likelihood that a worker is picking up a task (and thus holds the lock) when `dispose` is issued.

```java
	@Test
	public void shouldNotReportWorkerScheduledFutureTask() {
		for (int i = 0; i < 1_000; i++) {
			Scheduler scheduler = Schedulers.newSingle("foo");
			Scheduler.Worker worker = scheduler.createWorker();

			try {
				Runnable dummyRunnable = () -> {
				};

				for (int j = 0; j < 257; j++) {
					worker.schedule(dummyRunnable, j + 1, TimeUnit.MILLISECONDS);
				}
				Disposable disposable = worker.schedule(dummyRunnable, 1, TimeUnit.SECONDS);

				RaceTestUtils.race(Schedulers.parallel(), disposable::dispose);
			}
			finally {
				worker.dispose();
				scheduler.dispose();
			}
		}
	}
```

## Possible Solution

```diff
diff --git a/reactor-core/src/main/java/reactor/core/scheduler/ReactorBlockHoundIntegration.java b/reactor-core/src/main/java/reactor/core/scheduler/ReactorBlockHoundIntegration.java
index 2c253e2b2..7f068445e 100644
--- a/reactor-core/src/main/java/reactor/core/scheduler/ReactorBlockHoundIntegration.java
+++ b/reactor-core/src/main/java/reactor/core/scheduler/ReactorBlockHoundIntegration.java
@@ -42,6 +42,7 @@ public final class ReactorBlockHoundIntegration implements BlockHoundIntegration
 
         // Calls ScheduledFutureTask#cancel that may short park in DelayedWorkQueue#remove for getting a lock
         builder.allowBlockingCallsInside(SchedulerTask.class.getName(), "dispose");
+        builder.allowBlockingCallsInside(WorkerTask.class.getName(), "dispose");
 
         builder.allowBlockingCallsInside(ThreadPoolExecutor.class.getName(), "processWorkerExit");
     }
```

## Your Environment

* Reactor version(s) used: reproduced this on `main` (`3.5.0-SNAPSHOT`), but originally tracked this down in `3.4.23`.
* Other relevant libraries versions (eg. `netty`, ...): N/A
* JVM version (`java -version`):
To reproduce in `reactor-core`:
```
openjdk version "11.0.15" 2022-04-19 LTS
OpenJDK Runtime Environment Microsoft-33279 (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM Microsoft-33279 (build 11.0.15+10-LTS, mixed mode)
```

Originally:
```
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)
```
* OS and version (eg `uname -a`):
`Darwin MacBook-Pro-5.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64`

**Comment by simonbasle** [comment]
Happy to accept a PR for the suggested exclusion 👍 do target the `3.4.x` branch please.

**Comment by nathankooij** [comment]
> Happy to accept a PR for the suggested exclusion 👍 do target the `3.4.x` branch please.

Alright, expect a PR soon. 👍

**Comment by chemicL** [comment]
Thank you for the contribution @nathankooij 🚀
