### ISSUE TITLE
`MonoSubscriber` based source cause performance degradation with `GroupedFlux` in case of fusion

### ISSUE THREAD

**Issue by PMacho** [reactor/reactor-core#3239]
## Expected Behavior

Side-effects are expected to decrease performance.

## Actual Behavior

I've however spottet a case where adding a side-effect repeatably increases performance by a factor of three.

## Steps to Reproduce

```java
@Test
void groupByFluxAggregateLoadTest() {
    int numberOfGroups = 30_000;
    Flux
            .range(0, numberOfGroups * 10)
            .groupBy(i -> i % numberOfGroups)
            .flatMap(
                integerIntegerGroupedFlux -> integerIntegerGroupedFlux
                    .count()
                    //.doOnNext(n -> {})
                ,
                numberOfGroups + 1
            )
            .as(StepVerifier::create)
            .expectNextCount(numberOfGroups)
            .verifyComplete();
}
```

## Possible Solution

Was guessing that might be due to altered requesting behaviour?!

## Your Environment

Same with Windows on Intel server chips and MacOS on ARM (M1).

* Reactor version(s) used: 3.4.24
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): Oracle 17.4
* OS and version (eg `uname -a`): Windows 11 on Intel server chips, MacOS 12.6 on ARM (M1)

**Comment by UgiR** [comment]
I am able to reproduce this as well (using `.hide()` instead of `.doOnNext(a -> {})` works as well)

**Comment by OlegDokuka** [comment]
@PMacho @UgiR do you mind adding a JMH test that demonstrates the mentioned performance outcome?

**Comment by UgiR** [comment]
It's rather rough, but just throwing the example snippet in JMH (and reducing # of groups), I get this:

Without `.hide()`:
```
# Warmup Iteration   1: 3.823 ops/s
# Warmup Iteration   2: 4.086 ops/s
# Warmup Iteration   3: 4.077 ops/s
# Warmup Iteration   4: 4.097 ops/s
# Warmup Iteration   5: 4.119 ops/s
Iteration   1: 4.052 ops/s
Iteration   2: 4.041 ops/s
Iteration   3: 4.111 ops/s
Iteration   4: 4.110 ops/s
Iteration   5: 4.118 ops/s
```

With `.hide()`:
```
# Warmup Iteration   1: 12.840 ops/s
# Warmup Iteration   2: 14.120 ops/s
# Warmup Iteration   3: 14.049 ops/s
# Warmup Iteration   4: 14.019 ops/s
# Warmup Iteration   5: 13.483 ops/s
Iteration   1: 13.947 ops/s
Iteration   2: 13.818 ops/s
Iteration   3: 14.137 ops/s
Iteration   4: 14.168 ops/s
Iteration   5: 14.207 ops/s

# Run progress: 20.00% complete, ETA 00:06:46
# Fork: 2 of 5
# Warmup Iteration   1: 
```

Test:

```
    @Benchmark
    public void test() {
        int numberOfGroups = 3_000;
        Flux.range(0, numberOfGroups * 10)
            .groupBy(i -> i % numberOfGroups)
            .flatMap(
                integerIntegerGroupedFlux -> integerIntegerGroupedFlux
                    .count()
                    .hide()
                ,
                numberOfGroups + 1
            )
            .as(StepVerifier::create)
            .expectNextCount(numberOfGroups)
            .verifyComplete();
    }
```

**Comment by OlegDokuka** [comment]
oh... `count()`.... then it is clear where the overhead comes from... @UgiR can you check the same with 3.5.0 snapshot or RC1?

**Comment by UgiR** [comment]
3.5.0-M6 was the most readily available to me given that I am not on a personal machine, but seems like the relevant change is in there as well, because performance now seems in line:

w/o `hide()`
```
# Warmup Iteration   1: 11.893 ops/s
# Warmup Iteration   2: 13.981 ops/s
# Warmup Iteration   3: 14.276 ops/s
# Warmup Iteration   4: 14.189 ops/s
# Warmup Iteration   5: 14.208 ops/s
Iteration   1: 14.187 ops/s
Iteration   2: 13.594 ops/s
Iteration   3: 14.257 ops/s
Iteration   4: 14.283 ops/s
Iteration   5: 14.206 ops/s
```

w/ `hide()`
```
# Warmup Iteration   1: 13.433 ops/s
# Warmup Iteration   2: 14.397 ops/s
# Warmup Iteration   3: 13.972 ops/s
# Warmup Iteration   4: 14.255 ops/s
# Warmup Iteration   5: 14.206 ops/s
Iteration   1: 14.153 ops/s
Iteration   2: 14.338 ops/s
Iteration   3: 14.230 ops/s
Iteration   4: 12.090 ops/s
Iteration   5: 14.403 ops/s
```

**Comment by OlegDokuka** [comment]
@UgiR @PMacho i know where the issue comes from. It is `Operators.MonoSubscriber` (used as a bade class for `MonoCount`) which in case of fusion introduces extra volatile read write (hence significant overhead for simple sync scenario). 

As it can be noticed, it is already fixed 🤣 (in 3.5). Although we can consider disabling fusion in 3.4 as well since it brings overhead

cc \@simonbasle @chemicL

**Comment by PMacho** [comment]
> @PMacho @UgiR do you mind adding a JMH test (_unfortunately ordinary unit tests can not be representative_) that demonstrates the mentioned performance outcome?

Sorry, for returning late. Thanks @UgiR  for your work.

**Comment by OlegDokuka** [comment]
@PMacho @UgiR feel free to contribute if you have spare time. The contribution should be disabling fusion inside the `MonoSubscriber` class. That is going to be the low-hanging fruit for 3.4.x
