### ISSUE TITLE
Improve ExecutorScheduler REJECTED handling

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#324]
It seems we cannot guarantee an ExecutorScheduler won't hang, especially when the REJECTED task happens in `request` (in which we cannot throw a `RejectedExecutionException`).
Unlike ExecutorServiceScheduler the executor doesn't expose state that would allow us to perform the rejection...
If we cannot find a working solution, we could consider removing the `ExecutorScheduler` altogether.

**Comment by smaldini** [comment]
We should try to fix it first since we have little use but might present some advantage like quick execution path conversion to Scheduler `Scheduler.fromExecutor(r -> r.run())`
