### ISSUE TITLE
Deep review and rework of build infrastructure

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#325]
- [x] Make sure which tests (spock, testng/tck, junit "classic" vs "loops") run at which step (PR, snapshot, milestone...)
 - [x] Review the gradle test tasks and how they are rewritten in the build.gradle
 - Review all `.gradle` files. Notably `setup.gradle` doesn't add the `Implementation-Version` where it should (see #316)
 - Maybe add a nightly bamboo build that will run all tests

**Comment by smaldini** [comment]
Probably worth tracking any discussed investigation on build pipeline along this this @rajinisivaram

**Comment by smaldini** [comment]
Need to precise this issue for any CI change on a different detailed issue if necessary
