### ISSUE TITLE
Flux.create not repeating last value

### ISSUE THREAD

**Issue by PeterJakubik** [reactor/reactor-core#3255]
Hello
I'm using `Flux.create` to emit values from a different thread. 
I want that the last emitted value is repeated 5 times with 1 second delay.

This doesn't seem to work with chaining `Flux.create` with `repeat` and `delay`

## Expected Behavior
The `repeat` operator should be able to repeat emitted values from `Flux.create`

## Steps to Reproduce
```java
        interface EventListener<T> {
            void onData(T t);
        }

        class EventProcessor<T> {
            List<EventListener<T>> listeners = new ArrayList<>();

            void register(EventListener<T> listener) {
                listeners.add(listener);
            }

            void notify(T value) {
                listeners.forEach(l -> l.onData(value));
            }
        }

        EventProcessor<String> stringProcessor = new EventProcessor<>();

        Flux<String> dynFLux = Flux.create((FluxSink<String> sink) -> stringProcessor.register(new EventListener<String>() {
            @Override
            public void onData(String s) {
                sink.next(s);
            }
        }));


        Flux<String> fi = dynFLux.repeat(5).delayElements(Duration.ofSeconds(1));

        fi.subscribe(val -> System.out.println(val));

        stringProcessor.notify("hi");

      // Error: The console prints just "hi" once, instead of 5x with 1s delay
```

* Reactor version(s) used: reactor-core-3.4.19

**Comment by chemicL** [comment]
The `repeat` operator re-subscribes to the original `Flux` upon receiving the completion signal, it does not repeat each `onNext` signal. Probably you are thinking about the following:

    Flux<String> fi = dynFLux.concatMap(i -> Mono.just(i).repeat(5)).delayElements(Duration.ofSeconds(1));
    
Keep in mind that there is no re-subscription possible with the provided logic, as the sink never receives a completion signal. The `Mono` on the other hand will complete after each item, allowing the actual repetition of the elements in your target `Flux`.
