### ISSUE TITLE
WebClient keeps on accepting delayed response even in the presence of timeout

### ISSUE THREAD

**Issue by noorulhaq** [reactor/reactor-core#326]
Hi,

I am trying to learn reactor project by developing a sample application. Below is the code snippet from the sample application.

```
public Mono<Quotation> findBestQuotation(Double loanAmount){

        return  Flux.range(1,9)
                .map(bankIndex -> "bank-"+bankIndex)
                .flatMap(bank -> requestForQuotation(bank, loanAmount)) // Scatter
                .collectList() // Gather
                .flatMap(quotations -> selectBestQuotation(quotations)).next();
    }
```

```
    private Mono<Quotation> selectBestQuotation(List<Quotation> quotations){
        return Flux.fromIterable(quotations).sort((q1, q2) -> (q1.getOffer() > q2.getOffer()) ? 1:-1).next();
    }
```

```
public  Mono<Quotation> requestForQuotation(String bank, Double loanAmount) {

        ClientRequest<Void> request = ClientRequest.GET("http://localhost:8091/{bank}/quotation?loanAmount={amount}", bank, loanAmount)
                .accept(MediaType.APPLICATION_JSON)
                .build();

        Mono<Quotation> offer = WEB_CLIENT
                .exchange(request)
                .then(response -> response.bodyToMono(Quotation.class))
                .timeout(Duration.ofMillis(500)) // Response should come back within 500ms
                .otherwiseReturn(new Quotation("Pseudo-offer-from-"+bank,loanAmount)); // Fallback strategy

        return offer;
    }
```

    
**Scenario** 

What I am doing in above code snippet is I am requesting for loan quotations form multiple banks at "Scatter" phase then I am selecting the best quotation after "Gather" phase.

**Problem** 

I have deliberately added 4 sec delay in the bank service against one bank. The problem which I am facing here is that WebClient kept on accepting the delayed response from the bank service even though I have mentioned timeout of 500ms for expected response.  

This behavior is causing the problem in subsequent loan request because the response of former request is being received in the later loan request.

Any clue is much appreciated.

**Comment by smaldini** [comment]
Should this issue be opened first on https://github.com/spring-projects/spring-framework ? From a reactor perspective we could start investigating with a `.log()` operator given that you have SLF4J or Java Logging in debug mode. Placing it just before timeout should show up if cancel where propagated here, also placing it after bodyToFlux should show if cancel was also propagated here.
It could also be a netty issue, make sure it runs on reactor 3.0.4 and reactor-netty 0.6.

**Comment by simonbasle** [comment]
@noorulhaq have you been able to investigate with the above hints? did you get to the root cause, or at least exchanged with the spring team to see if this was the best way of achieving your goal with the `WebClient`?

**Comment by noorulhaq** [comment]
Sorry for not replying on this thread. Honestly speaking, I don't know how this problem automatically got solved. Probably, I upgraded the version to verify the issue. Anyhow, I enjoyed reactor and wrote an excellent [article](https://dzone.com/articles/functional-amp-reactive-spring-along-with-netflix) on it, with some experiment with Netflix OSS stack and Hystrix enabled WebClient. One slight problem that I faced with WebClient was related to setting readtimeout on the WebClient. Which I still do not know how to achieve that.

**Comment by smaldini** [comment]
@noorulhaq we are looking at this API on reactor-netty but I don't think there's an explicit timeout in WebClient. however nothing prevents you to use Flux/Mono#timeout 🗡

**Comment by simonbasle** [comment]
Just an unrelated remark: in your use case you could avoid the "gather to list" and final "find best quotation in list" steps, by combining them into a `reduce`:

```
//instead of .collectList(...).flatMap(...), do this:
.reduce((prev, current) -> prev.getOffer() > current.getOffer() ? current : prev)
```

**Comment by noorulhaq** [comment]
@simonbasle thanks for reading the article and sharing your thoughts. You are right, but I intentionally did that to see all quotations along with the best quotation in response. I should have mentioned this also there. 
One more point that I forgot to share is that I wanted to handle backpressure between the bank and loan broker. Can you please suggest how can it be possible through HTTP integration?

**Comment by noorulhaq** [comment]
@smaldini, that is what I did eventually. One unrelated question; what was actual need of creating WebSlient when we already had AsyncRestTemplate in spring and it can also be configured with Netty4ClientHttpRequestFactory.

**Comment by simonbasle** [comment]
@noorulhaq did it end up working with the `timeout` operator from reactor, in the end?

About backpressure, this isn't a scenario where it makes much sense IMO, as you are collecting and sorting multiple results, so you need the whole list anyway. And these HTTP requests are one-shot operations, so they won't benefit much from backpressure either...

**Comment by noorulhaq** [comment]
Yes, it worked eventually.
