### ISSUE TITLE
Mono.fromRunnable() should return a Mono<Void> instead of Mono<T>

### ISSUE THREAD

**Issue by yamass** [reactor/reactor-core#3269]
From the source code:
```java
public static <T> Mono<T> fromRunnable(Runnable runnable) {
	return onAssembly(new MonoRunnable<>(runnable));
}
```
There is no way that `fromRunnable()` ever returns anything else than a `Mono<Void>`, since Runnable does not have a return type. 

The unnecessary generic parameter make it necessary to specify `Void` explicitly when using `fromRunnable()`:

```java
// does NOT compile
Mono<Void> doStuff() {
	return Mono.fromRunnable(() -> {
		// ...
	})
	.subscribeOn(Schedulers.boundedElastic());
}

// does compile
Mono<Void> doStuff2() {
	return Mono.<Void>fromRunnable(() -> {
		// ...
	})
	.subscribeOn(Schedulers.boundedElastic());
}
```

## Expected Behavior
returns `Mono<Void>`

## Actual Behavior
returns `Mono<T>`

## Steps to Reproduce
see examples

## Possible Solution
Make it return Mono<Void>

## Your Environment
* Reactor version(s) used: 3.4.24

**Comment by simonbasle** [comment]
This is an early intention to make such "empty" Monos more composable in complex chains that do have a non-Void type, the same way `Mono.empty()` and `Mono.never()` also are typed. It is less wasteful to assign an (erased) generic type than to force a lot of usages to go through a `cast(T)` operator just for the sake of it, and the fact that it is generified precisely allows the `Mono.<Void>fromRunnable` escape hatch in your case.

Note that the Java type system has also a good handle of this other alternative:
```java
	Mono<Void> doStuff() {
		Mono<Void> runnable = Mono.fromRunnable(() -> {
			// ...
		});
		return runnable.subscribeOn(Schedulers.boundedElastic());
	}
```
