### ISSUE TITLE
Javadoc jar is released with BUILD-SNAPSHOT version

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#327]
See the `3.0.4` javadoc jar, eg [here](http://repo.spring.io/release/io/projectreactor/reactor-core/3.0.4.RELEASE/reactor-core-3.0.4.RELEASE-javadoc.jar!/index.html)

**Comment by smaldini** [comment]
Should be fixed now, its also correctly mentioned in release checklist and should be in sync via https://github.com/reactor/reactor-core/commit/5fcb69f83041cdb01b707fd9f96e59872492de06#diff-37a9ffb42254f2688f3936b054f705a9R25.
