### ISSUE TITLE
Downstream operators override upstream prefetch value

### ISSUE THREAD

**Issue by kushagraThapar** [reactor/reactor-core#3275]
I am not sure if this is a bug or not, but what I have observed is that downstream operators override prefetch values set in any upstream operators causing them to effectively request high number of records from upstream (sometimes default is 32, sometimes it is 256). What's interesting is that this happens even when I convert this Flux to a lazy iterable and iterate on it using next methods. (which are supposed to be blocking on `next()` calls)

Business use case - we run queries against distributed system and fetch data from different machines at once. Based on the number of machines to reach to, and the number of processors on the client side, the query logic calculates concurrency and prefetch values for operators like `Flux.generate`, `Flux.flatMapSequential`, and `Flux.mergeSequential`. Downstream operators are not aware of this query logic and work independently of it. However, when any downstream operator is applied like `flatMap()`, it requests by default 256 values, causing the `Flux.generate` operator to produce 256 values even if it has a prefetch value of 1.  

## Expected Behavior
I would expect a way to avoid downstream operators override prefetch values in upstream operators. And in case of `toIterable()`, I would expect Flux to honor back-pressure through `iterator.next()` calls through prefetch value and only generate values that are consumed by downstream operators. 

## Actual Behavior
It prefetches and drains all the results which haven't been consumed yet through `iterator.next()` 

## Steps to Reproduce
Run `main` method on any of the below classes to reproduce the issue. 

https://github.com/kushagraThapar/reactor-core-test/blob/master/src/main/java/com/example/FluxPrefetchSample.java

https://github.com/kushagraThapar/reactor-core-test/blob/master/src/main/java/com/example/FluxOfFluxGeneratePrefetchSample.java

```java
private static final Logger logger = LoggerFactory.getLogger(FluxPrefetchSample.class);

    public static void main(String[] args) throws InterruptedException {
        Set<Flux<Integer>> generatedFlux = Collections.singleton(getGeneratedFlux());
        Flux<Integer> mergedFlux = Flux.mergeSequential(generatedFlux, 1, 1).log()
                                       .map(integer -> integer).log()
                                       .flatMap(Flux::just).log();
        Iterator<Integer> iterator = mergedFlux.toIterable(1).iterator();
        if (iterator.hasNext()) {
            logger.info("Next is : {}", iterator.next());
        }
        Thread.sleep(5 * 1000);
    }

    private static Flux<Integer> getGeneratedFlux() {
        return Flux.generate(State::new, (State state, SynchronousSink<Integer> sink) -> {
            if (state.get() < 10) {
                sink.next(state.get());
                logger.info("Generating next page");
                state.increment();
            } else {
                sink.complete();
            }
            return state;
        });
    }

    static class State {
        private final AtomicInteger integer;

        public State() {
            integer = new AtomicInteger();
        }

        public int get() {
            return integer.get();
        }

        public void increment() {
            integer.incrementAndGet();
        }
    }
```

## Your Environment

* Reactor version(s) used: LATEST

**Comment by OlegDokuka** [comment]
@kushagraThapar what you observe is expected. Every operator likes flatMap / concatMap / switchMap / groupBy / window / buffer / (others where the input parameter is `prefetch` will do extra demand from the upstream regardless of your downstream. To configure their behavior you need to also configure them to prefetch exactly 1 element. 

e.g.

```java
Set<Flux<Integer>> generatedFlux = Collections.singleton(getGeneratedFlux());
        Flux<Integer> mergedFlux = Flux.mergeSequential(generatedFlux, 1, 1).log()
                                       .map(integer -> integer).log()
                                       .flatMap(Flux::just, 1, 1).log();
        Iterator<Integer> iterator = mergedFlux.toIterable(1).iterator();
        if (iterator.hasNext()) {
            logger.info("Next is : {}", iterator.next());
        }
        Thread.sleep(5 * 1000);
```
