### ISSUE TITLE
No way to meter Schedulers used internally by Reactor

### ISSUE THREAD

**Issue by kkocel** [reactor/reactor-core#3285]
Either I'm missing something or by deprecating `Schedulers.enableMetrics()` there is a regression in functionality.

When I played with https://github.com/reactor/reactor-monitoring-demo I noticed that it was possible to meter Schedulers that were used internally by Reactor eg:

```java
	public static Flux<Long> interval(Duration period) {
		return interval(period, Schedulers.parallel());
	}
```

or `boundedElastic` Scheduler that was used to handle incoming requests from netty.

Currently, there is no way to get metrics for such schedulers because I cannot wrap them in `TimedScheduler`.

**Comment by OlegDokuka** [comment]
what we need to do here, we need to port `SchedulerMetricDecorator` to the new metrics module. @kkocel feel free to contribute

**Comment by simonbasle** [comment]
even though @kkocel [question on StackOverflow](https://stackoverflow.com/q/74461502/1113486) is Spring Boot-oriented, the `Factory` described in [my answer](https://stackoverflow.com/a/74461554/1113486) is pure Reactor code, so it could be used directly with `Schedulers.setFactory(...)`.

**Comment by kkocel** [comment]
Maybe utilized version of this factory could be part of monitoring module WDYT @simonbasle  ?

**Comment by kkocel** [comment]
I've just learned that netty and micrometer have built-in metrics support- https://projectreactor.io/docs/netty/release/reference/index.html#_metrics
This will be a more comprehensive solution than adding metrics to each Scheduler.
