### ISSUE TITLE
FluxIterable may call iterator twice, that may break constrainOnce contract of Kotlin Sequence

### ISSUE THREAD

**Issue by mcoolive** [reactor/reactor-core#3295]
FluxIterable may call `iterator` method twice. I don't think it is forbidden, but it seams a poor practice because of performance and/or possible side effects. Use with Kotlin Sequence, it may cause an IllegalStateException: This sequence can be consumed only once.

## Expected Behavior

The following code throws an IllegalStateException. I expect the flux is consumed without any exception.

    listOf('1', '2', '3').iterator().asSequence().toFlux().blockLast()

## Actual Behavior

Now, an  IllegalStateException is thrown with the message: "This sequence can be consumed only once".

## Steps to Reproduce
This Kotlin code fails systematically with an exception: `IllegalStateException: This sequence can be consumed only once`.

```java
@Test
void reproCase() {
    // This should not throw exception. But it does...
    listOf('1', '2', '3').iterator().asSequence().toFlux().blockLast()
}
```

In my understanding Kotlin asSequence extension puts a constrainOnce contract:

    public fun <T> Iterator<T>.asSequence(): Sequence<T> = Sequence { this }.constrainOnce()

In FluxExtensions.kt, we have:

    fun <T : Any> Sequence<T>.toFlux(): Flux<T> = Flux.fromIterable(object : Iterable<T> {
        override fun iterator(): Iterator<T> = this@toFlux.iterator()
    })

And in FluxIterable, we have:

    static <T> boolean checkFinite(Iterable<T> iterable) {
        return iterable instanceof Collection || iterable.spliterator().hasCharacteristics(Spliterator.SIZED);
    }
    public void subscribe(/* ... */) {
        /* ... */
        knownToBeFinite = FluxIterable.checkFinite(iterable);
        it = iterable.iterator();
        /* ... */
    }

Moreover, Kotlin `Sequence` does not overload the default implementation of `spliterator()`, that's why `iterator` method is called twice in my case. So the constrainOnce is broken.

## Possible Solution

I think `FluxIterable` should call the `iterator` method only once. A possible solution is to always build a `Spliterator` to both iterate and test `Characteristics`.

If you prefer to keep `FluxIterable` unchanged, then I suggest to change the implementation of `Sequence<T>.toFlux()` extension, to rely on `Flux.fromStream` instead of `Flux.fromIterable`.

## Your Environment

* Reactor version(s) used: 3.4.6 or 3.5.0
* Other relevant libraries versions (eg. `netty`, ...): Kotlin-extension 1.1.8 or 1.2.0
* JVM version (`java -version`): Java 8 or 11.

**Comment by OlegDokuka** [comment]
I'm not sure we can guarantee `constrainOnce` since the same flux can be subscribed twice, but we definitely can improve the mentioned code

**Comment by chemicL** [comment]
This issue has been raised in the past: #3297 BTW (linking)
