### ISSUE TITLE
Is there a commitment to ensure that `MicrometerMeterListenerFactory` is reusable/cacheable?

### ISSUE THREAD

**Issue by JamesChenX** [reactor/reactor-core#3299]
## Documentation Issue

The return value `MicrometerMeterListenerFactory` of `reactor.core.observability.micrometer.Micrometer#metrics` seems reusable or cacheable, meaning it can be used for multiple `Flux` or `Mono` instances.

But there is no commitment on docs saying it's always reusable or not.

## Improvement Suggestion

The documentation should better mention `MicrometerMeterListenerFactory` is reusable or not.

## Additional context

reactor-core-micrometer:v1.0.0

**Comment by chemicL** [comment]
@JamesChenX I'm going over the backlog of issues and wanted to follow up on your suggestion. While it might seem justified to document the potential for reuse, it also might be limiting for the future evolution of this API. The reuse might also be limited, having in mind the fact that the factory is parameterized with type `T` allowing for smooth fluent API chaining which maintains the type of the upstream `Flux`/`Mono`. What are you looking for? Is it a performance gain of not allocating an object every time you assemble the chain? I wonder if there are demonstrable gains in such a case. If you're still interested in this aspect do let us know your thoughts on the above.
