### ISSUE TITLE
Add method to transform Mono<T> into Mono<Optional<T>>

### ISSUE THREAD

**Issue by AndreasHuber-CH** [reactor/reactor-core#3311]
Hi,
When using Mono.zip() function to combine multiple Monos together, I find myself sometimes in need of making sure that some Mono<T> always completes with a value to make sure that the zip emits a value even if one of the input Monos doesn't.

This can be done relatively easily by transforming a Mono<T> into an Mono<Optional<T>> by combining `map(Optional::of)` and `defaultIfEmpty(Optional.empty())`.

While this code is pretty easy to write, I was wondering whether this would merit a dedicated method in the Mono class.
For example:
```
public Mono<Optional<T>> toOptional() {
    return this.map(Optional::of).defaultIfEmpty(Optional.empty());
}
```
Or maybe there would be a slightly smarter implementation to achieve that.

For Flux we already get this kind of behavior from the `Flux.collectList()` method that returns a `Mono<List<T>>` which always emits 1 value of a possibly empty list. So having a similar method in Mono that guarantees to always emit a possibly empty Optional looks useful to me.
Or is there some other approach that I missed?

I saw I could also use `Mono.materialize()` to achieve something similar, but this would also transform errors into signals which is not what I want.

**Comment by chemicL** [comment]
Sounds good. Please focus on the `Mono` operator and don't add it to `Flux` just yet.

If there is demand we can discuss it, but one might argue `Flux` has other ways for dealing with the situations appropriate for 0-N types of streams, e.g. `collectList` that you mentioned. Also, `Flux` has a `single(defaultValue)` which can be used in combination with `map`: `map(Optional::of).single(Optional.empty())` (or `.singleOrEmpty()` which can then leverage the operator we decided to add), which in case of actual streams with some values might not be the dominating factor to have this chain of operations when used in the `zip` operator that you describe.

**Comment by He-Pin** [comment]
Then maybe we need another one too convert back, like `flattenOptional`

**Comment by AndreasHuber-CH** [comment]
Hm, so you think if `map(Optional::of).single(Optional.empty())` isn't short enough and worth an operator `.flatMap(Mono::justOrEmpty)` needs one as well? To me doing one flatMap calls seems just easy enough, and I think it should already be pretty optimized because Mono.just() and Mono.emtpy() are `Fuseable.ScalarCallable`, right?
