### ISSUE TITLE
Empty Flux never completes when subscribed

### ISSUE THREAD

**Issue by alif2** [reactor/reactor-core#3320]
When I return an empty Flux, either through `ReactiveCrudRepository.saveAll(list)` where list is empty, or by directly returning `Flux.empty()`, the Flux never completes when it is subscribed to and hangs indefinitely.

## Expected Behavior

The Flux should complete while emitting 0 items.

## Actual Behavior

The Flux never completes.

## Steps to Reproduce

```java
@RestController
public class Controller {
public Mono<ServerResponse> saveItem() {
    return save.collectList().flatMap(s -> {
        if(s.isEmpty()) return ServerResponse.notFound.build();
        return ServerResponse.ok().body(BodyInserters.fromValue(s));
    })
    .switchIfEmpty(ServerResponse.ok.build());    
}

@Service
public class Service {
public Flux<Entity> save() {
    List<Entity> entities = new ArrayList<Entity>();
    if(entities.isEmpty()) {
        return Flux.empty();
    }
}
```

## Your Environment

* Reactor version(s) used: 3.5
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): openjdk version "17.0.4.1" 2022-08-12
* OS and version (eg `uname -a`): Windows 11

**Comment by OlegDokuka** [comment]
@alif2 your example is invalid. I tried to reproduce what you showed with pure reactor and it works fine for me 


```java


public class Controller {

	@Test
	public void saveItem() {
		Flux.empty()
		    .collectList()
		    .flatMap(s -> {
			    if (s.isEmpty()) {
				    return Mono.just("ServerResponse.notFound.build()");
			    }
			    return Mono.just("ServerResponse.ok().body(BodyInserters.fromValue(s))");
		    })
		    .switchIfEmpty(Mono.just("ServerResponse.ok.build()"))
		    .as(StepVerifier::create)
		    .expectNextCount(1)
		    .expectComplete()
		    .verify();
	}

}

```
