### ISSUE TITLE
Online reference documentation inaccessible [404 error]

### ISSUE THREAD

**Issue by alexismanin** [reactor/reactor-core#3330]
Hi,

This morning, (2023-01-13T08:28+01:00), the reference documentation is inaccessible:

1. Go to the main website: https://projectreactor.io/
2. Click on "Documentation" menu
3. Click on Reactor Core -> Reference -> release link
4. A Spring 404 error page appear.

Regards,

**Comment by alexismanin** [comment]
After a few more test, it appears that snapshot links work, both for java doc and reference. But "release" links looks broken, whatever section I choose (reactor-test, reactor-netty, etc.)

**Comment by violetagg** [comment]
@alexismanin Can you try now? It is related to https://github.com/reactor/projectreactor.io/issues/109

**Comment by alexismanin** [comment]
I confirm that it works now. Thank you !
