### ISSUE TITLE
Add method to transform Mono<Optional<T>> into Mono<T>

### ISSUE THREAD

**Issue by wenhaozhao** [reactor/reactor-core#3341]
Hi,

When flatten Mono<Optional<T>>, we must test non-null and then map Optional<T> to T, like:
```
Mono.just(Optional.empty()).filter(optional->optional.isPresent()).map(optional->optional.get());
```

This can be done relatively easily by transforming a Mono<Optional<T>> into an Mono<T> like mapOptional operator in RxJava.

Or just add a new operator mapOptional to Mono, like:

```
public Mono<Optional<T>> mapOptional() {
    return this.filter(optional->optional.isPresent()).map(optional->optional.get());
}

```

While this code is pretty easy to write, I was wondering whether this would merit a dedicated method in the Mono class.

Or maybe there would be a slightly smarter implementation to achieve that.

**Comment by OlegDokuka** [comment]
Hi, @wenhaozhao!

There is mapNotNull which can solve your problem:

```java
Mono.just(Optional.empty()).mapNotNull(optional->optional.get());
```
