### ISSUE TITLE
Micrometer + observation / tracing: IllegalStateException "Trying to close scope for span"

### ISSUE THREAD

**Issue by MartinHeyer** [reactor/reactor-core#3354]
_Might be resolved by reactor-core:3.5.3 (not yet released; already using the latest sub artifacts)
Might be related to https://github.com/reactor/reactor-core/issues/3350_

Context propagation / restoration of micrometer thread locals seems to get mixed up. The following test will raise an IllegalStateException. Traces reported to grafana/tempo have a wrong parent-child relationship.

## Expected Behavior
The following test should run successfully. Calling contextCapture() + handle() {} should not lead to corruption of micrometer thread locals.

## Actual Behavior
An IllegalStateException is thrown.
Traces reported to Grafana/Tempo show a wrong parent-child relationship.

## Steps to Reproduce
```kotlin
    @Test
    fun test() {
        val registry = TestObservationRegistry.create().also {
            it.observationConfig().observationHandler(DefaultTracingObservationHandler(SimpleTracer()))
        }

        val myFlux = Mono.just(1)
            .handle { item, sink ->
                sink.next(item)
            }

        val obs0 = Observation.createNotStarted("observation-0", registry)
        val obs1 = Observation.createNotStarted("observation-1", registry)

        obs0.observe {
            obs1.observe {
                myFlux
                    .contextCapture()
                    .block()
            }
        }
    }
```

## Your Environment
    openjdk 17
    implementation("io.micrometer:micrometer-observation:1.10.4")
    implementation("io.micrometer:context-propagation:1.0.2")
    implementation("io.micrometer:micrometer-core:1.10.4")
    testImplementation("io.micrometer:micrometer-test:1.10.4")
    testImplementation("io.micrometer:micrometer-observation-test:1.10.4")
    testImplementation("io.micrometer:micrometer-tracing-test:1.0.1")

**Comment by chemicL** [comment]
Please try with

    testImplementation("io.micrometer:micrometer-tracing-test:1.0.2")

as there was a bug that just got fixed today. Does it help?

**Comment by chemicL** [comment]
I ran the following (we mostly use Java in our projects):

	@Test
	void test() {
		ObservationRegistry registry = TestObservationRegistry.create();
		registry.observationConfig()
		        .observationHandler(new DefaultTracingObservationHandler(new SimpleTracer()));

		Mono<Integer> myFlux = Mono.just(1)
		                           .<Integer>handle((item, sink) -> sink.next(item));

		Observation obs0 = Observation.createNotStarted("observation-0", registry);
		Observation obs1 = Observation.createNotStarted("observation-1", registry);

		obs0.observe(() -> obs1.observe(() -> myFlux.contextCapture().block()));
	}

and indeed this throws the exception you've shown. I believe this should be reported in micrometer-tracing:
https://github.com/micrometer-metrics/tracing

**Comment by chemicL** [comment]
The reactor agnostic reproducer is the following:

    @Test
    void test() {
        ObservationRegistry registry = TestObservationRegistry.create();
        registry.observationConfig()
                .observationHandler(new DefaultTracingObservationHandler(new SimpleTracer()));

        ContextRegistry.getInstance().registerContextAccessor(new ContextAccessor<Observation, Observation>() {
            @Override
            public Class<? extends Observation> readableType() {
                return Observation.class;
            }

            @Override
            public void readValues(Observation sourceContext,
                    Predicate<Object> keyPredicate,
                    Map<Object, Object> readValues) {

            }

            @Override
            public <T> T readValue(Observation sourceContext, Object key) {
                return (T) sourceContext;
            }

            @Override
            public Class<? extends Observation> writeableType() {
                return Observation.class;
            }

            @Override
            public Observation writeValues(Map<Object, Object> valuesToWrite,
                    Observation targetContext) {
                return (Observation) valuesToWrite.get(ObservationThreadLocalAccessor.KEY);
            }
        });

        Observation obs0 = Observation.createNotStarted("observation-0", registry);
        Observation obs1 = Observation.createNotStarted("observation-1", registry);

        obs0.observe(() -> obs1.observe(() -> ContextSnapshot.setAllThreadLocalsFrom(obs1).close()));
    }

**Comment by chemicL** [comment]
@MartinHeyer please open an issue for Micrometer, your discovery is valid, just needs to be handled on their side.
