### ISSUE TITLE
Thread Local context is lost after CompletableFuture

### ISSUE THREAD

**Issue by jonathannaguin** [reactor/reactor-core#3357]
## Expected Behavior
The thread local context should be restored after the completable future is handled.

## Actual Behavior
The thread local context is lost

## Steps to Reproduce

```java 
    @Test
    void threadLocalsLostAfterCompletableFuture()
    {
        Hooks.enableAutomaticContextPropagation();

        AtomicReference<String> tlValue = new AtomicReference<>();

        Flux.just(1)
            .flatMap(i -> Mono.fromFuture(CompletableFuture.runAsync(() -> System.out.println(i)))
                              .doOnNext(j -> tlValue.set(REF1.get())))
            .contextWrite(Context.of(KEY1, "present"))
            .blockLast();

       // This assertion will fail when it should pass
        Assertions.assertEquals("present", tlValue.get());
    }
```

## Possible Solution
None

## Your Environment

* Reactor version(s) used: 3.5.3
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): 18.0.2.1
* OS and version (eg `uname -a`):  21.6.0 Darwin

**Comment by chemicL** [comment]
Thanks for the report.

Actually, the example will never call `doOnNext()`, as it's just a `Runnable` that you provide, so it completes without delivering any element to the `Mono` returned by `flatMap`. Consider using `doOnSuccess` instead. In my setup, this works properly.

Also, if you also wanted to see the ThreadLocals in `CompletableFuture` runtime, consider wrapping an `ExecutorService` using context-propagation library API.

Here's a complete example:

	@Test
	void threadLocalsLostAfterCompletableFuture()
	{
		Hooks.enableAutomaticContextPropagation();

		AtomicReference<String> tlValue = new AtomicReference<>();

		Flux.just(1)
		    //.flatMap(i -> Mono.fromFuture(CompletableFuture.runAsync(() -> System.out.println(i)))
		    .flatMap(i -> Mono.fromFuture(CompletableFuture.runAsync(() -> System.out.println(i),
				                      ContextExecutorService.wrap(Executors.newCachedThreadPool())))
		                      .doOnSuccess(ignored ->
				                      tlValue.set(REF1.get())
		                      ))
		    .contextWrite(Context.of(KEY1, "present"))
		    .blockLast();

		// This assertion will fail when it should pass
		Assertions.assertEquals("present", tlValue.get());
	}

Please verify and if another reproducer comes to your mind, reopen the issue.

**Comment by jonathannaguin** [comment]
thanks @chemicL ,  that works and I was able to pinpoint the issue I was having.

It seems the AWS SDK 2 library does something that breaks the ThreadLocal Context, so this:

```java
return Mono.fromFuture(table.putItemWithResponse(putRequest))
            .map(a->..);
```

will leave the chain without the context, however adding `contextCapture()` makes it work:

```java
return Mono.fromFuture(table.putItemWithResponse(putRequest))
             .contextCapture()
            .map(a->..);
```

**Comment by OlegDokuka** [comment]
I guess we need to add mechanism to capture threadLocal at the source level. Similar to onLastHook the onFirstHook can let us decorate any source and ensure TL are restored on signals

**Comment by chemicL** [comment]
Actually, the reproducer provided is (after replacing doOnNext with doOnSuccess) correct @jonathannaguin – apologies. The reason I was able to get TLs is because the `CompletableFuture` finishes before the initial request to the `Mono`.
If a slight delay is introduced inside the lambda, it is the `ForkJoinPool` `Thread` that delivers the value to the reactive chain. At that point the TLs are gone.

There are three solutions here (use just one):
* provide the `CompletableFuture` framework with a wrapped `Executor`, that restores TLs to all the async steps,
* use `contextWrite()` operator,
* use `contextCapture()` operator.

If you don't need TLs within your lambda, `contextWrite()` will suffice. You are writing the intended TL value directly to Reactor `Context`. Adding another `contextWrite()` immediately after returning from an asynchronous source which is outside of Reactor's control will restore TLs from the `Context`. And as `Context` is inherited from the downstream operators, it will be the `Context` with `KEY1` with value of `"present"` when `Function.identity()` is used as argument.

`contextCapture()` could be used when you want to store existing TLs into Reactor `Context` at the point of subscription, but it doesn't apply here IMO. It will add unnecessary performance hit of reading all existing TLs.

Here is the example of viable choices in the face of a delay (the AWS SDK 2 example introduces a similar delay):

	@Test
	void threadLocalsLostAfterCompletableFuture()
	{
		Hooks.enableAutomaticContextPropagation();

		AtomicReference<String> tlValue = new AtomicReference<>();

		Flux.just(1)
            .flatMap(i -> Mono.fromFuture(CompletableFuture.runAsync(() -> {
	                              System.out.println(i);
	                              try {
		                              Thread.sleep(1000);
	                              }
	                              catch (InterruptedException e) {
		                              e.printStackTrace();
	                              }
                              // Uncommenting below will make the above lambda see TLs
                              //}, ContextExecutorService.wrap(Executors.newCachedThreadPool())))
                              // The below call makes downstream operators see TLs defined
	                          // by the Context of the downstream contextWrite operator.
                              })).contextWrite(Function.identity())
                              .doOnSuccess(ignored -> tlValue.set(REF1.get())))
            .contextWrite(Context.of(KEY1, "present"))
            .blockLast();

		Assertions.assertEquals("present", tlValue.get());
	}

**Comment by chemicL** [comment]
To summarise - I don't think this is a bug. Any source of Thread switching by external libraries or explicit calls by the user, which is outside of Reactor-provided APIs will be a cause of losing the ThreadLocal values.
@OlegDokuka do you think we should do anything special for the `fromFuture` operator?

**Comment by jonathannaguin** [comment]
Thanks a lot @chemicL for your investigaton on this.

My humble opinion is that, very likely anybody using `fromFuture` will hit this issue. Also we don't always have an option to alter the `CompletableFuture` execution when that's fully managed by a third-party library.

**Comment by jonathannaguin** [comment]
@chemicL @OlegDokuka Any thoughts about this? should this be re-opened?

**Comment by chemicL** [comment]
I remember about it. When we have a chance to sync, we'll discuss it.

**Comment by OlegDokuka** [comment]
@chemicL I think we need to have something like `Hooks.onFirstOperator` which can decorate any signal root. It may eliminate the need to decorate everything (e.g. customer executors, etc)

**Comment by jonathannaguin** [comment]
@chemicL @OlegDokuka is it worth re-opening this issue then?

**Comment by chemicL** [comment]
@jonathannaguin for this and similar cases, we intend to implement #3366
