### ISSUE TITLE
Hung WorkQueueProcessor threads after shutdown/completion

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#336]
I get hung threads with the following stack even once WorkQueueProcessor is shutdown and/or completed.  I noticed that only some thread hang like this, but if i cancel all subscribers before shutdown then **all** threads hang, so it maybe that the hung thread are just the ones that have been cancelled.

This is probably related to #335 

```
sourceFailed.event-loop.01 [WAITING]
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await() AbstractQueuedSynchronizer.java:2039
reactor.util.concurrent.WaitStrategy$LiteBlocking.waitFor(long, LongSupplier, Runnable) WaitStrategy.java:374
reactor.util.concurrent.WaitStrategy$PhasedOff.waitFor(long, LongSupplier, Runnable) WaitStrategy.java:439
reactor.core.publisher.RingBuffer$Reader.waitFor(long) RingBuffer.java:491
reactor.core.publisher.WorkQueueProcessor$QueueSubscriberLoop.run() WorkQueueProcessor.java:840
java.lang.Thread.run() Thread.java:745
```

**Comment by smaldini** [comment]
@dfeist let me know and reopen if you still see the issue ?

**Comment by dfeist** [comment]
Fantastic, I'll check and get back to you.  Thanks!
