### ISSUE TITLE
Context Loss in WhenRetry errorFilter impacts Hooks.onEachOperator

### ISSUE THREAD

**Issue by pwhissell** [reactor/reactor-core#3361]
## Expected Behavior

When using a Hooks.onEachOperator to propagate a ThreadLocal value from the context [for example as it is done here](https://github.com/archie-swif/webflux-mdc/blob/master/src/main/java/com/example/webfluxmdc/MdcContextLifter.java) the context should always contain values defined during the  invocation of Mono::contextWrite .

 ## Actual Behavior

The context received in the Hooks.onEachOperator is empty for the [whenRetry companion's concatMap operator](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/util/retry/RetrySpec.java#L360)
because [it is temporarily cleared](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/util/retry/RetrySpec.java#L379).

Caused this pull request: https://github.com/reactor/reactor-core/pull/3262
When trying to fix this: [indefinate hanging bug](https://github.com/reactor/reactor-core/issues/3253)

 

## Steps to Reproduce

1. create and register a hook for onEachOperator as seen [here](https://github.com/archie-swif/webflux-mdc/blob/master/src/main/java/com/example/webfluxmdc/MdcContextLifter.java)

 

```java

@Test

void reproCase() {

        Hooks.onEachOperator(

            Operators.lift((scannable, coreSubscriber) -> new MdcContextHelper<>(coreSubscriber))

        );

        var givenContextKey = "contextKey";
        var givenContextValue = "contextValue";
        var expectedException = new Exception("expectedException");
        var tooManyRetriesException = new Exception("tooManyRetriesException");
        Mono.error(expectedException)
            .retryWhen(Retry
                .backoff(2, Duration.ofMillis(1))
                .filter(t->{
                    assert MDC.get(givenContextKey) != null; // This fails and should not fail
                    return false;
                })
                .doBeforeRetry(signal->{
                    assert MDC.get(givenContextKey) != null; // This works fine
                })
                .onRetryExhaustedThrow((retryBackoffSpec, retrySignal)->tooManyRetriesException))
                .onErrorComplete(e->expectedException.equals(e))
            .contextWrite(Context.of(givenContextKey, givenContextValue))
            .block();

}

```

## Possible Solution

1. Find a better way to fix https://github.com/reactor/reactor-core/issues/3253 and do not clear context [here](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/util/retry/RetrySpec.java#L379)

2. extract the [invocation of the errorFilter](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/util/retry/RetrySpec.java#L369) from [the companion's concatmap](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/util/retry/RetrySpec.java#L360)

 ## Your Environment

 * Reactor version(s) used:
3.5.3

* Other relevant libraries versions (eg. `netty`, ...):
org.springframework.boot:spring-boot-starter-parent:3.0.2
org.springframework:spring-webflux:6.0.4
io.projectreactor.netty:reactor-netty-http:1.1.2

* JVM version (`java -version`):
java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)

* OS and version (eg `uname -a`):
Windows
MINGW64_NT-10.0-19044 PF33D1P6 3.3.3-341.x86_64 2022-01-17 11:45 UTC x86_64 Msys

**Comment by OlegDokuka** [comment]
should be fixed with #3370
