### ISSUE TITLE
Enhance Retry with "on demand complete" and "circuit breaking"

### ISSUE THREAD

**Issue by dvoloshyn** [reactor/reactor-core#3365]
## Motivation
We use reactor-kafka like this:
```
    KafkaReceiver
                .create(ReceiverOptions.<byte[], byte[]>create()
                        .maxDeferredCommits(16)
                        .addRevokeListener(partitions -> {
                            //TODO: clean up records in pipeline
                        }))
                .receive()
                .flatMap(record -> Mono
                        .defer(() -> process(record))
                        .retryWhen(Retry//TODO: share retry state between messages to make use of totalRetriesInARow
                                .backoff(Long.MAX_VALUE, Duration.ofMinutes(1))
                                .maxBackoff(Duration.ofHours(1)))
                        .then(Mono.fromRunnable(() -> {
                            record.receiverOffset().acknowledge();
                            //TODO: signal retry earlier for one of the pending retries
                        })))
                .retryWhen(Retry
                        .backoff(Long.MAX_VALUE, Duration.ofSeconds(1))
                        .maxBackoff(Duration.ofMinutes(1))
                        .transientErrors(true))
                .subscribe();
```
We have "transientErrors" retry for the KafkaReceiver and "ordinary" retries for individual messages.

1. In case of Kafka rebalance (addRevokeListener()) I need a way to clean-up the processing pipeline (complete pending retries). Cannot think of an elegant way to do that.
2. To prevent useless retries while at the same time be able t quickly retry pending retries after recovery from some transient error I need to be able to add a bit of "Circuit Breaker" smartness to the retry. Like share retry state between group of Monos so that I could use "totalRetriesInARow" and "transientErrors". And also, trigger retry of some pending retries earlier when some of the Monos from the group completed successfully or retried successfully. 

## Desired solution
Described above use cases are directly supported by the reactor-netty + reactor.

## Additional context
Ready to provide more details/clarifications of the use cases if necessary.
In case the use cases above could be implemented without changes in the reactor/reactor-netty, I would be grateful for some clues like documentation links, stackoverflow answers, forums, etc.

**Comment by OlegDokuka** [comment]
Hi, @dvoloshyn!

Thank you for the issue. It sounds to me as functionality for a specific (niche) use case and probably has to be implemented outside of reactor-core.

**Comment by OlegDokuka** [comment]
Also, it may help if you describe the problem better or the ideal is isolated example with which we can play to understand the problem better (ideal just pure reactor without any external dependencies)

Thanks

**Comment by chemicL** [comment]
@dvoloshyn closing due to no feedback to what @OlegDokuka requested in March. Please reopen if you are able to provide more details.
