### ISSUE TITLE
ThreadLocal values lost after non-Reactor upstream sources continue execution

### ISSUE THREAD

**Issue by chemicL** [reactor/reactor-core#3366]
In cases like:

- `Flux.from(Publisher<? extends T> source)`
- `Mono.fromFuture(CompletableFuture<? extends T> future)`

where the source can make `Thread` context switches, we'd still like to provide users the means to restore `ThreadLocal` values using the automatic context-propagation mechanism. Currently, the user would need to manually create a boundary, like this:

    Mono.fromFuture(future).contextWrite(Function.identity())

to be able to restore `ThreadLocal`s from current `Context`.

These can be implemented as something like "onFirstOperator" hook, or "onExternalSource".

---

Making the external source aware of and able to use ThreadLocals registered with `ContextRegistry` from context-propagation library is outside of the scope of this issue. For that, we could prepare a documentation section with best practices and guidance as to how to deal with these:
- for simple cases that only use an `Executor` to run tasks -> explain how to wrap the `Executor` with the context-propagation library
- for simple cases where user code is run with `Runnable` or `Callable` primitives, explain how to wrap these with the context-propagation library
- for advanced cases, like using a different reactive-streams implementation, or event-loops, explain how context-propagation can be used in these cases and what are the risks of non-linear async execution

**Comment by jonathannaguin** [comment]
will this issue be resolved on 3.5.5? It seems it got dropped for the 3.5.4 release

**Comment by chemicL** [comment]
Hopefully we can ship it in 3.5.5, but I haven't yet started investigating whether it's complex or not. I will update this issue next week hopefully.

**Comment by jonathannaguin** [comment]
@chemicL  sorry to be a pain, but is there any updates on this? I am honestly blocked on this issue for moving many projects to Spring Boot 3. Thanks for your hard work!

**Comment by chemicL** [comment]
I do hope to make some progress on it next week. I did some initial research this week, looks promising, will start implementing soonish :) However, right now I'm helping investigate another high priority issue and finalizing work on a different one. I do hope we can deliver this feature in 3.5.5, but can't fully commit to this deadline.

**Comment by trebouys** [comment]
@jonathannaguin, for your information, we are blocked by this issue to (we lost context after a mongodb call) and we find a workaround, waiting for an official fix, using AOP to inject context after each mongodb calls dynamically without having to do it everywhere in our application. Maybe it could be a temporary solution for you too.

Our AOP:
```kotlin
@Aspect
@Component
class RepositoryAspect{

  @Around("execution(* org.springframework.data.mongodb.repository.ReactiveMongoRepository..*(..))")
  fun repoAroundAllMethods(joinPoint: ProceedingJoinPoint): Any {
         val result = joinPoint.proceed()
         return (result as? Mono<*>)?.contextWrite { it }
                      ?: (result as? Flux<*>)?.contextWrite { it }
                      ?: result
  }
}```
