### ISSUE TITLE
Gateway traceid broken generation

### ISSUE THREAD

**Issue by ArtyomKazlanzhi** [reactor/reactor-core#3375]
I'm working with Spring boot 3.01, micrometer tracing, bridge brave, spring cloud gateway
Found on the web that I can populate logs with traceId and spanId if to add reactor-core 3.5.3
and by adding
Hooks.enableAutomaticContextPropagation();

It really helps, but for some reason it breaks generating the trace id, for the first request to the gateway it generates a new one, then with every new request TraceContext using the same trace id over and over, except the span id, it's a new one every time (like it should be)

**Comment by chemicL** [comment]
@ArtyomKazlanzhi can you please try using the latest versions of the libraries and retry? Usually, it's a matter of updating Spring Boot to 3.0.4. It carries the latest of Micrometer and Reactor unless you specify the versions on your own, in which case you also should bump.

If using the latest versions you still see the issue, it's best if you prepare an isolated reproducer that we can work with.

**Comment by ArtyomKazlanzhi** [comment]
@chemicL I have tried to update the dependencies to the latests, trace id and span id are no more the same, they are generated correct, but they no more displayed in the logs
created a sample with same configuration
https://github.com/ArtyomKazlanzhi/spring-gateway-micrometer-tracing

**Comment by github4sanjay** [comment]
its very unpredictable after upgrading to spring boot 3, same code produces traceId sometimes and sometimes not, not sure wats issue 

```
2023-03-11 18:13:19 2023-03-11 10:13:19,081 [parallel-2] INFO [gateway,640c543eda23fff1f4dc85ea58b5f171,1b0e2dd80b1de2ad,,] com.example.gateway.AddAuthHeaderGatewayFilter - API /api/v1/devices request by f0343220-73fb-4db2-98fa-853638423fa7 from device f00639ed-d457-49e9-b05d-891d4e984c8a
2023-03-11 18:13:36 2023-03-11 10:13:36,193 [parallel-1] INFO [gateway,00000000000000000000000000000000,0000000000000000,,] com.example.gateway.AddAuthHeaderGatewayFilter - API /api/v1/devices request by f0343220-73fb-4db2-98fa-853638423fa7 from device f00639ed-d457-49e9-b05d-891d4e984c8a
```

**Comment by chemicL** [comment]
@github4sanjay without a reproducer it won't be possible to help. I would consider reporting this to the relevant Spring portfolio project if it is a functionality of that project.

**Comment by kzander91** [comment]
This problem re-appeared for me, I created #3584 with a simple reproducer.
