### ISSUE TITLE
Micrometer.observation failure with automatic context propagation

### ISSUE THREAD

**Issue by maciej-gromul** [reactor/reactor-core#3395]
Context is not properly propagated through publishers when using `Hooks.enableAutomaticContextPropagation();`. I've created a simple [spring boot 3 application](https://github.com/maciej-gromul/boot-3-problems-with-context-propagation) that should be working using micrometer observations to create tracing context. I can see spans being created but their context is not propagated which results in something like this:

![image](https://user-images.githubusercontent.com/89904409/224020691-49df5e86-a2f4-4d8b-b5ba-3038d4a752e5.png)

while expected trace should be nested like this:

```
http get /trace
  |
  -- some-random-name
       |
       -- simple-text-wrapping-service
            |
            -- other-layer
```

I've confirmed that TapSubscriber properly registers in reactor context new tracing context from created span, but it get's lost somewhere and in the next tap operator that creates a new observation with new span later on it always attaches to the root span.

## Expected Behavior
Context get's propagated and spans are being properly connected to each other.

## Actual Behavior
Root span created by spring webflux is always being treated as parent root, even if we create new span following the migration guide for sleuth, it get's created but parent stays as current span/context.

## Steps to Reproduce
Here's the project with example to reproduce the problem: https://github.com/maciej-gromul/boot-3-problems-with-context-propagation. There's docker compose configuration file to run grafana stack allowing easy verification of generated tracing.

## Possible Solution
Don't know what precisely causes this.

**Comment by maciej-gromul** [comment]
I'm still new to tap operator, but from what i've seen this is the "recommended" way to use observation from reactor-core-micrometer. It's documented here: https://github.com/reactor/reactor-core/blob/main/docs/asciidoc/metrics.adoc

**Comment by chemicL** [comment]
@maciej-gromul if you have time, please validate the behaviour with the latest snapshot.

**Comment by maciej-gromul** [comment]
It's still being published https://github.com/reactor/reactor-core/actions/runs/4509632576, i'll try it out later :)

**Comment by maciej-gromul** [comment]
I've replaced deps with below ones, but it still doesn't work :( I don't get the traces connected with each other :( Maybe i'm doing something wrong there ?
```xml
<dependency>
  <groupId>io.projectreactor</groupId>
  <artifactId>reactor-core</artifactId>
  <version>3.5.5-SNAPSHOT</version>
</dependency>
<dependency>
  <groupId>io.projectreactor</groupId>
  <artifactId>reactor-core-micrometer</artifactId>
  <version>1.0.5-SNAPSHOT</version>
</dependency>
```

**Comment by chemicL** [comment]
Interesting. To make sure the classpath contains the correct version, please try putting a debug breakpoint in `FluxTapRestoringThreadLocals.TapSubscriber`'s constructor and see if it's used at all.

My PR had a synthetic test added for this case:
https://github.com/reactor/reactor-core/blob/main/reactor-core-micrometer/src/test/java/reactor/core/observability/micrometer/MicrometerObservationListenerTest.java#L480

I wonder how it's different from the setup your application has. Let me know if the version you're using contains the changes and whether you think there is something that test doesn't cover.

**Comment by maciej-gromul** [comment]
It's getting into the constructor. I've updated the [example](https://github.com/maciej-gromul/boot-3-problems-with-context-propagation). When i debug constructor for that tap, each time i'm getting context with a span created by tap and the parent is the root span created by spring.

![image](https://user-images.githubusercontent.com/89904409/227887630-451c5c0d-d0f7-4fe7-a143-23108eb421ea.png)

Maybe this already is solved and there's a problem with basic context propagation ? 

The setup is pretty simple. We've got single endpoint GET /trace, that has tap observation on it, later there's flatmap method on text wrapping service.

![image](https://user-images.githubusercontent.com/89904409/227887791-764a58e6-faee-4a9f-a25a-fddcabd19683.png)

![image](https://user-images.githubusercontent.com/89904409/227888028-66365c95-2822-4b76-b8f1-2496e103b22d.png)

Following that we should get span **GET /trace** (which we do) and then **some-random-name** connected to **GET /trace** and then **simple-text-wrapping-service** connected to **some-random-name**. But for some unknown to me reason all of them are being registered to root **GET /trace**

**Comment by chemicL** [comment]
Are you certain of where your `.tap(Micrometer.observation(observationRegistry))` should go? The child span should be available in the operators upstream from that occurrence, not downstream, in my understanding. Please try reordering (putting `tap` at the very end in each level of `Observation` hierarchy) and reassess.

**Comment by maciej-gromul** [comment]
It works if i do it that way. I have few questions with that. I thought that i need to put tap at the beginning to correctly calculate execution times etc. following the [metrics docs](https://github.com/reactor/reactor-core/blob/main/docs/asciidoc/metrics.adoc) from reactor-core. If i have to put it at the end doesn't it mean i will have invalid metrics in that case since it will skip processing ?

But to make those work as spans i need to place it at the very end. Doesn't it mean that it's actually having either this or that correct instead of both ?

Additionally it will be impossible to instrument flux publishers which should have separate context per element published to follow on the tracing properly (sleuth now is using ScopePassingSpanSubscriber i believe). If i have to put it at the end because it's using the context that is actually being "propagated" only upstream then it's impossible to use it with any flux publisher properly. Unless we want to simply have generic context per whole flux.

**Comment by chemicL** [comment]
It works correctly for both concerns. It's not declaration time that matters, but the execution time -> `Observation` is started when the pipeline is subscribed to. It gets stopped when the `Flux` completes (or gets cancelled/ or errors) and when `Mono` delivers `onNext` (or completes/ gets cancelled/ errors). Every operator upstream from the particular `.tap(Micrometer.observation(observationRegistry))` will be executed within the context of the `Observation` created at subscription time of that particular `tap`. E.g. all the log statements in operators above will have the trace-id/span-id pair from that `Observation`, and all operators below (downstream) will have the parent's (or empty) values associated.

In case of measuring a particular item from a `Flux` -> I imagine you'd be interested in a flat-map-like operator which is able to wrap every item in a `Mono` (e.g. using `Mono.just()`, which can be followed by a `tap` to associate a new `Observation` which measures the processing of each individual item.

Hope this helps.

**Comment by maciej-gromul** [comment]
I did some simple testing and it actually makes difference, i understand where it comes from, but unless it's unintended we should update metrics docs to describe how it behaves, since reactive programming is still
```java
var meterRegistry = new SimpleMeterRegistry();
var registry = ObservationRegistry.create();
registry.observationConfig()
  .observationHandler(new DefaultMeterObservationHandler(meterRegistry));

var source = Flux.range(1, 10);
source.name("test1")
  .tag("foo", "bar")
  .tap(Micrometer.observation(registry))
  .flatMap(i -> Mono.delay(Duration.ofSeconds(1)))
  .name("test2")
  .tap(Micrometer.observation(registry))
  .blockLast();

meterRegistry.getMeters()
  .stream()
  .filter(meter -> !meter.getId().getName().endsWith(".active"))
  .forEach(
    meter -> {
       System.out.println();
       meter.measure().forEach(measurement -> System.out.println(
         meter.getId().getName()
         + " | "
         + measurement.getStatistic().name()
         + ":" + measurement.getValue()
       )
    );
  }
);
```

Out of it i get such results:

```text
test2 | COUNT:1.0
test2 | TOTAL_TIME:1.056872122
test2 | MAX:1.056872122

test1 | COUNT:1.0
test1 | TOTAL_TIME:0.048378594
test1 | MAX:0.048378594
```

**Comment by maciej-gromul** [comment]
I did some simple testing and it actually makes difference, i understand where it comes from, but unless it's unintended we should update metrics docs to describe how it behaves.

```java
var meterRegistry = new SimpleMeterRegistry();
var registry = ObservationRegistry.create();
registry.observationConfig()
  .observationHandler(new DefaultMeterObservationHandler(meterRegistry));

var source = Flux.range(1, 10);
source.name("test1")
  .tag("foo", "bar")
  .tap(Micrometer.observation(registry))
  .flatMap(i -> Mono.delay(Duration.ofSeconds(1)))
  .name("test2")
  .tap(Micrometer.observation(registry))
  .blockLast();

meterRegistry.getMeters()
  .stream()
  .filter(meter -> !meter.getId().getName().endsWith(".active"))
  .forEach(
    meter -> {
       System.out.println();
       meter.measure().forEach(measurement -> System.out.println(
         meter.getId().getName()
         + " | "
         + measurement.getStatistic().name()
         + ":" + measurement.getValue()
       )
    );
  }
);
```

Out of it i get such results:

```text
test2 | COUNT:1.0
test2 | TOTAL_TIME:1.056872122
test2 | MAX:1.056872122

test1 | COUNT:1.0
test1 | TOTAL_TIME:0.048378594
test1 | MAX:0.048378594
```

Additionally we don't get metrics of onNext like in previous versions of reactor.metrics(), this we would need to make separate metrics again manually.

**Comment by maciej-gromul** [comment]
Additionally it would be nice to have something similar to tap(Micrometer.observation) that would by default wrap flux to provide observations on per element so that we could get spans there as well. Wrapping each flatMap manually everywhere is kinda painful :(

**Comment by chemicL** [comment]
@maciej-gromul please open a new issue with that suggestion. I don't have enough context to answer whether that is possible but we can consult with the Micrometer team once we have the expectations in place.
