### ISSUE TITLE
CI is 3x slower after updating jcstress-core from 0.15 to 0.16 

### ISSUE THREAD

**Issue by violetagg** [reactor/reactor-core#3403]
CI is 3x slower after updating `jcstress-core` from 0.15 to 0.16 (**~1h 30min**) https://github.com/reactor/reactor-core/actions/runs/4365616791
The previous commit was passing of **~25min** https://github.com/reactor/reactor-core/actions/runs/4365521418

**Comment by chemicL** [comment]
The JCStress release notes:
https://mail.openjdk.org/pipermail/jcstress-dev/2023-February/001075.html

From the tests output, it feels this change could potentially affect the time it takes to complete:
https://github.com/openjdk/jcstress/commit/0703c84699fdd9bb626db2b42cf0de67e5dc50a7

This change reduced the heap used from 256mb to 128mb for our tests.

Also, in 0.16 the CPU topology recognition changed, but not sure if it schedules anything differently now.

**Comment by chemicL** [comment]
Also, from that very commit I noticed calculating `adjustStrideCount` used to just sample powers of two, now it tries more configurations to pick the number:

```
count = Math.max((int)(count*1.2), count+1);
```

before it was simply

```
count *= 2;
```

It can also slow down the build in the setup phase, where runtime parameters are picked.

**Comment by OlegDokuka** [comment]
ci should be fixed as of now
