### ISSUE TITLE
Apply contextCapture automatically in block operators

### ISSUE THREAD

**Issue by ttddyy** [reactor/reactor-core#3406]
## Motivation

When `WebClient` is used in Spring MVC with `block` operator, users always need to call `contextCapture` to grab the context on the thread to properly populate the context in addition to `Hooks.enableAutomaticContextPropagation()`.

## Desired solution

The expectation from many developers in imperative programming world would be that context are automatically propagated such `WebClient` operation chain, and wherever writing logs, MDC is properly populated.

The `block` operators could be a trigger to capture context. So that, `WebClient` users with blocking code can automatically get context propagation without always specifying `contextCapture`.

## Additional context

It is a headache for developers to always ask to call `contextCapture` when they use `WebClient` in imperative code with `block` operators.
Many cases, they have switched `RestTemplate` to `WebClient` and realized MDC logging is not working.
Their expectation is simply `WebClient` call with `block` to work as same with `RestTemplate`...

**Comment by daltonfury42** [comment]
Hi, any updates on this? I see a PR open, it will be super helpful if that can merge and I can use a snapshot jar. We have a huge project with lot of webclient usage and it will be painful to go and update each to call contextCapture.
