### ISSUE TITLE
Mono.fromCompletionStage fails to propagate error signal when exception is thrown in `map`, `flatMap` and `handle`

### ISSUE THREAD

**Issue by mcanalesmayo** [reactor/reactor-core#3417]
A Mono created with `Mono.fromCompletionStage` fails to propagate an error signal downstream in the following cases:
- `mono.map` throws an unchecked exception
- `mono.flatMap` returns a mono containing an error signal
- `mono.handle` signals an error on the provided sink

Others like `Mono.fromFuture` work fine, please see the following repository containing simple test cases on how to reproduce: https://github.com/mcanalesmayo/reactor-core-cs-bug

## Expected Behavior
Error signal to be propagated downstream

## Actual Behavior
Error signal is lost

## Steps to Reproduce
https://github.com/mcanalesmayo/reactor-core-cs-bug

## Possible Solution
Did not look into details on how to fix, but a simple workaround is just using `Mono.fromFuture(cs.toCompletableFuture())` instead

## Your Environment

* Reactor version(s) used: 3.5.4
* Other relevant libraries versions (eg. `netty`, ...): N/A
* JVM version (`java -version`): 11
* OS and version (eg `uname -a`): macOS Ventura 13.2.1

**Comment by OlegDokuka** [comment]
fixed and should be available in 3.4.30 and 3.5.7
