### ISSUE TITLE
Why only the number of core threads can be used but not the maximum number of threads?

### ISSUE THREAD

**Issue by miaoweiwei** [reactor/reactor-core#3419]
```java
@Test
public void testParallel() throws InterruptedException {
  ThreadPoolExecutor RANGE_SCHEDULER_POOL =
      new ThreadPoolExecutor(3, 256,
          30L, TimeUnit.SECONDS,
          new LinkedBlockingQueue<>(1024),
          new ThreadFactoryBuilder().setNameFormat("Range-Scheduler-%d").build(),
          new ThreadPoolExecutor.CallerRunsPolicy());
  RANGE_SCHEDULER_POOL.allowCoreThreadTimeOut(true);
  Scheduler RANGE_SCHEDULERS_POOL = Schedulers.fromExecutor(RANGE_SCHEDULER_POOL);
  ParallelFlux<String> parallelFlux = Flux.range(1, 500).parallel(20).runOn(RANGE_SCHEDULERS_POOL).flatMap(index -> {
      Mono<String> supplier = Mono.fromSupplier(() -> {
          Random random = new Random();
          try {
              Thread.sleep(random.nextInt(1000));
          } catch (InterruptedException e) {
          }
          return String.format("mono1-%s-%d%n", Thread.currentThread().getName(), index);
      });
      return supplier.map(obj -> obj);
  });

  Mono<List<String>> mono1 = parallelFlux.collectSortedList(Comparator.comparingInt(Object::hashCode));
  mono1.subscribe(System.out::println, Throwable::printStackTrace);

  Thread th = new Thread(() -> {
      while (true){
          System.out.println(RANGE_SCHEDULER_POOL);
          try {
              Thread.sleep(1000);
          } catch (InterruptedException ignored) {}
      }
  });
  th.start();
  Thread.sleep(60_000_000);
}
```
output
```
java.util.concurrent.ThreadPoolExecutor@6fc2ae19[Running, pool size = 3, active threads = 3, queued tasks = 17, completed tasks = 20] 
java.util.concurrent.ThreadPoolExecutor@6fc2ae19[Running, pool size = 3, active threads = 3, queued tasks = 17, completed tasks = 20] 
java.util.concurrent.ThreadPoolExecutor@6fc2ae19[Running, pool size = 3, active threads = 3, queued tasks = 17, completed tasks = 20]
...
```

* Reactor version(s) used:  3.2.10.RELEASE
* JVM version (`java -version`): Oracle OpenJDK 11.0.18
* OS and version (eg `uname -a`): MacOS Ventura 13.2.1 (22D68)

**Comment by OlegDokuka** [comment]
Unrelated to the project. Please refer the official JDK [docs](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html#ThreadPoolExecutor(int,%20int,%20long,%20java.util.concurrent.TimeUnit,%20java.util.concurrent.BlockingQueue)) for more info about ThreadPool behaviours . Also, you may find this Stackoverflow answer valid as well https://stackoverflow.com/questions/17659510/core-pool-size-vs-maximum-pool-size-in-threadpoolexecutor

**Comment by miaoweiwei** [comment]
> Unrelated to the project. Please refer the official JDK [docs](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html#ThreadPoolExecutor(int,%20int,%20long,%20java.util.concurrent.TimeUnit,%20java.util.concurrent.BlockingQueue)) for more info about ThreadPool behaviours . Also, you may find this Stackoverflow answer valid as well https://stackoverflow.com/questions/17659510/core-pool-size-vs-maximum-pool-size-in-threadpoolexecutor

I think it is related to the project. Please run this code

**Comment by miaoweiwei** [comment]
> Unrelated to the project. Please refer the official JDK [docs](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html#ThreadPoolExecutor(int,%20int,%20long,%20java.util.concurrent.TimeUnit,%20java.util.concurrent.BlockingQueue)) for more info about ThreadPool behaviours . Also, you may find this Stackoverflow answer valid as well https://stackoverflow.com/questions/17659510/core-pool-size-vs-maximum-pool-size-in-threadpoolexecutor

The Scheduler created using the Schedulers.fromExecutor method
