### ISSUE TITLE
subscribeOn(Schedulers.parallel()) doesn't execute in parallel when located right after a just()

### ISSUE THREAD

**Issue by antonio-marrero** [reactor/reactor-core#342]
I've noticed a different behaviour when you place a subscribeOn straigh after a just from when you put another operator in-between.
For example:
```java
CountDownLatch latch = new CountDownLatch(1);

Flux<Integer> flux = Flux.range(0, 30);
flux.flatMap(count -> Flux.just(count)
     .subscribeOn(Schedulers.parallel())
     .map(i -> highCpuProcess(i)))
     .doAfterTerminate(latch::countDown)
     .subscribe( m -> System.out.println("Subscriber received - " + m + " on thread: " + Thread.currentThread().getName()));

latch.await();
```
This always creates four threads but only uses one and never runs the processes in parallel. 
![singlethread](https://cloud.githubusercontent.com/assets/3987991/21726061/f9bcc4ae-d432-11e6-82dd-ac4400667202.png)

On the contrary, when you put an operator in the middle the four threads are used, I use log() in my example but it can be any operator:
```java
CountDownLatch latch = new CountDownLatch(1);

Flux<Integer> flux = Flux.range(0, 30);
flux.flatMap(count -> Flux.just(count)
     .log()
     .subscribeOn(Schedulers.parallel())
     .map(i -> highCpuProcess(i)))
     .doAfterTerminate(latch::countDown)
     .subscribe( m -> System.out.println("Subscriber received - " + m + " on thread: " + Thread.currentThread().getName()));

latch.await();
```

In this last case, the four threads are used:
![multithread](https://cloud.githubusercontent.com/assets/3987991/21726166/7545320a-d433-11e6-9ee8-e6d38fa6938d.png)

**Comment by antonio-marrero** [comment]
NOTE: Using Mono instead of Flux works fine
```Java
		CountDownLatch latch = new CountDownLatch(1);
		
		Flux<Integer> flux = Flux.range(0, 30);
		flux.flatMap(count -> Mono.just(count)
				.subscribeOn(Schedulers.parallel())
				.map(i -> highCpuProcess(i)))
		.doAfterTerminate(latch::countDown)
		.subscribe( m -> System.out.println("Subscriber received - " + m + " on thread: " + Thread.currentThread().getName()));
		latch.await();
```

**Comment by akarnokd** [comment]
This is a cross-boundary fusion problem with flatMap and an async-fuseable source that schedules emissions internally, like the fused just+subscribeOn and observeOn in general.

I don't know yet how would be possible to keep such fusion, therefore, I suggest disabling fusion on these classes:

  - `FluxSubscribeOnValue`
  - `FluxPublishOn`

You can simply return `NONE` or strip the classes from `QueueSubscription`

**Comment by smaldini** [comment]
Yes for FluxSubscribeOnValue.
I wonder if we can keep the fusion for FluxPublishOn if its not backfused tho or parent is not fuseable ?
