### ISSUE TITLE
deadlock happened when using groupBy in some case

### ISSUE THREAD

**Issue by realzero0** [reactor/reactor-core#3427]
## Expected Behavior

No deadlock and working fine

## Actual Behavior

Deadlock and timeout exception occurred

## Steps to Reproduce

```java
    @Test
    void test() {
        AtomicLong upstream = new AtomicLong(0L);
        AtomicLong downstream = new AtomicLong(0L);

        Flux.fromStream(Stream.iterate(0L, (last) -> ++last))
                .flatMap(number -> Flux.concat(
                        Mono.just(number),
                        Mono.just(number)))
                .take(768)
                .doOnNext(next -> {
                    upstream.incrementAndGet();
                })
                .publishOn(Schedulers.boundedElastic())
                .groupBy(Function.identity())
                .flatMap(groupFlux ->
                        Flux.just(1L)
                                .collectList())
                .doOnNext(batch -> {
                    long startNano = System.nanoTime();
                    while (System.nanoTime() - startNano < 1_000_000) ;
                })
                .map(Collection::size)
                .doOnNext(downstream::addAndGet)
                .count()
                .timeout(Duration.ofSeconds(30))
                .block();
    }
```

- make a flux
- take more than 768 (3 times of concurrent size)
- groupBy (all element should have duplicated key. every element will be grouped by a key)
- flatmap
  - create new Flux on flatmap
- collect (in this example, `count()`)
- deadlock...

## Your Environment

* Reactor version(s) used: 3.5.4
* Other relevant libraries versions (eg. `netty`, ...): spring-boot 3.0.4
* JVM version (`java -version`): java17
* OS and version (eg `uname -a`): osx

**Comment by realzero0** [comment]
#2352

**Comment by OlegDokuka** [comment]
@realzero0 that is expected. The given group MUST be subscribed. Otherwise, backpressure upstream if no elements are consumed from created groups.
