### ISSUE TITLE
Then(aVoid -> myHandler) does not react on empty Mono

### ISSUE THREAD

**Issue by apischan** [reactor/reactor-core#343]
I have situation when I need to do some actions with `Mono`, then some with `Flux` and then again with `Mono`. I have to chain them with `Mono<Void>` because the handling have no result. Here is how it looks like:
```
myHandler.handle("a") // this method returns Mono<Void>
                .then(aVoid -> myHandler.handle("b"))
                .then(aVoid -> myHandler.handleMany(Flux.just("c", "d", "e", "f"))) //this one also returns Mono<Void> to combine calls further
                .then(aVoid -> myHandler.handle("g"))
                .block();
```

So the issue is when Reactor trying to combine empty results of handling to one `Mono<Void>`. I'm doing it this way:
```
public Mono<Void> handleMany(Flux<String> someStrings) {
    return Mono.when(someStrings.flatMapSequential(
            this::handle
    ));
}

public Mono<Void> handle(String someString) {
    return Mono.create(sink -> {
        Callback<Void> callback = new Callback<>(sink);
        workToDo.add(new SomeMessage<>(someString, callback));
    });
}
```
Also I'm using `sink` to notify when handling of one of `Flux` element is done.
```
sink.success(null) // here is the issue is happening. null because sink is related to `Mono<Void>`
```
And part of statcktrace:
```
java.lang.NullPointerException: e
	at java.util.Objects.requireNonNull(Objects.java:228)
	at reactor.util.concurrent.SpscArrayQueue.offer(SpscArrayQueue.java:46)
	at reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.innerNext(FluxMergeSequential.java:266)
	at reactor.core.publisher.FluxMergeSequential$MergeSequentialInner.onNext(FluxMergeSequential.java:515)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:97)
```

Sorry for maybe unclear explanation but it is really a bit complicated to explain :)
To take a look at full example please follow my Github. [Direct link](https://github.com/apischan/lite-rx-api-hands-on/tree/master/src/main/java/io/pivotal/literx/example).

**Comment by smaldini** [comment]
Did you try sink.success() ? we usually explicitly check as soon as possible that a null is not sent in the flow (it happens that MonoSink let it pass). Sink.success() will skip next and just complete as it should do since Reactive Streams do not support null. If that works we can just add the early check.

**Comment by apischan** [comment]
@smaldini of course I tried `sink.success()` but it works even worse. Maybe I'm doing something wrong here but I expected that all my chain 
```
myHandler.handle("a") // this method returns Mono<Void>
                .then(aVoid -> myHandler.handle("b"))
                .then(aVoid -> myHandler.handleMany(Flux.just("c", "d", "e", "f"))) //this one also returns Mono<Void> to combine calls further
                .then(aVoid -> myHandler.handle("g"))
                .block();
```
will work with `sink.success()` but it don't. It completes immediately after the first statement `myHandler.handle("a")` and never doing `myHandler.handle("b")` etc.

**Moreover in my example if I would use `sink.success(null)` it throws exception but with this it stucks forever if timeout has not set.**

In example above if my method `handle` would return `Mono<String>` I wouldn't have any problem. But it have to return `Mono<Void>` because I no need any result after handling. I expected the same API and behaviour for both `Mono<Void>` and `Mono<String>` and as `Void` have no any value - I forced to pass `null` as parameter. I need a way somehow to complete my `Mono<Void>`.
Just look at `CompletableFuture` - if I need to complete if without value - I would do it this way `future.complete(null)` and **no NPE will be thrown**.

If you can please take a look at my example [here](https://github.com/apischan/lite-rx-api-hands-on/tree/master/src/main/java/io/pivotal/literx/example). It is short and very straightforward.

**Comment by smaldini** [comment]
The  ` then(aVoid -> anything)` is never going to be invoked, then(data -> {}) is like flatMap(data -> {}) but with one possible value generated at most, it reacts with a source data, which here is a void.

You may want to chain such Void mono using `thenEmpty(Publisher<Void>)` or simply `<V> then(Mono<V>)` as you can notice these two signatures ignore the incoming data.

**Comment by apischan** [comment]
And what do you think about this one?

> Moreover in my example if I would use sink.success(null) it throws exception but with this it stucks forever if timeout has not set.

Here I mean if in my program `sink.success(null)` will happen and timeout will **not** be set - it will silently throw NPE somewhere under the hood (and even in some cases I will not see this NPE) and the thread will be stuck.

**Comment by smaldini** [comment]
Yes @apischan we extracted a separated issue for this see  #349

**Comment by smaldini** [comment]
@simonbasle FAQ 2 item ? Mono.then(val -> xxx) and in general any callback taking a data argument will be shortcircuited by complete or error.

**Comment by simonbasle** [comment]
keeping this to track adding that to the reference guide's FAQ. The underlying issue (#346) has been improved upon
