### ISSUE TITLE
Add doOnEach(Consumer<? super Signal<T>> signalConsumer) equivalent in ParrelelFlux and Mono

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#344]
What @simonbasle added in https://github.com/reactor/reactor-core/commit/e1b28e1a3562142ae7f04c6fd88401bbf89715be is pretty cool/useful, just a shame there isn't an equivalent in Mono/ParrelelFlux as it'd be useful, and for consistency of course.

Another option with ParrelelFlux is to keep it as tight as possible, and not duplicate any but the most used operators, and then allow Flux operators to be used via #283 e.g.

```
parallelFlux.transformRail(flux -> flux.doOnEach(..))
```

**Comment by smaldini** [comment]
Fixed by #348
