### ISSUE TITLE
Hooks.onEachOperator caused execute on different thread

### ISSUE THREAD

**Issue by will-zdu** [reactor/reactor-core#3450]
## Expected Behavior

The "Operation enter call1:" will print on elastic-* thread like this
"10:28:18.541 [elastic-1] INFO app.controller.TestHook - Operation enter call1"
when I remove the hook it will print like this
"10:36:30.557 [elastic-2] INFO app.controller.TestHook - Operation enter call1"
## Actual Behavior

The "Operation enter call1:" will print on elastic-* thread like this
"10:36:30.557 [single-1] INFO app.controller.TestHook - Operation enter call1"

the log print action execute on single thread but without hook it will be execute on elastic thread pool

## Steps to Reproduce

```java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import reactor.core.CoreSubscriber;
import reactor.core.Scannable;
import reactor.core.publisher.Hooks;
import reactor.core.publisher.Mono;
import reactor.core.publisher.Operators;
import reactor.core.scheduler.Schedulers;

import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;
import java.util.function.BiFunction;

public class TestHook {

    private static final Logger logger = LoggerFactory.getLogger(TestHook.class);

    static{
        try{
            Hooks.onEachOperator("testHook", Operators.lift(new Lifter<>()));
        }catch (Throwable ignored){
        }
    }


    public static class Lifter<T>
            implements BiFunction<Scannable, CoreSubscriber<? super T>, CoreSubscriber<? super T>> {

        /** Holds reference to strategy to prevent it from being collected. */

        @Override
        public CoreSubscriber<? super T> apply(Scannable publisher, CoreSubscriber<? super T> sub) {
            return sub;
        }
    }

    public static void main(String[] args) throws InterruptedException {
        Callable<String> callable = () -> {
            logger.info("Operation enter call1: ");
            return "call1";
        };


        Mono.defer(() -> Mono.fromCallable(callable)
                             .publishOn(Schedulers.elastic())
                             .flatMap(source -> {
                                 logger.info("Again enter map :{} ", source);
                                 return Mono.just(source);
                             })).subscribeOn(Schedulers.single()).subscribe();


        TimeUnit.SECONDS.sleep(3);
    }
}
```

## Possible Solution

```java
public final Mono<T> publishOn(Scheduler scheduler) {
		if(this instanceof Callable) {
			if (this instanceof Fuseable.ScalarCallable) {
				try {
					T value = block();
					return onAssembly(new MonoSubscribeOnValue<>(value, scheduler));
				}
				catch (Throwable t) {
					//leave MonoSubscribeOnCallable defer error
				}
			}
			@SuppressWarnings("unchecked")
			Callable<T> c = (Callable<T>)this;
			return onAssembly(new MonoSubscribeOnCallable<>(c, scheduler));
		}
		return onAssembly(new MonoPublishOn<>(this, scheduler));
	}
```
When add some this code on reactor.core.publisher.Mono#publishOn
```java
if (this instanceof InternalMonoOperator) {
			InternalMonoOperator<?, ?> internalMonoOperator = (InternalMonoOperator<?, ?>) this;
			Mono<?> source = internalMonoOperator.source;
			if (source instanceof MonoLiftFuseable) {
				MonoLiftFuseable<?, ?> monoLiftFuseable = (MonoLiftFuseable<?, ?>) source;
				Mono<?> source1 = monoLiftFuseable.source;
				if(source1 instanceof Callable) {
					@SuppressWarnings("unchecked")
					Callable<T> c = (Callable<T>)source1;
					return onAssembly(new MonoSubscribeOnCallable<>(c, scheduler));
				}
			}
		}
```
it will be right
or when I remove the hooks ,it will be right too

It may be a design mistake on reactor hooks

## Your Environment

* Reactor version(s) used: reactor core 3.3.13.RELEASE
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): JDK 11 ,JDK17 both will reproduce it
* OS and version (eg `uname -a`): Linux core 5.4.0-144-generic

**Comment by chemicL** [comment]
The proposed solution looks dangerous, it most probably destroys the efforts that the hook would try to make to modify the operator by reaching for the internals and skipping the proper subscription process.

Instead of trying to solve the problem, please describe why you think this is a problem and provide a use case where you'd expect a different behaviour.

**Comment by chemicL** [comment]
Also, please note 3.3.13.RELEASE is unsupported (https://projectreactor.io/docs/core/release/reference/#_active_development). Please consider updating.

**Comment by will-zdu** [comment]
@chemicL 
```java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import reactor.core.CoreSubscriber;
import reactor.core.Scannable;
import reactor.core.publisher.Hooks;
import reactor.core.publisher.Mono;
import reactor.core.publisher.Operators;
import reactor.core.scheduler.Schedulers;

import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;
import java.util.function.BiFunction;

public class TestHook {

    private static final Logger logger = LoggerFactory.getLogger(TestHook.class);

    static{
        try{
            // Hooks.onEachOperator("testHook", Operators.lift(new Lifter<>()));
        }catch (Throwable ignored){
        }
    }


    public static class Lifter<T>
            implements BiFunction<Scannable, CoreSubscriber<? super T>, CoreSubscriber<? super T>> {

        /** Holds reference to strategy to prevent it from being collected. */

        @Override
        public CoreSubscriber<? super T> apply(Scannable publisher, CoreSubscriber<? super T> sub) {
            return sub;
        }
    }

    public static void main(String[] args) throws InterruptedException {
        Callable<String> callable = () -> {
            logger.info("Operation enter call1: ");
            return "call1";
        };


        Mono.defer(() -> Mono.fromCallable(callable)
                             .publishOn(Schedulers.elastic())
                             .flatMap(source -> {
                                 logger.info("Again enter map :{} ", source);
                                 return Mono.just(source);
                             })).subscribeOn(Schedulers.single()).subscribe();


        TimeUnit.SECONDS.sleep(3);
    }
}
```

without the hook the log "Operation enter call1: " will be execute on elastic thread pool
but when I add the hook ,  the apply method just it's self , log "Operation enter call1: " will be execute on single thread pool
 the difference is only about the this code remove or add
```java
Hooks.onEachOperator("testHook", Operators.lift(new Lifter<>()));
```
The log print on different thread may be a little mistake,but I execute a block() operation before or after the log ,add hook will be
report an exception of IllegalException
block(),blcokFirst(),blockLast() are blcoking ,which is not supported in thread single-1 


I know that my solution is very dangerous. I just want to help reactor project locate the cause of this case, not the solution I suggested. Maybe I didn't express clearly

**Comment by will-zdu** [comment]
maybe log print on differnet thread is look like not not serious ,If I change code to that
```java
package app.controller;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import reactor.core.CoreSubscriber;
import reactor.core.Scannable;
import reactor.core.publisher.Hooks;
import reactor.core.publisher.Mono;
import reactor.core.publisher.Operators;
import reactor.core.scheduler.Schedulers;

import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;
import java.util.function.BiFunction;

public class TestHook {

    private static final Logger logger = LoggerFactory.getLogger(TestHook.class);

    static{
        try{
            Hooks.onEachOperator("testHook", Operators.lift(new Lifter<>()));
        }catch (Throwable ignored){
        }
    }


    public static class Lifter<T>
            implements BiFunction<Scannable, CoreSubscriber<? super T>, CoreSubscriber<? super T>> {

        /** Holds reference to strategy to prevent it from being collected. */

        @Override
        public CoreSubscriber<? super T> apply(Scannable publisher, CoreSubscriber<? super T> sub) {
            return sub;
        }
    }

    public static void main(String[] args) throws InterruptedException {
        Callable<String> callable = () -> {
            logger.info("Operation enter call1: ");
            Mono.just("test1").block();
            return "call1";
        };


        Mono.defer(() -> Mono.fromCallable(callable)
                             .publishOn(Schedulers.elastic())
                             .flatMap(source -> {
                                 logger.info("Again enter map :{} ", source);
                                 return Mono.just(source);
                             })).subscribeOn(Schedulers.single()).subscribe();


        TimeUnit.SECONDS.sleep(3);
    }
}

```
it will be report an error

```
Caused by: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread single-1
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83)
	at reactor.core.publisher.Mono.block(Mono.java:1707)
	at app.controller.TestHook.lambda$main$0(TestHook.java:42)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:57)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4455)
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:126)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

when I remove the hook,it will be all right

**Comment by will-zdu** [comment]
@chemicL @reactorbot  Please check my pre comment

**Comment by will-zdu** [comment]
@chemicL @reactorbot @dittos @pcdavid please check my pre coomment

**Comment by dittos** [comment]
I think `Mono.defer(() -> expression).subscribeOn(scheduler)` only guarantees that `expression` runs on the `scheduler`, not Mono generated from the expression is subscribed on the scheduler. (so nothing is wrong about callable being run on elastic OR single scheduler)

If you want to make sure that callable to be run on some specific scheduler, add subscribeOn just after the fromCallable like `Mono.fromCallable(() -> ...).subscribeOn(scheduler)`.

**Comment by chemicL** [comment]
Thanks for clarifying what is the business logic.

First things first.
I think it is reasonable to expect that the lambda provided to `Mono.fromCallable(callable)` executes on a specific `Scheduler`. In fact this is what the reactor documentation recommends in https://projectreactor.io/docs/core/release/reference/#faq.wrap-blocking.

However, it seems your expectation is that the lambda executes on a `Thread` from the `Scheduler` specified in the `publishOn()` operator that follows (as per initial report).

The fact that the lambda is executed there without the hook is a consequence of operator fusion from my understanding. The `publishOn` operator notices during assembly time, that the type of the source is a `MonoCallable` and delegates subscription to its own `Scheduler` to optimize delivery on the intended `Thread` meant for the receiver (or `Subscriber`):

https://github.com/reactor/reactor-core/blob/3.4.x/reactor-core/src/main/java/reactor/core/publisher/Mono.java#LL4002C30-L4002C30

When `Hooks` come into play, they erase the source type info from this optimization and the behaviour is actually correct.

IMO this is a bug, also present in 3.5 line. @OlegDokuka WDYT?

**Comment by will-zdu** [comment]
@chemicL  @OlegDokuka 
Isn't there a way to improve it? The above demo is to improve for me who reproduce this problem, it is not a real case encountered, the real case is like this
I am a programer to writing javaagent，to implement a apm system，we  need use hook  to link the different  opearation (span such as database ,http ) on a same transaction or trace,  We cannot modify the client's code，if our agent add our javaagent 
it will be report the exception

**Comment by will-zdu** [comment]
@chemicL @OlegDokuka   is ther any way to improve it , if do not imporve it ,it meas that ,any javaagent who add hooks to monitor reactor will be report the exception ,it meas a lot ,monitor reactor will caused exception ,wo have to lose observability on reactor,may be  can you give me anthor way to monitor reactor ?
