### ISSUE TITLE
Interrupt state not propagated when Thread interrupted during Blocking method call

### ISSUE THREAD

**Issue by 10sa** [reactor/reactor-core#3451]
If an InterruptedException is thrown during the operation, the Interrupt state is hidden by the BlockingOptionalMonoSubscriber classes. (Other implementations may have similar issues)

This implementation prevents the Thread.interrupted() method from determining if a thread is in the Interrupt state when an exception is thrown on the thread that called the block method.

## Expected Behavior
If the thread is interrupted while the block method is in the wait state, the Thread.interrupted() method should return true in the catch clause.

## Actual Behavior
The Thread.interrupted() method returns false, even though the thread was interrupted and an exception was thrown in the block method. 

## Steps to Reproduce
In the test code, the Thread.interrupted() assertion in the catch clause fails, even though we interrupted the thread that called the blockOptional method.

```java
@Test
public void interruptStateTest() throws InterruptedException {
	final Object lock = new Object();
	final Thread thread = new Thread(() -> {
		try {
			Mono.create(sink -> {
				try {
					Thread.sleep(1000);
					sink.success();
				}
				catch (InterruptedException e) {
					Thread.currentThread().interrupt();
				}
			}).blockOptional();
		}
		catch (Exception e) {
			e.printStackTrace();
			assertTrue(Thread.interrupted());
		}
		finally {
			synchronized (lock) {
				lock.notify();
			}
		}
	});
	
	thread.start();
	thread.interrupt();
	
	synchronized (lock) {
		lock.wait();
	}
}
```

## Possible Solution
When an InterruptedException exception is thrown, add `Thread.currentThread().interrupt();` to restore interrupt state the current thread and throw a custom exception.

### Example code
https://github.com/reactor/reactor-core/blob/324a64c3d7e21b9ec51c4e421a88c8a8689263b5/reactor-core/src/main/java/reactor/core/publisher/BlockingOptionalMonoSubscriber.java#L107-L116

Modify the above code as follows
```java
try {
	await();
}
catch (InterruptedException ex) {
	dispose();
	RuntimeException re = Exceptions.propagate(ex);
	//this is ok, as re is always a new non-singleton instance
	re.addSuppressed(new Exception("#blockOptional() has been interrupted"));

	// Restore interrupt state
	Thread.currentThread().interrupt();
	throw re;
}
```

## Your Environment
* Reactor version(s) used: 3.5.5
* Other relevant libraries versions (eg. `netty`, ...): None
* JVM version (`java -version`)
```
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b06, mixed mode)
```
* OS and version (eg `uname -a`): Windows 10, 22H2 19045.2913

**Comment by OlegDokuka** [comment]
Hi, @10sa!

You have an invalide example given. It never stops. You forgot to put `sink.error`/`throw e`, which ensures that blockOptional will be unblocked.

try the following to fix the issue, or enssure that the original issue is rethrown

```
@Test
public void interruptStateTest() throws InterruptedException {
	final Object lock = new Object();
	final Thread thread = new Thread(() -> {
		try {
			Mono.create(sink -> {
				try {
					Thread.sleep(1000);
					sink.success();
				}
				catch (InterruptedException e) {
					Thread.currentThread().interrupt();
					assertThat(Thread.interrupted()).isTrue();
					sink.error(e);
				}
			}).blockOptional();
		}
		catch (Exception e) {
			e.printStackTrace();
			assertThat(Thread.interrupted()).isTrue();
		}
		finally {
			synchronized (lock) {
				lock.notify();
			}
		}
	});

	thread.start();
	thread.interrupt();

	synchronized (lock) {
		lock.wait();
	}
}
```

Closing this one as invalid, but feel free to reopen it if you have another reproducer

**Comment by OlegDokuka** [comment]
@10sa 
welcome to create a PR with the mentioned fix ;)

**Comment by 10sa** [comment]
> @10sa welcome to create a PR with the mentioned fix ;)

Okay. I'll fix it and post a PR.
