### ISSUE TITLE
Documentation: emphasize that the order of subscribeOn matters

### ISSUE THREAD

**Issue by chemicL** [reactor/reactor-core#3452]
Following from #3450, it should be clarified in the documentation that the order of `subscribeOn` in the chain is significant, as opposed to what the documentation states in https://projectreactor.io/docs/core/release/reference/#schedulers.

**Comment by will-zdu** [comment]
@chemicL  @OlegDokuka  is ther any way to improve it , if do not imporve it ,it meas that ,any javaagent who add hooks to monitor reactor will be report the exception ,it meas a lot ,monitor reactor will caused exception ,wo have to lose observability on reactor,may be you can give me anthor way to monitor reactor

**Comment by will-zdu** [comment]
We combine multiple Spans executed on different threads into a single request's unique trace by monitoring Reactor.This is what APM monitoring needs to do. If hooks cause disruption to the code execution thread, it can prevent the use of APM monitoring and make it impossible to achieve observability in Reactor.

**Comment by will-zdu** [comment]
@chemicL @pcdavid  Please check my comment before

**Comment by pcdavid** [comment]
@will-zdu I think you're meaning to ping someone else, maybe with a similar GitHub id (laready in https://github.com/reactor/reactor-core/issues/3450#issuecomment-1537623909). I am not involved in reactor development. I think I may have fixed a typo a the doc once, but that's all.

**Comment by will-zdu** [comment]
> @will-zdu I think you're meaning to ping someone else, maybe with a similar GitHub id (already in [#3450 (comment)](https://github.com/reactor/reactor-core/issues/3450#issuecomment-1537623909)). I am not involved in reactor development. I think I may have fixed a typo a the doc once, but that's all.

sorry

**Comment by will-zdu** [comment]
@chemicL I submit an anthor issuse https://github.com/reactor/reactor-core/issues/3458 ,please check it too

**Comment by will-zdu** [comment]
@OlegDokuka   Observability is a concern that needs to be taken into consideration. Datadog and OpenTelemetry both implement monitoring for Reactor using a hook mechanism. As a developer of a Java agent, it is not possible to control the application's code.
https://github.com/DataDog/dd-trace-java/tree/16f2761b13dfe0a70c6b3aea7d4eb8e0b18dc12c/dd-java-agent/instrumentation/reactor-core-3.1
https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/389005ea11c2244593a526284c520c74e2429c89/instrumentation/reactor

It means that if someone write code like this,it will be ok without javaagent,but when add javaagent it wil be broken

**Comment by OlegDokuka** [comment]
@will-zdu can you please elaborate on the problem? do you mean the problem is that publishOn stops scheduling on different thread? when hook is added?

**Comment by will-zdu** [comment]
I am a Java probe developer. Our client needs to monitor Reactor, and we use Reactor's hook mechanism to achieve this. Our implementation mechanism is the same as Datadog and OpenTelemetry's Reactor monitoring. We cannot control the implementation of our client's code. If there is no suitable method, we can only give up our monitoring of Reactor

if our client write code like this,
```java
package app.controller;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import reactor.core.CoreSubscriber;
import reactor.core.Scannable;
import reactor.core.publisher.Hooks;
import reactor.core.publisher.Mono;
import reactor.core.publisher.Operators;
import reactor.core.scheduler.Schedulers;

import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;
import java.util.function.BiFunction;

public class TestHook {

    private static final Logger logger = LoggerFactory.getLogger(TestHook.class);

   
    public static void main(String[] args) throws InterruptedException {
        Callable<String> callable = () -> {
            logger.info("Operation enter call1: ");
            Mono.just("test1").block();
            return "call1";
        };


        Mono.defer(() -> Mono.fromCallable(callable)
                             .publishOn(Schedulers.elastic())
                             .flatMap(source -> {
                                 logger.info("Again enter map :{} ", source);
                                 return Mono.just(source);
                             })).subscribeOn(Schedulers.single()).subscribe();


        TimeUnit.SECONDS.sleep(3);
    }
}

```
Without our Java agent, this code works perfectly fine. However, after adding our probe, it throws an error during execution. This puts us in a difficult position, and if there is no better solution, we may have to give up monitoring Reactor.

We are using Reactor's hook mechanism to achieve cross-thread correlation for monitoring purposes. We are monitoring a single request and using the WebFlux technology stack. With Reactor, we can execute a synchronous database operation on other threads. We want to establish a relationship between the transaction on the web request thread and the database operation on other threads.

```java
 @Autowired
    private RedisTemplate redisTemplate;

    private static final Logger logger = LoggerFactory.getLogger(CallController.class);

    @GetMapping("/call1")
    public Mono<String> call1() throws InterruptedException {
        Callable<String> callable = new Callable<String>(){
            @Override
            public String call() throws Exception {
                ValueOperations valueOperations = redisTemplate.opsForValue();
                valueOperations.set("helloeeee","java");
                Mono.just("test").block();
                logger.info("Operation enter call1: ");
                return "call1";
            }
        };





        return Mono.defer(() -> Mono.fromCallable(callable)
                                    .publishOn(Schedulers.elastic())
                                    .flatMap(source -> {
                                        //                    ValueOperations valueOperations = redisTemplate.opsForValue();
                                        //                    valueOperations.get("helloeeee");
                                        logger.info("Again enter map :{} {}", source);
                                        return Mono.just(source);
                                    }));
    }
```
Like the code above, when a web request comes in, the Redis database operation is switched to another thread through Reactor (this may not be in line with Reactor's recommendations, but we can't control our clients' code). We need to associate call1() and the Redis call with the same transaction.

**Comment by OlegDokuka** [comment]
You need to suggest your client fixing their code pointing to reactor docs. There is no issue with your java agent

**Comment by will-zdu** [comment]
@OlegDokuka   If there is no better way, we can only disable our monitoring of the reactor. We must make every effort to ensure that adding our Java agent will not affect customers, even if it is due to issues in their code.
I still hope there is a way to avoid customers writing such code, or adding hooks that will not result in errors.

**Comment by OlegDokuka** [comment]
Well, just think a bit that tomorrow we disable publishOn behaviour you see today (assume this operator will never affect upstream since it is the default behaviour for this operator), would it also force you to abandon the whole tool or just motivate you to rework your code so it works properly

**Comment by will-zdu** [comment]
I am waiting for good news about Reactor, which is one of my favorite Java frameworks
