### ISSUE TITLE
Customize the Observation created by MicrometerObservationListener

### ISSUE THREAD

**Issue by nvervelle** [reactor/reactor-core#3455]
## Motivation

The current integration between reactor and micrometer, with `tap()` and `Micrometer.observation()`, only allows simple use cases for the creation of the `Observation` that will observe the reactive pipeline : it's currently not possible to provide a context supplier or a convention that will be used to create the `Observation`.

One example where the current solution is limiting is when using Kafka in spring boot where the listener is a `Flux`, each kafka message becoming an element of the `Flux`. It's not possible to extract the `traceparent` header from the kafka message to use it when creating the `Observation`.

## Desired solution

I'd like to be able to give more control on what `Micrometer.observation()` is doing. My idea is to be able to provide an optional `Function<ObservationRegistry, Observation>` so that the `Observation` will be created with as much customization as required.

## Considered alternatives

I first tried a solution that will not imply any modification on `reactor-micrometer` library : I had to copy/paste 3 package private classes from the library (`MicrometerObservationListener`, `MicrometerObservationListenerConfiguration` and `MicrometerObservationListenerFactory`) to be able to modify them. It's not a good solution in the long term, as it needs to keep the 3 modified classes in sync with the library.

## Additional context

I have submitted a PR with my ideas about the `Function<>`: https://github.com/reactor/reactor-core/pull/3456

**Comment by OlegDokuka** [comment]
Makes sense to me now. Do you mind signing CLA so i can merge your PR?

**Comment by nvervelle** [comment]
Hi @OlegDokuka, I've signed the CLA, so you can merge the PR if you want :+1:

**Comment by nvervelle** [comment]
Hi @OlegDokuka , any hope to merge the PR in the near future ?

**Comment by chemicL** [comment]
@nvervelle I asked for some tests and documentation in the PR, hopefully we can make this into the next release :)

**Comment by nvervelle** [comment]
@chemicL I've pushed a commit for the tests and documentation

**Comment by ajax-osadchuk-r** [comment]
This improvement will help my team a lot, we are also looking for a way to properly use the micrometer with the reactor-kafka.
@nvervelle your solution seems to actually what we need.
@chemicL Looking forward to get this feature released.

**Comment by chemicL** [comment]
@nvervelle thank you for the contribution! This change will be part of 3.5.8 and 3.6.0-M1 🚀  Looking forward to more contributions 👏
