### ISSUE TITLE
Second zipped Mono.fromRunnable(...) never executed

### ISSUE THREAD

**Issue by txema-martinez-scopely** [reactor/reactor-core#3495]
I've found a strange behaviour when zipping 2 `Mono`'s created from a `Runnable` and I think it may be a bug.

## Expected Behavior
Both `Mono`'s should be executed.

## Actual Behavior
Only the first `Mono` is executed.

## Steps to Reproduce
```java
@Test
public void testZipRunnables() {
    List<String> values = new ArrayList<>();
    Mono.zip(Mono.fromRunnable(() -> values.add("mono1")), Mono.fromRunnable(() -> values.add("mono2")))
            .block();
    assertThat(values).containsExactlyInAnyOrder("mono1", "mono2");
}
```

## Your Environment
* Reactor version(s) used: 3.5.6
* JVM version: OpenJDK 17.0.2
* OS and version: MacOS Big Sur 11.7.7

**Comment by gowa** [comment]
@txema-martinez-scopely , this seems to be awkward, but well-known behavior: https://yuanwang.ca/posts/zip-void-reactor.html .

'zip' generates a Mono of tuple. And it's empty if any of the 'elements' is empty, while Mono.fromRunnable is kind of empty. Maybe, the absence of necessity to calculate anything after the first Publisher was empty, gives the above behavior

**Comment by OlegDokuka** [comment]
You need to use `Mono.when` for void sources
