### ISSUE TITLE
Context propagation error with io.micrometer

### ISSUE THREAD

**Issue by JaEdmuva** [reactor/reactor-core#3499]
I have a Spring boot 3.1.0/webflux/reactor 3.5.6
When using reactor 3.5.3 or after (as indicated in the documentation (https://micrometer.io/docs/observation#instrumentation_of_reactive_libraries_after_reactor_3_5_3)
 with the Hook API:

Hooks.enableAutomaticContextPropagation();

It will generate an error due to an update in io.micrometer.context-propagation API. It will no longer allow to call the .reset() in the ThreadLocalAccessor interface since it's been deprecated, resulting in an exception like this:

IllegalStateException(this.getClass().getName() + "#reset() should  not be called. Please implement #setValue() method when removing the #reset() implementation.");

## Expected Behavior
The context propagation should be executed without errors

## Actual Behavior
An exception is thrown when enabling automatic context propagation

## Possible Solution
IF it's simple as that, the solution would be to call the restore(V previousValue) or setValue(previousValue) method to actually 'reset' the state

## Your Environment
Springboot 3.1.0
io.micrometer:micrometer-tracing-bridge-otel:1.1.2

* Reactor version(s) used: 3.5.6
* Other relevant libraries versions (eg. `netty`, ...): reactor-netty-http:1.1.7
* JVM version (`java -version`): 17
* OS and version (eg `uname -a`): mac os

**Comment by OlegDokuka** [comment]
Hello, @JaEdmuva !

Can you please provide a reproducer!

Thanks,
Oleh

**Comment by zoobert** [comment]
I believe this simple case is related to the issue described above. However, it requires jwt authentication of the endpoint and is related to the recent (soon-to-be released) changes in Spring Boot 3.1.1.

**Comment by chemicL** [comment]
@zoobert I don't think these are related. Please report this against [spring-security](https://github.com/spring-projects/spring-security/issues) (as also suggested by @bclozel in https://github.com/micrometer-metrics/micrometer/issues/3916#issuecomment-1601416597).

After a quick glance my suspicion is that the `Observation` wrapping that Spring Security performs collides with the identity of the current `Observation` in scope, for which micrometer recently added checks. Perhaps a wrapped `Observation` should report the identity of the delegate as its own. Those are just some ideas, I think it should be analysed separately from this issue.

**Comment by chemicL** [comment]
In 3.5.7 the new API of _context-propagation_ is used. It's up to the implementor of the `ThreadLocalAccessor` contract to provide a proper, backwards compatible migration plan. If you get this exception from micrometer's `ObservationThreadLocalAccessor`, this issue should be reported in the micrometer repository. As a backwards compatible use of the 1.0.3 API of _context-propagation_ is in 3.5.7, I'm closing the issue for now. Please open a new issue if you believe we got something wrong and have a reproducer.

**Comment by JaEdmuva** [comment]
@chemicL Thank you for reaching out. Actually v1.0.3 API has deprecated the .reset() method. Apparently this upgrade was not really tested. Although I agree that the implementor should provide backwards compatibility as well.
