### ISSUE TITLE
Introduce a variation of `contextCapture` that captures the context immediately

### ISSUE THREAD

**Issue by dstepanov** [reactor/reactor-core#3501]
Currently, `contextCapture` is:

> a convenience shortcut to capture thread local values during the subscription phase and put them in the Context that is visible upstream of this operator
	
Personally, I don't see it much useful as the actual subscription might be way outside of the user code.

It would be nice to have something like `currentContextCapture` as that would capture the current thread-local context and add it to the reactor context, something like:

```java
var newCtx = capturedContextFromThreadLocal();
mono.contextWrite(ctx -> ctx + newCtx);
```

One of the use cases would be:
```java
// update MDC context
mono.currentContextCapture()
// delete MDC context
// The MDC context is propagate to all the operators
```

**Comment by OlegDokuka** [comment]
Hello, @dstepanov!

Can you please provide a certain usecase where contextCapture does not work (test or any reproduceable example with explicit expectations) 

Thanks,
Oleh

**Comment by dstepanov** [comment]
In Micronaut integration I need to capture the context manually https://github.com/micronaut-projects/micronaut-reactor/pull/306/files#diff-6bfb100b108ce8193896caf0431107f8a207233bd1545b7ac94e692a001ea901R38

**Comment by dstepanov** [comment]
This is an enhancement request, not a bug report.

The `contextCapture` works as the JavaDoc describes. I think it should be named `contextCaptureOnSubscribe` as it is confusing that the capture is postponed and nothing is captured on the method invocation.

My use case differs. I have a try-resources block that modifies the thread-local. This state I want to capture into the Reactor context immediately on some new method invocation. There might be better naming than `capture` here as I wish to extend it with any possible new thread-local state.

**Comment by chemicL** [comment]
I agree with the sentiment and I think we could consider `contextCaptureNow()` as a new operator that captures during assembly time, on the spot, when the method is invoked. It feels more intuitive to capture at the time of assembling. Subscription-time capture is out of the control of the person assembling the pipeline and can be useful when an assembled pipeline is reused for more subscribers, but the regular case would be to assume the `ThreadLocal` values are present when assembling the pipe. @OlegDokuka WDYT?

**Comment by chemicL** [comment]
For a year there have not been any requests for this. It seems this is not really necessary in the end.
