### ISSUE TITLE
"How Do I Ensure Thread Affinity when I Use publishOn()"  demo has compile error

### ISSUE THREAD

**Issue by manzhizhen** [reactor/reactor-core#3502]
C.6. How Do I Ensure Thread Affinity when I Use publishOn()?
https://projectreactor.io/docs/core/release/reference/#faq.thread-affinity-publishon

```java
Flux<Integer> source = Sinks.many().unicast().onBackpressureBuffer().asFlux();
source.publishOn(scheduler1)
	  .map(i -> transform(i))
	  .publishOn(scheduler2)
	  .doOnNext(i -> processNext(i))
	  .subscribe();
```

should be ：

```java
Sinks.Many<Integer> dataSinks = Sinks.many().unicast().onBackpressureBuffer();
Flux<Integer> source = dataSinks.asFlux();
source.publishOn(scheduler1)
	  .map(i -> transform(i))
	  .publishOn(scheduler2)
	  .doOnNext(i -> processNext(i))
	  .subscribe();
```

**Comment by tejavenkatlanka** [comment]
Hi @manzhizhen / @OlegDokuka , Can I fix this ?.

**Comment by chemicL** [comment]
Feel free to open a PR.

**Comment by tejavenkatlanka** [comment]
create a PR to main brach. please let me know if it has to merge to any feature branch

**Comment by chemicL** [comment]
@tejavenkatlanka thanks for the contribution! No need to change the branch, I merged it into main, which stands for current, 3.5.x release line.
