### ISSUE TITLE
Is it safe to use a Map/Reference Object in the reactor context?

### ISSUE THREAD

**Issue by 1528110566** [reactor/reactor-core#3509]
https://stackoverflow.com/questions/76337536/is-it-safe-to-use-a-map-reference-object-in-the-reactor-context

What if I put a Map/Reference Object in reactor context?

```java
Mono.just(1)
        .flatMap(item -> {
            return Mono.deferContextual(ctx -> {
                Map<String, String> temp = ctx.get(CONTEXT_KEY);
                // put something into MAP. <1>
                temp.put(MAP_KEY, "value");
                return Mono.just(item);
            });
        })
        .flatMap(item -> {
            return Mono.deferContextual(ctx -> {
                Map<String, String> temp = ctx.get(CONTEXT_KEY);
                // effected by context which modified in operators above. <2>
                // print `value`
                System.out.println(temp.get(MAP_KEY));
                return Mono.just(item);
            });
        })
        // put contextWrite at the down of the chain, ensure operators above could see the MAP.
        .contextWrite(ctx -> ctx.put(CONTEXT_KEY, new HashMap<String, String>()))
        .subscribe();
```

As we all known, `context` will affect operators above it, and the order is `from z to a`. The example above put a `HashMap` in `context`, and modified it in step 1, which affect step 2. Now the order seems like `from a to z`, and I can use it like a `ThreadLocal`.

So I want to known is this operation legal? Does any performance issues occur if the MAP is very big? Or does it cause a thread-safe problem?

**Comment by chemicL** [comment]
It's difficult to answer these questions without a particular execution context in mind. The question belongs to StackOverflow, so I'm closing the issue.

Having said that, here's my attempt at answering:
> So I want to known is this operation legal?
It is legal, but the consequences of writing to the map depend on the actual flow of operations. It's best to treat the Context as read-only.

> Does any performance issues occur if the MAP is very big?
It's not a question relevant to reactor. Performance/memory impact is something to measure in a particular scenario.

> Or does it cause a thread-safe problem?
It definitely is a concern, as flatMap can execute on multiple Threads.
