### ISSUE TITLE
The timeout behavior in Mono.block(timeout)

### ISSUE THREAD

**Issue by anuchandy** [reactor/reactor-core#3519]
The `Mono.block(timeout)` API throws an "IllegalStateException" with the error text "Timeout on blocking read for ..." when the timeout expires.

I wonder if it should instead throw "TimeoutException"? This is how typical Java blocking APIs behave - for example CompletableFuture.get(timeout) [reference](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#get-long-java.util.concurrent.TimeUnit-). 

Is it possible to address this? The "IllegalStateException" exception is so generic that it's impossible to distinguish when an API that takes timeout throws this for timeout reasons.

Or at least the "IllegalStateException" with cause as TimeoutException. But I think for the ease of use, the users are likely to prefer direct throwing of "TimeoutException" instead of catching "IllegalStateException" and unwrapping the cause.

**Comment by OlegDokuka** [comment]
Hello, @anuchandy!

Thank you for your question!
Unfortunately, we can not use `TimeoutException` since it is a checked exception. This means we can not throw it without explicit checked exception declaration at the API level which can be inconvenient for many users.

Best,
Oleh

**Comment by anuchandy** [comment]
@OlegDokuka I see, that make total sense and is a breaking change. Thanks for clarifying!

What’s your thought on including TimeoutException as the cause in the IllegalStateException?, would that be better user experience instead of the application pattern matching the error message ? 

The reason I’m asking is, TimeoutException is retriable in many cases, whereas IllegalStateException may not be and is generic. So having the cause indicating the reason as TimeoutException instance seems like a better experience in this case. What do you think?
