### ISSUE TITLE
Reactor logs exception declared as constant differently than created with new

### ISSUE THREAD

**Issue by abialas** [reactor/reactor-core#3552]
We are using reactor-kafka to consume records from a topic. When we miss some value in cache we just throw an exception and later we handle it (send to dlq, log). Recently I have seen RecordTooLargeException when sending to dlq. When I open the stacktrace which was sent along with a record to dlq it was huge. I have seen multiple times same logs.

> Assembly trace from producer [reactor.core.publisher.MonoCallable] :
> 	reactor.core.publisher.Mono.fromCallable
> 	com.s.domain.WebhookHandler.handle(WebhookHandler.java:40)
> Error has been observed at the following site(s):
> 	*___Mono.fromCallable ⇢ at com.s.domain.webhook.WebhookHandler.handle(WebhookHandler.java:40)
> 	|_        Mono.filter ⇢ at com.s.domain.webhook.WebhookHandler.handle(WebhookHandler.java:41)
> 	|_           Mono.map ⇢ at com.s.domain.webhook.WebhookHandler.handle(WebhookHandler.java:42)
> 	|_ Mono.switchIfEmpty ⇢ at com.s.domain.webhook.WebhookHandler.handle(WebhookHandler.java:43)
> 	*________Mono.zipWith ⇢ at com.s.domain.webhook.WebhookHandler.handleWebhook(WebhookHandler.java:27)
> 	|_       Mono.flatMap ⇢ at com.s.domain.webhook.WebhookHandler.handleWebhook(WebhookHandler.java:28)
> 	|_          Mono.then ⇢ at com.s.domain.webhook.WebhookHandler.handleWebhook(WebhookHandler.java:36)
> 	|_      Mono.doOnEach ⇢ at com.s.domain.webhook.WebhookConsumer.handleReceivedRecord(WebhookConsumer.java:65)
> 	|_     Mono.doOnError ⇢ at com.s.domain.webhook.WebhookConsumer.handleReceivedRecord(WebhookConsumer.java:66)
> 	|_     Mono.doOnError ⇢ at com.s.domain.webhook.WebhookConsumer.handleReceivedRecord(WebhookConsumer.java:70)
> 	*___Mono.fromCallable ⇢ at com.s.domain.webhook.WebhookHandler.handle(WebhookHandler.java:40)
> 	|_        Mono.filter ⇢ at com.s.domain.webhook.WebhookHandler.handle(WebhookHandler.java:41)
> 	|_           Mono.map ⇢ at com.s.domain.webhook.WebhookHandler.handle(WebhookHandler.java:42)
> 	|_ Mono.switchIfEmpty ⇢ at com.s.domain.webhook.WebhookHandler.handle(WebhookHandler.java:43)
> 	*________Mono.zipWith ⇢ at com.s.domain.webhook.WebhookHandler.handleWebhook(WebhookHandler.java:27)
> 	|_       Mono.flatMap ⇢ at com.s.domain.webhook.WebhookHandler.handleWebhook(WebhookHandler.java:28)
> 	|_          Mono.then ⇢ at com.s.domain.webhook.WebhookHandler.handleWebhook(WebhookHandler.java:36)
> 	|_      Mono.doOnEach ⇢ at com.s.domain.webhook.WebhookConsumer.handleReceivedRecord(WebhookConsumer.java:65)
> 	|_     Mono.doOnError ⇢ at com.s.domain.webhook.WebhookConsumer.handleReceivedRecord(WebhookConsumer.java:66)
> 	|_     Mono.doOnError ⇢ at com.s.domain.webhook.WebhookConsumer.handleReceivedRecord(WebhookConsumer.java:70)

What is interesting is we throw exception from constant:

```
CustomException CUSTOM_EXCEPTION = new CustomException("dummy message);

  private Mono<String> handle(String value) {
    return Mono.fromCallable(() -> {
          if (value.contains("dummy")) {
            throw CUSTOM_EXCEPTION;
          } else {
            return value;
          }
        })
        .filter(not(String::isBlank))
        .map(this::someMapping)
        .switchIfEmpty(
            Mono.defer(
                () ->
                    Mono.error(new RuntimeException("should not happened"))));
  }
```

When I send I record which fails I see single logs, when I send second record I see duplicated roots in stacktrace. When I send third failed record I see same roots three times.

However, when I change:

`throw CUSTOM_EXCEPTION;`

to:

`throw new CustomException("dummy message);`

I see correct logs (just once, not duplicated).

We use ReactorDebugAgent.

Does Reactor differently handle Exceptions created with `new` and from constant?

## Expected Behavior

Roots in the stacktrace should be single for single processing.

## Actual Behavior

Roots in the stacktrace are duplicated as many times as error occurs.

## Your Environment

* Reactor version(s) used: 3.4.30
* JVM version (`java -version`): Temurin-17.0.6+10

**Comment by OlegDokuka** [comment]
@abialas that is a known issue. We can do nothing as of now. However, there are few things you can do: 

1. Avoid usage of the static exceptions within a reactor flow. You can map existing exceptions using the `onErrorMap` operator
2. disable stack trace and suppression. e.g: 
```java
static final class StaticThrowable extends Error {

		StaticThrowable(String message) {
			super(message, null, false, false);
		}

		StaticThrowable(String message, Throwable cause) {
			super(message, cause, false, false);
		}

		StaticThrowable(Throwable cause) {
			super(cause.toString(), cause, false, false);
		}
	}
```
