### ISSUE TITLE
ContextPropagation  incompatible with micrometer v1.0.3 or higher

### ISSUE THREAD

**Issue by renatomariscal** [reactor/reactor-core#3553]
## Expected Behavior
Context propagation should work.

## Actual Behavior
Thrown exception: `io.micrometer.context.ContextRegistry$1#reset() should not be called. Please implement #setValue() method when removing the #reset() implementation.`

## Steps to Reproduce

I am attempting to set the context propagation to propagate Open Telemetry:
```java
...
import io.opentelemetry.context.Context;

@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        Hooks.enableAutomaticContextPropagation();
        ContextRegistry.getInstance()
                .registerThreadLocalAccessor("OTEL_CONTEXT",
                        () -> Context.current(),
                        (context) -> context.makeCurrent(),
                        () -> Context.root().makeCurrent()

                );
        SpringApplication.run(Application.class, args);
    }
}

```

## Possible Solution

It seems like when the previous value was undefined (`null`) , this code attempts to use `reset`:

https://github.com/reactor/reactor-core/blob/5f5435fe8029ed61a7bc15dd3836ef99f9d18416/reactor-core/src/main/java/reactor/core/publisher/ContextPropagation.java#L95-L100

Which calls the deprecated method:
https://github.com/micrometer-metrics/context-propagation/blob/5a6c71ae4821cdb1f5a8b1b842c5ce3843c48e85/context-propagation/src/main/java/io/micrometer/context/ThreadLocalAccessor.java#L89-L92

```java
    @Deprecated
    default void reset() {
        throw new IllegalStateException(this.getClass().getName() + "#reset() should "
                + "not be called. Please implement #setValue() method when removing the " + "#reset() implementation.");
    }
 ```

It seems like the issue started with `context-propagation` version `1.0.3`, the code doesn't cause the same error with `1.0.2`.

## Your Environment
```xml
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>context-propagation</artifactId>
            <version>1.0.4</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.5.8</version>
        </dependency>
```

**Comment by chemicL** [comment]
The code you point to should not be run on versions >= 1.0.3 of context-propagation library. There is a runtime check. Perhaps the actual dependency resolution brings in a different dependency of reactor-core at runtime, which is incompatible with future versions of context-propagation. Please validate. Possibly, provide a reproducible setup.

**Comment by xodiumluma** [comment]
@renatomariscal did you explicitly add the newest version of context-propagation? 
I know that sometimes devs do this because of security scanners flagging potential vulnerability, whether it's a false alarm or not, such as Twistlock/Prisma Cloud. So managers come asking, why is your security dashboard red? The only way to get it green is to add an explicit dependency of the latest version. This was the case with snakeyaml last year.

**Comment by OlegDokuka** [comment]
@xodiumluma can you make sure that reactor-core is >= 3.5.7? We know that 3.5.6<= are incompatible (unfortunatelly, there is a breaking change in micrometer context-propagation library which should be adressed with 1.0.4). however, with 3.5.7 and higher we did a proper workaround to handle that incompatibility. Thus, extra input on your dependency tree is aprecciated

**Comment by renatomariscal** [comment]
I see, I had assumed the version declared directly on my `pom` would've been prioritized, I failed for not checking the actual resolved dependency.

I was effectively using  reactor-core 3.5.6 defined by `io.projectreactor:reactor-bom:2022.0.7` (which was brought by spring boot).

By inserting the latest reactor-bom `2022.0.9`, I know get `3.5.8` which works. Thanks a lot!

_PS: Out of curiosity, why is reactor-core context propagation dependent on micrometer? It does sound like something which should belong here._

**Comment by OlegDokuka** [comment]
@renatomariscal we do have compile time dependency. IT should be fine If micrometer context-propagation is not available since we do runtime check for class path availability. However, the 1.0.3 brought important bug fixes (although we failed to detect backward incompatibility on-time), that is why no there is some pitfalls in versions compatibility.


Anyways, seems that issues is resolved, and on behalf of the team I apologies for the inconvenience 🙇

Best,
Oleh

**Comment by xodiumluma** [comment]
Hi. Sorry I was sick. Latest deps WFM.
https://github.com/xodiumluma/reactor-context-propagation-test/blob/master/app/build.gradle
```
    implementation 'io.projectreactor:reactor-core:3.5.8'
    implementation 'org.reactivestreams:reactive-streams:1.0.4'
    implementation 'io.micrometer:micrometer-core:1.11.2'
    implementation 'io.micrometer:context-propagation:1.0.4'
    implementation 'org.slf4j:slf4j-api:2.0.7'
```
(just run `./gradlew test` - caveat - I used JDK 21 + Gradle Wrapper 8.2.1 - not supported config, but I was trying to build `reactor-core` from scratch, couldn't be bothered to swap out JDK hahaha :laughing: )

**Comment by xodiumluma** [comment]
> I see, I had assumed the version declared directly on my `pom` would've been prioritized, I failed for not checking the actual resolved dependency.
> 
> I was effectively using reactor-core 3.5.6 defined by `io.projectreactor:reactor-bom:2022.0.7` (which was brought by spring boot).
> 
> By inserting the latest reactor-bom `2022.0.9`, now I get `3.5.8` which works. Thanks a lot!
> 
> _PS: Out of curiosity, why is reactor-core context propagation dependent on micrometer? It does sound like something which should belong here._

Hi @renatomariscal 

Although the micrometer project is for telemetry, it has a separate library which is very useful for propagating contexts, hence the [micrometer context propagation library](https://github.com/micrometer-metrics/context-propagation). 

The micrometer bit is just in name. There is no actual micrometer dependency, unless I'm wrong...
- https://github.com/micrometer-metrics/context-propagation/blob/main/buildscript-gradle.lockfile
- https://github.com/micrometer-metrics/context-propagation/blob/main/build.gradle
