### ISSUE TITLE
Apply contextCapture automatically in `await` function

### ISSUE THREAD

**Issue by be-hase** [reactor/reactor-core#3563]
## Motivation

This is a similar issue.
https://github.com/reactor/reactor-core/issues/3406

For users using kotlin coroutine, [ThreadContextElement](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-thread-context-element/) is used to propagate MDC, etc.

The block operator is supported by [Hooks.automaticContextPropagation](https://github.com/reactor/reactor-core/pull/3420), but not the await function. Therefore, we are forced to write it this way.

```kotlin
// e.g. WebClient

webClient.post()
    .uri("...")
    // omitted
    .contextCapture()
    .awaitSingle()
```

It would be great if the await function is also supported, like the block operator.

...However, the await function is implemented on the coroutine side, so perhaps a request should be made on the coroutine side.
https://github.com/Kotlin/kotlinx.coroutines/blob/1ccc96890d38be52d1bdcd31af5befb54804aa05/reactive/kotlinx-coroutines-reactor/src/Mono.kt#L46

**Comment by be-hase** [comment]
Sorry, I was wrong in my verification and the problem did not occur even with `await`.
I'll close this issue.

**Comment by be-hase** [comment]
I have created a sample project.
https://github.com/be-hase/context-propagation-report-202309

The code is in one file.
https://github.com/be-hase/context-propagation-report-202309/blob/main/coroutines-issue/src/main/kotlin/example/CoroutinesIssueApplication.kt

You can start it with the following command.
```` .
. /gradlew :coroutines-issue:bootRun 
```

**Comment by be-hase** [comment]
I found that the following workaround can be done using the `ContextInjector` mechanism provided by the coroutines side.
- https://github.com/Kotlin/kotlinx.coroutines/blob/7e2d23740c71b8ec5a7e2440f02b36e0519496a6/reactive/kotlinx-coroutines-reactive/src/ContextInjector.kt
- https://github.com/Kotlin/kotlinx.coroutines/blob/7e2d23740c71b8ec5a7e2440f02b36e0519496a6/reactive/kotlinx-coroutines-reactor/src/Mono.kt#L47

```kotlin
package example

import kotlinx.coroutines.InternalCoroutinesApi
import kotlinx.coroutines.reactive.ContextInjector
import org.reactivestreams.Publisher
import reactor.core.publisher.Flux
import reactor.core.publisher.Mono
import kotlin.coroutines.CoroutineContext

@OptIn(InternalCoroutinesApi::class)
class ContextCaptureInjector : ContextInjector {
    override fun <T> injectCoroutineContext(publisher: Publisher<T>, coroutineContext: CoroutineContext): Publisher<T> {
        return when (publisher) {
            is Mono -> publisher.contextCapture()
            is Flux -> publisher.contextCapture()
            else -> publisher
        }
    }
}
```

**Comment by OlegDokuka** [comment]
@be-hase please move reopen this ticket at kotlin side since we can nothing to do at the reactor one

**Comment by be-hase** [comment]
OK, I'll reopen issue. thanks :)

**Comment by be-hase** [comment]
reopend here: https://github.com/reactor/reactor-kotlin-extensions/issues/59
