### ISSUE TITLE
"distinct" hangs forever when duplicate emitted in Flux.create

### ISSUE THREAD

**Issue by xabgesagtx** [reactor/reactor-core#3569]
## Expected Behavior

When I create a Flux using `Flux.create` and use `distinct` on it, I should be able consume all distinct elements.

## Actual Behavior

After applying `distinct` on a Flux that was created with `Flux.create` trying to block or to consume all the elements hangs forever.

Small notes on this:
* I did not observe this hanging behavior when there are no duplicates
* also, this doesn't seem to be the case for Fluxes that were created differently (e.g. `Flux.just` or `Flux.fromIterable`)

## Steps to Reproduce

```java
@Test
void reproCase() {
        Flux<String> flux = Flux.<String>create(sink -> {
            sink.next("test1");
            sink.next("test1");
            sink.next("test2");
            sink.complete();
        }).distinct();
        StepVerifier.create(flux)
                .expectNext("test1")
                .expectNext("test2")
                .verifyComplete();
}
```

This code is/was working in reactor version 3.5.7 but started hanging forever after updating to version 3.5.9

## Your Environment

* Reactor version(s) used: 3.5.9
* Other relevant libraries versions (eg. `netty`, ...): 
  * spring-boot: 3.1.3
  * netty: 4.1.97.Final
* JVM version (`java -version`): Temurin-17.0.4.1+1 
* OS and version (eg `uname -a`): Ubuntu 22.04.1

**Comment by echatman-ias** [comment]
I am encountering this as well.

**Comment by echatman-ias** [comment]
Works in `3.5.8`, broken in `3.5.9`

**Comment by echatman-ias** [comment]
Still broken in `3.5.10`

**Comment by simondaudin** [comment]
Hello, I'm having a similar problem with a slightly different code 
```
Flux<Integer> flux = Flux.<Integer>create(sink -> {
        sink.next(1);
        sink.next(2);
        sink.complete();
    })
    .doOnRequest(v -> System.out.println("requested: "+v))
    .filter(i -> i % 2 == 0);

StepVerifier.create(flux)
    .expectNext(2)
    .verifyComplete();
```
Which results in 
```
requested: 9223372036854775807
requested: 1
```
Then it hangs forever

My guess is that it might be related to https://github.com/reactor/reactor-core/pull/3557
After some digging, in the second request, https://github.com/reactor/reactor-core/blob/7f9c77ec28dc0bdfc1eafe04062cb1195fd9b552/reactor-core/src/main/java/reactor/core/publisher/FluxCreate.java#L530
`consumer` is null, and then troubles happen.
