### ISSUE TITLE
Better documentation of how to contribute a custom operator.

### ISSUE THREAD

**Issue by He-Pin** [reactor/reactor-core#3570]
## Motivation

Better understanding the internal of reactor-core.

## Desired solution

Add some document of how to contribute a new stream operator, where to start, eg, how to implement a `map` , or `filter` operator.

**Comment by OlegDokuka** [comment]
@He-Pin this series of talks could be a good start -> https://www.youtube.com/watch?v=uBUDM3dVD3A.

**Comment by chemicL** [comment]
This hasn't been picked up. With the above series from @OlegDokuka I think it's enough for someone encountering this issue in the future.
