### ISSUE TITLE
Mono timeout behavior different in version 3.5.9

### ISSUE THREAD

**Issue by balatbn** [reactor/reactor-core#3576]
We are migrating from version 3.4.25 to 3.5.9. During migration we found that timeout on Mono behaves differently.

Example code:

```java
  @Test
  public void testTimeout() {

    Mono<String> stringMono = Mono.just("data")
      .map(f -> {
        try {
          Thread.sleep(Duration.ofSeconds(3).toMillis());
        } catch (InterruptedException e) {
          e.printStackTrace();
        }
        return "value";
      })
      .timeout(Duration.ofSeconds(1))
      .subscribeOn(Schedulers.parallel());

    try {
      final String block = stringMono.block();
      System.out.println("Got output " + block);

    } catch (Exception ignore) {
      System.out.println("No output");
    }
  }
```
This code used to work in version 3.4.25. i.e., we used to get an exception and code printed `No output`. With 3.5.9, we are not getting time out exception.

## Expected Behavior
Print message should be "No output"

## Actual Behavior
"Got output value" is printed

## Steps to Reproduce
Refer code sample above

## Your Environment

* Reactor version(s) used: 3.5.9
* JVM version (`java -version`): 11
* OS and version (eg `uname -a`): Cent OS 7

**Comment by chemicL** [comment]
I just tested this against 3.4.25 and it prints out `Got output value`. Is this the actual code you're running?

**Comment by balatbn** [comment]
I re-ran the test case again(same code) and it is printing "No output" with `3.4.25`.

Ignoring versions, our understanding is this code should print "No output". Why are we getting "Got output" here?

**Comment by chemicL** [comment]
Interesting, I even tried running against earlier, 3.4.20 version, still the same behaviour.

To the point, though:

> our understanding is this code should print "No output".

That would seem reasonable, except for the fact that the code is against the reactive principles. Your map operator is performing a **blocking** call (`Thread#sleep`). If, as the documentation suggests, before blocking, you add `publishOn(Schedulers.boundedElastic)`, you should get the expected result.

Once we start working with examples that break the assumptions, it's difficult to determine what the behaviour should be. I'm not saying the behaviour is 100% correct – perhaps we have an issue. But, from what I see, nothing changed between these versions in the `timeout` operator. And my empirical tests show no behaviour change.

If you manage to provide a valid (non-blocking, or blocking in the dedicated boundedElastic threads) example, that breaks the expectations of the `timeout` operator then we have something to work on.
