### ISSUE TITLE
Different behaviors on different VMs

### ISSUE THREAD

**Issue by MoosArga** [reactor/reactor-core#3577]
I have an API in spring Boot that returns a Mono. This API calls different consumers with imbricated Mono.zip. When I call this API on a windows platform and an error occurs in one of the consumers, i have three kind of behaviors : 
- On Chrome : response appears on network but never catched by our client app (Angular) 
- On Firefox : nothing appears on network and of course never catched by our client app 
- On Postman : Error : aborted

If i call this API from a Linux platform (Dockerized or bare server) same behavior on Chrome, Firefox and Postman and our client app catchs the error. 

## Expected Behavior
Same behavior on all environments / VMS

## Your Environment

Java 11 
Kotlin 1.6.0
Spring Boot 2.4.12 (with webslufx starter subdependencies)
reactor-kotlin-extensions 1.1.10

(Sorry for my english, not my native language)

**Comment by chemicL** [comment]
The spectrum of the question is really, really broad. Best thing to do is to observe the actual behaviour using something simple, e.g. `curl`. But before that - where is the API running? Are you running the boot application on the same VM as the tool you're calling its API? In that case it's not certain whether the clients used on Windows are to blame or the Boot app running on Windows. Once you identify whether it's the app that is at fault and you have a reproducible example which we can work with, e.g. validating it using a developer-grade tool, such as curl, we can help determine which project this issue would belong to in the first place.

BTW. If it is not a reactor/spring -specific bug report, but rather a question regarding your setup, consider using StackOverflow for that purpose.

I'm closing the issue for now, please reopen if you have successfully identified the component responsible and can give us a reproducer.

**Comment by MoosArga** [comment]
Thanks for you answer and your reactivity, i will try to find a way to reproduce it easily. Actually, this a teammate project, i'm gonna try to make a sample project based on what we have noticed.
