### ISSUE TITLE
reactor.core.publisher.FluxCreate.BaseSink#request   throw NullPointerException 

### ISSUE THREAD

**Issue by qinarmy-zoro** [reactor/reactor-core#3579]
reactor.core.publisher.FluxCreate.BaseSink#request() throw   NullPointerException ,because  this.requestConsumer is null .
NullPointerException cause reactor.core.publisher.FluxFilter.FilterSubscriber cancel ,but downtream don't cancel ,so stream never end .

## Expected Behavior

on line test use case : https://github.com/QinArmy/jdbd-mysql/blob/master/src/test/java/io/jdbd/mysql/simple/ReportBugTests.java
```java
public class ReportBugTests {

    private static final Logger LOG = LoggerFactory.getLogger(ReportBugTests.class);

    private static final Executor EXECUTOR = Executors.newFixedThreadPool(1);


    @Test
    public void reportBug() {
        final Consumer<FluxSink<Integer>> consumer = sink -> EXECUTOR.execute(() -> {
            for (int i = 255; i < 300; i++) {
                sink.next(i);
            }
            sink.complete();
        });
        Flux.create(consumer)
                .filter(num -> {
                    LOG.info("num : {}", num);
                    return num < 100;
                })
                .blockLast();
    }

}
```
 
## Steps to Reproduce

```java

```

## Possible Solution

reactor.core.publisher.FluxCreate.BaseSink#request 
```java
	       @Override
		public final void request(long n) {
			if (Operators.validate(n)) {
				long s = addCap(this, n);

				if (hasRequestConsumer(s)) {
					LongConsumer consumer = requestConsumer;
					if (consumer!= null && !isCancelled()) {
						consumer.accept(n); // due to here NullPointerException ,so bug
					}
				}

				onRequestedFromDownstream();
			}
		}
```
## Your Environment

* Reactor version(s) used: reactor-core-3.5.10 
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`):  all 
* OS and version (eg `uname -a`): mac

**Comment by qinarmy-zoro** [comment]
You so slow

**Comment by qinarmy-zoro** [comment]
Westerners' work efficiency is too low

**Comment by OlegDokuka** [comment]
#3569 same issue
