### ISSUE TITLE
Premature thread interruption in a Flux buffer when calling blocking code

### ISSUE THREAD

**Issue by mtricht** [reactor/reactor-core#3587]
When calling code that could block such as the `elasticsearch-java` library, which uses the Apache HTTP client, from inside a `Flux` after a `bufferTimeout` I'm getting weird behavior.

## Expected Behavior
After the last element of a `Flux` using a `bufferTimeout`, I expect the thread to not be interrupted until everything is finished.

## Actual Behavior
After the last element of a `Flux` using a `bufferTimeout`, the thread is interrupted.

## Steps to Reproduce

```java
var logger = LoggerFactory.getLogger(Main.class);
Flux.range(0, 25)
        .doOnNext(number -> {
            // Would be a call to the elasticsearch-java library
            try {
                Thread.sleep(250);
            } catch (InterruptedException e) {
                logger.error("This doesn't get interrupted");
            }
            logger.info("Working on " + number);
        })
        .bufferTimeout(5, Duration.ofMillis(100))
        .doOnNext(numbers -> {
            // Would be a call to the elasticsearch-java library
            try {
                Thread.sleep(250);
            } catch (InterruptedException e) {
                logger.error("Flux after buffer interrupted");
                System.exit(1);
            }
            logger.info("Working on a list of size " + numbers.size());
        })
        .ignoreElements()
        .block();
```

Workaround is to make sure the buffer timeout runs on a new scheduler like so (I think):

```diff
    .bufferTimeout(5, Duration.ofMillis(100))
+   .publishOn(Schedulers.single())
```

Or to replace `bufferTimeout` with `buffer`.

## Your Environment

* Reactor version(s) used: 3.4.24 in production, 3.5.10 in reproducible repository
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): 17
* OS and version (eg `uname -a`): Ubuntu 22.04 jammy, Windows 11

**Comment by OlegDokuka** [comment]
@mtricht what you see is expected since bufferTimeout by default does not respect back pressure, hence, when timeout is triggered for the next buffer, it emit it on a separate thread, hence see not progress and terminated execution then. What you need to try is either windowTimeout(..., fairBackpressure = true) or same configurations for bufferTimeout. 
Let me know if this issues still reproduces with the mentioned configurations
