### ISSUE TITLE
Rename Exceptions.fail*(e) methods

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor-core#36]
`Exceptions.fail(e)` and `Exceptions.failUpstream(e)` was relevant for the old behavior (throwing an exception) but not for the current (returning a wrapped exception). My proposal is to use `Exceptions.wrap(e)` and `Exceptions.wrapUpstream(e)`, but feel free to propose better name.

**Comment by sdeleuze** [comment]
I think I would vote for `Exceptions.propagate()` like [in RxJava](http://blog.danlew.net/2015/12/08/error-handling-in-rxjava/).

**Comment by smaldini** [comment]
+1 for Exceptions.propagate()
