### ISSUE TITLE
Investigate storing Exception for stack trace rather than using Strings

### ISSUE THREAD

**Issue by philwebb** [reactor/reactor-core#361]
Currently the [operatorStacktrace](
https://projectreactor.io/docs/core/snapshot/api/reactor/core/publisher/Hooks.OperatorHook.html#operatorStacktrace--) stores a String copy of the stack trace. It might be quicker to instead store `Exception` instances and only use `printStackTrace` if absolutely necessary.

**Comment by philwebb** [comment]
See [SPR-14944](https://jira.spring.io/browse/SPR-14944) for background.

**Comment by smaldini** [comment]
@philwebb if you have a mean to test the 3.0.5.BUILD-SNAPSHOT

**Comment by smaldini** [comment]
Will keep under this form for now.
