### ISSUE TITLE
Mono/Flux switchIfEmpty Enhancement

### ISSUE THREAD

**Issue by EasternGamer** [reactor/reactor-core#3640]
The enhancement is fairly basic extension of switchIfEmpty where an additional option of providing a supplier/runnable/callable/other. 
## Motivation
It's been a bit of a pet-peeve for me, the motivation is for a more concise way of doing the following: 
- someMono.switchIfEmpty(Mono.fromSupplier(() -> { ... })
- someMono.switchIfEmpty(Mono.fromRunnable(() -> { ... })
- someMono.switchIfEmpty(Mono.fromCallable(() -> { ... })

## Desired solution
Instead the above, it would be simply:
- someMono.switchIfEmpty(() -> {...})

Additionally, in the case that the return is a publisher, it should transform to that publisher, kinda like a flat version of switch.
- someMono.flatSwitchIfEmpty(() -> { ... return someOtherPublisher }

**Comment by chemicL** [comment]
Thanks for the proposal.

I have a concern regarding support for both `Supplier` and `Callable`. Consider the following quick attempt:

```
	public static <T> Mono<T> switchIfEmpty(Callable<T> callable) {
		return Mono.fromCallable(callable);
	}
	public static <T> Mono<T> switchIfEmpty(Supplier<T> supplier) {
		return Mono.fromSupplier(supplier);
	}

	public static void main(String[] args) {
		Mono.empty().switchIfEmpty(() -> "Hello"); // Ambiguous
	}
```

From that perspective, I'm not certain which variant should be chosen. Supporting both would mean the user has to cast, which would be far from an improvement.

>in the case that the return is a publisher

In this case, you probably mean the return type being `Mono`? Just having a generic `Publisher` would spawn quite a few questions and open up new alleys for exploration. Also, `flatSwitchIfEmpty(() -> someOtherMono())`  looks like `switchIfEmpty(Mono.defer(() -> someOtherMono())` which doesn't seem like much of an enhancement from pure writing perspective, but perhaps would improve the allocation by a tiny bit.

Just my 2c. @OlegDokuka I'd love to know your thoughts.

**Comment by EasternGamer** [comment]
I honestly didn't realize the difference between the two when I made the post. I had a look at them now. My intent behind this is to allow functional interface usage and member references for switchIfEmpty, and the hypothetical flatSwitchIfEmpty.
For instance, doing the following code:
```java
    public static String defaultValue() {
        return "Hello";
    }
    
    public static Mono<String> asyncValue() {
        Mono<String> tmp = Mono.just("hello");
        // do some processing with tmp or similar that interacts with the reactor API
        return tmp;
    }

    public static void main(String[] args) {
        Mono.empty().switchIfEmpty(Main::defaultValue);
        // or
        Mono.empty().switchIfEmpty(() -> "Hello");
        
        Mono.empty().flatSwitchIfEmpty(Main::asyncValue); 
        // or
        Mono.empty().flatSwitchIfEmpty(() -> {
            Mono<String> tmp = asyncValue(); // get some async value
            // do some processing using tmp
            return tmp;
        });
    }
```
It would seem cleaner to me to do the above.

I suppose you are right with the publisher part. It would be a nice feature really to have a similar ``flatMapMany``/``flatMapIterable`` for switch, but perhaps that is going a bit far for this proposal. Regardless, with ``Flux.flatSwitchIfEmpty`` would take a generic publisher.
``Flux.switchIfEmpty`` might be a bit tricky, come to think of it, it could be a single element or an iterable.
In ``Flux`` perhaps just switchIfEmpty where it takes in a supplier of a publisher, like the following:
```java
    public static Mono<String> asyncValue() {
        Mono<String> tmp = Mono.just("hello");
        // do some processing with tmp or similar that interacts with the reactor API
        return tmp;
    }

    public static <T> Flux<T> switchIfEmpty(Supplier<Publisher<T>> supplier) {
        return Flux.defer(supplier);
    }

    public static void main(String[] args) {
        Flux.empty().switchIfEmpty(Main::asyncValue);
    }
```

**Comment by EasternGamer** [comment]
@chemicL do you have comments regarding the above still?

**Comment by chemicL** [comment]
Thanks for more details. Just to capture what I understood so far.

	// Having
	static String defaultValue() {
		return "Default";
	}

	static Mono<String> fallbackMono() {
		return Mono.just("Fallback");
	}

	public static void main(String[] args) {
		// this:
		result = Mono.<String>empty().switchIfEmpty(Mono.fromSupplier(Main::defaultValue)).block();

		// would become:
		result = Mono.<String>empty().switchIfEmpty(Main::defaultValue).block();

		// and this:
		result = Mono.<String>empty().switchIfEmpty(Mono.defer(Main::fallbackMono)).block();

		// would become:
		result = Mono.<String>empty().flatSwitchIfEmpty(Main::fallbackMono).block();
	}

It looks like an easy thing to add, but it has maintenance costs that go far beyond the easy implementation. The benefit right now sounds like just an alias. To make it performant it would require implementing an operator. But is there a performance cost here in wrapping? Is it just the cost of typing a few additional characters? My understanding is that the current API makes things crystal clear as to the moment at which things are resolved. With the proposed `flatSwitchIfEmpty` it hides some of the logic as to when the execution happens.

The complexity added for `Flux` might be even more to consider, I haven't given it much consideration at this point aside from signalling that Publisher can be tricky. We do have `switchIfEmpty` operator in `Flux` and I imagine it is enough to cover the needs most users have.

Noticing this issue has not gained any community interest and the described fears, I'll close the issue. We can always reconsider if the community decides it really adds significant value, e.g. in terms of a documented performance overhead.
