### ISSUE TITLE
NPE when Mono(List(null)).flatMapIterable

### ISSUE THREAD

**Issue by Hiosdra** [reactor/reactor-core#3649]
## Expected Behavior
Exception should not be thrown. I would expect Flux to be empty or contain the null value or at least this behavior be documented.

## Actual Behavior
Exception in thread "main" java.lang.NullPointerException: The iterator returned a null value
	at java.base/java.util.Objects.requireNonNull(Objects.java:235)
	at reactor.core.publisher.FluxIterable$IterableSubscription.fastPath(FluxIterable.java:389)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:291)
	at reactor.core.publisher.BlockingSingleSubscriber.onSubscribe(BlockingSingleSubscriber.java:53)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:201)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:105)
	at reactor.core.publisher.MonoFlattenIterable.subscribeOrReturn(MonoFlattenIterable.java:79)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8759)
	at reactor.core.publisher.Flux.blockLast(Flux.java:2752)

## Steps to Reproduce
```java
public static void main(String[] args) {
        Mono.just(List.of(1).stream().map(a -> null).toList()) //as List.of(null) don't work
                .flatMapIterable(Function.identity())
                .blockLast();
    }
```
and
```java
    public static void main(String[] args) {
        Mono.just(List.of(1).stream().map(a -> null).toList()) 
                .flatMapMany(Flux::fromIterable)
                .blockLast();
    }
```

## Possible Solution
Document or change the behaviour.

## Your Environment
* Reactor version(s) used: 3.5.11 (but tested also on 3.6.0)
* Other relevant libraries versions (eg. `netty`, ...): Spring Boot Data Redis 3.1.5 (found during debugging error from ReactiveStringRedisTemplate.opsForValue().multiGet().flatMapIterable)
* JVM version (`java -version`): Coretto 17
* OS and version (eg `uname -a`): MacOS newest per day of issue creation, M2 Pro processor

**Comment by OlegDokuka** [comment]
Hello, @Hiosdra!

Project Reactor is an implementation of the Reactive-Streams specification. As[ per the specification](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.4/README.md#2.13), null values are prohibited. 


In addition to that we have clearly defined [null-safety](https://projectreactor.io/docs/core/release/reference/#null-safety) throughout the whole api. You may find that all [packages](https://github.com/reactor/reactor-core/blob/main/reactor-core/src/main/java/reactor/core/package-info.java#L22) are marked as null-safe unless it is explicitly marked in particular method or function that nullable values are allowed (e.g. in [Scannable](https://github.com/reactor/reactor-core/blob/94e431cbb1fb4b6194de7fdaf0304c604d82eb01/reactor-core/src/main/java/reactor/core/Scannable.java#L260).

Cheers,
Oleh

**Comment by Hiosdra** [comment]
Thanks @OlegDokuka. So if it was the data returned straight from Spring Data Redis, then I should file the bug there?

Pseudocode:
```java
@Autowired
ReactiveStringRedisTemplate template;

template.opsForValue()
    .multiGet(keys)
    .flatMapIterable(x->x)
```

**Comment by OlegDokuka** [comment]
> Thanks @OlegDokuka. So if it was the data returned straight from Spring Data Redis, then I should file the bug there?
> 
> 
> 
> Pseudocode:
> 
> ```java
> 
> @Autowired
> 
> ReactiveStringRedisTemplate template;
> 
> 
> 
> template.opsForValue()
> 
>     .multiGet(keys)
> 
>     .flatMapIterable(x->x)
> 
> ```
> 
> 

yes, i think soo

**Comment by broccolism** [comment]
> So if it was the data returned straight from Spring Data Redis, then I should file the bug there?
>> yes, i think soo

Hi @OlegDokuka ,  I think `flatMapIterable` has some responsibility not to make NPE, **at least it should send error signal**.

How about null value is returned as a result of HTTP REST API call?
We cannot always predict when another server will give us null value or not, so I guess it is not possible to avoid this situation even using null-safety things.

How do you think?
