### ISSUE TITLE
[Suggestion] Dynamic Concurrency Control in flatMap for External System Calls

### ISSUE THREAD

**Issue by AChekroun** [reactor/reactor-core#3652]
## Motivation

When dealing with external system calls, it's common to use `flatMap`. However, a challenge arises when these external systems become potential bottlenecks. The core of the issue is the need to dynamically manage the concurrency of the `flatMap` operator to prevent overloading these systems.

Currently, I employ libraries like Resilience4j's Bulkhead or Netflix's concurrency-limits to manage this. These solutions, while effective in some cases, have a significant drawback: they throw `RejectedExecutionException` when overloaded. This exception handling fails to signal the upstream publisher in the reactive stream to reduce the request rate, leading to an ineffective management of backpressure.

## Desired solution

Having a `flatmap` with dynamic concurrency or `rateLimiter` with dynamic value

Thanks for your time

**Comment by chemicL** [comment]
Can you please provide a minimum example project as an attached zip or a repository where the limitations of the current design can be observed?

**Comment by chemicL** [comment]
Closing as per the above. Feel free to reopen once you have an example project to share.
