### ISSUE TITLE
[Enhancement request] Flux from streaming file

### ISSUE THREAD

**Issue by patpatpat123** [reactor/reactor-core#3656]
## Motivation
It would be great for this project to offer a possibility to construct a flux out of a streaming file.
By streaming file, please imagine a log file, where periodically, at fixed or not fixed internal, a new line at the end of the file.
It would be great if likewise, from the flux perspective, we can construct the flux from this 1..N streaming file.

## Considered alternatives
As of right now, one can use constructs such as:
```
Flux.using(
           () -> Files.lines(PATH),
           Flux::fromStream,
           Stream::close
 );
```
or 
```Flux.from(org.javaync.io.AsyncFiles.lines(Path.of("test/sample.txt")))```
However, this does not take into account the new lines going into the file, unfortunately.

## Desired solution
It would be great if reactor core could provide an api to handle streaming files, as there is no convenient way out in the market as of now.

Thank you for reading, wishing you a good day

**Comment by chemicL** [comment]
Thank you for the detailed suggestion @patpatpat123. Have you tried experimenting with [apache-commons-io `Trailer` class](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/input/Tailer.html)? Marrying the listener API with `Sinks` should not be a difficult exercise for a start. If that doesn't suit your needs, perhaps there is an opportunity for creating something more performant. However, most probably reactor-core is not the right place, but let's first gather the requirements: performance expectations, types of files, decoding considerations (you indirectly implicated splitting by end-of-line – perhaps there are more options). It might fit into reactor-addons, but if there's more into it perhaps reactor-netty or even netty, which contains some performant utilities for dealing with files, e.g. [ChunkedNioFile](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/stream/ChunkedNioFile.java).

**Comment by chemicL** [comment]
@patpatpat123 friendly ping :)

**Comment by patpatpat123** [comment]
Thank you for the pointer.

I tried using trailer, combining it with sinks, and it is working!

**Comment by chemicL** [comment]
@patpatpat123 awesome, thanks for the update!
