### ISSUE TITLE
HTTP 404 on documentation / Javadoc Link 

### ISSUE THREAD

**Issue by jprinet** [reactor/reactor-core#3699]
HTTP 404 when following the documentation / Javadoc links from the README

## Documentation Issue
Try this as an example:
https://projectreactor.io/docs/core/release/reference/index.html
https://projectreactor.io/docs/core/release/api/

**Comment by violetagg** [comment]
@jprinet We know about the problem and working on resolving it
https://github.com/reactor/projectreactor.io/issues/143
