### ISSUE TITLE
Support progressive upgrade to Long.MAX requests

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#371]
Currently a lot of operators use REQUESTED.addAndGet in their drainLoop and this is failing cases where subscriber started requesting with 1, 2 then switched to Long.max (unbounded). 

A simple fix would be to use `Operators.addAndGet(REQUESTED, this, -e);` and this needs to be evaluated against any performance degradation given the double volatile touch ( @akarnokd ?);

**Comment by simonbasle** [comment]
Different methods in `Operators` allow to increment or decrement an updater. It might not be clear enough which method is best. Maybe clean that up a little and / or improve the javadoc (with comments in the form "when in this use case, use {otherMethod} instead")

**Comment by smaldini** [comment]
After investigations, it seems that the current main issue might be that some operators such as flatMap might suffer from holding a requested Long.MAX - N where n might come from tryEmit decrement. That means the operator will work with a large value and eventually get back to 0 after Long.MAX - N elements have been processed. This is not unique to flatMap. The issue fixed in commit https://github.com/reactor/reactor-core/commit/b47ce5e31d94af64fa1bd71386c285eb6ac4432a is actually not necessary anymore after testing.

However there might be some possible polishing when async boundaries make sense.

**Comment by smaldini** [comment]
If more needs to be investigated, we'll sure be re-opening this one to replace more REQUESTED.addAndGet(..., -e) by Operators.produced
