### ISSUE TITLE
i m having an error "r.core.Exceptions","stack_trace":"java.lang.StackOverflowError: null

### ISSUE THREAD

**Issue by mehdi-git1** [reactor/reactor-core#3726]
i have this error : {"timestamp":"2024-02-12T16:15:28.843+0000","severity":"WARN","logger":"r.core.Exceptions","stack_trace":"java.lang.StackOverflowError: null\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\tat java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)\n\t... 1004 frames truncated\n","traceId":"523ee3ea-636c-4ecd-95f7-0ad4814724cb","sourceSubDomain":"authenticationController","forwardedFor":"10.49.65.52, 172.17.44.7, 172.17.98.196","requestId":"a3a241edbb91a86037b6d99b5ab9eeda","sourceMethod":"POST","x-correlation-id":"a1e18a9e-5952-4b95-bf38-cb4a4d627d9c","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36","source":"com.carrefour.fr.bff.location.session.api","sourceService":"authenticate","sourceDomain":"location-demo.fr.carrefour.com","version":"develop-build-1173258321","hostname":"bfflo-demo-api-77fb7d7f69-97lbm"}

**Comment by mehdi-git1** [comment]
can you help me please

**Comment by chemicL** [comment]
If you think you found a bug with reactor-core then please follow the issue report template which seems you immediately removed when opening this report. Please try again, provide a reproducer, library version, etc. I'm closing this as invalid for now.
