### ISSUE TITLE
Can not determine root error for an exception in reactor call chains.

### ISSUE THREAD

**Issue by markpollack** [reactor/reactor-core#379]
We are using reactor via the cf-java-client library.   When an error occurs in our integration tests, we don't get a clear indication of where in the code that error was thrown from.  With `Hooks.onOperator(op -> op.operatorStacktrace());` enabled there isn't much more information either to localize which API call resulted in a

```Composition chain until failing Operator :
	|_	Mono.error(ErrorPayloadMapper.java:82)
```

I'll have to dig in manually, but generally speaking it is more common for the cf-java-client library to make multiple http requests in a chain for a logical end user operation such as deploying a task.

https://build.spring.io/browse/SCD-DCF-CFDPWS-214/test/case/224848966

shows the issue in context.

**Comment by smaldini** [comment]
Immediately fixed trace, will improve debugging tooling on the long run.
