### ISSUE TITLE
Add flatMapIterable alias 

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#38]
It seems to be a good regular candidate to be factored in Flux/Mono.

**Comment by joaoevangelista** [comment]
It would be something like [this](https://github.com/joaoevangelista/reactor-core/blob/8c01828ec0e0a1a929c4e507ad45d82e253685f1/src/main/java/reactor/core/publisher/Flux.java#L2655) ? I did it based on RxJava operator, but only with the necessary code [here](https://github.com/joaoevangelista/reactor-core/blob/8c01828ec0e0a1a929c4e507ad45d82e253685f1/src/main/java/reactor/core/publisher/FluxMapPair.java)

**Comment by akarnokd** [comment]
You can implement this via flatMap directly:

`flatMap(v -> fromIterable(mapper.apply(v)))`

Of course, you could adapt `flatMap` and get rid of some wrapping, but even with this efficiency push of Reactor, might not worth it maintenance-wise.

**Comment by smaldini** [comment]
Yes agree the alias will just do fine. A signature alias :+1:
