### ISSUE TITLE
Best practices and failure handling

### ISSUE THREAD

**Issue by aviadhadida** [reactor/reactor-core#381]
Hi.

Thanks for answering to my colleague on different thread. This is basically after we made a change regarding to the upgrade from 2.X to 3.X.
https://github.com/reactor/reactor-core/issues/375
We have used the EventBus as event manager in our application(Low latency FX system) and it works very well for us.

After the change we decided to take every module and create his own processor to handle event.
1. Does this use seems to be correct from your point of view? Because lack of document at the current stage and after reviewing everything we could we don't really know what to do here
2. We have tried to use Flux in order to perform action every X interval
For example: Market is arriving 1000 for 1 second but we want to process an update only 4 time in a second. After upgrading we are using:

Processor with buffer and sending to another method.
In this method we have Flux that get list and try to work in parallel in order to complete his task.
We had 2 major problems:
1. Sometimes we received Null event which we cannot find that our system is sending to i suppose maybe we are miss using the processor

  

        //Definition of processor
        ReplayProcessor<Event> classAEventProcessor = ReplayProcessor.create();

        //Event handler subscribing
        public void onMyEventX(Consumer<Event> consumer) {
           Flux<Event> handler = classAEventProcessor .filter(event -> event.getType().equals(EVENT_X));
           handler.subscribe(consumer);
       }

in the example above the event in the handler sometimes get null.. Once he does the stream stop working until we are restating server(Because only on restart we are doing creating processor)

2.We have tried to us parallel but sometimes some of the message were disappeared so maybe we are misusing the framework

        //On constructor
       tickProcessor.buffer(1024, Duration.of(250, ChronoUnit.MILLIS)).subscribe(markets -> 
       handleMarkets(markets));

       //Handler
      Flux.fromIterable(getListToProcess())
	       	.parallel()
		.runOn(Schedulers.parallel())
		.doOnNext(entryMap -> {
			DoBlockingWork(entryMap);
		})
		.sequential()
		.subscribe();

The intention of this is that the processor will wakeup every 250ms and invoke the handler. The handler will work work with Flux parallel in order to make better and faster processing.
*In case that DoBlockingWork takes more than 250ms i couldn't understand what will be the behavior

I know this is long and i will appreciate your attention. 
Thanks,
Aviad

**Comment by aviadhadida** [comment]
After reviewing with trial and error.. We have noticed the the legacy EventBus is much more faster than create different processor to every module(8 processors in general).
We really need help here.. We tried everything

**Comment by simonbasle** [comment]
A few clarifications:

- I think `ReplayProcessor` was used as an example in the previous issue by @smaldini... Do you really need replay capabilities? ie each event is kept in a buffer and **the whole history** is replayed to listeners that register at later points in time?
- `parallel()` and the `parallel` scheduler aims at fully utilizing the CPUs, but for short in-memory work. Blocking inside the parallel is not a good idea. What does the `DoBlockingWork` operation do, in a bit more details? (kind of blocking work, dependency to an external source, how does it call this source - ie a `Callable`? callback-based API? blocking API?...)

**Comment by aviadhadida** [comment]
I will try to better explain myself. We have used version 2.X with eventBus.
Every time we had specific event we went to RingBufferProcessor and onNext(event)/
The RingBuffreProcessor was set to run every 250MS(buffer(1024, 250MS)).
So this as the general flow:
Event tick -> publish throw eventBus -> subscriber get event and put in processor -> processor is buffering and updating every 250MS.(We were updating user on new event)

so basically DoBlockingWork is just action that goes into memory for each user * events.
In case of a lot of users with a lot of events is was slow.. So in order to make it faster we wanted to use parallel(Meaning parallel for every user update).

Once we have upgraded the version we need to remove the eventbus. After long investigation we have wrapped DirectorProcessor and used 2 thread(1 in, out) in order to handle event as close to the previous eventBus and it seems to work but we are not sure what is the best practices.
I am not really understand what the diffrences between parallel(), Schedulers.elastic() , flatMap and more options. Hope i managed to explain the porposes of the parallelizm we are searching for and i appreciate and you also can tell me if the replacment of the eventBus looks fine from your side.

Thanks a lot

**Comment by simonbasle** [comment]
hi @aviadhadida 
did you make some progress on this issue?

 * getting back at it, it seems like you have a listener-based API that injects data into the system. For such a case, `Flux.create()` can be a good fit. It exposes  a `Sink` through a `Consumer<Sink>` and the idea is to provide a lambda inside of which you register a listener. On data event, push the data by calling `sink.next(v)`. If you can detect completion or errors, use `sink.complete()` and `sink.error(t)`:
 ```
 Flux.create(sink -> {
     MyListener l = new MyListener() {
         public void onData(T data) {
             sink.next(data);
          }
          public void onError(Throwable t) {
              sink.error(t);
          }
      }
      myDataSource.registerListener(l);
 });
 ```
 
  * `flatMap` vs `parallel()`: `flatMap` gives more control on the flow and is not purely about parallelization, but rather about triggering asynchronous sequences and merging them back. It lets you tune a bit more how much is requested from upstream. `parallel()` is purely about dividing work between `n` *rails*. It will pull as much data as possible from the upstream, in order to maximize work. It truly parallelize the work only when calling `runOn(Scheduler)` though. It also assumes the threads created by `runOn` are available (not blocked).

So the general idea is to use `create` + `flatMap` and ensure the blocking method is called from a dedicated thread. Something along the lines of this:

```
//this is so the pool is shared, can be disposed, etc...
static Scheduler WORK_POOL = Schedulers.newElastic("workPool");

// register the listener and convert to Flux via sink
Flux.create(sink -> ...)
        //buffer raw data by batches of 1024 or 250ms
        .bufferTimeout(1024, Duration.ofMillis(250))
        //perform work on the buffer
        .flatMap(buffer -> Flux.fromIterable(buffer) // back to a flux of raw data
                                                  .publishOn(WORK_POOL) //execute each item and blocking work in a separate thread
                                                  .map(rawValue -> doBlockingWork(rawValue)) // this happens in the work pool
        ) //here you could tune the concurrency of flatMap by adding the relevant int parameter
        //maybe do some more stuff, switch back to a single predifined thread, etc...
        //consume the final form of the data (eg. show in UI)
        .subscribe(v -> doSomethingWithEachTransformedValue(v));
```

Hope this helps. I'll close this issue for now, please re-open if you still need help.
