### ISSUE TITLE
Example titles are not prefixed with Example N.

### ISSUE THREAD

**Issue by pderop** [reactor/reactor-core#3811]
## Documentation Issue
The new antora version of the reactor-core documentation has the following issue: All example titles are not prefixed anymore with Example N., like it was the case before.

Also, the background color is not consistent as the one we had in previous asciidoc version.

## Improvement Suggestion

I'm not sure, but this issue might be related to `antora-ui-projectreactor`

## Additional context

see https://github.com/reactor/reactor-core/pull/3806#discussion_r1603313977

**Comment by chemicL** [comment]
I think we can live without the prefix, so I'm closing this issue.
