### ISSUE TITLE
Redirect old docs links to new Antora docs links

### ISSUE THREAD

**Issue by pderop** [reactor/reactor-core#3812]
## Documentation Issue

Once reactor-core documentation is migrated to Antora, some links to the documentations will change.
now, since we have some links to the current doc outside in the wild, like in  https://www.canva.dev/blog/engineering/enabling-real-time-collaboration-with-rsocket/, where there is a link to https://projectreactor.io/docs/core/release/reference/#faq.mdc which is now `https://projectreactor.io/docs/core/release/reference/faq.html#faq.mdc`.

we need to redirect old links to new ones.

## Improvement Suggestion

for some cases, it might be possible to use Antora page-aliases [attributes](https://docs.antora.org/antora/latest/page/page-aliases/).
For other cases, we might need to configure some redirect mapping in Cloudflare.

**Comment by chemicL** [comment]
Let's address this on a case-by-case basis. It's a lot of links to check at this point so we might as well just fix them when reported.
