### ISSUE TITLE
SynchronousSink - verb is missing in javadoc

### ISSUE THREAD

**Issue by ilya-ulyanov** [reactor/reactor-core#3835]
## Documentation Issue
The javadoc for the SynchronousSink says:
"... You can FluxSink or MonoSink based generators for these situations."
 
## Improvement Suggestion
The above should be rephrased by adding a verb, for instance - "use", so it becomes:
"... You can **use** FluxSink or MonoSink based generators for these situations."

**Comment by chemicL** [comment]
Thanks for the report. Are you open to contributing this fix? [It doesn't require signing the CLA](https://github.com/reactor/.github/blob/debbeab9db6a8742630fba3aec0cb4cda7156c38/CONTRIBUTING.md#clipboard-contributor-license-agreement).

**Comment by ilya-ulyanov** [comment]
Yes, will do. Thanks.

**Comment by ilya-ulyanov** [comment]
I have opened a PR - https://github.com/reactor/reactor-core/pull/3838
