### ISSUE TITLE
Review operator FluxWindow cancel

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#384]
Currently the main window subscriber's cancel doesn't seem to protect against a cancel race from inner `UnicastProcessor`. That leads windows that have been cancelled to potentially accumulate data, that it will never emit downstream.

Also the `ONCE` field updater is only used only in cancel in `WindowExactSubscriber` for instance (would need to check all window implementations).

**Comment by akarnokd** [comment]
UnicastProcessor [drops](https://github.com/reactor/reactor-core/blob/master/src/main/java/reactor/core/publisher/UnicastProcessor.java#L304) incoming events if [cancelled](https://github.com/reactor/reactor-core/blob/master/src/main/java/reactor/core/publisher/UnicastProcessor.java#L385).

**Comment by rajinisivaram** [comment]
@simonbasle @smaldini I had a look through all the window implementations and there are some inconsistencies. But I couldn't find a race condition as mentioned in the description of this issue. As far as I can tell, if an inner is cancelled, `FluxWindow` could deliver data that are dropped, but not if main is also cancelled. `ONCE` and `WIP` in `FluxWindow` are used similarly to `CANCELLED` and `GROUP_COUNT` in `FluxGroupBy`. Every window implementation seems to have a slightly different set of variables with confusing names. Do we want to make the naming consistent or only fix semantic inconsistencies?

`FluxGroupBy`, `FluxWindow` and `FluxWindowBoundary` deliver data to already open windows even if main is cancelled (no new windows are created and the subscription is cancelled when all existing inners complete). But `FluxWindowTimeOrSize` and `FluxWindowPredicate` cancel the subscription immediately and don't deliver any more data after main is cancelled. Is this as designed?

**Comment by smaldini** [comment]
Fixing inconsistencies will help further reviews I believe. The purpose would be to really account for all childs (main + window(s)) when dealing with cancellation to cope with all situations:
- main child has cancelled but window(s) can still accept data
- main child is alive but window(s) have cancelled, we drop until new windows are produced
- all cancelled, we cancel main parent

**Comment by simonbasle** [comment]
> * main child has cancelled but window(s) can still accept data
Not sure I follow this case @smaldini... Are you talking about a window to which we have forwarded data but it currently keeps it in its queue for lack of request?

**Comment by smaldini** [comment]
```flux.window(10).take(1).flatMap(w -> w)```
This must cancel only when the current window has terminated or cancelled.

**Comment by rajinisivaram** [comment]
@smaldini 
`flux.window(10).take(1).flatMap(w -> w)` generates 10 elements.
`flux.windowWhile(i -> i != 10).take(1).flatMap(w -> w)` never generates any (cancels immediately).

Just to confirm - we want to fix `windowWhile` and others that cancel immediately? 
And use consistent variable names in all window implementations to track cancelled/windowCount?

**Comment by smaldini** [comment]
yes @rajinisivaram
