### ISSUE TITLE
Trace id is coming sometime and missing sometime at requestInterceptor during load test

### ISSUE THREAD

**Issue by oms12** [reactor/reactor-core#3875]
During load test of our application we observed that some of request in the request interceptor is missing the trace-id. Attached the logs pls check.

## Your Environment
    <dependency>
        <groupId>io.micrometer</groupId>
        <artifactId>micrometer-tracing-bridge-otel</artifactId>
    </dependency>
    
    <dependency>
        <groupId>io.projectreactor</groupId>
        <artifactId>reactor-core-micrometer</artifactId>
    </dependency>

* Reactor version(s) used: 3.5.13
* Springboot webflux - 3.2.1

**Comment by chemicL** [comment]
Hey, this looks more like a question than a bug report. [Consider using Stackoverflow or Gitter](https://github.com/reactor/.github/blob/debbeab9db6a8742630fba3aec0cb4cda7156c38/CONTRIBUTING.md#question-do-you-have-a-question).

Before I close the issue though, please try using reactor-core 3.6.9 and the latest Spring Boot dependencies. Also, do you mean that you are using automatic context propagation?

If the above don't help, consider creating a minimal reproducible example repository or zip that you can share and we can run to evaluate whether there's a bug.

**Comment by oms12** [comment]
we found bug at our side. Thank you for your response.
