### ISSUE TITLE
Flux of Mono ResponseSpec (webclient .retrieve) .OnErrorResume unusefull to substitute with a correct Mono when return Mono.error()

### ISSUE THREAD

**Issue by skyblackhawk** [reactor/reactor-core#3884]
```
	@Override
	public Flux<?> getRatesFlux(String logHash, String apiUrl) {
		return ratesReactiveRepository
				.findAll()
				.flatMap(rate -> {
					log.info("{} rate read from MongoDb: {}", logHash, rate);
					String url = apiUrl + "/" + rate.getRateName();
					log.debug("{}, START {} URI: {}",
							logHash,
							"controller.ratesServiceImpl.getRatesFlux",
							url);
					return webClient
							.post()
							.uri(url)
							.accept(MediaType.APPLICATION_JSON)
							.retrieve()
							.onStatus(	HttpStatusCode::is5xxServerError,
										clientResponse -> Mono.error("INTERNAL SERVER ERROR for rate " + rate))
							.onStatus(	HttpStatusCode::is4xxClientError,
										clientResponse -> Mono.error("EMPTY for rate " + rate))
							.bodyToMono(ContentFragmentMainEntity.class);
				});
	}
```
```
Below service is called from controller:
		return aemRatesService
				.getRatesFlux(logHash, apiUrl)
				.onErrorContinue((err, i) -> log.error("ERROR LOAD SOME RATE VERIFY LOG"))
				.flatMap(response -> {
					log.info("OK LOAD " + response.getCodice());
					return Mono.just("SUCCESS LOAD RATE " + response.getCodice());
				})
				.collectList();
```

I tried to use .OnErrorResume but block flow return a single value not continue and in this implementation not continue stop after a 505 INTERNAL SERVER ERROR.

How can manage in a Flux a Mono.error to return a Mono.just object and continue in asyncronous flatmap?

Thanks a lot for your support.

**Comment by chemicL** [comment]
Hey, please have a look at our [policy on questions](https://github.com/reactor/.github/blob/main/CONTRIBUTING.md#question-do-you-have-a-question).

**Comment by skyblackhawk** [comment]
In my case:
.doOnError allow to add a log for example or same action
.OnErrorResune substitute result with a value but in Mono in Flux(ResponseSpec).flatmap can't change Mono object.

The one solution that I found is used .OnErrorContinue but I lost error response of webclient 500 and 404.

I want to tell that there are technics to manage exception or error in case of Exception to continue flatmap.

I'm using java21 and SpringBoot webflux 3.2 and Mongo Reactive lon Mongo v7
