### ISSUE TITLE
Automatic context propagation not working with subscribed sink mono

### ISSUE THREAD

**Issue by mrodal-onlab** [reactor/reactor-core#3887]
## Expected Behavior
Found the issue using spring-statemachine. Somewhere in the statemachine the logging context was getting lost. Debugging I found the part where this was happening, and could extract a small code sample that reproduces the error. The error happens when using `Hooks.enableAutomaticContextPropagation();` and it works as expected when not using it.

## Actual Behavior
Context is not being propagated when using `Hooks.enableAutomaticContextPropagation();`

## Steps to Reproduce

```java
void reproCase() {
  log.info(MDC.getCopyOfContextMap().toString()); // Logging context found
  var sink = Sinks.one();

  sink.asMono().flatMap(s->{
      log.info(MDC.getCopyOfContextMap().toString()); // Logging context missing
      return Mono.just(1);
  }).subscribe();

  sink.emitValue("", Sinks.EmitFailureHandler.FAIL_FAST);
}
```

## Your Environment

* Reactor version(s) used: 3.6.9
* Other relevant libraries versions (eg. `netty`, ...): `spring boot 3.3.3`, `micrometer-core 1.13.3`, `micrometer-tracing 1.3.3`
* JVM version (`java -version`): java 17
* OS and version (eg `uname -a`): Windows 10

**Comment by chemicL** [comment]
Can you share how you are populating the MDC and what you expect would propagate the MDC?

**Comment by mrodal** [comment]
Im not populating the MDC, it is being populated by micrometer I believe.
Heres a sample application:
https://github.com/mrodal/issue-context-propagation

Its just a controller with the code above and the application starter with the `Hooks.enableAutomaticContextPropagation();`

**Comment by chemicL** [comment]
Ok. I'm not sure what exactly you are trying to achieve, but you are creating a disconnected pipeline when you call `.subscribe()`. Essentially, all that is present in the MDC is coming from `Context` associated with the incoming request. The gist is - you return some `Flux`/`Mono` in your controllers to which the framework subscribes. A `Subscriber` carries a `Context` that represents an `Observation` associated with that request processing. Micrometer-Tracing takes care of populating the MDC with trace-id/span-id metadata taken from the `Observation` that is present in the `Context`. Once you create another `Flux`/`Mono` which does not form a reactive chain with the existing `Subscriber` then it contains an empty `Context` that does not have that `Observation`. This fire-and-forget pattern can lead to such issues. Consider asking a question on Gitter or StackOverflow how to best structure your code for the actual use case that you have and make sure you consult [our reference documentation on this](https://projectreactor.io/docs/core/release/reference/#context.propagation).

**Comment by mrodal** [comment]
The example code is a simplification of the spring-statemachine library code. I'll check over there if they can find a workaround
Thank you

**Comment by namnq** [comment]
@mrodal  do you have any solution for this issue?

**Comment by mrodal** [comment]
Hi @namnq, we are using a build from the branch in this PR https://github.com/spring-projects/spring-statemachine/pull/1164
