### ISSUE TITLE
Retry cached Mono

### ISSUE THREAD

**Issue by melgenek** [reactor/reactor-core#391]
I was trying to cache http result that I've got using [reactive http client](http://docs.spring.io/spring/docs/5.0.0.M4/spring-framework-reference/html/web-reactive.html#web-reactive-client) and `@Cacheable` annotation. Something like this:
```
@Cacheable("items")
public Mono<Item> getItem() {
    return Mono.just(()->someCode()).cache();
}
```
This approach works but I'm concerned about error responses, that can happen during connection. 
It seems to me that retrying http call is one of the viable approaches:
```getItem().retry(1)```
Currently the retry works but it gets the cached result but doesn't replay business logic underneath.
Could you please check if this is sane proposition to call original logic instead of cached value on retry?
The unit test that reproduces the issue:
```
public class MonoTest {

	@Test
	public void shouldRetryCachedError() {
		SampleService sampleService = new SampleService();
		Mono<String> producer = Mono.fromSupplier(sampleService::call).cache();
		try {
			producer.block();
			fail();
		} catch (RuntimeException e) {
			System.out.println("Caught exception : " + e);
		}

		sampleService.serverAvailable = true;
		String result = producer.retry(1, t -> {
			System.out.println("ASKING FOR RETRY");
			return true;
		}).block();
		assertEquals("Success", result);
	}

	class SampleService {
		boolean serverAvailable = false;
		String call() {
			System.out.println("Calling service with availability: " + serverAvailable);
			if (serverAvailable) {
				return "Success";
			} else {
				throw new RuntimeException("Error");
			}
		}
	}
}
```

**Comment by asarkar** [comment]
@melgene @smaldini Can't you use `defer`?
```Mono.defer(() -> sampleService.call())
    .retry
```

**Comment by asarkar** [comment]
> if previous call was cached with error result

Or don't cache error response by putting a filter before cache.

I'm interested in points 3 and 4. Do you've some code you can show?

**Comment by smaldini** [comment]
Would that documentation be enough for now http://next.projectreactor.io/docs/core/release/reference/docs/index.html#error.handling ?

**Comment by simonbasle** [comment]
I think you've found a way of doing what you wanted, closing this for now. don't hesitate to re-open if your issue is not addressed!
