### ISSUE TITLE
Questions about cache(1).parallel().

### ISSUE THREAD

**Issue by masterav10** [reactor/reactor-core#392]
Hey Reactor team,

I have a flux which has multiple subscribers. To prevent duplication upstream, we use cache(1) before we the subscribers. One of three subscribers uses a parallel stream. The stream never receives data, which was unxpected. I'm not sure if this is a bug or not, but we have a test case which demonstrates the behavior. See gist below:

https://gist.github.com/masterav10/c686bdcf0c70c7817a19e6b9e03f3a41

Tested using Reactor 3.0.4.RELEASE.

**Comment by smaldini** [comment]
Hey it's a bug we're on this thanks for the report.
