### ISSUE TITLE
Replace Legacy EventBus with processor

### ISSUE THREAD

**Issue by aviadhadida** [reactor/reactor-core#393]
Hi.

I am trying to achieve the same throughput that i had with eventBus and to implement with the Processor. The major change is that i will decouple events among the different modules and every module will have its own processor. 
As part of my efforts i have tried to wrap DirectProcessor that every consumer will run with threadPool as i believe eventBus is working.. But still the it is not fast as the eventBus.
Any suggestion?

**Comment by simonbasle** [comment]
(note: we are planning on writing more exhaustive documentation on each type of `Processor` and when to use them)

**Comment by simonbasle** [comment]
(from @aviadhadida in #483):
> NP. Sorry for that we have just got into real need to upgrade reactor version and it conflicts with using event bus and we have real concern that it will be deprecated soon. This is a real time trading system that already in production.
> Thanks for your help

**Comment by smaldini** [comment]
Moving the issue to https://github.com/reactor/reactor-addons/pull/103
