### ISSUE TITLE
Marble Diagrams Are Hard to Read in Dark Mode

### ISSUE THREAD

**Issue by Attacktive** [reactor/reactor-core#3932]
## Expected Behavior

The text within marble diagrams should be readable.

## Actual Behavior

![Screenshot 2024-11-11 18:35:08](https://github.com/user-attachments/assets/95ea5542-cba8-4972-9f24-0ee8b646dbc1)

## Steps to Reproduce

1. go to [Flux, an Asynchronous Sequence of 0-N Items](https://projectreactor.io/docs/core/milestone/reference/coreFeatures/flux.html),
2. turn on dark mode

## Possible Solution

Either:
1. the text within the diagram is white, or
2. the diagram has the light background
for example,
```html
<img src="..." style="background-color: white">
```

**Comment by violetagg** [comment]
@oodamien Thanks!
@Attacktive @chemicL This PR #3933 should fix the issue.

**Comment by chemicL** [comment]
Thanks @violetagg :)
