### ISSUE TITLE
Mono.cache says signal is indefinetly cached. What does it means?

### ISSUE THREAD

**Issue by metalpalo** [reactor/reactor-core#3950]
Hi all

I defined following Mono stored in variable and subscribing it to creating instance via longer method. 
This is executed during application boostrap on background.

```
instance = Mono.fromCallable(() -> createInstance(endpointAddress))
        .cache()
        .subscribeOn(boundedElastic());

instance.subscribe();

```
and then I call multiple times(e.g. 1 000 000 000) via **instance.block()** to get variable from several threads

I possible that mono even if cached that can be invalidate during application lifetime? 
The documentation says that signal is cached indefinitely? What does it means?

thanks
brpalo

**Comment by chemicL** [comment]
Hey, thanks for your interest in Project Reactor.

I think in this case it means "forever". Let's check [the dictionary](https://dictionary.cambridge.org/dictionary/english/indefinitely) (I'm not a native English language speaker):

> for a period of time with no fixed end

In essence it means what the documentation says - once the source of the cache operator is done propagating the signal, no further subscriptions will be made by the cache operator in the future, the signal is replayed as long as the cache operator is being used or reused for future subscribers.

Note [our contribution guidelines](https://github.com/reactor/.github/blob/1f1c1399a4e4f9afab4d2b43c0130e2dea5cd9dd/CONTRIBUTING.md#question-do-you-have-a-question) that we use our issue tracker for bug reports and enhancement proposals and not for questions. Please use StackOverflow or Gitter for future queries.
