### ISSUE TITLE
Remove DependencyUtils#reactorVersion()

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor-core#4]
Since Reactor is now modular, all modules will not have the same version, so `DependencyUtils#reactorVersion()` makes not sense anymore. And removing it is from my POV a best practice since version should not be hardcoded like that in the code (not error prone during releases).

**Comment by ifesdjeen** [comment]
I agree, that makes sense.

**Comment by sdeleuze** [comment]
Fixed
