### ISSUE TITLE
Mono.just().filter().then() does not run as expected

### ISSUE THREAD

**Issue by allomov** [reactor/reactor-core#412]
Hey, all.

I want to bring my apologies for not having much of Java experience.

I am playing with an application for resilience tests, the app is called [chaos-loris](https://github.com/Altoros/chaos-loris). It should select a number of app instances basing on probability and put them down.

Currently, I have an issue with a [code that uses Reactor](https://github.com/Altoros/chaos-loris/blob/master/src/main/java/io/pivotal/strepsirrhini/chaosloris/destroyer/StandardDestroyer.java#L75-L79). The code looks like this:
```
getInstanceCount(chaos, platform).then(instanceCount -> Flux.range(0, instanceCount)
    .flatMap(index -> Mono.just(fateEngine.getFate(chaos))
        .filter(fate -> THUMBS_DOWN == fate)
        .then(terminate(chaos.getApplication(), index, platform)))
    .collectList()
```
The problem is that this code does not filters a Mono and calls `terminate` method for each app instance.

I see the problem with `terminate` method not been passed as anonymous function and I fixed this code like this:
```
getInstanceCount(chaos, platform).then(instanceCount -> Flux.range(0, instanceCount)
    .flatMap(index -> Mono.just(fateEngine.getFate(chaos))
        .filter(fate -> THUMBS_DOWN == fate)
        .then(() -> terminate(chaos.getApplication(), index, platform)))
    .collectList()
```
But this change still does not work and I can't see why.

Could you please verify that when I run `Mono.just().filter().then()` and a lambda passed to `filter` returns `false`, this prevents lambda from `then` to be called?

Thank you,
Alex L.

**Comment by allomov** [comment]
I've found the problem (see details here: https://github.com/strepsirrhini-army/chaos-loris/pull/10/files). I needed to pass an extra parameter to the lambda of `then` method, otherwise the lambda was called each time.

I think, that this is unexpected behavior for most of users. Most of them would expect that `then` will be running only if filter was passed. What do you think?

**Comment by smaldini** [comment]
Its a good question, its a kind of Java 9 style where we differ behavior based on the lambda signature. We put it here in FAQ number 2 item http://next.projectreactor.io/docs/core/snapshot/reference/docs/index.html#faq.monoThen

**Comment by allomov** [comment]
I convinced that such approach can cause hard-to-detect errors, such was made in https://github.com/strepsirrhini-army/chaos-loris/pull/10. Because people tend to miss parameters in functions, and the only situation you want to overload methods is to add parameters that might extend method functionality, not to change its behaviour.

**Comment by javo1005** [comment]
Friendo, so right now is working as you said the `.then` operator is always being executed after .filter ? because I am having the same issue.

**Comment by allomov** [comment]
@javo1005 can't answer you right now. I would suggest to open a new issue for your question (and probably refer this PR)
