### ISSUE TITLE
Add code style configuration

### ISSUE THREAD

**Issue by joaoevangelista** [reactor/reactor-core#42]
A code style configuration file would be nice to have, so contributors don't mess up the already formatted code.

An eclipse format file could be enough since IntelliJ has a converter from that file.

**Comment by smaldini** [comment]
Good point @rstoyanchev do you know where the Spring one is ?

**Comment by bclozel** [comment]
Here are a few resources:

* the [official documentation](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#use-spring-framework-code-style)
* [eclipse files](https://github.com/spring-projects/spring-framework/tree/master/src/eclipse)
* [IDEA files](https://github.com/spring-projects/spring-framework/tree/master/src/idea) (although I think the newest versions only accept JARs for importing those settings, not single files anymore)

**Comment by joaoevangelista** [comment]
IDEA 2016.1 aka 16 now have support for import xml files, lower versions can import manually coping the xml to `/$HOME/.IntelliJIdea{version}/config/codestyles/`

**Comment by smaldini** [comment]
Whats the state of that btw ?

**Comment by joaoevangelista** [comment]
I did a draft of a contributing guide, basing on Spring's, included the files for both Eclipse and IDEA.
You can check on my fork [here](https://github.com/joaoevangelista/reactor-core/tree/add-contrib-guide). Any feedback is appreciated, if you want to turn this into a pull request so the conversation happen there, just let me know.

**Comment by smaldini** [comment]
Seems good, I need to sync the style of the project itself as we don't wrap over 90 but 120 I think. Should we include idea settings ?

**Comment by joaoevangelista** [comment]
Yes, it's just a file, even IntelliJ can import from eclipse I think it's better to have a "native" config. And since recent versions come with xml importer we don't need a Jar.
Should I open a pull request?

**Comment by smaldini** [comment]
Yup gohead Thanks a million

**Comment by joaoevangelista** [comment]
You're welcome, opened!
