### ISSUE TITLE
Externalise the creation of 'request' thread in EventLoopProcessor's via Executor ideally.

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#420]
Currently there is no way to give this thread a name.

**Comment by simonbasle** [comment]
@dfeist can you elaborate? `EventLoopProcessor` is abstract but its constructor accepts a `ThreadFactory`, which as far as I can see is used by the two implementations with factory methods taking a `name` for that very purpose...

Is there a combination of parameters in one of these factory methods that you feel is missing the `name` variant?

**Comment by simonbasle** [comment]
@dfeist can you elaborate? `EventLoopProcessor` is abstract but its constructor accepts a `ThreadFactory`, which as far as I can see is used by the two implementations with factory methods taking a `name`...

Which thread are you talking about precisely? Is there a combination of parameters in one of these factory methods that you feel is missing the `name` variant?

**Comment by dfeist** [comment]
@simonbasle I was referring to the thread used for requests. See `reactor.core.publisher.WorkQueueProcessor#requestTask`.  Here `new Thread()` is used directly.  Ideally this should use an `Executor` or a `Supplier<Thread>` to externalise the creation of the thread.

In out case we manage all executors and their threads centrally for monitoring etc, but this thread because it is created on the fly like this is therefore off-radar.

**Comment by simonbasle** [comment]
mmh so it's not really about the name, is it? (furthermore it inherits the name used by the processor)

**Comment by dfeist** [comment]
Correct, name is part of it of course, but as you say thats already dealt with quite well.  It's more about externalising it if possible. I updated summary of issue.

**Comment by smaldini** [comment]
I think we could provide a post creation configurator like FluxSink.onCancel(Disposable) but for potential onSubscribe(Subscription) : 
```public TopicProcessor/WorkQueueProcessor<T> onSubscribeHandler(ExecutorService)```

**Comment by dfeist** [comment]
@smaldini I'm not convinced about post-creation.  What happens if this is set have "request" thread has already been created?  Also isn't it more `requestTaskExecutor` than `onSubscribeHandler`?

**Comment by smaldini** [comment]
Edited a bit but its on onSubscribe that requestTask is created as you can publish to processor without onSubscribing it. The post-creation is mainly to not bloat over the create final properties we need for sure at creation time.

**Comment by smaldini** [comment]
Speaking of ExecutorService I think its due time that we consider these Processor to stop using ExecutorService and start using Scheduler that would allow us to consider rejecting some sort of Scheduler like global single/parallel and not elastic based on their spinning/blocking expectation.

**Comment by dfeist** [comment]
perceived bloat vs. allowing user to do things that don't make sense though and needing to explicitly fail in setter if it's used too late (doing nothing and it simply not being used, I don't think is a good idea).

Scheduler is fine by me, as long I you can still adapt from ExecurorService->Scheduler

**Comment by smaldini** [comment]
Thats because the processor works in dual mode, with or without onSubscribe and we can't know in advance what are you going to do with it. Regarding Scheduler, i think it goes further because allowing an ExecutorServiceScheduler doesn't offer particular guarantees about its parallelism. We might need to actually revisit the request task to not use a different thread at all and with operate work-stealing.

**Comment by smaldini** [comment]
Work stealing meaning that if you onSubscribe before any subscriber(and so thread actives) you run on the onSubscribe thread. If your subscribers drain enough data, one of them will try to request more data directly.

**Comment by dfeist** [comment]
Work stealing seems like a cleaner way to deal with requesting, assuming there are no disadvantages.

**Comment by simonbasle** [comment]
I have modified to use a final `ExecutorService`. There is one variant of `create` and `share` that allow you to set it (you'll have to provide **all** parameters). See PR #463.
