### ISSUE TITLE
concatMap/concatMapIterable/flatMapIterable on a cached Flux longer than 256 works wrong

### ISSUE THREAD

**Issue by dynaxis** [reactor/reactor-core#422]
Please see the code at https://github.com/dynaxis/reactor-bug .
The `Flux.concatMapIterable` on a cached `Flux`  longer than `256` doesn't pass the original elements as they are. Instead, the elements from the 2nd to 2567th, are repeated. `flatMapIterable` has the same problem though the code doesn't include code for showing it. `flatMap` works fine but `concatMap` not, FYI.

In the repo above, I added `RxJava2Test` to see if the equivalent operator works fine with RxJava2. Actually it does. Maybe this is helpful to point out what's wrong with Reactor's implementation.

**Comment by smaldini** [comment]
Can you try with 3.0.5.BUILD-SNAPSHOT we fixed this in #411 I think

**Comment by dynaxis** [comment]
Ok, I'll try and get back.

**Comment by dynaxis** [comment]
The snapshot build doesn't work too.

**Comment by dynaxis** [comment]
I guess `concatMap/concatMapIterable/flatMapIterable` and `flatMap` should work almost identical in getting the cached source `Flux` through the associated function. But only `flatMap` works.

The `256` number should be related to the default size of `UnboundedReplayBuffer`.

**Comment by smaldini** [comment]
Thanks a lot the quick run, found the issue will be part of 3.0.5 and in a moment in snapshot

**Comment by dynaxis** [comment]
Thanks. I'll depend on the snapshot build till 3.0.5 is available.

**Comment by smaldini** [comment]
Thanks again @dynaxis you had a very exemplary issue report btw 👍 That always helps a lot!
