### ISSUE TITLE
Add a meaningful but simple toString() to `QueueSubscription`

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#428]
Right now the default uses the iterator, which fails for this particular queue since it is not implemented.
We could just toString something static.

**Comment by simonbasle** [comment]
`on-hold`: in hindsight, this is an interface with many direct implementors. Not sure a static common toString value is really a good idea. Unless you remember this issue being about something else @smaldini ?

**Comment by smaldini** [comment]
it fails default toIterator/String interpolation by various frameworks since we fail toIterator(). We could at least provide a nice to string like "className-fused[pending=size()]"

**Comment by simonbasle** [comment]
closing this for now. you can't have a default `toString` method (or any other `Object` method) in an interface anyway.  maybe the introspection change will be able to help with that issue in the future, and libraries relying on `iterator()` could continue to be a problem.
