### ISSUE TITLE
ExecutorServiceScheduler interruptIfNeeded is not fully respected in worker

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#443]

**Comment by smaldini** [comment]
Currently mayInterruptIfNeed flag is not working as intended in ExecutorServiceScheduler#Worker.
future.cancel is called regardless of mayInterruptIfNeeded if worker is terminated (boolean1 || boolean2).

**Comment by simonbasle** [comment]
will be addressed by #459
