### ISSUE TITLE
TopicProcessor share(..) and create(..) fail silently when backlog size is 1.

### ISSUE THREAD

**Issue by masterav10** [reactor/reactor-core#445]
See this gist for a testcase demonstrating the behavior: [ReactorMultiSubscribeBehaviorTest.java](https://gist.github.com/masterav10/14f9f5f1628ad370f9fb9fcfbf8e9db6).

Essentially, a cryptic error appears at some point during the subscriptions, and I can't tell if it fails silently or if the logger is printing the exception since it doesn't bubble up from the test case.

I would have expected static factory method to throw the exception.

Tested using 3.0.5.RELEASE on Windows and LInux.

**Comment by simonbasle** [comment]
@masterav10 can you confirm the error message was `Spec. Rule 3.9 - Cannot request a non strictly positive number: 0`?

**Comment by masterav10** [comment]
Yessir.
