### ISSUE TITLE
repeatWhenEmpty() versions show different behaviour

### ISSUE THREAD

**Issue by twoseat** [reactor/reactor-core#46]
We tried switching cf-java-client from using `.repeatWhenEmpty()` with a `maxRepeat` value, to using the version that just takes a `repeatFactory`. This leads to a number of test failures caused by 'insufficient' mocking in the tests - a test that successfully provided two responses to a repeated request [(example)](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-operations/src/test/java/org/cloudfoundry/operations/applications/DefaultApplicationsTest.java#L584-L594) before our change fails with a null pointer exception because it's being asked to supply a third response with the new approach.

For now we're using the two parameter version with `MAXINT-1` as a workaround [(example)](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-util/src/main/java/org/cloudfoundry/util/JobUtils.java#L47). Should the two versions of `.repeatWhenEmpty()` differ in this way?

**Comment by akarnokd** [comment]
The operator is implemented differently for `MAX_VALUE` and non `MAX_VALUE`. I'm not sure what it supposed to do btw. I'd assume this repeats the source if it just completes without an `onNext`, but it is implemented via `repeatWhen()` and some other logic but I don't see the source being shared thus the operator could subscribe to the source twice.

**Comment by akarnokd** [comment]
See #47 for a possible fix; not sure how it would affect your mocks (as I don't do mocks myself).

**Comment by smaldini** [comment]
Pending verification after #47 merge

**Comment by twoseat** [comment]
Tested and working in latest snapshot
