### ISSUE TITLE
Flux.buffer() pushing to downstream when there are no more pending elements?

### ISSUE THREAD

**Issue by oleg-alexeyev** [reactor/reactor-core#48]
The use case is to implement adaptive batching: drain what's available on RingBuffer up to some maximum and push to downstream (DB in our case). That way batching automatically adapts to load, having minimum transaction lengths under normal load and fully utilize batching for better throughput under peak loads. This seems to be quite a common pattern. Is there a ready solution or could it be added to Reactor?

From implementation perspective, it seems quite straightforward, replacing the following line in `FluxBuffer.onNext()`:

> if (b.size() == size)

with something like

> if (b.size() == size || (source instanceof Backpressurable && ((Backpressurable)source).getPending() - 1 /\*to account for the current element being processed\*/ <= 0))

Please correct me if I'm wrong.

One other thing is that maximum buffer size - ideally there should be a variant with IntSupplier so that the max number of  elements drained to the buffer could be changed dynamically. I'm thinking of a strategy measuring transaction length and adjusting max batch size in order to fit into a goal (similar to G1 goals on GC pauses).

**Comment by akarnokd** [comment]
There's supposed to be a buffer version which buffers up to a maximum size or within a time window, whichever happens first.

The `IntSupplier` may conflict with prefetch/pipelining nature of sequences. Several operators request more before the previously requested amount is fully delivered. An IntSupplier would require awaiting the previous amount completely and issue a new request with additional latency. In addition, such dynamic parametrization requires per-sequence state which an IntSupplier can't do on its own.

**Comment by oleg-alexeyev** [comment]
Regarding `buffer(maxSize, timespan)`:
- The first issue I met was that `timespan` wasn't effective. It turned out that if I don't specify time `Flux.getTimer()` is used, which uses `Timer.globalOrNull()` and `FluxBufferTimeOrSize` gets initialized with `null` timer, treats this as a valid input and `buffer(maxSize, timespan)` works as `buffer(maxSize)`, what causes elements to stuck in the buffer. It would be very nice if it worked in a fast-fail manner to avoid debugging.
- Another thing which surprised me was that if the buffer is pushed downstream when timespan elapses, the downstream code is executed on the timer thread, not the one from `WorkQueueProcessor`'s pool. As my intention was to execute that db code always in one thread, I thought that this `buffer` version is not really suitable for my task. Later I realized that according to Reactive Streams rule 1.3, my downstream code shouldn't be called concurrently in different threads and then it would be perfectly suitable for the job. Is this really guaranteed for `buffer(maxSize, timespan)`?

I've now experimented with my own fork of `FluxBuffer`, `FluxAdaptiveBuffer`, but must admit I'm not very impressed by the result at the moment - I've managed to make it work with `WorkQueueProcessor` (not with `dispatchOn` as `FluxDispatchOn` doesn't implement `getPending`), but under the load it doesn't buffer much ending up with too many transactions on db :(.

Still, the idea might be more relevant in cases when more data come in one element (I had really small data in elements) or in cases when minimum latency is important and batching is also desired, e.g. we have some highly concurrent API calls. I'll get back to this topic later as we progress with reactorizing our app :).

**Comment by oleg-alexeyev** [comment]
Could you comment on the question above regarding `buffer(maxSize, timespan)` behavior?

**Comment by akarnokd** [comment]
I can't comment on `WorkQueueProcessor` but it sounds like @smaldini has to do something about, perhaps align with Rsc's views? I don't know about `buffer(maxSize, timespan)` here, it still looks like it was implemented before Rsc; it should serialize its output as both the timer thread and the main source thread may emit at the same time.

**Comment by smaldini** [comment]
@oleg-alexeyev It should use serialization via thread stealing so whoever is first is doing the job while the other thread enqueues its event. You would see more timer thread onNexting in case your timeout is too short for instance.

**Comment by oleg-alexeyev** [comment]
Thanks for confirmation!

**Comment by smaldini** [comment]
I'll close that issue for now, don't hesitate to trigger the open issue back anytime !
