### ISSUE TITLE
EventBus will be deprecated - What is substitute for him? 

### ISSUE THREAD

**Issue by aviadhadida** [reactor/reactor-core#483]
Hi we tried to migrate the event Bus to processors with no success(Less throughput and speed than the processor, maybe because of misuse). We had one wrapper and one event bus in the application which was working with all events in the system. We have tried to split events between modules(Something like every moudle will have is own event bus/ processor) and maybe we are not using processors right.
We need help here, tried to read the docs but still couldn't find it. 
How we can migrate and still not harm the performance of our application?
Thanks

**Comment by simonbasle** [comment]
you have already opened an issue with [the exact same question](https://github.com/reactor/reactor-core/issues/393) (#393), please refrain from opening duplicate issues...

**Comment by aviadhadida** [comment]
NP. Sorry for that we have just got into real need to upgrade reactor version and it conflicts with using event bus and we have real concern that it will be deprecated soon. This is a real time trading system that already in production.
Thanks for your help

**Comment by pe-qwe** [comment]
Hi, did you find a solution to your problem?
