### ISSUE TITLE
Flux.windowTimeout to start timer right away

### ISSUE THREAD

**Issue by devrandom** [reactor/reactor-core#484]
`Flux.windowTimeout(int, Duration)` starts the timer after the first element of a window is received.  This means that empty windows are not generated.  It would be desirable to have an alternative behavior where the timer is started right after subscription and after each window is emitted, so that we always get a window emitted at least once per duration.

The use case is where we want the output to also function as a heartbeat.

If both behaviors are desirable, then perhaps a second version of this method or a flag could be added.  Alternatively, if the old behavior is dropped, then that behavior could be still be easily obtained by adding a filter stage for window size `> 0`.

**Comment by simonbasle** [comment]
Yeah we should start the timer right at subscription time. This is what is done in RxJava if I'm not mistaken, and sound like the correct behavior.
