### ISSUE TITLE
Mono.When API handle Mono.Empty parameter as Unfulfilled Monos

### ISSUE THREAD

**Issue by ulyssesjason** [reactor/reactor-core#488]
Reactor Version: '3.0.4.RELEASE'
used in Spring Boot: 1.4.3.RELEASE

While using

```
Mono<T> object1 = Mono.just(new Object())
Mono<T> object2 = Mono.empty
Mono.When(object1, object2).map()...

```
if object1 has valid content but object2 is Mono.empty, then the Mono.when is instantly return as empty.

Is there a better way to handle corresponding situation(or in the future release)?

> I want to keep handling the whole mono parameter list even some of them are Mono.empty, such as form a big response with partial pieces still be in it instead of a whole empty response.
> 

Right now we have to put a otherwiseIfEmpty and otherwiseReturn for every parameter for when API, if mono.when could accept Optional parameter of Mono, or similar mechanism, it could be a helpful. (or not using when api, but a new api that tolerate partial mono empty input)

**Comment by simonbasle** [comment]
After discussing this with @smaldini, we don't think we'll add that feature. We don't really want to duplicate the current `Mono.when`/`Mono.whenDelayError` API to accommodate for empty sources.

You already have found the workaround (and need to deal with errors too, so you'd still need to "customize" each source anyway...).
You could maybe come up with a helper function to do that in a more readable way (but I guess that maybe each source's `otherwiseIfEmpty` need custom tailoring).

I'll however mark it as `addons-candidate`, as we may introduce a new addons artifact with supplementary operators like this in the future (goal would be to provide extra utilities for people that care less about the lean aspect of the API, while keeping that aspect in `reactor-core`).
