### ISSUE TITLE
Add `toOptional` blocking operator for Mono

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#492]

**Comment by simonbasle** [comment]
Not sure we want that since it can encourage *blocking* 😨. It is even a bit misguiding, as it is not obvious that converting to an `Optional` would block (especially if you don't know that `Optional` is `final`). Maybe naming it `blockOptional` could help with that...

**Comment by hisener** [comment]
Sorry to resurrect this issue. Recently I asked a question in [gitter.im](https://gitter.im/reactor/reactor?at=6103f1b2d8381a2a839de6fb) but it didn't get any traction. I think it's somewhat related to this issue so I wanted to try my chance here, as well. :)

---

We have a code that converts `Mono<T>` to `Mono<Optional<T>>`, it simply converts `Mono.just(T)` -> `Mono.just(Optional.of(T))` and `Mono.empty()` -> `Mono.just(Optional.empty())`.

We have two flavors for that conversion:

1.
```
mono()
  .map(Optional::of)
  .defaultIfEmpty(Optional.empty())
```

2.
```
mono()
  .flux()
  .collect(MoreCollectors.toOptional()) // from Guava.
```
Would it make sense to add a `#toOptional` method to `Mono`? There is already `#blockOptional` that returns Optional, for instance, and also `#justOrEmpty` that accepts `Optional`.

**Comment by hisener** [comment]
Thanks for the answer. I agree that there is not much value.

A question for option 2, is there any downside of doing `Mono` to `Flux` conversion just to map it to an `Optional`? E.g., potential performance impact, etc.

**Comment by simonbasle** [comment]
@hisener indeed that second approach is a bit redundant, just to be able to apply a `Collector`. That said, the number of wrapping is the same: map() and flux() both create a second publisher instance that wraps the original, and defaultIfEmpty() and collect() respectively create a third instance over that. `map()` and `defaultIfEmpty()` have very simple internal behavior, so the solution with an additional `Collector` might be a bit at a disadvantage here too.
