### ISSUE TITLE
Interrupt issue with DispatchOn

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#50]
Original from https://github.com/reactive-streams/reactive-streams-jvm/issues/310 by @sskrla

When using .dispatchOn Flux calls .interrupt() on the current thread (via scheduler.accept(null)) before it calls the onError or onComplete.

Specifically, this caused issues using the ElasticSearch client as it throws an exception if the current thread is an interrupted state when you make a blocking API call.

For example:
```
Flux.from(documents)
    .dispatchOn(processorsExecutorService)
    .buffer(batchSize)
    .onNext( requests -> {
        BulkRequestBuilder builder = client.prepareBulk();
        requests.forEach(builder::add);
        builder.get() // Throws interrupted exception on last batch
    })
    .subscribe()
```

**Comment by akarnokd** [comment]
Two options:

  - Release the scheduler **after** the terminal event has been emitted. Drawback: potentially longer retention.
  - Make sure the `Future.cancel()` is called with `false` if the current thread happens to be the thread running the task.

**Comment by smaldini** [comment]
I actually wonder which `interrupt` @sskrla is referring to since it should be the current dispatcher strategy for SchedulerGroup at least. I guess since it was referring to Fluxion which offered `dispachOn(ExecutorService)` as in RSC it is this one.

**Comment by smaldini** [comment]
As a second issue, adding ExecutorService to Flux should be considered, opened #51.

**Comment by smaldini** [comment]
@akarnokd do you know if we face that issue still in RSC ExecutorService support ?

**Comment by akarnokd** [comment]
Due to a recent update, Rsc's `observeOn` shuts down the worker after `onComplete` has been delivered. At that point, all that's left is the end of the wrapper action on the scheduler and no user code can be executed that would throw on an interrupted thread. Otherwise, it still interrupts itself at that point which adds some overhead. I can work around that if necessary.

**Comment by smaldini** [comment]
I'll sync it as it for now thanks @akarnokd .
