### ISSUE TITLE
`Mono.then(Function)` to be renamed `flatMap`, `flatMap` to be renamed `flatMapMany`

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#516]
**update**: after discussing this, it seems more correct for `Mono`'s `flatMap` to do what `then(Function)` currently does (map a value to a Mono and "flatten" to this `Mono`).
As a consequence, this would mean the current `Flux<R>`-returning `flatMap` would need to be renamed `flatMapMany`.

~Candidate new name: `mapWhen(Function<T, Mono<R>>)`.~

This will remove the inconsistency of the `then` version that needs the source to be valued to work, unlike all other `then` variants. This will also improve the usage in languages like Kotlin and Scala, where the lambda parameters can be omitted but that brings an ambiguity with the `then(Supplier)` variant.

~To reduce migration friction, the operator can be introduced as an alias and old version marked as deprecated in 3.1.0.M1 and removed in 3.1.0.RELEASE.~ due to name clashing, the change cannot be eased into with a deprecation during M1 though...

**Comment by sdeleuze** [comment]
Big +1 for disambiguate that from a Kotlin POV, but also from a Java one (changing the behavior based on the number of lambda arguments could lead to very tricky issue to debug).

But I am wondering with the new name since with Stéphane we chosen `then()` thinking about `Promise` world so would be nice to be able to keep the prefix `then`.

So what about `thenMap(Function<T, Mono<R>>)` for the new name, seems to be consistent with the `MonoThenMap` internal type and with `flatMap()` also.

**Comment by simonbasle** [comment]
ping @smaldini @rstoyanchev for the naming

**Comment by simonbasle** [comment]
`consider-backport` of the deprecation + aliasing to `3.0.x`

**Comment by rstoyanchev** [comment]
It always not intuitive to me conflating then as in "continue after" and then as in "map + nest". It's easy for example to overlook that `Mono<Void>` won't ever produce an item. 

It's also disconnected from `Mono#flatMap` which is conceptually what I'm looking for and what I'm used to from using `Flux#flatMap` as well. There is already an established pattern for overloading `flatMap` -- `flatMap`, `flatMapIterable`, `flatMapSequential` for `Flux` and `flatMap`, `flatMapIterable` for `Mono`. So couldn't we have `flatMap`, `flatMapFlux`, `flatMapIterable`?

RxJava follows this pattern and looking to Java both `Stream` and `Optional` have `flatMap`. Unless there is some significant issue from a naming perspective I don't see how any of the alternatives can be better than aligning with the established terminology for this sort of thing.

**Comment by simonbasle** [comment]
@rstoyanchev IMHO if anything `mapWhen` is the degenerative case of a `flatMap`, so if we use that prefix I think we shouldn't rename `Mono#flatMap` to _flatMapFlux_ but rather `Mono#then(Function)` to `Mono#flatMapMono` (or something similar).

**Comment by simonbasle** [comment]
`3.0.x` "backport" strategy (as discussed with @smaldini):
 - [ ]  mark `Mono#then(Function)` as deprecated **only in javadoc**
 - [ ] add `Mono#flatMapMany` alias
 - [ ] mark `Mono#flatMap` as deprecated (both javadoc & annotation), hint to `flatMapMany`
