### ISSUE TITLE
Thread affinity and publishOn() operator

### ISSUE THREAD

**Issue by dmitrievanthony** [reactor/reactor-core#521]
It's just a question about operator publishOn() and thread affinity. 
Currently it's not clear from documentation is it guaranteed that one subscriber will be processed in one thread after publishOn() operator.

I've tested the following case:
```
Flux<String> started = ep.publishOn(scheduler);
Flux<String> afterStateUpdate = started.doOnNext(e -> {
    System.out.println("STATE UPDATE : " + Thread.currentThread().getId());
    state.add(e);
}).share();
afterStateUpdate.subscribe();
ep.onNext("1");
ep.onNext("2");
ep.onNext("3");

afterStateUpdate.subscribe(e -> {
    System.out.println("MAIN SUBSCRIBER : " + Thread.currentThread().getId());
});
ep.onNext("4");
ep.onNext("5");
ep.onNext("6");
```

And got this result:

```
STATE UPDATE : 12
STATE UPDATE : 12
STATE UPDATE : 12
STATE UPDATE : 13
MAIN SUBSCRIBER : 13
STATE UPDATE : 13
MAIN SUBSCRIBER : 13
STATE UPDATE : 13
MAIN SUBSCRIBER : 13
```

Result means that state update subscriber had been working in one thread and then started working in another. Is it correct behavior?

And my main question, how can I guarantee thread affinity for a subscriber?

**Comment by dmitrievanthony** [comment]
I found only one way to be 100% sure that one subscriber uses the same thread. It's to create a pool of single schedulers like this:

    Scheduler[] schedulers = new Schedulers[10];
    for (int i = 0; i < 10; i++) {
      schedulers[i] = Schedulers.newSingle();
    }

And then for every subscriber take a one scheduler from this pool. If anyone know other way to provide thread affinity - please correct me.

**Comment by dmitrievanthony** [comment]
I've checked your test and it looks like it differs from my case, i.e in my example i basically do the following:

1. First subscriber is added.
2. Several messages are emitted by `onNext(x)`
3. Second subscriber is added.
4. Several messages are emitted by `onNext(x)`.

And as result processing of first subscriber starts on one thread on step 2, and than the processing switches to another thread on step 4 (likely because of new late subscriber). This is where i think thread affinity doesn't satisfied.
Your test is about two subscribers starting listening to messages before any messages are published.

**Comment by rajinisivaram** [comment]
@dmitrievanthony I have created PR #698 to test the sequence you described.

**Comment by dmitrievanthony** [comment]
Thank you very much, looks like it works for 3.0.7 versions (on version 3.0.4. test fails).
