### ISSUE TITLE
Compilation error - VERSION: 3.0.6.RELEASE

### ISSUE THREAD

**Issue by MarianneAbdelmalek** [reactor/reactor-core#530]
I have been using project reactor for some time now (VERSION:  3.0.6.RELEASE), but today while building a compilation error was newly introduced in the following lines of code:

```
private Mono<ServerResponse> byId(ServerRequest request) {

		return Mono.just(request)
                .map(req -> req.pathVariable("id"))
                .filter(idStr -> idStr.matches(UUID_PATTERN))
                .map(UUID::fromString)
                .map(tripRepository::byId)
                .filter(tripEntity -> tripEntity.getId() != null)
                .map(TripView::getTripView)
                .then(t -> ServerResponse.ok().body(Mono.just(t), TripView.class))
                .otherwiseIfEmpty(ServerResponse.unprocessableEntity().build());
	}
```

The error reads:

> no suitable method found for then((t)->Serve[...]lass))
> [ERROR] method reactor.core.publisher.Mono.<V>then(reactor.core.publisher.Mono<V>) is not applicable
> [ERROR] (cannot infer type-variable(s) V
> [ERROR] (argument mismatch; reactor.core.publisher.Mono is not a functional interface))
> [ERROR] method reactor.core.publisher.Mono.<V>then(java.util.function.Supplier<? extends reactor.core.publisher.Mono<V>>) is not applicable
> [ERROR] (cannot infer type-variable(s) V
> [ERROR] (argument mismatch; incompatible parameter types in lambda expression))
> [ERROR] -> [Help 1]

**Comment by sdeleuze** [comment]
You are likely using `3.1.0.BUILD-SNAPSHOT` version which changed `then(Function)` to `flatMap(Function)`, so you can fix your dependency management or keep using 3.1 and rename `then` to `flatMap` for lambda taking one input parameter. `then()` now is only about doing something on complete without using the incoming value.

**Comment by MarianneAbdelmalek** [comment]
Works, thanks.
