### ISSUE TITLE
Verify is missing from reactor-test 3.0.6

### ISSUE THREAD

**Issue by bearrito** [reactor/reactor-core#537]
I'm following http://projectreactor.io/docs/core/release/reference/docs/index.html#_testing_a_scenario_with_code_stepverifier_code

I do no see the verify method available.

![no_verify](https://cloud.githubusercontent.com/assets/1908139/25050195/0751b8a8-2114-11e7-89c1-d25ed17caa1e.png)

**Comment by simonbasle** [comment]
hey @bearrito, as stated in the reference documentation, there is a difference between expectations on the intermediate events (the values) and the **terminal** events (complete or error). `verify()` is only available once you've expressed a terminal event expectation, for instance `expectComplete()`.

> For terminal events, the corresponding expectation methods (expectComplete(), expectError() and all its variants) will switch to an API where you cannot express expectations anymore. In that last step, all you can do is perform some additional configuration on the StepVerifier then trigger the verification.

If your publisher is infinite, you can `thenCancel()` it rather that expecting a terminal event, and that should correctly interrupt the sequence and terminate the test.

**Comment by bearrito** [comment]
`thenCancel()` l is what I was looking for. Sorry for the noise.
