### ISSUE TITLE
Don't forget to update project version in marble links in GA phase

### ISSUE THREAD

**Issue by artembilan** [reactor/reactor-core#565]
Right now it looks suspicious to have:
```
* <img class="marble" src="https://raw.githubusercontent.com/reactor/reactor-core/v3.0.6.RELEASE/src/docs/marble/ignorethen1.png" alt="">
```
in the version `3.1.B-S`.

Also review if marbles on methods are really reflect reality of the proposed API.
Maybe rename some files to be more clear.

**Comment by smaldini** [comment]
Should be accurate now
