### ISSUE TITLE
Let `Mono.subscribe()` return a `Disposable` rather than a `MonoProcessor`

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#566]
To align with `Flux.subscribe()`, make `Mono.subscribe()` return a plain `Disposable`. Having it return a `MonoProcessor` is confusing, as it can lead to writing code like `mono.subscribe().subscribe(new BaseSubscriber() {...})`.

(note that since this is a breaking change on the return type, there's no possibility of deprecating the method first in M1, so this will target M2)

**Comment by simonbasle** [comment]
as discussed with @smaldini, we'll have `subscribe` return a `Disposable` just like the other variants with callbacks. The equivalent of the current implementation that returns a `MonoProcessor` will be kept as `toProcessor()`.

**Comment by osi** [comment]
This removed the ability to make a `Mono` be eagerly "hot" in-line. On a Flux you can do:

`Flux.replay().autoConnect(0).anotherOperator`

and that used to be `Mono.cache().subscribe().anotherOperator`

**Comment by simonbasle** [comment]
@osi doesn't it work with `Mono.cache().toProcessor().anotherOperator`?

**Comment by osi** [comment]
Mono.toProcessor() doesn't call MonoProcessor.connect()

--
(peter.royal|osi)@pobox.com - http://fotap.org/~osi


On Fri, May 26, 2017, at 12:56 PM, Simon Baslé wrote:
> @osi[1] doesn't it work with
> Mono.cache().toProcessor().anotherOperator?> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/osi
  2. https://github.com/reactor/reactor-core/issues/566#issuecomment-304348848

**Comment by simonbasle** [comment]
@osi created an issue to have an alternative that calls `connect()` and can be used inline.
