### ISSUE TITLE
refCount with a delay before disconnecting from upstream

### ISSUE THREAD

**Issue by osi** [reactor/reactor-core#569]
Related to the https://github.com/reactor/reactor-core/blob/master/src/main/java/reactor/core/publisher/FluxRefCount.java#L116 (subscribers coming and going below threshold concurrently), one feature I had in my non-reative code I'm migrating was a delay after the count going to 0 before unsubscribing from the source. 

In my systems, the main "race" of this type is a subscriber going away and immediately coming back (milliseconds to seconds duration). Being able to delay the unsubscribe for a duration would help "trashing" of publishers that might be more expensive to setup (say, sourced by IPC).

**Comment by simonbasle** [comment]
API wise we could maybe add a variant to `Flux.refCount` with an additional **`gracePeriod`** `Duration` parameter that would only delay the unsubscription if set?

**Comment by osi** [comment]
that'd satisfy my use-case. and _gracePeriod_ is good terminology too.

**Comment by akarnokd** [comment]
FYI: https://github.com/akarnokd/RxJava2Extensions/blob/master/src/main/java/hu/akarnokd/rxjava2/operators/FlowableRefCountTimeout.java

**Comment by simonbasle** [comment]
@akarnokd 😍 
@osi @smaldini  I wonder if it would make more sense as an extra operator in `reactor-extra` (similar to the above being in RxJava2Extensions for RxJava)? It is maybe a bit "niche"...

**Comment by osi** [comment]
no opinion on where it ends up. since it would be mostly the same as refCount, that might be an argument for being in core for easy code sharing.

**Comment by smaldini** [comment]
I think it should be core. Nice job @akarnokd, we'll probably port it for M2.

**Comment by osi** [comment]
It would be nice to be able to specify which scheduler to use for the grace period, rather than requiring the elastic (for API parity elsewhere where the scheduler can be specified)
