### ISSUE TITLE
Potential "never drain" bug in the SerializedSink

### ISSUE THREAD

**Issue by artembilan** [reactor/reactor-core#575]
The `SerializedSink` does delegation to the other `FluxSink` impl.
When that one throws exception on the `sink.next(t)`, we never decrease `wip` and, therefore never pass the next value to downstream.
My use-case is based on the `.retry()` and idea to never terminate the source in case of errors on the item.
The test-case looks like:
```
@Test
	public void testProcessorRetry() {
		FluxProcessor<Integer, Integer> processor = DirectProcessor.create();

		FluxSink<Integer> sink = processor.sink();

		List<Integer> results = new ArrayList<>();

		processor.retry()
				.subscribe(new Subscriber<Integer>() {

					@Override
					public void onSubscribe(Subscription subscription) {
						Assert.notNull(subscription, "'subscription' must not be null");
						subscription.request(Long.MAX_VALUE);
					}

					@Override
					public void onNext(Integer integer) {
						if (integer == 5) {
							throw new IllegalStateException("error");
						}
						results.add(integer);
					}

					@Override
					public void onError(Throwable throwable) {
						Operators.onErrorDropped(throwable);
					}

					@Override
					public void onComplete() {

					}

				});

		for (int i = 0; i < 10; i++) {
			try {
				sink.next(i);
			}
			catch (Exception e) {
				assertThat(e, instanceOf(IllegalStateException.class));
				assertThat(e.getMessage(), containsString("error"));
			}
		}

		assertFalse(processor.isTerminated());
		assertTrue(processor.hasDownstreams());

		assertEquals(0, ((Scannable) sink).scan(Scannable.Attr.BUFFERED));

		assertThat(results, contains(0, 1, 2, 3, 4, 6, 7, 8, 9));

	}
```

So, with the `.retry()` I really re-subscribe to the `processor` and never terminate it.
But since we have this code in the `SerializedSink`:
```
if (WIP.get(this) == 0 && WIP.compareAndSet(this, 0, 1)) {
	sink.next(t);
	if (WIP.decrementAndGet(this) == 0) {
		return this;
	}
}
```
we don't step to the  `if (WIP.decrementAndGet(this) == 0) {` because no `try...catch...finally` around `sink.next(t);`.
Since we nowhere else we perform decrement we neven overcome the next condition:
```
if (WIP.getAndIncrement(this) != 0) {
	return this;
}
```
to go to the `drainLoop()`.

Another observation (maybe deserves separate issue) is like `LambdaSubscriber`:
```
try {
	if (consumer != null) {
		consumer.accept(x);
	}
}
catch (Throwable t) {
	Exceptions.throwIfFatal(t);
	this.subscription.cancel();
	onError(t);
}
```
And I somehow can't find how `FluxRetry` deals with that `cancel()`.
On the other hand it may not do anything  anyway, just because it is already subscriber wish to cancel or not.
Only the concern from my side that it is surprise to use `retry()` and be canceled in case of simple `Consumer` subscription.

That's why I use direct `Subscriber` in the test to meet my fault-tolerant requirements.

Thanks!

**Comment by akarnokd** [comment]
This is not allowed in a plain `Subscriber`:

```java
throw new IllegalStateException("error");
```

**Comment by artembilan** [comment]
@akarnokd ,
Thank you for the quick feedback, but it is a little bit not full.
You say "not allowed". OK, what is allowed then, please?

On the other hand with the `Consumer`-based subscriber the `retry` becomes useless in my understanding of the behavior I see.

**Comment by akarnokd** [comment]
When implementing a `Subscriber` manually, you are to follow the Reactive-Streams specification. This case is handled by rule [§2.13](https://github.com/reactive-streams/reactive-streams-jvm#2.13), which basically says don't throw from the `onXXX` methods.

This is allowed:

```java
@Override public void onNext(Integer integer) {
    if (integer == 5) {
        subscription.cancel();
        onError(new IllegalStateException("error"));
        return;
    }
    results.add(integer);
}
```

This is also allowed:

```java
processor.map(v -> {
    if (v == 5) {
       throw new IllegalStateException("error"));
    }
    results.add(v);
})
.retry()
.subscribe(...);
```

**Comment by artembilan** [comment]
OK. I got it @akarnokd !

Thank you!

So, `errorConsumer` is something "must do" in such a case.
Not sure why do we need `retry()` then though if we always swallow exceptions with the `onError()`...

Anyway the original issue about `SerializedSink` remains independently of my subscriber implementation.

**Comment by simonbasle** [comment]
the thing is you don't really swallow the exceptions in an `onNext`, `onComplete`, etc... the rule linked above is about avoiding **throwing** an `Exception` and instead propagating it through `onError`. (the throw from inside the `map` lambda is ok because `map` does just that: it catches any Exception from the lambda and propagates it to `onError`)

**Comment by artembilan** [comment]
Thank you, guys, for all your wisdom, but I see that you don't follow your own recommendations - `LambdaSubscriber`:
```
public final void onNext(T x) {
		try {
...
		}
		catch (Throwable t) {
			Exceptions.throwIfFatal(t);
			this.subscription.cancel();
			onError(t);
		}
	}
```
Jumping further I see that `Exceptions.throwIfFatal(t)` does the re-throw.
And there are several re-throw cases in the `LambdaSubscriber.onError()` implementation...

So, the original issue about never drain in the `SerializedSink` is still here.

What ma I missing again?

Thank you!

**Comment by simonbasle** [comment]
The `throwIfFatal` is for a very particular corner case, as it only throws if the error is irrecoverable at the application level. This includes OOM but also a couple of Reactor internal fatal exceptions... All of these warrant a stop of the whole sequence though.

@artembilan In your original issue, the problem was that a call to `sink.next` would throw an exception? The whole thing wasn't hanging, right?

**Comment by artembilan** [comment]
No, it isn't hanging.
Is this test-case much cleaner for you?
```
FluxProcessor<Integer, Integer> processor = DirectProcessor.create();

FluxSink<Integer> sink = processor.sink();

List<Integer> results = new ArrayList<>();

processor.subscribe(integer -> {
	if (integer == 5) {
		throw new IllegalStateException("error");
	}
	results.add(integer);
});

for (int i = 0; i < 10; i++) {
	try {
		sink.next(i);
	}
	catch (Exception e) {
		// Exceptions$ErrorCallbackNotImplemented
		assertThat(e.getCause(), instanceOf(IllegalStateException.class));
		assertThat(e.getMessage(), containsString("error"));
	}
}

assertFalse(processor.isTerminated());

assertEquals(0, ((Scannable) sink).scan(Scannable.Attr.BUFFERED));
```
Yes, there is no subscriber any more because it is cancelled during the error in the `LambdaSubscriber`. But the `sink` is still able to accept data and store it in its internal queue forever as you see by the latest assertion.
