### ISSUE TITLE
Memory leaks when using concatMap and subscribeOn Schedulers.newSingle

### ISSUE THREAD

**Issue by fvlad** [reactor/reactor-core#578]
When running the following test:
```
@Test
    public void test() throws Exception {
        AtomicLong counter = new AtomicLong(0L);
        Scheduler scheduler = Schedulers.newParallel("scheduler", 10);
        Flux
            .<Long>generate(sink -> sink.next(counter.getAndIncrement()))
            .concatMap(i -> {
                return Mono.just(i)
                    .publishOn(scheduler)
                    .map(number -> number * 2L);
            })
            .subscribeOn(Schedulers.newSingle("subscriber"))
            .subscribe(new BaseSubscriber<Long>() {
                @Override
                protected void hookOnSubscribe(Subscription subscription) {
                    subscription.request(10);
                }

                @Override
                protected void hookOnNext(Long value) {
                    upstream().request(1);
                }
            });

        Thread.sleep(100000000);
    }
```
Memory starts to leak.
Thanks to @dfeist the leak seems to be here `reactor.core.scheduler.SingleScheduler.SingleWorker#tasks` and as a workaround scheduler can be replaced with
`.subscribeOn(Schedulers.fromExecutorService(Executors.newSingleThreadExecutor()))`.

**Comment by simonbasle** [comment]
(memory snapshot screenshot taken from gitter)
![image](https://cloud.githubusercontent.com/assets/6986166/25656319/c88b57de-2ff8-11e7-91a4-3fab5c07b472.png)

**Comment by akarnokd** [comment]
See #581.

**Comment by simonbasle** [comment]
Cause: For some calls to `SingleScheduler.schedule`, instead of submitting a decorated task (`ScheduledRunnable`) to the ExecutorService, the task lambda itself is submitted. As a result, it never calls the cleanup code embedded in `ScheduledRunnable`, hence the leak.

(thanks @akarnokd)
