### ISSUE TITLE
Operator and Scannable support for naming and tagging a flow

### ISSUE THREAD

**Issue by osi** [reactor/reactor-core#579]
edit: this issue has grown in scope, see comments from https://github.com/reactor/reactor-core/issues/579#issuecomment-314154258

original issue:
In diagnosing flows, it would be handy to be able to attach a "name" or "description" attribute to a Flux/Mono that could be introspected via Scannable.

**Comment by simonbasle** [comment]
@osi interesting idea. how do you see that name/description being attached? did you mean to the whole chain (eg. for `Flux<Integer> flux1 = Flux.just("foo").map(String::length)` the name would be attached to flux1) or something more static, per operator to get the name of each operator?
how would the introspection behave in case 1, if multiple attempts at attaching the name are made?

**Comment by osi** [comment]
my thought was that the name would be attached to flux1. similar to how `log` can be used to log at that point in the chain. the use-case i had in mind was in the pluggable hooks for handling uncaught exceptions, being able to introspect the flux/mono that was involved in the exception for better diagnosis. i have many different live streams in my application and figuring out which one based on what the stack trace looks like can be tricky.

even fancier would be to have all stack traces include the name, similar to how logback includes the jar name in stack trace lines (https://logback.qos.ch/reasonsToSwitch.html)

**Comment by simonbasle** [comment]
@osi have you looked into `checkpoint`?

**Comment by osi** [comment]
i was inspired by reading about `checkpoint`. i'll experiment with that - i was initially turned away from it because of the overhead of stacktrace capture (i'd like to have something safe to have on in production all the time). but i should probably measure the actual impact instead of guessing :)

**Comment by simonbasle** [comment]
We got a suggestion to offer a `checkpoint` variant where the stacktrace fill is omitted when there is a `description` provided. That might be the best of both worlds ;)
Looks like I forgot to open an issue for that, so here it goes: #587

**Comment by osi** [comment]
ah, yes, that might be a winner (and the checkpoint description could still be made into a Scannable attribute :)

**Comment by osi** [comment]
another place the "name" could be used - if a chain is subscribed to a TopicProcessor, which names its threads after the TopicProcessor name, `name-#`, it would be handy to have a name that might be the lightweight checkpoint name, or something else, replace the `#` in the thread name to be more helpful when looking at thread dumps

**Comment by simonbasle** [comment]
Here is where we think we'll go with that:
 - [ ] add utility method to extract a default name from class name (removing prefixes / suffixes, etc..) and have toString of `Flux` / `Mono` use that.
 - [ ] add a `FLOW_NAME` attribute: a String which would default to null and could be set by the user through a `namedAs(String)` operator (bit like checkpoint)
 - [ ] add `Scannable#flowName()` that walks the `parents()` and find the closest `FLOW_NAME`.
 - [ ] add a `TAGS` attribute: a Set of String which would default to null and could be set by the user at various points in the flow via a `taggedWith(String... tags)` operator
 - [ ] add `Scannable#tags()` that walks **all** `parents()` to merge their sets of tags.

**Comment by simonbasle** [comment]
This issue is not only fixed by e4d7635 but by multiple commits : 7c015a6, 011e7a2, 51a0fb0, 7d23703, a6289c2, e4d7635. (another rebase-and-merge that should have been a squash-and-merge, see #738)
