### ISSUE TITLE
Improve handling of specific Throwable types

### ISSUE THREAD

**Issue by rwinch** [reactor/reactor-core#58]
Right now it is a bit cumbersome to handle an error of a specific type.

For example, if I need `Mono.otherwise` to handle only a specific error I just do:

```java
.otherwise( t -> {
	if(t instanceof SpecificException) {
		return ...
	}
	return Mono.error(t);
}
```

It would be nice if we had something similar to `Flux.doOnError(Class<E> exceptionType, Consumer<E> onError)`.

There are likely other places that sort of handling would be nice.

**Comment by nebhale** [comment]
@rwinch It seems that you and the `cf-java-client` team have come up with this independently.  We actually created a [utility](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-util/src/main/java/org/cloudfoundry/util/ExceptionUtils.java#L73-L81) used [like this](https://github.com/cloudfoundry/cf-java-client/blob/7847bdd16b6f77d193584218a2ebc6add74e9e1d/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/stacks/DefaultStacks.java#L56) to do what you're asking for.  Now that we've got multiple people coming up with the same requirements, it would seem time to promote into the framework.

**Comment by smaldini** [comment]
I'll find some time to add a couple of them before M3

**Comment by joaoevangelista** [comment]
Something like that ?

``` java

public final Mono<T> otherwise(Class<? extends Throwable> exceptionType, Supplier<Mono<T>> fallback) {
		return otherwise(e -> {
            if (exceptionType.isAssignableFrom(e.getClass())) {
                return fallback.get();
            } else {
                return Mono.error(e);
            }
        });
	}
```

**Comment by smaldini** [comment]
What do you think @rwinch , @joaoevangelista  @nebhale of a vararg pattern instead ? :

 ```public final Mono<T> otherwise(Supplier<Mono<T>> fallback, Class<? extends Throwable>.... exceptionType) {``` 

e.g.:
```
mono.otherwise(fallback(), AuthenticationException.class, NotFoundException.class)

**Comment by joaoevangelista** [comment]
Seems nice, if you don't know exactly what type of exception will occur and we avoid chaining multiple times `otherwise` for each exception, maybe add to other `Mono#doOnError` and ´Flux#onErrorResumeWith`, `Flux#doOnError` methods ?

**Comment by smaldini** [comment]
related to #81 #80 #84

**Comment by smaldini** [comment]
Closing since duplicate with #81 #84 #80
