### ISSUE TITLE
distinctUntilChanged variant that accepts a BiPredicate

### ISSUE THREAD

**Issue by osi** [reactor/reactor-core#608]
`Flux<T> distinctUntilChanged(BiPredicate<T> predicate)` would allow "distinct until changed" to operate as a "jitter"

my use case is a stream of complex objects where simple equality isn't a sufficient test. there's an allowed "slop" of change in values that should limit downstream emissions.

**Comment by simonbasle** [comment]
Do you mean it like a trigger on a variance between the current element and the previous element @osi ? That would be a totally new operator I think. Furthermore, it will easily devolve into requiring the 3 value variant, then 4, then etc... I'm not sure we want to go down that path in core.

You could try rolling your own solution (maybe `create` with a state could work) or this could be a candidate for the `reactor-extra` addon.

wdyt @smaldini?

**Comment by osi** [comment]
yes, trigger on variance between the current and previous.  think of a calculation that is producing a Double, but I only want to emit if the new value is 0.005 different from the last emitted value.

my thinking was that the current implementation could be transformed to use a BiPredicate easily, thus the enhancement idea

```
Function<T,K> keyExtractor;
BiPredicate<K,K> comparator = Object::equals;
T newValue;
T lastValue;

if(comparator(keyExtractor.apply(lastValue),
              keyExtractor.apply(newValue))) {
    return false;
        }

lastValue = newValue;
actual.onNext(newValue);
return true;

```

**Comment by simonbasle** [comment]
After looking at your PR and back at the original use case, this doesn't sound like the correct name/operator. Elements that **are** distinct would be eliminated... Sounds more like a new specialization of `takeUntil` (that would need its own name, maybe `takeUntilDifference`?
