### ISSUE TITLE
scan(initial, accumulator) variant that will accumulate-then-emit

### ISSUE THREAD

**Issue by osi** [reactor/reactor-core#609]
To make `Flux#scan(initial, accumulator)` more useful with infinite streams, it would be nice if it behaved like this:

```
        StepVerifier.create(Flux.<Integer>create(sink -> {
            sink.next(3);
            sink.next(4);
            sink.next(5);
        }).scan(10, (a, b) -> a + b))
                    .expectNext(10, 13, 17, 22)
                    .thenCancel()
                    .verify(Duration.ofMillis(250));
```

If scan is being used for a "live" reduction, the accumulation always lags by one. This confused me for awhile since it seems to contradict the flow diagram at http://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#scan-A-java.util.function.BiFunction- (at least in how the timing works)

**Comment by smaldini** [comment]
I might need to qualify this more as it could actually be an issue rather than an enhancement.

**Comment by osi** [comment]
as a spike, scanWith can be rebuilt using `just` and `map`,

```
	public final <A> Flux<A> scanWith(Supplier<A> initial, BiFunction<A, ? super T, A>
			accumulator) {
		Objects.requireNonNull(accumulator, "accumulator");
		Flux<T> source = this;
		return defer(() -> {
			A initialState = initial.get();
			Function<T, A> mapper = new Function<T, A>() {
                A state = initialState;

				@Override
				public A apply(T v) {
					A newState = accumulator.apply(state, v);
					state = newState;
					return newState;
				}
			};
			return Flux.concat(Flux.just(initialState), source.map(mapper));
		});
	}
```

All the tests pass, except the errorOnSubscribe scenario from the superclass complains about getting one value (haven't fully figured out how those generic tests work yet)
