### ISSUE TITLE
Expose processor builders as `builder` static method

### ISSUE THREAD

**Issue by osi** [reactor/reactor-core#628]
the builders are nice. would also be cool to have `XXXProcessor.builder` as an alias to `XXXProcessor.Builder.create`

**Comment by simonbasle** [comment]
I have removed the static `create` methods in Builders. This is only marginally better, but still better :) Note that you still have to prefix the call with the processor class and generic type:
```
WorkQueueProcessor<String> processor = WorkQueueProcessor.Builder.<String>create().build();
//vs
WorkQueueProcessor<String> processor = WorkQueueProcessor.<String>builder().build()
```
