### ISSUE TITLE
Flux.create is not agnostic to sink initialization methods order

### ISSUE THREAD

**Issue by Dmitry-Erokhin** [reactor/reactor-core#643]
`FluxCreate.SerializedSink` request for results immediately after calling `sink.onRequest`, thus if all data fed in this initial request with calling `sink.complete` afterwards and `sink.onDispose` is initialised AFTER  `sink.onRequest`, disposal code will not be called.

When Emitter exhausted on first request (let's say have only one item):

Case 1. Important stuff will be done.
```java
Flux.create(s -> { 
                    //Emmit something calling first function, 
                    //if nothing more to emmit – calling second function
                    final Emitter emitter = new Emitter(s::next, s::complete);
                    
                    s.onDispose(() -> {
                        //DO SOME IMPORTANT DISPOSE STUFF
                    });

                    s.onRequest(emitter::emmit);
                }
        );
```        
        
Case 2. Important stuff will NOT be done.
```java
Flux.create(s -> { 
                    //Emmit something calling first function, 
                    //if nothing more to emmit – calling second function
                    final Emitter emitter = new Emitter(s::next, s::complete);

                    s.onRequest(emitter::emmit);
                                        
                    s.onDispose(() -> {
                        //DO SOME IMPORTANT DISPOSE STUFF
                    });
                }
        );
```

Naively thinking about solution – initial request for data can be deferred after sink is created.

**Comment by simonbasle** [comment]
@Dmitry-Erokhin thanks for reporting this. The way @rajinisivaram fixed the issue is that if the `onDispose` is called while the `sink` already completed, the dispose callback will be immediately invoked.
