### ISSUE TITLE
When fused, failing doOnNext don't propagate exceptions to doOnError

### ISSUE THREAD

**Issue by lbovet** [reactor/reactor-core#664]
This test works:

        Flux<Integer> f = Flux.just(1)
                .doOnNext(i -> {
                    throw new IllegalArgumentException();
                })
                .doOnError(e -> {
                    throw new IllegalStateException(e);
                });
        f.subscribe(i -> fail(), e -> assertTrue(e instanceof IllegalStateException));

But this one does not:

        ConnectableFlux<Integer> f = Flux.just(1)
                .doOnNext(i -> {
                    throw new IllegalArgumentException();
                })
                .doOnError(e -> {
                    throw new IllegalStateException(e);
                }).publish();
        f.subscribe(i -> fail(), e -> assertTrue(e instanceof IllegalStateException));
        f.connect();

In fact, the doOnError closure is never visited. 

Maybe related to #272.

Using 3.0.7.RELEASE

**Comment by simonbasle** [comment]
Looks like a bug related to micro-fusion! As a workaround, if it occurs with your real source, put a `.hide()` before the `doOnNext`.

**Comment by simonbasle** [comment]
@akarnokd seems like RxJava `FlowableDoOnEach` is also susceptible to this: https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/flowable/FlowableDoOnEach.java#L285

**Comment by akarnokd** [comment]
Yes, I saw this and already composing a patch for RxJava.

**Comment by simonbasle** [comment]
@akarnokd awesome, pinged you on the fix PR for Reactor to compare ;)

**Comment by akarnokd** [comment]
PR posted. https://github.com/ReactiveX/RxJava/issues/5415
