### ISSUE TITLE
elasped operator variants that accept BiFunction instead of creating Tuple

### ISSUE THREAD

**Issue by osi** [reactor/reactor-core#672]
When using `Mono.elapsed` a common pattern I do is to use the operator, and then immediately follow it up with a `map` operation that updates my metrics with the duration, and then unpacks the tuple.

Now that Tuple is `@Nullable`, `Tuple2.getT1()` is marked as being potentially null by IntelliJ since it is a long being unboxed.

If this is a common enough idiom, how about adding `Mono.elapsed(LongConsumer)` that will emit the elapsed duration to the consumer as a side-effect rather than stamping the individual elements?

**Comment by smaldini** [comment]
Interesting suggestion indeed. but if we align with zip / when philosophy it should rather be a BiFunction.

**Comment by simonbasle** [comment]
@osi we are going to make `Tuple2` ~great again~ non-null... That would make this issue irrelevant wouldn't it?

**Comment by osi** [comment]
yea, that removes the genesis of the idea. happy to discard the issue.

**Comment by simonbasle** [comment]
obsolete thanks to #696
