### ISSUE TITLE
delayUntil dropping the element associated with an erroring trigger

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#673]
I have a big doubt on how the associated operators (both Mono and, as of #631), Flux versions) should behave when the trigger (the delaying publisher) errors. Right now in Mono it doesn't emit the value. delayError variant just lets subsequent triggers (which are fused) play before propagating all errors in a single composite exception.

I'm thinking it would make sense for the values to still be emitted in case of an error in the trigger:

 - Mono.untilOther: the first trigger to error would lead to emitting the value then erroring with the same
 - Mono.untilOtherDelayError: all erroring trigger play out (eg a trigger that errors after a 200ms pause will still delay the element by 200ms), the value is emitted, a possibly composite error is signalled
 - Flux.untilOther: there's no fusion of subsequent calls, so no possibility of composing several triggers' errors => the first element with a trigger that errors leads to that element being emitted then the same error signalled downstream
 - Flux.untilOtherDelayError: each element can have an errorring trigger. it will still be emitted when the trigger fails, and the trigger's error is aggregated with the other trigger errors and signaled at the end of the whole sequence

@smaldini @nebhale thoughts?

**Comment by simonbasle** [comment]
confirmed by this kind of test:

```

	@Test
	public void triggerFailureStillEmitsItem() {
		StepVerifier.create(Mono.just("foo")
		                        .delayUntil(v -> Mono.error(new IllegalStateException("boom"))))
		            .expectNext("foo")
		            .verifyErrorMessage("boom");
	}

	@Test
	public void triggerFailureDelayedStillEmitsItem() {
		StepVerifier.create(Mono.just("foo")
		                        .delayUntilDelayError(v -> Mono.error(new IllegalStateException("boom"))))
		            .expectNext("foo")
		            .verifyErrorMessage("boom");
	}
```

**Comment by nebhale** [comment]
I _think_ I'm against sending the value(s) in the case of an error.  We effectively use `delayUntil` for async side effects.  For example, 

```
.delayUntil(applicationId -> stageApplication(applicationId))
.delayUntil(applicationId -> waitForStagingToFinish(applicationId))
.delayUntil(applicationId -> startApplication(applicationId))
.delayUntil(applicationId -> waitForStartingToFinish(applicationId))
```

Letting the value propagate before the error would cause following operations to be triggered, even though there was a failure in the required operation before them.

**Comment by smaldini** [comment]
Btw this could be written

```
.delayUntilOther(stageApplication(applicationId))
.delayUntilOther(waitForStagingToFinish(applicationId))
.delayUntilOther(startApplication(applicationId))
.delayUntilOther(waitForStartingToFinish(applicationId))
```
But I wonder if Function is really the nominal case vs Publisher and delayUntil could be delayUntilMap vs delayUntilOther which could be delayUntil.

**Comment by nebhale** [comment]
Actually, `applicationId` is a derived value, so we do actually need a function somewhere.

```
...
createApplicationAndGetId(...)
.flatMap(applicationId -> stageApplication(applicationId)
    .delayUntilOther(waitForStagingToFinish(applicationId))
    .delayUntilOther(startApplication(applicationId))
    .delayUntilOther(waitForStartingToFinish(applicationId)))
```

Which isn't really an improvement.

**Comment by smaldini** [comment]
Well noted thanks for the healthy reminder.

**Comment by smaldini** [comment]
I tend to lean toward error short circuit to align with the general principle everywhere else. Retry and future #629 will also help with that separately.
