### ISSUE TITLE
Using simple System.out "logging" rather that JdkLogger as a fallback

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#680]
When SLF4J cannot be activate, consider falling back to a `Logger` adapter that just uses `System.err` (for ERROR and WARN) and`System.out`, rather than JRE logging. Alternatively, provide a way of choosing between the two fallbacks?

**Comment by simonbasle** [comment]
@smaldini I'll let you decide, then we can change the assignee if implementation needed.

**Comment by smaldini** [comment]
I agree, @rstoyanchev wdyt ?
