### ISSUE TITLE
FlatMap trySubscribeScalarMap does not pass failed signal to onOperatorError

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#684]
**Affects: 3.0.8**
When flatMap fails with an Exception failed signal may or may not be passed to `onOperatorError`  depending on how the child stream is setup.

In the case of `onNext()`, this is done correctly. See: https://github.com/reactor/reactor-core/blob/3.0.x/src/main/java/reactor/core/publisher/FluxFlatMap.java#L365

But, in the case of `trySubscribeScalarMap` it is not. See: https://github.com/reactor/reactor-core/blob/3.0.x/src/main/java/reactor/core/publisher/FluxFlatMap.java#L144

The workaround is to not use flatMap with `just()` immediately before something that might fail and instead do `flatMap(event -> just(event).doOnNext(e ->{}).transform(..))`

**Comment by simonbasle** [comment]
I think you can also workaround the issue by using `hide()` rather than a `doOnNext`, right @dfeist? If so, the intent is probably clearer.

**Comment by dfeist** [comment]
@simonbasle Right, assume so, didn't try though as in the end I didn't actually need flatMap there and removed it.  Still, I'm concerned this might impact elsewhere..

**Comment by simonbasle** [comment]
Is there any criticality to it though? We don't really plan on releasing a 3.0.8 unless there are major bugs, and I don't think this is one. Would you mind targeting `master` in your PR instead of `3.0.x` for now?

**Comment by dfeist** [comment]
Up to you..  assumed you used approach where bugs are fixed un `3.0.x` for if/when there is another release and cherry-picked to 3.1.

**Comment by simonbasle** [comment]
Yeah for now we've applied the inverse strategy, self-contained fix commits on master + backport on 3.0.x ;)

**Comment by simonbasle** [comment]
@dfeist will you have the bandwidth to PR that on top of the most recent master?
