### ISSUE TITLE
MonoProcessor should null 'source' when complete

### ISSUE THREAD

**Issue by osi** [reactor/reactor-core#690]
When using `MonoProcessor` via `Mono#cache`, there can be unexpected object retention of the upstream `source`

`MonoProcessor` nulls its `subscription` field upon reaching a terminal state. It should do the same for `source`.

**Comment by smaldini** [comment]
Agree

**Comment by simonbasle** [comment]
Conceptually this is fairly easy to implement indeed, but to test... Do you have a reproducible test case on hand by any chance @osi?

**Comment by osi** [comment]
I'm not sure how to best test unexpected retention. I discovered then when looking at a heap snapshot from my app that uses `Mono.fromFuture` and the value in the future had been retained.

One could maybe construct a test by using a `WeakReference` and `System.gc()`, but my initial thought is that it might not be reliable.

**Comment by simonbasle** [comment]
This is part of the RS contract to null out a source, but I don't think this will help with the retention scenario @osi: if you keep a reference to the processor, it would keep a reference to the `value` internally. If you null it out, the source would also be garbage collected. Unless I'm missing something?

**Comment by osi** [comment]
My pseudo-code is:

`Mono.fromFuture(future).map(processFuture).cache()`

I *do* want (and expect) the result of `processFuture` to be cached (which is `value` inside the `MonoProcessor`).

But since `MonoProcessor` retains `source`, that keeps a reference to the `MonoCompletionStage` which has a reference to `future`.

**Comment by simonbasle** [comment]
Thanks, it allowed me to build a working test case for complete/error/cancel 👍
