### ISSUE TITLE
Add TYPE_USE nullability annotation on generic parameters in the API

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#714]
~Explicitly marking fields as `@Nullable` is important for null-safety analysis in Eclipse IDE. It can also improve the analysis performed by IntelliJ, although not required. The corollary to that change is of course to make the `@NonNullApi` annotation act on fields in addition to method return values and parameters.~

~(that analysis and decision was originally made in Spring Framework, see [commit](https://github.com/spring-projects/spring-framework/commit/cc74a2891a4d2a4c7bcec059f20c35aa80bcf668) and [issue SPR-15720](https://jira.spring.io/browse/SPR-15720))~

Add `NonNull`/`Nullable` annotations that apply to the use of generic types in the API, allowing to tell whether or not things like a generified `Collection<T>` can contain `nulls` (as opposed to the collection parameter itself being `null`).

**Comment by simonbasle** [comment]
Both Reactor and Spring will refocus this effort to only look at the API level, so field-level annotations won't be put in place after all.

On the other hand, a more impactful change would be to not only annotate API parameters and return values but also *generic types*. Unfortunately, the associated `TYPE_USE` scope is too broad for that to be put on the `@NonNullAPi` package annotation.

So it looks like we'll need to introduce `@NonNull` and `@Nullable` annotations for the purpose of annotating generic types in the API.

The result is that we would then be able to tell tools (including the Kotlin compiler) that a vararg or a generified parameter like a `Collection` is not supposed to contain any `null` (or, on the contrary, if it is acceptable for it to contain `null` values), as opposed to the vararg array or collection itself being `null`.

**Comment by sdeleuze** [comment]
Indeed, draft commit available [here](https://github.com/sdeleuze/reactor-core/commit/nullable-v2), I should be able to merge it next week, after a review and discussion about [my feedbacks](https://youtrack.jetbrains.com/issue/KT-19592#comment=27-2421462) with Jetbrains.

**Comment by smaldini** [comment]
fixed in #864
