### ISSUE TITLE
Map operator does not bubble up UpstreamException

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#72]
Seems that FluxMap is missing `Exceptions.throwIfFatal(e)` in it's inner subscriber catch block which means that UpstreamExceptions aren't bubbled upstream and instead are propagated downstream.

Wondering if there is a way to refactor these inner subscribers so that it's not necessary for each and error operator to have to  do these checks as seems to be the case now?

**Comment by akarnokd** [comment]
Right, `map` was added very early on before the error handling has been fleshed out. Fixed via https://github.com/reactor/reactive-streams-commons/commit/2cb8bf5df9ceb43756d909d5c11ceeabfa5579f1 . @smaldini will sync up Reactor-Core.

**Comment by smaldini** [comment]
Synchronized, thanks both!
