### ISSUE TITLE
sample variant that always emits the final event

### ISSUE THREAD

**Issue by osi** [reactor/reactor-core#724]
the `sample` operator only emits events when the companion signals.

the use-case is a finite stream that is using `scan` to perform a calculation where observation of the interim results is desired (for a UI).

this can currently be approximated by:

```
Flux<Integer> values = source.cache(1);

values.sample(Duration.ofMillis(250)).concatWith(values.last());
```

**Comment by smaldini** [comment]
that should always be the case imo wdyt @akarnokd

**Comment by osi** [comment]
i was pondering it as default behavior too.

when a complete signal is emitted from the source, wait until the next sampler interval to emit any remaining `onNext` event and the `onComplete`

**Comment by smaldini** [comment]
yes its much easier to skipLast() if you don't want the last anyway than this.

**Comment by simonbasle** [comment]
I think it makes sense as default behavior, but do you really need the delay part? If the source completes earlier than the sampling window, wouldn't it still make sense for the `sample` operator to *immediately* emit the last seen value downstream and complete?

**Comment by osi** [comment]
the delay isn't needed. i mentioned it thinking it might make implementation easier if all downstream events were tied to the ticking of the sampler interval.

**Comment by simonbasle** [comment]
Ok, I've put together a PR: #756
