### ISSUE TITLE
Consider addition of Flux.onErrorDrop() operator

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#74]
Sometimes when an error occurs you simply want to drop the message being processed, rather than terminate or fallback to a fixed value and continue.  Especially if you are using another mechanism to nack the message. See [https://github.com/reactor/reactor-core/issues/73]

Doing this via simple out-of the box operators is not possible today from what i can see, yet if an onErrorDrop() operator existed this would be trivial.   

In the following example the Flux.error() would be terminal if it wasn't for the 'onErrorDrop', with 'onErrorDrop' a single failing item in sequence will not terminate stream.
```
Flux.range(0,10).map(i -> {
    try {
         return process(i);
    } catch (Throwable ex) {
        return Flux.error(ex);
    }
}).onErrorDrop().consume(System.out::println);
```

**Comment by akarnokd** [comment]
You can do this just fine:

```java
Flux.range(0, 10)
.concatMap(i -> {
    try {
        return Flux.just(process(i));
    } catch (Throwable ex) {
        Log.error(ex);
        return Flux.empty();
    }
}).consume(System.out::println);
```
or
```java
Flux.range(0, 10)
.concatMapIterable(i -> {
    try {
        return Collections.singletonList(process(i));
    } catch (Throwable ex) {
        Log.error(ex);
        return Collections.emptyList();
    }
}).consume(System.out::println);
```

**Comment by dfeist** [comment]
User issue then, sorry. I was trying to do something similar using map() and couldn't. Thanks.
