### ISSUE TITLE
Support creation of empty mono from lambda that returns a nullable value

### ISSUE THREAD

**Issue by sbuettner** [reactor/reactor-core#743]
Imagine you are in kotlin land and want to return a `Mono<X>` from an existing function `fun x(): X?`. Currently its only possible to wrap each call to `x()` using the Mono.create like: 
```
Mono.create { s -> s.success(x()) }
```

It would be nice to have some kind of generic shorthand method like this to allow a simple creation of a lazy mono like: 
```
fun <T> fromCallableOrEmpty(body:() -> T?): Mono<T> = Mono.create<T> { s -> s.success(body()) }
```

where you would simply write: `fromCallableOrEmpty { x() }`.

**Comment by smaldini** [comment]
@sdeleuze @rstoyanchev WDYT

**Comment by sdeleuze** [comment]
Didn't we discuss at some point supporting that (nullable lamnda arguments with `OrEmpty` behavior) out of the box without having to add another variant to the API? I don't remember the final discussion / decision so a refresh on that topic would be welcome as it is IMO related to this request.

**Comment by sdeleuze** [comment]
Precision: my question/proposal is about the possibility to support "`null` value to empty `Publisher`"  behavior in `Mono` and `Flux` public "entry points", not in Reactor internals which should remain based on a non-null principle.

**Comment by simonbasle** [comment]
Background on why this has been discussed and deferred before: the `Callable` must be lazily evaluated, especially it must behave well with backpressure and `subscribeOn` (ie the call must run on the subscribeOn's thread). Having `null` value + backpressure was proving difficult in this case.

**Comment by sbuettner** [comment]
@simonbasle I had a look at the current implementation and I think it would be great if we could tweak it a little bit. Lets assume that we have a kotlin lambda that returns a nullable value of type: `T`. Using the current implementation I would get a `Mono<T?>`. 

This may not be what we want as a `Mono` should never contain a `null` value. My expectation would be a `Mono<T>`. Therefore I would vote to change the return type for example of 
```fun <T> (() -> T).toMono(): Mono<T> = Mono.fromSupplier(this)``` 
to
```fun <T> (() -> T?).toMono(): Mono<T> = Mono.fromSupplier(this)```

This way we would get a `Mono<T>` even though the lambda returns a `T?`.

**Comment by sbuettner** [comment]
@simonbasle should I open a new issue to discuss this proposal?

**Comment by simonbasle** [comment]
@sbuettner no I don't think this warrants another issue. would love to get a PR to better evaluate this follow-up, if that is not too much trouble (reference this issue in the PR description)

**Comment by sbuettner** [comment]
@simonbasle Ok, I will try to come up with something 😄

**Comment by sbuettner** [comment]
@simonbasle #1062
