### ISSUE TITLE
isTerminated and isStarted always return false

### ISSUE THREAD

**Issue by ufoscout** [reactor/reactor-core#75]
Hi all,

calling isTerminated() or isStarted() on a Mono always return false as shown in this test:
```
    @Test
    public void testIsTerminated() throws InterruptedException {
        Mono<String> result = Mono.just("helloWorld");

        result.consume(
                text -> System.out.println("next"),
                e -> System.out.println("error"),
                () -> System.out.println("complete"));

        assertEquals("helloWorld", result.get());

        Thread.sleep(100);

        assertTrue(result.isTerminated()); // <- This assertion fails
        assertTrue(result.isStarted());   // <- This assertion also fails
    }
```
"next" and "complete" are printed in the standard output but the assertions fail.

**Comment by smaldini** [comment]
It's a perception issue these are just saying this component is not terminated and indeed you can resubscribe as many times as you want to Mono.just. try `Mono.subscribe() : Mono` and assign it as a result.

**Comment by ufoscout** [comment]
Uhm... ok. That seems a little bit strange to me.
Does it mean that a Mono will behave differently depending on how it has been created?
Then why is the "complete" callback called? The isTerminated description says "Has this upstream finished or "completed" / "failed" ?".
Finally, the description of isStarted() is "Has this upstream started or "onSubscribed"", here there is a subscriber so it should return true. Am I wrong?

**Comment by smaldini** [comment]
Yes I think I will demote the Completable contract from Mono, looks like its causing confusion. Mono is a Publisher, isCompleted usually relate to state, which in the flow architecture we have means Subscriber. 

MonoProcessor (as returned by cache() or subscribe() ) implements a correct is Started.

But yeah you can subscribe as many time as you want to Mono.just() so it doesn't really have an end in itself, what has an end is what you have subscribed to it.
