### ISSUE TITLE
Missing API calls in documentation

### ISSUE THREAD

**Issue by dsyer** [reactor/reactor-core#77]
From the docs:

>  If you passed the integers 1, 2 and 3 into the Processor, you would see output in the console similar to this

But it doesn't show how to "pass" integers (or anything) into a processor. Only the output.

**Comment by dsyer** [comment]
In the same section I believe `flux<Integer> s = flux.from(p);` should be `Flux<Integer> s = Flux.from(p);`?

**Comment by smaldini** [comment]
Which doc are you referring to, we don't have any guide yet

**Comment by dsyer** [comment]
https://github.com/reactor/reactor-core/blob/master/src%2Fdocs%2Fasciidoc%2Fcore-processor.adoc#topicprocessor

**Comment by smaldini** [comment]
yeah that's the old reference but we want a new one more comprehensive. Time is not our friend tho but while we are polishing a reactor-core M4 and reactor-netty M1 (and spring 5 M1), we will take care of that. I think I myself will be free to work on it after Spring.IO unfortunately but keep ideas rolling out for guide and blog post. I will leave that issue open for now.

**Comment by rstoyanchev** [comment]
does it even make sense to have the old reference here?

**Comment by smaldini** [comment]
Nope, removed from this repo.

**Comment by simonbasle** [comment]
since the reference is being completely rewritten, superseded by #404
