### ISSUE TITLE
Provide an Exceptions utility to unwrap composite exception to `List<Throwable>`

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#770]
Currently, one can create a composite `Exception` by calling `Exceptions.multiple`. However, detecting that a `Throwable` is such a composite is tricky: the instance created is just a bare `RuntimeException` with a particular message and suppressed exceptions.

It would be interesting to at least offer a way of unwrapping any exception into a `List<Throwable>`, with the main purpose of detecting the `Exception.multiple`-produced instances and returning their suppressed exceptions as a list. Any other `Throwable` would be returned as a singleton List, as suggested by @dfeist:

```java
 public static List<Throwable> unwrapCompositeException(Throwable throwable) {
    if(throwable.getClass().equals(Throwable.class) && throwable.getMessage().equals("Multiple exceptions")){
      return asList(throwable.getSuppressed());
    }
    else {
      return singletonList(unwrap(throwable));
    }
  }
```

Another possible improvement would be to at least have a package-private type for composite exceptions that would allow us to `instanceOf`-detect them (+ expose a `isMultiple` check method for consistency with other exception utils).

**Comment by dfeist** [comment]
>Currently, one can create a composite Exception by calling Exceptions.multiple
The main use case isn't creating that manually, rather it's getting one of these as the result of concatMapDelay/flatMapDelay, and the issues associated with identifying it and unwrapping it, given flatMapDelay/concatMapDelay may or may not produce these exception type in a deterministic way based on how many errors there are.

I'm not sure it's a good idea for conatMapDelayError/flatMapDelayError to always signal a composite error when using delayError, even though it would be more deterministic. Using a utility method to unwrap and deal with the maybe, may not be situation may be best.
