### ISSUE TITLE
Flux.merge seldomly does not emit events properly

### ISSUE THREAD

**Issue by lebannen** [reactor/reactor-core#777]
We were investigating how Flux.merge requests events from sources, but I've figured out the following behaviour. We have test:

```
    @Test(timeout = 1000)
    public void name() throws Exception {
        Flux<Integer> f1 = Flux.<Integer>create(sink -> {
            int  i =0 ;
            while(!sink.isCancelled()) {
                sink.next(i++);
            }
        })
                .subscribeOn(SCHEDULER1);

        Flux<Integer> f2 = Flux.<Integer>create(sink -> {
            int  i =0 ;
            while(!sink.isCancelled()) {
                sink.next(i--);
            }
        })
                .subscribeOn(SCHEDULER2);

        Flux.merge(f1,f2)
                .take(1000)
                .blockLast();
    }

```

### Expected behavior
Test should always pass.

### Actual behavior
seldomly (once for 400-500 runs on the average) fails with time out. Many of this fails are following: flux emits 64 events and then just stucks. It's reproducing rarely, so currently I cannot investigate it better.

### Steps to reproduce
Run test until it fails.

### Reactor Core version
3.0.7

### JVM version (e.g. `java -version`)
1.8.0_131

### OS version (e.g. `uname -a`)
Linux 4.4.0-81-generic

**Comment by akarnokd** [comment]
This is caused by a same-pool deadlock due to the interplay between `create` and `subscribeOn`. Since `create` occupies the thread all the time, the replenishing requests from `merge` can't get executed as those tasks are scheduled behind the currently running `create` task.

It requires changes to `FluxSubscribeOn` similar to [this](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/flowable/FlowableSubscribeOn.java#L132). Also for convenience, the application of `subscribeOn` could check for an immediately upstream `FluxCreate` [and/or](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Flowable.java#L13091) add a new `subscribeOn` overload to disable requesting on the same thread.

**Comment by smaldini** [comment]
I was looking forward to reproduce this in the last pass i did on the publishOn/subscribeOn use cases so thankfully we have it now 👍  . @akarnokd do you think Mono.subscribeOn would require it even tho its one value at most ?

**Comment by lebannen** [comment]
@smaldini, do you need any assistance from my side or you will solve this issue yourself?

**Comment by akarnokd** [comment]
Mono.create produces at most one item and then exits. If you have a deferred scalar subscription backing it, there should be no problems as the scheduled request can reach it now that the custom logic quit.

**Comment by smaldini** [comment]
We would welcome contribution but I'm ok to fix it too @lebannen - I just love to get people involved somehow 👍  Let me know if you don't have time for it I'll do it asap.

**Comment by lebannen** [comment]
Well, I've found stable test to reproduce:

```
        @Test
	public void createWithSubscribeOnAndPublishOn() throws Exception {
		AssertSubscriber<Integer> ts = AssertSubscriber.create();

		Flux.<Integer>create(sink -> {
			int i = 0;
			while (!sink.isCancelled()){
				sink.next(++i);
			}
		})
                                .map(Function.identity())
				.subscribeOn(Schedulers.parallel())
				.publishOn(Schedulers.parallel())
				.subscribe(ts);

		ts.awaitAndAssertNextValueCount(1000)
		  .assertNoError()
		  .assertNotComplete();
	}
```

But the problem is how to find if we have `Flux.create` in chain. I've made changes to fix this test, but if I add `Flux.flatMap` to chain, it still does not work:

```
	@Test
	public void flatMapWithCreateSubscribeOnAndPublishOn() throws Exception {
		AssertSubscriber<Integer> ts = AssertSubscriber.create();

		Flux.just(1)
		    .flatMap(val ->
				    Flux.<Integer>create(sink -> {
					    int i = 0;
					    while (!sink.isCancelled()){
						    sink.next(++i);
					    }
				    }))
		    .subscribeOn(Schedulers.parallel())
		    .publishOn(Schedulers.parallel())
		    .subscribe(ts);

		ts.awaitAndAssertNextValueCount(1000)
		  .assertNoError()
		  .assertNotComplete();
	}
```

I am not sure if it's possible at all to handle all corner cases, unless subscribeOn will use one worker for itself and another for upstream.

**Comment by smaldini** [comment]
Yes the fix @akarnokd mentioned does suffer from this limitation and that means you would have to use an explicit subscribeOn alias for this (subscribeOn(scheduler, boolean). 
It might be pretty limited if your API is encapsulated and don't know in advance if you need it (or safely use subscribeOn(s, true) everytime).

BTW did you try 
```Flux.<Integer>create(sink -> {
                 sink.onRequest(n -> {
					    int i = 0;
					    while (!sink.isCancelled()){
						    sink.next(++i);
					    }
                 });
				    }))```

**Comment by lebannen** [comment]
I've commited my [changes](https://github.com/lebannen/reactor-core/commit/a5aaad0c6dde756e7642fbcbad380e26598b2215)

**Comment by lebannen** [comment]
@smaldini code with `onRequest` does not work for my fix, but it's very strange, because n elements were required and you emit infinite sequence.

**Comment by lebannen** [comment]
There is no problem if it's MAX_VALUE. The race occurs, when you get request(n) and cannot get worker to request more

**Comment by lebannen** [comment]
BTW, during my investigation I've found interesting behaviour of `merge` with `subscribeOn`.

Test:

```
        SCHEDULER1 = Schedulers.newParallel("scheduler1");
        SCHEDULER2 = Schedulers.newParallel("scheduler2");

        Flux<Integer> f1 = Flux.<Integer>create(sink -> {
            int  i =0 ;
            while(!sink.isCancelled()) {
                sink.next(i++);
                LockSupport.parkNanos(10);
            }
        })
                .log()
                .subscribeOn(SCHEDULER1);

        Flux<Integer> f2 = Flux.<Integer>create(sink -> {
            int  i =10000 ;
            while(!sink.isCancelled()) {
                sink.next(i++);
                LockSupport.parkNanos(10);
            }
        })
                .log()
                .subscribeOn(SCHEDULER2);

        Flux.merge(f1,f2)
                .log()
                .take(1000)
                .blockLast();
```

[Full logs](https://pastebin.com/nzCtetSe)

The interesting part: all events in `f1` & `f2` are processed in correct schedulers. But the merge results are processed strangely. It starts correctly:
```
19:36:22.498 [scheduler1-1] INFO reactor.Flux.Create.1 - onNext(1)
19:36:22.498 [scheduler1-1] INFO reactor.Flux.Merge.3 - onNext(1)
19:36:22.498 [scheduler2-2] INFO reactor.Flux.Create.2 - onNext(10001)
19:36:22.498 [scheduler2-2] INFO reactor.Flux.Merge.3 - onNext(10001)
```
Then it get's mixed:
```
19:36:22.511 [scheduler2-2] INFO reactor.Flux.Create.2 - onNext(10019)
19:36:22.511 [scheduler1-1] INFO reactor.Flux.Create.1 - onNext(40)
19:36:22.511 [scheduler1-1] INFO reactor.Flux.Create.1 - onNext(41)
19:36:22.511 [scheduler2-2] INFO reactor.Flux.Merge.3 - onNext(10019)
19:36:22.511 [scheduler2-2] INFO reactor.Flux.Merge.3 - onNext(40)
19:36:22.511 [scheduler2-2] INFO reactor.Flux.Merge.3 - onNext(41)
```
After requested events from `f2` are processed it does not request new events, but only requests events from `f1` and process them in its scheduler.

**Comment by lebannen** [comment]
Any updates on how properly solve this problem?

**Comment by smaldini** [comment]
It seems this wouldn't require any change for the original issue and could lay the ground to a potential recommendation in doc/javadoc. I'm uneasy with adding the scan cost even smart directly to subscribeOn. I can however add an alias to force synchronous request which would allow advanced users solve their issue without onRequest.
```java
Flux<Integer> f = Flux.<Integer>create(sink -> {
			int[] j = new int[1];
			sink.onRequest(r -> {
				int i = 0;
				int k;
				while (i < r && !sink.isCancelled()){
					k = ++j[0];
					sink.next(k);
					i++;
				}

			});
		})
```

**Comment by smaldini** [comment]
@lebannen ping me if that's enough a compromise to document the use as before  + exposing the ````Flux.subscribeOn(scheduler, requestOn=true)``` alias too.

**Comment by lebannen** [comment]
@smaldini, well, we just got rid of almost all `Flux.create` that we had, and I wrote merge that is more suitable for our purporses, so I don't have problems with this behaviour now.

IMHO, it's better to have more robust and less effective tool, than faster and more fragile one. The problem with `Flux.subscribeOn` is that it's used quite often, but you must know some details about it to use it properly (or to avoid `Flux.create`, which we thought was the main way to create flux). 

For our purposes reactor performance is not critical, because our code takes much more time, than inner reactor logic. But, I suppose, you have other vision, so I can only accept it :) In that case, I suppose that documentation + extra method is fine. But I don't think, that it's a good way to add a new parameter to `Flux.subscribeOn` as it was done in rx-java.

**Comment by simonbasle** [comment]
@lebannen unfortunately for 3.1.0 I think we'll have no other choice but adding that extra parameter. We might come up with something later on, I initially thought about the `Context` stuff we're adding but that is not suitable for assembly time decisions like that.
