### ISSUE TITLE
Named transformative hooks to allow replace/remove of sub-hooks with additive behavior

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#784]
Hooks.onEachOperator("sleuth", someHook) would override a previously registered "sleuth" hook instead of adding up like current onEachOperator.

Needed for hooks that are transformative (`Function` `onEachOperator`/`onLastOperator` and `BiFunction` `onOperatorError`).

**Comment by simonbasle** [comment]
do we want to force the user to provide a key? if not, should the "legacy" version generate a random key and return it?
should we also add a `onXxxReset(String key)` to remove the key from the registry of hooks?

**Comment by simonbasle** [comment]
should be an immutable `List`, with copy-on-write semantics when adding / removing a hook
