### ISSUE TITLE
Add "edit page" button to documentation pages

### ISSUE THREAD

**Issue by helmbold** [reactor/reactor-core#801]
I've found several little errors in the documentation (like an example with `delay` instead of `delayElements` or `testcompile` instead of `testCompile`), but I didn't find an easy way to fix these errors. To make it easier to contribute to the documentation, it would be helpful to add an "edit page" button like in the [Kotlin documentation](http://kotlinlang.org/docs/reference/basic-syntax.html).

**Comment by simonbasle** [comment]
This won't be as straightforward, as the documentation is single page but the source is split between several asciidoc files. Would a link [pointing to the doc directory](https://github.com/reactor/reactor-core/tree/master/src/docs/asciidoc) work? You'd have to find the correct file and click on the 🖊 edit icon.

**Comment by helmbold** [comment]
Yes, this would be an improvement. I had actually no idea where to look for the documentation. Maybe there could be a little link near each section heading pointing to the related source file.

**Comment by rotilho** [comment]
You can copy the sentence and search in the repository for it to find the real file. Not optimal but it works.

**Comment by simonbasle** [comment]
I found a way to add a direct edit link at the end of most sections, not bullet-proof (especially for sections that themselves do include files) but a step forward nonetheless. Additionally this would only make it through the HTML5 rendering:

```asciidoc
include::aboutDoc.adoc[leveloffset=1]
ifeval::["{backend}" == "html5"]
https://github.com/reactor/reactor-core/edit/master/src/docs/asciidoc/aboutDoc.adoc[Suggest Edit^, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<about-doc>>"
endif::[]
```

Reopening for second PR.
