### ISSUE TITLE
Flux.last() does not propagate errors

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#811]
### Expected behavior

I expect errors to be propagated to the `Mono` it returns.

### Actual behavior

Instead an exception occurs: `java.util.NoSuchElementException: Flux#last() didn't observe any onNext signal`

### Reactor Core version

3.0.7

**Comment by smaldini** [comment]
This doesn't seem to be reproduced at least in 3.1
```StepVerifier.create(Flux.error(new Exception("test"))
		                        .last())
		            .verifyErrorMessage("test");```
