### ISSUE TITLE
Context.empty() special casing is confusing

### ISSUE THREAD

**Issue by yschimke** [reactor/reactor-core#816]
Need the switchEmpty is Context happens to be Context.empty.  I would argue that an empty context is still a context, and filtering it out should be the case that requires extra code.

```
Mono.currentContext().switchIfEmpty(Mono.just(Context.empty())).flux().map(c -> "a").blockLast()
```

**Comment by smaldini** [comment]
Fair enough, Spring Security has the same issue in fact @yschimke
