### ISSUE TITLE
DirectProcessor using ParallelFlux crashes with error "Queue is full?!"

### ISSUE THREAD

**Issue by BerlinAdam87** [reactor/reactor-core#824]
### Expected behavior
DirectProcessor using ParallelFlux should help us support high throughput and reliability.
(We cannot require restart on fail).

### Actual behavior
I'm getting the following exception after a while and i'm not sure what to do:

reactor.core.Exceptions$OverflowException: Queue is full?!
        at reactor.core.Exceptions.failWithOverflow(Exceptions.java:152) ~[reactor-core-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at reactor.core.publisher.ParallelSource$ParallelSourceMain.onNext(ParallelSource.java:231) ~[reactor-core-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:96) ~[reactor-core-3.0.7.RELEASE.jar:3.0.7.RELEASE]
        at reactor.core.publisher.DirectProcessor$DirectInner.onNext(DirectProcessor.java:304) ~[reactor-core-3.0.7.RELEASE.jar:3.0

do i need to 'release' the queue at some point? what might be the cause for it to be full?

### Steps to reproduce
Just tried to create several events (onNext) and i have 16 subscribers with filter.
For example:
```
public void subscribe(eventRoute, Request flow) {
ParallelFlux<Request> parallelFlux = directProcessor.filter(flow -> flow.getPayload().getEventRoute().equals(eventRoute))
					.parallel()
					.log()
					.runOn(Schedulers.fromExecutor(excuterService));
parallelFlux.subcribe(() -> {do something with try and catch}
}
```
//In events call
directProcessor.onNext(req);

This is super important for us, this happened in production environment right now..
### Reactor Core version
3.0.7.RELEASE

### JVM version (e.g. `java -version`)
1.8.0_121

### OS version (e.g. `uname -a`)
MINGW64_NT-10.0 ADAMB-DELL 2.6.1(0.306/5/3) 2017-01-20 15:23 x86_64 Msys

**Comment by osi** [comment]
by default the queue for parallel dispatch is only 256 elements. a `DirectProcessor` also offers no back-pressure.

if you want to dispatch tasks to separate threads for processing, you might want to look at the `WorkQueueProcessor` instead.

**Comment by simonbasle** [comment]
what @osi said 😄

**Comment by akarnokd** [comment]
I think it should have failed still inside `DirectProcessor`: https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/DirectProcessor.java#L311 . Unless this is line is a recent addition, the error indicates the OP alled `DirectProcessor.onNext` from multiple threads at the same time which could result in bypassing the request accounting inside the processor itself.

**Comment by osi** [comment]
@akarnokd yes, i think you're correct. i was just looking at `ParallelSourceMain` when making my analysis

**Comment by simonbasle** [comment]
Yes, that message comes from the `ParallelSource` and indeed seems to indicate the request accounting in `DirectProcessor` was bypassed (otherwise the error would have been "Can't deliver value due to lack of requests"). If you call the processor from multiple threads @BerlinAdam87, use the `processor.sink()` instead.

> Create a FluxSink that safely gates multi-threaded producer Subscriber.onNext(Object).
> The returned FluxSink will not apply any FluxSink.OverflowStrategy and overflowing FluxSink.next(Object) will behave in two possible ways depending on the Processor:
> - an unbounded processor will handle the overflow itself by dropping or buffering
> - a bounded processor will block/spin

I would still recommend moving away from `DirectProcessor` for this use case.

**Comment by BerlinAdam87** [comment]
Thanks for your answers, i have a couple of follow-up questions:

How do i choose the correct processor? I've tried to run some unit tests and this use case with your framework gave the same throughput as i had with the EventBus on your previous version (I had to make the change because of the upgrade).

1. Can I get an example for using sink for this purpose?
2. Maybe I can get the list of High level details for each processor?

Thanks

**Comment by aviadhadida** [comment]
Hi guys. I am colleague of @BerlinAdam87  and we are struggling to replace with WorkQueueProcessor instead of DirectProcessor because we are using multi thread producers.

The problem we have ran a few tests with multithread producers and it seems that some of the message are sent to workQueueProcessor are dropped in the way and our producer doen not get them. Any chance we can get an example? Or reference to document that will help us with the processors?
This is kind of urgent and this stops us from going to production with our current version

Thanks a lot

**Comment by simonbasle** [comment]
@aviadhadida @BerlinAdam87 in your events, rather than keeping a reference to the `processor` (a WorkQueueProcessor rather than DirectProcessor), keep a reference to the `processor.sink()` instead. Use the `Sink` in the event call: `sink.next(req)` rather than `processor.onNext(req)`. This should serialize calls from multiple producer threads.

**Comment by aviadhadida** [comment]
Thanks a lot :). It seems to work fine.. We will continue with our testing

**Comment by simonbasle** [comment]
@aviadhadida @BerlinAdam87 actually as an alternative you could experiment with `WorkQueueProcessor` in *shared* mode as well as `TopicProcessor` (also in shared mode). Look at these processors's `builder()` method, their builder have a `share(boolean)` option to set to true. Using that, you could go back to using the `processor.onNext` directly in your event calls, see if it gives you better performance that the `sink`...

I have started work on the processors section of the reference guide by the way, track progress in #853  ;)

**Comment by aviadhadida** [comment]
Will do.. We will use Topic it seems to work fine, can you explain what share means? and what is autoCancel? 
We will be waiting for documentation but in the meantime maybe it can help us understand if we are using this framework as we suppose to

**Comment by simonbasle** [comment]
- `share` is a configuration option for `WorkQueueProcessor` and `TopicProcessor` that should make them usable from concurrent threads even when using `onNext` directly on the processors.
 - `autoCancel` is another configuration option which is useful when you use the processor in connecting a source and multiple subscribers (it cancels the source when all the subscribers are cancelled). Not applicable here as you are pushing data through the processor manually, not by subscribing it to a source.

**Comment by aviadhadida** [comment]
OK, Thanks a lot

**Comment by aviadhadida** [comment]
I did use exactly what you said and tested on standalone application to verify i am getting the required behavior.
When i have implemented under our application we have noticed with weird behavior and we are not very sure if this is an issue or we are doing something unexpected.

When we did the following:
```
   private static final ExecutorService executorService =  Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors());

    private TopicProcessor<SomeObject> processor;

    @PostConstruct
    public void init() {
        processor = TopicProcessor.share(executorService);
    } 
```

All the onNext calls didn't invoked the subscribers at all.. And once i have change it to:
```
    private TopicProcessor<SomeObject> processor;

    @PostConstruct
    public void init() {
        processor = TopicProcessor.share(Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors()));
    } 
```

Everything worked..
We want to limit the use of thread in the system and differentiate between low latency oriented events and less important latency oriented event.

NOTE:We are using several instances of TopicProcessor in the system and the same behavior is on all cases with those 2 scenarios.

Maybe can you shed a light on this weird behaviour

Thanks

**Comment by simonbasle** [comment]
@aviadhadida did you reuse the `ExecutorService` in the first instance? `TopicProcessor` will use the executor service you provide to create **long-lived threads**, one per subscriber (so you should also take care not to subscribe more times than the ExecutorService's capacity)

**Comment by aviadhadida** [comment]
Yes i did reuse it.. We have in general more subscribers so i assumed that in case we have too many subscribers it will be slower and blocked by each other and this is fine by us.. Depends on the use case.

**Comment by aviadhadida** [comment]
@simonbasle Can you approve the comment below is correct?
So basically we have 2 options if the comment is correct.
1. Use DirectProcessor and make the access to his onNext thread safe
2. Do not use processors for events between layers or maybe we can use Flux/ParallellFlux in another way?

**Comment by simonbasle** [comment]
Have you tried with `WorkQueueProcessor`, which was my initial recommendation? This one doesn't create 1 thread per subscriber so it could work better for your use case. The other recommandation was to try with `DirectProcessor` and its `sink()`.

**Comment by aviadhadida** [comment]
The problem with WorkQueueProcessor is that he is send signal only to one subscriber when invoking onNext.(As i understood from the docs i have read). This will not work for us because we have several subscribers for event and we need everyone to handle(Every subscriber doing something else).

**Comment by aviadhadida** [comment]
@simonbasle We have tried to use Sink but the problem is that we this processor is not supporting back-pressure and not able to buffer the requests.. What is the diffrenece between DirectProcessor and EmitterProcessor?
What EmitterProcessor is used for?
