### ISSUE TITLE
Flux.filter swallows onComplete if predicate never evaluated to true

### ISSUE THREAD

**Issue by caillette** [reactor/reactor-core#828]
### Expected behavior

`Flux.filter()` should return a flux that completes when filtered flux completes.

### Actual behavior

`java.util.NoSuchElementException: Flux#last() didn't observe any onNext signal`

### Steps to reproduce

```
    final String last = Flux
        .just( "A", "B", "C" )
        .filter( /*"C"::equals*/ nil -> false )
        .last()
        .block()
    ;
    Assertions.assertThat( last ).isNull() ; 
```

### Reactor Core version

3.0.7.RELEASE

### JVM version (e.g. `java -version`)

1.8.0_131

### OS version (e.g. `uname -a`)

Darwin winXpSp2.local 13.4.0 Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64 x86_64

**Comment by simonbasle** [comment]
This is due to the use of `last()`, which contract states:

```
Emit the last element observed before complete signal as a Mono, or emit NoSuchElementException error if the source was empty. For a passive version use takeLast(int)
```

**Comment by caillette** [comment]
My bad. Thanks for the explaination.
