### ISSUE TITLE
Rename Mono.currentContext

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#831]
Currently the interface clashes in MonoProcessor if we want it to implement CoreSubscriber.
The simplest way to go around that before RC1 on Context API is to change Mono.currentContext to something else. We have the next few days to choose so suggestions box is open.

If nothing else we can go with Mono.subscriberContext() to map the existing instance method subscriberContext(Context) and subscriberContext(Function<Context,Context>). 

cc @rwinch @rstoyanchev @yschimke

**Comment by yschimke** [comment]
+1 to subscriberContext() - the no param (static) getter, vs single param setter is a relatively common pattern. e.g. OkHttpClient.Builder.dispatcher(d) vs OkHttpClient.dispatcher()

**Comment by yschimke** [comment]
n.b. some docs are out of date e.g.

```
* Past one user key/value pair, the context will use a copy-on-write {@link Context}
 * backed by
 * a new {@link java.util.Map} on each {@link #put}.
```

**Comment by simonbasle** [comment]
We'll make sure to fix that doc in the same PR ;)

**Comment by smaldini** [comment]
Sorry fixed the API now for integration purpose but we'd open a separate one for doc in general that is not as critical
