### ISSUE TITLE
Processor is cancelled even when onErrorResume is used

### ISSUE THREAD

**Issue by vbasem** [reactor/reactor-core#832]
### Expected behavior
To be able to feed the processor with more data when, when in previous attempt an exception was thrown but dealt with with onErrorResume

### Actual behavior
The processor always ends up in canceled and disposed status. All other calls to sink.next(data) are silently ignored

### Steps to reproduce
```JAVA
    FluxSink<Map> inputSink;
    
    @PostConstruct
    public void init() {
        UnicastProcessor<Map> pub = UnicastProcessor.create();
        inputSink = pub.sink(FluxSink.OverflowStrategy.BUFFER);
        pub.flatMap(in -> Mono.empty().switchIfEmpty(Mono.error(new RuntimeException("error"))))
                .onErrorResume(error -> Mono.empty())
                .subscribe();
    }

    public void iAmCalledFromOutside(Map data) {
        inputSink.next(data);
    }
```
now calling the ```iAmCalledFromOutside``` method from outside twice will result in the second call being completely ignored.

To be more exact I am trying this within:
```org.springframework.boot:spring-boot-starter-webflux:2.0.0.M3```
### Reactor Core version
reactor-core:3.1.0.M3

### JVM version (e.g. `java -version`)
java version "1.8.0_121"

### OS version (e.g. `uname -a`)
Centos 7  -  3.10.0-514.el7.x86_64

**Comment by akarnokd** [comment]
You applied the `onErrorResume` at the wrong level. This will fail the sequence coming out from the processor:

```java
pub.flatMap(in -> Mono.empty().switchIfEmpty(Mono.error(new RuntimeException("error"))))
```

When flatMap sees this error, it cancels its subscription and then notifies the error downstream, which is then turned into completion by

```java
.onErrorResume(error -> Mono.empty())
```

In addition, `UnicastProcessor` is single use and only one subscriber is allowed to consume it over its lifetime. You may want to use `DirectProcessor` instead.

**Comment by vbasem** [comment]
thanks alot for the response and the insight.

Perhaps then I will seek advice on how to model the logic below which ofcurse doesn't work according to the explanation above:

```JAVA
    class EX1 extends RuntimeException {}; class EX2 extends RuntimeException {}; class EX3 extends RuntimeException {};

    @PostConstruct
    public void init() {
        DirectProcessor<Map> pub = DirectProcessor.create();
        inputSink = pub.sink(FluxSink.OverflowStrategy.BUFFER);
        pub
                .flatMap(in -> Mono.just("some external call").switchIfEmpty(Mono.error(new EX1())))
                .flatMap(in -> Mono.just("some other call").switchIfEmpty(Mono.error(new EX2())))
                .flatMap(in -> Mono.just("some really different call").switchIfEmpty(Mono.error(new EX3())))
                .map(s -> "some logic when steps above are done!")
                .onErrorResume(EX1.class, (e) -> Mono.just("first step failed"))
                .onErrorResume(EX2.class, (e) -> Mono.just("second step failed"))
                .onErrorResume(EX3.class, (e) -> Mono.just("third step failed"))
                .subscribe();
    }
    
```

The beauty of it is that the work flow will have a very flat logic which is very readable and understandable.

Perhaps we can take the conversation to a slack channel?

**Comment by osi** [comment]
@vbasem there is a gitter channel for the project, https://gitter.im/reactor/reactor

**Comment by vbasem** [comment]
Protocol:

my wish was expressed in this issue #629 .

For now I am wrapping the errors  in the flatMaps with onErrorReturn which seem to have the desired effect.

thank you.
