### ISSUE TITLE
Infinite loop in Flux.create(...).sort(...).toStream().collect(toSet())

### ISSUE THREAD

**Issue by micolator** [reactor/reactor-core#841]
### Expected behavior
Have an exception raised

### Actual behavior
Infinite loop during execution

### Steps to reproduce
```
Flux.<String>create(sink -> {
	sink.next("a");
	sink.next("b");
	sink.complete();
}).sort((a, b) -> {
	throw new RuntimeException("test");
}).toStream().collect(toSet());
```

### Reactor Core version
3.0.4.RELEASE

### JVM version (e.g. `java -version`)
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### OS version (e.g. `uname -a`)
Linux my-pc 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### Comment
When I use `Flux.fromIterable(asList("a","b"))` instead of `Flux.create`, it works as expected.
When I use `toIterable()` instead of `toStream().collect(toSet())`, it works as expected.

So I don't understand what's happening

**Comment by simonbasle** [comment]
This looks like a bug in the `FluxFlattenIterable` operator internally used by the `sort`: it should see the error produced by the `Comparator` while polling the sortedList operator.

As a workaround in the `3.0.x` branch, use this instead of `sort()`:
```
Flux<String> source = Flux.<String>create(sink -> {
			sink.next("a");
			sink.next("b");
			sink.complete();
		})
    //this replaces the sort ===>
				.collectSortedList((a, b) -> { throw new IllegalStateException("boom"); })
				.hide()  //avoid the fusion that doesn't propagate the error correctly
				.flatMapIterable(Function.identity()); // <===

**Comment by micolator** [comment]
Thanks for the workaround !
