### ISSUE TITLE
Exceptions.unwrap should never return null

### ISSUE THREAD

**Issue by osi** [reactor/reactor-core#848]
### Expected behavior

`Exceptions.unwrap(Throwable)` to return the unwrapped exception

### Actual behavior

`null` was returned

### Steps to reproduce

I believe that this is coming from a `CancelException` (via `onNextDropped`) which is the only case of a `ReactiveException` that has a null `getCause`.

This causes `Schedulers.handleError` (or in my case `ForkJoinPoolScheduler.handleError`) to log no exception, just the message. 

### Reactor Core version

3.1.0M3

**Comment by smaldini** [comment]
Commit issue reference error fixing in a bit.

**Comment by simonbasle** [comment]
(if you come to this issue from commit 291dccc, have a look at #849 instead)
