### ISSUE TITLE
Flux.map() and null-handling when wrapping existing blocking API's

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#86]
The only way to do this currently is via the use of `flatMap` and `Mono.justOrEmpty()` which isn't as efficient and causes more allocations/stack.

One option is to introduce something in Flux e.g. `Flux.mapOrEmpty()` that behaves the same as `map` but drops message and does `request(1)` when null is returned, but I understand this clutters the primary API where nulls simply are not allowed.  So maybe an alternative is to implement something outside of Flux in something like `LegacyUtils` that can then somehow be pulled into and used in a Flux stream just in the cases where you need to deal with legacy API's that throw exceptions/return null.

This is somewhat related to: https://github.com/reactor/reactor-core/issues/80

**Comment by lcor1979** [comment]
Hello, will mapOrFilter be also available for Mono ?
The base issue is the same, if you want to map on a nullable property, you have to do a filter() and map() or a flatMap(Mono.justOrEmpty())

Thank you

**Comment by simonbasle** [comment]
@lcor1979 `mapOrFilter` has been replaced by `handle` back in 3.0.0.RELEASE, so use `handle` instead.

**Comment by lcor1979** [comment]
Ok perfect, thank you.
