### ISSUE TITLE
Deprecate Mono.justOrEmpty in favor of fromOptional + just

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#860]
The `justOrEmpty(T)` special treatment is not really warranted for `Mono`, and could just be merged into the normal behavior of `Mono.just(T)`.

In order to limit confusion, and since we still need a signature that takes an `Optional<T>` and returns a `Mono<T>` (by opposition to a `Mono<Optional<T>>`), we would rename `Mono<T> justOrEmpty(Optional<T>)` to `Mono<T> fromOptional(Optional<T>)`.

The `Flux` behavior wouldn't change. Although it could be argued that `Flux.just(T)` could accommodate `null`, we determined that it wouldn't be possible for the `Flux(T...)` variant. As a consequence, we prefer to keep Flux internally consistent (same behavior for both variants) rather than (partially) aligning with Mono.

**Comment by simonbasle** [comment]
After discussing it further, there is no great value in changing the API (and the behavior of `just`). The argument above makes sense, but it is not overwhelmingly strong. Not enough so that we want to do that between RC1 and RELEASE.

The counterargument is that the fact `justOrEmpty` is so distinctive makes you pause and think about doing a `Mono.just(null)` twice.

So we'll keep the status quo. Looks like #743 has more value anyway.

**Comment by simonbasle** [comment]
@sdeleuze for your null safety annotation effort, this basically boils down to `Mono.just(@NonNull T)` and `Mono.justOrEmpty(@Nullable T)` right?

**Comment by sdeleuze** [comment]
@simonbasle Yep, indeed

**Comment by jabrena** [comment]
Hi @simonbasle,

Maybe this discussion should be opened again.

The behaviour of `Mono.justOrEmpty` is not coherent in my humble opinion.

Take a look the following examples:

``` java
final String value = null;
then(Mono.just(Optional.ofNullable(value)).block()).isEqualTo(Optional.empty()); //OK
then(Mono.justOrEmpty(value).log().map(Optional::ofNullable).block()).isEqualTo(value); //KO
then(Mono.justOrEmpty(value).log().map(Optional::of).block()).isEqualTo(value); //KO
then(Mono.justOrEmpty(Optional.ofNullable(value)).block()).isEqualTo(value); //KO
then(Mono.empty().block()).isEqualTo(value); //OK
then(Mono.just(Optional.ofNullable(value))).isNotEqualTo(Mono.justOrEmpty(value)); //KO
``` 

If the developer need to integrate with a legacy application maybe, it is safer to use the pattern:

``` java
Mono.just(Optional.ofNullable(value))
```

than the usage of justOrEmpty:

``` java
Mono.justOrEmpty(value).log().map(Optional::ofNullable)
Mono.justOrEmpty(value).log().map(Optional::of)
```

What do you think?

Juan Antonio

**Comment by simonbasle** [comment]
@jabrena what you seem to be missing is the fact that `null` is an illegal value for a `Publisher` (like `Flux` and `Mono`) to pass via an `onNext`. 

`Mono.justOrEmpty(Optional)` is immediately translating the `Optional` to either a valued `Mono` or an empty `Mono`. Since `map` precisely works on `onNext` signals, but empty Monos don't produce such signals, the `map` transformations in your example cannot really produce an empty `Optional`. `blockOptional()` can, though...
