### ISSUE TITLE
Flux's delaySubscription operator not receiving result with Schedulers.parallel()

### ISSUE THREAD

**Issue by artshell** [reactor/reactor-core#867]
reactor-core version: 3.1.0.RC1
java version: jdk8

```java
Flux.just(5)
                .delaySubscription(Duration.ofMillis(500), Schedulers.parallel())
                .subscribe(System.out::println);
```

That thread is daemon inside of ParallelScheduler, Since  ?

**Comment by akarnokd** [comment]
> Since ?

From pretty early on. You have to delay the exit of the main thread to see the results.

**Comment by artshell** [comment]
How to delay exit main thread?

**Comment by artshell** [comment]
Thank you very much, the problem resolved
