### ISSUE TITLE
Proof-read and technical review of new sections of the documentation

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-core#868]
See #853 and #838, these have been merged despite not being fully subject to proof-reading (cc @Buzzardo) and technical review (@smaldini).

Good point about the doc being merged is that rendered version can be reviewed from the site:
 - http://next.projectreactor.io/docs/core/snapshot/reference/#processors
 -  http://next.projectreactor.io/docs/core/snapshot/reference/#_checking_execution_path_with_code_publisherprobe_code
 - http://next.projectreactor.io/docs/core/snapshot/reference/#scheduler-factory
 - http://next.projectreactor.io/docs/core/snapshot/reference/#hooks
 - http://next.projectreactor.io/docs/core/snapshot/reference/#context

**Comment by Buzzardo** [comment]
If you folks have made changes, I can make another run at proofreading. Happy to do it.

**Comment by simonbasle** [comment]
yeah, new sections are linked in the issue above @Buzzardo

**Comment by Buzzardo** [comment]
I should have written "if you're done making changes, at least for a while...." :)

If you have more changes coming soon, I'll hold off. If you're done for a while, I'll make another pass.

Do you have more changes coming in the next few days?

**Comment by simonbasle** [comment]
ah got it! no, no further changes scheduled for now

**Comment by smaldini** [comment]
waiting for an extra review round before fully closing this one early next week @simonbasle

**Comment by Buzzardo** [comment]
I'll do my next pass on Monday, then. :)

**Comment by simonbasle** [comment]
@buzzardo @smaldini the release is supposed to happen on Monday European time, so review before that would be best :D

**Comment by Buzzardo** [comment]
Well, I guess I missed my chance for this release. I'll go ahead and proofread again anyway. Those changes can make it into the next release, and they'll be picked up when people clone or fork the project.

**Comment by simonbasle** [comment]
of course, please do ;)
