### ISSUE TITLE
Extension mechanism to allow exceptions to be wrapped before onError()

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#89]
This is important in use cases where the current `event` when the exception occurred is required as context when handling the exception downstream.

A previous approach for handling this type of use case, `doOnErrorValue(BiConsumer)` was removed as the value was being held onto regardless of if it was used later on not, and this was being done simplicity behind the scenes.

By allowing the user to provide a exception mapping via a `BiFunction<Exception, T, Exception>` they are free to i) wrap all exceptions as they see fit ii) add current event as context to exception field or via a additional cause and whatever is done it is explicit and only occurs if configured by the user, so would not have the same issues as the previous approach. 

The only other approaches to do this currently are:
1) Use custom operators instead of out-of-the-box operators such as map()
2) Abuse flatMap `.flatMap(event -> just(event).compose(..).onErrorResumeWith(exception -> handleException(event, exception))`

**Comment by smaldini** [comment]
@akarnokd any thoughts ?

**Comment by akarnokd** [comment]
You could have a stacktrace-less exception class holding onto the exception value
and added as a suppressed exception to the actual exception.

**Comment by dfeist** [comment]
@akarnokd Me and @smaldini discussed that approach as an alternative, which actually used to exist in reactor but was removed.  The problem with that approach is that it's implicit/automatic which can cause issues if there is IO involved and/or if the user is not expecting the value to be held onto. Also to use the value you need a `doOnErrorValue` operator which IMO is rather unnatural.  Allowing exceptions to be intercepted solves this problem in a clearer, more explicit, user defined way but is also adds more optional flexibility to error handling in general. 

@smaldini Even if this the approach i suggest isn't taken I think it's pretty important to provide some way for users to get hold of the error value easily, so i'd say this is more than just a question.

**Comment by smaldini** [comment]
I think it's still worth considering, maybe not for M4 but we have a similar thing for Logger (LoggerExtension) and Schedulers (setComputationFactory)

**Comment by dfeist** [comment]
@smaldini There might be another approach, perhaps we can brainstorm it a bit more, but this pretty important for me. 

The main goal with this issue is not to have to do the following which i see as unideal, as the use of flatMap here is not ideal and impacts stream complexity and performance :-(

`flux.flatMap(event -> just(event).compose(..).mapError(ex -> new ProcessingException(ex, event)).`
