### ISSUE TITLE
Provide a way to deal with incorrect usage of blocking methods like get() in TestSubscriber

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor-core#90]
Feedback from @dsyer during Spring I/O 2016

**Comment by akarnokd** [comment]
Do you have an example of such bad usage?

**Comment by sdeleuze** [comment]
Being able to assert that the user has written `flux.flatMap(value -> methodReturningMono(value))` and not `flux.map(value -> methodReturningMono(value).get())`.

**Comment by smaldini** [comment]
This kind of advanced introspection will need a completion of the introspection support to navigate the stack. E.g. an introspection mode where Mono#get record the origin stack to see if enclosed in any reactor.core.publisher stack.

**Comment by smaldini** [comment]
We should probably be able to decorate WaitStrategy now for this kind of detection.

**Comment by sdeleuze** [comment]
The new `block()` method name is enough to avoid unexpected blocking call IMO, so I close this issue.
