### ISSUE TITLE
Computational flow graph in reactor 3.0

### ISSUE THREAD

**Issue by lokardy** [reactor/reactor-core#904]
Hi,
        Is there any computation flow  graph which is readily available for reactor 3.0. I was just scrolling through few of the old issues and found below issue

https://github.com/reactor/reactor/issues/410

is there any solution at this point of time?

**Comment by simonbasle** [comment]
I don't think the discussion in that old issue is still very relevant, is it? Use of the `Flux` API is akin to laying out the computational flow graph, and if you want to programmatically (reflectively) find it on any given `Flux` you can attempt to do it through the `Scannable` interface, eg. using `Scannable.from(myFluxInstance).parents()`.

**Comment by lokardy** [comment]
Thanks for the reply @simonbasle. Unfortunately there is very little documentation around scannable interface so it would be of great help of you can point me to the right documentation link. I am looking at how we can form a direct a cyclic graph.

**Comment by simonbasle** [comment]
closing, this was never addressed but not currently something we can prioritize
