### ISSUE TITLE
Use MpscQueue when possible to avoid synchronization

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-core#914]
We could drop some explicit synchronization locking in a few places by inlining a simplified producer/consumer index based MpscQueue from JCTools.

**Comment by OlegDokuka** [comment]
does sbdy work on that?

**Comment by simonbasle** [comment]
> does sbdy work on that?
Haven't started yet, no. But I think @smaldini wanted to tackle it / had specifics in mind since he didn't provide more details

**Comment by OlegDokuka** [comment]
Alrighty, I will ask him about that :)

**Comment by simonbasle** [comment]
now that the MPSC queue is in (#1010), this can be worked on for the release after 3.1.3. Removing the milestone for now.
