### ISSUE TITLE
Use CompletableFuture instead of raw Future

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor-core#92]
Since raw `Future` are async but blocking, and since we we have already deprecated `fromFuture(Future future`) because this is a trap, my proposal is to merge `Mono.fromFuture(Future future)` and `Mono.fromCompletableFuture(CompletableFuture future)` into a single `Mono.fromFuture(CompletableFuture future)` + renaming `CompletableFuture Mono.toCompletableFuture()` to `CompletableFuture Mono.toFuture()`.

That would reduce the API surface, avoid people to write blocking code, and would take advantage from the fact that Reactor is now Java 8+.

**Comment by raymondhjm** [comment]
> merge `Mono.fromFuture(Future future)` and `Mono.fromCompletableFuture(CompletableFuture future)` into a single `Mono.fromFuture(CompletableFuture future)` + renaming `CompletableFuture Mono.toCompletableFuture()` to `CompletableFuture Mono.toFuture()`

This is a breaking change, as `Mono.fromFuture(CompletableFuture future)` is compatible with `Mono.fromFuture(Future future)` that will change code from blocking to non-blocking.

However, I think that's worth doing, we should instruct to make code flow as async as much as possible.

**Comment by sdeleuze** [comment]
@smaldini Coul you have a look to [this PR](https://github.com/reactor/reactor-core/pull/96)?

**Comment by smaldini** [comment]
Merged
