### ISSUE TITLE
Inconsistent API Documentation for Schedulers

### ISSUE THREAD

**Issue by johannes-gehrs** [reactor/reactor-core#935]
### Expected behavior
Documentation for `Schedulers.elastic()` should be consistent.

### Actual behavior
The [documentation mentions](https://projectreactor.io/docs/core/snapshot/api/reactor/core/scheduler/Schedulers.html) that

> other factories like elastic() return a shared instance, that is the one used by operators requiring that flavor as their default Scheduler.

However, the actual method docs for `elastic()` state that it returns

> a new Scheduler that hosts a fixed pool of single-threaded ExecutorService-based workers and is suited for parallel work

This appears to be contradictory or at least unclear. Either the method returns a new Scheduler or a shared instance.

### Steps to reproduce
n/a

### Reactor Core version
Latest Snapshot and 3.1.1 Release.

### JVM version (e.g. `java -version`)
n/a

### OS version (e.g. `uname -a`)
n/a

**Comment by simonbasle** [comment]
the methods that don't have a `new` prefix indeed return a shared instance, so it looks like the javadoc is misleading
