### ISSUE TITLE
Computations.parallel() gums up after first request

### ISSUE THREAD

**Issue by dsyer** [reactor/reactor-core#94]
If I do this:

```
    private ExecutorService scheduler = Executors.newFixedThreadPool(4);

    @RequestMapping("/parallel")
    public Mono<Result> parallel() {
        log.info("Handling /parallel");
        return Flux.range(1, 10) // <1>
                .log() //
                .flatMap( // <2>
                        value -> Mono.fromCallable(() -> block(value)) // <3>
                                .subscribeOn(scheduler), // <4>
                        4) // <5>
                .collect(Result::new, Result::add) // <6>
                .doOnSuccess(result -> {
                    result.stop(); // <7>
                });
    private ExecutorService scheduler = Executors.newFixedThreadPool(4);

    @RequestMapping("/parallel")
    public Mono<Result> parallel() {
        log.info("Handling /parallel");
        return Flux.range(1, 10) // <1>
                .log() //
                .flatMap( // <2>
                        value -> Mono.fromCallable(() -> block(value)) // <3>
                                .subscribeOn(scheduler), // <4>
                        4) // <5>
                .collect(Result::new, Result::add) // <6>
                .doOnSuccess(result -> {
                    result.stop(); // <7>
                });
    }
```

it's fine, but slow. Replacing `Executors.newFixedThreadPool(4)` with `Computations.parallel()` causes the app to freeze (HTTP connections all time out) on second and subsequent requests. Creating a new `Computations.parallel()` per request and calling `shutdown()` in the `doOnSuccess()` is fine too, and faster. I want the faster, without the fuss of calling `shutdown()` if possible.

**Comment by dsyer** [comment]
Here's a thread dump while the client is timing out:

[threads0.txt](https://github.com/reactor/reactor-core/files/286476/threads0.txt)

The request has actually been through the `Flux` chain (I see logs from all items plus the `onComplete()`), so I don't know why it is stuck.

**Comment by smaldini** [comment]
Unexpected Configuration error where scheduler is prematurely shutdown before further requests (autoShutdown on completion/cancellation via ref counting).
Actually Scheduler should fail if shutdown and still used, but the immediate solution is to rework Computations into Scheduler as planned. I'll keep the other issue #93 open for reference around that rework.
