### ISSUE TITLE
how to chain together different monos ?

### ISSUE THREAD

**Issue by hank-whu** [reactor/reactor-core#941]
can mono do like this ?

val oneFuture: Future[Int] = Future{1}
val twoFuture: Future[Int] = Future{2}
val threeFuture: Future[Int] = Future {3}
val helloFuture: Future[String] = Future {" hello "}

val resultFuture: Future[String] = for {  
&nbsp;&nbsp;oneValue <- oneFuture
&nbsp;&nbsp;twoValue <- twoFuture
&nbsp;&nbsp;threeValue <- threeFuture
&nbsp;&nbsp;helloValue <- threeFuture
} yield oneValue + twoValue + threeValue + helloValue

**Comment by simonbasle** [comment]
Yes:
```java
Mono.zip(oneMono, twoMono, threeMono, helloMono)
    .map(tuple -> "" + tuple.getT1() + tuple.getT2() + tuple.getT3() + tuple.getT4())
```
(don't forget to `subscribe` to get notified of the `String` concatenation.

You can also do it with reduce if you don't want the intermediate `Tuple4`:

```java
Flux.merge(oneMono, twoMono, threeMono, helloMono)
    .reduce(() -> "", (str, v) -> str + v)
```

**Comment by hank-whu** [comment]
Thanks very much
