### ISSUE TITLE
the placement of subscribeOn does matter the behavior of code

### ISSUE THREAD

**Issue by sage417** [reactor/reactor-core#943]
### Expected behavior
no matter subscribeOn is before or after onErrorResume, it does not effect the blocking time and should always block for 1s?
### Actual behavior
as the code below, if subscribeOn is before onErrorResume, the Mono blocks 1 seconds as excepted, but if subscribeOn is after onErrorResume , the Mono blocks 10 seconds. 
### Steps to reproduce

block **1seconds**:

```java
        Mono.fromCallable(() -> {
                
                try {
                    TimeUnit.SECONDS.sleep(10L);
                } catch (InterruptedException ignore) {
                }
                return "result from plan A";
                })
                .timeout(Duration.ofSeconds(1L))
                .subscribeOn(Schedulers.elastic())
                .onErrorResume(t -> Mono.fromCallable(() -> {
                    System.out.println("plan B running on thread:" + Thread.currentThread().getName());
                    return "result from plan B";
                }))
                .block();
```

block **10seconds**:

```java
         String result = Mono.fromCallable(() -> {
                    
                    try {
                        TimeUnit.SECONDS.sleep(10L);
                    } catch (InterruptedException ignore) {}
                    return "result from plan A";
                })
                .timeout(Duration.ofSeconds(1L))
                .onErrorResume(t -> Mono.fromCallable(()->{
                    System.out.println("plan B running on thread:" + Thread.currentThread().getName());
                    return "result from plan B";
                }))
                .subscribeOn(Schedulers.elastic())
                .block();
```
### Reactor Core version
3.1.1
### JVM version (e.g. `java -version`)
1.9
### OS version (e.g. `uname -a`)
windows 10

**Comment by smaldini** [comment]
We need to investigate this but as a best practice it is often advised to run immediately subscribeOn after any blocking code as in general we will try to colocate executions paths.

**Comment by OlegDokuka** [comment]
@smaldini I will investigate it.

**Comment by akarnokd** [comment]
FYI, both RxJava 2.1.6 (using `Flowable` or `Single`) and Reactive4JavaFlow 0.1.3 (using `Esetleg` = `Mono`) pass the test. 

For some reason I couldn't discover, when the timeout happens, the fallback `Mono`'s call result only appears after the 10 second when the first source's sleep ends. As if there was no thread interruption from the `timeout` cancelling the main source; `doOnCancel` does report cancellation but there `catch InterruptedException` doesn't trigger.

**Comment by OlegDokuka** [comment]
@smaldini @akarnokd found the issue, the problem is in MonoSubscribeOn, which subscribe method looks like
``` Java
        @Override
	public void subscribe(CoreSubscriber<? super T> actual) {
		Scheduler.Worker worker = scheduler.createWorker();

		SubscribeOnSubscriber<T> parent = new SubscribeOnSubscriber<>(source,
				actual, worker);
		actual.onSubscribe(parent);

		try {
			worker.schedule(parent);
		}
		catch (RejectedExecutionException ree) {
			if (parent.s != Operators.cancelledSubscription()) {
				actual.onError(Operators.onRejectedExecution(ree, parent, null, null,
						actual.currentContext()));
			}
		}
```

and in that case `actual` is simple Operators.MonoSubscribe which do nothing with timeout cancelation 

```
@Override
		public void cancel() {
			this.state = CANCELLED;
			value = null;
		}
```

**Comment by OlegDokuka** [comment]
found another problematic place. For some reasons the next task is not executed 
```
void trySchedule(long n, Subscription s){
			try {
				 worker.schedule(() -> s.request(n));
			}
			catch (RejectedExecutionException ree) {
				if (!worker.isDisposed()) {
					actual.onError(Operators.onRejectedExecution(ree, this, null, null,
							actual.currentContext()));
				}
			}
		}
```

and if we replace `worker.schedule(() -> s.request(n));` with `request(n)` everything start working well

**Comment by simonbasle** [comment]
@OlegDokuka so with the above thread checking logic, the problem disappears? (it would make sense, I guess)

**Comment by OlegDokuka** [comment]
@smaldini @simonbasle created the PR that fix issue, please take a look :)
