### ISSUE TITLE
Performance Issue with log() operation call via SLF4J

### ISSUE THREAD

**Issue by hoswey** [reactor/reactor-core#956]
### Expected behavior
No Performace Issue
### Actual behavior
Thread block on the log
### Steps to reproduce
stress test
### Reactor Core version
3.1.1.RELEASE
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
Linux  4.4.0-57-generic 78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

please refer to issue on spring cloud gateway project[#93](https://github.com/spring-cloud/spring-cloud-gateway/issues/93)

**Comment by smaldini** [comment]
According to that issue we would probably not have an immediate solution to workaround the SLF4J getLogger method. Maybe we could open a signature of log() to accept a Logger instead of a String, wdyt @simonbasle

**Comment by simonbasle** [comment]
how about a `Consumer<String>`? But a `Logger` could be another intermediate solution, yes.

**Comment by simonbasle** [comment]
@hoswey do you have a simple to setup performance test that you could share? I'm looking into adding a `log(Logger logger, ...)` overload as an alternative to the `log(String category, ...)` one.

**Comment by simonbasle** [comment]
@hoswey I added a `log(Logger)` overload in the https://github.com/reactor/reactor-core/tree/956-logWithProvidedLogger branch. Would you be able to at least build it locally and run your performance test, see if it makes things better with a pre-instantiated `Logger`?
