### ISSUE TITLE
Add operators with dynamic duration

### ISSUE THREAD

**Issue by helmbold** [reactor/reactor-core#960]
I'm missing timing operators where the time (duration) is dynamic. Example: I want to use two alternating buffers, where one buffer starts when the other emits its value. The problem with the current implementation in this scenario is that the "buffer clocks" ticks whether the buffer is currently in charge or not. I could use `buffer(Publisher<?> other)` and push some timing event in the chain. To do this the following operator would be useful:

```Java
Flux<Long> timer(Flux<Duration> time)
```

This operator should emit a long after the `time` has elapsed. This is much like [`interval`](http://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#interval-java.time.Duration-) but the `time`  would be dynamic in this case.

My specific scenario would be even simpler if I could set the duration via a publisher, where a new buffer should begin when the duration gets changed:

```Java
Flux<List<T>> buffer(Flux<Duration> duration)
```

**Comment by simonbasle** [comment]
What would the source of the durations be? Maybe combining a `Processor`, `Flux.interval` and `Flux.switchOnNext` would work for you? See the following snippet:

```java
EmitterProcessor<Duration> durationSource = EmitterProcessor.create();
		Flux<Long> ticks = Flux.switchOnNext(durationSource.map(Flux::interval));
		Flux<List<Long>> test = Flux.interval(Duration.ofMillis(100))
		                            .take(10)
		                            .buffer(ticks);
```

**Comment by helmbold** [comment]
The actual requirement is somewhat more complicated. I have a stream with boolean values signaling errors or the absence thereof, so `true` means "error occurred" and `false` means "ok".  To avoid false alarms an error should only be pushed downstream if it occurred continually for a certain time (lets call it `preBufferTime`). If an error was signaled there must be only "ok" message (`false`) for another certain time (`postBufferTime`), before the "ok" message is pushed downstream, this again is to avoid early messages.

The stream of messages (t = true, f = false) can be visualized like this: 

```     
tfttfttttttftftfffff
     ---       -----
       | switch    | switch to pre buffer
       | buffer    | 
       |           |
       t           f
       (alarm)     (all-clear)
```

The `preBufferTime` is 3 seconds and the `postBufferTime` is 5 seconds in my example. The dashed line (`---`) shows the relevant window leading to an event being pushed downstream. 

Both buffers should emit mutual exclusive, so that after emitting a value the other buffer should become active and the emitting buffer should not emit until the buffer comes active again. What makes the scenario even more complicated is that one or both buffer times could be 0. Both buffers could potentially be a single buffer. 

I tried to solve this with setting the appropriate time (`preBufferTime` or `postBufferTime`) on my timer flux and let it close the buffer when this time elapsed. After each buffer switch (pre to post or vice versa) the timer is set again. This does however not solve the problem with a buffer time of 0 and a sliding window is still not possible. So I would actually need a variant of the initially suggested operator:

```Java
Flux<List<T>> buffer(Flux<Duration> duration, Flux<Duration> timeshift)
```
In the end it is a dynamically configurable Flux, a bit like an Actor in Akka.

I don't see any (reasonably elegant) possibility to implement this scenario with the current set of operators.

**Comment by helmbold** [comment]
Finally I solved this specific scenario by combining two buffers and filtering, so that only one buffer emits determined by a toggled `AtomicBoolean`.

The problem with the method suggested above 
```Java
Flux<List<T>> buffer(Flux<Duration> duration, Flux<Duration> timeshift)
```
would be that a buffer could start before the buffer switching and emit its value after the switching what would be invalid in my case. To avoid this, one would need to "reschedule" the buffer closing event what is not possible.

Alternating buffer times could be achieved with `bufferWhen` and a publisher that delivers a `Mono.delay(x)` or `Mono.delay(y)` alternately, so for this scenario no other method is needed (although it wasn't the solution in my case).

If you don't find the probably more universal `timer` method useful, I think that we can close the ticket.

**Comment by simonbasle** [comment]
ok, glad you found a way to achieve your goal 👍
