### ISSUE TITLE
Question | Store the Disposable when subscribed to a Mono in database

### ISSUE THREAD

**Issue by vivekaditya** [reactor/reactor-core#978]
### Question
I am currently exploring the [reactor-core][1]. I am able to subscribe to a Mono and also save the disposable to handle the execution of the subscriber.

    Mono<Object> task1 = Mono.just("Task1");
    Mono<Object> task2 = Mono.just("Task2");
    System.out.println(System.currentTimeMillis());
    HashMap<Mono,Disposable> taskHandlerMap = new HashMap<>();
    Disposable task1Handler = task1.delayElement(Duration.ofSeconds(5)).subscribe(
    (Object x)->{
            System.out.println(x.toString() + "\t" + System.currentTimeMillis());
    });
    taskHandlerMap.put(task1,task1Handler);
    Disposable task2Handler = task2.delayElement(Duration.ofSeconds(10)).subscribe(
    (Object x)->{
            System.out.println(x.toString() + "\t" + System.currentTimeMillis());
    });
    taskHandlerMap.put(task2,task2Handler);

I am able to dispose a scheduled task by using the handler map as follows.

    taskHandlerMap.get(task2).dispose();

Can I save this taskHandlerMap in a database? Is yes, how can I save it. Else is there a better way to store the disposable created at subscription. I have raised the same question on [SO](https://stackoverflow.com/questions/47692305/store-the-disposable-when-subscribed-to-a-mono-in-database). Apologies, If you monitor both the things.
  [1]: https://projectreactor.io
### Reactor Core version
3.1.2.RELEASE
### JVM version (e.g. `java -version`)
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
### OS version (e.g. `uname -a`)
Darwin localhost 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

**Comment by simonbasle** [comment]
(answered on SO as well)

a `Disposable` is merely a reference to a live computation, and it makes no sense to try and save it and restore it to/from a database.

It is kind of like if you submitted an long HTTP call to an `ExecutorService` and expected to be able to save the `Future` to the DB and somehow restore it... If the application stops, the HTTP call is gone anyway. If the application keeps on running, there's no need to keep the `Future` in a DB (you'd keep it in memory, with the same lifespan as the HTTP call).
