### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor-core#98]
It would be nice to check what is needed to make `reactor-core` running on Android since Google recently announced [Java 8 support on ](https://developer.android.com/preview/j8-jack.html). It seems to me that this is supported as of Android Gingerbread (to be checked).

The fist goal of this issue is to identify what are the blocking point to run Reactor 2.5 on Android (class not available, etc.)

If somebody has the time to experiment with that that would be awesome.

**Comment by arnaudgiuliani** [comment]
Hello Sébastien, I have a good App using RxJava. I can take some times to check about reactor.

**Comment by sdeleuze** [comment]
@arnaudgiuliani Thanks! Please notice that we have not check yet so I guess there will be some classes not available et various issues, the current step is to identify the blocking point in order to evaluate what need to be done to run Reactor 2.5 on Android. Any feedback welcome.

**Comment by arnaudgiuliani** [comment]
@sdeleuze Ok, I'll tell you what I see.

**Comment by arnaudgiuliani** [comment]
@sdeleuze I've made a simple test with android N & reactor (followed the android N/java 8 project guide https://developer.android.com/preview/setup-sdk.html#next). You can check the project here : https://github.com/Ekito/reactor-droid

I've got the following compile errors :
[output.txt](https://github.com/reactor/reactor-core/files/311537/output.txt)

**Comment by sdeleuze** [comment]
Thanks a lot for the project, I am going to have a deeper look.

**Comment by arnaudgiuliani** [comment]
Ok. One thing to keep in mind : Android N is still in preview and the deployment will start at the end of this year. With such target, we can't cover a large amount of target (perhaps a kotlin module can help adopt it faster).

Also keep on eye on RxAndroid. There's some custom stuff like Schedulers, that have better mapping to android platform (target the main thread ...)

**Comment by sdeleuze** [comment]
@arnaudgiuliani It seems Java 8 support will work as of Android 2.3 (Gingerbread) even if we need to check that. And yes, we plan to create dedicated schedulers.

**Comment by akarnokd** [comment]
I was unable to get Jack working properly. This scheduler compiles inside the studio but won't run on an emulator because Java 8 libraries are not yet supported by Jack.

```java
package reactor.android;

import android.os.Handler;
import android.os.Looper;
import android.os.Message;

import java.util.concurrent.TimeUnit;

import reactor.core.flow.Cancellation;
import reactor.core.scheduler.TimedScheduler;

/**
 * Android Scheduler.
 */
public final class AndroidScheduler implements TimedScheduler {

    final Handler handler;

    static final AndroidScheduler MAIN_THREAD = new AndroidScheduler(Looper.getMainLooper());

    public static AndroidScheduler mainThread() {
        return MAIN_THREAD;
    }

    public AndroidScheduler(Handler handler) {
        this.handler = handler;
    }

    public AndroidScheduler(Looper looper) {
        this.handler = new Handler(looper);
    }

    @Override
    public Cancellation schedule(final Runnable task, long delay, TimeUnit unit) {

        handler.postDelayed(task, unit.toMillis(delay));

        return new Cancellation() {
            @Override
            public void dispose() {
                handler.removeCallbacks(task);
            }
        };
    }

    @Override
    public Cancellation schedulePeriodically(Runnable task, long initialDelay, long period, TimeUnit unit) {
        long nowMillis = now(TimeUnit.MILLISECONDS);
        long initialMillis = unit.toMillis(initialDelay);

        final PeriodicDirectTask pt = new PeriodicDirectTask(task, this, nowMillis + initialMillis, unit.toMillis(period));

        Message message = Message.obtain(handler, pt);
        message.obj = this; // mass cancellation token

        handler.sendMessageDelayed(message, initialMillis);

        return new Cancellation() {
            @Override
            public void dispose() {
                handler.removeCallbacks(pt);
            }
        };
    }

    @Override
    public Cancellation schedule(final Runnable task) {
        handler.post(task);

        return new Cancellation() {
            @Override
            public void dispose() {
                handler.removeCallbacks(task);
            }
        };
    }


    @Override
    public long now(TimeUnit unit) {
        return unit.convert(System.currentTimeMillis(), TimeUnit.MILLISECONDS);
    }

    @Override
    public TimedWorker createWorker() {
        return new AndroidWorker(handler);
    }

    static final class AndroidWorker implements TimedWorker {

        final Handler handler;

        volatile boolean shutdown;

        public AndroidWorker(Handler handler) {
            this.handler = handler;
        }

        @Override
        public Cancellation schedule(final Runnable task, long delay, TimeUnit unit) {
            if (shutdown) {
                return REJECTED;
            }

            Message message = Message.obtain(handler, task);
            message.obj = this; // Used as token for unsubscription operation.

            handler.sendMessageDelayed(message, unit.toMillis(delay));

            if (shutdown) {
                handler.removeCallbacks(task);
                return REJECTED;
            }

            return new Cancellation() {
                @Override
                public void dispose() {
                    handler.removeCallbacks(task);
                }
            };
        }

        @Override
        public Cancellation schedulePeriodically(Runnable task, long initialDelay, long period, TimeUnit unit) {
            if (shutdown) {
                return REJECTED;
            }

            long nowMillis = now(TimeUnit.MILLISECONDS);
            long initialMillis = unit.toMillis(initialDelay);

            final PeriodicTask pt = new PeriodicTask(task, this, nowMillis + initialMillis, unit.toMillis(period));

            Message message = Message.obtain(handler, pt);
            message.obj = this; // mass cancellation token

            handler.sendMessageDelayed(message, initialMillis);

            if (shutdown) {
                handler.removeCallbacks(pt);
                return REJECTED;
            }

            return new Cancellation() {
                @Override
                public void dispose() {
                    handler.removeCallbacks(pt);
                }
            };
        }

        @Override
        public Cancellation schedule(final Runnable task) {
            if (shutdown) {
                return REJECTED;
            }

            Message message = Message.obtain(handler, task);
            message.obj = this; // mass cancellation token

            handler.sendMessage(message);

            if (shutdown) {
                handler.removeCallbacks(task);
                return REJECTED;
            }

            return new Cancellation() {
                @Override
                public void dispose() {
                    handler.removeCallbacks(task);
                }
            };
        }

        @Override
        public void shutdown() {
            shutdown = true;
            handler.removeCallbacksAndMessages(this);
        }

        @Override
        public long now(TimeUnit unit) {
            return unit.convert(System.currentTimeMillis(), TimeUnit.MILLISECONDS);
        }

        static final class PeriodicTask implements Runnable, Cancellation {
            final Runnable task;

            final AndroidWorker worker;

            final long start;

            final long period;

            long count;

            volatile boolean cancelled;

            public PeriodicTask(Runnable task, AndroidWorker worker, long start, long period) {
                this.task = task;
                this.worker = worker;
                this.start = start;
                this.period = period;
            }

            @Override
            public void run() {
                if (cancelled || worker.shutdown) {
                    return;
                }

                task.run();

                if (cancelled || worker.shutdown) {
                    return;
                }

                long next = start + (++count) * period;
                long now = worker.now(TimeUnit.MILLISECONDS);

                long delta = next - now;

                Handler handler = worker.handler;

                Message message = Message.obtain(handler, this);
                message.obj = worker; // mass cancellation token

                if (delta <= 0L) {
                    handler.sendMessage(message);
                } else {
                    handler.sendMessageDelayed(message, delta);
                }

                if (cancelled || worker.shutdown) {
                    handler.removeCallbacks(this);
                    return;
                }
            }


            @Override
            public void dispose() {
                cancelled = true;
                worker.handler.removeCallbacks(this);
            }
        }
    }

    static final class PeriodicDirectTask implements Runnable, Cancellation {
        final Runnable task;

        final AndroidScheduler worker;

        final long start;

        final long period;

        long count;

        volatile boolean cancelled;

        public PeriodicDirectTask(Runnable task, AndroidScheduler worker, long start, long period) {
            this.task = task;
            this.worker = worker;
            this.start = start;
            this.period = period;
        }

        @Override
        public void run() {
            if (cancelled) {
                return;
            }

            task.run();

            if (cancelled) {
                return;
            }

            long next = start + (++count) * period;
            long now = worker.now(TimeUnit.MILLISECONDS);

            long delta = next - now;

            Handler handler = worker.handler;

            Message message = Message.obtain(handler, this);
            message.obj = worker; // mass cancellation token

            if (delta <= 0L) {
                handler.sendMessage(message);
            } else {
                handler.sendMessageDelayed(message, delta);
            }

            if (cancelled) {
                handler.removeCallbacks(this);
                return;
            }
        }


        @Override
        public void dispose() {
            cancelled = true;
            worker.handler.removeCallbacks(this);
        }
    }
}
```

**Comment by sdeleuze** [comment]
On my side, good news I got it compiling properly with Gradle after installing manually Android build tools `24.0.0 rc4` and modifying the build config [like that](https://github.com/sdeleuze/reactor-droid/commit/07d03a9a8512f2be5aedd5d129da087b2cea910f).

**Comment by akarnokd** [comment]
Thanks, with some [extra setup](http://stackoverflow.com/a/37709840/61158), I got that almost working. Now it complains that `java.time.Duration` on `Flux` can't be found, despite I've set up JDK 8u92 (both in the IDE and when built). I can reference `java.util.function.Function` all right.

**Comment by sdeleuze** [comment]
@akarnokd Can you show me your Gradle output with the `java.time.Duration` error in order to allow me to compare with mine?

**Comment by akarnokd** [comment]
[Sure](https://gist.github.com/akarnokd/7d39911de24457961acb6265ac88d538)

I'm using the latest official Android Studio btw. Maybe you are using a preview build of the studio? It appears mine won't recognize many Java 8 classes.

**Comment by sdeleuze** [comment]
Ok, I got the same error when I use `Flux.interval()`, but it works if I use `Flux.just()` for example. Maybe we should provide a backport of `java.time.Duration` with `reactor-android` to make it work since [this API is not provided with Android support for Java 8](https://developer.android.com/preview/j8-jack.html)?

**Comment by sdeleuze** [comment]
I have asked to those who may know ^^ https://twitter.com/sdeleuze/status/742653519673561088

**Comment by mp911de** [comment]
Obtaining the `Unsafe` in `reactor.core.util.PlatformDependent` ​_could_​ fail on [older Android versions](https://android.googlesource.com/platform/libcore/+/09bcea1fd2a0bade07ab034352fde6c6ff6e01a6%5E%21/#F0). Obtaining the private constructor, making it accessible and creating an own instance works across all Java VM’s.

**Comment by sdeleuze** [comment]
Response from Jake Wharton about how to support `java.time.Duration`:
> The JSR 310 types are not available in the current preview. Hopefully they'll be included in the next ones, though

**Comment by JakeWharton** [comment]
There's an issue filed for `java.time.*`'s inclusion into the platform: http://b.android.com/203281. Star it if you like.

It's worth noting that Android N preview 4 was released yesterday which is documented as having the final APIs that will ship in N and it lacks `java.time`. This means that in all likelihood these APIs will not be in N and instead will be in M. The platform team is very aware of people's interest in `java.time` so it definitely will get there eventually, but it looks like it will miss this release.

**Comment by akarnokd** [comment]
I've updated to 24 and a small test code works on the device if I don't get near the `Duration` methods.

**Comment by JakeWharton** [comment]
> It seems to me that this is supported as of Android Gingerbread 

Few language features are supported this far back. The ones are: lambdas, method references, and repeated annotations, and those are all supported by having the compiler rewrite them into compatible implementations (anonymous classes and wrapper annotations, respectively).

The platform APIs, however, like `java.util.function` and `java.util.stream` will only work on devices actually running Android N or newer.

**Comment by sdeleuze** [comment]
Since we are not using `java.time.Duration` internally and since that users can easily call [`Duration#toMillis()`](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#toMillis--), I would like to try the following as an experiment:
- Remove the overloaded methods based on `java.time.Duration` from the API
- Test if Reactor works in Gingerbread using [streamsupport](https://github.com/streamsupport/streamsupport) backport + eventually other polyfills for missing classes

That's important to have a better idea of what we can acheive in term of Android support before RC1, since that could eventually impact the API.

**Comment by smaldini** [comment]
@JakeWharton quick question, does it support Java 8 Concurrent Map too ?

**Comment by JakeWharton** [comment]
`ConcurrentMap` itself didn't change in Java 8 as far as I can tell but `Map` did. And it looks like Android got all of those new methods: https://developer.android.com/reference/java/util/concurrent/ConcurrentMap.html (ensure API level is set to 24 in the upper-left).

**Comment by sdeleuze** [comment]
The result of my tests is that Reactor can work on Android Nougat, at least with the tests I did on my fork of [reactor-droid](https://github.com/sdeleuze/reactor-droid), with this [pull request](https://github.com/reactor/reactor-core/pull/115) that uses different method names from `Duration` and `long` based time periods.

I also did a try with previous versions, but while they can support some Java 8 features, default methods are not supported.

```
:app:compileDebugJavaWithJack
ERROR: Default method long upstreamCount() not supported in Android API level less than 24
ERROR: Default method long now(java.util.concurrent.TimeUnit -p_1_Ljava_util_concurrent_TimeUnit_) not supported in Android API level less than 24
ERROR: Default method boolean isCancelled() not supported in Android API level less than 24
ERROR: Default method long downstreamCount() not supported in Android API level less than 24
ERROR: Default method boolean hasDownstreams() not supported in Android API level less than 24
ERROR: Default method long getCapacity() not supported in Android API level less than 24
ERROR: Default method long getPending() not supported in Android API level less than 24
ERROR: Default method boolean add(java.lang.Object -p_1_Ljava_lang_Object_) not supported in Android API level less than 24
ERROR: Default method java.lang.Object peek() not supported in Android API level less than 24
ERROR: Default method boolean offer(java.lang.Object -p_1_Ljava_lang_Object_) not supported in Android API level less than 24
ERROR: Default method java.lang.Object remove() not supported in Android API level less than 24
ERROR: Default method java.lang.Object element() not supported in Android API level less than 24
ERROR: Default method java.util.Iterator iterator() not supported in Android API level less than 24
ERROR: Default method java.lang.Object[] toArray() not supported in Android API level less than 24
ERROR: Default method java.lang.Object[] toArray(java.lang.Object[] -p_1__Ljava_lang_Object_) not supported in Android API level less than 24
ERROR: Default method boolean remove(java.lang.Object -p_1_Ljava_lang_Object_) not supported in Android API level less than 24
ERROR: Default method boolean containsAll(java.util.Collection -p_1_Ljava_util_Collection_) not supported in Android API level less than 24
ERROR: Default method boolean addAll(java.util.Collection -p_1_Ljava_util_Collection_) not supported in Android API level less than 24
ERROR: Default method boolean removeAll(java.util.Collection -p_1_Ljava_util_Collection_) not supported in Android API level less than 24
ERROR: Default method boolean retainAll(java.util.Collection -p_1_Ljava_util_Collection_) not supported in Android API level less than 24
ERROR: Default method boolean contains(java.lang.Object -p_1_Ljava_lang_Object_) not supported in Android API level less than 24
ERROR: Default method void shutdown() not supported in Android API level less than 24
ERROR: Default method void start() not supported in Android API level less than 24
ERROR: Default method java.lang.Object getId() not supported in Android API level less than 24
ERROR: Default method java.lang.String getName() not supported in Android API level less than 24
ERROR: Default method int getMode() not supported in Android API level less than 24
ERROR: Default method long getPeriod() not supported in Android API level less than 24
ERROR: Default method java.lang.Throwable getError() not supported in Android API level less than 24
ERROR: Default method void onSubscribe(org.reactivestreams.Subscription -p_1_Lorg_reactivestreams_Subscription_) not supported in Android API level less than 24
ERROR: Default method void onError(java.lang.Throwable -p_1_Ljava_lang_Throwable_) not supported in Android API level less than 24
ERROR: Default method void onComplete() not supported in Android API level less than 24
ERROR: Default method reactor.core.subscriber.BaseSubscriber connect() not supported in Android API level less than 24
ERROR: Default method reactor.core.subscriber.SubmissionEmitter connectEmitter() not supported in Android API level less than 24
ERROR: Default method reactor.core.subscriber.SubmissionEmitter connectEmitter(boolean -p_1_Z) not supported in Android API level less than 24
ERROR: Default method void onNext(java.lang.Object -p_1_Ljava_lang_Object_) not supported in Android API level less than 24
ERROR: Default method long now(java.util.concurrent.TimeUnit -p_1_Ljava_util_concurrent_TimeUnit_) not supported in Android API level less than 24
ERROR: Default method boolean isStarted() not supported in Android API level less than 24
ERROR: Default method boolean isTerminated() not supported in Android API level less than 24
ERROR: Default method int requestFusion(int -p_1_I) not supported in Android API level less than 24
ERROR: Default method java.lang.Object connectedInput() not supported in Android API level less than 24
ERROR: Default method java.lang.Object connectedOutput() not supported in Android API level less than 24

com.android.jack.api.v01.CompilationException
        at com.android.jack.api.v01.impl.Api01ConfigImpl$Api01CompilationTaskImpl.run(Api01ConfigImpl.java:113)
        at com.android.builder.core.AndroidBuilder.convertByteCodeUsingJackApis(AndroidBuilder.java:1931)
        at com.android.build.gradle.tasks.JackTask.doMinification(JackTask.java:148)
        at com.android.build.gradle.tasks.JackTask.access$000(JackTask.java:73)
        at com.android.build.gradle.tasks.JackTask$1.run(JackTask.java:112)
        at com.android.builder.tasks.Job.runTask(Job.java:51)
        at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:223)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.jack.JackAbortException
        at com.android.jack.abort.Aborter.run(Aborter.java:35)
        at com.android.jack.abort.Aborter.run(Aborter.java:29)
        at com.android.sched.scheduler.ScheduleInstance.runWithLog(ScheduleInstance.java:203)
        at com.android.sched.scheduler.MultiWorkersScheduleInstance$SequentialTask.process(MultiWorkersScheduleInstance.java:466)
        at com.android.sched.scheduler.MultiWorkersScheduleInstance$Worker.run(MultiWorkersScheduleInstance.java:163)
Warning: Exception while processing task java.io.IOException: com.android.jack.api.v01.CompilationException
:app:compileDebugJavaWithJack FAILED
```

@smaldini I am wondering if we should perform some tests without default methods to see if there are other errors, or if we stick to Android Nougat compat (by merging the PR I created) since default methods are mandatory for Reactor API. Any thoughts?

**Comment by JakeWharton** [comment]
You might want to try Retrolambda which can backport default methods when
doing full compilation (i.e., when incremental compilation is disabled). It
slows down your build, but it should effectively support all Android
versions.

**Comment by sdeleuze** [comment]
Oh thanks, I will try that.

**Comment by sdeleuze** [comment]
Sounds like Gradle Retrolambda plugin does not work with Jack & Jill yet, see https://github.com/evant/gradle-retrolambda/issues/71!

**Comment by sdeleuze** [comment]
I am going to see what going on if we remove defaults methods (I mean is there other blocking points or not).

**Comment by JakeWharton** [comment]
Yes it doesn't work with Jack. You use JDK 8's javac and it rewrites the
bytecode to be compatible with Java 6 which the dex tool can process.

**Comment by sdeleuze** [comment]
The result of my experiment of removing [all default methods](https://github.com/sdeleuze/reactor-core/tree/android) from `reactor-core` and trying to get it running on Android API 23 is that it makes it possible to compile, but leads to other blocking errors.

As soon as we target API 23, `java.util.function.*` classes are not available anymore and [streamsupport](https://github.com/streamsupport/streamsupport) backport, like [threetenbp](https://github.com/ThreeTen/threetenbp), can't be used as a dropin replacement because it does not use the same packages.

As a consequence, I think with some refinement (dedicate schedulers) we can target Android Nougat (API 24+) with `reactor-core`, but not previous versions.

**Comment by smaldini** [comment]
I think we can close that issue for now and we will request help for backporting via rewriting script a specific reactor-core-android.jar. Especially we can also merge RS for such jar inside it. Please re-open if you think otherwise.
Thanks everyone for your support on this and thorough investigation,  we have at least all the necessary base to continue working

**Comment by tia-ru** [comment]
One of the most common operations when dealing with asynchronous tasks on Android is to observe the task's result or outcome on the Android application main thread. Ractor core does not provides a scheduler to observe on main thread. There is external library with such scheduler:
https://github.com/tia-ru/reactor-android-scheduler
