### ISSUE TITLE
settings `-Dreactor.trace.operatorStacktrace=true` obtain `NullPointerException`

### ISSUE THREAD

**Issue by kevin70** [reactor/reactor-core#985]
### Expected behavior
Success

### Actual behavior
```
Caused by: java.lang.NullPointerException
	at reactor.core.publisher.Hooks.onEachOperator(Hooks.java:100)
	at reactor.core.publisher.Hooks.onEachOperator(Hooks.java:69)
	at reactor.core.publisher.Hooks.<clinit>(Hooks.java:476)
```

### Steps to reproduce
1. `Mono.just("hello").subscribe()`
2. settings `-Dreactor.trace.operatorStacktrace=true`
3. Running programs

### Reactor Core version
`reactor-core:3.1.2.RELEASE`

### JVM version (e.g. `java -version`)
`jdk1.8.0_121`

### OS version (e.g. `uname -a`)
`Windows`

Initialization of variable order problems
[Hooks.java#L471](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/Hooks.java#L471)

[Hooks.java#L516](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/Hooks.java#L516)

Initialization `globalTrace`  `log` The instance has not been created yet, cause `NullPointerException`

**Comment by simonbasle** [comment]
Issue in Chinese, yeah sure 🤔
Can you translate that in full into English please @kevin70? Otherwise I will close.

**Comment by kevin70** [comment]
@simonbasle ok
