### ISSUE TITLE
EventLoopProcessor#awaitAndShutdown(long, java.util.concurrent.TimeUnit) should use Duration.

### ISSUE THREAD

**Issue by dfeist** [reactor/reactor-core#986]
### Expected behaviour

EventLoopProcessor#awaitAndShutdown(Duration duration)

### Actual behaviour

EventLoopProcessor#awaitAndShutdown(long, java.util.concurrent.TimeUnit)

**Comment by simonbasle** [comment]
We can introduce a `Duration` based method and maybe deprecate the old `long + TimeUnit` one... 

The `Duration` should probably be passed to the external `ExecutorService#awaitTermination` by converting it to nanosecond resolution? (that amounts to a maximum timeout of 292 years, which should be fine 😆)
