### ISSUE TITLE
'delayElements' behavior not so intuitive

### ISSUE THREAD

**Issue by matgabriel** [reactor/reactor-core#989]
I just migrated some code from RxJava 2 to Reactor, and got a bit surprised by the behavior of the 'delayElements' method.
From its name I assumed that it would have the same behavior as the 'delay' method in Rx: apply a delay to each element, regardless of the timing of the previous element, while according to the marble diagram, it acts more like a rate limiter in reactor.

Is there any recommended way to have the same behavior as the 'delay' from Rx with Flux operators?

**Comment by simonbasle** [comment]
The marble diagram is actually misleading: it does indeed apply a delay to each element, so the marbles in that source flux should appear on the bottom arrow with a simple translation.

Consider this test:
```java
Flux<Tuple2<Instant, String>> delays = Flux.concat(
				Mono.delay(Duration.ofMillis(1000)).then(Mono.just("A1")),
				Mono.delay(Duration.ofMillis(3000)).then(Mono.just("B3")),
				Mono.delay(Duration.ofMillis(2000)).then(Mono.just("C2"))
		)
               .map(v -> Tuples.of(Instant.now(), v))
               .doOnNext(v -> System.out.println("source: " + v));

		delays.delayElements(Duration.ofSeconds(1))
		      .elapsed()
		      .map(t2 -> Tuples.of(t2.getT1() / 1000 + "s", Instant.now(), t2.getT2().getT2()))
		      .doOnNext(v -> System.out.println("delayElements: " + v))
		      .blockLast();
```

It outputs:
```
source: [2017-12-18T14:36:21.300Z,A1]
delayElements: [2s,2017-12-18T14:36:22.315Z,A1]
source: [2017-12-18T14:36:24.314Z,B3]
delayElements: [3s,2017-12-18T14:36:25.318Z,B3]
source: [2017-12-18T14:36:26.318Z,C2]
delayElements: [2s,2017-12-18T14:36:27.322Z,C2]
```
Note the first delayed value comes 1s after first source value, and compared to subscription this is 2s after _subscription_ hence the `2s` on the second row.

Other delayed values come respectively 3s after first then 2s after second, which mirrors delays that are observed between their respective source values.

**Comment by simonbasle** [comment]
@matgabriel is that what you expected? if so, the marble should probably be changed.

**Comment by matgabriel** [comment]
@simonbasle : this works if the delay is lower or equals to the time between items on the stream.

If we take this simple example:

`Flux.interval(ofMillis(500)).delayElements(ofSeconds(5)).doOnNext(System.out::println).blockLast();`

I would expect items to be emitted every 500ms after the initial 5 seconds delay, but they are in fact emitted every 5 seconds and this results in a backpressure exception which I would not expect if the source flux was simply translated with a delay, because the buffer should then have a constant size (10 elements buffered for the 5 seconds delay)

**Comment by simonbasle** [comment]
ah I see. First, know that `interval` isn't the best behaved of sources in terms of backpressure...
for such a use case however, if you want to only incur an initial delay, you should use `delaySubscription`.

**Comment by matgabriel** [comment]
What I want to achieve is a little bit different: I want to subscribe immediately, and apply a delay to each item. So if I receive items at 10 Hertz from an external system, and apply a delay of 1 second, I would expect that the output is still at 10 Hertz with the value shifted in time by 1 second, while in reality it is at 1 Hertz.
That's the difference between 'delayElements' in Flux and 'delay' in Flowable.

**Comment by simonbasle** [comment]
looks like this is an artifact of `delayElements` using `concatMap`... not sure yet if delayElements should be changed, but in the meantime you can use `flatMap`:

```java
Flux.interval(Duration.ofMillis(500))
		    .flatMap(v -> Mono.just(v).delayElement(Duration.ofSeconds(5)))
```

**Comment by matgabriel** [comment]
yes I understand that it might be risky to change the semantic of `delayElements` now as some code out there might rely on it.
The workaround it not too complicated, but I think it would be useful to have a Flux operator with the same semantic. It is a behavior I find quite useful to implement all kinds of timeout scenarios.

**Comment by simonbasle** [comment]
@matgabriel does that semantic sound right:
 - subscribes to source immediately
 - delays first element by `Duration`
 - delays subsequent elements and completion/error signals by the same duration, _as they are emitted by the source_ => unlike `delayElements` which is backed by a `concatMap`, and thus triggers the delay _once the previous element has been emitted with its own delay_
 - if a sequence has no element, immediately propagates its terminal signal (`onError`/`onComplete`)

**Comment by matgabriel** [comment]
Yes, this sounds right.

**Comment by simonbasle** [comment]
how about the name:
 - I proposed `delayFirstElement` in my PR, although technically all elements are delayed...
 - Plain `delay` would introduce confusion with the static `Mono.delay` (which is just a static method to create a single delayed tick)
 - other names that I can think of:
    - `delayFirst`
    - `delayElement`: semantics would align with the `Mono` operator of the same name, but maybe too subtle a difference between `Flux#delayElements` and `Flux#delayElement`...
    - ~`delay`~: not usable due to the misalignment with `Mono#delay`
    - `delayShift` (meh)

Any other suggestion?

**Comment by matgabriel** [comment]
I find `delayFirstElement` a bit confusing because at first sight it looks like only the first element is delayed... of course when you think a bit about it, it's obvious that the next elements also have to be delayed.

Unfortunately the best name is already taken by `delayElements`, and I cannot come up with a better name...
I also thought about something with shiftXXX, but it is better if this method stays in the delayXXX range in the javadoc.

**Comment by simonbasle** [comment]
new proposal: `delaySequence`, as this operator delays (or shifts) the _whole_ sequence.
wdyt @matgabriel @smaldini ?

**Comment by matgabriel** [comment]
I like it, I think it's much better than `delayFirstElement`
