### ISSUE TITLE
Filter by type and map Kotlin extension for Flux

### ISSUE THREAD

**Issue by dsebastien** [reactor/reactor-core#995]
Hello,

I've mistakenly created https://github.com/reactor/reactor-kotlin-extensions/issues/14 in the legacy repository, so I'll write it again here :)

In my project I've written a small extension function for Flux to easily do a filter + map operation on a user-provided type.

Without the extension:
```
val stream: Flux<Any> = ...
stream
  .filter { it is SomeType }
  .map { it as SomeType }
  .doOnNext { // "it" is of the type I care about
  }
```
With the extension:
```
val stream: Flux<Any> = ...
stream
  .filterByType<SomeType>()
  .doOnNext { // "it" is of the type I care about
  }
```
Here's the code of the function:
```
/**
 * Filter the [Flux] by the given type and map the filtered stream to that type.
 * This allows to avoid having to write code like:
 * stream
 *   .filter { it is SomeType }
 *   .map { it as SomeType }
 *   .doOnNext { ... }
 * And allows to write this instead:
 * stream
 *   .filterByType<SomeType>()
 *   .doOnNext { ... }
 *
 * @param TypeToFilterTo the type that we should filter the stream with and map to
 */
inline fun <reified TypeToFilterTo> Flux<*>.filterByType(): Flux<TypeToFilterTo> {
    return this.filter {
        it is TypeToFilterTo
    }.map {
        it as TypeToFilterTo
    }
}
```

Is this something that could be integrated in this project within https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/kotlin/reactor/core/publisher/FluxExtensions.kt ?

**Comment by OlegDokuka** [comment]
Not sure that this extension will find a place here, but you may try to add this feature to add-ons [repo](https://github.com/reactor/reactor-addons/tree/master/reactor-extra/src/main/kotlin/reactor)

**Comment by smaldini** [comment]
What about the ofType operator ?

**Comment by dsebastien** [comment]
@smaldini indeed ofType does what I wanted.
I guess this is then another case of "RTFM".

Thanks!
